### ISSUE TITLE
AAPS in landscape mode on small screen

### ISSUE THREAD

**Issue by roppenheimer** [nightscout/AndroidAPS#10]
![Screenshot_20200928-171206_AndroidAPS](https://user-images.githubusercontent.com/179086/94458746-434d2a80-01ae-11eb-9d5d-55eb6f489fc4.png)

When in landscape mode the Insulin, Carbs, Basal, Sensitivity icons use up valuable real estate meaning that there is not enough space to properly view the graphs. Could we have a landscape template which omits or moves the icons making more space available for the graphs.

**Comment by MilosKozak** [comment]
this is impossible to resolve general way. it would mean specific layout for every single resolution
