### ISSUE TITLE
[3.0beta7] In-app notification gets "stuck" sometimes

### ISSUE THREAD

**Issue by kristinsmotz** [nightscout/AndroidAPS#1000]
Have noticed some times the notification inside AAPS won't snooze when button is pressed, even when pressing multiple times. It takes an Exit from application before they disappear. Managed to catch one on screen recording, but unfortunately I don't have logs. 

https://user-images.githubusercontent.com/71758682/143861177-17b1368c-6a57-4bbb-8792-e5fd6bea5e01.mp4

.

**Comment by MilosKozak** [comment]
create new issue when you get logs

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/370b504d749924e9a1e789d0f7231e942bff335d
