### ISSUE TITLE
[3.0-beta7] Dana R stats page now empty

### ISSUE THREAD

**Issue by stefanchavdarov** [nightscout/AndroidAPS#1003]
2.8 version Dana R stats page was quite useful, now its empty with 3.0-beta7 
![viber_image_2021-11-29_23-49-11-889](https://user-images.githubusercontent.com/45970062/143949998-8c050899-1ae4-491f-b6fb-5759ef805dc5.jpg)

Log line at reloading stats from pump from attached log file:
`00:10:08.692 [Thread-81396] D/PUMPCOMM: [MsgHistoryDone.handleMessage():18]: History done received`
but onward the screen ends up empty
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/7621481/AndroidAPS.log)

Pump: Dana R
BG source: Dexcom One on xdrip native
on Android 11, Samsung A72

**Comment by MilosKozak** [comment]
did you switch to 3.0 recently?

**Comment by stefanchavdarov** [comment]
Switched to 3.0 at beta-4 and following updates ever since.. but I didnt visit pump stats page till today
I wipe db for that red triangle when new sensor start goes with xdrip g6 native, thus i assume appear empty

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/918a245ed04b8726c39d6966aa0dbb7134612177

**Comment by stefanchavdarov** [comment]
WOW thats fast
