### ISSUE TITLE
[3.0-beta7] AAPS didnt update 'x min ago' with new BG reading being same as prior one

### ISSUE THREAD

**Issue by stefanchavdarov** [nightscout/AndroidAPS#1005]
3.0-beta7 doesnt update 'x min ago' when no change in BG
Screen shows "8 min ago" at phone timestamp 00:11,. Xdrip at same time was showing 2 min ago and I've been debugging why its reading wasnt delivered to AAPS. It seems it was actually delivered, but AAPS didnt update the "min ago" timestamp. 
Log - 10.4 (188.0 in mg/dl log) was delivered at 00:07 (log line below). 

I presume it happens when delta is 0 (+0.06) between prior and current value, but not certain enough.

![0-02-05-e23ac8dee0c082e161033ebf16ed213663a12d23c5007c3230ea47baffd7d109_73d10466a9004e5a](https://user-images.githubusercontent.com/45970062/143953554-f2feb8da-e1bc-4353-8ac9-79d00f9140d4.jpg)

Log line from recive
`00:07:50.721 [pool-15-thread-4] D/BGSOURCE: [XdripPlugin$XdripWorker.doWork():80]: Received xDrip data: Bundle[{com.eveningoutpost.dexdrip.Extras.NoiseBlockLevel=200, com.eveningoutpost.dexdrip.Extras.BgSlope=0.0, com.eveningoutpost.dexdrip.Extras.VersionInfo=2111161026 68eecdc-2021.11.16, com.eveningoutpost.dexdrip.Extras.Raw=0.0, com.eveningoutpost.dexdrip.Extras.Time=1638223667481, com.eveningoutpost.dexdrip.Extras.CalibrationInfo=-1, com.eveningoutpost.dexdrip.Extras.NsNoiseLevel=null, com.eveningoutpost.dexdrip.Extras.Noise=-9999.0, com.eveningoutpost.dexdrip.Extras.SensorBattery=-1, com.eveningoutpost.dexdrip.Extras.NoiseWarning=0, com.eveningoutpost.dexdrip.Extras.BgSlopeName=Flat, com.eveningoutpost.dexdrip.Extras.BgEstimate=188.0, com.eveningoutpost.dexdrip.Extras.SourceDesc=G6 Native / G5 Native, com.eveningoutpost.dexdrip.Extras.SourceInfo=G6 Native, com.eveningoutpost.dexdrip.Extras.Collector.NanoStatus=  }]`

**Comment by stefanchavdarov** [comment]
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/7621617/AndroidAPS.log)
.. the log

**Comment by MilosKozak** [comment]
when this happen again paste screenshot of BG tab too

**Comment by MilosKozak** [comment]
closed for inactivity
