### ISSUE TITLE
[3.0-beta7] Carbs Treatment Date missing

### ISSUE THREAD

**Issue by chrisbev** [nightscout/AndroidAPS#1009]
On my Treatments Carbs tab see attached all except 'Calc'
entries appear with only time making it difficult to work out the date.
Samsung A41 And11 Patched LibreLink xDrip
![Screenshot_20211130-100601_AndroidAPS](https://user-images.githubusercontent.com/43484095/144035047-d2f2c575-e6e0-4f28-8855-d3c4cfce2f96.jpg)
![Screenshot_20211130-100617_AndroidAPS](https://user-images.githubusercontent.com/43484095/144035081-0b04a3a2-b474-4ce9-85f0-196f4d1cf459.jpg)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/EN/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
putting date would result in not readable text after especially on smaller screens
Calc doesn't have this problem thus can be with date
