### ISSUE TITLE
NSClient showing "??" since 24h

### ISSUE THREAD

**Issue by Kywalh** [nightscout/AndroidAPS#1019]
![Screenshot_20211201-115454](https://user-images.githubusercontent.com/28366579/144244551-cc78d014-6178-4644-8777-0607fd81feb9.jpg)
Reporting bugs
--------------
Since 24h, I can only see "??" on NSClient 2.8.2 (nighscout 14.0.4).

Might be linked to https://github.com/nightscout/share2nightscout-bridge/pull/51

Thanks

**Comment by MilosKozak** [comment]
it must be resolved on bg source side
