### ISSUE TITLE
Apps not running for 15 min while bg is changing 

### ISSUE THREAD

**Issue by margogoodfellow** [nightscout/AndroidAPS#1021]
Timing 20:30-20:45

https://drive.google.com/file/d/1r8zsKZe--5ifwzjb2SszRsNqc6ggyxH-/view?usp=driv
![Uploading 20211201_204458.jpg…]()
esdk
![20211201_204502](https://user-images.githubusercontent.com/68740119/144312099-6aa8cf7c-ab1e-4cc1-bd9c-e82de353d016.jpg)
![20211201_204502](https://user-images.githubusercontent.com/68740119/144312130-12c020c2-d9e6-4a2d-b162-efdcea1230d5.jpg)

**Comment by MilosKozak** [comment]
Loop is not running because your phone storage was/is full

**Comment by margogoodfellow** [comment]
Hi

I had this happened again but my phone storage is not full
