### ISSUE TITLE
Dev_14 Automation/ Can't delete part of rule

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1033]
I saved an automation rule and I want to modify it. I can't delete part of the rule. The _x_ doesn't delete it.

![Screenshot_20211204-172812_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/144717507-7858523e-f7e9-4726-8324-93e1b310ca11.jpg)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/fa4f0eb6886ef861c639a279840798dde63e1048
good catch!
