### ISSUE TITLE
[2.8.2.14-dev] Bolus nowhere to be found

### ISSUE THREAD

**Issue by Freloner** [nightscout/AndroidAPS#1040]
**AndroidAPS 2.8.2.14-dev** 
**Build**: 8783e67a9
**Flavor**: Fullrelease

**Problem description**:
I did a manual Bolus at around (maybe between) 09:25 & 09:50, then I noticed that my pod is ticking a lot due to SMBs, I checked AAPS, found that my BG is rising fast & the bolus is nowhere to be found, no trace at all.

**Log files:**
[AndroidAPS._2021-12-06_00-00-01_.2.zip](https://github.com/nightscout/AndroidAPS/files/7660212/AndroidAPS._2021-12-06_00-00-01_.2.zip)

**Screenshots:**

![Screenshot_20211206-104326_AndroidAPS](https://user-images.githubusercontent.com/87416963/144836893-a88e0155-cb17-4ab6-bec3-20f4af3bc780.jpg)
![Screenshot_20211206-104314_AndroidAPS](https://user-images.githubusercontent.com/87416963/144836894-356b6527-b204-4625-96d7-95bb0e816cc7.jpg)
![Screenshot_20211206-112419_AndroidAPS](https://user-images.githubusercontent.com/87416963/144836895-29f86068-8162-4620-8b18-5aac6d0a2ee9.jpg)
![Screenshot_20211206-104342_AndroidAPS](https://user-images.githubusercontent.com/87416963/144836896-313155dd-c87e-464d-a17d-b04394e34c88.jpg)

**Comment by avereha** [comment]
I do not find any bolus in the logs.

**Comment by Freloner** [comment]
> I do not find any bolus in the logs.

Me neither..

**Comment by robertrub** [comment]
Had the sane problem this morning. No carb entries'and no bolus.
![Screenshot_20211207-100540_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/145000607-8195c911-e049-4171-bdf5-6664d77aa98d.jpg)
![Screenshot_20211207-100637_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/145000626-2df33e3d-ce6c-4779-81b7-6b6b860225c0.jpg)

**Comment by robertrub** [comment]
![Screenshot_20211207-100540_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/145001603-ca9d3c6f-ca14-467b-a116-a776402f6db1.jpg)
![Screenshot_20211207-100637_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/145001618-5e73cc25-261e-4062-b341-5e5a3f858042.jpg)

**Comment by robertrub** [comment]
It might be a _user error_ in my case as I can't find any reference to any carbs or bolus in my logs. I'll keep watching.

**Comment by avereha** [comment]
Adding more logging to all the dialogues: https://github.com/nightscout/AndroidAPS/pull/1109

**Comment by avereha** [comment]
Suggesting to close this issue and reopen when we have logs that show the bolus.

**Comment by robertrub** [comment]
Ok. You can close it AFAIK. I never had the issue again. In my case, it was a _user error_
