### ISSUE TITLE
3.0beta9 Unable to Build

### ISSUE THREAD

**Issue by mfranzelihs** [nightscout/AndroidAPS#1045]
Hello,
trying to build 3.0 Beta 9, but I get an error every time I try. Please see screenshot
![IMG_4155](https://user-images.githubusercontent.com/53946154/145078431-1de9adb7-1267-49dd-8a7a-6356334b9956.jpeg)
.

**Comment by vanelsberg** [comment]
I have no problems building from current dev. Double check documentation on building.
Make sure you have updated Android Studio to latest version.
And maybe checkout this:
https://docs.google.com/document/d/1oc7aG0qrIMvK57unMqPEOoLt-J8UT1mxTKdTAxm8-po

**Comment by MilosKozak** [comment]
you may try clear studio cache

**Comment by mfranzelihs** [comment]
Got it working, thank you. That document helped. I was not downloading the right branch correctly. 

However, any idea why it says I need to rebuild in just a few days?
