### ISSUE TITLE
I use beta 9 with a combo pump and every time I click on the pump disconnect the app crashes

### ISSUE THREAD

**Issue by mordechi-david** [nightscout/AndroidAPS#1049]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/EN/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new
It happens every time, I use Android 10 and my logs go up through fabric by email md0527600652@gmail.com
תודה רבה

**Comment by mordechi-david** [comment]
זה קרה גם עכשיו ב 6:59

**Comment by swissalpine** [comment]
Same setup (Combo und last Beta/dev): Pump disconnect works like a charm!

**Comment by mordechi-david** [comment]
For me it collapses again and again here is a screenshot of a disconnected
pump and basal no 0

בתאריך יום ד׳, 8 בדצמ׳ 2021, 10:38, מאת swissalpine ‏<
***@***.***>:

**Comment by mordechi-david** [comment]
Attaches diaries
[AndroidAPS._2021-12-08_14-50-29_.0.zip](https://github.com/nightscout/AndroidAPS/files/7676114/AndroidAPS._2021-12-08_14-50-29_.0.zip)
[AndroidAPS._2021-12-08_14-49-26_.0.zip](https://github.com/nightscout/AndroidAPS/files/7676116/AndroidAPS._2021-12-08_14-49-26_.0.zip)
