### ISSUE TITLE
Synchronisation error - changes NS profile are not correct synched to AndroidAPS

### ISSUE THREAD

**Issue by peterleimbach** [nightscout/AndroidAPS#1050]
Reporting bugs
--------------
- I use Beta 8 and on nightscout side 14.0.7. The error occurred at around 10:10 o'clock this morning. Sorry I can't get this information better.
- I added
  a. log file,
  b. screenshot from ns profile editor and
  c. screenshot vom AndroidAPS
- The error occurred when I switched back from 4 IC values per day to hourly based IC values. Therefore I added in the NS profile editor further entries for every hour and saved the profile.
- On ns side the hourly added values are correct but on AndroidAPS there are new entries but the time information is missing and I had to add this manual.
- The second issue I see but I don't know where it comes from (NS or AndroidAPS) ist that the timestamp since the profile is in place (gültig in German) is not correct
[AndroidAPS_LOG_1638958717120.log.zip](https://github.com/nightscout/AndroidAPS/files/7675284/AndroidAPS_LOG_1638958717120.log.zip)
![30db5e6b-e3d6-4ba6-b6a7-6a842e07ba98](https://user-images.githubusercontent.com/4148261/145192219-bfab76ab-4aa5-4225-8397-18fa785fe26e.jpg)
<img width="874" alt="Bildschirmfoto 2021-12-08 um 11 24 11" src="https://user-images.githubusercontent.com/4148261/145192235-e04d4622-fc91-4e83-aa54-b6b5b1e57129.png">

.

**Comment by MilosKozak** [comment]
did you follow this while setting profile?
https://androidaps.readthedocs.io/en/latest/Installing-AndroidAPS/Releasenotes.html#changes

**Comment by peterleimbach** [comment]
I think I violated "Record modification from NS is not allowed" when I changed the profile with Nightscout profile editor if I understand this right.

**Comment by MilosKozak** [comment]
I don't know this message

**Comment by peterleimbach** [comment]
That's part of the release notes. I thought I used a not already implemented functionality.

"NSClient rewritten for better synchronization and more detailed customization @MilosKozak

Record deletion from NS is not allowed (only invalidation through NSClient)
**Record modification from NS is not allowed**
Sync setting available without engineering mode (for parents)
Ability to resync data"

**Comment by peterleimbach** [comment]
I think I now found what you mean in the release notes.

No, I did not clone the entry. I just changed and saved it. Somehow I have not seen this in the release notes.
