### ISSUE TITLE
[NSclient 3.0-beta8] - Error message by entering carbs from NSclient App

### ISSUE THREAD

**Issue by streethawk22** [nightscout/AndroidAPS#1053]
[AndroidAPS_LOG_1638978501376.log.zip](https://github.com/nightscout/AndroidAPS/files/7677222/AndroidAPS_LOG_1638978501376.log.zip)
Error message by entering carbs from NSClient App.
NSClient Version: 3.0 beta8
Error Message: "Data coming from anorher pump, change the pump driver for pump status  #refresh".
![Screenshot_20211208-162252_NSClient](https://user-images.githubusercontent.com/25482897/145238440-7543d0e8-fff1-4cd8-8c0e-3fe180610445.jpg)
 added.

--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/EN/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new
[AndroidAPS_LOG_1638978501376.log.zip](https://github.com/nightscout/AndroidAPS/files/7677227/AndroidAPS_LOG_1638978501376.log.zip)

**Comment by MilosKozak** [comment]
16:22 is not in logs
