### ISSUE TITLE
Setup wizard has a dead wiki link on the Sensitivity Detection page

### ISSUE THREAD

**Issue by legoandmars** [nightscout/AndroidAPS#1056]
The sensitivity detection page links `https://github.com/MilosKozak/AndroidAPS/wiki/Sensitivity-detection-and-COB` as a source for more info, which redirects to [the old AndroidAPS repo](https://github.com/MilosKozak/AndroidAPS) since the old wiki is no longer located in that repository

<img src="https://user-images.githubusercontent.com/34404266/145344198-55899a6e-d6b7-48d7-af8b-791831ba1c3c.png" alt="Image example" width="400px">

As far as I can tell this is the only reference to the old wiki left in the app, it probably just slipped through the cracks because nobody reported it

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/9be074045bda6abc346e6ab40968743354ae5107
Thanks
