### ISSUE TITLE
direction arrow misplaced

### ISSUE THREAD

**Issue by guydavies** [nightscout/AndroidAPS#106]
In the 2.7.2 Dev build bf0dc1cb9 the direction arrow seems to be misplaced. 

I'm running on a Google Pixel4a

You can see the issue in the photo at the link below
[https://photos.app.goo.gl/YFG9LcSfiTfnfjDV7](url)

**Comment by guydavies** [comment]
URL above should be [https://photos.app.goo.gl/YFG9LcSfiTfnfjDV7](https://photos.app.goo.gl/YFG9LcSfiTfnfjDV7).  Trying to do it from the phone didn't work out as I expected.

I'm seeing the same issue still with the very latest dev build 3f64dff01 built this afternoon.

**Comment by StephenBrown2** [comment]
I have also seen an issue where the direction arrow gets updated from the bg source, then resets to horizontal shortly thereafter. Not sure if it's related, I'll try to capture logs next time it happens.

**Comment by Alamo04** [comment]
Confirm guydavies issue.
Same on Pixel 5.

In the latest dev, it seems to be in place again, but this version can't be created,.
Time Ago position is now under the arrow and there are a few errors about time etc. in the building prozess.

**Comment by guydavies** [comment]
Fixed in the latest Dev build.
