### ISSUE TITLE
zero value for SMB recorded. 

### ISSUE THREAD

**Issue by pbloom209** [nightscout/AndroidAPS#1067]
Dana I
Beta 3 ver 9
I have noticed that on the home screen it shows the triangle for SMB being delivered.
When checking in treatments they are zero.  This is confirmed on the pump checking the history.

Please see screenshot
![Screenshot_20211213-082202_AndroidAPS](https://user-images.githubusercontent.com/37948551/145730238-aba2e222-5cf3-47df-81f3-4c33a6d319a1.jpg)
![Screenshot_20211213-082209_AndroidAPS](https://user-images.githubusercontent.com/37948551/145730242-24671996-ce76-42b5-84b0-fbbad29c27a8.jpg)
s

**Comment by MilosKozak** [comment]
version?
logs?

**Comment by pbloom209** [comment]
Logs as requested


[AndroidAPS._2021-12-13_02-39-49_.2.zip](https://github.com/nightscout/AndroidAPS/files/7708010/AndroidAPS._2021-12-13_02-39-49_.2.zip)

**Comment by pbloom209** [comment]
this issue is continuing to occur.  I cannot see any pattern of events that is triggering this.

**Comment by MilosKozak** [comment]
log is 10:27 - 15:24
i need a time to search for

**Comment by pbloom209** [comment]
![Screenshot_20211214-224831_AndroidAPS.jpg](https://user-images.githubusercontent.com/37948551/145993250-e2ea1615-f13f-49ef-8356-b633d4a12f17.jpg)


New screenshot.

With new log.

**Comment by pbloom209** [comment]
[AndroidAPS (1).log](https://github.com/nightscout/AndroidAPS/files/7711387/AndroidAPS.1.log)

**Comment by pbloom209** [comment]
also note it does not seem to change the SMB from 0.1

**Comment by pbloom209** [comment]
search for 22:24 and 22:29

**Comment by pbloom209** [comment]
i have just noticed the pattern when AAPS changes the Temp basal rate it also posts in the treatments the 0 SMB and adds the triangle to the home screen

**Comment by pbloom209** [comment]
it just did this pattern again.  So the changing of the Basal creates a zero 
smb

**Comment by MilosKozak** [comment]
what is your bolus step in doctor's menu?

**Comment by MilosKozak** [comment]
could you try it manually on your pump?
start bolus of 0.05 without TBR and with 40% TRB running

**Comment by pbloom209** [comment]
I will change the mininum in the doctors menu to 0.05

**Comment by pbloom209** [comment]
tried 0.05 with both basal on the pump no problem

**Comment by pbloom209** [comment]
They are now showing 0.05 in pump history when I look at it in AAPS

**Comment by pbloom209** [comment]
I think it is fixed.  now i have changed to 0.05 in Doctors menu.
Tx
