### ISSUE TITLE
Android 12 Samsung losing connection to Dana I pump

### ISSUE THREAD

**Issue by pbloom209** [nightscout/AndroidAPS#1070]
updated to Android 12.

Pump randomly disconnects and I need to re-pair the pump.

Beta 3 version 9

This random disconnect has occurred about 4 times in the last 24 hours.

I updated the software about 36 hours ago.

![Screenshot_20211214-124651_AndroidAPS](https://user-images.githubusercontent.com/37948551/145918832-88eba590-4ec0-4fa9-9aa2-eac033d6ab9f.jpg)

![Screenshot_20211214-124730_Settings](https://user-images.githubusercontent.com/37948551/145918821-b3279450-0482-48c5-af0c-ffb4bc65b901.jpg)
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/7708081/AndroidAPS.log)

**Comment by MilosKozak** [comment]
If AAPS cannot connect to the pump for some time, encryption keys are cleared and new pairing is initiated. It's Android thing. I cannot help. Downgrade to A11 if you don't find better solution
