### ISSUE TITLE
Wear OS confirmation screen is blank

### ISSUE THREAD

**Issue by erobinson** [nightscout/AndroidAPS#1078]
Version: 3.0-beta11 for both phone & watch

Steps to reproduce

1. Go into app on wear os
2. Select Wizard/eCarb/Bolus/TempT
3. Select any inputs in the steps and confirm
4. There is a confirmation coming back from the phone
5. Expected result: Confirmation shows info and allows the user to confirm the action
6. Actual result: The confirmation screen shows "Title" at the top and a blank/black screen without the option to confirm anything

**Comment by reijoahola-nightscout** [comment]
This is probably the same as #1077.

**Comment by erobinson** [comment]
Closing as duplicate
