### ISSUE TITLE
[3.0 Beta 11] RileyLink appears not to be scanned (legibility problem)

### ISSUE THREAD

**Issue by rustymonkey** [nightscout/AndroidAPS#1079]
Upon launching 2.8.2.18-dev, no connection to the OL was possible. Clearing cache, restarting the phone and reseting the OL had no effect. Deleting the OL and initiating a scan didn't resolve the issue either because AAPS failed to find the OL (I've _never_ observed this before)!

This was previously working with all earlier builds (last tested was 2.8.2.16).

Tested with 2.8.2.18-dev = B11 / S7 running Android 11 / OL firmware 2.5 / MDT 554

EDIT: this log was taken immediately after attempting to Scan for the OrangeLink.
[AndroidAPS_LOG_1639632763003.log.zip](https://github.com/nightscout/AndroidAPS/files/7724841/AndroidAPS_LOG_1639632763003.log.zip)

EDIT2:
- On launch, there was no prompt for any new Bluetooth permissions
- The Setup Wizard didn't prompt for any new Bluetooth permissions either

**Comment by rustymonkey** [comment]
Note: reverting to 2.8.2.16 solved the problem confirming that it's a recent regression.

**Comment by rustymonkey** [comment]
Further investigation reveals that this issue occurred due to a combination of:
1) #474 : this issue sometimes occurs on reboot, the workaround requiring deletion/addition of the RL/OL
2) A cosmetic bug in Beta 11 in which the RileyLink configuration dialog displays the scanned OrangeLink almost invisibly. In other words, when the user presses [Scan] on the RileyLink configuration panel, the RL is scanned, but displays so faintly that it's almost invisible! See below:
![AndroidAPS_RL-Scan-dialog-legibility](https://user-images.githubusercontent.com/34991028/146441134-0eb98801-b02e-42c5-8b2a-ee628e11ee97.png)

**Comment by Philoul** [comment]
@rustymonkey can you test PR #1120 and tell me if it fix your issue (black text...) ?

**Comment by rustymonkey** [comment]
Verified in 3.0 RC2. Thanks!
