### ISSUE TITLE
Feature request : calculate insulin used for meal carbs.

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1084]
A feature request (if several are interested in it) about carbs and insulin needed to absorb them.
In AAPS, it is easy to see if basals are correct: without food, you look if you have positive or negative IOB and can decide if your basal settings are correct. 
My question is about meals. I enter carbs and use the wizard to calculate the U needed and inject 80% of the calculated bolus and let the SMBs do their job to catch up. 
I can't find a way to see if my carbs/insulin index is correct. I need to add the bolus, the SMBs and the "theoretical basals" then subtract the "not given basals" in order to see if the quantity of insulin given was the quantity calculated...
It would be nice if, once the BGs are back on target (or after x hours after a meal), we could have the information of the bolus used (either in bolus or SMB form) to absorb the meal carbs (taking the basal off the calculations).

Lets try with a real life situation : BG at carb and bolus entry is 100 (which is also the target). Enter 50g and 5U needed, 4U injected ( = _meal start_ )
We can use the _duration of meal/carbs_ variable set in the AAPS parameters and/or when we reach target to set the end of test time ( = _meal end_ ).
I'd see the calculation as :
Bolus at meal time + SMBs between meal start and meal end  - IOB at meal start - IOB at meal end - calculated basal from profile for the meal duration = units injected to absorb our 50g of meal carbs.
We can start the calculations at each meal or only "on demand".

**Comment by szantos** [comment]
This would be a very useful feature!

[ I've created a basic spreadsheet for this purpose, but it's not ideal, as I was not able to get historical IOBs through the APIs (maybe my bad). Then I've solved it based on the integral of the activity curve, which is not an elegant way. ]

My suggestions:
- meal_start and meal_end time as input
- in this time frame sum all the carbs and insulin which have taken effect
- for carbs it is "easier" based on carb bolus and COB difference between end and start (but depends on carb absorption model)
- for insulin it is trickier (as robertrub proposed)
- think about profile switches, these should be ignored (calculation should be based on a profile at meal_start), also IOB=0 should be calculated based on the initial (basal)profile
- the correction insulin (SGV at meal_start and meal_end differ) should be considered based on ISF

Now to make AAPS devs happy:
I'm not sure whether this should be done in AAPS. Maybe NS would be a better place, extending the features of loopalyzer, comparing meals of multiple days more easily, etc.
