### ISSUE TITLE
[3.0-beta9] NSClient - Incorrect vertical position of BG check on graph

### ISSUE THREAD

**Issue by vmichalec** [nightscout/AndroidAPS#1085]
Hi, this is probably only displaying issue on NS client side, details in screenshots.

Here is bg check of 5.8 correctly displayed on aaps graph, also entry in treatments shows value corrrectly. (Sorry for non-english screenshots)
![AndroidAPS_01](https://user-images.githubusercontent.com/24793786/146589177-c0fd3ae3-748a-48e7-a018-8bf68f999942.jpg)

![AndroidAPS_02](https://user-images.githubusercontent.com/24793786/146589198-fcce9f8a-4730-4c32-8fa4-4519f94bd7e8.jpg)

But on NS Client side the value is positioned on the bottom of the graph, not on correct y-axis (vertical) position.

![NSClient_01](https://user-images.githubusercontent.com/24793786/146589213-47b52058-c98c-431f-a939-35c916ea9500.jpg)

And also in entries screen the value is not shown in the BG check entry.

![NSClient_02](https://user-images.githubusercontent.com/24793786/146589220-b5b7c4cf-f29c-489c-950a-e1e001acd809.jpg)

**Comment by vmichalec** [comment]
**[3.0-beta11]** I have checked it also on latest beta. NSClient side treatments entry now shows also the value - perfect. Now I can see also the real problem behind - in AAPS I entered blood glucose on action tab as value of 30.0 mmol/L but on NSClient side there is shown as 1.7 mmol/L so now it is obvious. Graph position of the entry on NSClient side is now lite bit higher so it looks like the graph is correct and shows the label on 1.7 y-axis position.

Moreover I'm using also 1.9.0.5 BYODA. Calibrations made here are shown correctly in AAPS and also NSClient.

**Comment by Philoul** [comment]
30mmol for a BG value! Very high, but 1.7 is a wrong convertion mg/dl to mmol/l.
Did you see 1.7mmol in user entry or in another place?

**Comment by vmichalec** [comment]
3.0-beta11 for aaps and nsclient, 14.2.5 nightscout version.

Doing again now: I entered BG Check in action tab of 30 mmol/L on aaps side, it becomes 1.7 mmol/L on nsclient side. Graph position of the entry on nsclient is slightly bellow 2 so I think it is only unit conversion problem.

**Comment by Philoul** [comment]
Can you please send me a screenshot of "user entry" icon in both phones please to help me understand where is the bug

**Comment by vmichalec** [comment]
AAPS:
![AndroidAPS_01](https://user-images.githubusercontent.com/24793786/146910142-4087939a-3aac-4a66-9b75-9f0998786ef4.jpg)
![AndroidAPS_02](https://user-images.githubusercontent.com/24793786/146910156-1a42b539-df75-4782-b51d-f64a3b7da245.jpg)
![AndroidAPS_03](https://user-images.githubusercontent.com/24793786/146910164-f1a415f4-3401-4406-8625-f3df7352a9fe.jpg)
![AndroidAPS_04](https://user-images.githubusercontent.com/24793786/146910172-a342da7c-0a46-4f5d-b542-0a07e1a67ff6.jpg)
![AndroidAPS_05](https://user-images.githubusercontent.com/24793786/146910188-007f6ff7-db69-489c-b1de-1835e5e61add.jpg)

NSClient:
![NSClient_01](https://user-images.githubusercontent.com/24793786/146910226-31564efd-7770-4c6a-8207-0d84e5755469.jpg)
![NSClient_02](https://user-images.githubusercontent.com/24793786/146910239-6ce8cd39-9622-4eb6-b6f6-1c3ac0471705.jpg)
![NSClient_03](https://user-images.githubusercontent.com/24793786/146910253-872162d0-c904-4e61-a257-27d347a7baed.jpg)

**Comment by Philoul** [comment]
@MilosKozak I confirm the bug, there is a wrong unit change somewhere between source phone and destination phone (see below send and received values in log)

Value sent by source phone is OK (Unit is MMOL recorded in database and sent in NSCLIENT)
```
10:53:43.752 [RxCachedThreadScheduler-95] D/DATABASE: [NSClientAddAckWorker.doWork$lambda-7():114]: Updated ns id of TherapyEvent TherapyEvent(id=4438, version=0, dateCreated=1640080403090, isValid=true, referenceId=null, interfaceIDs_backing=InterfaceIDs(nightscoutSystemId=null, nightscoutId=61c1a427cfbcaf0004001c7d, pumpType=null, pumpSerial=null, temporaryId=null, pumpId=null, startId=null, endId=null), timestamp=1640080392000, utcOffset=3600000, duration=0, type=ANNOUNCEMENT, note=test notif, enteredBy=AndroidAPS, glucose=6.0, glucoseType=SENSOR, glucoseUnit=MMOL)
10:53:43.763 [pool-19-thread-2] I/NSCLIENT: [DataSyncSelectorImplementation.processChangedTherapyEventsCompat():536]: Loading TherapyEvents data Start: 4438 ID: 4438 HistoryID: TherapyEvent(id=4439, version=0, dateCreated=1640080403090, isValid=true, referenceId=4438, interfaceIDs_backing=null, timestamp=1640080392000, utcOffset=3600000, duration=0, type=ANNOUNCEMENT, note=test notif, enteredBy=AndroidAPS, glucose=6.0, glucoseType=SENSOR, glucoseUnit=MMOL) 
```

But value received on the other phone, unit is wrong (MMOL is replaced by MGDL)
```
10:53:48.987 [pool-18-thread-2] D/DATABASE: [NSClientAddUpdateWorker.doWork():291]: Inserted TherapyEvent TherapyEvent(id=1152, version=0, dateCreated=1640080428971, isValid=true, referenceId=null, interfaceIDs_backing=InterfaceIDs(nightscoutSystemId=null, nightscoutId=61c1a427cfbcaf0004001c7d, pumpType=null, pumpSerial=null, temporaryId=null, pumpId=null, startId=null, endId=null), timestamp=1640080392000, utcOffset=3600000, duration=0, type=ANNOUNCEMENT, note=test notif, enteredBy=AndroidAPS, glucose=6.0, glucoseType=SENSOR, glucoseUnit=MGDL)
```

**Comment by Philoul** [comment]
Additionnally record is correct in NS (units = mmol)
```
    {
      "eventType": "Announcement",
      "isValid": true,
      "created_at": "2021-12-21T09:53:12.000Z",
      "enteredBy": "AndroidAPS",
      "units": "mmol",
      "notes": "test notif",
      "glucose": 6,
      "glucoseType": "Sensor",
      "isAnnouncement": true,
      "identifier": "61c1a427cfbcaf0004001c7d",
      "srvModified": 1640080392000,
      "srvCreated": 1640080392000
    },
```

**Comment by Philoul** [comment]
Very strange Breakpoint in `TherapyEventExtension.kt`line 72 (`therapyEventFromJson` function), and the json string looks like that:
"unit" = "md/dl" and I have a "mmol" key with value ???
```
{
    "_id":"61c2407fcfbcaf0004001dc4",
    "eventType":"Question",
    "isValid":true,
    "created_at":"2021-12-21T21:00:28.000Z",
    "enteredBy":"AndroidAPS",
    "units":"mg\/dl",
    "notes":"test",
    "glucose":6.5,
    "glucoseType":"Finger",
    "mills":1640120428000,
    "mmol":6.5,
    "targetTop":null,
    "targetBottom":null
}
```

It's not the json string got from NS (see below json strings with API V1 queries)
```
{
    "_id":"61c2407fcfbcaf0004001dc4",
    "eventType":"Question",
    "isValid":true,
    "created_at":"2021-12-21T21:00:28.000Z",
    "enteredBy":"AndroidAPS",
    "units":"mmol",
    "notes":"test",
    "glucose":6.5,
    "glucoseType":"Finger",
    "mills":1640120428000,
    "carbs":null,
    "insulin":null
},
```
Unfortunatly I can't find where json string is modified to make a clean fix...

**Comment by MilosKozak** [comment]
it's NS bug. reported to NS team
