### ISSUE TITLE
[3.0b11]App crash near end of startup pump comms cycle w/ Medtronic. 

### ISSUE THREAD

**Issue by PedanticAvenger** [nightscout/AndroidAPS#1087]
Version : 3.0b11
Os: android 11
Pumo:Medtronic

App repeatedly crashes at the end of pulling pump info, started around 1AM. 
App restarts fine, begins talking to pump and crash repeats.
[AndroidAPS_LOG_1639991165247.log.zip](https://github.com/nightscout/AndroidAPS/files/7744114/AndroidAPS_LOG_1639991165247.log.zip)

**Comment by PedanticAvenger** [comment]
Workaround to get things finally working was to set virtual pump for 5 min then switch back to Medtronic.

**Comment by andyrozman** [comment]
It seems that new logic for determinig TBRs is not working 100% (there seem to be some side scenarios wich weren't considered). I need to extend logic a little.
@PedanticAvenger
