### ISSUE TITLE
Option to not allow using same OTP for SMS again

### ISSUE THREAD

**Issue by ideaweb** [nightscout/AndroidAPS#1088]
Maybe already implemented features for SMS security are good enough (checking sender, bolus limit/time frame, all numbers will be informed etc but is SMS still secure enough e.g. faking sender identification?), but I would feel safer (especially for remote monitoring of a child) if an already used/accepted OTP cannot be used twice (e.g. sending "CARBS 5" but someone uses same code again for "BOLUS 5"). 

Of course in this case user has to wait (<30 sec), but maybe adding an option in SMS configuration would be nice, where the user can decide by self (to not care for better usability or to avoid "TOTP replay attack").

I tested it only with branch 3.0b11.

**Comment by MilosKozak** [comment]
I'm personaly taking advantage of using the same code multiple times within short time range to send more commands.
I believe the risk of abuse OTP code (when there is another phone # check in place) very low.
But keeping this open if more people request it
