### ISSUE TITLE
Can't pass objective 1 / NS connection not detected

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1090]
Objective 1 can't be validated if you don't set _BG backfill from NS_ to ON. The BGs are on NS but AAPS seems not to be aware.
Once you set backfill BGs, you can validate objective 1.
As backfilling BGs from NS is the source of doubled BGs in AAPS (and thus the red triangle), it is counterproductive to be obliged to set it ON in order to pass obj 1.

**Comment by MilosKozak** [comment]
resolved by https://github.com/nightscout/AndroidAPS/commit/5d74f71d0aeaf6b88f3719d3030509ca7250fef3
