### ISSUE TITLE
[Latest dev] No profile change if only the target area was changed

### ISSUE THREAD

**Issue by swissalpine** [nightscout/AndroidAPS#1091]
If I change the target area in a Local Profile and save it, then trigger a profile change, the profile change is not performed and the previous targets remain active.
Workaround: Start a profile for a few minutes with a percentage change, then - when switching back - the changed Local Profile with the changed targets is active.
Version: Latest devs (already for a longer time)
Pump: Combo

**Comment by Alamo04** [comment]
Confirmed
There are some fixes done in the past, but they didn't help in that case.

You must always have a small change in your basal profile (0,01) then the profile switch works without to change to a different profile first.

**Comment by MilosKozak** [comment]
hmmm it works properly for RS/i

**Comment by MilosKozak** [comment]
looking at te code it should work for Combo as well
Please provide logs

**Comment by Alamo04** [comment]
Forced it for you @MilosKozak .
Changed only Target fom 100 and 90 to only 100.

Shown in treatment but nothing happens in AAPS.

![Screenshot_20211230-193610](https://user-images.githubusercontent.com/36486505/147779612-7ef7038a-1326-4f09-8976-e6f19f67b8ab.png)
![Screenshot_20211230-193644](https://user-images.githubusercontent.com/36486505/147779621-fcb74cf7-2d01-4d37-aef4-fcac765272d8.png)

[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/7794204/AndroidAPS.log)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/7243f8fb6645b8de9271f1a0b55352231b2c9015
