### ISSUE TITLE
Enhancement: Show G6 transmitter age

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1092]
Actually, AAPS keeps track of the G6 **sensor** age. It would be helpful to keep track of the **transmitter age** too.

I don't know if _transmitter change_ info is transferred from BYODA/xDrip or needs to be entered in AAPS...

xDrip gives the transmitter **age** but BYODA only gives **the date** when it was started

**Comment by MilosKozak** [comment]
BOYDA doesn't send this info.
you may request it then we can implement it

**Comment by robertrub** [comment]
@MilosKozak Why not add a button in AAPS for _Transmitter activation_ ? 

![Screenshot_20211223-104828_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/147222501-fb768412-9551-443c-852b-74d56013ad45.jpg) ?
