### ISSUE TITLE
Automation successfully triggers but not the alert set. 

### ISSUE THREAD

**Issue by bchris21** [nightscout/AndroidAPS#1101]
Dev18
Android 9

**Expected behavior:**  
Automation "Going Low - Give 1 Glucotab" is set for warning on an upcoming low. Automation triggers if network location is outside school in a 5Km radius. An alarm is set to trigger. Since AAPS v3, when Automation is successful, the alarm clock starts a 10sec countdown and triggers an alarm which can be snooze like a normal alarm clock. Notification set on AAPS header in main screen and a dot with message is set in graph.

**Issue:**  
Automation "Going Low - Give 1 Glucotab" set for warning on an upcoming low is triggered. Header and graph notification are set but no alarm triggered anymore even though all volume levels (music, alarm and ringtone) are set at around 50%. No alarm clock countdown started. No battery saving mode active.

**Reproducing:**  
Not easy to reproduce as it happens every now and then. Just exported logs (attached) on latest occurrence this morning.

**Question:**  
- Is this Android alarm clock triggering the new expected behavior? In v2.8.2 there was a nice pop up with an alarm that triggered with no count down and an option to snooze for different time-frame or even stop the alarm completely.

 ![Screenshot_20211227_122236.jpg](https://user-images.githubusercontent.com/4725280/147467179-6ff7c0e6-1d9f-4b61-9c55-5d1ff8f99aa2.jpg)

![Screenshot_20211227_122203.jpg](https://user-images.githubusercontent.com/4725280/147467190-21455e94-8421-424d-8ec6-363c2e743013.jpg)

![Screenshot_20211227_122117.jpg](https://user-images.githubusercontent.com/4725280/147467199-3b76b3a1-a274-4e9f-86c6-7135b24dc732.jpg)

![AndroidAPS_LOG_1640591336442.log.zip](https://github.com/nightscout/AndroidAPS/files/7779947/AndroidAPS_LOG_1640591336442.log.zip)

**Comment by MilosKozak** [comment]
v3 uses Android alarm function instead for better compatibility. OK means command was executed.
there nothing I can help with
I did a small chnge that can help on very busy slow phones https://github.com/nightscout/AndroidAPS/commit/aee036e20074fdb0992ccfd582bf7cd8b1689418
