### ISSUE TITLE
Pixel 6 and Dash have slow connection time / sometimes failing to connect

### ISSUE THREAD

**Issue by um17tjs** [nightscout/AndroidAPS#1112]
Using Libre2 -> Librelink Patched -> Xdrip -> AAPS -> Dash

When connecting to the pump for any treatment input, TBR, test Bleep or READSTATUS. The connection time varies however 90% of the time it will be greater than 70 seconds until it connects. On a few occasions AAPS has failed to connect to the pump at (after 120 seconds). 

Using 3.0-beta11 Build: f910fd7fb-2021.12.21-20:56 Flavor: fullrelease Nightscout version: 14.2.5 Engineering mode enabled

[AndroidAPS_LOG_1640887200250.log.zip](https://github.com/nightscout/AndroidAPS/files/7794063/AndroidAPS_LOG_1640887200250.log.zip)

**Comment by MilosKozak** [comment]
connection time is not (and cannot be) affected by AAPS. Is pure Android thing. AAPS gets control when connection is established.
You can change position of pump-dash or ask in FB group for some Pixel related tweaking
