### ISSUE TITLE
3.0beta11: NSClient queue appears empty 

### ISSUE THREAD

**Issue by tanja3981** [nightscout/AndroidAPS#1114]
Using 3.0beta11.

I had my nsclient paused for a couple of days.
When I went to unpause, I wondered why the queue would be empty...
After unpausing the queue was still empty.
After restart, the queue contained entries and these were sent.

The queue size should reflect the number of items in the queue, no matter whether paused or not, shouldn't it?

![Screenshot_20220101-023347.png](https://user-images.githubusercontent.com/7403966/147842342-1d96ab82-73ba-486b-a545-8a5068e0d70f.png)
![Screenshot_20220101-023352.png](https://user-images.githubusercontent.com/7403966/147842344-194bfb8a-f319-4618-b7c2-2b52b937ccb8.png)
![Screenshot_20220101-023419.png](https://user-images.githubusercontent.com/7403966/147842347-541be93a-50dd-4524-aaa5-e59a8fb72585.png)

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/b5b6432b130c400fde707e8000775d6a391c19bd
