### ISSUE TITLE
[3.0 beta 11] Config builder UI - Pump order (Omnipod Eros / Dash)

### ISSUE THREAD

**Issue by xJoe** [nightscout/AndroidAPS#1121]
I recommend to adjust the order to have Dash directly after Omnipod Eros and Combo directly after Insight to prevent users from irritation.

I'd also call pumps Omnipod Eros and Omnipod DASH.

**Actual order**
1. DanaR
2. DanaR Korean
3. DanaRv2
4. Dana-i/RS
5. Accu-Check Insight
6. Omnipod
7. Accu-Chek Combo
8. Medtronic
9. Diaconn G8
10. Dash
11. MDI
12. Virtual Pump

**Proposed order**
1. DanaR
2. DanaR Korean
3. DanaRv2
4. Dana-i/RS
5. Accu-Check Insight
_6. **Accu-Chek Combo**_
7. Omnipod **Eros**
_8. Omnipod **DASH**_
9. Medtronic
10. Diaconn G8
11. MDI
12. Virtual Pump

**Comment by avereha** [comment]
:+1:

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/a1bc75859674de4c01b99f4889d2bdb1e5f0b0d1
