### ISSUE TITLE
[BETA 11] Problem with data processing

### ISSUE THREAD

**Issue by 69nobody** [nightscout/AndroidAPS#1132]
New data such as delivered boluses or eaten carbohydrates cannot be processed and are not displayed.
Unpairing and re-pairing unfortunately only worked for a short time.
Then the same was displayed as marked in red in the picture. "...TempStop 06:24..."
In the statistics Dana-i tab is displayed under error, event is processed TEMP_STOP 06:24.
![grafik](https://user-images.githubusercontent.com/94611099/148361569-9f9f10d7-bf00-4cec-955e-50cdd0e7a6a2.png)

This is really weird, right after delivering a bolus comes "loading events" then the already known red framed is displayed again.

Bolus is delivered, the number of units does not change in the IOB display. The same applies to COB.
Whenever AAPS connects to the pump to exchange current data, "Result is being processed......." is displayed.

[AndroidAPS._2022-01-06_09-52-56_.3.zip](https://github.com/nightscout/AndroidAPS/files/7820975/AndroidAPS._2022-01-06_09-52-56_.3.zip)

Translated with www.DeepL.com/Translator (free version)

**Comment by 69nobody** [comment]
I was able to solve my problem by resetting the databases.
I then imported a copy of my settings and activated my profile.
IOB and COB are updated and displayed again.
The TEMPSTOP entry is no longer displayed.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/3a30f73aa11273e7e44938be60022ba9c668ea50
