### ISSUE TITLE
[3.0-beta11] QuickWizard bolus without carbs entry

### ISSUE THREAD

**Issue by vmichalec** [nightscout/AndroidAPS#1133]
Rarely it happens that after performing bolus (this time using QuickWizard) there is no carb entry created. In this case it was with dana-rs pump.

```
08:23:21.787 [RxCachedThreadScheduler-92] D/CORE: [UserEntryLogger$log$2.invoke():45]: USER ENTRY: TREATMENT QuickWizard Raňajky [TherapyEventType(value=BOLUS_WIZARD), Insulin(value=3.4), Gram(value=20)]
```

Logs: [AndroidAPS.log.zip](https://github.com/nightscout/AndroidAPS/files/7821242/AndroidAPS.log.zip)

![01](https://user-images.githubusercontent.com/24793786/148371855-4cd2b6ea-af5d-49a6-845a-1529423b1013.png)
![02](https://user-images.githubusercontent.com/24793786/148371877-2ed59264-75d4-40c1-8936-2448d374db57.png)
![03](https://user-images.githubusercontent.com/24793786/148371890-02a485ce-0568-429c-aadc-9b8633dc7df9.png)

**Comment by filipwoz** [comment]
I experienced today and yesterday the same with the Dash pump - actually quite critical, as the carbs are missing then for the next calculations.
In my case not only the KH but also the Bolus-Calc entry was missing.

**Comment by MilosKozak** [comment]
It's pump error
`08:23:28.880 [Thread-26053] W/PUMPBTCOMM: [BLEComm.sendMessage():832]: Reply not received APS_SET_EVENT_HISTORY`

Anyway, I added error dialog when this happen https://github.com/nightscout/AndroidAPS/commit/54257ef6f0aff7e75329d0d25367e19c82301bec
