### ISSUE TITLE
[3.0 beta11] Not possible to set particular clock-time for recording an external bolus 

### ISSUE THREAD

**Issue by filipwoz** [nightscout/AndroidAPS#1134]
In the Insulin dialog if using the second checkbox you are recording external insulin injection (not with the AAPS pump)

![image](https://user-images.githubusercontent.com/20597551/148393544-2bd16ed8-b8c6-4ce8-a079-da8243602f14.png)

here at the moment it is only possible to do it with the current time stamp or with a time shift of plus/minus minutes.
I am missing a possibility to to select a particular date/time like in the Carbs dialog

Moreover the "Time Shift" field is (at least in German translation) wrongly labeled as "Zeit" ("Time").

**Comment by MilosKozak** [comment]
this is expected behaviour. setting insulin to the the past should be rare situation because calculations meanwhile would be wrong. thus "Time" control is enough
