### ISSUE TITLE
[3.0-beta11] AAPS/NSClient Synchronisation setting has Receive APS offline events. Is it needed ?

### ISSUE THREAD

**Issue by reijoahola-nightscout** [nightscout/AndroidAPS#1137]
When testing synchronisation of various things between AAPS and NSClient I found that there is a setting "Receive APS offline events" in AAPS app. It specifies that "Accept APS offline events entered through NS or NSClient". However I cannot find any way of giving "APS offline events" (Suspend Loop, Disconnect Loop etc.) from NSClient. Have I misunderstood something or is this setting unnecessary ?

**Comment by MilosKozak** [comment]
you'll see in nsclient timerange where aaps was off .... that's all

**Comment by reijoahola-nightscout** [comment]
Yes, I noticed that timerange can be seen also in NSClient app when the operation is started from AAPS app. But the question was is AAPS synchronisation setting needed because the operation cannot be started from NSClient.

**Comment by MilosKozak** [comment]
no at the moment but maybe in the future

**Comment by reijoahola-nightscout** [comment]
> no at the moment but maybe in the future

Should the setting be grayed as long as it has no real function.
