### ISSUE TITLE
Dev 19 (and before) / Too many alert beeps

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1139]
Not urgent. This happened several times with the older dev versions too. 

AAPS sends a notification via Android and it "beeps". In some occasions (can't find out when :(  ) it beeps 3-5 times. I copied the logs in case you can see the reason in them.  Look at time 11:46

[AndroidAPS_LOG_1641638856393.log.zip](https://github.com/nightscout/AndroidAPS/files/7834876/AndroidAPS_LOG_1641638856393.log.zip)

![Screenshot_20220106-195856_AndroidAPS](https://user-images.githubusercontent.com/76626474/148678932-e1c84040-3b84-4f78-92cd-9531d5463912.jpg)

**Comment by MilosKozak** [comment]
i see notifications only from automations

**Comment by robertrub** [comment]
Tnx. I have automations to raise target when there is a hypo risk. Maybe this automation and "x grams of carbs needed" alert is the reason for the multi beeps.

I'll keep watching and report more or close the issue accordingly.
