### ISSUE TITLE
[3.0beta11] NSClient does not see temp target 

### ISSUE THREAD

**Issue by kristinsmotz** [nightscout/AndroidAPS#1141]
Just discovered that when a temp target is set either manually or via automation on AAPS phone, it can not be seen on NSClient phone.

Aaps:
![received_984383505811064](https://user-images.githubusercontent.com/71758682/148695470-daefff49-e88e-46f0-a9ef-f8f9a6d6fc3a.jpeg)
NSClient:
![Screenshot_20220109-192427_NSClient](https://user-images.githubusercontent.com/71758682/148695482-dac4f300-f61a-4832-a9ef-8172df16620c.jpg)

[AndroidAPS_LOG_1641752708207.log.zip](https://github.com/nightscout/AndroidAPS/files/7835660/AndroidAPS_LOG_1641752708207.log.zip)

**Comment by MilosKozak** [comment]
if the problem is on NS side I need logs from NS as well. and time of occurence

**Comment by kristinsmotz** [comment]
I will try to recreate this afternoon, and include logs from both phones (AAPS phone currently at school). I checked in Nightscout reporter (https://nightscout-reporter.zreptil.de/) and was able to find all the temp targets from yesterday in a report there, so info is coming through to NS, but possibly not to NSClient. 
![bilde](https://user-images.githubusercontent.com/71758682/148755295-c775dc7d-d84c-46f7-938d-531a1c5d2811.png)

As per right now I checked NSClient - Treatments - temp target tab, and could not find any temp targets there for yesterday except one that was cancelled due to no connection I believe. 
![Screenshot_20220110-120021_NSClient](https://user-images.githubusercontent.com/71758682/148755424-57df64c9-2628-4993-a70d-25f1cbfee486.jpg)

**Comment by kristinsmotz** [comment]
I'll try tonight to reproduce and export logs from both phones, then update to RC-1 and try to reproduce error there as well.

**Comment by kristinsmotz** [comment]
I just remembered; i updated our nightscout site 5th january at night, in order to fix a previously reported error with BG check having wrong value in NSClient. I did an update to the latest dev on nightscout. So I would guess that something in that build is causing this error for me now. If updating to RC-1 tonight does not help I will roll back NS to latest master, and see if that does it then report the error there as well.

**Comment by kristinsmotz** [comment]
I decided to revert to master on my nightscout site and can now see temp targets in NSClient. I suspect this commit on the nightscout dev is what caused this issue: https://github.com/nightscout/cgm-remote-monitor/commit/aca8d5ab492f1e356c36f340102044dc961d82aa#diff-5a16ec3fb169ae3b2b0b4d0a810080d451c8910345d86280d1cc2c67d4a178a0

**Comment by MilosKozak** [comment]
so passing TT to NSClient is not working with current NS dev?

**Comment by kristinsmotz** [comment]
That is correct, or at least with the dev as it was on 5th January.

**Comment by kristinsmotz** [comment]
Today had another occurrence of TT not showing up in NSClient, only on AAPS phone. We updated to RC-1 a couple of days ago. The TT came from an automation that runs every Thursday at 10.00. it also posts a message to graph area "Fysak torsdag 10.30-12.00", and sets a temporary 80% profile, both of which showed up on both phones.
 
Screenshots from AAPS: 
![graph](https://user-images.githubusercontent.com/71758682/149370346-0cbd5dbc-c173-47db-ad08-17cd49b19590.jpg)
![treatments](https://user-images.githubusercontent.com/71758682/149370362-00dc03a0-2e1c-434e-9d6f-3437246950af.jpg)
![automation](https://user-images.githubusercontent.com/71758682/149377810-c90ef526-1976-4282-8ea7-390fee294b4b.jpg)

Screenshots from NSClient:
![Screenshot_20220113-165938_NSClient](https://user-images.githubusercontent.com/71758682/149370467-fb58804f-1849-4a24-8a65-db1a83a12fb5.jpg)
![Screenshot_20220113-170019_NSClient](https://user-images.githubusercontent.com/71758682/149370502-ab4d2f4b-0435-413b-a64e-6b6a80e84dd7.jpg)

Log from AAPS: 
[AndroidAPS_LOG_1642089548988.log.zip](https://github.com/nightscout/AndroidAPS/files/7864355/AndroidAPS_LOG_1642089548988.log.zip)

 
If it will help you investigate further, our NS site is https://heddamamonitor.herokuapp.com/
This time it appears that NS didn't catch the TT either:
[NS reporter log.pdf](https://github.com/nightscout/AndroidAPS/files/7864748/NS.reporter.log.pdf)

![bilde](https://user-images.githubusercontent.com/71758682/149380025-1c310185-f360-48f7-995e-e576ba34fe76.png)

I'm having trouble with logs in NSClient, they're either only being put in the /logs folder at random times, or being deleted in random order. I'd really appreciate any advice to fix this so I always can have the logs for the last 24 hours available. Currently this is what the folder on my phone contains:
new logs every 10-20 minutes since 13.26, but still containing logs from 1.41, 2.01 and 2.16 this morning.
![Screenshot_20220113-182255_My Files](https://user-images.githubusercontent.com/71758682/149378843-dfeedef7-4deb-489c-80e3-69d35f5944be.jpg)

**Comment by MilosKozak** [comment]
whithout NSC logs is not possible to resolve the issue. having so many files means there is too much logging enabled. give me a sample of NSC log

**Comment by kristinsmotz** [comment]
[AndroidAPS_LOG_1642369862613.log.zip](https://github.com/nightscout/AndroidAPS/files/7878042/AndroidAPS_LOG_1642369862613.log.zip)
[AndroidAPS_LOG_1642369878670.log.zip](https://github.com/nightscout/AndroidAPS/files/7878043/AndroidAPS_LOG_1642369878670.log.zip)
![received_483391019977595](https://user-images.githubusercontent.com/71758682/149680093-1a273320-ddd9-4f39-9e03-3d51d8b60fc7.jpeg)
![received_484694859882267](https://user-images.githubusercontent.com/71758682/149680096-ef8e3dd5-0009-47a5-b1ac-e9a4e9e96c17.jpeg)
![Screenshot_20220116-231135_NSClient](https://user-images.githubusercontent.com/71758682/149680110-54e6f50f-64df-4975-ab7f-c8fa3a59639e.jpg)


I just did a set of tests to reproduce. 

First test: manual TT , showed up in NSClient
Second test: automation setting TT and Temp profile, did not show in NSClient
Third test: automation setting TT and note, showed up in NSClient. 

Added screenshots from treatments to easily see times to look for in log.

**Comment by MilosKozak** [comment]
sorry i need both: screenshot + logs from AAPS and the same from NSC. I'm not sure what is what and second logs doesn't cover 22:15

**Comment by kristinsmotz** [comment]
I understand. Having trouble with getting phones to send correct logs when I try. I will try to review log settings on both phones and recreate the errors. Do you have recommendations for what to log which will give you enough info without flooding the log with irrelevant stuff? Would this be sufficient on the NSClient phone?

![Screenshot_20220124-103055_NSClient](https://user-images.githubusercontent.com/71758682/150757196-920bf204-f0b1-47cd-8e3b-675b4b347778.jpg)

**Comment by MilosKozak** [comment]
no need to enable anything special.  just logs +- 1h from the event from both devices

**Comment by kristinsmotz** [comment]
OK here goes. Started a TT from Automation at 21.00 (With a temp profile included in the same Automation). 
Info from NSClient phone:
NSClient 3.0-rc3
NSCLIENT
Build: 617cdd681-2022.01.17-16:02
Remote: https://github.com/nightscout/AndroidAPS
Flavor: nsclientrelease
Nightscout version: 14.2.5
Log: 
[AndroidAPS_LOG_1643142836954.log.zip](https://github.com/nightscout/AndroidAPS/files/7937130/AndroidAPS_LOG_1643142836954.log.zip)
Screenshots of Overview and TT tab in Treatments on NSClient phone:
![Screenshot_20220125-213406_NSClient](https://user-images.githubusercontent.com/71758682/151060072-98540638-48c0-4cf3-b58c-e354b723e960.jpg)
![Screenshot_20220125-213415_NSClient](https://user-images.githubusercontent.com/71758682/151060084-2b490acb-5dcc-4c02-ad23-213cb5e3ac8e.jpg)

From AAPS phone:
AndroidAPS 3.0-rc3
Build: 617cdd681-2022.01.17-15:51
Remote: https://github.com/nightscout/AndroidAPS
Flavor: fullrelease
Nightscout version: 14.2.5
Engineering mode enabled
Logs:
[AndroidAPS_LOG_1643142902100.log.zip](https://github.com/nightscout/AndroidAPS/files/7937145/AndroidAPS_LOG_1643142902100.log.zip)
Screenshots from Overview and TT tab in Treatments:
![image](https://user-images.githubusercontent.com/71758682/151060454-5b5c2e96-e71e-449e-b5b4-b1461552c5d2.png)
![image](https://user-images.githubusercontent.com/71758682/151060513-ef226148-62ae-4acd-be11-e8605b00dd37.png)

**Comment by kristinsmotz** [comment]
As previously mentioned, it appears this error only occurs when using an Automation to set a temp % profile AND a temp target in the same automation.

**Comment by MilosKozak** [comment]
related to bug in NS
I already created a fix for that https://github.com/nightscout/cgm-remote-monitor/pull/7285 but it's not part of NS yet
