### ISSUE TITLE
[3.0-rc1] Some strange icons on bolus wizard

### ISSUE THREAD

**Issue by vmichalec** [nightscout/AndroidAPS#1150]
I noticed some strange icons on bolus wizard in packed form

![Screenshot_20220110-184500_AndroidAPS](https://user-images.githubusercontent.com/24793786/148814248-cdd6ceb3-eab6-43e4-9311-e209cd9a2a71.jpg)

vs. unpacked
![Screenshot_20220110-184508_AndroidAPS](https://user-images.githubusercontent.com/24793786/148814263-64e10332-4095-4ef8-98a2-f9297c8db0b3.jpg)

**Comment by parapenT1sta** [comment]
Are you serious? What is strange?
It means to show you "BG" "Trend" "COB" and "IOB" options... that when you click on view they disappear because they are shown on the list...

**Comment by vmichalec** [comment]
Ok, so it is a feature. Thanks.

**Comment by parapenT1sta** [comment]
> Ok, so it is a feature. Thanks.
![photo 100 18-11-49](https://user-images.githubusercontent.com/608650/148817579-14de74d7-e7ba-479f-9b3e-61eac860ca7d.jpg)
