### ISSUE TITLE
[3.0 RC1] profile shift not resulting in changed carb-ratio in Bolus Wizard

### ISSUE THREAD

**Issue by hartlijn** [nightscout/AndroidAPS#1153]
Shifting profile does not lead to correct ratios to be used in Bolus Wizard.
I shifted - 1 hour and in the wizard still the Carbratio of the original unshifted value is used. It should have used 5.5 but it took 6.2. 
![Screenshot_20220111-130646](https://user-images.githubusercontent.com/28272471/148942509-857c5a97-8326-4992-b9ea-d0c508daffdd.jpg)
![Screenshot_20220111-130635](https://user-images.githubusercontent.com/28272471/148942561-ff166661-85e2-499c-89b0-5b5a19d10488.jpg)
![Screenshot_20220111-130714](https://user-images.githubusercontent.com/28272471/148942603-0db5396d-6ec8-4b96-bb82-0e56fb981900.jpg)
[AndroidAPS_LOG_1641903106869.log.zip](https://github.com/nightscout/AndroidAPS/files/7846460/AndroidAPS_LOG_1641903106869.log.zip)

**Comment by Philoul** [comment]
I don't think there is a bug here...
In your example, you shifted your profile 1h earlier, so at 1.06 PM, AAPS will take values of 2.06PM in your profile, and IC is 6.2 in your profile between 1PM and 5PM...

**Comment by hartlijn** [comment]
Hmm, how stupid. Sorry.

Op di 11 jan. 2022 19:30 schreef Philoul ***@***.***>:
