### ISSUE TITLE
Re-order icons in Bolus Wizard

### ISSUE THREAD

**Issue by parapenT1sta** [nightscout/AndroidAPS#1154]
I think it would be nice if the icons in bolus wizard would follow the right order of the detailed list, the actual icons order is BG - TREND - INSULIN - CARBS. I think Insulin should swap with carbs.

![photo 100 18-11-49](https://user-images.githubusercontent.com/608650/148956384-8fd3af44-8174-49d0-8e39-0de3ac5810d2.jpg)

**Comment by Philoul** [comment]
Good proposal, I'll prepare a PR...

**Comment by parapenT1sta** [comment]
Thank you!
