### ISSUE TITLE
[3.0 RC1] Dash pod initialization after discarding pod is failing on a wrong bluetooth address

### ISSUE THREAD

**Issue by filipwoz** [nightscout/AndroidAPS#1159]
Repro Steps:
- try to deactivate dash pod
- break up the procedure and click on Discard Pod
- try to activate a new pod
Result:
Unhandled java Error message: 
![image](https://user-images.githubusercontent.com/20597551/149184646-5ccea16f-932d-44e3-a760-734bbce94162.png)

Expected:
After discarding a pod a new pod should be possible to activate without issues

Seems that by discarding a Pod cleanup of the buetooth connection address does not happen.

Logs attached:
[AndroidAPS._2022-01-12_07-01-11_.zip](https://github.com/nightscout/AndroidAPS/files/7856366/AndroidAPS._2022-01-12_07-01-11_.zip)
Note: do not wonder I did quite a strange workaround after that to make it running again (probably was not needed):
- Downgraded to 3.0 beta 11
- tried to activate a new pod (again with the same error)
- tried to deactivate the old pod and again discarded it
- tried to activate a new pod again - then it worked!
- Upgraded back to 3.0 RC1
I suppose what really helped was probably the re-discarding of the old POD and not the version downgrade.

**Comment by avereha** [comment]
How did you "break up the procedure"?

**Comment by filipwoz** [comment]
> How did you "break up the procedure"?

I am not sure as my son did it without me looking at than. I thought you could read it from the logs.
I think he was telling that it was taking a long time (or even showing a timeout message) and then he pressed the button to discard the pod.
