### ISSUE TITLE
3.0rc1 SMB disabled 

### ISSUE THREAD

**Issue by winni67** [nightscout/AndroidAPS#1169]
Hello,

perhaps a new feature or possible a bug. I don‘t use my 3.0rc1 version for active looping. So I don‘t know, if the SMBs are disabled in 3.0rc1 or earlier in one of the beta versions.
When I started testing the 3.0 versions with beta1, then the SMBs are working.
But today, I saw this message (see picture). SMBs are enabled in the configuration.
I use xDrip+ (slave) for generating the glucose values on my AAPS3.0 test system.
Kind regards
![7D632E63-DD92-455E-8CCA-E0723C57B422](https://user-images.githubusercontent.com/6819067/149363113-e762abf4-039b-405f-8e72-e86cade48d3c.png)

**Comment by MilosKozak** [comment]
what is on the top of this tab?

**Comment by winni67** [comment]
![74723519-4CA7-4A11-83E8-E60900321560](https://user-images.githubusercontent.com/6819067/149498208-98382864-dba1-4c69-b7b4-66d0bd23d5ef.png)

**Comment by parapenT1sta** [comment]
Do you have Red warning sign on the main screen regarding the BG readings?

**Comment by winni67** [comment]
On my master system: xDrip+ with Dexcom G6 Native mode, xDrip+ master for followers. On my test system with AAPS 3.0: xDrip+ Sync Follower.
There is no red warning sign on the main screen of my AAPS3.0 test system.

**Comment by winni67** [comment]
![9B2CDFE4-2BA0-4702-BC7E-DBD5C9A84A39](https://user-images.githubusercontent.com/6819067/149524423-28590f21-770a-4272-ab81-3489228c4dff.png)
![A6409714-4D71-434E-86F7-65717F068E90](https://user-images.githubusercontent.com/6819067/149524430-2b7f893b-0969-4d54-86ef-6f2f8b1d0abe.png)
![456A7A6D-3B96-4CF0-8EA5-81A984FB0E47](https://user-images.githubusercontent.com/6819067/149524432-ec58a59a-c07d-446e-8d88-f6bff3cdbcab.png)
![7DDB2104-EE16-4DAF-B4EF-ED552DA6AC51](https://user-images.githubusercontent.com/6819067/149524433-a91a45d9-54c6-4076-831c-8978adb13d22.png)

**Comment by MilosKozak** [comment]
hmmm seems to be ok
then provide logs pls

**Comment by overfrenk** [comment]
max minutes of basal to limit smb to 120 is very high,limit to max 90 for test.

**Comment by overfrenk** [comment]
always to test : set safety multiplier to 5  both options and maximum total IOB to 25U.

**Comment by winni67** [comment]
Logs send via mail.

**Comment by winni67** [comment]
The mail address in AAPS 3.0 „SEND LOGS BY EMAIL“ xxx@androidaps.org can‘t be reached. The domain androidaps.org doesn‘t exist.

**Comment by MilosKozak** [comment]
add it here directly

**Comment by winni67** [comment]
[AndroidAPS_LOG_1642191610498.log.zip](https://github.com/nightscout/AndroidAPS/files/7877381/AndroidAPS_LOG_1642191610498.log.zip)

**Comment by MilosKozak** [comment]
From what I see you are using BG source not supporting SMB always and you don't enter carbs. Thus COB is always zero and SMB is forced disabled

**Comment by winni67** [comment]
Yes, that‘s already mentioned in the Constraints Part of the „OPENAPS SMB“ section. But when xDrip+ Sync Follower isn‘t allowed as BG source, then I can‘t test AAPS 3.0 on my test system anymore. The option to set a second G6 is possible, but then, I have to wear a lot of additional stuff close to me. Using it as active loops system is not my favorite.
