### ISSUE TITLE
Numeric keyboard and timeout for application and bolus password

### ISSUE THREAD

**Issue by ideaweb** [nightscout/AndroidAPS#1170]
For our child its not possible to lock the screen for several reasons. Thats why i am happy that such passwords exists. But with having a tiny phone its not easy to enter a password easily. 

- Is it possible to add a new type "Custom PIN" (numeric password), its the same like "Custom password" but if selected it shows the numeric keyboard by default, but only for application and bolus password, for settings and master password i think it would be not a good idea.

- Nice to have would be to have an option "timeout" that showing the password popup again does not depends only on "focus". I mean, to not ask for the password e.g. for 2 minutes after last action/click.

- At the beginning i worked with bolus password, that the app can be used without entering the password. For carbs and bolus it works nice, but for other actions, like changing TBR, profile and its values etc. the password is not requested. But maybe its controlled by settings password (i did not check).

But everything is nice2have and not important. Thx for the great work!!

**Comment by Andries-Smit** [comment]
Regards: 

> "At the beginning i worked with bolus password, that the app can be used without entering the password. For carbs and bolus it works nice, but for other actions, like changing TBR, profile and its values etc. the password is not requested. But maybe its controlled by settings password."

This should be improved in PR #1406
