### ISSUE TITLE
3.0 RC1 MDT unable to Scan for Rileylink

### ISSUE THREAD

**Issue by jroth-haj** [nightscout/AndroidAPS#1173]
I wanted to Change to my second RL.
So I removed the current RL and started scanning without success.

I had to import my settings to geht it running again.

Pixel 5, Android 12, RileyLink and OrangeLink

**Comment by MilosKozak** [comment]
this is not enough info to provide any help

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/e2bdc348349e6894c05eb0ba9809e378e10cb9d1

**Comment by Philoul** [comment]
Can we have the same permission issue in Insight driver with Android 12?

**Comment by MilosKozak** [comment]
yes
