### ISSUE TITLE
[30 rc1] AAPS shows double down arrow at 283 and increasing delta value.

### ISSUE THREAD

**Issue by 69nobody** [nightscout/AndroidAPS#1177]
![grafik](https://user-images.githubusercontent.com/94611099/149589590-f8ebf049-b297-4d54-9fb8-10b9a3629390.png)

Although the blood glucose level is rising, two downward arrows are displayed in the AAPS interface.
In addition, I noticed that when entering carbohydrates, the message "Bolus cannot be delivered" is displayed and you can only stop the action.
An input via the bolus calculator with carbohydrates has worked.
Logs are attached.
[AndroidAPS._2022-01-14_22-20-06_.0.zip](https://github.com/nightscout/AndroidAPS/files/7873393/AndroidAPS._2022-01-14_22-20-06_.0.zip)

**Comment by mick711** [comment]
I read last week same issue and if you see that it's a Xdrip problem .

**Comment by 69nobody** [comment]
thanks for this information. I will close my issue.

**Comment by 69nobody** [comment]
The same problem I described was reported by someone else a few days ago. This information was sent to me by mick711.
