### ISSUE TITLE
[3.0 RC1] Separate entry of carbohydrates not possible.

### ISSUE THREAD

**Issue by 69nobody** [nightscout/AndroidAPS#1178]
When entering carbohydrates, the message "Bolus cannot be delivered" is displayed and you can only cancel the action.
No carbohydrates are then added.
An input via the bolus calculator with carbohydrates worked.
Protocols are attached.
[AndroidAPS._2022-01-14_22-20-06_.0.zip](https://github.com/nightscout/AndroidAPS/files/7873617/AndroidAPS._2022-01-14_22-20-06_.0.zip)

**Comment by MilosKozak** [comment]
time of occurence?

**Comment by 69nobody** [comment]
In my memory, this must have happened in the evening. When I search my logs in AAPS I find only one entry with 25g carbohydrates at 20:58.

**Comment by MilosKozak** [comment]
this time is not log file

**Comment by 69nobody** [comment]
Ok, sorry for my imprecise expression. I said that the input only for the carbohydrates did not work. However, the input via the bolus calculator worked. The input that worked was at 20:58. So the error occurred approximately between 20:50 and 20:58. There should be something in the log. If there was nothing to be found at this time, the behaviour was probably not recorded in the log.

**Comment by MilosKozak** [comment]
log is from 21:45

**Comment by 69nobody** [comment]
Are the log files not continuously updated for one day?! Does the log file have to be exactly from 20:50 to 20:58? If the error cannot be found, then please take care of the other messages and close my issue.

**Comment by MilosKozak** [comment]
you can open the file yourself and see the time
