### ISSUE TITLE
Duplicate CGM data as the readings , in virtual pump and data coming from Knighscout not via xdrip

### ISSUE THREAD

**Issue by g7kbr** [nightscout/AndroidAPS#1179]
AndriodAPS 3.0-rc1

So running in virtual mode with a Medtronic 722.  The CGM is currently coming from my Knightscout account.  I am on objective 5.  I seem to have duplicate CGM data as the readings are very close multiple times.

I am almost at a stage to go Omnipod Dash, my CGM data is from a libre2.

I am a bit concerned about the red triangle.

Any feedback would be great.  I see that it is users on G6 dexcom which seem to see this.

Log file attached, and 3 x JPG's showing issue.  Using Build: 86ec769f6-2022.01.12-18:29

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in t
![IMG_7288](https://user-images.githubusercontent.com/27280641/149617894-ab584020-1801-46db-abb4-71554eb764b
[Log Export.txt](https://github.com/nightscout/AndroidAPS/files/7874715/Log.Export.txt)
0.jpg)
he About dialog in the app, when pressing the three dots in the
![IMG_7290](https://user-images.githubusercontent.com/27280641/149617893-829e6e30-2183-4774-a1e8-3537aef8b3d2.jpg)

![IMG_7289](https://user-images.githubusercontent.com/27280641/149617888-981f42d7-4fff-4b5b-89e9-a0a9aff1a982.jpg)

  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/EN/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new
[Log Export.txt](https://github.com/nightscout/AndroidAPS/files/7874821/Log.Export.txt)
![IMG_7288](https://user-images.githubusercontent.com/27280641/149619725-7c683c35-bac1-476b-9bcd-fee28a4f1ae3.jpg)

**Comment by g7kbr** [comment]
> AndriodAPS 3.0-rc1
> 
> So running in virtual mode with a Medtronic 722. The CGM is currently coming from my Knightscout account. I am on objective 5. I seem to have duplicate CGM data as the readings are very close multiple times.
> 
> I am almost at a stage to go Omnipod Dash, my CGM data is from a libre2.
> 
> I am a bit concerned about the red triangle.
> 
> Any feedback would be great. I see that it is users on G6 dexcom which seem to see this.
> 
> Log file attached, and 3 x JPG's showing issue. Using Build: [86ec769](https://github.com/nightscout/AndroidAPS/commit/86ec769f6b1c711a9fd0e694681421f7c68858e3)-2022.01.12-18:29
> 
> ## Reporting bugs
> * **Note the precise time the problem occurred** and describe the circumstances and steps that caused
>   the problem
> * Note the Build version (found in t
>   ![IMG_7288](https://user-images.githubusercontent.com/27280641/149617894-ab584020-1801-46db-abb4-71554eb764b
>   [Log Export.txt](https://github.com/nightscout/AndroidAPS/files/7874715/Log.Export.txt)
>   0.jpg)
>   he About dialog in the app, when pressing the three dots in the
>   ![IMG_7290](https://user-images.githubusercontent.com/27280641/149617893-829e6e30-2183-4774-a1e8-3537aef8b3d2.jpg)
> 
> ![IMG_7289](https://user-images.githubusercontent.com/27280641/149617888-981f42d7-4fff-4b5b-89e9-a0a9aff1a982.jpg)
> 
> upper-right corner).
> 
> * Obtain the app's log files, which can be found on the phone in
>   _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
>   See https://androidaps.readthedocs.io/en/latest/EN/Usage/Accessing-logfiles.html
> * Open an issue at https://github.com/nightscout/AndroidAPS/issues/new
![IMG_7288](https://user-images.githubusercontent.com/27280641/149619657-b2b84c55-2871-4fd7-9cd2-b74b2098b97d.jpg)
[Log Export.txt](https://github.com/nightscout/AndroidAPS/files/7874819/Log.Export.txt)
[Log Export.txt](https://github.com/nightscout/AndroidAPS/files/7874820/Log.Export.txt)

**Comment by g7kbr67** [comment]
Re-opened as I didn't realise I closed it.
