### ISSUE TITLE
Cannot "Profile Switch"

### ISSUE THREAD

**Issue by christinadamianou** [nightscout/AndroidAPS#1181]
build e39014962-2021.12.19-13:34 - AndroidAPS 3.0-beta11
Using Pump Omnipod DASH. BG Source Glunovo
Go to Actions > Profile Switch
Press the button.
Button turns to disabled for some seconds and turns back to normal without opening the window to let me change my profile.

Log Files:
[AndroidAPS._2022-01-06_17-06-36_.0.zip](https://github.com/nightscout/AndroidAPS/files/7875539/AndroidAPS._2022-01-06_17-06-36_.0.zip)

**Comment by MilosKozak** [comment]
it generaly means there is no valid profile to switch to
