### ISSUE TITLE
SNOOZE text inside the snooze button is not responsive

### ISSUE THREAD

**Issue by dar-kod** [nightscout/AndroidAPS#1183]
AndroidAPS 3.0-rc1
Build version: 86ec769f6
Phone: Poco F3
Settings -> Display -> Text size: L

Maybe this is a phone specific, but I find this not optimized:

![photo_2022-01-15_23-55-08](https://user-images.githubusercontent.com/24446806/149640204-58d3ed2f-2aed-431d-a955-6d1bd14baaad.jpg)

**Comment by MilosKozak** [comment]
AAPS is not so optimize for very small screens. if you rotate to landscape is it OK?

**Comment by dar-kod** [comment]
If I rotate to landscape, it is the same.
![photo_2022-01-17_09-44-18](https://user-images.githubusercontent.com/24446806/149736942-ba182a37-d946-40ee-b385-852bf47d5a4f.jpg)

**Comment by nicoleloop** [comment]
The snooze option has never worked for me in the 2.5 years I have used AndroidAPS. Has it worked for everyone else all this time?

**Comment by dar-kod** [comment]
@MilosKozak, the issue in my case is layout. Is it possible to fix it?

**Comment by MilosKozak** [comment]
improved by https://github.com/nightscout/AndroidAPS/commit/72e73f604f124ea08d3dc0a06a6765dbe9fe4899

**Comment by dar-kod** [comment]
Thank you.
