### ISSUE TITLE
The time length of the yellow triangle above the BG value should be greatly shortened

### ISSUE THREAD

**Issue by dar-kod** [nightscout/AndroidAPS#1185]
AndroidAPS 3.0-rc1
Build version: 86ec769f6

The yellow triangle appeared after changing the G6 transmitter and sensor. Some say that the yellow triangle appears due to the missing value of BG and lasts for about 30 or 36 hours. I don't see the point in the yellow triangle being present for so long just because of one missing value.

**Comment by Els3401** [comment]
I have the same experience: a yellow triangle because of one missing value (sometimes after a reboot, ...).
AndroidAps 3.O-rc1

**Comment by MilosKozak** [comment]
missing value is aproximated without triangel

**Comment by MilosKozak** [comment]
data scanned is exactly the same that is used for calculations
