### ISSUE TITLE
V3 RC2 Bug : Message new version available 

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1190]
The RC1 bug is still there in RC2. There is a message telling that there is a new version since 1 day and closed loop will stop in a week and 14 days etc.

There is no newer version than RC2...

![Screenshot_20220117-104329_One UI Home.jpg](https://user-images.githubusercontent.com/76626474/149746598-f9c53941-8552-4df7-89c9-d3509fdbb9c8.jpg)

**Comment by Alamo04** [comment]
> The RC1 bug is still there in RC2. There is a message telling that there is a new version since 1 day and closed loop will stop in a week and 14 days etc.
> 
> There is no newer version than RC2...
> 
> ![Screenshot_20220117-104329_One UI Home.jpg](https://user-images.githubusercontent.com/76626474/149746598-f9c53941-8552-4df7-89c9-d3509fdbb9c8.jpg)

Are you sure that this is RC2 ? Perhaps you installed RC1 again ?
Don't see that message with RC2.

**Comment by robertrub** [comment]
I have checked and I have RC2 installed.

![Screenshot_20220117-092006_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/149756998-d20d8fdf-a4b7-427a-bb6d-d1505a7e3307.jpg)

**Comment by happygirlnyc70** [comment]
I can confirm, I also got this message rc2 
![Screenshot_20220117-080924](https://user-images.githubusercontent.com/65825958/149775198-447d5e11-697f-445f-a560-49cb8920e1c3.png)

**Comment by Alamo04** [comment]
Confirmed,  just now I become this message too.
Version runs 16h 45 minutes now.

**Comment by robertrub** [comment]
Same issue persists on RC3 too.

![Screenshot_20220118-103551_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/149910580-676f9206-6016-4601-9165-751bf36754a7.jpg)
![Screenshot_20220117-183707_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/149910603-3b8de09c-f04d-4307-bda6-e0eea1387568.jpg)

**Comment by happygirlnyc70** [comment]
The error is still present for rc3
![Screenshot_20220118-072611](https://user-images.githubusercontent.com/65825958/149937312-9780ce3d-559e-469c-b05d-e756dd5403ed.png)

**Comment by sboernemeyer** [comment]
CONFIRM
also in RC3

**Comment by catherinefranq** [comment]
oui egalement pour moi en rc3
![Screenshot_20220120-071804_AndroidAPS 1](https://user-images.githubusercontent.com/69969351/150320508-3a934f89-3218-4288-8873-c235e143a381.jpg)

**Comment by nicoleloop** [comment]
Oh good I thought I was losing my mind lol. Yes, every night for the past 2-3 nights in a row at exactly 1am the same message appears on my phone's app as well. Why only at 1am? No clue, but it is an annoying time for it to appear...

**Comment by robertrub** [comment]
Mine is around 10AM (GMT+1). Probably depends on you time zone.

**Comment by MilosKozak** [comment]
once in 24h. depends on when the last check was done

**Comment by nicoleloop** [comment]
Oh, of course! Thanks for the quick response Milos. 🙂

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________
