### ISSUE TITLE
3.0-rc3 SMB Script Debug output

### ISSUE THREAD

**Issue by mountrcg** [nightscout/AndroidAPS#1193]
small formating error in the Script Debug output on SMB plugin:
![Screenshot_20220117-173657~2](https://user-images.githubusercontent.com/539276/149808507-8bba7b69-8b68-404e-af06-c9d95fe77010.png)
.. was already occurring at rc1

**Comment by MilosKozak** [comment]
duplicated to https://github.com/nightscout/AndroidAPS/issues/912
