### ISSUE TITLE
Silent Crash of AAPS

### ISSUE THREAD

**Issue by Futaba12** [nightscout/AndroidAPS#1194]
Reporting bugs
--------------
Setup : 
- Phone One plus Nord with Android 11
- AAPS version : 2.8.2.19-dev (Build 0a1cbdb91)
- All battery optimization are deactivated
- BG from BYODA only in version 1.7.03

AAPS has crash silently. The first screenshot shows around 3pm30 (17 january 2021) that AAPS stops everything and the most problematic thing is that the pod doesn't fallback on my basal profile until I check my phone around 6pm. The second screenshot shows the pod history ans we can see a TBR set to 0u at 3pm24 precisely and another TBR set at 3.2u at 6pm14 when I check my phone. In this time frame, my bg has rised (Look at the last screenshot in red rectangle).

I also attach the AAPS logs just after the issue observed.

[AndroidAPS_LOG_1642440166854.log.zip](https://github.com/nightscout/AndroidAPS/files/7888178/AndroidAPS_LOG_1642440166854.log.zip)
![Screenshot_20220117-181249](https://user-images.githubusercontent.com/15014600/149918770-761e1cbc-bb54-4242-be5b-c2192d3816e1.jpg)
![Screenshot_20220118-013735](https://user-images.githubusercontent.com/15014600/149918784-85714ec1-877e-4965-aaaf-06d97abe64b2.jpg)
![Screenshot_20220118-014841__01](https://user-images.githubusercontent.com/15014600/149918800-fa819156-4572-4f12-95dc-fad3363845fb.jpg)

**Comment by MilosKozak** [comment]
sorry, reason is not visible in logs

**Comment by Philoul** [comment]
@Futaba12 do you have unchecked items in "Maintenance/Paramètres journal" (in french ;-) ) ?
=> If yes, can you "enable" all items (to get maximum informations in log file and help us understanding what's your problem?
We cannot see any useful information in your log to be able to understand what could be the root cause of your crash...

**Comment by ToreBj** [comment]
![image](https://user-images.githubusercontent.com/23278852/150019876-0c0ec920-1b28-444c-bf65-69849cb768e9.png)
Have you disabled these?

**Comment by Futaba12** [comment]
> @Futaba12 do you have unchecked items in "Maintenance/Paramètres journal" (in french ;-) ) ?
> => If yes, can you "enable" all items (to get maximum informations in log file and help us understanding what's your problem?
> We cannot see any useful information in your log to be able to understand what could be the root cause of your crash...

Here a screenshot of the log parameters :

![Screenshot_20220118-225714.jpg](https://user-images.githubusercontent.com/15014600/150025280-0e83e632-3a11-4aef-8ae6-25e9a923a51e.jpg)
