### ISSUE TITLE
Disable SMS Notification for Pump Basal Update

### ISSUE THREAD

**Issue by bobhome007** [nightscout/AndroidAPS#1202]
- Permanently an issue since RC1

- 09386a0b7-2022.01.18-22:21

When a local profile is changed by a profile %, AAPS sends an SMS notification "Basal Profile in Pump Updated"

Can this be disabled and changed into a notification option that can be enable/disable in the settings ?

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/e5ce0ce95fdd4cc11735f30b807d911c8d49aa25
