### ISSUE TITLE
NSClient not displaying AutoSense used currently on the main AAPS device

### ISSUE THREAD

**Issue by filipwoz** [nightscout/AndroidAPS#1203]
Observed with v3 RC3
I have AutoSense on my main AAPS device turned on which is displaying a higher or lower sesitivity on the main device. 
On the NSClient device however these changes are not displayed at all - Autosense Icon stays as on the screenshot all the time:
![image](https://user-images.githubusercontent.com/20597551/150319392-ab2c11b7-2e31-496a-9604-789ae504ddcd.png)
Do I need to setup the client with some special setting to receive this information or is it a bug?

**Comment by JohhnyP** [comment]
Bumping this insteadf of opening a new one.
Does anyone has any insight regarding it?
Dev branch has the same behavior?

**Comment by MilosKozak** [comment]
Closed for inactivity. Create new issue is if you still see the problem on latest branch
