### ISSUE TITLE
Feature Request: Alternative to SMS confirmation replies to save costs

### ISSUE THREAD

**Issue by filipwoz** [nightscout/AndroidAPS#1204]
An experience from the field:
- My child uses a phone with a minimal mobile contract including 100 free SMS - when started using SMS commands I used it up in 2 days (including doubled commit messages to 2 associated phones as recommended in the documentation) and had a lot of costly SMS messages in the next days before I noticed that
It would be useful to have an alternative to that:
- either an option to turn off the SMS confirmation completely (for me they are not necessary as I can see the confirmation in the NSClient by looking at the changes when they happened) 
- or another communication channel then SMS like What's App or Telegram etc.

**Comment by MilosKozak** [comment]
skip confirmation coud be dangerous. with poor internet connection there would be nothing visible in NS
send message programmatically using other app is not possible as I know
