### ISSUE TITLE
Limits to max_iob and max_basal

### ISSUE THREAD

**Issue by missmagoo** [nightscout/AndroidAPS#1214]
https://github.com/nightscout/AndroidAPS/blob/f28b04226e22789e1558365a03475522db44536a/app/src/main/res/xml/pref_openapssmb.xml#L14

https://github.com/nightscout/AndroidAPS/blob/f28b04226e22789e1558365a03475522db44536a/app/src/main/res/xml/pref_openapssmb.xml#L26

The patient type for pregnancy has a hard-coded limit of 45U for max_iob and a limit of 25U/hr basal, but lines 14 and 26 have limits set to 12 and 25, the "insulin resistant adult" patient type limits. The app physically won't allow you to enter numbers greater than these, and should be remedied to reflect all the newest patient types.

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/8f7b178c0427f1a30e61e43ad35b37b7cb50154a
