### ISSUE TITLE
[3.0-rc3] Prime/fill on disconnected pump creates bolus entry

### ISSUE THREAD

**Issue by vmichalec** [nightscout/AndroidAPS#1216]
Hi, I did following:

1) Pump was disconnected.
2) Prime/fill button used twice to send 0.25 and 0.25 units.
3) Pump was auto-reconnected after 60 mins.

- What I have got are two entries of 0.25 units. First one is prime/fill (expected) but second one is normal bolus entry counted in IOB (unexpected). Here with Dana-RS pump. Here are logs [AndroidAPS.zip](https://github.com/nightscout/AndroidAPS/files/7921196/AndroidAPS.zip)

- In my second setup with dana-r pump I did this case again but it worked without problems.

- I also noticed that if the pump auto-reconnects there is no entry about it in treatments.

![main_screen](https://user-images.githubusercontent.com/24793786/150693753-820ba8ec-e5d6-4a76-afb9-aa025d3f408a.png)
![actions](https://user-images.githubusercontent.com/24793786/150693757-343b9709-8950-459f-9aac-54d451fe1d53.png)
![treatments](https://user-images.githubusercontent.com/24793786/150693762-aee874c4-3634-4414-8cd1-b12dfe950ced.png)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/983b31866da865253e69d1af84508e0a945cb408
