### ISSUE TITLE
Eat Reminder (high glucose/time)



### ISSUE THREAD

**Issue by annushkiii** [nightscout/AndroidAPS#1219]
Hello, not issue, but improvement idea.

when using the bolus wizard my sugar is over my target, I get a pop up like "you shoud eat later [...] should remind you?". If I choose yes, the reminder rings only when my sugar is unter/at my target. 

This is confusing, because I can enter a reminder time. I assume that I get a reminder exact in the time, which I enter. 

If I enter for example 30 minutes, and my sugar is over my target to get a reminder "You should eat, but your sugar is over target. Should remind when you reached your target?" or somehing like this.

**Comment by MilosKozak** [comment]
haw can you enter reminder time?

**Comment by annushkiii** [comment]
![Screenshot_20220124-203452.png](https://user-images.githubusercontent.com/80789970/150851805-b814fff3-28b8-4f40-b8dc-20de1b13fc86.png)

**Comment by annushkiii** [comment]
![Screenshot_20220124-203452~2.png](https://user-images.githubusercontent.com/80789970/150851890-3104607a-b44d-43cc-9431-112e320cbfca.png)
