### ISSUE TITLE
Nightscout crashes with AndroidAPS 3.0 RC3 

### ISSUE THREAD

**Issue by vagtil2005** [nightscout/AndroidAPS#1221]
We are using the version 3.0 RC3 (exact built Build: 617cdd681-2022.01.17-15:57) with Nightscout version: 14.2.5 and DanaRS. Whenever we are trying to make a profile change through NS Client, Nightscout Crashes and needs a Dyno restart in order to get started again. I am attaching the log files from AndroidAPS, NSClient and Nightscout as a screenshot with the error message we are getting in NS Client. There was no problem with the 2.8.2.1 version
[AndroidAPS-nsclient.log](https://github.com/nightscout/AndroidAPS/files/7932202/AndroidAPS-nsclient.log)
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/7932204/AndroidAPS.log)
[Heroku-logs-1643097339580.txt](https://github.com/nightscout/AndroidAPS/files/7932225/Heroku-logs-1643097339580.txt)
![271817632_625149865436200_6672997397797207742_n](https://user-images.githubusercontent.com/42769910/150948795-0b32a737-4981-479c-90c8-45b42c90327d.jpeg)

**Comment by MilosKozak** [comment]
what do you see in NS heroku log?

**Comment by vagtil2005** [comment]
I have uploaded the file. I am not sure if this is the correct timing though. So when I see the same problem again I will export the log files to see them in more detail.

**Comment by MilosKozak** [comment]
no crash in this part of log

**Comment by vagtil2005** [comment]
sorry about but I am not aware to extract the whole log file. can anyone give me some instructions?

**Comment by MilosKozak** [comment]
i'm afraid they are not stored. you must copy text when this happen

**Comment by vagtil2005** [comment]
[heroku-logs-1643222036334.txt](https://github.com/nightscout/AndroidAPS/files/7944295/heroku-logs-1643222036334.txt)

I think that this is the correct one. happened right now

**Comment by vagtil2005** [comment]
and an assorted screen from NSClient messages 
![viber_image_2022-01-26_20-36-53-724](https://user-images.githubusercontent.com/42769910/151225713-ab0107eb-3d1c-4c30-a2bc-019761e10f1b.jpg)
t

**Comment by vagtil2005** [comment]
[heroku-logs-1643222338526.txt](https://github.com/nightscout/AndroidAPS/files/7944326/heroku-logs-1643222338526.txt)

another one with the errors

**Comment by vagtil2005** [comment]
and the assorted screensho
![viber_image_2022-01-26_20-36-53-724](https://user-images.githubusercontent.com/42769910/151226315-f96d6e38-ffe5-41e8-9c89-9abdcf6dffef.jpg)
t

**Comment by MilosKozak** [comment]
i§m getting this one too time to time. there is a PR with fix but is not merged yet https://github.com/nightscout/cgm-remote-monitor/pull/7284
the only solution now is clear treatment collection

**Comment by mountrcg** [comment]
for me it happens on SGV transmits, as you can see on [discord](https://discord.com/channels/629952586895851530/629954570394533889/936282110950510732)
<img width="1360" alt="Bildschirmfoto 2022-01-27 um 16 36 47" src="https://user-images.githubusercontent.com/539276/151391652-326060c0-d19f-4383-971a-75bb0759d1a6.png">
looking at the NS-DB I see some BG's are duped

**Comment by mountrcg** [comment]
I deleted the duplicated entries in NS DB and restarted dyno - hpppened again - crash.log attached

[crash.log](https://github.com/nightscout/AndroidAPS/files/7951764/crash.log)

**Comment by MilosKozak** [comment]
don't you have Dxcom bridge enabled?

**Comment by mountrcg** [comment]
bridge is disabled

**Comment by mountrcg** [comment]
@MilosKozak  strangely since yesterday at no dups happened again, but I did not do anything
<img width="965" alt="Bildschirmfoto 2022-01-28 um 12 00 06" src="https://user-images.githubusercontent.com/539276/151535738-36bd32bc-4c6b-4853-b7be-949aad93c173.png">

**Comment by mountrcg** [comment]
btw if I let xdrip upload the G6 BYODA BG'S to NS instead of AAPS the dataset is more complete with noise information
<img width="1611" alt="Bildschirmfoto 2022-01-28 um 12 05 28" src="https://user-images.githubusercontent.com/539276/151536484-c908b44e-35cd-40de-965f-9ca3d1babf90.png">

**Comment by MilosKozak** [comment]
duplicated values were not comming from AAPS. AAPS always fill "isValid" field
