### ISSUE TITLE
Feature Request: Leak detection 

### ISSUE THREAD

**Issue by crizz6396** [nightscout/AndroidAPS#1223]
One of the biggest issues with pods is occlusions & leakage.  If there was a way to identify a leak by too little pressure that would be incredibly useful.

**Comment by MilosKozak** [comment]
I believe it's close to impossible distinguish between sensitivity change, forgotten bolus, leaking infusion set etc within reasonable period of time

**Comment by crizz6396** [comment]
It would have to be during a bolus.  Even if there was a way to show the
pressure change.  I'm assuming an occlusion is detected when pressure
builds up.  What I don't know is how omnipod or other pumps report the
value.  It would just be a useful tool to have when troubleshooting.

Yesterday I went live for the first time and trying to determine why all of
a sudden my bg was going high after bolusing multiple times.  It appeared I
wasn't getting all my insulin.  It was almost like I was getting no basal.
Hopefully today goes better.

**Comment by MilosKozak** [comment]
this value is not sent outside the pump

**Comment by crizz6396** [comment]
Damn...
