### ISSUE TITLE
3.0 RC3 | No bg received while values in xdrip tab

### ISSUE THREAD

**Issue by bargro1991** [nightscout/AndroidAPS#1227]
This is the second time I experience this issue, using FSL2/xDrip+/ and AAPS 3.0 Rc3. Samsung Galaxy S9
AAPS is stating the last received BG is 149 minutes ago, while in de xDrip tab it shows the BG values like it should.
After a restart of AAPS the values show up in the main screen again.

![Screenshot_20220126-092906_AndroidAPS](https://user-images.githubusercontent.com/61165833/151129275-5b9004cc-5474-4aad-aa7f-9b246a889de9.jpg)
![Screenshot_20220126-092912_AndroidAPS](https://user-images.githubusercontent.com/61165833/151129284-152b5f3d-3e87-4449-94f8-5e00a67023d4.jpg)

**Comment by MilosKozak** [comment]
log file?

**Comment by bargro1991** [comment]
Apologies
[AndroidAPS_LOG_1643205481190.log.zip](https://github.com/nightscout/AndroidAPS/files/7944480/AndroidAPS_LOG_1643205481190.log.zip)

**Comment by bargro1991** [comment]
i'm afraid the logs that correspond with these events are gone, is there any way to get them back?

**Comment by MilosKozak** [comment]
should be fixed in dev
