### ISSUE TITLE
No glucose register when use calc

### ISSUE THREAD

**Issue by mick711** [nightscout/AndroidAPS#1230]
It's happen with Dev 8fb17, when use Calc no glucose register but when use glucose it's OK. 
Phone zenfone 8, android 12.

![Screenshot_20220126-122209440](https://user-images.githubusercontent.com/441734/151160127-c859371b-e605-428e-9486-b54828513948.jpg)
![Screenshot_20220126-122216436](https://user-images.githubusercontent.com/441734/151160160-7a9a4844-c062-4d92-8582-3fab2eb10ddb.jpg)
![Screenshot_20220126-123239167](https://user-images.githubusercontent.com/441734/151160192-f699b481-ada3-4a52-97e2-667e2c5a4ef7.jpg)
![Screenshot_20220126-123232600](https://user-images.githubusercontent.com/441734/151160213-df07bd37-98bf-4bd2-994b-5c68b5c2e76a.jpg)
![Screenshot_20220126-123244840](https://user-images.githubusercontent.com/441734/151160244-55423aba-0823-41f3-9198-bfc2e62e480d.jpg)

Log file: https://drive.google.com/file/d/1p7FL8g-ijHBEXwn7wxLevvb9LKTtjurn/view?usp=drivesdk

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/EN/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
log is empty. drag&drop the file from phone here

**Comment by mick711** [comment]
[AndroidAPS_LOG_1643196772856.log.zip](https://github.com/nightscout/AndroidAPS/files/7948175/AndroidAPS_LOG_1643196772856.log.zip)

I can make a new log file for lunch .

**Comment by mick711** [comment]
I think issue can be closed. With a20f4f.. Dev built this issue not happen
