### ISSUE TITLE
3.0rc3 Omnipod Dash fatal error when using BT for phone call

### ISSUE THREAD

**Issue by stevensonderekr** [nightscout/AndroidAPS#1231]
ADD TIME OF EVENT HERE: 15:45 approx

Using Omnipod Dash pods. Screaming pod, could not reconnect to pod to deactivate. Occurred while using Bluetooth hands-free in my car to make a phone call. This issue has happened before with my car hands-free and I have had a similar issue when using a Bluetooth headset to make a phone call, but do not have this issue when streaming audio over Bluetooth to the same headset.
I'm assuming the issue is related to the HFP Bluetooth phone call profile interfering with the driver operation required to connect properly with the pod.
I am currently using a Google Pixel 3XL.
Potential workaround may be forcing no pod connections while this profile is active.
Right now I can't use my hands free and that is really not great.
If the logs are not good enough, I can try to reproduce the issue.
 -------------------------------------------------------
(Please remember this will send only very recent logs.
If you want to provide logs for event older than a few hours,
you have to do it manually)
-------------------------------------------------------
AndroidAPS 3.0-rc3
Build: 3b41e46a6-2022.01.26-00:41
Remote: https://github.com/nightscout/AndroidAPS
Flavor: fullrelease
Nightscout version: 14.2.4
Engineering mode enabled
[AndroidAPS_LOG_1643237488999.log.zip](https://github.com/nightscout/AndroidAPS/files/7946198/AndroidAPS_LOG_1643237488999.log.zip)

**Comment by MilosKozak** [comment]
This is phone issue and cannot be resolved by AAPS. Sorry
Other phones may stop BT comm during whatsapp call etc...
