### ISSUE TITLE
[v3-rc3] Bolus Dialog does not close on cancel

### ISSUE THREAD

**Issue by Andries-Smit** [nightscout/AndroidAPS#1239]
When cancelling a bolus in the progress with an Omnipod Eros, with the cancel button, the dialog shows the message below. The pumps cancels correctly, and the dialog can not be closed. However, before version 3 the dialog was removed/closed when the cancel was completed. 

Workaround, minimize app, and reopen.

![image](https://user-images.githubusercontent.com/6724749/151568517-fa4c5880-9b43-442e-8014-5dc444ea55a8.png)

It seems that the timestamps do not match
https://github.com/nightscout/AndroidAPS/blob/dev/core/src/main/java/info/nightscout/androidaps/dialogs/BolusProgressDialog.kt#L134

13:35:18.414 [main] D/PUMP: [BolusProgressDialog.onResume$lambda-3():133]: Running timestamp 1643373302482. Close request timestamp  1643373307351
[AndroidAPS._2022-01-28_00-00-01_._cancel_issue.zip](https://github.com/nightscout/AndroidAPS/files/7959560/AndroidAPS._2022-01-28_00-00-01_._cancel_issue.zip)

**Comment by MilosKozak** [comment]
The timestamp is used to distinguish beteween bolus and SMBs. Can you debug it? Driver should use EventOverviewBolusProgress.Treatment

**Comment by vanelsberg** [comment]
Confirming: also seeing this.

**Comment by regiorunner** [comment]
This issue seems related to #987 [3.0-beta6] Eros: Message bolus stopped not cleared.
