### ISSUE TITLE
BYODA / BUTTONS / Can't go to calibration text error

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1240]
@MilosKozak You deactivated going directly to BYODA calibration from AAPS (which is good as it didn't work) but the text for the "Calibration button option" hasn't changed. 

Also now we can turn it ON and not see the calibration button in the UI if we are using BYODA. It looks like a bug eventhough it is not.

![Screenshot_20220129-055649_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/151648114-d6b77a18-7b8c-4d19-80b7-23109b8663df.jpg)

![Screenshot_20220129-055710_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/151648123-da7872fa-8fc1-43f2-bc13-51556368c98c.jpg)

Can you change the text of the button to say "only in xDrip" and if possible to disable the option if we use BYODA?

**Comment by MilosKozak** [comment]
i'll change it later. It would mean new translations
