### ISSUE TITLE
[3.0-rc3] no button for catheter/reservoir/pod change

### ISSUE THREAD

**Issue by annushkiii** [nightscout/AndroidAPS#1242]
Hello,

everytime I change the pod, I give 1.8 iE for the change. In the settings I choose a Fill/Prime standard insulin amount of 1.8. iE. In my action tab I can't choose something like catheter/reservoir/-exchange (screens below). 
![Screenshot_20220129-183936.png](https://user-images.githubusercontent.com/80789970/151671455-fc58da18-f563-48c8-b724-057ea39b6025.png)
![Screenshot_20220129-184223.png](https://user-images.githubusercontent.com/80789970/151671497-6403278f-f46e-415b-96ef-395a057c887d.png)

**Comment by Philoul** [comment]
I think prime/fill is automatically done when you change your pod (no risk of error because build in values).
These settings are required for other pumps because tubing and catheter are not all the same.

**Comment by MilosKozak** [comment]
the button is not there because omnipod doesn't support priming at all. having it there could be very confusing for most people

**Comment by annushkiii** [comment]
@MilosKozak @Philoul 

A part of Omnipod users giving after podchange an extra basal to fill the little needle with insulin. Not all needed this, but in my opinion a lot. I'm in Facebook in a german Omnipod Group and read very often, that it is required.

My problem with AAPS because of the lack of  this button is, that I give the 1,8 needed bolus (this works fir me really good). The algorhitmus thinks "1,8 iE extra without carbs? Oh I have to reduce the basal!" and this is wrong. Because of this I asked in Looped DE for a solution and the recommendation is posting this as an issue here.

**Comment by vanelsberg** [comment]
> Facebook in a german Omnipod Group and read very often, that it is required.
Never heard of this. AFAIK this is utterly non-sense,

Omnipod primes automatically after canula insert.
Check the Omnipod user manual. There is no mention on requirement nor recommendation to do any additional "priming".

**Comment by annushkiii** [comment]
I knew the manual and use omnipod since over 5 years. Maybe I explain it here wrong. 

Started now a survey at Facebook and post the result here after few days.

**Comment by annushkiii** [comment]
Now I post the results. There are very different. Sry it's in German but I can translate. I asked if someone use extra bolus after podchange. I asked this in Looped-DE group amd in Omnipoddies & Friends group. Looped Community don't need the extra bolus (I think, because loop can handle it self). The people from Omnipoddies group needed it. Someone post a workaround, which said to enter few carbs, this don't confuse the loop, I think it's a good solution.

Ja=yes
Nein=no


![Screenshot_20220202-184319.png](https://user-images.githubusercontent.com/80789970/152210051-930c1bd8-d565-410f-9385-acf83740cc17.png)![Screenshot_20220202-184238.png](https://user-images.githubusercontent.com/80789970/152210059-bb8f3775-220a-4740-82c0-c9cf81c6c7d1.png)

**Comment by Andries-Smit** [comment]
@annushkiii a work around is; do add the insulin, like would do as a bolus. Thereafter you remove the in the treatment dialog (via de option menu, treatments), When remove it from the history and the algo will not use it the calculate the basal rate.

**Comment by annushkiii** [comment]
> @annushkiii a work around is; do add the insulin, like would do as a bolus. Thereafter you remove the in the treatment dialog (via de option menu, treatments), When remove it from the history and the algo will not use it the calculate the basal rate. 
> 

Thx this is a good solution!

**Comment by Andries-Smit** [comment]
@annushkiii A reference on the why you might need of an extra bolus: https://www.omnipod.com/poddertalk/diabetes-support/why-so-high-that-annoying-new-infusion-site-phenom
