### ISSUE TITLE
Feature request: Add new buttons for easier UAM looping

### ISSUE THREAD

**Issue by a-rigatuso** [nightscout/AndroidAPS#1243]
When using no-carb/bolus looping it would be helpful to have more options for buttons in overview settings. I would like to add **temporary target presets (eating soon, activity, hypo** from the temporary target dialogue) and **profile switch** (from action tab) as optional buttons on the home screen.

I built a quick mockup for clarification:  

![aaps-uam-layout](https://user-images.githubusercontent.com/3932888/151678573-ef73fe4f-5d47-47dc-bb83-482c56ad91d1.jpg)

With active eating soon TT:  

![aaps-uam-layout-aktiv](https://user-images.githubusercontent.com/3932888/151678583-d8cb66ba-d015-4f02-8de2-8a26fc980427.jpg)

**Comment by Philoul** [comment]
full UAM looping is not standard way to loop.
You can access to profile switch with loog click on profile name, and to all other functions from with just one more click on target button.
I'm afraid your proposal will incease the complexity in settings (several additional buttons).

**Comment by MilosKozak** [comment]
you can create custom buttons with 3.0 and automation
this is edge case to be implemented to main AAPS
