### ISSUE TITLE
Dev 20/ Crazy calculation "loop" on main UI with strange graphics 

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1244]
From time to time (didn't find what triggers it), there is a _recalculation new data_ that starts over and over for a long time with strange graphs in the middle of the calculations.

Eventually it stops recalculating and the graph goes back to normal. So, not a major bug but seems strange.

![Screenshot_20220130-085436_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/151692668-2878504f-83c4-4a28-96fe-ab997efedaa5.jpg)

For the logs, look at around 8h54
[AndroidAPS_LOG_1643529458396.log.zip](https://github.com/nightscout/AndroidAPS/files/7965566/AndroidAPS_LOG_1643529458396.log.zip)

**Comment by MilosKozak** [comment]
can you paste screenshot of Treatments Temp basals?

**Comment by robertrub** [comment]
No change in temporary basals. Temp target change but several minutes before the "loop".
Different captures around 8:54

![Screenshot_20220130-113155_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/151696145-3d1aa212-4045-4784-ad17-2b2ac4195770.jpg)
![Screenshot_20220130-113249_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/151696150-53f98254-f325-415a-8daa-b9a1046bc23e.jpg)
![Screenshot_20220130-113308_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/151696157-464640fb-57c5-4fb4-a3ab-88710a2d9110.jpg)

The bolus was injected at 8:54 once the calculations were finished.
![Screenshot_20220130-113552_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/151696183-b9041bcb-c0c7-43e2-9bd4-a5930e2065da.jpg)

**Comment by Thomas-Wolff** [comment]
I can also confirm this, but it settles down again after a few seconds. 

Have a nice Sunday, greetings Thomas

**Comment by robertrub** [comment]
It took about 1 min in this case (usually, it takes less time).

**Comment by vanelsberg** [comment]
Seeing this also when changing scale. But it takes only a few seconds (up to 10?) before it settles down.
