### ISSUE TITLE
Add Glucose Direction and Delta

### ISSUE THREAD

**Issue by bobhome007** [nightscout/AndroidAPS#1245]
Version: AAPS 3

Type: Improvement

Add glucose trending direction as an Automation Trigger type

Add Glucose delta value and time time period as an Automation Trigger type

Eg.

Glucose Direction = UP
Delta Period = 40 min
Delta = 1.9 mml or mgdl

This example means Automation will trigger if glucose is rising in 40 mins by 1.9 mml

**Comment by Philoul** [comment]
It already exists (trigger BG difference)
You can select Delta / Short avg. delta / Long avg. delta. and the amount (is equal / is greater than / ...)

**Comment by bobhome007** [comment]
Is there an option for direction ?

**Comment by bobhome007** [comment]
Ok it takes negative numbers so this will be falling glucose I think
