### ISSUE TITLE
Accessibility Initiative

### ISSUE THREAD

**Issue by Andries-Smit** [nightscout/AndroidAPS#1255]
**Accessibility testers/feedback wanted!** Are you interested in the experience of how a blind person "sees" an application? Or do you have experience? Please join!

Making AAPS accessible for all users regardless of their (temporarily) disabilities is a noble goal, this might not be 100% achievable, but we should keep on improving.

Accessibility is not only a topic for (colour) blind, blind people. **All AAPS users** have temporarily accessibility issues; a bumpy ride in the bus, make it hard to click small targets. On the move in the car, you should keep your eyes on the road. Bright and low-light conditions make it sometimes hard to read the text and many more situations.

This inattentive will test, gatherers ideas and improvements on all levels of accessibility;
•	Touch targets, (can you click small buttons?)
•	Colour contrast (can you read it?)
•	Voice access and control (Can you use it without hands?)
•	Screen reader accessibility (discover your app with your eyes closed)

To make all aspects of fully AAPS application including setup would be nearly impossible.
Our goal is to make the primary functions of APPS accessibly for all types of users.

There are some open pull requests for review. 
•	Learn to use [Talkback ](https://support.google.com/accessibility/android/answer/6283677?hl=en)
•	Learn reviewing [tools ](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en&gl=US)
•	Learn about [best practices](https://developer.android.com/guide/topics/ui/accessibility) 

Pull requests to review :
1. Light theming #326 
2. Improved overview #1200
3. Table structure, row focus #1251
4. Remove dialog header images #1252
5. Wizard dialog #1253

**Comment by vanelsberg** [comment]
I think this is a great initiative that could benefit many if not all.
Fortunately my eyesight is great so I will need to think about how to "test" this...
