### ISSUE TITLE
3.0.0 NS Client no Control 

### ISSUE THREAD

**Issue by elgrupo123** [nightscout/AndroidAPS#1258]
NS Client 3.0.0 control.

With NSClient 3.0.0, Profiles/Temporary Rate on the Master cannot be controlled/changed. Even the last action such as changing the pump is not displayed. With RC3 it worked without problems. Also NS shows all NS client data. Bug or are we making a mistake??

**Comment by reijoahola-nightscout** [comment]
It looks like s ome of NSClient synchronisation settings are removed in AAPS. Profile Switch and Temp Target for example. I do not know the reasons.

**Comment by elgrupo123** [comment]
In the RC3 version, it worked wonderfully and made life a lot easier for us parents. If it is wanted now, it would be a huge step backwards and a shame.

**Comment by reijoahola-nightscout** [comment]
Seems to be fixed now in 3.0.1.

**Comment by elgrupo123** [comment]
3.0..0.1 does not remedy the situation. 3.0.1 is currently having problems downloading.

**Comment by MilosKozak** [comment]
with 3.0.0.1 you can enable it in preferences
