### ISSUE TITLE
[3.0.0] Profile editor shows Basal profile under IC tab

### ISSUE THREAD

**Issue by reijoahola-nightscout** [nightscout/AndroidAPS#1266]
Just a minor cosmetic issue:
Profile editor has a new feature to show profiles under IC, ISF and BAS.
ISF and BAS show corresponding profile correctly but IC shows basal profile.

**Comment by Andries-Smit** [comment]
@reijoahola-nightscout thank you for reporting, can you add screenshots to issue to explain? Thank you
