### ISSUE TITLE
DASH age/insulin level esthetic bug

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1275]
@Andries-Smit You have simplified the information shown for EROS/DASH pods. Thanks :)

There is a small error on the interface (DASH in my case).

![20220202_172804.jpg](https://user-images.githubusercontent.com/76626474/152523635-42575b31-63c5-4ed6-a209-b43cf3ba5f81.jpg)

You have _Age:Insulin level_ when _Age:_ should be removed.

It would be nice to eliminate all information concerning the battery for DASH. The battery changes with each pod. 

![Screenshot_20220202-171940_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/152524013-89d93697-f46a-4fdb-8b76-140934bacf76.jpg)
![Screenshot_20220202-171923_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/152524034-0b98ff02-77b0-43f6-a75e-9fc2ff3361d5.jpg)

The battery information for EROS should stay as it reports OL battery info.

**Comment by Andries-Smit** [comment]
@robertrub it is fixed in PR https://github.com/nightscout/AndroidAPS/pull/1264
The battery is on my list, but first, this and a refactor of the status light has to be merged https://github.com/nightscout/AndroidAPS/pull/1200.
After that, it is a small change to do you request on battery

**Comment by robertrub** [comment]
Thanks a lot :) Do we close this issue then ?

**Comment by Andries-Smit** [comment]
It would be great if you can test the fix and comment in the PR, if it solves your issues then you can close this issue.
