### ISSUE TITLE
Force discarded DASH. Cannot reconnect 

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1276]
@avereha I did a test which didn't work well. 
Main phone. Export settings. Change pump to virtual pump.
Test phone. Install 3.0.0.1 dev. Ok for all the permissions. Import the exported settings. Phone connects to DASH, beep test ok. Discard DASH via test phone. Kill AAPS and uninstall on test phone.
On main phone. Change pump back to DASH. AAPS can't connect to DASH (normal). I "try" to discard pod. I can't of course as the pod has been deactivated by test phone (normal). After 1+ minutes of waiting, I hit "back button" of Android. I then try to discard again and get the message for "forcing" pod discard that I accept. Till now, everything looks normal.

But, on DASH page, there is a message about pump driver change... (sorry no screen capture).

I try to activate the new pod but I can't, I get this message over and over.

![Screenshot_20220204-203400_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/152594639-8693581f-0164-46c9-8d7a-c4cbb72809e6.jpg)

I had to kill AAPS, clear AAPS cache and restart it in order be able to activate the new pod.

Look at the logs around 20:33 (+/- 4 min)

![AndroidAPS_LOG_1644003534086.log.zip](https://github.com/nightscout/AndroidAPS/files/8005898/AndroidAPS_LOG_1644003534086.log.zip)

**Comment by filipwoz** [comment]
Similar to my earlier issue: https://github.com/nightscout/AndroidAPS/issues/1159
