### ISSUE TITLE
AAPS crash when activating local profile

### ISSUE THREAD

**Issue by Pallesauka** [nightscout/AndroidAPS#1281]
In AAPS I used the profile helper function to generate a local profile. I used the DPV profile and copied the results to my local profile list. Using the default generated name of the profile (very long name incl date, time etc) causess AAPS to crash once the profile is activated. Changeing the name to something simple solves the issue. 
I think automatically generated profile names should not crash the software.

This is with AAPS 3.0.0.1 and android 10.

**Comment by Andries-Smit** [comment]
@Pallesauka thank you for reporting, can you share a log file of the occurrence?

**Comment by MilosKozak** [comment]
closed for inactivity
