### ISSUE TITLE
The current profile is not visible in the profile editor

### ISSUE THREAD

**Issue by JimmyFoks** [nightscout/AndroidAPS#1284]
In the profile editor (and even after touching the name of the active profile on the main screen) I can't select the profile that is currently active. I don't see any of the two newly created local profiles today (manually via mobile phone).

AndroidAPS 3.0.0.1; Android 11
![small1](https://user-images.githubusercontent.com/34617797/152690976-cea40bdd-3fb2-4f1d-a64b-b79525a391bc.jpg)
![small2](https://user-images.githubusercontent.com/34617797/152690982-c10efa6e-f3a2-4dbb-b41f-b61d4eb4b10a.jpg)

**Comment by MilosKozak** [comment]
if you set profile and then delete it in profile it will be still running

**Comment by MilosKozak** [comment]
you can still clone running profile from treatments

**Comment by JimmyFoks** [comment]
The profile was never deleted by me.
And as another interesting fact - when I enter the profile editor, I change something in the displayed profile (not the current one on the main screen) and then I touch RESET, the profiles are displayed - see the video.

https://user-images.githubusercontent.com/34617797/152727427-0821f5a8-8191-414e-93b7-5bfad3b2688d.mp4

**Comment by MilosKozak** [comment]
this seems to be caused by synchronization with NS (different profiles received from NS during editing)
review all profiles to be without error, do small change and save ....
then you should see the same profiles in NS

**Comment by JimmyFoks** [comment]
Okay.
