### ISSUE TITLE
AAPS asks me to send logs ;) No carb count after BD reset

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1303]
I had 2 G6/BYODA start problems and was using Libre2/OOP2/xDrip for the BGs in AAPS while G6 was getting stable (both sensors on me and activated). When G6 started working OK, I switched to G6/BYODA as the BG source and (as expected), I got the red triangle as Libre2 and G6 BGs were both in the DB. 

I reset the BD in AAPS and started getting this message : Something like "Unknown situation, send logs to dev". I exported the logs but the message kept coming back. I then realized that COB was _ND_ ( _not available_ in French UI) even though I had entered them after the DB reset. I deleted the carbs from treatments and re-entered them but it didn't change the _ND_. I had to force kill AAPS. Wipe cache memory in Android and restart AAPS. After that, all is working correctly. 

All this happened between 7h30 and 8h.

[AndroidAPS_LOG_1644561897500.log.zip](https://github.com/nightscout/AndroidAPS/files/8046914/AndroidAPS_LOG_1644561897500.log.zip)
 
[AndroidAPS_LOG_1644563024298.log.zip](https://github.com/nightscout/AndroidAPS/files/8046916/AndroidAPS_LOG_1644563024298.log.zip)

**Comment by MilosKozak** [comment]
unknown reason
