### ISSUE TITLE
Minor bug : no pod age after DB reset

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1304]
I had to reset the AAPS DB. After reset, strangely the DASH tab knows the pod end date but the actions tab does not know how old the pod is.

![Screenshot_20220211-131844_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/153590930-5a973a0f-5128-4679-a3d3-b4d63593a052.jpg)

![Screenshot_20220211-131859_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/153590954-de6a236d-dd51-4697-b254-cf80254646f5.jpg)

**Comment by MilosKozak** [comment]
this information is stored in database as Canula age
