### ISSUE TITLE
Large NSClient time display

### ISSUE THREAD

**Issue by timocm** [nightscout/AndroidAPS#1308]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/EN/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by mick711** [comment]
Could you please edit and add title 😉

**Comment by timocm** [comment]
NSClient 3.0.0.1. The time display is massive on the top right side: can this be made smaller or be removed so that the deltas can be moved over to the right and the BG value can be moved to the right allowing the BG value to be completely visible when there is a double digit BG value or if the font size of the phone is increased? #1308

**Comment by MilosKozak** [comment]
can you provide screenshot?

**Comment by timocm** [comment]
![Screenshot_20220214-072034728](https://user-images.githubusercontent.com/34131445/153775718-fd3c9226-e074-4dfc-b0a7-577913495ae7.jpg)
With present font settings : no space for a BG > than 9.9

**Comment by timocm** [comment]
![Screenshot_20220214-072322249](https://user-images.githubusercontent.com/34131445/153775760-2bb0ce13-d1dc-4660-af7b-ef7883a1d1d6.jpg)
With a setting of a larger font size

**Comment by timocm** [comment]
![Screenshot_20220214-072403801](https://user-images.githubusercontent.com/34131445/153775803-8283b929-ad09-44b8-a64d-bddf0782caff.jpg)
With a setting of a larger display size

**Comment by MilosKozak** [comment]
what is this phone?

**Comment by timocm** [comment]
Galaxy note20 ultra

**Comment by kristinsmotz** [comment]
I get the same if I increase font size in phone settings larger than the third available size (dot on the scale line). Samsung Flip 3. I just use the 2nd or 3rd sizes. 
![Screenshot_20220214-105121_Settings](https://user-images.githubusercontent.com/71758682/153841293-b295d54b-526e-4daf-b894-2ceb8b602a71.jpg)
![Screenshot_20220214-105116_NSClient](https://user-images.githubusercontent.com/71758682/153841305-a040d33f-9dfe-42d7-afaf-774ec9785c6c.jpg)
![Screenshot_20220214-105132_Settings](https://user-images.githubusercontent.com/71758682/153841326-0857a250-f1af-45d4-8e2d-2855ba194c53.jpg)
![Screenshot_20220214-105141_NSClient](https://user-images.githubusercontent.com/71758682/153841335-9eb4fa73-437c-481c-968e-8051ef4b9d1d.jpg)
![Screenshot_20220214-105153_Settings](https://user-images.githubusercontent.com/71758682/153841355-ed9293e8-68bf-40a6-89d8-07b30bd36e50.jpg)
![Screenshot_20220214-105159_NSClient](https://user-images.githubusercontent.com/71758682/153841370-fea03b0c-d7ca-439c-adb1-48f04b0e83b7.jpg)
![Screenshot_20220214-105209_Settings](https://user-images.githubusercontent.com/71758682/153841379-888e7ab5-e68c-461e-bce0-db5fcdd8d731.jpg)
![Screenshot_20220214-105215_NSClient](https://user-images.githubusercontent.com/71758682/153841409-6add59dd-4fe2-419c-b96d-c15df46087c1.jpg)

**Comment by MilosKozak** [comment]
> what is this phone?

and you font size?

**Comment by timocm** [comment]
I was  hoping for less space for the time and a more centralized position of the BG value
![IMG-20220215-WA0000](https://user-images.githubusercontent.com/34131445/153948404-5c8138b1-a063-4636-bcca-38a56fb73aa4.jpg)

**Comment by Andries-Smit** [comment]
@timocm I scaled down the text size in PR #1436 could you validate this works for you well for your device?
