### ISSUE TITLE
SMB hijacks programmed bolus progress popup and prevents cancellation of the programmed bolus

### ISSUE THREAD

**Issue by TranceCake** [nightscout/AndroidAPS#1315]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem:
  I programmed a bolus through the bolus wizard. 
  I confirmed the bolus.
  Immediately a popup was shown that showed the bolus progress and listed the correct bolus amount
  But it was actually the progress of an ongoing SMB since it completed 0.3 units instead of the programmed 3.3.

  This happens when you program a bolus and an SMB is being or about to be given. The progress popup then shows the SMB 
  progress instead of the programmed bolus progress. This is an issue because the bolus wizard calculated the bolus based on an IOB 
  that was calculated prior to the SMB, resulting in a slight overdose of insulin potentially.

- **Note the Build version**: 3.0.0.1 but it should be noted that I also saw this issue in earlier version 2.8.x
- **Obtain the app's log files**:

[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/8054513/AndroidAPS.log)

**Comment by Antoine-35** [comment]
I sent a manual bolus and the SMB started just before I sent the bolus.
The SMB and the bolus were injected but I did not get the pop up of the bolus injection and impossible to cancel

**Comment by Andries-Smit** [comment]
Might be related to https://github.com/nightscout/AndroidAPS/issues/1239

**Comment by Antoine-35** [comment]
Ok I know how to reproduce it.
If you send a bolus during an SMB, the pop up disappears every time.
I'll take a video to share with everyone.

**Comment by Antoine-35** [comment]
Video of the SMB hijack bolus progress:
https://drive.google.com/file/d/18VaIM4L8jrf17H7ar1oX41G8Fq4lxtm9/view?usp=sharing

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/bbcbf3f90535c719fb70bbcb41c486cc7bf475ad
