### ISSUE TITLE
Feature request: Show BG and arrow on phone unlock screen

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1316]
xDrip has a nice feature, show BG and arrow on the unlock screen of phone. You just wake up the screen to see your BG.

It would be nice for BYODA users if AAPS had something similar.

![20220213_052701.jpg](https://user-images.githubusercontent.com/76626474/153738714-508ac5e3-0638-46e6-9f8a-341b3dc0eac7.jpg)

**Comment by Alamo04** [comment]
Would be a nice to have feature, for all users without XDrip. 

For now I use Boyda and XDrip only for my Watch and this Lock Screen feature. :)

**Comment by MilosKozak** [comment]
i don't know even how to enable it

**Comment by robertrub** [comment]
![Screenshot_20220214-071901_xDrip+.jpg](https://user-images.githubusercontent.com/76626474/153810641-97e84b7f-c1d0-441c-9b54-98fcc9c3945a.jpg)

**Comment by Andries-Smit** [comment]
The question is, should this be implemented in BYODA, and not AAPS?

Logic and most of the code can be reused from https://github.com/NightscoutFoundation/xDrip/search?p=1&q=number+wall

However, BYODA has an option to support both xDrip and AAPS config
> Would you like to broadcast your glucose readings to other apps? G6 ONLY
> [ ] Yes, broadcast to both xDrip and Android APS.

There is also an option for Always-on Display for Wear OS watches too.
