### ISSUE TITLE
[3.0.0.1] Profile editor - basal graph shown in IC tab

### ISSUE THREAD

**Issue by kristinsmotz** [nightscout/AndroidAPS#1336]
I took screenshots of the different tabs in the Profile tab, and noticed the display graph below the IC ratios doesn't show IC but rather a copy of the basal rates graph. 
Checked in both AndroidAPS and NSClient phones and it's the same for both. 

![20220217_184339](https://user-images.githubusercontent.com/71758682/154540645-de46c3e6-6c1e-49cb-a9dc-350fa2cdaeb6.jpg)

**Comment by MilosKozak** [comment]
it's already fixed in dev
