### ISSUE TITLE
Glucose value strike-through and incorrect time for minutes ago

### ISSUE THREAD

**Issue by dkmsoft** [nightscout/AndroidAPS#1339]
Has happened a couple of times (Rel 3.0.0.1) that the BG number has a stale value strike-through and number of minutes ago not updated. Screenshot shows last BG to be 203 minutes ago when in fact the BG readings have been coming in every five minutes (as evidenced by correct up to date graph and also xDrip readings are all there up to the current time). It's a display issue.

![AAPS_invaliddisplay](https://user-images.githubusercontent.com/50314479/154616753-50fee333-80fc-440d-8a1a-8c5dd5a14bc4.jpg)
.

**Comment by athinab** [comment]
I've experienced the same issue, too!

**Comment by LewEasy** [comment]
I have had the same thing a couple of times now. 

One minute all is fine then suddenly the Overview Page says last reading was XX(X) minutes ago or similar, all the while xDrip keeps updating and the graph in AAPS is also showing these values. 

Using AAPS 3.0.0.1, xDrip+ nightly from 15.02.2022 with Libre 2 on a Xioami Redmi Note 8 Pro (MIUI Global 12.5.6 / Android 11)

**Comment by MilosKozak** [comment]
without logs this issue is useles at this is not common situation
