### ISSUE TITLE
Proposal: make "pulled down" menu items in the "Preferences" Section retractabel

### ISSUE THREAD

**Issue by jbuckhi** [nightscout/AndroidAPS#1357]
Right now, if you open a menu by clicking the down arrow, the pulldown menu opens and stays open, till you leave the preference section.

Is it possible to introduce (for example) an up arrow to close a submenu again? This would make it easier to navigate the menues and keep track, especially for beginners.

Another proposal: you could also highlight a submenu section with a different background color for better readability, or make both.

**Comment by MilosKozak** [comment]
this is android preferences behavior and design. we cannot change it
