### ISSUE TITLE
[2.7.2-dev] Graph shows temporary target of 0 for a few minutes

### ISSUE THREAD

**Issue by ArthurusDent** [nightscout/AndroidAPS#136]
While I had set an eating soon temporary target of 80, the target was changed to 0 for a few minutes. It's probably just a glitch because I couldn't find anything in the logs but I thought, one of the devs should have a look.

Screenshot:
![Screenshot_20201223-024643_AndroidAPS](https://user-images.githubusercontent.com/6848629/103044190-f21bbf80-457f-11eb-8c35-c8309884d906.png)

Logs:
timeframe: 
01:02:11.543 [main] D/CORE: [OverviewMenus.onContextItemSelected():365]: USER ENTRY: TEMP TARGET EATING SOON
...
01:21:40.026 [main] D/CORE: [OverviewMenus.onContextItemSelected():408]: USER ENTRY: TEMP TARGET CANCEL

[AndroidAPS._2020-12-23_00-00-04_.zip](https://github.com/nightscout/AndroidAPS/files/5737479/AndroidAPS._2020-12-23_00-00-04_.zip)

System:
AndroidAPS 2.7.2-dev 6cb62412c
Medtronic 554
Dexcom G6
xDrip+
Oneplus 3T
Lineage 17.1

**Comment by MilosKozak** [comment]
where is the zero?

**Comment by ArthurusDent** [comment]
I've marked it:
![Screenshot_20201223-024643_AndroidAPS](https://user-images.githubusercontent.com/6848629/103484316-239d5200-4dee-11eb-8a38-2fc345fc711c.png)

**Comment by MilosKozak** [comment]
this is caused by worng NS synchronization. turn on NS upload only

**Comment by ArthurusDent** [comment]
I had already turned on "NS upload only" at the time this happened.
