### ISSUE TITLE
If battery dies during bolus delivery you get full bolus anyway but AAPS does record only part of it

### ISSUE THREAD

**Issue by PetrMlejnek** [nightscout/AndroidAPS#1361]
CASE:

I hit bolus shortcut for breakfast that should give me 8,7 U.
During bolus delivery I get error message in AAPS that only 1,1 U was delivered.
I looked at the pump display that shows me the battery needs to be replaced.
I was sure that I get more than 1,1 U of insulin because insulin delivery took a long time (definitely longer than 1,1 U).
I replaced the battery.
I synced pump with AAPS by hitting Bluetooth logo in AAPS.
But AAPS still shows that only 1,1 U was delivered.
So I looked to pump bolus history and there was a record of 8,7 U delivery.
So pump knows that it delivered full bolus, but AAPS doesn't.

So the DANGEROUS problem is that if battery dies during bolus delivery you get full bolus anyway but AAPS does record only part of it. If you did not notice it, you can overdose and end up in hypo.

--------------
PUMP: Dana R v2, Model: 03, Protocol: 02, Code: B1
APP: Android APS 2.8.2

![Screenshot_20220222-082307_AndroidAPS](https://user-images.githubusercontent.com/42749712/155177481-6c920d9b-bd24-444b-9142-1c1955aba0a6.jpg)
![Screenshot_20220222-082319_AndroidAPS](https://user-images.githubusercontent.com/42749712/155177503-711c15f9-028f-4c3e-bc82-476c09ea1f54.jpg)
![20220222_082737](https://user-images.githubusercontent.com/42749712/155177529-d5d63266-fdbc-4d8e-b58c-9d23429f0b9f.jpg)

**Comment by MilosKozak** [comment]
do you have log files?

**Comment by PetrMlejnek** [comment]
It happened this morning between 8 to 9 am.

[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/8119333/AndroidAPS.log)
[AndroidAPS._2022-02-22_00-00-03_.2.zip](https://github.com/nightscout/AndroidAPS/files/8119334/AndroidAPS._2022-02-22_00-00-03_.2.zip)
[AndroidAPS._2022-02-22_00-00-03_.1.zip](https://github.com/nightscout/AndroidAPS/files/8119335/AndroidAPS._2022-02-22_00-00-03_.1.zip)
[AndroidAPS._2022-02-22_00-00-03_.0.zip](https://github.com/nightscout/AndroidAPS/files/8119336/AndroidAPS._2022-02-22_00-00-03_.0.zip)

**Comment by PetrMlejnek** [comment]
It happened this morning at 8:21.
[AndroidAPS._2022-02-22_00-00-03_.1.txt](https://github.com/nightscout/AndroidAPS/files/8119353/AndroidAPS._2022-02-22_00-00-03_.1.txt)

**Comment by MilosKozak** [comment]
now i see it's 2.8
logging was not so good to be able find anything.
and you are not using v2 driver anyway. main R driver doesn't use history and any problem with connectivity leads to wrong data almost everytime

**Comment by PetrMlejnek** [comment]
Omg, I don't know how that happened. Thank you!
