### ISSUE TITLE
[Enhancement] Allow sending SMS without obj 10

### ISSUE THREAD

**Issue by yossibivas11** [nightscout/AndroidAPS#1373]
There is a need for SMS notifications for low/high BG for people that need followers but the followers don't use internet (ultra orthodox jews), they do use sms/voice calls. 
I propose to enable the "send SMS to all numbers" capability to everyone, before reaching objective 10. 
Perhaps add this functionality to the SMS communicator.

**Comment by MilosKozak** [comment]
sorry. this is automation feature and there is no plan to change it.
There is more options to do it but I'm affraid everything needs internet
