### ISSUE TITLE
[3.0.0.1 dev-b] Crash on latest dev

### ISSUE THREAD

**Issue by Philoul** [nightscout/AndroidAPS#1375]
![image](https://user-images.githubusercontent.com/52934600/155676827-75be06bb-9f9a-4ce6-9db3-33d0fc275a94.png)

**Comment by MilosKozak** [comment]
dev-b ?

**Comment by Philoul** [comment]
Build this morning with latest commit of yesterday evening

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/bd61e53bc8a6d8e081cc8dc47dc24c62936fc84e
