### ISSUE TITLE
No carbs in AAPS if phone restart during bolus started via wizard

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1377]
I entered carbs in wizard and started bolus injection. During the bolus, I had to restart the phone. Once restarted, I actualized pod status to validate the sent bolus.

I can see the bolus but there is no trace of the carbs in AAPS.

![Screenshot_20220225-122218_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/155711501-07c1c3f1-efb6-4a2f-b319-f9bae19dad28.jpg)

![Screenshot_20220225-122228_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/155711520-6d4ad986-f955-4a40-a66b-a23813982042.jpg)

![Screenshot_20220225-122253_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/155711559-40085fb6-d94a-4b2b-a8f3-d30019e6ae3d.jpg)

I don't know if the logs are reset after reboot...

![AndroidAPS_LOG_1645788190507.log.zip](https://github.com/nightscout/AndroidAPS/files/8140929/AndroidAPS_LOG_1645788190507.log.zip)

**Comment by MilosKozak** [comment]
carbs are recorded only if bolus is delivered successfuly. it's for safety because people entered carbs for 2nd time when repeated bolus

**Comment by robertrub** [comment]
@MilosKozak When the phone booted, the bolus was "unsure" in the DASH tab. When I actualized it, the fact that the bolus was injected totally was known to AAPS.
I don't know if it will be doable to find a logic that adds carbs if they are missing or to show a message "check carbs and bolus" after boot if AAPS stopped before the bolus complete (the DASH tab new that it hadn't received the "bolus injected ok" message).

**Comment by MilosKozak** [comment]
carbs info is store donly in memory until bolus is finished
