### ISSUE TITLE
3.0 Treatments "bolus calc" to database conversion error

### ISSUE THREAD

**Issue by kristinsmotz** [nightscout/AndroidAPS#1382]
When bolusing using the Bolus calculator, BG appears correct as 5.4 in mmol/l value (didn't screenshot this). When later viewing the same bolus in Treatments - Calc, the BG value appears as 0.2. This indicates that when posting to database, a mmol value is wrongly seen as a mgdl value and divided by 18. 

![Screenshot_20220226-003236_NSClient](https://user-images.githubusercontent.com/71758682/155816939-3d0f9881-798a-45e0-9312-48c840d2dd30.jpg)

Bolus happened at 21.51 in this case. 
[AndroidAPS._2022-02-25_22-32-04_.0.zip](https://github.com/nightscout/AndroidAPS/files/8145404/AndroidAPS._2022-02-25_22-32-04_.0.zip)
Screenshots from log highlighting relevant part: 
![image](https://user-images.githubusercontent.com/71758682/155817253-3c1b37bf-1975-4f4d-a56f-5514f5db19d5.png)

![image](https://user-images.githubusercontent.com/71758682/155817384-4c9b8c47-b2eb-4527-99c7-fccfc39c1e13.png)

**Comment by ruenightscout** [comment]
Thanks for raising this issue. I noticed the same today.
![Screenshot_20220225-211307_NSClient](https://user-images.githubusercontent.com/25442477/155837028-77d28c7a-31c4-4858-a442-de70c4d898e2.jpg)
