### ISSUE TITLE
Loop is not executing 

### ISSUE THREAD

**Issue by margogoodfellow** [nightscout/AndroidAPS#1388]
I had this problem before.  I have built new app from scratch and I still have this problem.  Loop works fine at first and then doesn't execute.  Bg is changing and loop doesn't respond for 10 -15 min. This happened lots of times today . 
https://drive.google.com/file/d/1UJWREu0WNm5X6Rf0__SVxTKwBYPfjpZk/view?usp=drivesdk

**Comment by MilosKozak** [comment]
i need exact time(s) when this happened

**Comment by margogoodfellow** [comment]
I don't understand why this happening as after last time I have rebuilt
completely and got new phone. Is this bug transferred with preferences or
is there something to do with nightscout?

**Comment by margogoodfellow** [comment]
https://drive.google.com/file/d/1O4Ol1VJYPyAhxJ1fM_85rEJvErRkW8oz/view?usp=drivesdk
Not executing from 7:50 am till 8:05 am I had to press run now

**Comment by MilosKozak** [comment]
ver 2.8 is unsupported now
test with 3.0
