### ISSUE TITLE
"NSClient version doesn't match to AndroidAPS"

### ISSUE THREAD

**Issue by JimAdkins** [nightscout/AndroidAPS#1392]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
This happens every hour or so.
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
NSClient 3.0.0 and AndroidAPS 3.0.0.1

For some reason every hour or so on NSClient I get the notification error that "NSClient version doesn't match to AndroidAPS. Please update." I got this version of NSClient from https://github.com/nightscout/AndroidAPS/releases/. Is there a more recent version of NSClient somewhere else? 

Thanks!

**Comment by Philoul** [comment]
New release v3.0.0.1 is now available 😉
