### ISSUE TITLE
Entrys in the treatment menu only partially visible

### ISSUE THREAD

**Issue by cr582** [nightscout/AndroidAPS#1394]
In the treatment menu, entries are only partially visible and can therefore no longer be deleted (at least in portrait mode). See attached screenshot.

![Screenshot_20220225_223142_info nightscout androidaps](https://user-images.githubusercontent.com/62606176/156000890-b91e61b1-169d-421e-b392-2d6e28fc6264.jpg)

Edit: Even when I set Font size to "small" I don't see fhe full line:

![Screenshot_20220228_152901_info nightscout androidaps](https://user-images.githubusercontent.com/62606176/156000716-ae39b601-75b5-48bb-b508-8f792087cc39.jpg)

**Comment by MilosKozak** [comment]
already improved in dev branch

**Comment by Andries-Smit** [comment]
@cr582 FYI fixed in PR #1362

**Comment by cr582** [comment]
unfortunatelly it's even worse in 3.1.0
![Screenshot_20220720-173137_AndroidAPS](https://user-images.githubusercontent.com/62606176/180023666-28edef7b-8fc6-441a-b17d-3b432a6ca85d.jpg)

**Comment by osodebailar** [comment]
It's all ok.
Click on the trashbin 😉

**Comment by cr582** [comment]
even if I click on the trash icon and select something I am not able to see what is selected. Sorry, but this is not a solution to the mentioned issued and I really would appriciate it if someone could reopen this bug report since it is in no means resolved.


![AndroidAPS_Screenshot_20220720-194123_](https://user-images.githubusercontent.com/62606176/180070003-4e51cf4c-bb12-4090-9f42-507e904718ff.jpg)

**Comment by osodebailar** [comment]
Have you choose an own font and/or resolution size ? It looks like very big to me ?

**Comment by cr582** [comment]
this is a screenshot with the smallest font setting available on Samsung Galaxy S20 FE
![AndroidAPSScreenshot_20220720-220103_](https://user-images.githubusercontent.com/62606176/180071508-28db3db5-0c9d-4d99-809e-465b1a891c66.jpg)
E

**Comment by cr582** [comment]
and thsi is a screenshot of the start screen (with smallest font size) - I'm not able to see how many units of insulin are still available in the cartridge


![Screenshot_20220720-220629_AndroidAPS](https://user-images.githubusercontent.com/62606176/180072763-a6b06819-46c7-427a-8489-51c0dc66ac92.jpg)

**Comment by osodebailar** [comment]
It's not a font issue. Maybe a Nightscout issue. Had the same problem a week ago .

**Comment by cr582** [comment]
smartphone in landscape mode shows everything. I strongly doubt that this is a nighscout issue


![Screenshot_20220720-221757_AndroidAPS](https://user-images.githubusercontent.com/62606176/180074016-70467ba0-c05d-45a3-9888-544fe9b3fc1d.jpg)

**Comment by cr582** [comment]
@osodebailar @MilosKozak should I open a new bug report for 3.1.0 or do you reopen this bug since it is clearly not fixed with #1362 
Thanks in advance

**Comment by MilosKozak** [comment]
what phone are we talking about?

**Comment by cr582** [comment]
first report: Huawei Mate 20; second report Samsung Galaxy S20 FE 5G
