### ISSUE TITLE
[3.0.0.1] After entering carbohydrates in the bolus calculator, no carbohydrates are displayed.

### ISSUE THREAD

**Issue by 69nobody** [nightscout/AndroidAPS#1401]
I have noticed several times now that when using the bolus calculator, after entering the carbohydrates and confirming with OK, no carbohydrates are displayed on the main screen. I have attached logs. Time approx. 14:30
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/8162019/AndroidAPS.log)

**Comment by mick711** [comment]
Me too but not all the time, sometimes it work.

**Comment by 69nobody** [comment]
I do not have other views/screenshots

![Screenshot_20220302-120830](https://user-images.githubusercontent.com/94611099/156355243-35995290-f5c3-46d0-84fd-199ea18b12a8.PNG)
![Screenshot_20220302-121031](https://user-images.githubusercontent.com/94611099/156355246-b80360e4-8c3d-4dde-9831-08b1f436ab9c.PNG)

**Comment by MilosKozak** [comment]
no data in log. create new issue with more screenshots and log if you can replicate
