### ISSUE TITLE
[DEV 3.0.0.1- E] After 51 minutes without bg values - TT was still on 0% and must be canceled manually. 

### ISSUE THREAD

**Issue by Alamo04** [nightscout/AndroidAPS#1410]
DEV-E,, Pixel 5, Combo, Dexcom G6, Boyda.

My Dexcom Sensor Failed, shows 47 and my bg was at 110. So I stopped the sensor.
After 51 minutes without values, AAPS didn't cancel his zero temp, so I must do that manually. 

The bg was rising up to 210 in that time.

![Screenshot_20220304-180053](https://user-images.githubusercontent.com/36486505/156810634-4c0cc7b5-2cb8-48f1-90be-fc19777fd53f.png)

**Comment by yhonatanb20** [comment]
Experiencing same issue, starnge that the algorithm doesn't suspend itself when there are no BG values.

**Comment by philipgo** [comment]
IIRC zero temps should be limited to 30 minutes when blood glucose values are missing: https://github.com/openaps/oref0/blob/acb0150021e7bf284b6741a9510076a13f690747/lib/determine-basal/determine-basal.js#L161

**Comment by jotomo** [comment]
OpenAPS is only invoked when a new glucose value arrives and can manually be invoked only for glucose values max 7 minutes old. Hence the code mentioned above isn't invoked and the active temp runs until finished (I'm guessing in an OpenAPS setup, the algo is triggered periodically, so it runs even if no new glucose values have arrived?)
Given the last inputs to OpenAPS in this case a long zero temp seems like an appropriate defensive action.
With a failing sensor like that the user needs to take over control and take appropriate action I'd say.
