### ISSUE TITLE
Objectives : link in the sensitivity question

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1414]
In the objectives, it will be more helpfull to give this link to AutoSens instead of (or joint with) the AutoSens algorithm 

https://androidaps.readthedocs.io/en/latest/Usage/Open-APS-features.html?highlight=Autosens#autosens

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/e02e55ce324e4e7ef315d909689a12c335156cc6
