### ISSUE TITLE
Objectives:  string name="troubleshooting_hint3" still references link to old AAPS Gitter room

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#1415]
**Aindrond APS 3.0**

_examl.xml:_
string name="troubleshooting_hint3" still references link to old AAPS Gitter room at https://gitter.im/MilosKozak/AndroidAPS

Should be replaced with link to Discord as mentioned on Gitter Feb 20, 2022:
_"The chat has moved. Please join us on Discord: https://discord.gg/4fQUWHZ4Mw"_

**Comment by improving-jeffd** [comment]
Just built the app recently and am going through objectives. This question still references gitter in the answers:
![IMG_20220417_134323](https://user-images.githubusercontent.com/1213947/163729877-a646496f-4510-4b06-96ca-3dd417ef870b.jpg)
