### ISSUE TITLE
[AAPS 3.0.0.1] Omnipod Dash Priming Bugs

### ISSUE THREAD

**Issue by JazzZ1** [nightscout/AndroidAPS#1420]
Time of occurance in log: 08.03.2022, 11:15
Description:

###[Bug 1]###
Now I have my fourth Dash in row connected and working totally fine. But after priming and setting the canulla, it always shows a connection error. So i just have to click retry and it works fine. But this happens every single time on exactly these 2 steps, so I guess this could be a bug, simply fixed by a automated reconnect at the end of priming and setting.

Pod Firmware: 4.10.0

So here are my screenshots:

![Screenshot_20220308-111506_AndroidAPS](https://user-images.githubusercontent.com/64336417/157280191-2b5a51fd-5d2f-4143-ae04-b642440b3de4.jpg)
![Screenshot_20220308-111516_AndroidAPS](https://user-images.githubusercontent.com/64336417/157280248-83908ad9-1515-46a1-9ecb-12238d004143.jpg)

So after priming I always get this error, where I every time need to click retry to be able to continue:
![Screenshot_20220308-111625_AndroidAPS](https://user-images.githubusercontent.com/64336417/157280315-39c7f1b4-010f-44b3-ac51-e55eb11df137.jpg)
![Screenshot_20220308-111631_AndroidAPS](https://user-images.githubusercontent.com/64336417/157280357-ee4fcf54-8bac-42a9-bb7b-596e3376c634.jpg)
![Screenshot_20220308-111635_AndroidAPS](https://user-images.githubusercontent.com/64336417/157280413-f7cfe79e-8d1c-479e-87cd-3550b3e1a16a.jpg)
![Screenshot_20220308-111639_AndroidAPS](https://user-images.githubusercontent.com/64336417/157280469-50d97dba-760a-416e-b4d2-a63a21c44fb5.jpg)

And after continuing to attach, it immediatly shows the same error again, so again I need to click retry to be able to attach the pump:
![Screenshot_20220308-111712_AndroidAPS](https://user-images.githubusercontent.com/64336417/157280536-ce7bac92-259d-422e-ae59-544baa6a4475.jpg)
![Screenshot_20220308-111739_AndroidAPS](https://user-images.githubusercontent.com/64336417/157280595-146fa6a1-9509-4970-9e91-c041a88c1d12.jpg)
![Screenshot_20220308-111747_AndroidAPS](https://user-images.githubusercontent.com/64336417/157280649-bf292cd6-165b-46de-8627-018e2f6fa050.jpg)

###[Bug 2]###
I use the setting "Display always on", but still the display turns off while priming and attaching the Dash pump. On all other screens it works normally.

Log: 
[AndroidAPS_pump.log](https://github.com/nightscout/AndroidAPS/files/8207928/AndroidAPS_pump.log)

Build: 479bfc4-2022.02.06-18:41

**Comment by macarolobe** [comment]
Same errors for me

**Comment by keltakmaster** [comment]
Yeah, same issue here too!

**Comment by Mynez** [comment]
Not work for me, it does not initialised
