### ISSUE TITLE
AAPS treatements has a strange date in the future

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1421]
EDIT : This is NOT an NS problem as I started issuing. It is about a strange date in AAPS treatments. You can skip the first messages...

I use BYODA and G6 sensor. I _Stop sensor_ and then _Start new sensor_ in BYODA. This information arrives and is treated correctly in AAPS. I can see sensor age in AAPS.

The bug is (maybe) in the way this information (new sensor insertion/start) is sent to NS by AAPS. The sensor inserted message is on the treatments tab of NS but NS doesn't show SAGE data.

![sage_no_age.png](https://user-images.githubusercontent.com/76626474/157291930-be422b0f-7b07-4fda-9fc0-d49c0be2dbc0.png)

People seem to have the SAGE working in NS if they note the sensor change **in AAPS**. In my case, the sensor change information arrives from BYODA to AAPS.

![Screenshot_20220308-072215_Discord.jpg](https://user-images.githubusercontent.com/76626474/157292321-782ccae4-536a-4122-9f85-9ec0c54b8c5c.jpg)

**Comment by robertrub** [comment]
I might have found the culprit. This had happened before. The CGM change date is totallt wrong in treatments in AAPS...

![Screenshot_20220308-191519_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/157303352-973513d8-c04a-45a3-b971-6b25a719065e.jpg)

And here is the real sensor change date from BYODA.

![Screenshot_20220308-193802_Dexcom G6.jpg](https://user-images.githubusercontent.com/76626474/157303546-14474633-5e77-4707-99db-b22fdec798b2.jpg)

Sorry, no logs :(

**Comment by robertrub** [comment]
It is becoming more and more strange...

![Screenshot_20220308-194004_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/157303997-103c3065-1fff-4608-93fa-39f3271b091a.jpg)

AAPS has the real insertion date too. I don't know from when the 2106 entry dates...

I can't delete the 2106 entry, it says _invalid_ after I tried to delete it...

**Comment by CaptainBalou** [comment]
Same entry for the same date here... I can't see the year but because it is on the top of the list I assume it is in the future and so it would be the same.

![Screenshot_2022-03-08-20-43-35-90_3eaa31bb2c2a38a1c605d9dc918cf694](https://user-images.githubusercontent.com/17015872/157314449-cb718b28-4aed-4e2d-b9a5-4778ac911ad3.jpg)
![Screenshot_2022-03-08-20-44-13-99_3eaa31bb2c2a38a1c605d9dc918cf694](https://user-images.githubusercontent.com/17015872/157314466-28330cfa-ea91-4748-97fb-81a7123f0342.jpg)

**Comment by robertrub** [comment]
@CaptainBalou Funny, it is the same exact date as mine... Even the same time stamp !
It is not something that came from BYODA most probably but where did AAPS get this entry is a mystery...

**Comment by CaptainBalou** [comment]
@robertrub Yes, just because it is a full match I decided to write that comment. :-) I also use BYODA. Unfortunately I have no suggestions what the issue could be. Just wante to tell that you're not alone with this. ;-)

**Comment by kristinsmotz** [comment]
I have seen this as well a few weeks ago, definitely year 2106, don't remember exact date. Also resolved it by deleting future treatments in Nightscout Admin tools.

**Comment by happygirlnyc70** [comment]
I also had the future entry.  I removed it from the treatment tab.  Nightscout resolved itself at my next sensor change. Using dev-e.
