### ISSUE TITLE
[3.0.0.1] Incorrect (future) timestamp in AAPS+ NightScout on Dex sensor change (BYODA)

### ISSUE THREAD

**Issue by AISMap** [nightscout/AndroidAPS#1426]
Hi,

I use BOYDA for managing my Dex G6 sensor and AAPS 3.0.0.1 as receiver. Sensor changes are kept automatically and sent to NightScout. 

Since I changed to AAPS 3.0.0.1 the timestamp for sensor change is not correct:
![image](https://user-images.githubusercontent.com/49242886/157636483-833e9842-5038-4b8c-9629-e36f77b25770.png)

sensor change happened` 2022-Mar-10 07:26 CET` - displayed in AAPS as well as sent timestamp to NightScout is `2106-02-07T06:28:1500Z` instead.
![image](https://user-images.githubusercontent.com/49242886/157636303-a2c78c4d-e403-42f3-9ddd-fb70ffde897a.png)

AAPS does not allow to delete this wrong data anymore, it is possible only flagging it as "invalid".

Please get that fixed as it spoils up NightScout data as well as AAPS. Thank you

**Comment by reijoahola-nightscout** [comment]
This seems to be about the same problem: https://github.com/nightscout/AndroidAPS/issues/1421

**Comment by ideaweb** [comment]
Quick question, did you use the action button to let APS know that you changed the Sensor? I had the same problem, when using the action button that date appears in future. But after avoiding the button its working for me because it seems that BYODA notifies APS automatically about sensor change. Maybe this is the trouble maker that APS has 2 dates... but of course maybe I am wrong.

**Comment by CaptainBalou** [comment]
@ideaweb I used xdrip for a while and there I used the action button to reset the time of the sensor. Since a few months I'm back on BYOD app and do not need this anymore because of the automatic notification as you mentioned.

**Comment by AISMap** [comment]
Hi,

No - I haven't done anything manually. AAPS creates the change date automatically after having received the info from BYODA. I am running this setup quite a while and with 2.8.2 there was never an issue.

/Arne

11.03.2022 10:19:21 Tom ***@***.***>:

**Comment by MilosKozak** [comment]
added validation https://github.com/nightscout/AndroidAPS/commit/58b49a05eaefd96a9273942b46217e0fe0fb71e1
