### ISSUE TITLE
3.0.0.1 Import Settings with corrupted json crushes app

### ISSUE THREAD

**Issue by naamanmeir** [nightscout/AndroidAPS#1439]
the existance of a corrupted json file that was exported from older version in the preferences folder
was causing the entire app to crush and restart once clicking the Import Settings button on the Maintenance menu

only after removing the corrupted file from the preferences folder it is possible to open the import screen after clicking import.
once the file is in the folder clicking Import Setting immediately restarts the app, and the import selection is not accessible.

the corrupted json file is attached , when that file is in folder the app crushes.
[corrupted json.zip](https://github.com/nightscout/AndroidAPS/files/8240205/corrupted.json.zip)

i dont know what happens when the file was exported and what caused the corruption.
new and other exports are working fine.
i can attach the log file but to my knowledge there is nothing there regarding the error.

the error was solved by removing the corrupted file and Import of other files works ok.

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/b31e328022e438f46eed4380e33d914639b1b350
