### ISSUE TITLE
[3.0.0.1] Buttons disappear when pump is disconnected

### ISSUE THREAD

**Issue by Rhabarbara745** [nightscout/AndroidAPS#1441]
Since 3.0.0.1 it's not possible to access Insulin Dialog and BolusWizard when the pump is disconnected.

This leads to the following problems:

- it is not possible to tell if a bolus should be given when the pump is disconnected from the body (eg. when swimming)
- "Do no bolus, record only" checkbox is more or less useless now
(because the pump must be reconnected to enter that insulin -> SMB kick in at the moment of reconnection, before even having the chance to enter already injected insulin.)

Since this is a major drawback compared to previous versions, my proposal would be reverting to the old behavior and if necessary, disable the "OK" buttons in BolusWizard and InsulinDialog when disconnected.

**Comment by MilosKozak** [comment]
this settings was in AAPS all the time. The reason is very simple. If pump is not initialized (not known to AAPS) it's not possible apply constrains from pump.
SMB is not kicked on reconection but on next BG

**Comment by Rhabarbara745** [comment]
Thanks for your quick reply @MilosKozak 

I'm not sure if we're talking about the same thing. By "disconnecting" I meant pressing the disconnect buttons (15min, 30min, 1h, ...) in the loop dialog. (the pump is already known by aaps at this stage)

<p float="left">
<img src="https://user-images.githubusercontent.com/57756367/158079097-1067ac57-3947-451e-b5f3-0fb691dc49e9.png" width="400">
<img src="https://user-images.githubusercontent.com/57756367/158079018-88a545c5-d7cc-4dd8-822a-0701664083f8.png" width="400">
</p>

**Comment by MilosKozak** [comment]
undestand now. but the answer is still the same. it can be confusing to see insulin dialog when pump is disconnected
