### ISSUE TITLE
Watch Face AAPSv2 Missing IOB and 10min BG Delta

### ISSUE THREAD

**Issue by erobinson** [nightscout/AndroidAPS#1451]
* Running latest dev for AndroidAPS app & wear app. 
* WatchFace AAPSv2 but also seems to impact other watch faces
* Running w/ Dyanmic ISF config (not sure if this makes a difference

![PXL_20220317_202539655](https://user-images.githubusercontent.com/1564297/158889606-38f44043-fe65-4d70-8262-b9c4e0691f3f.jpg)
)

@Andries-Smit

**Comment by Andries-Smit** [comment]
@erobinson is this still happening?  I think it should be temporary. Not all data is available at the start of your watch app. Therefore the data will be updated with 3 different data sets.

**Comment by erobinson** [comment]
It's been like that for a few weeks, haven't done any debugging/testing to isolate the problem.

**Comment by erobinson** [comment]
Found that I didn't have the show delta & show IOB settings turned on 😢 All working fine.
