### ISSUE TITLE
Minor actions tab 3 dot menu bug

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1475]
Actions tab, I hit 3 dots menu. I see the preferences for the actions but I can't tap and open the option.

![Screenshot_20220321-180115_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/159325868-577e47a3-01a9-400f-9bc1-012eadd78604.jpg)

![Screenshot_20220321-175551_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/159325882-7e85b8c9-5354-436b-8feb-ba63d0177965.jpg)

**Comment by Thomas-Wolff** [comment]
Yes, I also notice the same behaviour.
In the tabs where it works, the arrow key at the top left no longer brings you back.

Greetings Thomas

**Comment by robertrub** [comment]
@Andries-Smit I know that there are no options fir actions. The bug is that the "Action pref" line is in the list of the menu. Unclicable but there ;)
