### ISSUE TITLE
[3.0.0.1-dev-g] Notifications from automations display twice 

### ISSUE THREAD

**Issue by kristinsmotz** [nightscout/AndroidAPS#1477]
Have noticed since building dev-g this weekend, and it persists after rebuilding today, that notifications from automations are duplicated in the header of AndroidAPS, once with red background and once with orange. One of them disappears if the system notification is swiped closed, but the other one must be OK'ed within AndroidAPS. 
Relevant screenshots:
![received_389914309225728](https://user-images.githubusercontent.com/71758682/159360373-617b21c3-8eee-4560-9941-74e867413630.jpeg)
![received_1121695428624273](https://user-images.githubusercontent.com/71758682/159360385-621731b4-25ad-45f3-a016-2895a0a1686c.jpeg)
![received_525450725863686](https://user-images.githubusercontent.com/71758682/159360394-fa97814d-a9ec-469d-a6d8-5a7fad2deb1c.jpeg)
![received_329998228978096](https://user-images.githubusercontent.com/71758682/159360408-1a2528ad-75bb-4916-918c-ab6670d726b1.jpeg)

Will add Log when I get to my computer later.

**Comment by kristinsmotz** [comment]
[AndroidAPS_LOG_1647894842341.log.zip](https://github.com/nightscout/AndroidAPS/files/8322819/AndroidAPS_LOG_1647894842341.log.zip)

**Comment by MilosKozak** [comment]
you setup sending notifications to NS and receive it back too. Then you get them twice
