### ISSUE TITLE
Constantly Notification from ANDROIDAPS PumpControl

### ISSUE THREAD

**Issue by rdurbano** [nightscout/AndroidAPS#1478]
Hello everyone!

I installed the last version yesterday and I noticed that the ANDROID APS PumpControl sending notifications for all glucose glucose information to xDrip and Nightscout. See the imagem below:
![Screenshot_2022-03-21-09-46-06-337_info nightscout aapspumpcontrol](https://user-images.githubusercontent.com/12244452/159381389-ec57ac24-e85d-4bb0-82c0-34f5f8fe3dfa.jpg)
![Screenshot_2022-03-21-09-45-45-338_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/12244452/159381398-25c0c292-72dc-4f4e-a62c-6cfc51952921.jpg)

**Comment by MilosKozak** [comment]
why are you doing profile switch every 5 min?

**Comment by rdurbano** [comment]
Is it a option in the app ? Is it possible disable ?

**Comment by duncanbarnes** [comment]
Possibly the same as #1536

> why are you doing profile switch every 5 min?

This looks the same as I see in which case it's happening by itself, not a manual action.

**Comment by MilosKozak** [comment]
resolved in dev
