### ISSUE TITLE
Reservoir Status light in NSClient

### ISSUE THREAD

**Issue by shafiro** [nightscout/AndroidAPS#1479]
NSClient 3.0.0.1-dev-g
Build 899270b7e-2022.03.20-08:35
Flavor: nsclientdebug
Nightscout version: 14.2.5
Omnipod Dash
Engineering mode enabled

Reservoir status light is always red on NSClient follower (Xiaomi mi9). Regardless of actual units remaining.
Reservoir status light is not red on main AAPS Phone, and not red in NS site. Just in NSClient follower.
It stays red even if "status lights" are turned off in NSClient preferences.
 
![image](https://user-images.githubusercontent.com/36660177/159431858-fbf5c1f8-55de-4da9-9d89-bc372ab52fdd.png)
![image](https://user-images.githubusercontent.com/36660177/159431902-f2d80a65-fec4-4d18-a25f-379cdb745c4d.png)

**Comment by MilosKozak** [comment]
what pump?

**Comment by shafiro** [comment]
Dash.

**Comment by kristinsmotz** [comment]
Pretty sure the status light color in NSClient has been red regardless of actual remaining amount for some time, I've seen this while using Eros as well. Checked my screenshots back to July 21, and all are red even with more than 50U left

**Comment by shafiro** [comment]
Yes, this goes a long way back and we had it with Eros on 2.x as well.

**Comment by MilosKozak** [comment]
Closed for inactivity. Create new issue is if you still see the problem on latest branch

**Comment by olorinmaia** [comment]
I can confirm the issue persist on latest master, if latest branch is what you mean by that. Omnipod dash.

**Comment by parapenT1sta** [comment]
> I can confirm the issue persist on latest master, if latest branch is what you mean by that. Omnipod dash.

DEV branch is the latest: https://github.com/nightscout/AndroidAPS/tree/dev
