### ISSUE TITLE
Feature /minor bug : TDD calculation delay

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1489]
The new look of _stats_ is GREAT :) Tnx.

At the same time, the time needed for the TDD calculations became even longer on the stats page (on a Samsung S9, not a _slow_ phone...). This "slowness" seems to impact DynamicISF on slow phones too.

I know changing db structure in the middle of a version is not the best option but maybe another way (without db change) to calculate could be found for a faster result.

Could AAPS calculate TDD of the past day at 00h00 and write it to the db or a file ? At 0h, there is usually not much activity and this way, the TDD calculations are already done when you need them.

**Comment by kamlox** [comment]
Seems related to the problem I have #1395
