### ISSUE TITLE
DEV G CRASH ON ANDROID 12

### ISSUE THREAD

**Issue by mick711** [nightscout/AndroidAPS#1490]
Hi try two time to compile last Dev branch for my Asus Zenfone 8 on Android 12 but when i would like to update Dev F when AAPS finish update impossible to start always crash impossible to have a log file.

**Comment by Alamo04** [comment]
Hmmm... don't think,  that's an Android12 thing,  because I'm using Android12 too and everything is fine. 🤔

**Comment by mick711** [comment]
I try tonight to factory reset my phone and see what happens

**Comment by parapenT1sta** [comment]
@mick711 also check if all permissions are set. I'm using Android 12 Beta with no issues and with latest dev build.

**Comment by mick711** [comment]
I don't know why but it's m'y backup or setting the problem. Factory reset and change POD now work, juste sée if it solve some rebout
