### ISSUE TITLE
How to download DATA from AAPS or NightScout

### ISSUE THREAD

**Issue by aflserna** [nightscout/AndroidAPS#1497]
HI, 
I can not find any way to download my personal data from NightScout. I would like to download all information (bg, basals, notes, bolus..) to use another source for reading and analysis. 
May i have some advice on how to do it?
Alberto

**Comment by Andries-Smit** [comment]
@aflserna Good question, the best place to ask is on the other platforms; Docs, Discord or Facebook. In GitHub, we track application features and bugs, and no user questions.

**Comment by MilosKozak** [comment]
usy NS /api/v1/
