### ISSUE TITLE
AAPS symbols is not visible!!!!

### ISSUE THREAD

**Issue by Thomas-Wolff** [nightscout/AndroidAPS#1498]
With update to AAPS 3.0.0.1-dev-g commit ea995f705, AAPS icon no longer visible in mobile phone status bar.

![Bild1](https://user-images.githubusercontent.com/59526802/159951880-cf6f626c-0ab5-4f6d-86e8-0604f9024491.jpg)

Greetings Thomas

**Comment by Andries-Smit** [comment]
@Thomas-Wolff thanks for report, it will be fixed soon
