### ISSUE TITLE
Trend arrows are displayed incorrectly.

### ISSUE THREAD

**Issue by elgrupo123** [nightscout/AndroidAPS#1504]
Trend arrows are displayed incorrectly.
For a long time I have observed that the divider arrows in AAPS are displayed incorrectly on high climbs. In XDrip, the are displayed correctly and forwarded to AAPS.

d33ce02 Omnipod Dash/Libre2/Pixel 4a.
![Screenshot_20220325-135031](https://user-images.githubusercontent.com/92778761/160230652-01c42f36-11ec-427d-a348-f45ecdcee3c1.png)
![Screenshot_20220325-135047](https://user-images.githubusercontent.com/92778761/160230654-91f0bd67-dc1b-4f42-b25d-3d77c2fdb16e.png)

**Comment by MilosKozak** [comment]
you need to provide logs with time when this happen

**Comment by elgrupo123** [comment]
[AndroidAPS_LOG_1648328454277.log.zip](https://github.com/nightscout/AndroidAPS/files/8356435/AndroidAPS_LOG_1648328454277.log.zip)

**Comment by MilosKozak** [comment]
I need exact time + log from this time + screenshot 
together

**Comment by elgrupo123** [comment]
Here's another example.
Here's another example.
Saturday, March 27, 2022 at 2:00 p.m

![signal-2022-03-28-111321_002](https://user-images.githubusercontent.com/92778761/160367138-4ad7a8fc-6430-43bb-a286-af8e6238046d.png)
![signal-2022-03-28-111321_001](https://user-images.githubusercontent.com/92778761/160367140-144c9c16-afbc-4937-b211-7b252f2be734.png)
![signal-2022-03-28-111321_003](https://user-images.githubusercontent.com/92778761/160367143-3fff5052-7274-4dcd-b67b-ca9f8333d73c.png)

[AndroidAPS_LOG_1648382552992.log.zip](https://github.com/nightscout/AndroidAPS/files/8361345/AndroidAPS_LOG_1648382552992.log.zip)

**Comment by MilosKozak** [comment]
`Received xDrip data: Bundle[{com.eveningoutpost.dexdrip.Extras.NoiseBlockLevel=200, com.eveningoutpost.dexdrip.Extras.BgSlope=8.652649374679686E-5, com.eveningoutpost.dexdrip.Extras.VersionInfo=2122032611 b66817e-2022.03.26, com.eveningoutpost.dexdrip.Extras.Raw=209.99999999999997, com.eveningoutpost.dexdrip.Extras.Time=1648382345344, com.eveningoutpost.dexdrip.Extras.CalibrationInfo=1648071747297, com.eveningoutpost.dexdrip.Extras.NsNoiseLevel=null, com.eveningoutpost.dexdrip.Extras.Noise=-9999.0, com.eveningoutpost.dexdrip.Extras.SensorBattery=-1, com.eveningoutpost.dexdrip.Extras.CalibrationPluginInfo=OOP , com.eveningoutpost.dexdrip.Extras.NoiseWarning=0, com.eveningoutpost.dexdrip.Extras.BgSlopeName=DoubleUp, com.eveningoutpost.dexdrip.Extras.BgEstimate=210.0, com.eveningoutpost.dexdrip.Extras.SourceDesc=Other App, com.eveningoutpost.dexdrip.Extras.SourceInfo=Libre2 Native, com.eveningoutpost.dexdrip.Extras.Collector.NanoStatus=}]`

`Received NS Data: [{"_id":"62405189e13c53240ae83f39","mgdl":210,"mills":1648382345344,"device":"xDrip-NSFollower","direction":"Flat","filtered":0,"unfiltered":0,"noise":1,"rssi":100,"type":"sgv","scaled":210}]`

* you receive from xDrip with correct direction
* then you receive data from NS with direction "Flat", data is marked comming from xDrip-follower

you should definitely review your configuration and:
* define single path to upload to NS
* all other clients put to read only mode
* disable download of Bg data from NS if you want to receive them from xDrip in AAPS

**Comment by elgrupo123** [comment]
thank you very much for the advice. 
It worked!  Thanks!!!
