### ISSUE TITLE
DST Dana RS stuck at reading history

### ISSUE THREAD

**Issue by mxsrm** [nightscout/AndroidAPS#1506]
After DST AAPS is now stuck at reading the pump history. Manually fixing the pump time (which was already updated manually) and resetting the APS databases did nothing. Even though the. Message disappears after some time,  looping, setting temp ratios Etc. does not work.

AAPS 3.0.0.1

**Comment by CaptainBalou** [comment]
Same here. Can't bolus anymore. I'm sorry but i can't attach logs Herr because I'm mobile.

3.0.0.1-dev-g from three days ago

**Comment by CaptainBalou** [comment]
After issuing one bolus via the bolus calculator directly in the Pump AndroidAPS seems to work fine again. Bolus history can be read without error now.

**Comment by CaptainBalou** [comment]
[AndroidAPS_LOG_1648366340572.log.zip](https://github.com/nightscout/AndroidAPS/files/8357192/AndroidAPS_LOG_1648366340572.log.zip)

Finally i got the file uploaded. Hope this helps.

**Comment by CaptainBalou** [comment]
Also some additional screenshots If needed...

![Screenshot_2022-03-27-09-23-09-50_3eaa31bb2c2a38a1c605d9dc918cf694](https://user-images.githubusercontent.com/17015872/160273418-b13a0be9-6b1e-42a3-9a22-d286ca98adf7.jpg)

![Screenshot_2022-03-27-09-31-54-74_3eaa31bb2c2a38a1c605d9dc918cf694](https://user-images.githubusercontent.com/17015872/160273432-13f1fe76-c835-47c0-8c7f-4363c4065bb3.jpg)

![Screenshot_2022-03-27-09-45-32-68_3eaa31bb2c2a38a1c605d9dc918cf694](https://user-images.githubusercontent.com/17015872/160273438-ee410237-ca97-4e74-9ae5-d98ff6a30475.jpg)

**Comment by CaptainBalou** [comment]
After the manually issued bolus via the Pump all Looks good which is like this:

![Screenshot_2022-03-27-10-31-36-00_3eaa31bb2c2a38a1c605d9dc918cf694](https://user-images.githubusercontent.com/17015872/160273529-1270ad70-c761-46a6-956f-7cf9d1940cb6.jpg)

As you can see also all data since DST change ist now covered in the chart.

**Comment by mxsrm** [comment]
I can confirm manually bolusing on the pump helps.

**Comment by npsgr** [comment]
The solution is “delete history” in DanaRS. The procedure is 
1.	go to pump
2.	Unlock
3.	Then while pressing - at the same time press + sign and arrow
4.	Appears password  0000
5.	Go to third 0 and put 4
6.	Go to fourth 0 put 9
7.	Go to first 0 put 8
8.	Go to second 0 put 9
9.	All in this order 
10.	Message then delete history.

**Comment by pimeys** [comment]
I've had this issue a few times in the past week already. Yes, the last message here fixes it for a few days, but it comes back eventually. It's not very nice when the connection gets stuck at night, and I don't notice any issues and I get low or high and need to wake up. The DanaRS has been working perfectly for three years with AndroidAPS. I had a replacement pump with the new firmware, which also worked over a month perfectly. When I got a new smartwatch, the problems started to appear.

Does anybody know what is the root issue here? Is it something to do with the pump clock not being sync with the watch or phone?

**Comment by MilosKozak** [comment]
@pimeys communication can be affected by connected watch if phone BT stack is not good. try not to use watch for some time

**Comment by pimeys** [comment]
It seems to be the cause. I disabled wifi from the watch and it's been much better now with the pump...
