### ISSUE TITLE
OmniPod Dash "Insulin delivery is suspended" notification shortly after updating pump time for DST

### ISSUE THREAD

**Issue by Lastof** [nightscout/AndroidAPS#1507]
On waking this morning I had a notification that pump time was out of sync (due to the time change) so updated it from the Dash tab with the "Set Time" button that appeared. About 30 minutes later the pod beeped a notification beep (beep, beep, short pause, beep, beep, long pause, beep, beep, short pause, beep, beep). On refreshing the Active Pod Alert was "Insulin delivery is suspended"

Attached are my logs from between 7am and 8am, time update was at 7:18, alarm sync was at 7:47. AAPS 3.0.0, running with Engineering Mode enabled since I missed the extra details on the dash page from beta.

Also attached are an image of the Dash page with alert showing, and the pod history from time update till alert silenced.

After the alert I verified that a bolus would dispense (clicking heard fine), then did a profile switch (to 95% then back) to make sure basal was delivering (Total Delivered is still decreasing and I occationally hear the clicks). Seems likely to be something to do with DST change and the suspension when time is changed, so likely not urgent but would be nice to fix/document before the next DST change in Autumn.

[AndroidAPS._2022-03-27_07_00_00-08_00_00.log](https://github.com/nightscout/AndroidAPS/files/8357414/AndroidAPS._2022-03-27_07_00_00-08_00_00.log)
[Dash tab with Alert](https://user-images.githubusercontent.com/593705/160278386-c7037c68-0564-45cd-b8b0-d3be34a27bcd.png)
[Pod History](https://user-images.githubusercontent.com/593705/160278387-6e3f1829-e274-4a93-b709-8e0378457156.png)

**Comment by avereha** [comment]
This is not a bug:
https://androidaps.readthedocs.io/en/latest/Configuration/OmnipodDASH.html?highlight=Dash#resuming-insulin-delivery
Communication can fail during profile switches, there is nothing we can do in this case.
