### ISSUE TITLE
BUG Dev-h / Both activate and deactivate buttons are ON

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1509]
Since dev h, both DASH pod activate and deactivate buttons are "lit". Usually one is "lit" and the other is grayed according to the pod status. Not any more.

![Screenshot_20220327-193836_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/160293791-13734123-06a7-47be-a150-89df059e8c27.jpg)

![Screenshot_20220327-175954_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/160293794-2fe2b97c-1084-4a68-9211-9a4f9cc08da3.jpg)

**Comment by robertrub** [comment]
I deactivated the old pod and both were still lit. I activated a new pod and still both are lit

**Comment by Thomas-Wolff** [comment]
Hello Robby, I can confirm this, I have also done this with the EROS, see #1473.

Greetings

**Comment by Thomas-Wolff** [comment]
@MilosKozak, I have just updated AAPS again, unfortunately both buttons are still active, or will this only be adjusted again after the next change.

![Bild2](https://user-images.githubusercontent.com/59526802/160399783-030d1476-8408-4113-ade8-525a85c7a1b9.jpg)

![Bild1](https://user-images.githubusercontent.com/59526802/160399835-834ad648-e15e-4895-b289-ec2626cc6306.jpg)

Greetings Thomas

**Comment by Thomas-Wolff** [comment]
Thank you, done with commit: 59d6f146d.

Greetings
