### ISSUE TITLE
No and erroneous basal rate shown 

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1527]
I'm changing my G6. During the 2h warmup, I stop the loop to have the DASH deliver the basal rate.

On the screen, I just a trait with no rate; if I hit the small line, it says 0.48U/h but the DASH tab says 0.50U/h...

I'd like to see the real rate shown on the main UI.

![Screenshot_20220331-190440_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/161127822-f0274fbe-c993-4079-aa7b-66e98de49efa.jpg)

![Screenshot_20220331-204240_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/161127857-16c81e33-3bce-440e-8605-b2c3fafc451d.jpg)

![Screenshot_20220331-204256_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/161127883-094397fd-d0be-420a-a973-e2d0c7fe84d7.jpg)

![Screenshot_20220331-204306_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/161127893-d4194f58-6157-40af-8294-ce9ea7b6ed25.jpg)

**Comment by robertrub** [comment]
And the logs...

![AndroidAPS_LOG_1648752535686.log.zip](https://github.com/nightscout/AndroidAPS/files/8392310/AndroidAPS_LOG_1648752535686.log.zip)

**Comment by robertrub** [comment]
There is no basal curve on rhe graph for almost 2h either...

![Screenshot_20220331-222505_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/161143950-8ed1a507-a13b-4cb7-95b0-27ac86c8df8c.jpg)

**Comment by MilosKozak** [comment]
is this still happening?

**Comment by robertrub** [comment]
Not for me. I've never see it happen again. You can close this issue.
