### ISSUE TITLE
Minor esthetic/ BYODA icon lost contrast 

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1531]
I wonder why the BYODA icon is soo "washed", with no contrast.

![Screenshot_20220331-190440_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/161319350-c08d3eaf-1913-45aa-90c5-6aa0177b12dd.jpg)

![Screenshot_20220401-201034_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/161319375-ff46fc48-3564-49e9-886b-48a9902e16cd.jpg)

**Comment by osodebailar** [comment]
We can make the contrast higher and the icon brighter in dark mode .
