### ISSUE TITLE
Our beautiful XDrip CGM Icon is missing ;)

### ISSUE THREAD

**Issue by elgrupo123** [nightscout/AndroidAPS#1532]
![Screenshot_20220401-211530](https://user-images.githubusercontent.com/92778761/161328052-8ec3f5be-25cb-4320-a3ec-bfd49dbb6388.png)

**Comment by osodebailar** [comment]
Solved in dev

**Comment by elgrupo123** [comment]
but not yet in 07c7ac4 . but not that bad ;)

**Comment by reijoahola-nightscout** [comment]
Or is it fixed only for BYODA but not for xDrip+ ?

**Comment by osodebailar** [comment]
Yes indeed. I made a fix and push it after coffee ☕️ 😉
