### ISSUE TITLE
Pump Control in MDI bug upload data Treatment in Nightscout - openaps://AndroidAPS 

### ISSUE THREAD

**Issue by thiagomsoares** [nightscout/AndroidAPS#1536]
Using the Pump Control 3.0.0.1 version, in MDI, AndroidAPS creates a new Treatment input for each received reading (from xdrip) with the following description Using the Pump Control 3.0.0.1 version, in MDI, AndroidAPS creates a new Treatment input for each received reading (from xdrip) with the following description **openaps://AndroidAPS** + *Profile Name in cell phone* for each new reading received. The information appears in Nightscout and also in the AndroidAPS Overview graph.+ *Profile Name in cell phone* for each new reading received. The information appears in Nightscout and also in the AndroidAPS Overview graph.

**Comment by thiagomsoares** [comment]
!(https://raw.githubusercontent.com/thiagomsoares/cgm-remote-monitor/d17b9831748bbefab6139ba9d2c54e681541b97a/4f2fd694-66ca-46a1-9ad9-d03cb19fdaa1.jpeg)

**Comment by thiagomsoares** [comment]
![image](https://user-images.githubusercontent.com/5190162/161380361-cf4d139a-2a19-4918-93e2-248aaa574ed7.png)

**Comment by duncanbarnes** [comment]
Seeing what I believe is the same thing here as well, switched to virtual pump as a temporary workaround
![Screenshot_20220410-000229](https://user-images.githubusercontent.com/4053079/162630240-ae813d2a-1475-429f-99d2-f7423e666583.png)

**Comment by duncanbarnes** [comment]
Log files from my install

[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/8459487/AndroidAPS.log)

**Comment by MilosKozak** [comment]
resolved by https://github.com/nightscout/AndroidAPS/commit/1c8cd564917c6b9bd011eabff29b66f796dab375
