### ISSUE TITLE
WIDGET : Very cool except basal rate color and not "clicable"

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1542]
The WIDGET is a great addition, tnx :)

It would be better id the basal rate was not black on gray ;)

![Screenshot_20220403-103943_One UI Home.jpg](https://user-images.githubusercontent.com/76626474/161419556-caebc5b1-59cb-43dd-b954-2dca17fc1ea1.jpg)

**Comment by robertrub** [comment]
Taping on the Widget doesn't open AAPS :( Would be nice to have that possibility.

**Comment by robertrub** [comment]
If DynISF is selected, we have a n/a when in AAPS the info is present.

![Screenshot_20220403-125145_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/161424198-c332f3f0-8818-4865-829c-803a66258ee2.jpg)

![Screenshot_20220403-125205_One UI Home.jpg](https://user-images.githubusercontent.com/76626474/161424205-fd20b95a-4d02-47dc-bf37-6f36105e92f4.jpg)

**Comment by robertrub** [comment]
When carbs are required, the texts are too condensed. Could the required carbs be noted on a 2nd line?

![Screenshot_20220403-144115_One UI Home.jpg](https://user-images.githubusercontent.com/76626474/161428640-e9e13c34-aedf-42c5-966c-ff008f2556ae.jpg)

**Comment by MilosKozak** [comment]
added posibility to extend widget .... are there still any issues?

**Comment by robertrub** [comment]
The _Temp Basal_ is easy to see

![Screenshot_20220404-154451_One UI Home.jpg](https://user-images.githubusercontent.com/76626474/161557707-10c3cda3-6cbe-4326-aa54-9fc6678f0977.jpg)

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/issues/1558
