### ISSUE TITLE
[DEV] Enhancement: Time underneath carb icon

### ISSUE THREAD

**Issue by xJoe** [nightscout/AndroidAPS#1544]
The time stamp underneath the carb icon on home screen leads to an additional line which wastes space on small phones like Jelly 2 (see screenshot). Maybe there’s an option to have it optional or remove it?
Thanks for considering.
![27BB6A55-A033-4B9A-B64C-08D75EDD45EA](https://user-images.githubusercontent.com/13958493/161439150-1d0954d8-5ac7-42fc-9bbe-11d1a4d21c65.jpeg)

**Comment by peterleimbach** [comment]
![image](https://user-images.githubusercontent.com/4148261/161441013-36699860-d32c-400f-98f1-e62dfb986637.jpeg)

I have no time on my Jelly 2 but I can't remember to have changed anything. I use the 3.0.0.1.

**Comment by MilosKozak** [comment]
disable engineering mode

**Comment by peterleimbach** [comment]
@xJoe I did not realized that you meant the dev version. Now I have it too.

![image](https://user-images.githubusercontent.com/4148261/162274667-17fbd5db-003f-4b30-912b-6cab05889ba6.jpeg)

**Comment by MilosKozak** [comment]
should i keep this open?

**Comment by xJoe** [comment]
> disable engineering mode

Thought engineering mode is mandatory to run dev or do I understand something wrong?
Proposal was meant to be enhancement for next master.

**Comment by Andries-Smit** [comment]
Is the time info really needed, or added for debugging purposes? Can we remove it?

**Comment by MilosKozak** [comment]
recently there was an issue when COB was sometimes outdated. I added timestamp to be able verify it.
I cannot say if the problem persists or not
