### ISSUE TITLE
3.0.0.1 dev-h - Not tracking BG and IOB properly

### ISSUE THREAD

**Issue by cygrahampearson** [nightscout/AndroidAPS#1549]
Reporting bugs
--------------
- 16:30ish - April 3rd- after updating from Tim's dev to NSDev-H I wasn't able to use Dynamic ISF because "no glucose data available". BYODA is working fine and the current BG is showing up in AAPS but AAPS doesn't seem to be logging BG data or IOB data as there are no graphs at all. IOB and COB are totally wrong. Its not logging carbs that I enter. When I manually gave insulin it worked but it actually subtracted insulin from the IOB and it subtracted the wrong amount. 
- Samsung S9
- 
I re-installed Tim's Dev and Master 3 and they are both working fine. 
-
[AndroidAPS_LOG_1649021558722.log.zip](https://github.com/nightscout/AndroidAPS/files/8405581/AndroidAPS_LOG_1649021558722.log.zip)

![Screenshot_20220403-165244_AndroidAPS](https://user-images.githubusercontent.com/73077567/161450538-b2b6ac33-f0a0-4aaa-b76f-f1fad6e9bb70.jpg)

![Screenshot_20220403-165239_AndroidAPS](https://user-images.githubusercontent.com/73077567/161450539-1b55c60a-a40f-4652-85d3-3142fc764c0a.jpg)

**Comment by cygrahampearson** [comment]
I just did a fresh build of Dev-H and the same issue is happening. IOB was wrong after install. It was listed at .81 U. I gave a manual bolus of 0.05U and the IOB lowered to 0.35U. I think this could be a serious issue. Master and Tim's Dev G are still working perfectly. If you want me to do a video to show the IOB going down when insulin is given let me know

[AndroidAPS_LOG_1649026172994.log.zip](https://github.com/nightscout/AndroidAPS/files/8405668/AndroidAPS_LOG_1649026172994.log.zip)
@MilosKozak @tim2000s

**Comment by MilosKozak** [comment]
nothing is visible in logs

**Comment by cygrahampearson** [comment]
@MilosKozak I'll rebuild and make sure to restart phone before running to make sure logs are working properly. I'm on day 3 of covid so it might take me a couple days

**Comment by cygrahampearson** [comment]
@MilosKozak the issue is resiolved in Dev-I. I took a video of the issue in dev h and will send later today
