### ISSUE TITLE
Default temp-targets won't set from watch

### ISSUE THREAD

**Issue by yhonatanb20** [nightscout/AndroidAPS#1555]
When trying to set a predefined temp-target (ex. Eating Soon) from the new temp target tile I get an error:
![Watch_Screenshot_220404-153731](https://user-images.githubusercontent.com/93551840/161548761-be8ea6e7-bc91-4d90-aeb4-7965b8a544d5.jpeg)
Setting manual temp-target from watch works OK.
**Using dev version on wear only, 3.0.0.1 master on phone. Great tiles feature in general, thanks a lot!

**Comment by MilosKozak** [comment]
i believe this is already fixed in dev. can you test it?

**Comment by robertrub** [comment]
Do you have the same versions on AAPS and watch (built from the same dev version )?

**Comment by yhonatanb20** [comment]
No. As I said I use dev on watch only...

**Comment by robertrub** [comment]
Might explain the bug. Can you try dev on both ? I can set TT from tiles on my watch.

**Comment by yhonatanb20** [comment]
I would like to do so, but since I use aaps for daily use, stability is very important for me on phone...

**Comment by robertrub** [comment]
Probably fixed in one of the devs. Dev-F on watch and Dev-I on phone. Set _Activity_ from the watch tiles and phone set a TT of 150. It is now working.

I think you can close this issue.
