### ISSUE TITLE
AAPS taking into account previous reading

### ISSUE THREAD

**Issue by yhonatanb20** [nightscout/AndroidAPS#1556]
Version 3.0.0.1, BG source xdrip:
If aaps looses bg readings (I get away from phone, phone restarts), and then gets updated reading + missed readings restored by transmitter, for some reason it takes into account the previous reading (the one before te most updated), until it gets the next one:
![Screenshot_20220403-181556_AndroidAPS](https://user-images.githubusercontent.com/93551840/161551826-70c2d043-a9bb-4187-920b-79c85a9ee97f.jpg)
![Screenshot_20220403-181607_AndroidAPS](https://user-images.githubusercontent.com/93551840/161551839-6e2cff2b-c191-49e1-b342-49f7e49ae571.jpg)

**Comment by MilosKozak** [comment]
it's a question to xDrip, what xDrip really broadcasts
for AAPS BOYDA is highly recommended
