### ISSUE TITLE
Esthetic bugs on version 3.0.0.1 graph

### ISSUE THREAD

**Issue by yhonatanb20** [nightscout/AndroidAPS#1557]
On version 3.0.0.1 (master) I experience two bugs regarding the displayed graph:
1. Last reading displayed on top but not on graph:
![Screenshot_20220404-160541_AndroidAPS](https://user-images.githubusercontent.com/93551840/161555182-b1f2732c-2238-471a-8d84-4d1282a4060b.jpg)
![Screenshot_20220402-160719_AndroidAPS](https://user-images.githubusercontent.com/93551840/161555187-40a355fd-d62d-409a-bae4-64fe11aaf609.jpg)
2. More rarely, there is just a part of the graph displayed (the most updated part):
![Screenshot_20220316-081245_AndroidAPS](https://user-images.githubusercontent.com/93551840/161555372-6a1ff9ed-7c09-4717-9d48-2e980f30a1fa.jpg)
*Both those problems are resolved by switching the graph all the way to 24hr and back to 3hr view.

**Comment by robertrub** [comment]
I'm not sure if AAPS ever showed the BG on the graph itself.

The second point has been solved in dev.

**Comment by yhonatanb20** [comment]
Of course it didn't. I mean that the last point is absent on the graph: see the first screenshot for ex.: there is no red point on the graph.

**Comment by robertrub** [comment]
I don't have that missing point in dev. Maybe it was solved too. Didn't remark it missing before.

![Screenshot_20220405-140404_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/161749834-0ab7d336-1a9a-4555-940f-498fe413c43b.jpg)

**Comment by MilosKozak** [comment]
hopefully resolved in dev
