### ISSUE TITLE
Profile helper text button text dark on dark theme

### ISSUE THREAD

**Issue by guydavies** [nightscout/AndroidAPS#156]
Transferred from MilosKozak/AndroidAPS at request of @andyrozman

When using the profile helper in the current Dev build and every time I've previously tested, the button at the top of the screen shows black text on a dark background so it is barely visible.

I suspect this is just not adjusting at all to the dark mode.

https://photos.app.goo.gl/eNxD8nNpie5RxY1e9

**Comment by osodebailar** [comment]
test it on 2.7.3-dev and button show text and icon correct
![Screenshot_1609347737](https://user-images.githubusercontent.com/25795894/103368954-34d22000-4ac9-11eb-81d7-9fd2458769a2.png)
![Uploading Screenshot_1609347794.png…]()

**Comment by Philoul** [comment]
The issue on this layout (minor) is for me the + and - buttons (black square around them and not centered vertically for "+" char)

**Comment by guydavies** [comment]
Agreed. My issue does now seem fixed but I also see the minor issue
described by Philoul. It's quite irritating once pointed out to me 😉

**Comment by Philoul** [comment]
It's link to ProfileHelperAppTheme style, but I don't know how to fix it.
I tried to use default AppTheme style (but AAPS crash), and I don't find which properties and setting to add/modify in ProfileHelperAppTheme to fix it.

**Comment by rICTx-T1D** [comment]
> It's link to ProfileHelperAppTheme style, but I don't know how to fix it.
I tried it too and I don't solved it :(

But the vertical-alignment of labels are improved.

**Comment by AdrianLxM** [comment]
Issue behind this: If the theme is a Material theme, the general Button will become a MaterialButton.
On a `MaterialButton` the `background` attribute alone will not work. `app:backgroundTint` should do it.

**Comment by AdrianLxM** [comment]
:) Thanks @guydavies for taking this over. Fixed, I hope.
