### ISSUE TITLE
WIDGET/ Esthetic/ Change background color intensity

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1563]
If it is not too much work, it would be nice to be able to change the saturation of the background color. The big massive gray bloc looks "old" compared to other widgets (time in the below example)

![Screenshot_20220405-134454_One UI Home.jpg](https://user-images.githubusercontent.com/76626474/161747663-01137455-eba0-48c5-a9a2-b0e1f23bbc94.jpg)

![20220405_134548.jpg](https://user-images.githubusercontent.com/76626474/161747692-93472444-1ea3-4564-ae5c-c48f2acbaa57.jpg)

**Comment by osodebailar** [comment]
As a proposal I would try a black with alpha .
Than it will have a nice glass look

**Comment by robertrub** [comment]
@osodebailar What it "black with alpha" ???

**Comment by osodebailar** [comment]
Black with alpha is black with x% transparency.
You can set any Color with an alpha value .
If you take black with an alpha value you get a glass effect .
If you take white with alpha it’s like a milk glass effect

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/1d2ecb257c7cafe585a6070e9614cb8d998ab752

**Comment by osodebailar** [comment]
@MilosKozak : perfectly done

**Comment by MilosKozak** [comment]
setBackgroundResource doesn't have rouded corners
