### ISSUE TITLE
[3.0.0.1-dev-i] Error in BG Check value when transferred from AAPS into NSClient

### ISSUE THREAD

**Issue by reijoahola-nightscout** [nightscout/AndroidAPS#1564]
When giving "BG Check" value in AAPS, it is transferred also into NightScout and NSClient app but
BG value is shown wrongly in NSClient app. The value in NSClient is the right BG value divided by 18.

This was tested with the latest 3.0.0.1-dev-i but the problem has been also in previous dev releases.
I am not sure is this a problem in NS or AAPS/NSClient.

I use mmol/L in all places (AAPS, NS, NSClirent).

**Comment by kristinsmotz** [comment]
I logged two BG checks last night/this morning. They show the correct mmol/l value in Nightscout report "Treatments" tab, but wrong value (mmol/18) in NSClient, if that helps at all. 
![image](https://user-images.githubusercontent.com/71758682/161841289-0d85a507-31ad-4616-89a6-6de3effd348a.png)
![Screenshot_20220405-222138_Log Viewer](https://user-images.githubusercontent.com/71758682/161842690-c85aae07-6547-46b3-9cc1-310d33aca236.jpg)
This log is from NSClient app. 
[AndroidAPS._2022-04-05_11-50-40_.0.zip](https://github.com/nightscout/AndroidAPS/files/8421635/AndroidAPS._2022-04-05_11-50-40_.0.zip)

**Comment by MilosKozak** [comment]
I tested now (AAPS dev, NS dev) and works like expected
