### ISSUE TITLE
WIDGET / Esthetic: 1 space between numbers

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1566]
Ok, I know I'm pushing but if we could have a leading space before the numbers, they wouldn't be stuck to each other and easier to read when the info is a bit long...

![Screenshot_20220405-171839_One UI Home.jpg](https://user-images.githubusercontent.com/76626474/161788290-4380754e-b1b3-43b7-9783-6b5dd8fa9275.jpg)

**Comment by MilosKozak** [comment]
![image](https://user-images.githubusercontent.com/11146458/161830181-66244d3e-bee9-4752-b73d-6f610caee8bd.png)

**Comment by robertrub** [comment]
Ha ha ha, of course... but that brings forward another bug ;) The information is not centered on the screen ;) It sticks to the right side. 

![Screenshot_20220405-213040_One UI Home.jpg](https://user-images.githubusercontent.com/76626474/161834996-5e727fc2-939c-4937-801b-068f6a0b9265.jpg)

I beta test my dental software too. One of the other testers is capable of seen an icon 1 pixel misplaced... We all became very attentif to position ;)

More seriously, if you can center, great. If it's complex, don't lose time on it.

**Comment by kristinsmotz** [comment]
I have a couple of comments as well. On my Samsung Zflip3 with NSclient the widget looks perfect. On my daughter's Huawei P30 Pro with AndroidAPS, the widget needs to be as large as 3x5 "slots" to display all the information. In 2x4 the text line below the treatment symbols is completely missing, in 2x5 we can see the top pixel of the text. I would also suggest the background be just a little bit less transparent, as with a noisy background it's very hard to read. Would it be possible to make some of this customizable so we could choose sizing/background transparency by preference? 
Samsung/NSclient 2x4:
![Screenshot_20220405-233302_One UI Home](https://user-images.githubusercontent.com/71758682/161854539-f265e7d1-823b-43bf-b47d-f0babd6cea12.jpg)
Huawei AAPS:
2x4
![277830237_393465545639569_2733067481673599367_n](https://user-images.githubusercontent.com/71758682/161854631-58d4753c-dedf-4c4d-a9d0-faaf232b9d87.jpg)
2x5
![277808866_1105108283382597_5244261232656343756_n](https://user-images.githubusercontent.com/71758682/161854642-76309ff4-5888-40ef-827c-845ba47bfaeb.jpg)
3x5
![277826456_267805425444953_2184090687700931383_n](https://user-images.githubusercontent.com/71758682/161854653-1d780890-09ce-4633-857c-124ab05164d6.jpg)

**Comment by MilosKozak** [comment]
as you see it's different on every phone and probably not possible to create general solution because set of features inside widget is VERY limited compared to application
You may try to play with system text size
