### ISSUE TITLE
Double BG after G6 calibration is back

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1582]
@MilosKozak You had solved the double BG with calibration near the 5 min after last read. This happened this morning with a G6 calibration just after the "normal" BG read. G6 with BYODA 1.9

![Screenshot_20220407-075321_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/162136779-5700460b-e3b8-44dc-ab09-69c897b58bb6.jpg)

![Screenshot_20220407-075335_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/162136794-54727424-d128-4f64-81a0-8e4d85be3db9.jpg)

![Screenshot_20220407-075533_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/162136806-049bb87b-f0bf-4792-9814-6e435edf1113.jpg)

![Screenshot_20220407-080139_Dexcom G6.jpg](https://user-images.githubusercontent.com/76626474/162136825-98175b32-2151-4f3f-8892-0f7257fb1c33.jpg)

![AndroidAPS_LOG_1649310850774.log.zip](https://github.com/nightscout/AndroidAPS/files/8440276/AndroidAPS_LOG_1649310850774.log.zip)

**Comment by MilosKozak** [comment]
this part is missing in logs. could you look for the correct one?

**Comment by robertrub** [comment]
Oups sorry. This one should be the correct one.

![AndroidAPS_LOG_1649415857979.log.zip](https://github.com/nightscout/AndroidAPS/files/8456797/AndroidAPS_LOG_1649415857979.log.zip)

**Comment by robertrub** [comment]
Strange as I had exported the log rapidly after the bug. Sorry, it's the only one I have.

I'll try to trigger the red triangle with the next calibration and catch the correct log.

**Comment by robertrub** [comment]
@MilosKozak Could not trigger the red triangle yet. Still trying to calibrate near the "normal BG read" times by the transmitter.

**Comment by robertrub** [comment]
@MilosKozak I'm closing this issue. Was never able to create the situation again.

I'll open a new one if it happens again.

Rob
