### ISSUE TITLE
[3.0.0.1-dev] unbelievable values when adjusting the ISF.

### ISSUE THREAD

**Issue by 69nobody** [nightscout/AndroidAPS#1583]
Since April 1st, I have been using the "DEV - DynISF".
Since yesterday it comes to unbelievable values when adjusting the ISF. See logs
I have uninstalled the program, restarted the phone and reinstalled the program. But this did not change the ISF values.
Maybe it is just a graphical error.
The values rose above 10000 in the display.

[AndroidAPS (1).log](https://github.com/nightscout/AndroidAPS/files/8442018/AndroidAPS.1.log)
[AndroidAPS._2022-04-07_11-40-05_.1.zip](https://github.com/nightscout/AndroidAPS/files/8442024/AndroidAPS._2022-04-07_11-40-05_.1.zip)

**Comment by MilosKozak** [comment]
discuss this on discord
