### ISSUE TITLE
BUG : stuck in temp basal

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1588]
I stopped the loop. I thought that the basal would kick in. It did not. On rhe DASH tab, I see no temp basal but on the main page, I have 0U/h (this is NOT helping my neg IOB problem either...)

I try to cancel temp basal in Actions and it doesnt work either.

![Screenshot_20220407-155125_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/162424177-05175f69-638e-4838-b678-03aa256efacb.jpg)

![Screenshot_20220408-130310_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/162424428-84f9d826-e4f7-4708-939f-5ee43c0821ac.jpg)

![Screenshot_20220408-130240_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/162424468-654d7f3c-fb83-4939-baba-78bf1752858f.jpg)

![Screenshot_20220408-130407_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/162424527-6f4a5956-2035-490a-aa63-a0e164b8f874.jpg)

**Comment by robertrub** [comment]
And the logs around 13h03

![AndroidAPS_LOG_1649415857979.log.zip](https://github.com/nightscout/AndroidAPS/files/8451316/AndroidAPS_LOG_1649415857979.log.zip)

**Comment by robertrub** [comment]
Seems like a temp basal duration problem. It is aways 4800...

![Screenshot_20220408-185140_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/162487075-c095a14b-2a3c-40a2-9e5e-e0ec16d5c8b4.jpg)

**Comment by elgrupo123** [comment]
I saw the same error.

**Comment by robertrub** [comment]
Seems like activation of a new DASH "solved" the problem.

**Comment by robertrub** [comment]
The bug might be related to AAPS restarting. I phone battery died and when I restated it, the duration was for 4800 minutes...

![Screenshot_20220413-215353_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/163259940-c691aa08-29f1-40e9-a786-a0ec9d2a4af8.jpg)

Look at around 21:55

![AndroidAPS_LOG_1649879810224.log.zip](https://github.com/nightscout/AndroidAPS/files/8484318/AndroidAPS_LOG_1649879810224.log.zip)

**Comment by danst1peak** [comment]
I have just had the same behaviour, disabled loop as fighting a low.

Loop shows disabled but 0.0 temp basal set for 4800 mins and unable to cancel.

I didn't take a picture of the Dash tab, but that was showing no temp basal, same as Robert's picture.

![Screenshot_20220422-062838_AndroidAPS](https://user-images.githubusercontent.com/99126049/164617763-6b3486d4-a5ee-44f6-a49d-762cc79bfaba.jpg)
![Screenshot_20220422-063134_AndroidAPS](https://user-images.githubusercontent.com/99126049/164617766-f9147fdb-3528-4501-8682-16e582e344c8.jpg)
![Screenshot_20220422-073229_AndroidAPS](https://user-images.githubusercontent.com/99126049/164617771-5191f084-b069-4f6f-886f-a804a99f19de.jpg)

**Comment by danst1peak** [comment]
Logs:

[AndroidAPS.zip](https://github.com/nightscout/AndroidAPS/files/8537568/AndroidAPS.zip)

**Comment by danst1peak** [comment]
I also tried changing profile to see if it reset, it didn't reset, but it did apply a different temp basal at 06:17 - even though loop was disabled.

**Comment by MarkSum1** [comment]
Although changing profile doesn't always reset, if you repeat this a few times it does.

**Comment by robertrub** [comment]
![Screenshot_20220507-145600_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/167260855-891b68d0-a8a4-4151-9ffb-3bc0b059e50f.jpg)

Things seem to work but I have this 4800 min TBR which should not be there...

**Comment by avereha** [comment]
I belive this bug was fixed with https://github.com/nightscout/AndroidAPS/pull/1715
Did you still notice this issue in `dev`, after 10th of May?

**Comment by robertrub** [comment]
No, I have not but I don't even remember how it had triggered. You can close the issue. If it happens again, I'll open a new one ;)
