### ISSUE TITLE
Incorrect SMS bolus delivered. 3.0.0.1 dev-i

### ISSUE THREAD

**Issue by elgrupo123** [nightscout/AndroidAPS#1591]
Incorrect SMS bolus delivered (17.48 )
Instead of 4.0IE, 0.2IE was given.
The wrong IOB was also displayed on the NS client, it was correct on the master.

Pixel 4a/Omnipod Dash/Build 391a471b2

THX. Greetings. 

![Screenshot_20220408-220522_2](https://user-images.githubusercontent.com/92778761/162527098-d917897e-1fb5-4b15-aabd-a0633c00c0f5.png)
![Screenshot_20220408-223157](https://user-images.githubusercontent.com/92778761/162527137-fe90322b-20da-4871-bc1c-50231657de6c.png)
![signal-2022-04-08-223756_001](https://user-images.githubusercontent.com/92778761/162527158-25cd61fc-c4ee-49f9-8e01-71db8731980a.png)
[AndroidAPS_LOG_1649448664145.log.zip](https://github.com/nightscout/AndroidAPS/files/8455194/AndroidAPS_LOG_1649448664145.log.zip)

**Comment by MilosKozak** [comment]
wrong  info in NSClient can be resoled by using dev branch of NS
the wrong response was caused by clash with SMB. I'm not sure if this is resolvable

**Comment by elgrupo123** [comment]
The problem hasn't happened again.
Greetings.
