### ISSUE TITLE
Minor / Widget / Delay updating data

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1595]
Not very important but it takes about over 1 min for the widget to update the shown data...

![Screenshot_20220410-134902_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/162616869-c68c95c2-4662-4a92-bf62-7549d1989e9d.jpg)

![Screenshot_20220410-134924_One UI Home.jpg](https://user-images.githubusercontent.com/76626474/162616891-d27981df-2a21-4aa3-94cf-910516b9a349.jpg)

**Comment by MilosKozak** [comment]
widget is updated once per min to save battery
