### ISSUE TITLE
Minor / UI Graph : out of proportion graphics

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1596]
This problem was solved but reappeared. While the data is being read (or calculated, the new progress barre starts on the left), the graphics seem to have huge vertical "values".

![20220410_010847.jpg](https://user-images.githubusercontent.com/76626474/162617445-5789d2eb-3a00-440e-bc71-e13fdea3dff7.jpg)

**Comment by robertrub** [comment]
N.B I had just set a TT that had started the calculations.

**Comment by MilosKozak** [comment]
hopefully fixed by https://github.com/nightscout/AndroidAPS/commit/79ea2fff0cf04d2abbd405e5913fbf537c52adad
