### ISSUE TITLE
Buttons disappear and sometimes don't reappear - dev-i

### ISSUE THREAD

**Issue by JohnKitching** [nightscout/AndroidAPS#1598]
Carbs, calculator, insulin, treatments buttons. 
I'm guessing they've been set to hide at times to maximise screen space. When connecting to pump perhaps?
I had an issue today that pump battery died so my buttons never reappeared (I'm guessing it was waiting for a pump disconnect event?). 
This was quite a problem as I could have really used the calculator to tell me what I needed from my backup pen.

**Comment by Andries-Smit** [comment]
By design, the buttons are only available when you can use them.

**Comment by JohnKitching** [comment]
Don't think I've ever needed them more than I did today to calculate a manual dose.

**Comment by Andries-Smit** [comment]
Carbs and CGM buttons are available  when pump is offline.
Theoretical the insuline button can be used without the pump, as it is has a "do not bolus, record only" checkbox.
By removing the buttons it makes it realy clear to the users that there the regular therapy is not available.

**Comment by JohnKitching** [comment]
All the buttons were hidden for me today. 

If you don't want to show the buttons how about providing another way to access the functionality?

**Comment by Andries-Smit** [comment]
To understand why the buttons are hidden, we can look in the code https://github.com/nightscout/AndroidAPS/blob/dev/app/src/main/java/info/nightscout/androidaps/plugins/general/overview/OverviewFragment.kt#L533
- Profile should be selected
- If the pump stores carbs info, you can not enter carbs when it is not connected; some Dana pumps do support it

Making the calculator available when the pump is not available is a niche function, and have to discuss effort / vs value with the team.

**Comment by JohnKitching** [comment]
It's not a biggie to me. I rarely use the buttons. I was just reporting a problem. I thought that was the point of testing dev. Sorry.

**Comment by Andries-Smit** [comment]
@JohnKitching, no need for apologies; I am happy to help
