### ISSUE TITLE
MINOR/ Is yellow triangle useful for G6 transmitter change ?

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1603]
When we change G6 transmitters, the  minutes at which the BGs arrive change which triggers the yellow triangle... I'm not sure if this alert is useful. If there are more than 1 delay in BGs, the yellow triangle is a normal information. 

In this case, BGs arrive each 5 min except that the new transmitter starts at a different "minute".

![Screenshot_20220411-092710_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/162686931-00f60bfd-5081-4400-8209-9c1f216e78a8.jpg)

![Screenshot_20220411-092723_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/162686979-b1cbe777-8fe5-4e8e-ab52-a08ba2b6cec2.jpg)

**Comment by MilosKozak** [comment]
in this case data must be recalculated because APS rely on 5 min interval
thus yellow triange
