### ISSUE TITLE
SMS Communicator Not Sending Response in Dev i but still works in Master (tried on multiple phones)

### ISSUE THREAD

**Issue by cygrahampearson** [nightscout/AndroidAPS#1610]
SMS communicator is not sending a response (but will still implement commands). 

This problem first began when I switched from @tim2000s main dynamic ISF branch to his dev. I briefly switched back to master and it worked fine. I then switched to NS dev G, H and then I and its not working. I've tried on multiple phones (S9, Jelly 2, Atom and Not 10) and its not working on any of them. Master still works fine. 
--------------
- Time: 8:40pm I sent five different SMS commands
-AndroidAPS 3.0.0.1-dev-i
-BUILD: 671127673-2022.04.05-12:55
-logs and screenshots attached
[AndroidAPS_LOG_1649724181836.log.zip](https://github.com/nightscout/AndroidAPS/files/8468679/AndroidAPS_LOG_1649724181836.log.zip)

![Screenshot_20220411-204217_AndroidAPS](https://user-images.githubusercontent.com/73077567/162857620-15fce289-c84d-40a7-b156-d44b47836d6b.jpg)
![Screenshot_20220411-201853_Permission controller](https://user-images.githubusercontent.com/73077567/162857624-053ddfee-9cdf-416c-ae21-bf1c0fd949d4.jpg)
![Screenshot_20220411-201440_Settings](https://user-images.githubusercontent.com/73077567/162857627-0445ef86-8f5e-423d-9c82-724a31c33ec0.jpg)
![Screenshot_20220411-205048_Messages](https://user-images.githubusercontent.com/73077567/162857633-b3d8e5ac-0819-4aaa-8874-523aab6e3bba.jpg)

Please let me know if there is anything I can do to help get you some useful data. 

Thank you, 

Coleby

**Comment by MilosKozak** [comment]
problem is on master. AAPS cannot send SMS even we see it's trying it

**Comment by MilosKozak** [comment]
what do you see in AAPS permissions in android setting?

**Comment by cygrahampearson** [comment]
@MilosKozak  Would it be helpful to send a video showing SMS commands sending texts in Master and then switching to dev ? I can show the settings and permissions and switch back to master to show. 

I've attached pictures of permissions, please let me know if you see anythin
![Screenshot_20220413-190022_Permission controller](https://user-images.githubusercontent.com/73077567/163292821-f234d4e3-fa58-4a12-933c-3f6ec9b3ea64.jpg)
![Screenshot_20220413-190014_Permission controller](https://user-images.githubusercontent.com/73077567/163292822-045eb870-bab8-420a-a98e-0164eec3d66b.jpg)
![Screenshot_20220413-190029_Permission controller](https://user-images.githubusercontent.com/73077567/163292824-461b8c71-630d-4041-9e99-6f14382e4860.jpg)
![Screenshot_20220413-190036_Permission controller](https://user-images.githubusercontent.com/73077567/163292825-dd94edb3-345e-4195-9ac3-bb5be4e72b9c.jpg)
![Screenshot_20220413-190036_Permission controller (1)](https://user-images.githubusercontent.com/73077567/163292826-944abf66-2b92-4498-a336-a6d6ac6420a2.jpg)
![Screenshot_20220413-185939_Permission controller](https://user-images.githubusercontent.com/73077567/163292827-02c19d7d-8110-4ee7-8cf5-e4c9ed85b252.jpg)
g

**Comment by MilosKozak** [comment]
there is no change in SMS code between master and dev-i except some text formating

**Comment by MilosKozak** [comment]
try it on another phone

**Comment by jumalakarhu** [comment]
I can confirm the same with Sony xperia xz1 compact.  sms command in dev is not functional. Sms is read in aaps and respons issued  (seen in sms log in aaps), but sms is not actually sent from phone. Works fine when going back to master. Could it be something about permissions not properly inherited/handled (?) in dev from master? Would be worth testing with a fresh install of dev, but I do not have a spare android 9+ at the moment.

**Comment by cygrahampearson** [comment]
@MilosKozak I've tried on Samsung note 10, Jelly 2, Atom and S9 all with no luck. They all work fine with Master. 

I'll take a video performing SMS commands and then switching from dev to master to new dev to show how its working/ not working and will pull some more logs. 

Is it helpful for me to adjust the log settings to add or remove certain categories?

It looks like @jumalakarhu can confirm what I am seeing as well.

**Comment by cygrahampearson** [comment]
@MilosKozak Here's a video of me attempting and failing to respond to SMS commands in dev-i and then installing master to show them working and then to dev h. 

https://drive.google.com/file/d/121tXlCh4dX9zuVP6RbcVSVzWT621wZWz/view?usp=sharing

Im updating now to latest dev to see if there are any changes

**Comment by rosseland** [comment]
Same issue here, dev-i, Huawei p20pro, android10

**Comment by shafiro** [comment]
Had the same problem with Galaxy S21+. After upgrading to Android 12, SMS functionality is back to normal.

**Comment by MilosKozak** [comment]
resolved by https://github.com/nightscout/AndroidAPS/commit/6f358bc0c80b902b0abbf6b0dbd77a88b035ee24

**Comment by cygrahampearson** [comment]
Thank you!
