### ISSUE TITLE
Active Pod Button after Eros Pod Change

### ISSUE THREAD

**Issue by Thomas-Wolff** [nightscout/AndroidAPS#1614]
When changing the Eros Pod, the error occurred again in the active 'Activate Pod' and 'Deactivate Pod' buttons.

Unfortunately, I also noticed another error during this change. In the last section after the catheter was shot, the 'Continue' button was briefly active and then immediately jumped to inactive. Unfortunately, after that I could only continue via Cancel. Unfortunately, I could not take a screenshot.
AAPS communicates cleanly with the Pod and Loop runs.

![Bild1](https://user-images.githubusercontent.com/59526802/163235226-e6d09284-ea2c-4209-a4bc-28cc7914f8db.jpg)

[AndroidAPS._2022-04-13_12-07-41_.15.zip](https://github.com/nightscout/AndroidAPS/files/8483461/AndroidAPS._2022-04-13_12-07-41_.15.zip)

Pod set at 13.04.2022 17:26 hrs

Performed with
AAPS 3.0.0.1-dev-i
build: 2a087c8d8

Greetings Thomas

**Comment by samspycher** [comment]
@Thomas-Wolff is this issue still occurring on later builds (after April 19)? According to the issue referenced by @robertrub above, it was resolved for Dash, perhaps also for Eros.

**Comment by Thomas-Wolff** [comment]
I'm currently running Dynamic ISF on the dev-k build on the eros, and it's fixed there.

Greetings Thomas
