### ISSUE TITLE
OLD BUG : Activate/Deactivate pod buttons are lit

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1621]
This bug was solved but is back once more. **Both** pod _activate_ and _deactivate_ buttons are turned ON (lit, not grayed) all the time (when pod is activated and when no pod is activated).

![Screenshot_20220414-114908_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/163449834-3cff993a-b65a-4b7a-8a8a-51f96bafd7e1.jpg)

![Screenshot_20220414-194704_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/163449853-6dd8642c-c736-4f13-904c-dceadb245b99.jpg)

**Comment by robertrub** [comment]
Seems similar to #1614 but mine was with DASH.

**Comment by Andries-Smit** [comment]
@robertrub I quickly checked. Previously it was caused by the styling changes. The last build seems fine on my test phone but does not have any active pods.

**Comment by robertrub** [comment]
I have both lit with active and no active pods.

**Comment by CaptainBalou** [comment]
Here I've got the buttons correct. During the pod was on and after it was deactivated. No trouble.

I don't know how to add a screenshot on my phone but I would have one I could add later if needed.

**Comment by CaptainBalou** [comment]
I'm also on dev-i at the moment but built 7 days earlier.

**Comment by robertrub** [comment]
A week ago, it was working ;)

**Comment by Thomas-Wolff** [comment]
I can also confirm this, I have already opened a new issue #1614 two days ago.
Greetings Thomas

**Comment by elgrupo123** [comment]
I can also confirm the error in the last build (1ba67d9f7).
In build before (391a471b2) everything is OK.

**Comment by CaptainBalou** [comment]
@robertrub 
> A week ago, it was working ;)

After I fixed a build issue in Android Studio I was able to build the app again. After using this build 4398a433c-2022.04.18-23:21 I can confirm that the buttons are both active here as well.

**Comment by osodebailar** [comment]
> @robertrub
> 
> > A week ago, it was working ;)
> 
> After I fixed a build issue in Android Studio I was able to build the app again. After using this build [4398a43](https://github.com/nightscout/AndroidAPS/commit/4398a433c3fbf257597abe2a52c734088def94ed)-2022.04.18-23:21 I can confirm that the buttons are both active here as well.

Please try it again with new version of dev. In simulation it seems to work

**Comment by elgrupo123** [comment]
@osodebailar 
The latest (49af54) works again. Unfortunately, the graphic below is much too high and the font is too small
![Screenshot_20220419-130808](https://user-images.githubusercontent.com/92778761/163991059-b7d125bb-be14-4947-9373-9e05e8157764.png)
.

**Comment by robertrub** [comment]
Sorry, on vacation till next tuesday with no PC. Will test in a week.

**Comment by CaptainBalou** [comment]
@osodebailar 
> Please try it again with new version of dev. In simulation it seems to work

For me all looks good again. My pod is online and button to activate is off, button do deactivate is on. Perfect.

**Comment by robertrub** [comment]
Solved :)
