### ISSUE TITLE
[Dev-i] Combo serial number detected as MAC address

### ISSUE THREAD

**Issue by parapenT1sta** [nightscout/AndroidAPS#1628]
The new value "Serial Number" shown in Combo information tab is wrong. Is displaying my Combo MAC Address. 

Is it suppose to be the MAC address or serial number?

![Screenshot_20220417-094825](https://user-images.githubusercontent.com/608650/163707589-817afcfa-2d65-485f-b697-da05dd2144f6.png)

**Comment by MilosKozak** [comment]
it's not possible to read SN from combo. This string is used internaly instead for password recovery
