### ISSUE TITLE
Feature Request : Make Nightscout NS optional and skip NS in objective 1

### ISSUE THREAD

**Issue by yrioux** [nightscout/AndroidAPS#1635]
During wizard add and option to make NS optional.
If NS is select has disable, skip all NS items during objective 1.

**Comment by MilosKozak** [comment]
NS is currently mandatory because AAPS doesn't provide reporting tool itself

**Comment by cyrusbyte** [comment]
Please make this optional especially if you use Dexcom BYODA it is not necessary for reporting. Also this assumes that reporting is mandatory.
Thanks

**Comment by MilosKozak** [comment]
it can be replaced by tidepool in dev

**Comment by cyrusbyte** [comment]
Dexcom already uploads data to Clarity which almost every hospital already has so no need for either.
