### ISSUE TITLE
Picker's colors doesn't match the rest of app

### ISSUE THREAD

**Issue by MilosKozak** [nightscout/AndroidAPS#1636]
![image](https://user-images.githubusercontent.com/11146458/163958472-c1beae07-0dcb-4ca0-a41e-d5a8acd8a811.png)
![image](https://user-images.githubusercontent.com/11146458/163958547-c9a3ebf2-04f3-4f3a-8978-0558dff17e33.png)

**Comment by osodebailar** [comment]
@MilosKozak  : For the Ok/cancel button color i made a PR.
But if we want to change the selected item background color as far as i know the color in the header would change also.
Its always the dark/light primary color.
Primary color in dark theme is lighter than in day theme and follows the google standard. 
@Andries-Smit what did you say ?

The PR: for ok Cancel color:
https://github.com/nightscout/AndroidAPS/pull/1644

**Comment by Andries-Smit** [comment]
The reason for me to keep the color  to the default to the Material Theme, was to start a discussion on what it really should be, default or custom.
Though when searching for the source of all other dialog buttons, I did find another rabbit hole of dialog fragments.

**Comment by osodebailar** [comment]
For me , personally I like it with the default Color .
The ok/cancel button is fixed now . And for me the rest could be as it is.
With the foresight to md3 , where more Color’s where he’s used and the primary Color will be used to tint the background of dialogs , it will fit perfect as it is now .
