### ISSUE TITLE
Coloring

### ISSUE THREAD

**Issue by MilosKozak** [nightscout/AndroidAPS#1639]
![image](https://user-images.githubusercontent.com/11146458/163984869-e2303bae-1670-4cd7-a13c-21b3d69c29d2.png)
Here would look better to have lighter whole cardview instead of textviews and small dark border

**Comment by osodebailar** [comment]
@MilosKozak : Where i can find the Textview ?

**Comment by MilosKozak** [comment]
Overview in NSClient mode

**Comment by osodebailar** [comment]
I will have a look later

**Comment by osodebailar** [comment]
https://github.com/nightscout/AndroidAPS/pull/1651
