### ISSUE TITLE
The last layout changes are inconvenient for small devices

### ISSUE THREAD

**Issue by swissalpine** [nightscout/AndroidAPS#1648]
Yes, I use a smartphone with a small screen, but I think I'm not the only one. From there, you should be careful with layout changes that take up space and don't add functionality. That's what the changes Material Card View and Material Button do.
Maybe it is possible to change the margin-top for small devices to 0 dp in the Material Card View (I changed it from 4 dp to 1 dp so I can see the graph again), how to adjust the material buttons is beyond me. Please revert this changes!
New Matieralbuttons:
![Screenshot_20220419-154927](https://user-images.githubusercontent.com/12517693/164031188-c50ebcf9-469a-48b7-bbb6-cd2d614e1fa2.png)
![Screenshot_20220419-154943](https://user-images.githubusercontent.com/12517693/164031505-8349053c-3e7a-429e-a2f6-42ff732cbdf8.png)

----

Old buttons:
![Screenshot_20220419-155236](https://user-images.githubusercontent.com/12517693/164031404-4b7ac49d-bfc6-41b0-8a39-609f76489d3c.png)
![Screenshot_20220419-155134](https://user-images.githubusercontent.com/12517693/164031625-bfba30f6-a129-41e7-aa61-599d1034c507.png)

Please undo at least the material button commit!
And have an eye on the impact on small Screens as well for future layout changes (btw I liked the old layout!). Thanks!

**Comment by osodebailar** [comment]
@swissalpine  We can change the style to smaller text , so it fits again .

**Comment by Andries-Smit** [comment]
There are 2 types of users, users with a personal phone running AAPS, do have, in general, a large screen.
And users with a designated device, which is quite often as small as possible.

To cater for both, we can easily distinguish using qualified resources. and then we can tweak for smaller screens, for example, setting some padding/margins/corner radius to 0.

https://developer.android.com/guide/topics/large-screens/support-different-screen-sizes

**Comment by Philoul** [comment]
Even if it's not a small device, I think marging in material button should be reduced (close than half of the width is lost...)
![Screenshot_20220420-075324_AndroidAPS.jpg](https://user-images.githubusercontent.com/52934600/164160640-cef909c7-a814-4c76-a099-fd68f6438f20.jpg)

**Comment by osodebailar** [comment]
> Even if it's not a small device, I think marging in material button should be reduced (close than half of the width is lost in overview) ![Screenshot_20220420-075324_AndroidAPS.jpg](https://user-images.githubusercontent.com/52934600/164160640-cef909c7-a814-4c76-a099-fd68f6438f20.jpg)

Changed the former workaround margin:
https://github.com/nightscout/AndroidAPS/pull/1652

**Comment by swissalpine** [comment]
Thanks for the effort and finding solutions!
