### ISSUE TITLE
[2.7.1-dev] [cosmetic-issue] AAPS show carbs in change request in extrem precision

### ISSUE THREAD

**Issue by rICTx-T1D** [nightscout/AndroidAPS#165]
![20210101_230019](https://user-images.githubusercontent.com/8592414/103447220-6c3afb00-4c88-11eb-8515-1a032492deea.jpg)

AAPS show carbs in change request in extrem precision.

**Comment by DM-LTR** [comment]
This is not a real issue, rather inconsistency in rounding nubmbers...

**Comment by rICTx-T1D** [comment]
It is an cosmetic issue, not a really bug.

**Comment by DM-LTR** [comment]
This cosmetic issue disappears once you close the loop.

**Comment by rICTx-T1D** [comment]
It is possible, but not all users use every time closed loop. Maybe the pump is not supported, the objectives are not complete or other reasons...
