### ISSUE TITLE
[2.7.3-dev] Inconsistency between TT-menu and Loop-menu concerning security

### ISSUE THREAD

**Issue by ArthurusDent** [nightscout/AndroidAPS#166]
I have enabled the biometric bolus and settings protection. If I want to set a temporary target, I have to provide my fingerprint but if I want to disable the loop, no fingerprint is required. I think that's inconsistent and the loop menu should also be protected.

System:
AndroidAPS 2.7.3-dev 1c8ed7b1a
Medtronic 554
Dexcom G6
xDrip+
Oneplus 3T
Lineage 17.1

**Comment by MilosKozak** [comment]
agree, added by https://github.com/nightscout/AndroidAPS/commit/eb84f5e6a7bba7f1ac52d57df9b2cfdf83c64b6c
