### ISSUE TITLE
Error SMB requests are not performed by the Accu-Chek Combo 

### ISSUE THREAD

**Issue by joaotipo1** [nightscout/AndroidAPS#1675]
The problem happens with SMBOpenAPS and also with AIME. The algorithm requests SMB without any restrictions but the pump does not run.

I already changed the pump and also the cell phone, but the problem persists. In the attached file the logs show that 9:49 am an SMB was requested.

--------------
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/8555373/AndroidAPS.log)
![WhatsApp Image 2022-04-25 at 09 54 03](https://user-images.githubusercontent.com/67444195/165109801-6d4f1695-2595-4075-ac64-fd9a4f9cd366.jpeg)
![WhatsApp Image 2022-04-25 at 11 07 11](https://user-images.githubusercontent.com/67444195/165109805-81884068-e736-4b49-9876-179b52fb1642.jpeg)

**Comment by MilosKozak** [comment]
sorry, here is supported only master and latest dev version of main repo
test one of these and create new issue
I added more logging
