### ISSUE TITLE
Features : Split bolus over time 

### ISSUE THREAD

**Issue by yrioux** [nightscout/AndroidAPS#1683]
It would be great if we can split bolus over time. 

Usecase :
- In bolus wizard enter the amount of cards. 
- click on "split bolus".
- open new pop-up 
- select duration, split over x minutes 
- bolus from wizard is displayed. Click on it to split it in 2 parts. We could see percentage of each part. 
- can click on other parts to split again. 

This can be useful if you eat pizza and want to receive insulin in future. 

I also feel pain when bolusing more than 5 units, if I can split all my meals bolus over 30 minutes, it will be more confortable and convenient.

**Comment by sebampuero** [comment]
If you would want to receive additional insuline as bolus or tbr in future for slow carbs or high fat content you would use eCarbs

**Comment by yrioux** [comment]
But eCarbs only schedule carbs. I cannot schedule bolus...

I must to think to enter bolus later.

**Comment by MilosKozak** [comment]
SMB is designed to do this automaticaly
Do a smaller bolus with food and let SMB do the rest 
Use ecarbs for for high fat foods

**Comment by MilosKozak** [comment]
you can set % of given upfront bolus in preferences

**Comment by nicoleloop** [comment]
I think that yrioux simply wanted the option to give an extended bolus that was unrelated to carb entries.

**Comment by MilosKozak** [comment]
extended bolus goes directly against SMB alg. thus is not possible to use it
