### ISSUE TITLE
Urgency: Crash AAPS after update samsung One UI 4.1

### ISSUE THREAD

**Issue by vincent1890** [nightscout/AndroidAPS#1689]
Good evening,
Following an update from samsung I can no longer use aaps I really need help urgently please

Reporting bugs
--------------
- 03/05/2022 a 20h01 Crash AAPS after update samsung One UI 4.1 (Android 12)
- 3.0.0.1 and version 3.0.0.2
- logs in attachments
[AndroidAPS._2022-05-03_01-20-12_.0.zip](https://github.com/nightscout/AndroidAPS/files/8613077/AndroidAPS._2022-05-03_01-20-12_.0.zip)
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/8613080/AndroidAPS.log)

**Comment by vincent1890** [comment]
Excuse me all it’s been two hours that I was on it in the end after removing the cache and stopping force of the app I had the time a few seconds press the next button which allowed to unlock the situation and not crash the application anymore
Thank help @Robby in discord and WhatsApp

https://user-images.githubusercontent.com/5764518/166552998-808dde5a-0bac-4488-9d97-e22768ce59f9.mp4

![Capture d’écran 2022-05-03 212640](https://user-images.githubusercontent.com/5764518/166553032-be607f56-3568-4e9c-b802-8c9b3dbb6ea8.png)

**Comment by vincent1890** [comment]
The video mounts the crash that was happening I don’t know if in the app there is a way to launch the app opened longer or have a bigger alert message about the permissions?

**Comment by mick711** [comment]
Try to delete all files and folder on your phone, backup some files liké parameters. Delete database and uninstall aaps. Reboot thé phone install AAPS and set your parameters not with a backup.

**Comment by MilosKozak** [comment]
resolved?

**Comment by MilosKozak** [comment]
closed by inactivity
