### ISSUE TITLE
Since Update to Dev-i (Build: 93af3d748). Pump Connection Errors

### ISSUE THREAD

**Issue by Alamo04** [nightscout/AndroidAPS#1693]
System:
- Dana RS pump
- Pixel 5 phone
- AAPS Dev-i (error comes with the update yesterday)

Using also dev-i a while, but since my update to dev-i (Build: 93af3d748) yesterday evening, I had 3 times "No connection to pump". It seems that this message has nothing to do with the reality, because the pump was connected.

Logs attached.

[AndroidAPS_LOG_1651693367390.log.zip](https://github.com/nightscout/AndroidAPS/files/8626734/AndroidAPS_LOG_1651693367390.log.zip)

**Comment by MilosKozak** [comment]
in logs everything looks normal, pump is connected withing a few seconds

**Comment by Alamo04** [comment]
Last connection problem was yesterday 23:25.

So I think the problem was gone, perhaps with a new update and restart phone.
