### ISSUE TITLE
Wear App stops connecting/synchronizing after installing 3.0.0.2-dev-j  Commit#3d9b08e5 (compatibility break?)

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#1698]
**AndroidAPS 3.0.0.2-dev-j**
**Build:** #3d9b08e5
**Flavor**: Fullrelease

**Watch**: Samsung Galaxy Watch4 44mm
_Wear App_: 2022.02.14 (Release version)
Build: #B1D45833C

**Problem description:**
With installing this build the Android Wear app stopped synchronizing.
APPS was updated at about 18:30h

App seems to not be connected,
Wear->RESEND DATA and Wear->OPEN SETTINGS ON WEAR have no effect.

![Screenshot_20220505_213846_sysui](https://user-images.githubusercontent.com/45144129/167013609-3bccada6-f04f-4f81-a54b-22185c57bdac.png)

![Screenshot_20220505_214022_androidaps](https://user-images.githubusercontent.com/45144129/167013629-3b1e9bc5-eeee-4857-859c-ecc4bc61bd29.png)

** Log files **
[AndroidAPS_LOG_1651779641963.log.zip](https://github.com/nightscout/AndroidAPS/files/8635517/AndroidAPS_LOG_1651779641963.log.zip)

**Comment by reijoahola-nightscout** [comment]
You have to update also Wear.

**Comment by vanelsberg** [comment]
Expecting dev being compatible with release version. 
Apparently, it is not?

**Comment by reijoahola-nightscout** [comment]
Not compatible in this case. There is some big reorganosation inside Wear dev-j.

**Comment by reijoahola-nightscout** [comment]
I have both AAPS and Wear updated into dev-j but there seems to be mysterious problems what I do not understand. Could you update your systen and comment is it working without problems.

**Comment by MilosKozak** [comment]
i see crashes comming from OnePlus Nord2 5G
caused by too old Wear OS

**Comment by vanelsberg** [comment]
Current dev version

**Comment by vanelsberg** [comment]
Upgraded Wear App to current dev. Yes, it is now showing syncing/BG.

Unfortunately for this version:
* Tiles are no longer functioning
* Watch faces layouts have "problems" (especially my favorite: "DigitalStyle")
* Watch settings (doubble screen-tap, settings) crashes when scrolling down)

So seems to be a work in progress...

**Comment by vanelsberg** [comment]
> caused by too old Wear OS

Well, In my case an almost brand new Samsung Galaxy Watch4. Was working perfectly with tiles and all control functions.
Came sort of as a surprise as I expected release version of the Wear app to stay compatible.

**Comment by MilosKozak** [comment]
tiles fixed, the rest is working well for me

**Comment by MilosKozak** [comment]
![image](https://user-images.githubusercontent.com/11146458/167029043-cdfdc480-e6e0-4817-979b-2ec4159aad04.png)

**Comment by vanelsberg** [comment]
> tiles fixed, the rest is working well for me

Ah, that's great!
Will test tomorrow and let you know my findings

**Comment by vanelsberg** [comment]
On UI: using same watchface. 

- I can display date, including day name (as in THU, 5 MAY, 23:52)
It shows "52" (should be day name) and "52 MAY" (date)". Day name and date show "minutes?"

- Always on is also affected.

**Comment by reijoahola-nightscout** [comment]
> On UI: I am using same watchface. Looks like UI is getting somewhat better now (layout may have been affected by database reset) But is still off on some parts.
> 
> * I can display date, including day name (as in THU, 5 MAY, 23:52) and week number
>   It shows "52" (should be day name) and "52 MAY" (date)". Day name and date show "minutes?"
> * Arrow on BG complication is not showing (something seems to be there)
> * BG complication shows "5." and then below something that looks like part of "3"
> * Not seeing basal & predeiction lines on graph
> 
> ![Screenshot_20220505_235635_sysui](https://user-images.githubusercontent.com/45144129/167032674-e0b30ce2-8441-4d05-b988-4b1cbeafa6d6.png)
> 
> * Always on is also affected.
> 
> ![20220505_235925](https://user-images.githubusercontent.com/45144129/167032586-bbd7684b-d39b-48c3-a9a5-af87314957fe.jpg)
> 
> ** This is how release version looked **:
> 
> ![original](https://user-images.githubusercontent.com/45144129/167033204-d4fe7fdc-2026-4b34-a24e-c540891eb376.jpg)

I have the same problems with the watchfaces. My watch is TicWatch Pro (from 2018) and the Wear OS should be the latest that the watch can update.

**Comment by vanelsberg** [comment]
> > tiles fixed, the rest is working well for me
> Ah, that's great! Will test tomorrow and let you know my findings

Tried (current) dev build: On install AAPS started cycled crashes on startup.
So needed reverted back to previous build 3d9b08e5c2.

**Comment by TT83TT** [comment]
for me, missing trend arrow and duplicate BG, OnePlus 8t phone and Galaxy Wear 4 watc
![IMAGE 2022-05-07 08:23:19](https://user-images.githubusercontent.com/28483752/167241702-5d005ca6-8665-40e9-8a86-fe14e0b51998.jpg)
![IMAGE 2022-05-07 08:23:35](https://user-images.githubusercontent.com/28483752/167241719-043c56f7-94b0-49f1-95b2-4c3636101462.jpg)
![IMAGE 2022-05-07 08:23:45](https://user-images.githubusercontent.com/28483752/167241725-250e3336-0300-459e-b192-5a7b9b3b8d82.jpg)
h

**Comment by TT83TT** [comment]
New last commit 96f095ce8, still the same, missing arrow and double BG

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/e01647d496e405d3ae9617ae76f353147181ec02

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/b437307157420a8abcdf46bee5981ecae739df71
if there is still somthing else, open new issue

**Comment by vanelsberg** [comment]
> [e01647d](https://github.com/nightscout/AndroidAPS/commit/e01647d496e405d3ae9617ae76f353147181ec02)

Yes, Looks ok now.
Thank for quick fixing: Much appreciated!
