### ISSUE TITLE
Feature request : Automation / change profile % <70%

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1700]
It would be very helpful to have the automations be able to change profile percentage to less than 70%.

When I exercise, I can set profile manually to 50%. If I set an automation for that, the lowest I can go is 70% which is not enough.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/4e440550143f05271a489f16359532d5f82a9058
