### ISSUE TITLE
Filter prediction lines

### ISSUE THREAD

**Issue by sarahkovac** [nightscout/AndroidAPS#1708]
I'd like to be able to choose which prediction lines show by default. Maybe the other prediction lines could be viewed in the graphs below or just selected in settings. I have been using this for months and still can't keep straight which line is which, and really there are only one or two that I need to see regularly. This would be much easier for beginners. Thanks!

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/EN/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by yrioux** [comment]
For example, in xDrip, the prediction line is the combination of COB and IOB. It's also easier and faster to understand the graph with single prediction.

See line in purple 
![Screenshot_2022-05-07-23-43-52-76_2dd2c1bcb8f659cd696bcba2072f751b](https://user-images.githubusercontent.com/102491323/167280911-5f060417-fe43-4a51-9fcb-c5ccbfc728cd.jpg)

**Comment by sarahkovac** [comment]
Exactly. The Loop app on iPhone does a great job of this. I think AAPS is definitely smarter, but making the AAPS UI a little more user-friendly would go a long way. Having the predicted eventual glucose number would be super helpful as well.
![image](https://user-images.githubusercontent.com/1032903/167301937-a40eaee7-8261-457d-aec1-83af6a20b768.png)



> For example, in xDrip, the prediction line is the combination of COB and IOB. It's also easier and faster to understand the graph with single prediction.
> 
> See line in purple ![Screenshot_2022-05-07-23-43-52-76_2dd2c1bcb8f659cd696bcba2072f751b](https://user-images.githubusercontent.com/102491323/167280911-5f060417-fe43-4a51-9fcb-c5ccbfc728cd.jpg)

**Comment by MilosKozak** [comment]
AAPS is different to loop
all prediction lines are used for decision thus keeping only one would not help to anything
