### ISSUE TITLE
Main screen (BG) is not updated

### ISSUE THREAD

**Issue by zwackelfuss** [nightscout/AndroidAPS#1712]
Since 3.0.01 I encounter the following problem:
- a new bg value (98) arrives at 7:49 (source: xDrip broadcast); previous bg is 86 (7:44)
![tab-xdrip](https://user-images.githubusercontent.com/46249367/167387263-e1415cef-dcc7-450f-b74d-2cca9c3ef275.png)

- AAPS uses and displayes new bg of 98 in all tabs, for ex. bolus calculator or  SMB log tab.
![tab_smb](https://user-images.githubusercontent.com/46249367/167387662-117e7c84-d522-40f6-8a3f-2935806270de.png)

- but the main screen is not updated and sticks showing the previous value ("last.. 9min ago" - correct would be "4min ago"). The outdated BG gets strikedout after 8-9mins:
![mainscreen](https://user-images.githubusercontent.com/46249367/167387179-9e724c4f-ea51-4419-ab7f-f47606c30cdd.png)

See screenshot: it is 7:53 and still old BG of 86 is displayed, although new BG of 98 is available since 7:49

- if next bg arrives, things are updated and ok again
- problem exists both with AAPS and NSClient
- problem does NOT occur on older AAPS/NSClient versions

**Comment by MilosKozak** [comment]
this is hopefully already fixed in dev
