### ISSUE TITLE
Wear app: Double-tab settings crash when scrolling down to end

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#1713]
**AndroidAPS 3.0.0.2-dev-j**
**Build:** #7ef313e4aa
**Flavor**: Fullrelease

Watch: Samsung Galaxy Watch4 44mm
**Wear App:** from AAPS 3.0.0.2-dev-j, build#7ef313e4aa
Build: #??????

**Problem description:** 

Watch face menu cashes on settings

_Repro_:

1. Double-tab on watch face for settings menu
2. Select "Settings"
3. Scroll down

When scrolling down beyond "Show Loop Status" the config page crashes back to the watch face.

**Comment by MilosKozak** [comment]
uninstall wear app and install again

**Comment by vanelsberg** [comment]
Ah... Missed that!
Tnx.

**Comment by vanelsberg** [comment]
Had to uninstall/reinstall twice, but know it stopped crashing.

**Comment by vanelsberg** [comment]
Menu started crashing again, now even worse disabling the entire watch face.
Reopening issue as https://github.com/nightscout/AndroidAPS/issues/1728
