### ISSUE TITLE
Wear app: BG arrow not visible on Watch Face AAPS(DigitalStyle)

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#1714]
**AndroidAPS 3.0.0.2-dev-j**
**Build:** #7ef313e4aa
**Flavor**: Fullrelease

Watch: Samsung Galaxy Watch4 44mm
**Wear App:** from AAPS 3.0.0.2-dev-j, build#7ef313e4aa
Build: #??????

**Problem description:** 

BG complication does not show direction arrow
Original WatchFace view (3.0.0.1 release):

![xxxx](https://user-images.githubusercontent.com/45144129/167487114-efa3a716-6b7c-4d90-aa82-e0ebae39fc7d.png)

**Comment by MilosKozak** [comment]
what's there?
btw do you know how to add watchface supporting complications to Huawei Watch 2?

**Comment by reijoahola-nightscout** [comment]
I have the latest version #58205e794. It shows BG arrow just like in that attached picture.
My watch is TicWatch Pro.

**Comment by vanelsberg** [comment]
Will check latest build/version,

> btw do you know how to add watchface supporting complications to Huawei Watch 2?
Have aprox 0.1% experience with complications, do not have the Huawei Watch,
Would like to know, but - nope - sorry ;-)

**Comment by vanelsberg** [comment]
@MilosKozak Fixed for mee.
Feel free to close..
