### ISSUE TITLE
Wear app: Watch face settings menu (double-tab, settings) crashes Watch face when scrolling to the end. 

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#1728]
**AndroidAPS 3.0.0.2-dev-j**
**Build:** #b4373071
**Flavor:** Fullrelease

**Watch:** Samsung Galaxy Watch4 44mm
**Wear App:** 2022.05.08

**Problem description:**

Watch face settings menu (double-tab, settings) crashes when scrolling down to the end. After this sometime the watchface switches to "black" and can only be restored by restarting the watch.

**Additional note:**

After fully uninstalling and then reinstalling the wear app the problem temporary solves, showing the settings menu correctly.
But then after some time (event?) problem reappears.

See also https://github.com/nightscout/AndroidAPS/issues/1713

**Comment by reijoahola-nightscout** [comment]
I believe that this is fixed in the latest dev version (3.0.0.2-dev-k 2022.05.12).

**Comment by vanelsberg** [comment]
No crashing in the past 24 hrs. Yes, seems to be fixed on latest build: can not reproduce the problem.

@MilosKozak Feel free to close this issue. Will re-open when necessary...

**Comment by jgslade** [comment]
I am experiencing this problem, I was trying to scroll down to try the workaround for the 0% issue on the calculator, but it crashes before I can get to the setting.

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/be199719bd92ac85a6d32587a839f3f728591f20
you need to uninstall/install if you are affected by this bug

**Comment by vanelsberg** [comment]
Confirming, fixed!
