### ISSUE TITLE
Widget: minor arrow color bug

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1732]
The sensitivity arrows are invisible. As well as the basal "icon"

![Screenshot_20220514-074445_One UI Home.jpg](https://user-images.githubusercontent.com/76626474/168413842-fd89b36f-2eaf-4d5e-b6a3-3e761a6324d9.jpg)

**Comment by osodebailar** [comment]
What you see is very dependent on how you set your background and the opacity of the widget .
With increasing the opacity you will see the arrow for example . With a lighter background you have the same effect

**Comment by robertrub** [comment]
Before a recent update, those were visible with my transparent background.

**Comment by robertrub** [comment]
Setting the background to opaque doesn't solve the problem either.

![Screenshot_20220514-095301_One UI Home.jpg](https://user-images.githubusercontent.com/76626474/168416574-55ff1056-8436-49f7-b894-20f7dc9c7132.jpg)

**Comment by swissalpine** [comment]
I can confirm this issue. Opacitiy makes no difference.

**Comment by osodebailar** [comment]
I will have a look on it in the next days
