### ISSUE TITLE
Objective 5 doesn't start

### ISSUE THREAD

**Issue by mushroom-dev** [nightscout/AndroidAPS#1736]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
I completed objectives 1-4 and verified them, but objective 5 didn't event start.  This situation lasts since about 7 days.

- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
I found this issue in version 3.0.0.1. I tried to reinstall it few times, it didn't help. Today I upgraded to 3.0.0.2 (build 219bdba21-2022.05.15-10:19) and imported my settings, issue still persist.

- Obtain the app's log files, which can be found on the phone in
I've just installed 3.0.0.2 so my logs are empty ...

I've made all kind of stuff that was probably supposed to be done at this stage. I changed all the profile settings, used temp targets, went through all the `treatment safety` and `OpenAPS SMB` settings, especially I've set `Max U/h temp basal can set to` setting which I believe objective 5 is about.

**Comment by MilosKozak** [comment]
can you provide screenshots?

**Comment by mushroom-dev** [comment]
![Screenshot_20220516-112343_AndroidAPS](https://user-images.githubusercontent.com/9194546/168562441-6f30a60c-f0b3-48d7-a493-9a8807a1f199.jpg)

**Comment by MilosKozak** [comment]
and screenshot of 1-3?

**Comment by mushroom-dev** [comment]
![Screenshot_20220516-201446_AndroidAPS_081544](https://user-images.githubusercontent.com/9194546/168662897-c7bb5e60-43d0-41ad-b360-0ac956085d49.jpg)
![Screenshot_20220516-201454_AndroidAPS_081547](https://user-images.githubusercontent.com/9194546/168662907-efc1f3e9-9fd0-49ee-af11-236cbfcb72ae.jpg)
![Screenshot_20220516-201504_AndroidAPS_081549](https://user-images.githubusercontent.com/9194546/168662912-01eb3795-3d15-4842-9cf0-c63ed46b603e.jpg)

**Comment by Der-Schubi** [comment]
You have to verify them ^^

**Comment by mushroom-dev** [comment]
Well .... it worked. I am pretty sure I clicked verify button before whatever it does. Anyway thank you
