### ISSUE TITLE
Insulin Suspended when changing countries and changing mobile networks (roaming)

### ISSUE THREAD

**Issue by bchris21** [nightscout/AndroidAPS#1739]
**AAPS Version:** v3 Dev-k
**Phone:** Xiaomi Mi-6
**Android Version:** 9

**Issue Description:**  
I am living in the borders of two countries and have to frequently commute between them with a car. 

When passing the borders mobile network automatically changes. No timezone change.  

A few minutes later:  

1. **Profile OK** notification received  
2. A few minutes later **Insulin   Suspended** alert is triggered with relative beep Omnipod Dash sound.  

If refresh button is clicked then alert is acknowledged and everything back to normal. If borders are crossed again issue happens again.  

Issue happened today at 09:34. Logs were unfortunately taken late at 22:20. I hope it covers this morning too. Otherwise I can attach new ones when reproduced.  

![Screenshot_20220515_222315_com.google.android.apps.photos.jpg](https://user-images.githubusercontent.com/4725280/168492440-a936304a-7f5a-4e1a-8ab7-dff4a743fbef.jpg)

![Screenshot_20220515_222323_com.google.android.apps.photos.jpg](https://user-images.githubusercontent.com/4725280/168492443-e731143b-cb3c-41e2-bb7e-15ad6d746bd6.jpg)

![Screenshot_20220515_222329_com.google.android.apps.photos.jpg](https://user-images.githubusercontent.com/4725280/168492446-361dda81-c033-4a45-8be8-5bbf1f88c9f0.jpg)

![AndroidAPS_LOG_1652645482499.log.zip](https://github.com/nightscout/AndroidAPS/files/8695932/AndroidAPS_LOG_1652645482499.log.zip)

**Comment by Steiniken** [comment]
Hi,
I can confirm this issue. Happend to me after boarder crossing from gemany to austria.

AAPS Version: v3.0.0.1
Phone: Google Pixel 4a
Android Version: 12
