### ISSUE TITLE
No syncing between NSClients -> AAPS

### ISSUE THREAD

**Issue by zwackelfuss** [nightscout/AndroidAPS#1743]
I did not notice it first, but now I am sure:
Actions taken from NSClient are **not** synced to AAPS master, for example  entering carbs or setting a temp target like "eating soon" , although they are synced to Nightscout.

Syncing "the other way" from AAPS to NSClients and Nightscout works fine.

As using NSClient to handle the most common actions remotely without the need to have kid's AAPS phone in hands, I would be really happy if syncing would work properly again (as it did in 2.8, at least for us).

As always: thank you!

**Comment by bchris21** [comment]
Same here, tested yesterday with Dev-K and nothing synced (carbs, TBR, etc).

**Comment by MilosKozak** [comment]
i just tested it on latest dev and it works. i'd need an example with logs from both NSClient and master (latest dev version)

**Comment by reijoahola-nightscout** [comment]
I tested this with the latest dev-k build 2022.05.16 and NSClient -> AAPS syncing worked.
Are you sure that you have enabled NSClient / Synchronisation settings in AAPS app Config Builder ?

**Comment by MilosKozak** [comment]
I see there are 2 TTs with similiar time. there is a bug in NS. could you try it with dev version of NS?

**Comment by bchris21** [comment]
Just tried with both Dev-k versions in NSClient and AAPS.

For me TBR is not passed to Nightscout at all.

**NSClient TBR 150mg/dl**
![Screenshot_20220519_235838.jpg](https://user-images.githubusercontent.com/4725280/169412180-53d02317-fc75-496e-970a-22922d979882.jpg)

**NSClient not passing the TBR**
![Screenshot_20220519_235950.jpg](https://user-images.githubusercontent.com/4725280/169412197-a1ef84eb-8e9c-4f01-90b1-cde523a5f335.jpg)

**Nightscout not reflecting the TBR**
![Screenshot_20220520_000035.jpg](https://user-images.githubusercontent.com/4725280/169412222-655e28ed-fb44-4f77-932d-87f62a5c456c.jpg)

**TBR not passed to AAPS**
![Screenshot_20220520_000229.jpg](https://user-images.githubusercontent.com/4725280/169412232-c3f1ee2d-a3ca-464e-84ce-a670ba5461ff.jpg)

![Screenshot_20220520_000703.jpg](https://user-images.githubusercontent.com/4725280/169412614-e4429ba1-2c56-4e36-b53a-9222a0830606.jpg)

![Screenshot_20220520_000800.jpg](https://user-images.githubusercontent.com/4725280/169412626-22c8d93c-2df8-481a-adcf-092324d3ae7f.jpg)

**Comment by MilosKozak** [comment]
I mean NS not NSClient

**Comment by bchris21** [comment]
NS upgraded to Dev (14.2.6 - 555f699e) 

I canceled a TBR but still nothing is passed on NSClient. 

![Screenshot_20220526_194815.jpg](https://user-images.githubusercontent.com/4725280/170547236-c75dddac-dc73-4daf-8b66-bc4b12cd149e.jpg)

![Screenshot_20220526_194726.jpg](https://user-images.githubusercontent.com/4725280/170547277-b3f99c39-5d7a-4319-96ae-478974d89fab.jpg)

![Screenshot_20220526_194932.jpg](https://user-images.githubusercontent.com/4725280/170547350-16bf57ad-749d-4612-a49b-ed136680c0e2.jpg)

Any advice for further troubleshooting?

Thank you in advance. 

Chris

**Comment by MilosKozak** [comment]
if you mean TT (not TBR) i tested now and it's working
guesing you don't have it enable in NSclient synchronization on AAPS side

**Comment by bchris21** [comment]
Issue fixed for my case. 

Built and installed NSClient2 which works fine. Upgrading to NS Dev did not work.

Apparently something was corrupted on previous installation.

Again thanks for your support.
