### ISSUE TITLE
[Enhancement] SMS Commands from a non-smart phone 

### ISSUE THREAD

**Issue by bchris21** [nightscout/AndroidAPS#1746]
I work in an environment where smart phones are not allowed for security reasons. Phones without a camera, usually old models, are an exception to the rule.

I cannot use them though as I cannot take a photo of the QR-Code for 2FA. Is there a way not to use 2FA setup and use this type of phone? Maybe add support for a portable token generator.

Thanks

**Comment by MilosKozak** [comment]
I don't know such device but for example Authy has application for PC

**Comment by bchris21** [comment]
I know Yubico as hardware token that supports most well known services.

https://www.yubico.com/  

![5series-new-edited-2-1024x406.png](https://user-images.githubusercontent.com/4725280/169162051-8d6f62ce-ff79-4ede-a794-614139aa2d72.png)

But I don't know how/if can this fit to AAPS and a non-smart phone.

I will meanwhile try to see how Authy web works.

Thanks Milos

**Comment by MilosKozak** [comment]
yubico is for different purpose
