### ISSUE TITLE
Feature Request: Main Graph rendering for Profile Changes

### ISSUE THREAD

**Issue by koelewij** [nightscout/AndroidAPS#1754]
The font and color used for showing a profile change in the graph is blurring the graph and also making other data hard to read. 
Changing the font and size to the same one that is used for Carbs & U of insulin, and giving it a different color (ie, magenta), would make it better to read and give less clutter on the screen. 
I do some automated temporary profile % changes, and those are intentionally set to a short interval. Therefore, multiple profile changes occur in a reasonable short timeframe. 
The image shows a 6 hour graph. changing that to 12 or more hours, will clutter the screen even more. 
![Screenshot_20220520-110440_AndroidAPS](https://user-images.githubusercontent.com/77214125/169495339-c64109f6-68f0-46df-a229-5bd1d307af77.jpg)

**Comment by robertrub** [comment]
I "plus 1" this request. The graphics become unreadable and the information is shown twice (in orange and blue).
I think that @Philoul had already created a pull request to "clean up" the graph with a check box...

 N.B. Am I the only one having trouble to upload pictures here ??? After the 6th unsuccessful try, I give up :(

**Comment by Philoul** [comment]
@robertrub My PR with checkbox has been replaced by an new item in graph menu to show or hide treatments.
Profile switches was not included in my old PR.

**Comment by robertrub** [comment]
L![Screenshot_20220521-125954_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/169650605-543be68b-bdd0-48b6-aae2-e7b01f092955.jpg)

Ok. I'd prefer to keep treatements and not see profil changes...

**Comment by Philoul** [comment]
It's not recommanded to have so many profile switches (see https://androidaps.readthedocs.io/en/latest/Usage/Automation.html#incorrect-use-of-automation)
A looper should not have several PS per hours, but only PS for specific events (exercise, ...).

And active profile is the most important information of a looper (all calculated informations and commands done by loop algo use profile informations). That's why I didn't included PS in my PR.

We can of course improve presentation (font size and style, color), but I don't think hide this major information is a good idea...

**Comment by robertrub** [comment]
@Philoul We can talk when your results will be better than mine. For the moment, I have 10% better TIR than you and only 1% hypos.

**Comment by koelewij** [comment]
The profile % changes are based on the BG value. With Fiasp the efficiency gets less @ higher BG, so i compensate with higher profile %. I try to keep the temporary changes short, so it doesn't stay unnecessary long in a higher % than required. I might in the future step over on DynamicISF, but for the time being, this is my DynISF. Options to toggle treatment and profile changes in the graph would also help, but i personally like to see them but less dominant as they are now

**Comment by MilosKozak** [comment]
improved with https://github.com/nightscout/AndroidAPS/commit/8b3c4c18c6a880cfb72fa8374e2be9aee03dcd4d
