### ISSUE TITLE
NSCLIENT - Pause

### ISSUE THREAD

**Issue by Atlas-Night-Out** [nightscout/AndroidAPS#1757]
Reporting bugs
--------------
NSCLIENT Pauseed keeps coming on, on its own! I have to manualy take it off to keep things running.
![pause_bug](https://user-images.githubusercontent.com/83882497/169647166-e56ebfcb-ae7b-406b-86b2-25a108010474.jpg)

Started 3 weeks ago roughly beginning of May 20222 
I had not done anything to make this bug happen it started on its own!
Yesterday it got even worse and no matter how many times I too the paused back off it kept coming back on and effecting my readings going to Xdrip and Nightscout 
I have asked in the group and no one seems to have a fix to this
Im running AndroidAPS 3.0.0.1 and Nightscout Version 14.2.5
[AndroidAPS[1].log](https://github.com/nightscout/AndroidAPS/files/8747381/AndroidAPS.1.log)

**Comment by MilosKozak** [comment]
NSClient is puased automaticaly after 5 reconnections within 2 min to prevent high data usage.
it's unpaused after 15 min (but can stay paused if the app is restarted meanwhile)
you have to resolve connectivity issues
btw reconnection is done with cellular <-> wifi change too

**Comment by Atlas-Night-Out** [comment]
I have wifi connected all of the time and the pause does not come back on as I see it auto pause and Im connected to wifi!

**Comment by Atlas-Night-Out** [comment]
Thank you was the cellular connections nice to know it works this way!
