### ISSUE TITLE
Profile switch: Percentage missing in Nightscout entry

### ISSUE THREAD

**Issue by philipgo** [nightscout/AndroidAPS#1758]
I am using AAPS dev (currently build 36a4ca33e-2022.05.20-18:11). Since around 12.04.2022 profile switches are displayed on Nightscout without the percentage. 

There are no relevant recent changes in Nightscout, so I assume it must have something to do with AndroidAPS. 

Could it have to do with this commit? [core/src/main/java/info/nightscout/androidaps/extensions/ProfileSwitchExtension.kt](https://github.com/nightscout/AndroidAPS/commit/2a54452e95c02d5d6c18861f2eb4d7a80634354d)

![grafik](https://user-images.githubusercontent.com/29184757/169668610-1c15a958-ec7d-4096-973a-b419c5b57d93.png)

The MongoDB entries show that the percentage is missing in the treatment entry.

![grafik](https://user-images.githubusercontent.com/29184757/169668959-3df4dbcd-9c85-4d8e-b724-c7dc4eeefe3f.png)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/4debc1b1708686d38e8544ac82da49b5e2bbbdf1

**Comment by philipgo** [comment]
Thank you, Milos!
