### ISSUE TITLE
Feature request / Meal bolus : separate IOB and COB check boxes

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1767]
It would be useful to be able to check COB and not IOB for a meal bolus.

If there is a low BG before a meal, I enter carbs but do not inject.

10-15 min later, I want to bolus using the calculator. The neg IOB stacked before the meal is added to the bolus due to COB and ends up giving too much insulin and a hypo.

Actually I can't check COB only. IOB gets selected at the same time.

![Screenshot_20220523-201418_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/169894914-7f4f786c-7da3-4c68-9531-606e9ba47a64.jpg)

**Comment by MilosKozak** [comment]
Allowing to select COB without IOB could lead to huge overdosing. This will not be allowed
And in your case it would not help anyway, because negative IOB doesn't disappear itself. if it's (after 15 min) above zero it means APS already gave you this insulin
