### ISSUE TITLE
2.8 limit for smb limit in min

### ISSUE THREAD

**Issue by CaroGo** [nightscout/AndroidAPS#177]
Version 2.8., poco f1 android 9, DanaRS , 

In this new update there is no more a limit for smb min. You could accidentally enter fir example 900 instead of 90 min.. (in uam field there is still a limit active!)

**Comment by MilosKozak** [comment]
limited by https://github.com/nightscout/AndroidAPS/commit/f28b04226e22789e1558365a03475522db44536a
