### ISSUE TITLE
Minor esthetic / graph menu color bug

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1770]
The treatements are in orange on the graph but the text background color in the menu is not the same color. It is a minor bug but confusing.

This is in dev-k. Didn't have the possibility to build dev-l yet.

![Screenshot_20220526-025638_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/170388488-0cf76372-1036-4df4-9793-dfe7cffa41ec.jpg)

**Comment by osodebailar** [comment]
@robertrub yes i Minor thing but I will have a look after father day .
