### ISSUE TITLE
[dev-l] After UI update graph labels doubled

### ISSUE THREAD

**Issue by swissalpine** [nightscout/AndroidAPS#1771]
Milosz, thank you first of all for your tireless work.
Maybe the UI update is not ready yet yesterday. If it is, I would like to ask you to label again on the graph again (as before) only every 2nd line: So BG values only with 40-80-120-etc. and not show every hour twice.
This would be an optical advantage at least for small screens ...

<img width="181" alt="image" src="https://user-images.githubusercontent.com/12517693/170426046-afd5f1cf-40c1-4a0d-8c9e-d69a5cfd8562.png">

**Comment by swissalpine** [comment]
Addition: Compared to an old screenshot, it is noticeable that the number of grid lines has doubled, not the labeling. Maybe this is the way?

<img width="179" alt="image" src="https://user-images.githubusercontent.com/12517693/170428170-2ac8c8ce-2390-437c-8321-cd93f7fe6426.png">

**Comment by MilosKozak** [comment]
it can be related to graphview update. I didn't notice this change on my phone
Could you test reverting this commit https://github.com/nightscout/AndroidAPS/commit/4350a2d5d178038c1debe0e38556fb35fe8dd6d8 ?

**Comment by osodebailar** [comment]
@MilosKozak they are (not) doubled, but it looks like than they are .
One hour has 2 entries: one for the full hour , one for the half hour . Maybe it’s configurable ?

**Comment by swissalpine** [comment]
Thanks!
Reverting this commit fixes the issue.

While looking at the change before reverting I noticed that Android Studio showed me errors in the FixedLineGraphSeries.java file, e.g. there should be no (false) here:
```
            maxY = graphView.getSecondScale().getMaxY();
            minY = graphView.getSecondScale().getMinY();
```
And  the following line should overrides nothing:
```
@Override public void drawSelection(GraphView mGraphView, Canvas canvas, boolean b, DataPointInterface value) {}
 ```

**Comment by MilosKozak** [comment]
these changes are related to change in lib

**Comment by MilosKozak** [comment]
this is how i see latest dev
![image](https://user-images.githubusercontent.com/11146458/170460236-78505022-16bc-42b8-9a5f-9d694adee66f.png)

**Comment by osodebailar** [comment]
This is my view :
![A108902D-D35B-41E6-BEE7-90544806B01A](https://user-images.githubusercontent.com/25795894/170462167-ad2c3630-431d-45b7-a0b5-7ecec7d16d1a.png)

**Comment by MilosKozak** [comment]
I reverted the upgrade. I could not make it working like before.
I remember it was hard before too

**Comment by swissalpine** [comment]
Thanks!!!
