### ISSUE TITLE
NSClient Dev-l not syncing on profile switch cancelation

### ISSUE THREAD

**Issue by bchris21** [nightscout/AndroidAPS#1772]
**Version:** Dev-l (on both AAPS and NSClient)  

**Issue Description:**  
- Changed profile to 150% and synced ok to NSClient  
- Automation canceled the high profile from 150% to 100% but profile was not changed to 100% on NSClient. 
- Also noticing a small IOB deviation (0.01U on AAPS to Neg. IOB on NSClient).  
- On NSClient I cannot switch to 100% manually. It's frozen on 150%.  
- Had no issues with Dev-K

Logs attached. 

**NSClient**  
![Screenshot_20220526_074339.jpg](https://user-images.githubusercontent.com/4725280/170434671-d111f86e-c569-44b3-ad43-67ddd2542db4.jpg)

![Screenshot_20220526_074451_info.nightscout.nsclient.jpg](https://user-images.githubusercontent.com/4725280/170434687-1ea7ae9a-a462-46e9-8b11-3a87923c39af.jpg)

**AAPS**  
![Screenshot_20220526_085655.jpg](https://user-images.githubusercontent.com/4725280/170434863-acb6458e-bf01-4077-b558-8085f9bce315.jpg)

![Screenshot_20220526_085706.jpg](https://user-images.githubusercontent.com/4725280/170434879-08dc3622-1f7a-47b5-9c67-af36deec168b.jpg)

![AndroidAPS_LOG_1653543930691.log.zip](https://github.com/nightscout/AndroidAPS/files/8776960/AndroidAPS_LOG_1653543930691.log.zip)

![AndroidAPS_LOG_1653543910211.log.zip](https://github.com/nightscout/AndroidAPS/files/8776962/AndroidAPS_LOG_1653543910211.log.zip)

**Comment by MilosKozak** [comment]
do you use dev branch of NS? there is a bug in master

**Comment by bchris21** [comment]
Yes Milos. Maybe it's related with with issue #1743 too https://github.com/nightscout/AndroidAPS/issues/1743.

How can I use Dev in NS? Rebuild in Heroku using Dev branch? Will I keep my NS URL? (That's my only concern actually).

Thanks

**Comment by bchris21** [comment]
@swissalpine thanks a lot.

Nightscout updated in Heroku. Just to confirm my actions:  

1) I disconnected and reconnected my fork and changed branch to Dev
![image](https://user-images.githubusercontent.com/4725280/170540422-cf4b7d17-32b2-4410-b46d-d90cf996df36.png)

2) Deployed successfully 
![image](https://user-images.githubusercontent.com/4725280/170541472-dd955e71-8e67-4252-a73e-26fa6643d67d.png)

![image](https://user-images.githubusercontent.com/4725280/170541593-e68f5f98-9481-4f2b-8711-12a581f8bf87.png)

**Question:**  
How can I confirm that I have Dev version in NS and not the Master?  As far as I remember version was the same before using Master. Restarted All Dynos and refreshed NS page.  
![image](https://user-images.githubusercontent.com/4725280/170542038-e8884855-fad1-4dc0-8f94-9420c898c29c.png)

I tried to send a TBR with NSClient (https://github.com/nightscout/AndroidAPS/issues/1743) but still is not passed.

Thanks

**Comment by MilosKozak** [comment]
tbr cannot be send over NS. It must come from pump

**Comment by bchris21** [comment]
Temp Target I am sorry.

Also tried carb entry and bolus (record only) but didn't work. 

Just tried with my wife's phone and all features work.

I have a Huawei P30 Pro while she has a Huawei P30. Same Dev-l versions installed on both phones.

I believe it's phone issue. I would like to make a clean installation of NSClient on my phone. Shall I Reset Database on NSClient? Will I lose any data from AAPS or NS or just local data? Can I simply uninstall and reinstall without recovering a settings backup?

Thanks

**Comment by bchris21** [comment]
Issue fixed.

Built and installed NSClient2 which works fine. 

Apparently something was corrupted on previous installation.

Again thanks for your support.
