### ISSUE TITLE
AAPS seems to have stuck itself

### ISSUE THREAD

**Issue by yhonatanb20** [nightscout/AndroidAPS#1783]
I've got no idea what happened here, but this seems like a serious bug, never seen it before:
![Screenshot_20220530-080711_AndroidAPS](https://user-images.githubusercontent.com/93551840/170921422-0e852717-4ccd-4476-b6e8-3371e19f1e9f.jpg)

**Comment by yhonatanb20** [comment]
AAPS 3.0.0.1 master

**Comment by MilosKozak** [comment]
play protect active?

**Comment by yhonatanb20** [comment]
No
At the bottom says 'handshaking'
