### ISSUE TITLE
[3.0.0.2-dev-l] AAPS Automation rule not possible to delete

### ISSUE THREAD

**Issue by reijoahola-nightscout** [nightscout/AndroidAPS#1784]
Tested AAPS app version is now the latest 3.0.0.2-dev-l (69ad28eaa) but the problem is probably also in some earlier versions.

After editing a new rule into Automation list, it cannot be deleted.
However it appears that when the phone or app is restarted, that rule can be deleted.

Not a big issue but clearly everything is not working as expected.

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/7fac5a87f3367193c3b1674312b0b39f28d74ba8
