### ISSUE TITLE
Pod not initialisated #dash #samsungS9+

### ISSUE THREAD

**Issue by Mynez** [nightscout/AndroidAPS#1787]
I have already tried to inizialized few **Dash pods**. My s9+ has always done it. In attached error message and logs. I'll tried a different dash box now... 

[Log file ](https://drive.google.com/file/d/1pbvN8dcXc9u4QYcbVPiN6tUOQ-141Jcl/view?usp=drivesdk)

![Screenshot_20220530-114017_AndroidAPS](https://user-images.githubusercontent.com/106529214/170978688-df6190c3-a3d2-44a8-ae73-348d5cf52d72.jpg)

**Comment by avereha** [comment]
Try maybe to get the phone closer to the pod?

**Comment by filipwoz** [comment]
Also using S9+ without initialization problems

**Comment by MilosKozak** [comment]
Closed for inactivity. Create new issue is if you still see the problem on latest branch
