### ISSUE TITLE
BYODA calibration =》red triangle in AAPS

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1791]
@MilosKozak I got the difficult to catch calibrating in BYODA giving a red triangle bug once more. I hope the logs will help you this time.

Around 22h27, I calibrate in BYODA. It was showing sth like 190 and calibration was higher, sth like 215... Next BG read, BYODA and xDrip shows 216 but AAPS shows 195. I look in BYODA tab in AAPS, the time stamp is correct 22:27 but BG is not 216 as in xDrip and BYODA.

5 min later, the BGs aligne on the 3 aps but I get the red triangle in AAPS.

![Screenshot_20220529-183119_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/171057482-29d56146-bd49-4f30-9bbc-0aa0f6d8dee1.jpg)

![Screenshot_20220530-223318_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/171057497-60eacac5-d811-4d07-91bf-dd325afe475f.jpg)

![Screenshot_20220530-223533_xDrip+.jpg](https://user-images.githubusercontent.com/76626474/171057508-2ee2e860-432a-4a3e-9931-07661e6d4b04.jpg)

![20220530_223740.jpg](https://user-images.githubusercontent.com/76626474/171057521-ffdeac8d-e2d8-4e28-a171-554115f5598e.jpg)

And the logs. Look a bit before and after 22:27...

![AndroidAPS_LOG_1653942984156.log.zip](https://github.com/nightscout/AndroidAPS/files/8800669/AndroidAPS_LOG_1653942984156.log.zip)

**Comment by MilosKozak** [comment]
this is impossible to detect from received batch (only 1 wrong value). The only way would be compare with database which would be expensive
I'll keep this open to see if it's rare or not

**Comment by robertrub** [comment]
Ok. It is in fact rare as I didn't have this bug for over a month (and I calibrated around the 5 min delay often).

Will come back if it happens again.

**Comment by vanelsberg** [comment]
>  in fact rare

Interesting. 
Calibrating G6/BUODA often (avg once every 2 days). Haven't seen any red triangles for a long time ...

**Comment by vanelsberg** [comment]
Weird problem: Have seen this in the past (weeks ago).
I cannot repro this. Tried several times.
Also I calibrate my G6 every 2 days on average. So I should see this at least occasionally

**Comment by robertrub** [comment]
Hi @MilosKozak Got the red triangle once more and this time I was about 3 min after the sensor BG measure. The difference between sensor and blood was important (G6 54 vs blood 70).

![Screenshot_20220618-230541_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/174457131-56052e8b-eebf-4bc0-85b8-e50de9dbd29a.jpg)

![Screenshot_20220618-230648_Dexcom G6.jpg](https://user-images.githubusercontent.com/76626474/174457135-464390bb-3397-44eb-b657-ec2f022546ac.jpg)

![AndroidAPS_LOG_1655586356150.log.zip](https://github.com/nightscout/AndroidAPS/files/8934357/AndroidAPS_LOG_1655586356150.log.zip)

I hope you'll get more info from these logs.

![20220614_083736.jpg](https://user-images.githubusercontent.com/76626474/174457174-3bd61342-1a51-4302-9158-5150ffa3e590.jpg)

**Comment by robertrub** [comment]
@MilosKozak I don't know if you did any work on the subject. I calibrated at 7:39 just after the 5 min top at 7:38.

There is a slide on the next BG in AAPS 7:44 that does not respect the 5 min intervals but had no flags.

To make it short : all is working ok.

![IMG_20220713_080830.jpg](https://user-images.githubusercontent.com/76626474/178663481-8c6d23b3-4e57-406b-8de8-4317ecf64773.jpg)

![IMG_20220711_140609.jpg](https://user-images.githubusercontent.com/76626474/178663536-1e443596-66ee-4f31-8a71-b5db6a866ed1.jpg)

After 5 tries, I can't upload a logs :( The GitHub app needs debugging too :) Will try later

**Comment by robertrub** [comment]
Ok, after 10 trials I give up. Tell me if you need the logs...
