### ISSUE TITLE
[2.7] Feature Request: Add Battery Age, Canula Age and Remaining Glucose to Automation

### ISSUE THREAD

**Issue by Arne1346** [nightscout/AndroidAPS#18]
Hi,

I would like to use AAPS Automation do show me a notification when 

- Battery age is older than n days
- Canula age is older than n days
- Remaining glucose in cartridge is less than n IE

and this info I'd like to receive during daytime only.

Automation would be a perfect tool if the three triggers were available.

Could you add them?

thank you,
Arne

**Comment by reijoahola-nightscout** [comment]
I would like to add also Battery level into this list. However, I must agree that all these can also looked after quite well with Status lights in the main screen.

**Comment by Arne1346** [comment]
In principle true, compared to the previous AAPS versions the main menu display in 2.7 is a big step ahead, but still can be overlooked quite easily. My preference would be a notification you actively need to confirm.

**Comment by MilosKozak** [comment]
setting tresholds and use colors is enough from my point of view
if you you watch the screen you'll see it. if not, notification doesn't help much
