### ISSUE TITLE
Can't load/create profile when migrating from TidePool Loop to AndroidAPS

### ISSUE THREAD

**Issue by PieterGit** [nightscout/AndroidAPS#1809]
Use case
* I am using TidePool Loop by default. TidePool Loop uploads `Default` profile to Nightscout
* Trying to get AndroidAPS, working with MDT 754/OrangeLink/DexcomG6/NS Client
* AndroidAPS fails with `Ongeldig profiel Default niet geaccepteerd door NS`
* The extended error message does not show any "reasons" of why the Profile is invalid
* I didn't manage to be a able to create a "LocalProfile" in AndroidAPS, so AndroidAPS is stuck because  "Geen profile ingesteld" (`noprofileset`)

Expected result: 
* Being able to use Loop `Default` profile, or being able to create a new `LocalProfile1`

Versions used:
* Nightscout version 14.2.6 (`dev` branch)
* TidePool Loop (`dev` branch)
* AndroidAPS: Version: 3.0.0.2-pumpcontrol (BuildVersion: 219bdba215-2022.05.02-18:08)
* Dutch (NL) language is set.

Relevant logfile:
```
12:49:12.104 [RxCachedThreadScheduler-26] D/NSCLIENT: [NSClientPlugin.onStart$lambda-5():124]: AUTH Authenticated (RWT)
12:49:12.106 [RxCachedThreadScheduler-26] D/NSCLIENT: [NSClientPlugin.onStart$lambda-5():124]: PROFILE profile received
12:49:12.137 [RxCachedThreadScheduler-26] D/NSCLIENT: [NSClientPlugin.onStart$lambda-5():124]: DATA received 537 treatments
12:49:12.147 [RxCachedThreadScheduler-26] D/NSCLIENT: [NSClientPlugin.onStart$lambda-5():124]: DATA received 10 device statuses
12:49:12.148 [NSClientServiceHandler] D/NSCLIENT: [NSDeviceStatus.handleNewData():89]: Got NS deviceStatus: $deviceStatuses
12:49:12.215 [RxCachedThreadScheduler-26] D/NSCLIENT: [NSClientPlugin.onStart$lambda-5():124]: DATA received 5 foods
12:49:12.218 [RxCachedThreadScheduler-26] D/NSCLIENT: [NSClientPlugin.onStart$lambda-5():124]: DATA received 1 mbgs
12:49:12.221 [RxCachedThreadScheduler-26] D/NSCLIENT: [NSClientPlugin.onStart$lambda-5():124]: DATA received 750 sgvs
12:49:12.225 [RxCachedThreadScheduler-26] D/NSCLIENT: [NSClientPlugin.onStart$lambda-5():124]: LAST 
12:49:12.295 [pool-14-thread-1] D/PROFILE: [LocalProfilePlugin$NSProfileWorker.doWork():476]: Received profileStore: createdAt: 1654326148000 Local last modification: 0
12:49:12.307 [pool-14-thread-1] D/PROFILE: [LocalProfilePlugin.loadFromStore():286]: ProfileStore not accepted
12:49:12.307 [RxCachedThreadScheduler-9] D/NOTIFICATION: [NotificationStore.add():60]: Notification received: Ongeldig profiel Default niet geaccepteerd door NS
12:49:12.308 [pool-14-thread-1] D/PROFILE: [LocalProfilePlugin$NSProfileWorker.doWork():480]: Received profileStore: {"_id":"xxx","enteredBy":"Loop"...
```

I will dig deeper to see if I can find a cause in either Nightscout / Loop or AndroidAPS.

**Comment by MilosKozak** [comment]
NS profiles are accepted only if they pass check.
this message means DIA, IC, ISF or Target have values of out accepted range
i believe nobody tested importing Loop profiles and nobody will
