### ISSUE TITLE
[2.8] Setup Wizard fails to import configuration

### ISSUE THREAD

**Issue by ArthurusDent** [nightscout/AndroidAPS#182]
I switched phones yesterday and did a fresh install of AndroidAPS 2.8 but copied the config files, too. When the Setup Wizard offered to import my settings, I pressed the button to open the dialogue but nothing happened. Another person on Discord reported the same problem. The person and I had no problem importing the config by using the usual maintenance dialogue.

System:
AndroidAPS 2.8
Medtronic 554
Dexcom G6
xDrip+
Oneplus 3T
Lineage 17.1

**Comment by MilosKozak** [comment]
on some phones it's necessary to restart aaps to apply storage permission

**Comment by ArthurusDent** [comment]
I didn't restart AndroidAPS. I quit the wizard and went straight to the maintenance dialogue.

**Comment by MilosKozak** [comment]
then restart of activity is enough

**Comment by ArthurusDent** [comment]
Sorry, I'm not following. Could you repeat yourself in more layman terms?

**Comment by MilosKozak** [comment]
switch between aaps screens

**Comment by robertrub** [comment]
Had the same issue. Import settings while installing didn't import the saved settings. I'm not 100% sure that I restarted the app after the permissions but I think I did restart. 
I had to quit the creation of a new profile and imported through the classical maintenance menu and it worked.
