### ISSUE TITLE
Dashboard minor bugs 3.0.0.2-dev-m 

### ISSUE THREAD

**Issue by Korostensky** [nightscout/AndroidAPS#1833]
Reporting bugs on dashboard
"3.0.0.2-dev-m"
--------------

# 1. When you remove an action from the treatment agenda, the information does not disappear from the chart (only not deleted).

![Screenshot_20220615-104326_AndroidAPS](https://user-images.githubusercontent.com/54218454/173790641-9c92b968-6abc-411a-9648-88f1785593dc.jpg)

![20220615_104627](https://user-images.githubusercontent.com/54218454/173790704-4dffdf3c-a5dd-4988-9d31-aea1768449e6.jpg)

# 2. If I start a new sensor (Dexcom G6), the system calculates the values and displays a warning. But this is displayed for more than one day (no longer shown in the graph, it's confusing) The exclamation mark symbol should disappear when you click "OK" or when the recalculation is not displayed.

![20220615_105623](https://user-images.githubusercontent.com/54218454/173791227-fac71db9-907c-4b88-b50e-19f35b326d43.jpg)
![Screenshot_20220615-105328_AndroidAPS](https://user-images.githubusercontent.com/54218454/173792688-a246c355-3869-4c3b-820e-7ea89233c03e.jpg)

**Comment by MilosKozak** [comment]
1) these are announcements - must be deleted on 5th tab
2) icon doesn't disappear after click. while using Dexcom you can see exclamation mark only on transmitter change for about day and half. If it's different situation, your configuration is somewhere wrong and there are doubled data

**Comment by Korostensky** [comment]
Thank you for the explanation, I agree and apologize for the unnecessary comments.

1. So my deletion only modified the IOB/COB and not the treatment, so it must be deleted from two places. 
But this is very handy (the app doesn't calculate the values, but I can see what I was doing for the changes)

2. I really changed the transmitter, a day and a half is fine.
