### ISSUE TITLE
Bolus cannot be cancelled

### ISSUE THREAD

**Issue by antoinekh** [nightscout/AndroidAPS#1834]
## Version
Master 3.0 and last dev
Omnipod DASH

## Bug

The bolus is seen in the display as the SMB small bar and it is not possible to cancel it

## How to reproduce it

1. Wait for the injection of a SMB
2. Send a bolus

Gif/video below:

![gif_bug_bolus](https://user-images.githubusercontent.com/52744345/173900170-430e9c8b-751e-4a76-a1c6-ff3af7c5d877.gif)

Same issue than #1315

**Comment by Der-Schubi** [comment]
We once discussed this topic on Discord from another angle. We talked about the idea, being able to hide / minimize the bolus dialog. Then you would need an option to bring the dialog back up so you could cancel a bolus if necessary.
Maybe it would be possible to bring up the bolus progress dialog by pressing on the pump status notification.

But maybe it would be easier to just open the dialog after the SMB is done.
Any idea, @MilosKozak ?

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/bbcbf3f90535c719fb70bbcb41c486cc7bf475ad
