### ISSUE TITLE
bug: Notes field not delivered to nightscout (at leats for carb correnctions)

### ISSUE THREAD

**Issue by justmara** [nightscout/AndroidAPS#1835]
**Steps to reproduce:**

- open `carbs` dialog, 
- enter carbs amount, 
- enter `test note` text in `Notes` field
- press `ok`, then `ok` to send
- wait event to be delivered to NS
- open nightscout -> reports -> treatments. there will be your new `carb correction` (or `meal bolus`) treatment with empty `Notes` column
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/4157587/174256868-0c05d0cb-550d-4d09-864a-21caa55df763.png">
in nightscout's db field `notes` is empty, like if it wasn't even sent to nighscout

**Expected behavior**
`test note` text in `Notes` field

**versions used**
Checked in nsclient 3.0.0.2 (downloaded from releases in github) and aaps 3.0.0.2 (built myself).
Nightscout 14.2.5

additional screenshots:
(this is add carbs screen from aaps, but in russian, sorry :))
<img width="346" alt="image" src="https://user-images.githubusercontent.com/4157587/174257591-fab6148c-0822-4d92-b034-b4db46ceb8ab.png">
note correctly shown in treatments (but still missing in nightscout)
<img width="405" alt="image" src="https://user-images.githubusercontent.com/4157587/174257699-c0b2b161-5a03-464c-b60f-a4657aab1095.png">

this is 2.8.2 nsclient behavior:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/4157587/174259482-34d88dd6-abb8-424d-8a1b-b952646e67d9.png">

<img width="1522" alt="image" src="https://user-images.githubusercontent.com/4157587/174259428-a58287a4-aa0d-45db-aeff-481e80e6765c.png">

**Comment by justmara** [comment]
this is how it seems from nightscout logs
```
 [32mWS: [0mdbAdd client ID:  P0NQlXvnhQyg6nOqAAAC  data:  {
  collection: 'treatments',
  data: {
    eventType: 'Carb Correction',
    carbs: 1,
    created_at: '2022-06-17T09:20:52.000Z',
    isValid: true,
    date: 1655457652000
  }
}
[35mDEDUPE: [0mAdding new record
got data-received event, requesting reload
[32mWS: [0mdbUpdate client ID:  nzi8xvBB9O9gGzpuAAAA  data:  {
  collection: 'treatments',
  _id: '62ac4794324e1700041bf697',
  data: {
    eventType: 'Carb Correction',
    carbs: 1,
    created_at: '2022-06-17T09:20:52.000Z',
    isValid: true,
    date: 1655457652000
  }
}
got data-received event, requesting reload
Got results {
  _id: 62ac4794324e1700041bf697,
  eventType: 'Carb Correction',
  carbs: 1,
  created_at: '2022-06-17T09:20:52.000Z',
  isValid: true,
  date: 1655457652000
}
```

this is same action sent from 2.8.2
```
[32mWS: [0mdbAdd client ID:  TaiSKeiBC1Z2lck7AAAD  data:  {
  collection: 'treatments',
  data: {
    eventType: 'Carb Correction',
    carbs: 1,
    created_at: '2022-06-17T09:38:54Z',
    date: 1655458734000,
    isSMB: false,
    notes: 'test note',
    NSCLIENT_ID: '1655458748903'
  }
}
got data-received event, requesting reload
[35mDEDUPE: [0mAdding new record
got data-received event, requesting reload
Load Complete:
	 sgvs:557, treatments:78, mbgs:2, profiles:1, devicestatus:845, sitechangeTreatments:1, insulinchangeTreatments:1, batteryTreatments:1, sensorTreatments:1, profileTreatments:2, tempbasalTreatments:4
data loaded: reloading sandbox data and updating plugins
[32mWS: [0memitted notification to all clients
2022-06-17T09:39:16.492Z	EMITTING NOTIFICATION:
  {"level":"Info","title":"Carb Correction","message":"\nCarbs: 1g\nNotes: test note","group":"default","plugin":"treatmentnotify"}
  ```

**Comment by MilosKozak** [comment]
db schema must be extended

**Comment by justmara** [comment]
@MilosKozak Why `enhancement` label? This feature were working on 2.0 and was lost during update to 3.x. And there is also UI input that is not processed/stored/sent as intended.
So it's a real bug introduced in 3.0 version of app, not a new feature/enhancement.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/pull/1842#issuecomment-1160627114
