### ISSUE TITLE
I keep getting an error using Accu-Chek Combo pump while bolusing

### ISSUE THREAD

**Issue by AndreySlepykh** [nightscout/AndroidAPS#1848]
Error message: Data is coming from different pump/ Change pump driver to reset pump state.
The problem start occuring 22 jun 2022 when I installed AndroidAPS v3.0.0.2 (Build: 219bdba21-2022/06/22-12:57)
I keep getting an error using Accu-Chek Combo pump while bolusing

[AndroidAPS._2022-06-23_00-00-00_.5.zip](https://github.com/nightscout/AndroidAPS/files/8965727/AndroidAPS._2022-06-23_00-00-00_.5.zip)

**Comment by MilosKozak** [comment]
switch to virtual pump and back
