### ISSUE TITLE
Users need a way to archive objectives achieved, independently from preferences

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#1852]
APS version 3.0

Users need a way to archive objectives achieved, independently to preferences.

As is now, restoring objectives can only be done by way of importing an old settings file.
Preferences from the old settings file are most likely outdated and will overwrite current settings.

**Comment by vanelsberg** [comment]
Possible solution:
While importing give the user the option to import "Objectives only"?

**Comment by MilosKozak** [comment]
80% of users would do this instead of pass them

**Comment by vanelsberg** [comment]
> 80% of users would do this instead of pass them

@MilosKozak Not sure what you are saying?
Objectives export/import is (should be) encrypted in the same way preferences are?

**Comment by MilosKozak** [comment]
everyone would look for any export on internet and just import finished preferences
