### ISSUE TITLE
Omnipod EROS: There is no way to forcefully wipe/reset the pod state in case of "emergency"

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#1853]
**AAPS version 3.0.0.1 release and higher**
**Driver: Omnipod EROS**

**Problem description:**
The Omnipod EROS driver has a bug that can lead to a situation where users get stuck with a pod registration that can not be continued or discarded. Several users reported running into this problem as a result of Pod activation failure.

Work around used for not losing Objectives is importing 3.0 settings in AAPS version 2.8.1, discard the Pod and then export preferences that can be imported by AAPS 3.0

**Proposed work around**:
Until the actual bug is solved, but also in general, I think the EROS driver should have a way to "wipe" the Pod state in case of "emergencies". Up to AAPS version 2.8 this could be done by editing the unencrypted preference file.
As of version 3.0 this is no longer an option.

How about an option to clear Pod state when running in developer mode? This way users have an "escape" option to get out of situations where there is Pod state without option to Discard. For AAPS 2.8 editing the preference file was used as a last resort

**Comment by vanelsberg** [comment]
Alternative solution to the problem would be resetting AAPS preferences or a reinstall.
An option to import "objectives only" would then ensure objectives are not lost

https://github.com/nightscout/AndroidAPS/issues/1852

**Comment by vanelsberg** [comment]
Remark:
Omnipod DASH implementation ensures that after 3 unsuccesfull retries user is offered the option to "forcefully" discarding the Pod.

Something like this maybe could also be implemented for EROS but expect this would need non-trivial driver changes?
Expecting forcefully wiping pod state can be done with minimal impact on drive code?

**Comment by MilosKozak** [comment]
what keys do you have to remove?

**Comment by vanelsberg** [comment]
> what keys do you have to remove?

@MilosKozak 
Clearing `content: "AAPS.Omnipod.pod_state"` should effectively remove the Pod.

Currently not using EROS so unable to validate. Do have 3 EROS pods reserved for dev, so can test when needed.

**Comment by vanelsberg** [comment]
Hint:
Think PodState is accessible at `java/info/nightscout/androidaps/plugins/pump/omnipod/eros/manager/AapsErosPodStateManager.java`
See methods storePodState() and readPodState()?

**Comment by vanelsberg** [comment]
![image](https://user-images.githubusercontent.com/45144129/175774087-fb073756-327e-4c3c-a0f1-c7a3f23de5d6.png)

**Comment by MilosKozak** [comment]
Discard pod is not enough in this state?

**Comment by vanelsberg** [comment]
The bug/problem is that AAPS/EROS somehow gets in a state where activation unexpectedly failed and activation process can not be continued. In that state however the "Discard" button is still Disabled (it believe it is only enabled after successful activation)

**Comment by vanelsberg** [comment]
Most obvious solution would be to target this specific bug (proper error handling?). But that would mean touching driver code which you may not want at this stage?

Also in any other situation, there is still no ways to repair by wiping state?

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/00f0446c21e059f1287333fc72578daeb6f8c8c2

**Comment by vanelsberg** [comment]
> [00f0446](https://github.com/nightscout/AndroidAPS/commit/00f0446c21e059f1287333fc72578daeb6f8c8c2)

Looks good. However not sure if this would do the trick (had been looking at something like this)
Problem is I suspect podStateManager.isPodInitialized to evaluate to true in this case (as Pod activation is started but ongoing)?

**Comment by vanelsberg** [comment]
Nice "solve". Maybe add this to dev and let "testers" look at this.
(Testing this: Of only I new a way to reproduce the originating problem...)

**Comment by vanelsberg** [comment]
Will ask around for a settings file that has the problem so I can test...

**Comment by vanelsberg** [comment]
Thanks @MilosKozak for taking this so fast!

**Comment by MilosKozak** [comment]
you can test it just before pod expiration (to not waste it)

**Comment by vanelsberg** [comment]
Thanks. That is the safest way....
But not needed. Discard (should only) remove the pod registration without actually de-activating the Pod.
So, after Discarding it should be recoverable through importing settings (which contains the pod stat)

**Comment by vincent1890** [comment]
Hello,
Unfortunately I use the dev version and the delete button does not work tested on two different pod (see screenshot
![Screenshot_20220627-021945_AndroidAPS](https://user-images.githubusercontent.com/5764518/176980481-0a88ab2e-e0ad-4ecc-b39f-d43f2c4f0761.jpg)
![Screenshot_20220627-021931_AndroidAPS](https://user-images.githubusercontent.com/5764518/176980483-ec04e5e0-83b2-4dc4-963d-56115fc1badd.jpg)
)
I have been forced to re-import a backup without pod to be able to use a new pod without failure

**Comment by vanelsberg** [comment]
> ... Unfortunately I use the dev version and the delete button does not work ...

@MilosKozak 
Confirming. The "Discard" button is active and responsive but pressing it does not have the expected effect (no errors)
Assuming the underlying code does not allow discarding while the pump is in this state....

**Comment by vanelsberg** [comment]
@MilosKozak Should we re-open this issue or do new?

**Comment by MilosKozak** [comment]
I need more info what must be cleared

**Comment by happygirlnyc70** [comment]
I can confirm this as well.  I have used both 3.1 beta and dev-n 4f0f01883 with the same result.

**Comment by vincent1890** [comment]
@MilosKozak 
> I need more info what must be cleared

Hello
I don’t know if my answer will bring an element of answer but it would have to go back to the state when a POD is deactivated correctly "No active POD".
Currently dasn the capture shown have little to see that a POD is still half active in the AAPS system

**Comment by vanelsberg** [comment]
> I need more info what must be cleared

@MilosKozak Discarding Pod is not Discarding properly....
Think I found the (underlying) problem is in not discarding/handling pod state correctly. Have to look into this ...
Will do a PR this week (currently family matters take prio).

**Comment by vanelsberg** [comment]
@MilosKozak 
Preparing a fix though https://github.com/nightscout/AndroidAPS/issues/1882

**Comment by vanelsberg** [comment]
Expect problem to be solved through https://github.com/nightscout/AndroidAPS/issues/1882
