### ISSUE TITLE
Settings lost after phone hard reboot

### ISSUE THREAD

**Issue by bchris21** [nightscout/AndroidAPS#1857]
Version: Dev-n
Android Version: 9

Phone was squeezed in my bag and power button was pressed. Phone hard rebooted 3-4 times.

When realized AAPS was on open loop. After running loop I got the message that I had to pass objective 1.

Reverted on previous good settings (a month ago) and as expected Pod was lost.

Reverted back to Dev-m and started a new Pod.

Strange thing is that I didn't have to discard the old Pod. I just started a new one.

Logs attached. Issue happened around 15:45 local time.

![AndroidAPS_LOG_1656251991995.log.zip](https://github.com/nightscout/AndroidAPS/files/8986840/AndroidAPS_LOG_1656251991995.log.zip)

![Screenshot_20220626_164334_com.google.android.apps.photos.jpg](https://user-images.githubusercontent.com/4725280/175819876-00811f02-cd4c-47df-8ccb-9226c3625a68.jpg)

![Screenshot_20220626_164340_com.google.android.apps.photos.jpg](https://user-images.githubusercontent.com/4725280/175819882-680fac9e-35a4-4ae4-b082-d078b8d3f036.jpg)

**Comment by MilosKozak** [comment]
that's something I cannot affect

**Comment by bchris21** [comment]
Ok maybe it's phone related.

A bit more info:

- Papertrail data transfer limit reached.
- There is a slow DBUPDATE of all BGs in NSClient.

Can I assume that the whole database was pruned?

Thanks

**Comment by MilosKozak** [comment]
local storage is android thing. AAPS can only use it but not reset it itself
