### ISSUE TITLE
Profile shift can lead to missing profile values

### ISSUE THREAD

**Issue by justmara** [nightscout/AndroidAPS#1858]
Having these profile settings
![telegram-cloud-photo-size-2-5314530843911372903-y](https://user-images.githubusercontent.com/4157587/175823335-e3579c15-322e-49a4-9d1c-2ca48f4c7ffc.jpg)

If you do profile shift for 2 hours, you'll get target of 5 for the whole day since 9:00
![telegram-cloud-photo-size-2-5314530843911372910-y](https://user-images.githubusercontent.com/4157587/175823375-3ed44c8b-5411-4ce0-8230-c5524d0270fe.jpg)
![telegram-cloud-photo-size-2-5314530843911372919-y](https://user-images.githubusercontent.com/4157587/175823652-f734e950-f8a7-4098-ac09-3de092ec5def.jpg)

The second range of '02:00 to 09:00' disappeared, but its value moved to (used to be) third range of `09:00...`

AndroidAPS 3.0.0.2 built from master.

**Comment by MilosKozak** [comment]
can you test the same with beta1 ? i already checked this and it was working properly

**Comment by justmara** [comment]
only could check 3.1-beta in emulator - works fine there.

**Comment by MilosKozak** [comment]
ok, it will be released soon
