### ISSUE TITLE
[2.8] TDD in Statistics is misscalculated

### ISSUE THREAD

**Issue by cristinav74** [nightscout/AndroidAPS#186]
Build version: 2.8

![image](https://user-images.githubusercontent.com/25306225/103630698-ba7f2100-4f4a-11eb-81eb-8f85b14e5b08.png)

The TDD for today is zero, which is incorrect. This results in the Average 8 days results being corrupted.
I believe the Average results should exclude current day.

**Comment by rICTx-T1D** [comment]
In my 2.8.0 version, the stat is ending yesterday and the average is over 7 days.

Do you have change time/date or timezone last 7 days?

**Comment by cristinav74** [comment]
No, but my phone had a security update last night.

New problem: after restarting my phone, I have completely different results in Statistics (obviously corrupted)
![image](https://user-images.githubusercontent.com/25306225/103633289-33cc4300-4f4e-11eb-89a1-efb801a6f3a9.png)

**Comment by rICTx-T1D** [comment]
This don't look nice. :-)
* Store all settings by export  on maintenance menu. 
* Sync all values with nightscout. 
* reset the stat's
* reset the database in maintenance menu
* check if is solved, otherwise reinstall AAPS

**Comment by cristinav74** [comment]
Tried all the options, problem still not fixed but thank you for your suggestions.
As a side detail, I migrated to 2.8.0 from 2.7.0 on Janury 3rd, which is the last day when the numbers are correct.
![image](https://user-images.githubusercontent.com/25306225/103635484-4005cf80-4f51-11eb-8222-626c5c696693.png)

**Comment by rICTx-T1D** [comment]
Has anyone other user the same problem? I can't reproduce it.

**Comment by cristinav74** [comment]
![Screenshot_20210105-183145](https://user-images.githubusercontent.com/25306225/103672018-5d07c600-4f84-11eb-99f5-ce21844f6667.png)

It looks like the pre-migration data cannot be loaded. No TIR and average for the days before installing 2.8.

**Comment by rICTx-T1D** [comment]
The the problem will be solved when time is gone.... Wait some days.

**Comment by cristinav74** [comment]
Definitely, it is a minor problem and should not affect future data (I hope so, I'll monitor my Stats).

**Comment by rICTx-T1D** [comment]
Can you check your stats in 7 or more days (calculated from update-date) again? When all is fine, you can close this issue, otherwise we need a new run to solve it again.

**Comment by cristinav74** [comment]
Sure, I'll keep this issue updated

**Comment by CaroGo** [comment]
I can't reproduce it either... just 7 days shown as it should be. Dana RS,

**Comment by cristinav74** [comment]
The Statistics are correctly calculated now that all of them have been logged under 2.8 version.
