### ISSUE TITLE
3.1beta Watchface isnt connecting.

### ISSUE THREAD

**Issue by FreDiabetics** [nightscout/AndroidAPS#1871]
I'm using a GalaxyWatch4 series and updated to the 3.1beta. No watchface is connecting. Even if I press send values to watch again nothing happens. The aaps complictaions showing !err!
I deleted the wear apk from the watch before I installed the 3.1beta wear apk.

![20220630_205237](https://user-images.githubusercontent.com/45721291/176756622-a392a49d-623a-4619-a289-7c860c845945.jpg)
![Screenshot_20220630_205541_sysui](https://user-images.githubusercontent.com/45721291/176756623-376a3859-4d84-4556-8d3d-49cc715a43e4.png)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
did you build new wear apk?

**Comment by FreDiabetics** [comment]
> did you build new wear apk?

yes I builded the new wear apk and sende it to the watch with android studio. I deleted the old wear apk before

![Screenshot_20220701_064300_androidaps](https://user-images.githubusercontent.com/45721291/176824916-30b5fde1-30a8-4385-bcae-9707edd2708b.png)
.

**Comment by FreDiabetics** [comment]
is there any tip or workaround?

**Comment by CarnageMarkus** [comment]
Same issue here

**Comment by MilosKozak** [comment]
Closed for inactivity. Create new issue is if you still see the problem on latest branch
