### ISSUE TITLE
dev-n not connecting with RileyLink (Medtronic)

### ISSUE THREAD

**Issue by gwsuperfan** [nightscout/AndroidAPS#1872]
Issue started with update to dev-n. Rileylink status w/Medtronic driver sits at "not started" despite no changes in config parameters from dev-m.

Scanning shows the RL device, but AAPS never appears to actually even attempt to initiate contact.

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/77e112471fb30bd13447df5d09a766e45cee3c95
