### ISSUE TITLE
3.1-beta1 Calibration button missing

### ISSUE THREAD

**Issue by PetrMlejnek** [nightscout/AndroidAPS#1875]
I'm missing Calibration button that should send me to BYODA app to calibrate a sensor.
See: https://www.youtube.com/watch?v=bwGZnAQvXGQ

Have this problem since AAPS version 3 (3.0.0.1, 3.0.0.2, 3.1-beta1)
BYODA version: 1.9.0.5, 1.10.0.2
Last AAPS version without this problem was 2.8.2

![calib_button](https://user-images.githubusercontent.com/42749712/176881802-52194f5a-589c-47b7-893e-c1644a39873b.jpg)

**Comment by MilosKozak** [comment]
for BOYDA it's not working properly thus feature has been removed

**Comment by PetrMlejnek** [comment]
> for BOYDA it's not working properly thus feature has been removed

It's a shame, I personally used it every day (1-2x), because I have to calibrate my sensors (even Dexcom G6).
