### ISSUE TITLE
 Rileylink is not connecting Beta 3.1

### ISSUE THREAD

**Issue by toniteh78** [nightscout/AndroidAPS#1876]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by toniteh78** [comment]
![Screenshot_2022-07-01-19-15-58-353_com facebook orca](https://user-images.githubusercontent.com/61123634/176940789-f9c3c740-48e6-41ed-962f-ef025d626834.jpg)

**Comment by MilosKozak** [comment]
fixed in dev
