### ISSUE TITLE
Wear OS: AAPS API version compatibility checks

### ISSUE THREAD

**Issue by Andries-Smit** [nightscout/AndroidAPS#1892]
Before 3.1 communication was less problematic for version mismatches between AAPS phone and watch app. 
Currently, if the API is mismatching the Watch or Phone app crashes when it tries to deserialize an object. This should be prevented.

Suggestion to introduce an API version, which is communicated beginning of the connection. When it mismatches the API should be halted and the user informed. The alternative is a strict match on the matching AAPS version. 

Al least the deserialization error should be caught without crashing the app.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/e1423c0f82a2c56a7d7e1ac734c413ab80b24285
