### ISSUE TITLE
Lineage OS, ANDROID 10 AAPS 3.1 DOESN'T WORK 

### ISSUE THREAD

**Issue by agniabakush** [nightscout/AndroidAPS#1899]
Reporting bugs
-----------
Application closes after launch with the message "An error has occurred in the application"

**Comment by Andries-Smit** [comment]
Can you add log details?
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/Usage/Accessing-logfiles.html

**Comment by agniabakush** [comment]
[AndroidAPS._2022-07-07_17-27-07_.0.zip](https://github.com/nightscout/AndroidAPS/files/9080405/AndroidAPS._2022-07-07_17-27-07_.0.zip)
[AndroidAPS._2022-07-08_09-29-56_.0.zip](https://github.com/nightscout/AndroidAPS/files/9080406/AndroidAPS._2022-07-08_09-29-56_.0.zip)

**Comment by agniabakush** [comment]
I don't know exactly which one, but hope these help.

**Comment by MilosKozak** [comment]
hmm I see you are not using master (or latest dev) version.
This version is not supported here
