### ISSUE TITLE
New crashes

### ISSUE THREAD

**Issue by elgrupo123** [nightscout/AndroidAPS#1901]
We've been getting new reboots a lot lately. 
This morning at 7:43 am. 
Maybe you can see from the log files what the problem is.

Thanks

AndroidAPS 3.0.0.2-dev-n
Build: ad89d5431-2022.07.02-07:56
Remote: https://github.com/nightscout/AndroidAPS
Flavor: fullrelease
Nightscout-Version: 14.2.5
Entwickler-Modus aktiviert
[AndroidAPS_LOG_1657349580752.log.zip](https://github.com/nightscout/AndroidAPS/files/9076078/AndroidAPS_LOG_1657349580752.log.zip)

**Comment by agmsd** [comment]
The same here. I think there cause is June update.

**Comment by agmsd** [comment]
> The same here. I think there cause is June update.
I fixed the problem by flashing a factory image. It's running smoothly now.

**Comment by MilosKozak** [comment]
sorry nothing is visible from log file
PS: turn OFF autosens logging
