### ISSUE TITLE
WIDGET / Android 12 : No more parameters

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1915]
I changed phones for a POCO F3 on Android 12 and I can't get the widget parameters any more. Long press on widget gives me only the size points but no parameter menu.

![IMG_20220716_093837.jpg](https://user-images.githubusercontent.com/76626474/179345399-b15d186d-bc96-4545-b619-73763dd62faf.jpg)

**Comment by MilosKozak** [comment]
probably too small screen. make the widget smaller first

**Comment by robertrub** [comment]
Nice try @MilosKozak  but no,. I had already tried to reduce widget size and the screen is big and has a huge definition. Please reopen the issue ;)

![IMG_20220716_114254](https://user-images.githubusercontent.com/76626474/179350568-249a17fa-dbc0-4c19-8cf5-e2eef3cb6a9d.jpg)

![IMG_20220716_121104](https://user-images.githubusercontent.com/76626474/179350580-d1419b5f-e237-4098-b6e5-44e4fe682906.jpg)

**Comment by MilosKozak** [comment]
![image](https://user-images.githubusercontent.com/11146458/179368590-3967f27b-0d5a-4545-8223-67209ebe4c43.png)
it works well even on Android12

**Comment by robertrub** [comment]
Probably it is due to the _MIUI 13_ overlayer on Android 12 of my XIAOMI POCO phone then :(
