### ISSUE TITLE
Master password reset DANA RS 

### ISSUE THREAD

**Issue by Hoost24** [nightscout/AndroidAPS#1916]
My master password (actually saved with password manager) did not work anymore when I tried to export current settings in order to update from 3.0.0.1 to 3.0.0.2. I followed the password reset guide and generally it looks as this worked fine (short after restart the password has been changed messaged popped up and the empty file in AAPS/extra is deleted).
However, calling preferences/general/advanced to change the master password returns "wrong password" when using the DANA S/N . Is there any special pw beside the S/N as printed on the pump and displayed in the DANA config?

**Comment by MilosKozak** [comment]
it's a bug in master version for RS pump. Password is empty after reset, not SN.
Will be fixed in upcomming version
