### ISSUE TITLE
Autotune is no longer selectable?

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#1919]
**AndroidAPS 3.1.0** (dev branch)
**Build**: bc2cd2c59
**Flavor**: Fullrelease, developer mode

**Problem description:**

Autotune is somehow "disabled"?
On upgrade, tab was removed. Option is still in config builder but is "unselecting" on selection

**Comment by vanelsberg** [comment]
@MilosKozak Reproduction should be easy.
If not, let me know. I'll add logfiles

**Comment by Philoul** [comment]
not on a released version (currently dev  build is 3.1.0 so master release ref).
Autotune is only available on dev with Engineering mode.

**Comment by vanelsberg** [comment]
@Philoul 
>  Autotune is only available on dev with Engineering mode.

Dev branch was just bumped to version 3.1.0 so yes, this is about latest dev commit.

**Comment by osodebailar** [comment]
@what is the reason to not make it available to the next master ?
Plug-ins like Autotune and the new Dynamic ISF are working perfect and very stable .

**Comment by 0xAalaoui** [comment]
Fixed by replacing this line https://github.com/nightscout/AndroidAPS/blob/dev/app/build.gradle#L108 with 

> version "3.1.0-dev"

**Comment by MilosKozak** [comment]
it's already changed to dev again
