### ISSUE TITLE
v3.1 can't select DynISF

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1922]
I can't select DynISF in v3.1. When I hit it, AAPS selects the OpenSMB AMA option.

![Screenshot_2022-07-19-17-03-55-735_info.nightscout.androidaps.png](https://user-images.githubusercontent.com/76626474/179896811-3238f129-7f1c-41b6-855c-bb9cd4dfc24f.png)

https://user-images.githubusercontent.com/76626474/179896862-d89cdd67-f5e6-48c4-b28d-645b6d08b341.mp4

**Comment by koelewij** [comment]
> I can't select DynISF in v3.1. When I hit it, AAPS selects the OpenSMB AMA option.
> 
> ![Screenshot_2022-07-19-17-03-55-735_info.nightscout.androidaps.png](https://user-images.githubusercontent.com/76626474/179896811-3238f129-7f1c-41b6-855c-bb9cd4dfc24f.png)
> 
>  Screenrecorder-2022-07-20-06-23-18-679.mp4

Having the same issue here.

**Comment by MilosKozak** [comment]
use dev branch. this is not included in master version
