### ISSUE TITLE
Dynamic ISF not activating

### ISSUE THREAD

**Issue by Rampiam** [nightscout/AndroidAPS#1925]
AAPS 3.1.0

After passing the new objectives when i select the Dynamic ISF the app goes back to the main screen and when i go to the preferences instead of Dynamic ISF it's selected the OpenAPS AMA.

I already resarted the phone and the issue didn't disappear.

**Comment by mick711** [comment]
I think you need to active engineering mode.

**Comment by Anubiso** [comment]
Hello, i have the same issue, i activate the dynamic ISF and then instead of the dynamic ISF the OpenAPS AMA is activated. The logs don't screem an obvious error. And the message of mick711 also does not help. Is there something i am missing? Thanks for feedback.
