### ISSUE TITLE
3.1: history browser charts menu without labels

### ISSUE THREAD

**Issue by justmara** [nightscout/AndroidAPS#1929]
Chart selector menu shown fine on overview, but has empty labels in History browser

![image](https://user-images.githubusercontent.com/4157587/179990376-43587b66-42e7-48ee-909c-e5738f2c6a2e.png)
![Screenshot_20220720-152747_NSClient](https://user-images.githubusercontent.com/4157587/179990727-656eaf5b-15ae-40d8-871b-52837f208beb.jpg)

**Comment by Rez3677** [comment]
Bro what's this? Can I make some cash? Teach me if it can pls tq

**Comment by osodebailar** [comment]
Can't reproduce it either in simulation nor on device

**Comment by MilosKozak** [comment]
I cannot reproduce too. Phone? Language?

**Comment by justmara** [comment]
I cathed it on my phone and in emulator with default (english) locale.

**Comment by vanelsberg** [comment]
Confirming for Samsung S22 Ultra, android 12
