### ISSUE TITLE
Autotune tab, selecting "Tune days" does not accept keyboard input

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#1932]
**AndroidAPS 3.1.0-dev-a**
**Build:** a857309ad
**Flavor:** Fullrelease, developer mode

**Problem description:**

Autotune tab, selecting "Tune days" does not accept keyboard input

Repro:
- Select Autotune tab
- Select "Tune days" input (keyboard input windows opens)
- Verify value can be changed using "+/-"
- Try entering a value through the keyboard

**Comment by Philoul** [comment]
Thanks for the report, I will analyse it (I can reproduce).
