### ISSUE TITLE
Unable to sync AAPS 3.1 with Sony Smartwatch 3

### ISSUE THREAD

**Issue by JimZam** [nightscout/AndroidAPS#1933]
Good night. My Sony Smartwatch 3 doesn't get data from AAPS once updated (the phone and the watch) to version 3.1. I have tried every single thing I can think of to make it work with no luck. If I downgrade to 3.0.2 (once again the phone and the watch) everything works fine. The app works in the watch and of course on the phone, but they don't sync. In AAPS it says "No watch connected" but I get notifications and data from xDrip+ and, as I said, if I downgrade it works again. I have read the logs but it's too much to me, I'm afraid I don't understand anything :-(
Any help is welcome.
Thank you in advance.

![SWR3](https://user-images.githubusercontent.com/23319786/180096556-f70c1251-2a17-4992-b528-949635a774cd.jpg)
![SWR1](https://user-images.githubusercontent.com/23319786/180096519-e4f2c9a0-8afc-4467-8440-74dad005dba5.jpg)

**Comment by MilosKozak** [comment]
show screenshot of version installed in watch

**Comment by JimZam** [comment]
Good morning. Here you are.
Thank you so much Milos.

![IMG_20220721_093054](https://user-images.githubusercontent.com/23319786/180156635-f582668e-6e10-428f-a506-24d0c06bc353.jpg)
![Screenshot_2022-07-21-09-35-14-135_info nightscout androidaps~2](https://user-images.githubusercontent.com/23319786/180156913-bacb2ef3-aea7-448e-9f5e-67d58103b2ef.jpg)

**Comment by MilosKozak** [comment]
watchface is 3.0.0.2

**Comment by JimZam** [comment]
Sorry, I have been trying so many builds I didn't remember which one was installed...
Here you are
![IMG_20220721_105539](https://user-images.githubusercontent.com/23319786/180173862-bf3dcf45-9cd7-4fe9-b3b6-451e1b779eda.jpg)
![IMG_20220721_105355](https://user-images.githubusercontent.com/23319786/180173874-5f5339da-6d9e-4d1d-9ee1-02fa7c588cf0.jpg)
![Screenshot_2022-07-21-10-58-31-490_info nightscout androidaps](https://user-images.githubusercontent.com/23319786/180174246-be33c43b-82d7-4bcc-82a7-267050f54b57.jpg)
![IMG_20220721_105929](https://user-images.githubusercontent.com/23319786/180174529-98af8eac-e026-4e55-9809-5780b4c5d24e.jpg)

**Comment by JimZam** [comment]
I'mafraid it is the same version, isn't it? Then version 3.1 gives me a black screen. I have two builds and probably one of them is 3.0.02, the one in the photos; the other one, 3.1, doesn't work at all :-(

**Comment by JimZam** [comment]
No way to make 3.1 work on the watch, it crashes or gives a black screen.
Sorry for the inconvenience and thanks for your help.
Kinzd regards
