### ISSUE TITLE
New connection form for accu chek

### ISSUE THREAD

**Issue by mordechi-david** [nightscout/AndroidAPS#1935]
I switched device I switched to pocket a new cubot device and tried to connect to the pump for a few hours without success finally after connecting via ruffy **and did not restart** but while connecting via ruffy I went out what andoidaps and re-entered and only then he managed to connect to users attention maybe need to check why so complicated Connect or add in documentation that there is another form of connection

**Comment by MilosKozak** [comment]
Combo was not designed for remote control at all. The way we are using is a hack and we can be thankfull to @jotomo that he was able to manage it. Switch to Dana, Insight etc. They have native support of remote control
