### ISSUE TITLE
[3.1.0] [master or dev] [minor] No Progress bar fillment on add insulin in virtual pump

### ISSUE THREAD

**Issue by rICTx-T1D** [nightscout/AndroidAPS#1955]
* Choose any virtual pump in configuration
* enter some insulin (without checkbox - only protocol )
* progress bar is comming and leave after some time,  but never filled
* why they coming at mdi?

**Comment by rICTx-T1D** [comment]
![Screenshot_20220712-082224_AndroidAPS](https://user-images.githubusercontent.com/8592414/180624896-9d42ad32-4ecf-4aab-8b8a-e2f0c60a9bab.jpg)

**Comment by MilosKozak** [comment]
resolved by https://github.com/nightscout/AndroidAPS/commit/3a87a95e323dd51998eae5e4d863d5d57cdd7a14
