### ISSUE TITLE
[3.1.0] [master or dev] Error "Wrong pump device" on virtual pump after restart

### ISSUE THREAD

**Issue by rICTx-T1D** [nightscout/AndroidAPS#1956]
* choose a virtual pump, subtype is unspecified 
* give some insulin or use calculator 
* quit the app by app-menu or android control panel or restart your phone 
* start aaps
* wait some times
* give some insulin or use calculator 
* the empty progress bar will show , #1955 
* error is present- Wrong pump device
* switch in configuration menu to a other physical pump and back to virtual pump 
* give insulin or use calculator 
* everything worked fine, until next app start

**Comment by rICTx-T1D** [comment]
![Screenshot_20220724-002734_AndroidAPS](https://user-images.githubusercontent.com/8592414/180624972-68035dd3-d40b-4cef-a691-1a2fedcea579.jpg)

**Comment by libxmike** [comment]
can report same issue on 3.1.02 (dev)

**Comment by mpessnegger** [comment]
can report the very same behaviour on 3.1.0.2 (fullrelease). i just press "dismiss" and the app works properly (Accu Check Combo, Decom G6

**Comment by rICTx-T1D** [comment]
Additional I will report, that when error message is shown,  the insulin injection was not save in database or nightscout. After switching pump driver to an other  and back, all working fine with saving the data.

**Comment by muthijammy** [comment]
Every restart of AAPS 3.1.0.2 reports the same error. Changing to virtual pump & then physical pump fixes till next restart. Not sure if it is impacting any other functionality. But error msg fills the screen and so graph1 on home screen is truncated on s9 plus mobile which has bigger screen compared to even more smaller mobile.

**Comment by VoronMods** [comment]
@Pallesauka @muthijammy and others, switching back and fort between pumps will do nothing, this is an issue in the Java Code, it is a bug. @MilosKozak any info on this issue/bug?

**Comment by muthijammy** [comment]
For everyone interested, I found following workaround suggested in fb works for me as well when error msg popsup:

choose a virtual pump, subtype is AAPS generic
Snooze popup error msg
Kill AAPS
Reopen AAPS. No error msg
Switch to needed pump. Error msg no longer popsup after restart of AAPS or mobile

**Comment by VoronMods** [comment]
> For everyone interested, I found following workaround suggested in fb works for me as well when error msg popsup:
> 
> choose a virtual pump, subtype is AAPS generic Snooze popup error msg Kill AAPS Reopen AAPS. No error msg Switch to needed pump. Error msg no longer popsup after restart of AAPS or mobile

its not about suppressing the error message, but about the error itself.
Your solution doesn't work, it's not a permanent solution, the error comes on the AAPS screen and comes from AAPS

**Comment by MilosKozak** [comment]
resolved by https://github.com/nightscout/AndroidAPS/commit/3f3cdde53bcff139515cf9cdfb9bb5dbd68a4ca2
