### ISSUE TITLE
[3.1] Danish language not available

### ISSUE THREAD

**Issue by zeppo33** [nightscout/AndroidAPS#1957]
![Screenshot_20220723-224228_AndroidAPS](https://user-images.githubusercontent.com/21089659/180633752-fb4fc9c7-33a3-417e-852b-a20ec38dcf55.jpg)
![Screenshot_20220724-073246_AndroidAPS](https://user-images.githubusercontent.com/21089659/180633765-0938f746-8967-473c-b318-8dd5e199c727.jpg)

**Comment by andyrozman** [comment]
Mhm. It seems that Danish is not enabled yet, but I can see some translations already there, so someone did some translations already... 
Maybe there is a reason this is not enabled? @MilosKozak any thoughts?

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/aa9543a0d2cd19a703f1731ba5f3f899b5b27240
