### ISSUE TITLE
Version 2.8.0 - pump reverted to set basal for 1.5 hours after cancelling loop suspension

### ISSUE THREAD

**Issue by tim2000s** [nightscout/AndroidAPS#196]
--------------
- After cancelling a loop suspension, the pump remained on pump basal rate for 1.5 hours and didn't suspend insulin once glucose levels started to drop. Incident occurred at 14.15. 
- Build and details in emailed log files. Version 2.8.0
-

**Comment by MilosKozak** [comment]
14.15 is missing in logs
but at 15:27 where log starts I still see that AAPS is not able to connect to pump. that's probably reason of your issue
