### ISSUE TITLE
3.1.0.2: Important info truncated in main screen

### ISSUE THREAD

**Issue by Arne1346** [nightscout/AndroidAPS#1960]
Hi,

with 3.1. some UI improvements have been applied. Unfortunately now a 6 inch phone (Xioami Mi A2) with a resolution 1080 x 2160 pixels is no longer able to display important information on the main screen due to truncation:

![signal-2022-07-24-134333_002](https://user-images.githubusercontent.com/72160775/180645623-0a009cf9-1d94-43f6-988d-3787d4509e65.png)

The red 1 in the middle of the line is the first digit of the remaining insulin units. At the moment the screenshot was taken it was 19 IU (which makes quite a different to 1 IU as displayed).

Can you rethink and enhance the new layout to make sure that all information can be displayed as before in 3.0?

thank you,
Arne

**Comment by Alamo04** [comment]
Confirmed
It's because the german translation is to long (Std) instead the english (h).

Solution for development: Don't translate this information and let it stay in english.

Solution for user: If needed, set AAPS language to english.

**Comment by cr582** [comment]
This issue is also seen in treatment tab among other locations. See also discussion and screenshots in #1394 (which was unfortunately and incomprehensibly closed).

**Comment by jgordon5** [comment]
I have the same problem with my Honor 50 5g. Sometimes it shows full information on home screen, at other times it's truncated. I put in the screen/pixel dimensions in Android Studio but it's still often truncated and doesn't show COB in full or IOB.

**Comment by MilosKozak** [comment]
> I have the same problem with my Honor 50 5g. Sometimes it shows full information on home screen, at other times it's truncated. I put in the screen/pixel dimensions in Android Studio but it's still often truncated and doesn't show COB in full or IOB.

screenshot?

**Comment by jgordon5** [comment]
I'll send it to you as soon as it does it again.
Jill Gordon

**Comment by jgordon5** [comment]
Hello
Here you are, the IOB is truncated and the sensitivity on the right hand
side.
Another screenshot shows insulin actually on board.

Best wishes
Jill

**Comment by jgordon5** [comment]
![Screenshot_20220805_195429](https://user-images.githubusercontent.com/38868358/183264281-96f527b1-f612-4014-8e7b-eb75f76def37.jpg)
![Screenshot_20220805_195415](https://user-images.githubusercontent.com/38868358/183264289-6ea9fec7-70ff-40f3-a0bb-23b21bf5e653.jpg)
Here are the screenshots - apologies for the delay. The first one shows what the IOB actually was. Quite often the amount of insulin in the reservoir only shows 1 figure when it should be showing 3.

**Comment by jgordon5** [comment]
Here are the screenshots - apologies for the delay. The first one shows what the IOB actually was. Quite often the amount of insulin in the reservoir only shows 1 figure when it should be showing 3.  Sorry tried to make them smaller but they ended up not being. Apologies.

![Screenshot_20220805_195429_edited](https://user-images.githubusercontent.com/38868358/183264555-e2c3716c-8e39-44db-9d10-924903ff69c0.jpg)
![Screenshot_20220805_195415_edited](https://user-images.githubusercontent.com/38868358/183264560-28713ea5-0c08-4204-9968-6ba4f009712c.jpg)
.

**Comment by MilosKozak** [comment]
this is not resolvable. you are using too large font on small display

**Comment by MilosKozak** [comment]
I updated all translation to one letter

**Comment by cr582** [comment]
and here's the same device in landscape mode
![Screenshot_20220809-150336_AndroidAPS](https://user-images.githubusercontent.com/62606176/183654063-0b2531c7-d83d-4995-a900-e8f28a454885.jpg)

**Comment by MilosKozak** [comment]
improved by https://github.com/nightscout/AndroidAPS/commit/c86edb94fd59ca1105a03296a565bf405d5d2636
