### ISSUE TITLE
Connection to galaxy watch 4 is not recognized by AAPS 3.1.0.2

### ISSUE THREAD

**Issue by avicorp** [nightscout/AndroidAPS#1962]
After update to 3.1.0.2 and re install of the wear app on Galaxy watch 4. AAPS not recognaize the connection to galaxy watch 4, the connection app is samsung wear and not google wear app.

In version 3.0.0.2 the app sends data to the watch but action from the watch didn't affect AAPS phone app.

The app was intalled on the watch using debuging via wifi.

![Screenshot_20220724-214555_AndroidAPS](https://user-images.githubusercontent.com/7301959/180661543-64d922d4-a4cb-44db-b367-c4adc3886c8e.jpg)
![Screenshot_20220724-214550_Galaxy Watch4 Manager](https://user-images.githubusercontent.com/7301959/180661544-10b9f1f5-f62c-4826-a034-e6eb7e904de3.jpg)
![Screenshot_20220724-213548_AndroidAPS](https://user-images.githubusercontent.com/7301959/180661545-4519d83b-72bf-4b64-90b6-42055f763d04.jpg)

**Comment by vanelsberg** [comment]
1. I assume, in general your Watch 4 is working as expected?
2. BT and WiFi are enabled on the watch?
3. Wear app version is of the same build as AAPS?
4. How did you install the AAPS wear app on your watch?

**Comment by vanelsberg** [comment]
Btw: just in case - Charge your phone, which should switch off phones battery saving mode and retry? ;-)

**Comment by avicorp** [comment]
Hi, 1. Yes 2. Yes 3. Yes 4. Run from the idea using abd debug via wifi.

I am after night of charge.

**Comment by andrewfaid** [comment]
Same issue on TicWatch - answers to the question are yes,yes,yes and run from AS console to physically connected (USB) watch

**Comment by vanelsberg** [comment]
Did you try uninstalling - then reinstalling the wear app?

(Running watch 4 myself on 3.1.02-dev-a. No problems)

**Comment by andrewfaid** [comment]
have reset watch and reinstalled twice

**Comment by avicorp** [comment]
> Did you try uninstalling - then reinstalling the wear app?
> 
> (Running watch 4 myself on 3.1.02-dev-a. No problems)

How do you connect the watch to the phone?
You use samsung wearable or wear os app?

**Comment by vanelsberg** [comment]
> How do you connect the watch to the phone? 
Using Samsung phone (Samsung Wear app) & Samsung Watch 4

**Comment by avicorp** [comment]
> > How do you connect the watch to the phone?
> 
> Using Samsung phone (Samsung Wear app) & Samsung Watch 4

3.1.02-dev-a version uses the old version for wear connectivity, i'm still trying to pin point the problem in the new version. I will be happy for more eyes on the issue.

**Comment by avicorp** [comment]
The watch app need to be sign in the same key like the app.
In case of installation using idea, debug process, you will need to set signingConfigs in "build.gradle" file of the wear.

**Comment by vanelsberg** [comment]
> The watch app need to be sign in the same key like the app.

Yes, preferably build both AAPS app and wear app from same commit.
Also can recommend installing the signed .APK using Wear Installer (from Google Store). It connects to the watch over WiFi (with adb debugging over WiFi enabled), copies the .apk and installs it. Works like a charm!

**Comment by gphilpott** [comment]
I have the same issue as the OP (using v3.1.0.3) with the Samsung Watch 4.

In my case the wear app uses the build variant of 'pumpcontrolRelease', using the same commit as the AAPS aps.
I transferred/installed to the watch using the freepoc.wearinstaller.

@avicorp can you confirm how you solved the issue? was it to rebuild using the commit referencing 3.1.02-dev-a?

**Comment by avicorp** [comment]
Did you build a signd apk?

**Comment by gphilpott** [comment]
> 

Thanks for the quick reply - yes, using the following steps:
(On the same commit as the build of the full app)
1. Run Android Studio / Build / Generate Signed Bundle or APK
2. (Leave settings as used for full app build i.e. same key store / pass)
3. Change Module to AndroidAPS.wear
4. Select Next, build variant 'pumpControlRelease'
5. Build, then transfer/install APK on to watch using the [org.freepoc.wearinstaller](https://play.google.com/store/apps/details?id=org.freepoc.wearinstaller) app

**Comment by gphilpott** [comment]
(FYI - based on your comment, I am re-tracing/double checking the installs and will report back later)

**Comment by avicorp** [comment]
Check it again, if that fail check the log file in the phone. 

Log file can be sent by mail in the maintenance section, you can fined it under the hamburger menu on the top left of the main screen.

**Comment by gphilpott** [comment]
Thanks, I think the issue is as you suspected - a signing issue.
Running jarsigner -verify on both apk's shows that whilst the watch apk is signed, the phone (full app) was not for some reason, which I am yet to solve.

**Comment by vanelsberg** [comment]
> 4. Select Next, build variant 'pumpControlRelease'

Why "pumpControlRelease"??
Just build for **fullRelease** (same goes for AAPS)

**Comment by gphilpott** [comment]
> > 4. Select Next, build variant 'pumpControlRelease'
> 
> Why "pumpControlRelease"?? Just build and sign for **fullRelease** (for both AAPS and wear app)

I was looking to start open looping, but allow remote control of the pump as per instructions here: https://androidaps.readthedocs.io/en/latest/Configuration/Watchfaces.html#building-wear-os-version-of-aaps

I have been able to get the watch connected thanks to both yours and @avicorp's suggestions - **thank you both!**.
I had to manually sign the main phone app using [apksigner](https://developer.android.com/studio/command-line/apksigner) and build the watch app using 'fullRelease' to get it to connect.
