### ISSUE TITLE
Wear app: Double tapping the "Digital Style" watchface graph area no longer changes graph resolution

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#1966]
**AndroidAPS**: 3.1.0.2-dev-a
**Build**: 0599E81
**Flavor**: Fullrelease, developer mode

**Problem:**
Double tapping the Wear App "Digital Style" watchface area no longer changes graph resolution.

*Additional info*:

- Running AAPS and Wear app from same build (latest dev)
- Graph resolution can be change through settings as usual

**Comment by rICTx-T1D** [comment]
Tap double on time digests.

**Comment by vanelsberg** [comment]
> Please try to tap double on time digests. Sometimes you need one or two additional taps to activate your interactive mode from wearOS. My Fossil Carlyle need 4 taps to switch first time and double tap to switch to next.

1. On Watch 4 tapping work reliable always. 2 taps just (used to) works
2. Tap area is/was graph area
3. Resolution does not change by any tapping

**Comment by rICTx-T1D** [comment]
When I tap multiple times on weekday name, the scale is changing.  Yes the tap area is moved incorrectly. 

Can you confirm the scale-change?

**Comment by vanelsberg** [comment]
Nope!

**Comment by vanelsberg** [comment]
> When I tap multiple times on weekday name, the scale is changing...
> ... the **tap area is moved** incorrectly.

(I checked again) Yes - you are absolutely right!

**Comment by rICTx-T1D** [comment]
@vanelsberg Can you modify the headline of this issue? Tapping-Zone is incorrect placed.

**Comment by vanelsberg** [comment]
I'd rather leave it like it is. Because that is the actual UI experience (caused by "Tapping-Zone is incorrect placed")

Analyzing actual problem and solving is to the devs to decide.
Comments here do point in that direction so solving should not be a problem ;-)
