### ISSUE TITLE
[3.1.0.2] problems on small displays with new abbreviation for „days“ and „hours“ 

### ISSUE THREAD

**Issue by fezulin** [nightscout/AndroidAPS#1973]
AndroidAPS 3.1.0.2 (compared in pictures with AAPS 3.0.0)
Used mobile: Pixel 4, Display 2280 x 1080 Pixel

Using a language specific abbreviation for „days“ and „hours“ seems to cause trouble in GUI on mobiles with small displays, if the new abbreviation has more then one letter. 

Picture 1: If pump is disconnected for 2 hours (TWO hours!), in 3.1.0.2 the GUI shows just 1(!) hour, minutes cannot be displayed. 

Picture 2: The „U“ for „untis“ cannot be displayed. I agree: It is not hard to guess, what is meant. ;o) 

Picture 1: 
![Picture1](https://user-images.githubusercontent.com/16593716/181742166-45ba63c2-6016-4a25-af93-fad4e961cabf.png)

Picture 2:
![Picture2](https://user-images.githubusercontent.com/16593716/181742194-ff9e1d9b-3f44-4884-bde6-eae37c77af69.png)

**Comment by maheini** [comment]
Same here. Mostly a problem caused by the translation, which isn't really a short version in German. I don't have a very small screen (1080 x 2160 wide) but still faced the missing numbers.

**Comment by OFlannigan** [comment]
Can also confirm, though not on a small screen. See also issue #1960. For short term solving, I switched the language to english.

**Comment by fezulin** [comment]
So this issue (#1973) might be closed, as it is a duplicate to #1960.
Sorry - I did not see #1960, when I posted this issue.
