### ISSUE TITLE
UI: screen rotation fails in historybrowser

### ISSUE THREAD

**Issue by justmara** [nightscout/AndroidAPS#1979]
Samsung s20+, Android 12. Aaps 3.1.0.2 built from master.
This is how history browser looks like in normsl mode:
![Screenshot_20220731-143221_NSClient](https://user-images.githubusercontent.com/4157587/182024346-d1f5e72f-0bf8-4106-b184-28fe202321df.jpg)

This is what happens after rotating phone horizontally to panoram mode:
![Screenshot_20220731-143241_NSClient](https://user-images.githubusercontent.com/4157587/182024387-b9a1f829-d6ef-45d8-89f7-d916967c1cd4.jpg)

Main graph missing, menu arrow too. And there is no scroller so even cannot slide screen up/down.

If you try switching between time intervals (6/12/18/24) data is loaded, bu still only part of screen is visible
![Screenshot_20220731-143846_NSClient](https://user-images.githubusercontent.com/4157587/182024536-462857a4-266d-4c9a-8e16-56ac36114471.jpg)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/b0cc056b41e6f508e63a6bc9079114e5a050fcb7
