### ISSUE TITLE
Data transport from AAPS to xDrip work only if NS Client is enabled.

### ISSUE THREAD

**Issue by libxmike** [nightscout/AndroidAPS#1983]
NS Client is a problem as it drains too much battery and runs every 30 sec. xDrip on the other side uses just 1% over 24h.
This did work awhile ago on older AAPS/NS Client version, now xDrip gets treatments/basal in the charts and for upload ONLY if NS is enabled.
Same issue 3.1.0.2 and Dev version.

**Comment by MilosKozak** [comment]
well yes. this was designed in the beginning of AAPS as broadcasting of data coming from NS to save double traffic between phone and NS, not AAPS <-> xdrip sync service. Thus it works like expected
