### ISSUE TITLE
App freezing on 3.1.0.2

### ISSUE THREAD

**Issue by yhonatanb20** [nightscout/AndroidAPS#1988]
Had an app freezing on 3.1.0.2, thought it should have been fixed: when tapping on aaps icon, got white screen with aaps logo for 5 seconds, than this screen closed, on second tap app lunched and "aaps started" note now displayed on graph
![image](https://user-images.githubusercontent.com/93551840/182921951-a64150fb-665a-45e2-b968-ab04caa207be.png)

**Comment by Andries-Smit** [comment]
@yhonatanb20 thanks for reporting the issue. Could you please add the log files so the issue could be investigated.

**Comment by yhonatanb20** [comment]
[AndroidAPS._2022-08-04_21-11-54_.1.zip](https://github.com/nightscout/AndroidAPS/files/9262709/AndroidAPS._2022-08-04_21-11-54_.1.zip)
[AndroidAPS._2022-08-04_21-11-54_.0.zip](https://github.com/nightscout/AndroidAPS/files/9262710/AndroidAPS._2022-08-04_21-11-54_.0.zip)
Here are all the files under the directory aaps/logs/info.nightscout.androidaps with date and time corresponding for the issue. Hope that's what you meant?

**Comment by MilosKozak** [comment]
it's impossible to find anything in logs without exact knowledge what to look for. When this happen again open new isse with time, logs etc, exactly like described in issue template
