### ISSUE TITLE
Minor / UI / IOB total while bolus injection

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1989]
Nothing really important but... When we start a bolus, the IOB on the background shows the IOB including the bolus that is being injected (before it is injected completely).

![IMG_20220804_192916.jpg](https://user-images.githubusercontent.com/76626474/182942695-a83cd0a1-4eb0-4408-a48f-5baf229f3872.jpg)

If we stop the bolus in the middle, the IOB is changed and the correct IOB is shown. Thus it is not a "bug".

It would be better if the IOB on the UI was updated when the bolus is finished (or stopped).

**Comment by MilosKozak** [comment]
that's how some drivers work (MDT, Omni)
