### ISSUE TITLE
Feature request: display profile timeshift under star

### ISSUE THREAD

**Issue by yhonatanb20** [nightscout/AndroidAPS#1993]
When making profile change with percentage different than 100%, the percentage is displayed under the star icon on the graph (i.e. star 130%). But when making a profile shift that includes only timeshift, just the star is diplayed, as if profile was just set to 100%. Could you do that in such cases the timeshift would be displayed below the star (i.e. star 2h or if profile percentage different than 100% than i.e. star 130%, 2h)?
BTW, thanks a lot for the star design, huge upgrade from the previous way of displaying profile change which just messed up the graph.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/2a93e059b1658ea0487da33eb496d02163370e26
