### ISSUE TITLE
Autosens freezing / failing to update - 3.1.0.2 

### ISSUE THREAD

**Issue by BeFlatLine** [nightscout/AndroidAPS#1995]
Version 3.1.0.2 and 3.1.0.3. Was not occurring on 3.0

Time of issue: 12:36 PM roughly. 

Desceiption: Autosens appears to freeze its update sporadically since updating from 3.0 to 3.1.0.2.  The Grey dot of starting AndroidAPS is from me troubleshooting the issue when it occurred previously. Issue appears to resolve itself with next blood sugar update, but is happening sporadically. 

NOTE: I changed profiles to a lesser profile because I've been more sensitive than normal to insukin lately. My body has swings where I'll need 10 - 20% more insulin for a day or two, but the past 2 days have been the opposite (where I've needed less insulin than usual). Not sure if that is playing an impact. 

![Screenshot_20220807-123628_Nova7](https://user-images.githubusercontent.com/77511567/183302514-b3264f04-5c86-4865-b5e4-3d6c88efc45d.jpg)
![Screenshot_20220807-123914_AndroidAPS](https://user-images.githubusercontent.com/77511567/183302522-271d1c6d-eb3c-4328-a724-ccdce409bc46.jpg)
![Screenshot_20220807-123847_AndroidAPS](https://user-images.githubusercontent.com/77511567/183302523-e8e8b227-7868-40aa-92b3-a47a1dc8d1f2.jpg)
![Screenshot_20220807-123852_AndroidAPS](https://user-images.githubusercontent.com/77511567/183302524-e89f4885-b119-444a-a967-48a87bae755f.jpg)
![Screenshot_20220807-124021_AndroidAPS](https://user-images.githubusercontent.com/77511567/183302527-881e16e7-8aa4-47d6-b3d8-fe676df86f1a.jpg)

**Comment by BeFlatLine** [comment]
[AndroidAPS_LOG_1659891342672.log.zip](https://github.com/nightscout/AndroidAPS/files/9277193/AndroidAPS_LOG_1659891342672.log.zip)
Adding the log file.

**Comment by BeFlatLine** [comment]
Updated to 3.1.0.3 and issue is still occurring. 
![Screenshot_20220811-195938_AndroidAPS](https://user-images.githubusercontent.com/77511567/184261732-60b68a4e-38ae-42e3-b5ed-791c3e28c474.jpg)

**Comment by MilosKozak** [comment]
improved by caching last autosens value in dev already
