### ISSUE TITLE
[2.7.0] [graphical/UI] Scaling of additional graph may need improvement

### ISSUE THREAD

**Issue by goomStar** [nightscout/AndroidAPS#2]
Reposting from https://github.com/MilosKozak/AndroidAPS/issues/2980#issue-708285027

Btw, master build via github/nightscout appears as '2.7.0-dev' in about-section
_//edit: this part above is solved/explained by first comment_

The scaling of fresh additional graphs seem to depend on the first data source selected. For full graph functionality a pre-check before drawing would be required, to find the optimal scaling.

Example/Reproduction:
Create an empty graph and use COB and DEV as data. As COB is the first source, the graph will use a fixed scaling with positive numbers only, even though DEV would need negative values.
It also affects the deviation-slope in negative area. They always work stand-alone, but in combination with COB as first source, the graph is not optimized.
When no COBs are found to be displayed for the chosen timeframe, the graph stays blank completely (like in the picture).

![Screenshot_20200918-093107_AndroidAPS](https://user-images.githubusercontent.com/38337079/94180385-37a3f000-fe9e-11ea-9e0b-203ac25edd55.png)

**Comment by dlvoy** [comment]
`-dev` suffix is only at *tag* 2.7.0, master branch (one commit later) have it fixed

**Comment by goomStar** [comment]
Not fixable at current state.
