### ISSUE TITLE
Last 3103.devA kills connection to DASH 

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2002]
@MilosKozak The latest dev build killed things. For DASH, no more pod history (shows a blank page and then slows the AAPS UI). No more beep the pod, nor connect to pod.
![Screenshot_2022-08-10-13-42-33-738_info.nightscout.androidaps.png](https://user-images.githubusercontent.com/76626474/183896256-a9f0cc2c-40e7-4b65-a7be-164917c9a165.png)

Reinstalling the older devA gets back the pod connection but losts selected profile, BG history etc.

Here is the log. Look around and before 13:55

![AndroidAPS_LOG_1660132552797.log.zip](https://github.com/nightscout/AndroidAPS/files/9299796/AndroidAPS_LOG_1660132552797.log.zip)

**Comment by robertrub** [comment]
Help !!! I downgraded to 

![Screenshot_2022-08-10-14-11-50-847_info.nightscout.androidaps.png](https://user-images.githubusercontent.com/76626474/183899629-d857a4e2-027d-4aee-b37a-214264c970c4.png)

but COB stays at 0 whatever I do (enter carbs via wizard or manually)

![Screenshot_2022-08-10-14-16-35-499_info.nightscout.androidaps.png](https://user-images.githubusercontent.com/76626474/183899758-6d7bdad0-6218-477d-a230-a885bd232039.png)

**Comment by MilosKozak** [comment]
it seems db update is not handled properly ..... i'll check on my phone

**Comment by elgrupo123** [comment]
Here is a similar problem. The connection to the Dash is there, but no bolus delivery possible
![PXL_20220810_154817569](https://user-images.githubusercontent.com/92778761/183959701-aa6aa507-673f-4265-a2fc-c546e9c3f5a5.jpg)
![PXL_20220810_154834266](https://user-images.githubusercontent.com/92778761/183959712-d4899d69-5c26-43fa-969c-4c33acc5c870.jpg)
.

**Comment by MilosKozak** [comment]
unable to replicate this issue.
But PR 1999 is removed now

**Comment by robertrub** [comment]
I updated from this dev

![Screenshot_2022-08-10-14-11-50-847_info nightscout androidaps](https://user-images.githubusercontent.com/76626474/184072090-ac1d9db5-33cc-4d1e-95e1-94dc09e1ca2b.png)

to this dev

![Screenshot_2022-08-10-13-42-33-738_info nightscout androidaps](https://user-images.githubusercontent.com/76626474/184072165-f3d144bb-b4f7-4f54-a2b1-1aa52e443d05.png)

I don't know if it is important or not.

**Comment by philipgo** [comment]
Same problem here, Pod is connected but Basal cannot be set.

I received this message when trying to connect a new pod:![image](https://user-images.githubusercontent.com/29184757/184217096-83ad3cfb-7ea0-4bf0-a9be-77238a5a2b57.jpeg)

**Comment by Philoul** [comment]
@MilosKozak Unfortunatly I have updated my PR #529 with dev branch including #1999 to resolve conflicts with insight Driver in kt and Notes update...
What's the best way to fix it ? close PR and make a new one (I don't know how to make a hard reset (on commit) on a remote branch...) ?

**Comment by robertrub** [comment]
@MilosKozak VERY strange. After the incident, I installed an older 3103dev A then installed MASTER 3103 and have been using master since. Since 0h today, I got my stats partially back (see number of days  insulin stats vs BG stats) 

![IMG_20220813_003814.jpg](https://user-images.githubusercontent.com/76626474/184453868-b3c461c9-250c-4474-9bb5-00bc302e96ff.jpg)

But the BG stats for the last 2 days are wrong, I was definitely NOT 100% yesterday...)

![Screenshot_2022-08-13-00-41-19-848_info.nightscout.androidaps.png](https://user-images.githubusercontent.com/76626474/184453956-a15d90be-5c27-4e9b-825f-52d9fac1fb8f.png)

**Comment by robertrub** [comment]
Seems that the stats got solved by themselves.

![Screenshot_2022-08-14-12-34-40-670_info.nightscout.androidaps.png](https://user-images.githubusercontent.com/76626474/184533038-61d3e71c-3eee-4afc-8a12-784e6226a9d2.png)
