### ISSUE TITLE
3.1.0.3: profile shift from nsclient fails

### ISSUE THREAD

**Issue by justmara** [nightscout/AndroidAPS#2009]
this is result of profile shift FROM nsclient app `+1h` for `2h30m`
![Screenshot_20220811-212131_NSClient](https://user-images.githubusercontent.com/4157587/184211414-6498355c-5439-4b10-8323-6a761d9ee3f2.jpg)

this is profile shift `-1h`
![Screenshot_20220811-211425_NSClient](https://user-images.githubusercontent.com/4157587/184211428-4342fdad-ad2a-42bb-ab48-3eef33b674f0.jpg)

**Comment by justmara** [comment]
updated to 3.1.0.3 and it works fine, sorry :)

**Comment by justmara** [comment]
Re-tested only to find than it fails when switched from nsclient.
This is how it is set on nsclient 3.1.0.3:
<img width="263" alt="image" src="https://user-images.githubusercontent.com/4157587/184592950-3a931c9b-fd48-481c-873c-4d51a8994bbd.png">

This is how this event is received from NS by main AAPS
<img width="238" alt="image" src="https://user-images.githubusercontent.com/4157587/184593167-1f53ff61-e344-4574-8883-c9943b40eccc.png">
seen in treatments
<img width="299" alt="image" src="https://user-images.githubusercontent.com/4157587/184593235-d7f78a5e-8f29-4e02-860c-4232063cb91c.png">
applied in AAPS
<img width="300" alt="image" src="https://user-images.githubusercontent.com/4157587/184593295-02a51cc5-3931-4faf-9a91-f7b403280e62.png">

Exactly same settings set from AAPS itself works fine

**Comment by justmara** [comment]
Both these events in NS. Seems that it is sent to NS with wrong timing 

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/4157587/184593548-fa6bdbe6-6590-41f9-93fa-10ca4510e775.png">

**Comment by MilosKozak** [comment]
hopefully fixed by https://github.com/nightscout/AndroidAPS/commit/f7951ec6141b3584790bc88bebe66527a7053b0e
