### ISSUE TITLE
Master 3103 / Treatments menu / careportal / 3 dot menu not clear

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2012]
![Screenshot_20220813-162554_AndroidAPS-1.jpg](https://user-images.githubusercontent.com/76626474/184526523-2cb6d8d7-cd90-413f-a20a-7190c35093e0.jpg)

Not very clear what this option does...

**Comment by Andries-Smit** [comment]
It remove start events from the log.
Is your suggestion to rename it? (Sugestions are welecome)
 Or should it be better documented?

**Comment by robertrub** [comment]
Ok, tnx. You don't have too much space for a better text :(

_Delete "AAPS started" entries_

Would be great if it is not too long. If it is too long, without the _entries_ word but keep the quotes.

**Comment by Andries-Smit** [comment]
Good suggestion, it is more descriptive

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/551c927495224a7e0622252cc3282696d4613a37
