### ISSUE TITLE
[Boost 3.1.0.2] Main Bildshirm zustand Insulin Füllung der Pumpe und Ladezustand OL-Pro Baterien fehlt

### ISSUE THREAD

**Issue by Thomas-Wolff** [nightscout/AndroidAPS#2013]
After updating to Boost 3.1.0.2, the insulin fill status of the pump (OmniPod eros) and the battery charge status of the OL Pro are always missing from the main screen.
In very few cases it is displayed, and disappears after a short time again.

Many greetings Thomas

![Bild1](https://user-images.githubusercontent.com/59526802/184530186-f9662e40-6934-4288-8878-2a27c463f725.jpg)

![Bild2](https://user-images.githubusercontent.com/59526802/184530204-d80418f8-6be9-4152-bd07-fb40bc7ebda3.jpg)

**Comment by Andries-Smit** [comment]
Is this issue also accire when you switch to English?
If it only in German it is related to issue #1960

**Comment by cr582** [comment]
this is independent from the used language (as described in #1960 ) . The information disappears in german as well as in english and has been reported in #1960
