### ISSUE TITLE
Dash issue. f7951ec

### ISSUE THREAD

**Issue by elgrupo123** [nightscout/AndroidAPS#2016]
Same issues with the Dash as before. No bolus delivery possible. Build f7951ec
![PXL_20220815_175939683](https://user-images.githubusercontent.com/92778761/184697285-5da1b04b-1b13-45b8-9f3c-868611c68e5d.jpg)

![PXL_20220815_180106362](https://user-images.githubusercontent.com/92778761/184697301-ecc15af3-0161-4ddd-908c-8d4126db9441.jpg)

The older version - works fine!
![Screenshot_20220815-204647](https://user-images.githubusercontent.com/92778761/184697570-5156c5e1-f5fd-4c36-8994-d6b1912695b5.png)

**Comment by mick711** [comment]
Same issue go back to old dev

**Comment by vanelsberg** [comment]
@justmara Tnx!!!
Will see if I can test this...

**Comment by MilosKozak** [comment]
reverted
