### ISSUE TITLE
Using Nsclient results in duplicate profileswitch events in NS and in AAPS

### ISSUE THREAD

**Issue by wootmasterslick** [nightscout/AndroidAPS#2030]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused the problem

18 aug 2022 23:22

Upon enabling nsclient the already present profileswitch events become duplicated and are the uploaded to NS.
Sometimes numerous copies form and impact functioning of the app.
Only the profileswitches are affected. They are flooding the NS and AAPS with useless information and making the app less responsive. The times are sometimes also varying so that affects any autotune calculations one might do.
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).

3.1.0.3

Pump accu Check Insight

- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/Usage/Accessing-logfiles.html

log files are coming asap

- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

done

Screenshots:

![](https://cdn.discordapp.com/attachments/629952669967974410/1009954497822466138/16E5D9EC-9D2C-404B-97BF-20121F05DD18.jpg)

![](https://cdn.discordapp.com/attachments/629952669967974410/1010142059996381184/IMG_8624.jpg)

![](https://cdn.discordapp.com/attachments/629952669967974410/1010154801931227197/Screenshot_2022-08-19-13-53-20-751_info.nightscout.androidaps.jpg)

![](https://cdn.discordapp.com/attachments/629952669967974410/1010158307807334451/Screenshot_2022-08-19-14-07-11-012_info.nightscout.androidaps.jpg)

Discussion:
https://discord.com/channels/629952586895851530/629952669967974410/1009953469127458896

**Comment by Philoul** [comment]
No impact on Autotune calculation done with AAPS plugin: for each BG value, Autotune use the active profile got from database to calculate basal rate (and associated IOB, Activity...)

**Comment by wootmasterslick** [comment]
> No impact on Autotune calculation done with AAPS plugin: for each BG value, Autotune use the active profile got from database to calculate basal rate (and associated IOB, Activity...)

Do you not agree it is an issue?

**Comment by Philoul** [comment]
I think having 3 or more lines for each profile switch is an issue, we should have only 2 lines (one line for the request, and a second line for the profile switch done into the pump).
But even if there is a bug, there is no impact on Autotune calculation (cf comment below in Issue's description)
> The times are sometimes also varying so that affects any autotune calculations one might do.

**Comment by MilosKozak** [comment]
this should be resolved in AAPS dev and NS 14.2.6
