### ISSUE TITLE
[3.1.0.3] AAPS uploads ecarbs (carbs spread over time) to NS as one time event 

### ISSUE THREAD

**Issue by nlof** [nightscout/AndroidAPS#2031]
I inputed 12 grams of carbs spread over one hour starting 11:37  at around 10:45. In NS it showed up as one bolus of 12 grams. I thought I made a mistake, I deleted it in AAPS, NS and Xdrip and entered it again around 11:08 (see last screenshot) but the results were similar. 

Before this bug, AAPS would create 4 treatments at 15 minute intervals of 3 grams each. It still shows up as such in AAPS but not in the treatments tab, nor on NS.

AAPS [3.1.0.3] 

[AndroidAPS._2022-08-20_09-54-44_.4.zip](https://github.com/nightscout/AndroidAPS/files/9386698/AndroidAPS._2022-08-20_09-54-44_.4.zip)

![Screenshot_2022-08-20-11-09-04-28](https://user-images.githubusercontent.com/70835405/185738760-0ed908c5-c26b-4a1f-8380-12b0658308c3.jpg)
![Screenshot_2022-08-20-11-09-14-80](https://user-images.githubusercontent.com/70835405/185738763-d447dc4b-e9a2-4eef-90f5-d32d1f451384.jpg)
![Screenshot_2022-08-20-11-09-26-88](https://user-images.githubusercontent.com/70835405/185738765-b25b402b-fe32-46c0-b5f5-c0b1726982f2.jpg) 
![Screenshot_2022-08-20-12-52-43-79](https://user-images.githubusercontent.com/70835405/185740353-b4bb8048-7b92-40eb-8869-13b85c98872b.jpg)
![Screenshot_2022-08-20-13-10-15-83](https://user-images.githubusercontent.com/70835405/185741111-bcc92950-3074-4387-a000-a0c76887bcae.jpg)

**Comment by MilosKozak** [comment]
eCarbs are one record with duration in new DB model. NS/xDrip/... must learn this first
AAPS and NSClient understant it.
