### ISSUE TITLE
[3.1.0.3] Future insulin activity projection line disappears

### ISSUE THREAD

**Issue by nlof** [nightscout/AndroidAPS#2032]
It happens recurrently, I just saw it again at 13:58 today. The yellow insulin projection line into the future disappears sometimes. Didn't use to happen with v. 2.8.2.1. It's a dashed line and most of the time it appears normally on 3.1.0.3 as well.

It may have to do with existing text from treatments around that area? (but not sure).
Logs and 2 screenshots attached.

UPDATE:to be more exact, the dashed insulin projection line stops at the next round hour line. See comments below.

[AndroidAPS._2022-08-20_12-52-10_.5.zip](https://github.com/nightscout/AndroidAPS/files/9386929/AndroidAPS._2022-08-20_12-52-10_.5.zip)
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/9386930/AndroidAPS.log)
![Screenshot_2022-08-20-13-58-07-90](https://user-images.githubusercontent.com/70835405/185743092-6452fcd2-86ce-4b52-ad44-3ced93ce1516.jpg)
![Screenshot_2022-08-20-14-04-14-38](https://user-images.githubusercontent.com/70835405/185743095-f0821179-867e-4115-81c1-c71e1b907c28.jpg)

**Comment by nlof** [comment]
And it partially reappeared a few minutes later.

[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/9386956/AndroidAPS.log)

![Screenshot_2022-08-20-14-11-59-01](https://user-images.githubusercontent.com/70835405/185743454-e79998b5-17f3-4465-9568-0d73783878b1.jpg)
![Screenshot_2022-08-20-14-13-50-00 (https://user-images.githubusercontent.com/70835405/185743455-8efdc564-6f02-4cb4-89b3-02922d08b6cf.jpg)

**Comment by Philoul** [comment]
I think you only have only forecast for activity until. the next hour in future.
If you are just before a new hour (13h58) or graph is still not fully updated (14h04), you don't see the forecast activity, and a bit later, you see it up to next hour (15h in your screenshots)...

**Comment by nlof** [comment]
You're absolutely correct, I followed this for a while and reached the same conclusion. 
It's still a bug, there's no reason for the graph to stop at the next round hour: it works fine on v 2.8.2.1, I'll post a screenshot.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/1f1a2eae48564779a9f88363749f6d58fa8441f1
