### ISSUE TITLE
MINOR / Watchface not centered

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2034]
@Andries-Smit On my Fossil gen 5 watch, this AAPS face is not centered and with larger numbers (20 and over) for the hour, one part of the number is cut off. You can see that one part of the 2 is cut off on my capture.

The same face from xDrip is centered.

![IMG_20220821_153340.jpg](https://user-images.githubusercontent.com/76626474/185793575-0f69844b-e116-4a75-affa-409d6c481080.jpg)

**Comment by robertrub** [comment]
Feature request : Same watchface in xDrip has the date also ;)
The date is often missing from AAPS faces (I didn't test them all ...)

**Comment by Andries-Smit** [comment]
Most watch faces where designed for square watches. Some of the round watches are an afterthought.
I'll review them to see if I can fix it. Though making it scale across all shapes and size a lot of work

**Comment by rICTx-T1D** [comment]
Fossil smartwatch's re-positon the watchface each minute and protect the watch for burn-in effects.  When you going in active mode, all is centered correctly on my Fossil  carlyle (Gen5).

**Comment by robertrub** [comment]
That's not the case on my Fossil. Other AAPS and xDrip faces are centered and don't move either.
