### ISSUE TITLE
MINOR / AAPS language change 

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2035]
Not sure if this was issued before. If I set AAPS language to English, the UI is in English. If I set it the to French, the UI is in French (phone language is French).

But, if I set it to English then set it to Phone default, the UI stays in English. The main page graphs has the French definitions but that's all.

**Comment by Andries-Smit** [comment]
It recommended to restart AAPS after language change.

**Comment by robertrub** [comment]
Ok. Is it possible to show a message after language change "Please restart AAPS" ? 

OTOH, language is something most people will never change.

**Comment by MilosKozak** [comment]
latest dev seems to behave correctly
