### ISSUE TITLE
Autosens / Weighted Average - Sensitivity stuck / not resetting to 100% with COB

### ISSUE THREAD

**Issue by janvitos** [nightscout/AndroidAPS#2044]
Hi,

Today, I noticed something odd about Autosens / Weighted Average and I think it might be due to a bug.

This afternoon, my son’s insulin sensitivity went up from 100% to 120% (see screenshot below) and Autosens adjusted its multiplier to 1.2 accordingly, as seen under “Script debug.” I could also see other altered values like ISF, which had been lowered to 120 from 144.

A bit later, my son started playing outside and became much more sensitive to insulin, but Autosens remained at 120%. Again, I noticed the Autosens multiplier was still at 1.2 and other values were still altered.

We were having a bit of a hard time getting him out of hypo, and I suspect Autosens might’ve been partly to blame since it was stuck at 120% even while his sensitivity was clearly much lower.

I then decided to test Sensitivity Oref1 to see if the behaviour was the same or different. As I thought, Sensitivity Oref1 reverted back to 100% when there were COB, which confirms there's most likely a bug in the Sensitivity Weighted Average plugin.

![300060707_1591471957913386_7685569438247279754_n](https://user-images.githubusercontent.com/10037804/186537110-886f0b4d-3fdc-4ad9-892d-20f478bc1794.jpg)

**Comment by justmara** [comment]
Read the docs: 

> If continuously eating carbs over an extended period, autosens will be less effective during that period as carbs are excluded from BG delta calculations.

**Comment by janvitos** [comment]
> Read the docs

I did read, and re-read the docs.

I truly believe there is a bug here.

**Comment by justmara** [comment]
It always were acting like this - sticking with latest calculated value until new one CAN be calculated. While COB>0 it has no new data, so new calculations cannot be done -> no sensitivity update.

**Comment by janvitos** [comment]
> It always were acting like this - sticking with latest calculated value until new one CAN be calculated

So why is Oref1 resetting to 100% when COB kick in? Shouldn't Weighted Average and Oref1 have the same behaviour regarding COB?

**Comment by nlof** [comment]
Weird, I didn't pay attention to such an issue.
I just checked in the recent graph and if you look at the red marked area, despite having COB, the white autosens (sensitivity) line is decreasing... 
I've been running the weighted average option with a timeframe of 4 hous for a year now....
Yes, sometimes it's somewhat slow to catch up with the decrease, but it's the nature of the beast...

![Screenshot_2022-08-28-14-15-39-04~2](https://user-images.githubusercontent.com/70835405/187071573-2e1f1d6b-9cc3-45eb-9c9b-d24719df9e1d.jpg)

**Comment by janvitos** [comment]
I'm going to close this as different people seem to have different results.

**Comment by nlof** [comment]
Unsure whether you should rush and close it, I just don't remember seeing this for sure. It's worth continuing to monitor it as it is possible that sensitivity doesn't decrease in real time but maybe it's recalculated later? I don't know for sure, I'll try to watch it in real time if I remember 🙂

**Comment by nlof** [comment]
Yesterday again sensitivity changed with COB (both down and up, see screenshot), but again, not sure i remember if it happened in real time. Probably yes, but unsure.
![IMG_20220829_090738](https://user-images.githubusercontent.com/70835405/187134215-d372c7a7-1b9f-430a-afd4-bc9887868ad0.jpg)
