### ISSUE TITLE
[3.1.0.3-dev-a]: Using the AMA algorithm, SMB is activated without changes in configuration

### ISSUE THREAD

**Issue by fjpezuela** [nightscout/AndroidAPS#2049]
ADD TIME OF EVENT HERE: 21:59
ADD ISSUE DESCRIPTION OR GITHUB ISSUE REFERENCE NUMBER:

I' using the AMA algorithm. After using it for a little less than a day at some point without making any changes to the configuration, SMB starts to appear. The SMB algorithm is added to the menu (both AMA and SMB appear). Since the problem occurs, SMB is already working. In the settings, the two algorithm options are marked (manually only one can be selected). If I change it manually it "works" again only with that algorithm, until some time passes and it happens again.

My impression is that it doesn't really work SMB, but Dynamic ISF, since according to my SMB configuration, I have 60 minutes with COB for microbolus and some fixes are quite bigger than that.

AndroidAPS 3.1.0.3-dev-a
Build: d87ab2d8a5-2022.08.23-17:27
Remote: https://github.com/nightscout/AndroidAPS
Flavor: fullrelease
Versión de Nightscout: 14.2.5
[AndroidAPS_LOG_1661502851159.log.zip](https://github.com/nightscout/AndroidAPS/files/9431622/AndroidAPS_LOG_1661502851159.log.zip)

Modo de ingeniería activado
<img width="187" alt="image" src="https://user-images.githubusercontent.com/67511778/186866397-b523a30d-f5fa-41cb-96b9-e1cebd9c88c1.png">
<img width="187" alt="image" src="https://user-images.githubusercontent.com/67511778/186866522-a7456899-18c6-4944-8064-9eca288a4c01.png">
<img width="187" alt="image" src="https://user-images.githubusercontent.com/67511778/186866651-3e97b177-5500-48ca-b601-4f5889eef8bb.png">
<img width="204" alt="image" src="https://user-images.githubusercontent.com/67511778/186866749-c9196177-9ac9-48e4-84b7-698b03960447.png">

**Comment by MilosKozak** [comment]
i can confirm SMB was enabled (AMA not executing) but the reason is not visible from logs, the system was mulctioning anyway (periodid NS reconnections ...)
