### ISSUE TITLE
No active Omnipod DASH after update from 3.0.0. to 3.1.0.3

### ISSUE THREAD

**Issue by vector3dgh** [nightscout/AndroidAPS#2054]
After updating from 3.0.0.0 to 3.1.0.3, the pump tab (DASH) no longer displays an active pod.
After installing 3.0.0.0, the active pump is displayed again.

**Comment by Andries-Smit** [comment]
@vector3dgh Please check the release notes https://androidaps.readthedocs.io/en/latest/Installing-AndroidAPS/Releasenotes.html#version-3-1-0
> Important hints
>   after update uninstall Wear app and install new version
>   Omnipod users: update on pod change !!!
