### ISSUE TITLE
[3.1.0.3-dev-a_a995867cda] Report of 2 bugs - One left

### ISSUE THREAD

**Issue by Alamo04** [nightscout/AndroidAPS#2069]
In the last dev versions are two new bug:

Treatments (also reported here https://github.com/nightscout/AndroidAPS/issues/2062#issue-1364230359):
- deleting of wrong entry's not longer possible. Delete button and "Remove AAPS started entrys" didn't have any function now.
![Screenshot_20220911-121239](https://user-images.githubusercontent.com/36486505/189522440-cce8e096-7bd6-47cf-88bc-8f62523e0177.png)

Messages:
- messages, that comes up if you enter wrong values (basal, isf...) shows only a white box. There is a white background with also white letters.
![Screenshot_20220911-121310](https://user-images.githubusercontent.com/36486505/189522460-d28950d5-eb1c-47ed-b547-c0663c5c31de.png)

@MilosKozak 
if you are aware of this bugs, you can close this issue.

My System:
Pixel 5 Dark Mode, DanaRS, Dexcom G6 with Boyda, latest Dev AAPS.

**Comment by justmara** [comment]
Have you tried pressing this icon? It may help with deleting records ;)
<img width="577" alt="image" src="https://user-images.githubusercontent.com/4157587/189537364-4be48994-3e19-4a4c-9464-9adde51d32ce.png">

**Comment by philipgo** [comment]
Same bugs here on a completely different setup

**Comment by MilosKozak** [comment]
menu fixed by https://github.com/nightscout/AndroidAPS/commit/0ccc5bfdfcb7f3f17f18d47594a8b3f42ca1bcd4

**Comment by Alamo04** [comment]
Hi @MilosKozak,

- Treatment deletion works now. :)

- White letters on white background are still remaining in Profile (Basal and IC). ISF and DIA works correct.

**Comment by MilosKozak** [comment]
@osodebailar

**Comment by osodebailar** [comment]
@MilosKozak i will have a look on it the next days
