### ISSUE TITLE
[ENHANCEMENT] REQUEST: Integrate MyFitnessPall API with AAPS

### ISSUE THREAD

**Issue by ragaimeena** [nightscout/AndroidAPS#2073]
enhancement request?

Is there a way to integrate data from MyFitnessPal (especially food database) into AAPS?
It will be fantastic if from within AAPS a person can QR/barcode scan food or enter from a food database that is already available like MyFitnessPal.
Great app BTW, you all are wonderful

**Comment by andyrozman** [comment]
I would imagine that MyFitnessPal database is private, so I don't any integration would be possible, But I might be wrong.

**Comment by ragaimeena** [comment]
Doesn't have to be MyFitnessPal. Is there any other database you know of that I can integrate rather than manual entry
