### ISSUE TITLE
[2.8.0] rest of insulin will not decrease by using virtual pump

### ISSUE THREAD

**Issue by rICTx-T1D** [nightscout/AndroidAPS#208]
Hi community, 

Iam using virtual pump mode and detect in version 2.8.0 (master) that the amount of insulin will not smaller, when insulin was recorded in bonus page.

When I start a new cartridge,  I make a infusion-set change with option reservoir. Then amount is full and age will be displayed as new. After some days and injections later, age has forwarded but amount is unchanged. 

I think it is a bug. Maybe in a early version too.

**Comment by MilosKozak** [comment]
do you have screenshots?

**Comment by rICTx-T1D** [comment]
![20210109_223132](https://user-images.githubusercontent.com/8592414/104109082-8436fe00-52ca-11eb-99f9-76c7ed1ea033.jpg)

**Comment by MilosKozak** [comment]
Please specify pump and upload logs

**Comment by MilosKozak** [comment]
sorry i missed the point.
Virtual pump is not capable to track resorvoir level
