### ISSUE TITLE
[3.1.0.3]NS Client Wrong import treatment form NS 

### ISSUE THREAD

**Issue by misiek2lucky** [nightscout/AndroidAPS#2080]
Hi. I found some bug.

First two pictures are from AAPS 3.1.0.3

Second two pictures are from My AAPS Client 3.1.0.3

 Third from NS

In the same time we  first add ecarbs 40g for 240min and using calc 40g and insulin for meal. AAPS Client don't import 40g from meal from NS. my preview is misleading me, and I might react wrongly.

![20220916_171914](https://user-images.githubusercontent.com/60369433/190675139-b0a171ad-5b3f-43b0-9664-bb298f37e068.jpg)
![20220916_172607](https://user-images.githubusercontent.com/60369433/190675141-6aa182de-4da0-49ba-81b5-b8ea13210910.jpg)
![20220916_171942](https://user-images.githubusercontent.com/60369433/190675142-8ef96508-a23c-419f-8b1a-95c59365a479.jpg)
![20220916_172514](https://user-images.githubusercontent.com/60369433/190675145-dbb0d652-af8e-47ed-9a02-0a0ad320a1c1.jpg)
![20220916_172039](https://user-images.githubusercontent.com/60369433/190675149-660bf7ec-6538-497a-9f80-6ab6b5ebe69a.jpg)

**Comment by MilosKozak** [comment]
use dev version of NS for proper sync

**Comment by misiek2lucky** [comment]
Thank You I will try.
