### ISSUE TITLE
Dash 

### ISSUE THREAD

**Issue by Viewquest** [nightscout/AndroidAPS#2097]
I installed the 3.1.0.3-dev-b today and found the following errors. First I wanted to activate a new dash after deactivating the old dash. There was an Activate Pod button, but I couldn't activate it. So I had to go back to the dev-a variant. Here it worked. Please check the process and correct it if necessary. Many Thanks.
Lothar

**Comment by Andries-Smit** [comment]
@Viewquest is this duplicate of #2092 ?

**Comment by Viewquest** [comment]
Bi

Von meinem iPhone gesendet

**Comment by Viewquest** [comment]
- [x] No

**Comment by MilosKozak** [comment]
what was the exact verison of dev-b?

**Comment by MilosKozak** [comment]
i hope activation was fixed in https://github.com/nightscout/AndroidAPS/commit/7543f3f11834bfb6a059448e6cc8fb9e11ea9bce

**Comment by Viewquest** [comment]
Von meinem iPhone gesendet

> Am 22.09.2022 um 20:45 schrieb Milos Kozak ***@***.***>:
>
> what was the exact verison of dev-b?

**Comment by Viewquest** [comment]
sorry, it's the same problem. Didn't see it.

**Comment by Viewquest** [comment]
Flying to NY today and will fix the problem in 10 days.

Best greads
Lothar

**Comment by MilosKozak** [comment]
I see, Pixel 4 .
it's already fixed
