### ISSUE TITLE
NSClient disconnection on WLAN

### ISSUE THREAD

**Issue by Duester64** [nightscout/AndroidAPS#21]
AAPS 2.7
NS Client stops sporadically, if Wlan is on, saying destroy and not allowed until Wlan is switched off. then it reconnects. The Wlan signal is always stable and strong. This occured since update from 2614 to 2700.

It happens if the router signal changes from one repeater to another in a home network. This may be the reason that some people only have this problem. Maybe it would be a solution to engage a reconnect instead to stop the client.

If the NSClient saying not alowed it won't start again until a restart of AAPS  or until you switch off wlan.

![Screenshot_20201001-130730_AndroidAPS](https://user-images.githubusercontent.com/61905746/94802136-657dbd00-03e7-11eb-86fd-219ac1b20c0d.jpg)

**Comment by Arne1346** [comment]
Not sure whether AAPS is the source of this issue.
Received an email from Martin who manages 10be.de with the info about recent issues. Martin was explaining that with the recent NS update to 14.x a huge number of additional connections to the Mongo DB are kept open which cause some pain on the 10be.de side. He is actively working on that.

Maybe this is also the origin of your reported issue - which for me (using 10be.de also) is simliar.

**Comment by Duester64** [comment]
Have changed the issue, Seems to happen on a repeater change. I tried it just a minute ago.

**Comment by MilosKozak** [comment]
not allowed means you have some restrictions is nsclient settings. check it
the info about current connectivity, charging etc is received from android.

i don't believe there is anything we can improve because we have to alwayse rely on android
