### ISSUE TITLE
[3.1.0.3-dev-a] No pairing for Dana-i/RS after clicking Selected Pump

### ISSUE THREAD

**Issue by szantos** [nightscout/AndroidAPS#2103]
After clicking Selected Pump in Dana-i/RS Preferences nothing happens, I'm unable to pair the pump.

- phone BT is on
- every permission for AAPS is given
- I've reset pairing information after long clicking BT status on the DANA Tab
- after short clicking BT status on the DANA Tab it tries to connect (counts the seconds)
- there were no Dana pumps paired with AAPS before (just a Combo)
- the Dana pump I'd like to pair, can communicate with the AnyDana app on the same phone

Workaround:
- reverting back to 3.0.0.1 (479bfc410)
- pairing appeared after clicking Selected Pump in Dana-i/RS Preferences
- updating AAPS to 3.1.0.3-dev-a
- pump remained paired, communication working as it should
- but still nothing happens after clicking Selected Pump in Dana-i/RS Preferences

**Comment by MilosKozak** [comment]
dev-a  is not the latest. test with current master

**Comment by szantos** [comment]
@MilosKozak 
same with 1de236a602

**Comment by MilosKozak** [comment]
tested with latest dev and no issue. scanning dialog appears immediately

**Comment by MilosKozak** [comment]
can you re-test with latest dev?
provide logs pls

**Comment by MilosKozak** [comment]
finally I saw the crash in logs
fixed by https://github.com/nightscout/AndroidAPS/commit/479ceabe9d064f5a7cb16d9ef93f80ff5fa9567d
