### ISSUE TITLE
Bad destination number in a log of SMS communication

### ISSUE THREAD

**Issue by maskac** [nightscout/AndroidAPS#2108]
After sending bolus command from number 604xxxxxx confirmation SMS gone tu 604xxxxxx and 771. But in the log is only doubled 771xxxxx number.
![issue](https://user-images.githubusercontent.com/16052233/193457102-46e9d3bb-93bb-4e30-b80a-b70f800afeda.png)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/2e3ce68e3da991833d4ca3d01aef339b71997bcf
