### ISSUE TITLE
IOB isnt calculated correctly or falsely at zero

### ISSUE THREAD

**Issue by GReise** [nightscout/AndroidAPS#2111]
After installing the new Update of AndroidAPS (2.8 -> 3.0), the bolus-IOB was calculated as - i would say - planned. 
But some hours passed and it turned to 0.00 and stayed there. 
There is no IOB change anymore when triggering insulin via the "insulin" or "calculate" button. Even the basalrate isnt taking place in the calculation. It stays at zero there no matter how much Insulin is given. Of course it was estet with the pump disconnected.
IOB is only set to a not-zero value, when entering an Insulindose with the "capture" checkbox.
I could reproduce this by resetting the databases. The logs didnt show anything unusual nor any difference between the first given insulindose and the faulty ones. The basalrate is still not visible.
This leads to an unneccesary amount of basalrate and SMBs, when carbs are active.
Might be incorrect operation by me, but maybe there is some explanation beside this.
I am going to use the fullDebug app next week.
Thanks in advance.

My setup: BYODA, Accu-Chek Combo via ruffy. 
![1664735567174](https://user-images.githubusercontent.com/114856704/193470343-5b36baae-54e9-4b2c-a3d5-f6fe93a5a9ff.jpg)
![1664735567192](https://user-images.githubusercontent.com/114856704/193470345-0f09356e-e276-49ac-83f7-c4e997f64043.jpg)
![1664735567208](https://user-images.githubusercontent.com/114856704/193470347-86efdd78-db7b-42bd-85fa-70a0e7a4af93.jpg)
![1664735567225](https://user-images.githubusercontent.com/114856704/193470348-1333572a-5f3e-4048-afff-436dd07a1fc4.jpg)

**Comment by MilosKozak** [comment]
it seems something is broken with your database.
reset database and try again
