### ISSUE TITLE
Error Messages Omnipod Dash

### ISSUE THREAD

**Issue by Viewquest** [nightscout/AndroidAPS#2114]
I installed the AAPS 3.1.0.3-dev-b on Sunday and now have the following error messages:
1. Setting temp basal might have basal failed if temp basal was previously runnig, it was canceled. pleas manually refresh pod status from the omnipod tab.
2. Unable to verify whether SMB bolus (0.35U) succeeded. <b>Refresh pod status to confirm or deny this command.
3. AndroidAPS not responding:
            close the app
            waiting
Since the messages appear more frequently, I believe that a correction should be made. Many Thanks.
Lothar
My systems: Pixel 4a, Byoda, xDrip

**Comment by MilosKozak** [comment]
provide logs

**Comment by Viewquest** [comment]
[AndroidAPS_LOG_1664879303140.log.zip](https://github.com/nightscout/AndroidAPS/files/9705029/AndroidAPS_LOG_1664879303140.log.zip)

**Comment by Viewquest** [comment]
Hello Milos, could you do something with my logs? I look forward to an update. Many greetings
Lothar

**Comment by MilosKozak** [comment]
log contains only a few minutes and connection was working fine

**Comment by MilosKozak** [comment]
open new  issue and provide all info requested if you can replicate the issue
* and reset logging to default + check all PUMP*
