### ISSUE TITLE
Dev-b bug: loop tab, pull down, restart aaps

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2115]
Strange bug. On the loop tab, when you pull down to force recalculation, AAPS stops or restarts. It was working OK before this beta.

Look around 0h37

![Screenshot_20221002_155951.jpg](https://user-images.githubusercontent.com/76626474/194177068-92818100-4287-4c13-8c05-e05fac469958.jpg)

![AndroidAPS_LOG_1665009485011.log.zip](https://github.com/nightscout/AndroidAPS/files/9719386/AndroidAPS_LOG_1665009485011.log.zip)

**Comment by robertrub** [comment]
On loop tab, 3 dots menu, _execute now_ works normally.

Only the pull down restarts AAPS.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/d3bb0d295ecb2180356a52bd94e14bcc675b4727
