### ISSUE TITLE
TDD statistics scrambled 

### ISSUE THREAD

**Issue by Duester64** [nightscout/AndroidAPS#2118]
![Screenshot_20221007-104423_AndroidAPS](https://user-images.githubusercontent.com/61905746/194513944-39912cf9-5ed9-4ebc-9175-beb8702abaaa.jpg)

The lines are scrambled due to IEs are added in each line. Proposal to add IE in Head line and delete it from the lines to clean up the table.

**Comment by Alamo04** [comment]
What version are you using.

Seems to be a problem with small displays.

On my Pixel 5 everything is fine, but I use the latest dev.

**Comment by Duester64** [comment]
I'm using the latest 3103 dev b and I have a common Samsung S21.

**Comment by MilosKozak** [comment]
you have probably large font set in system

**Comment by cr582** [comment]
"large fontset" seems to be the default answer to all display problems. Maybe the developers could agree that you can make fontsets bigger for a reason and find a solution for that? But what do i know?

**Comment by MilosKozak** [comment]
I agree. And it works like expected. If you you set larger font than app is designed for (or you have smaller screen), system start wrapping the text. It's android feature, not AAPS

**Comment by Duester64** [comment]
Just for proposal if you reduce the  column carbohydrates an bit it would fit even for laarger fonts.

**Comment by swissalpine** [comment]
It is again due to the German translation: "Kohlenhydrate" is a very long word, while the English "Carbs" is much shorter.
Maybe the translators should translate with the UI in mind and use the abbreviation "KH" instead of "carbohydrates".

**Comment by szantos** [comment]
Also see Changes (v3) proposal in #2091

**Comment by MilosKozak** [comment]
I added new "carbs_short" for translation
