### ISSUE TITLE
Dana RS not regularly reading reservoir

### ISSUE THREAD

**Issue by JohnKitching** [nightscout/AndroidAPS#213]
I noticed yesterday AAPS was reporting 40 units in the reservoir for several hours.  
On tapping the Bluetooth icon it dropped to  23. 
Today I took a couple of screenshots showing before and after tapping the Bluetooth icon. 
I'm on 2.8. I didn't notice this happen on 2.7 but I'm not certain it didn't. 
Will email logs now. 
![image](https://user-images.githubusercontent.com/48366213/104129983-569f9280-5366-11eb-9c07-d241647b41b8.png)
![image](https://user-images.githubusercontent.com/48366213/104129990-5acbb000-5366-11eb-974d-b1094845d292.png)

**Comment by JohnKitching** [comment]
Sorry, screenshots wrong way round.

**Comment by MilosKozak** [comment]
there is not enough information in logs.
you turned on autosens logging which is producing so much data that it's effectively breaking find something else
open new issue when you have more useable logs
