### ISSUE TITLE
[3.1.0.3 Master branch] Cannot loop, always executing

### ISSUE THREAD

**Issue by diyaps** [nightscout/AndroidAPS#2134]
Reporting bugs
--------------
Pump: Medtronic 723
Phone: Samsung S22U
Problem occurrence time： 2022 10.19  20:28
[AndroidAPS.zip](https://github.com/nightscout/AndroidAPS/files/9820484/AndroidAPS.zip)
After reset my pump and phone and concent again. It  cannot loop.
The loop tap always show "Executing".
![Screenshot_20221019-202543_AndroidAPS](https://user-images.githubusercontent.com/1226919/196695220-e09030e0-54be-4082-849d-9af53a43e53b.jpg)

**Comment by MilosKozak** [comment]
a) communication with RL is failing. That's something I cannot resolve for you. It's either phone or RL issue
b) only master and latest dev is supported here

**Comment by diyaps** [comment]
@MilosKozak  not sure why RF is failing, but I still can bolus.  Anyway finally I resolved the issue by setting up the basal in the pump. Then it can loop.
I think some how the RF failing error make apps cannot sync profile to pump and then issue occurs
