### ISSUE TITLE
[Omnipod Dash] content issue in Pod Management

### ISSUE THREAD

**Issue by dar-kod** [nightscout/AndroidAPS#2138]
AndroidAPS 3.1.0.3
Phone: Poco F3 MIUI 13.0.5, Android version 12
Settings -> Display -> Text size -> L

After update from MIUI 12.5 (android version 11) to this one, there is a content issue in **POD MGMT**. In DASH tab, if you click at PD MGMT button, Pod Management will be open. But the font size here is very small. Please see the first attached screenshot. Before update of MIUI the font size was ok. Please see second screenshot. I suppose, this must be very easy to fix. Thanks in advance.

![1660243539446](https://user-images.githubusercontent.com/24446806/197402986-867514a8-5d63-4c4f-b02e-727f586b2cf3.jpg)

![1660243539457](https://user-images.githubusercontent.com/24446806/197402855-628ee88e-111b-42a4-961e-7a4d429dc78e.jpg)

**Comment by MilosKozak** [comment]
that's not something we can fix
Font size is set to 11dp. Before and now too
