### ISSUE TITLE
Dev-C cleaning database bug

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2142]
@MilosKozak More info on the _clean db_ "reseting" db update to NS.

I have NS and Mongodb on my NAS in containers. All is working OK.

I pause NS update in AAPS. 
Set to zero the database on the NAS.
Clean db to 3 months in AAPS.
This sets the NS upload cue to over 55000
Unpause NS update and AAPS starts to send the 55+ k data.
Once all the data is uploaded, I go to my NS web page and try reports. I only have 1 days data. Theoretically, there should be 3 months data.

It is as if the data was not uploaded or was uploaded not as NS expects.

![Screenshot_20221023_143531.jpg](https://user-images.githubusercontent.com/76626474/197954675-159c4ee7-023b-4755-9a1e-bef3ed57176b.jpg)

**Comment by robertrub** [comment]
![Screenshot_20221026_085034.jpg](https://user-images.githubusercontent.com/76626474/197955276-08c3d064-8f42-493d-9345-a9fe9df97f05.jpg)

![Screenshot_20221026_085110.jpg](https://user-images.githubusercontent.com/76626474/197955320-b5a93de2-8dad-4978-84e3-580bd145407d.jpg)

**Comment by MilosKozak** [comment]
can you verify ns db via https://..../api/v1/treatments.json ?

**Comment by robertrub** [comment]
I must be doing something wrong as I get this message
![Screenshot_20221204_181131_DuckDuckGo](https://user-images.githubusercontent.com/76626474/205505209-51f87edc-aa9b-4a76-8d89-b67a3592e3bc.jpg)

**Comment by MilosKozak** [comment]
can you open NS and see data on this computer?
