### ISSUE TITLE
Dev-C Winter time / Prediction lines

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2145]
![Screenshot_20221030_045316.jpg](https://user-images.githubusercontent.com/76626474/198861836-312388fb-a109-41b5-817e-93bb64d5239b.jpg)

Changed to winter time, it is 5AM with the new time. The graph has prediction lines starting in the past...

**Comment by Alamo04** [comment]
@robertrub
Without Logs, they can't say anything about that.
They also don't know your Phone, your pump, your AAPS version....

So far I hear from our german community, they didn't have this issue. But I think they are all sleeping at this time. :)
Did that issue still exist, or was it self fixing ?

**Comment by robertrub** [comment]
It was "fixed" when I got up around 8AM. 

It is probably just a graphic glitch and happens once a year, for winter time change ;)

**Comment by robertrub** [comment]
There are other glitches too with DST. Nothing serious though.

![Screenshot_20221031_081638.jpg](https://user-images.githubusercontent.com/76626474/198957874-7bca5a5f-d503-4800-948f-a48f6e48b44b.jpg)
