### ISSUE TITLE
DST causes double data in statistics in V3.1.0.3 dev-c

### ISSUE THREAD

**Issue by koelewij** [nightscout/AndroidAPS#2146]
After DST, Statistics shows double data lines. 
![Screenshot_20221031_075752_AAPS](https://user-images.githubusercontent.com/77214125/198958102-f6f20bbb-1ee2-4900-b481-f1dc8b9935cd.jpg)

Though it seems not that serious, functions like Dynamic ISF are using those statistics and might be influenced by this behavior. 
It would be better that the day involved would be an hour longer/shorter instead of generating a separate entry with unexplainable data.

**Comment by robertrub** [comment]
Same here

![Screenshot_20221031_081638.jpg](https://user-images.githubusercontent.com/76626474/198962891-577d9faf-8bbd-4c0e-8d63-99935745da41.jpg)

**Comment by MilosKozak** [comment]
cause by daylight saving change when day is longer than 24h
