### ISSUE TITLE
[3.1.0.2] Readings for the Nightscout website upbat plugin are duplicated(?).

### ISSUE THREAD

**Issue by AgushkaNightscout** [nightscout/AndroidAPS#2163]
Hello. Thank you for your brilliant product! My battery reading in the NS is duplicated. In the database, the entries are like attached below. Upload to NS is done by AAPS and xDrip+, in xDrip+ all the checkboxes about sending the battery status are unchecked, so I assumed it's AAPS. Can you please tell me what's wrong?

![Снимок экрана от 2022-11-03 23-46-45](https://user-images.githubusercontent.com/90107639/199923713-12e5ccad-702b-4edf-80e5-69cabcd02262.png)
![Снимок экрана от 2022-11-03 23-46-31](https://user-images.githubusercontent.com/90107639/199923757-a847cb28-55d8-408e-804b-f1ddc5257f3f.png)

**Comment by MilosKozak** [comment]
the second record is not from AAPS, probably xDrip.
Ask there

**Comment by AgushkaNightscout** [comment]
Thank you!
