### ISSUE TITLE
Loop not executing when BG is changing version 3.1.0.3

### ISSUE THREAD

**Issue by margogoodfellow** [nightscout/AndroidAPS#2165]
Timing 7:21 it was last time when loop has executed. Bg has changed again but loop hasn't executed again. Please see pictures.  I have done bew build, passed all objectives and opened new nightscout.  Also done this on new phone.  
Please can you look into this and this is happening to me all the time in every version apart of 3.0.0

Link to logs : https://drive.google.com/file/d/1YHQ2yB-khQ0USeA-kuraAKfCV35tLObT/view?usp=drivesdk

Time 7:21-7.29

> 
![IMG-20221105-WA0006](https://user-images.githubusercontent.com/68740119/200111295-b25504b4-6d66-488c-bb56-ccf2cabc56b7.jpg)
![IMG-20221105-WA0005](https://user-images.githubusercontent.com/68740119/200111297-081eb4d4-3adc-48f7-9f32-0bfbdbd249d8.jpg)
![IMG-20221105-WA0004](https://user-images.githubusercontent.com/68740119/200111298-4efa44c6-f44e-4cae-b132-eafad6922dc9.jpg)
![IMG-20221105-WA0003](https://user-images.githubusercontent.com/68740119/200111299-9d0f3622-abff-4cef-841e-c2414a9f9b54.jpg)
![IMG-20221105-WA0002](https://user-images.githubusercontent.com/68740119/200111300-7fbe1690-3869-4d74-ba92-69dbbc15233f.jpg)
![IMG-20221105-WA0001](https://user-images.githubusercontent.com/68740119/200111302-fa85b93a-41cd-44ac-b52a-550bf3f564a9.jpg)
![IMG-20221105-WA0000](https://user-images.githubusercontent.com/68740119/200111303-f15b2ff4-1baf-44c1-a17d-76687664e2b9.jpg)

**Comment by MilosKozak** [comment]
In logs i see AMA executing regulary even after 7:21

**Comment by margogoodfellow** [comment]
I don't know then what's going on.  As you can see on the pictures,  loop
wasn't executing.

**Comment by MilosKozak** [comment]
added more logging https://github.com/nightscout/AndroidAPS/commit/bd35007f44786235788b9879ffae5de73149f4c2, provide new logs pls

**Comment by MilosKozak** [comment]
duplicate to https://github.com/nightscout/AndroidAPS/issues/2130
