### ISSUE TITLE
[2.8] "History Browser" window does not display/refresh as requested

### ISSUE THREAD

**Issue by jbuckhi** [nightscout/AndroidAPS#217]
If you open the "History Browser" you get an empty diagram (without data):

![Screenshot_20210111-161954_AndroidAPS](https://user-images.githubusercontent.com/56472275/104204788-ef4d1580-542d-11eb-8fe9-141e63b56d46.jpg)

You have to press the "24" button (in the upper right corner), then the data is displayed:
![Screenshot_20210111-162025_AndroidAPS](https://user-images.githubusercontent.com/56472275/104205054-3b985580-542e-11eb-8ca7-71f46c7a1e82.jpg)

Same thing, if you want to switch the date (no matter which button you use): nothing happens! Again, you first have to press the "time range button" in the upper right corner, to get the results.

**Comment by robertrub** [comment]
It was the same in 2.7.0 too. 
And the "Button" text on button is not very explicite ;)

**Comment by rICTx-T1D** [comment]
2.8.2 master is affected too.

**Comment by MilosKozak** [comment]
resolved in dev
