### ISSUE TITLE
Last dev bug

### ISSUE THREAD

**Issue by overfrenk** [nightscout/AndroidAPS#2205]
Reporting bugs
--------------
In the actions tab only the bg and prime control keys work, all others always lead to the bg control key. In tools history and tdd crash aps. Last buil DEV 15/11/22 8pm.

**Comment by MilosKozak** [comment]
👍 
fixed by https://github.com/nightscout/AndroidAPS/commit/99c232a2e5c3a642d91409c004c50415431bdcc1
