### ISSUE TITLE
[DEV] [EOPATCH2] pump timer reset on starting new pump

### ISSUE THREAD

**Issue by MarvelousMarvin** [nightscout/AndroidAPS#2211]
Reporting bugs
--------------
- 15:40 hours Amsterdam time 21 November 2022.
- 3.1.0.3 dev c
- Pump timer doesn't reset to 0 on starting new pump.

![Screenshot_20221122-002107](https://user-images.githubusercontent.com/40701484/203177683-a6c38732-b78e-4817-b577-11a72a9c39c6.png)
![Screenshot_20221122-002134](https://user-images.githubusercontent.com/40701484/203177698-e1828621-26eb-458c-b728-6e348bf70087.png)

**Comment by jbr7rr** [comment]
Seems to be fixed with this comment:
https://github.com/nightscout/AndroidAPS/commit/9d14db71c7dd9d47a6c0205307432ba97b7778e7
