### ISSUE TITLE
[3.1.0.3-dev-d]  Bolus calculator  set notice-field to "null" as default

### ISSUE THREAD

**Issue by rICTx-T1D** [nightscout/AndroidAPS#2244]
Hi folks,

when I open the bolus calculator, the notice fild (under amount of insulin dose) is filled with "null" as default value.
Please fix it. Thx.

**Comment by Alamo04** [comment]
Confirmed

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/180d9327b627e95c26defe541e4222a3a699c671
