### ISSUE TITLE
**AndroidAPS** 3.1.0.3-dev-d showing logo on DASH History view (affects readability) 

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#2250]
**AndroidAPS** 3.1.0.3-dev-d
**Build**: 6172ca8d
**Flavor**: fullrelease / Engineering mode

**Problem description**:
For DASH pump, the AndroidAPS logo is unexpectedly shown on the DASH tab when on Pod Management (button press)?
Problem is the logo stays in overlay when switching to "Pod History", making history unreadable.

**Additional Info**:

- Logo showing when on  DASH, Pod Management, somewhat unexpected? Could see showing the Omnipod Pump logo here... 
- When selecting "Pod History", logo is showing in overlay affecting readability:

**DASH tab "Pump Managent":**

![image](https://user-images.githubusercontent.com/45144129/205461572-87ac28d7-f37e-4c63-966b-96e9565ecb8b.png)

**DASH tab "Pump Managent" -> "Pod History", image showing in overlay affects readability:**

![image](https://user-images.githubusercontent.com/45144129/205461637-2e4e264e-0774-415c-a996-5c5115789f45.png)

**Comment by MilosKozak** [comment]
re-test with https://github.com/nightscout/AndroidAPS/commit/40bbafe14a8aed5a084320421259cb5cad12e636 pls

**Comment by vanelsberg** [comment]
@MilosKozak Tested, confirming, fixed
