### ISSUE TITLE
[DEV] Overlapping temp basals in history possibly causing wrong IOB

### ISSUE THREAD

**Issue by jbr7rr** [nightscout/AndroidAPS#2251]
Build: 4b46ea8363-2022.12.04 Merged at: https://github.com/nightscout/AndroidAPS/commit/9a35579d66b8f01d0a5610d7485ced848e736f7e
Pump Used: EOPatch
Time: See screenshot (2022-12-04 18:23 and 18:03 would be times of interest)

I noticed basals not cancelling correctly (or not showing up in history at least) causing wrong IOB results. See screenshot:
![WhatsApp Image 2022-12-04 at 18 35 01](https://user-images.githubusercontent.com/60566713/205506577-e6085f06-5c68-4c00-8d29-21b11c92f488.jpeg)

Logs:
[AndroidAPS_2022-12-04-jb.zip](https://github.com/nightscout/AndroidAPS/files/10149125/AndroidAPS_2022-12-04-jb.zip)

Edit: Looking back at the history I see this happinging on older builds as well. Looking further back I also saw some instances of this behaviour with the Combo (new driver). Will start a DASH when this one needs changing and see if it happens there as well. Removing the EOPatch tag.

**Comment by vanelsberg** [comment]
Can not see the problem here.
E.g. 17:38h 120m basal is replaced with a 5 min basal at 18:03h. Nothing wrong with that...
Please explain?

**Comment by jbr7rr** [comment]
> Can not see the problem here. E.g. 17:38h 120m basal is replaced with a 5 min basal at 18:03h. Nothing wrong with that... Please explain?

Please look again, the basal did not end it was overlapping. In fact AAPS was thinking it was still running, the job counter for the one at 18:18 was still going up every 5 min.

Here is another example, please note the end time of the first temp basal. It later then the next one started

![Screenshot_20221205-012129](https://user-images.githubusercontent.com/60566713/205525188-ee882271-5135-49c6-9c84-425f200d6041.png)

**Comment by vanelsberg** [comment]
Any relation with an overlapping problem that was solved for DASH?
https://github.com/nightscout/AndroidAPS/issues/1597

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/d261bbad09a04d854ee3169eaf927f5502d8c7a2
