### ISSUE TITLE
Equil pump support?

### ISSUE THREAD

**Issue by nuke3** [nightscout/AndroidAPS#2253]
Will there be support for the Equil pump?
http://www.microtechmd.com/en/Products/EQUIL-Patch-Insulin-Pump
TL;DR It's tubeless insulin pump like Dash Omnipod, but it's costs significantly less (~90 USD/m).

**Comment by MilosKozak** [comment]
yes. Expecting next year

**Comment by Stealthwick** [comment]
Hi Milos, can you let me know who is working on this? I'd like to help out and support them with hardware etc if that would help them :)

> yes. Expecting next year

**Comment by Stealthwick** [comment]
> Hi Milos, can you let me know who is working on this? I'd like to help out and support them with hardware etc if that would help them :)
> 
> > yes. Expecting next year

@MilosKozak ?

**Comment by MilosKozak** [comment]
I know only rumor
