### ISSUE TITLE
Beta D : 0 min duration temp basals

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2254]
I was just looking at the past basals and was astonished to see several 0 min temp basals.

![Screenshot_20221204_153223_AAPS.jpg](https://user-images.githubusercontent.com/76626474/205581021-aa96728a-f67b-41f5-9ebd-bc63ae19d19d.jpg)

![AndroidAPS_LOG_1670223378646.log.zip](https://github.com/nightscout/AndroidAPS/files/10151739/AndroidAPS_LOG_1670223378646.log.zip)

![Screenshot_20221205_075605_AAPS.jpg](https://user-images.githubusercontent.com/76626474/205581334-9ca133ca-1917-4997-aa39-bb44a7b8cebc.jpg)

No idea what S means either.

Several days ago, they were there too.

![Screenshot_20221204_214951_AAPS.jpg](https://user-images.githubusercontent.com/76626474/205581702-b504250c-fa9b-48f7-8122-7ca5fc25ead6.jpg)

**Comment by MilosKozak** [comment]
id does mean "SUSPENDED". Dash is using it in some cases and from AAPS point of view this doesn't break anything
