### ISSUE TITLE
[3.1.0.3-dev-d] Going back in preferences opens all tabs

### ISSUE THREAD

**Issue by OFlannigan** [nightscout/AndroidAPS#2261]
When in three-dots-menu under preferences and you click on any option (no matter if sub-menu or single option) and then going back unfolds all tabs at once.

For example:
General -> Language.
Then back-gesture will quit dialog and unfold all tabs.
Also happens when "cancel" is clicked.

Version: 3.1.0.3-dev-d
Phone: Pixel 7 Pro
OS: Android 13 Build TQ1A.221205.011

**Comment by robertrub** [comment]
I confirm.
![Screenshot_20221206_091811_AAPS.jpg](https://user-images.githubusercontent.com/76626474/206038385-a1941419-191e-41f5-bcbc-2d949f465216.jpg)

**Comment by MilosKozak** [comment]
this is fully under android control. No way to change behavior
