### ISSUE TITLE
Pod is not reached!

### ISSUE THREAD

**Issue by Viewquest** [nightscout/AndroidAPS#2272]
Hello,
I have the version DEV-D , Build 40bbafe14a since December 4th. installed and get the following error messages:

[AndroidAPS_LOG_1670592620808.log.zip](https://github.com/nightscout/AndroidAPS/files/10195276/AndroidAPS_LOG_1670592620808.log.zip)
I hope the files can be opened and the error can be fixed.

Many greetings
Lothar
![Screenshot_20221209-142949](https://user-images.githubusercontent.com/94917775/206715042-fb739f44-a33e-4897-8f2c-8cc5a2f56e52.png)

**Comment by MilosKozak** [comment]
the crucial log is missing

**Comment by MilosKozak** [comment]
that's the same

**Comment by Viewquest** [comment]
Ja, welches Protokoll soll ich Dir senden? Habe doch nur das aus der AAPS!

**Comment by Viewquest** [comment]
Yes, which protocol should I send you? I only have that from the AAPS!

**Comment by MilosKozak** [comment]
it must contain time 14:28 and before

**Comment by Viewquest** [comment]
I copied the log right after the error message. May I ask you how I get other log files?

**Comment by Viewquest** [comment]
![Screenshot_20221209-145943](https://user-images.githubusercontent.com/94917775/206719338-28a87d63-9138-48e2-ae6e-b4ed89b30dc4.png)
This error message also comes up. If I immediately take a screenshot, the error should appear. I can't get any other log through AAPS. Or I still have to learn that too. But would like to understand it without a degree in developer language.

**Comment by MilosKozak** [comment]
https://androidaps.readthedocs.io/en/latest/Usage/Accessing-logfiles.html?highlight=accessing%20log

**Comment by Viewquest** [comment]
Thank you for this information. So far I have not been able to connect my Android to my Mac. I've only ever sent the data via email. Will now check how I get to the data. Unfortunately I have to pass today. Sorry, I will report back the days when I have solved the problem of data transfer. Many greetings
Lothar

**Comment by Viewquest** [comment]
Unfortunately I cannot transfer the logs to the PC. The mobile phone (Pixel 4a) does not allow the transmission. Will clarify that next week. Possibly I'm going to get a new cell phone. Sorry for the inconvenience. Lothar

**Comment by Viewquest** [comment]
Since I'm already working with the DEV - E version, it won't make sense to get active here again. With the next issue I will also be able to deliver the corresponding log files. Many thanks for your support.
