### ISSUE TITLE
Feature Request: Ability to set insulin strength for Omnipod

### ISSUE THREAD

**Issue by koelewij** [nightscout/AndroidAPS#2276]
Currently the Omnipod can only handle 100U/ml insulins. While some parents require diluted insulin to be able to accurately dose insulin, others use for instance Lyumjev 200U to reduce the burning effect of this insulin. 
Currently people need to change many parameters in their profile and other settings in AAPS to be able to handle those insulins. And then try to correctly interpret the results. Algorithms like DynISF that are based on TDD would not properly work with different strengths of insulin other than 100U. 

Would it be possible to have one parameter in the Omnipod driver that takes care of this multiplication factor? 

Of course setting this parameter to something else than 100U would require a warning of some kind to be displayed during change of the parameter, but also on the status line as a reminder. 

Possibly this could be used for other pumps that can handle only one strength.

**Comment by MilosKozak** [comment]
duplicate to https://github.com/nightscout/AndroidAPS/issues/527
