### ISSUE TITLE
[dev] [EoPatch]

### ISSUE THREAD

**Issue by sfriedriszik** [nightscout/AndroidAPS#2286]
12/13 / 4:17 p.m
EoPatch Pump
The bolus calculator has calculated the following insulin delivery
- 0.05
- 0.01

For both delivery sizes, AAPS responds with a bolus delivery error
[AndroidAPS_LOG_1670944649190.log.zip](https://github.com/nightscout/AndroidAPS/files/10220171/AndroidAPS_LOG_1670944649190.log.zip)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/23cc3c9c3e15e50c93562951a5948e462bd49f01
