### ISSUE TITLE
[dev] Missing BG Value Upload

### ISSUE THREAD

**Issue by sfriedriszik** [nightscout/AndroidAPS#2287]
AAPS 3.1.0.3-dev-e
In earlier versions of the Nightscout configuration, the upload of BG values to Nightscout was at the second point.
Now the menu item has disappeared. Rearranged ?

![image](https://user-images.githubusercontent.com/43376497/207393965-598b6e55-58e9-4a99-b588-84f7567adbea.jpeg)

**Comment by MilosKozak** [comment]
it's in BG source preferences. The reason of removal from here was this feature is not available for all bg sources

**Comment by macarolobe** [comment]
With fsl2 and xdrip the preference menu is disabled so my bg are not upload to ns

**Comment by sfriedriszik** [comment]
I use Juggluco to send the values to Aaps. This is done via the xdrip Broadcase Channel. Now I have no possibility to send the values to Nightscout.

**Comment by MilosKozak** [comment]
xDrip is treated as BG source with upload capability thus this option is missing in AAPS

**Comment by MilosKozak** [comment]
@sfriedriszik then xdrip can upload the data or?

**Comment by sfriedriszik** [comment]
@MilosKozak I don't use xdrip. I use Juggluco with connection to Aaps. Juggluco uses the xdrip broadcast to transfer the data to Aaps.

**Comment by MilosKozak** [comment]
if you install xdrip it will receive the data as well

**Comment by sfriedriszik** [comment]
@MilosKozak  I know that. I don't want to install xdrip. that worked great before. the diabox users have the same problem.

**Comment by MilosKozak** [comment]
you may ask juggloco devs to create a special broadcast to aaps
