### ISSUE TITLE
NS client invalide namespace

### ISSUE THREAD

**Issue by mick711** [nightscout/AndroidAPS#2295]
Hy I would like to use my synology Nas for my Nightscout server. 
My Nightscout work with xdrip but impossible to use it with aaps. 
I don't know if it's because I have a namespace error or other. 
Thanks

**Comment by mick711** [comment]
![Uploading Screenshot_20221218-135730417_1.jpg…]()

**Comment by parapenT1sta** [comment]
You don't need /api/v1 in the address.

**Comment by mick711** [comment]
Many thanks it work, I read doc since two hours but impossible to find Nightscout adress.

**Comment by mick711** [comment]
Many thanks it work, I read doc since two hours but impossible to find Nightscout adress.
