### ISSUE TITLE
[DEV][EOPatch] Wrong timestamp used in low reservoir notification

### ISSUE THREAD

**Issue by Cnidders** [nightscout/AndroidAPS#2297]
AAPS 3.1.0.3-dev-e
Build: f41fa8a45a-2022.12.17 Merged at: f1499d1886ae1e9b3dfc17c93ae3836703429f0
Time: 14:27/14:28

I got the notification that my EOpatch reservoir is low, but the time that showed within the red notification bar was 18:02, in stead of 14:28. I suspect the timestamp of the patch wake-up time is being used to show in the notification bar (see second screenshot). 

![Overview](https://user-images.githubusercontent.com/25057221/208687874-4351f7db-12e6-499a-8a33-9f663c535471.jpeg)
![EOPatch](https://user-images.githubusercontent.com/25057221/208687902-898a9a50-3040-4223-90c0-bfeb8723fe03.jpeg)

[AndroidAPS_LOG_1671544576905.log.zip](https://github.com/nightscout/AndroidAPS/files/10269185/AndroidAPS_LOG_1671544576905.log.zip)

**Comment by MilosKozak** [comment]
14:28:20.483 [RxCachedThreadScheduler-26] D/NOTIFICATION: [NotificationStore.add():61]: Notification received: Low reservoir
Replace Patch soon.

The notification is repeating and you see only only time of last occurence
