### ISSUE TITLE
Dev-e: Omnipod Dash: AAPSCLient showing conflicting remaining amounts

### ISSUE THREAD

**Issue by kristinsmotz** [nightscout/AndroidAPS#2299]
In new AAPSclient after installing dev-e (possibly also dev-d), there are two displays of remaining amount in Dash pod on the overview tab. The top one constantly displays 50U even when remaining amount is less. Correct remaining amount corresponding with AAPS phone Dash tab displays in next line of icons.
![Screenshot_20221222_170151_AAPSClient](https://user-images.githubusercontent.com/71758682/209174807-da874b0c-b24c-43c8-952a-15b8d8e7ee2b.jpg)

![Screenshot_20221222_170651_AAPSClient](https://user-images.githubusercontent.com/71758682/209174865-b91584fe-8a4f-499c-bcc0-daab6ca478c8.jpg)

**Comment by MilosKozak** [comment]
this is already fixed i recent devs

**Comment by kristinsmotz** [comment]
Perfect :)

**Comment by kristinsmotz** [comment]
I noticed that the newer version now displays remaining amount only on top line, not in the Pump section of the lower line. And when remaining amount goes to 0U, it disappears completely from both lines. It also disappears in AAPS app. 
Have updated to dev-f today and it's the same there. No number at all for 0U. 


AAPSClient: 
![Screenshot_20221230_221541_AAPSClient](https://user-images.githubusercontent.com/71758682/210114647-5ac5c305-3c9d-4c8b-9ad3-2ebfe8843f14.jpg)

AAPS:
![received_862495104895759](https://user-images.githubusercontent.com/71758682/210114737-3fff0eb4-b194-4468-b631-e6376a86c8f1.jpeg)
![received_877871770075341](https://user-images.githubusercontent.com/71758682/210114738-5d2565c4-b1a8-490e-bae4-a7ae80619a66.jpeg)

**Comment by kristinsmotz** [comment]
I noticed that the newer version (dev-f) now displays remaining amount only on top line, not in the Pump section of the lower line. And when remaining amount goes to 0U, it disappears completely from both lines. It also disappears in AAPS app. 
Have updated to dev-f today and it's the same there. No number at all for 0U. In the lower line, UPLD (uploader phone battery%) disappears for me when it reaches 100%, maybe there is too much padding in that section/careportal info line?


AAPSClient: 
![Screenshot_20221230_221541_AAPSClient](https://user-images.githubusercontent.com/71758682/210114647-5ac5c305-3c9d-4c8b-9ad3-2ebfe8843f14.jpg)

AAPS:
![received_862495104895759](https://user-images.githubusercontent.com/71758682/210114737-3fff0eb4-b194-4468-b631-e6376a86c8f1.jpeg)
![received_877871770075341](https://user-images.githubusercontent.com/71758682/210114738-5d2565c4-b1a8-490e-bae4-a7ae80619a66.jpeg)

**Comment by MilosKozak** [comment]
is this working well now with latest dev?

**Comment by kristinsmotz** [comment]
Unfortunately there is still a discrepancy. I just rebuilt from dev now after your update and this is a screenshot from AAPSClient. 
![Screenshot_20230110_131705_AAPSClient](https://user-images.githubusercontent.com/71758682/211549789-c4f3b0bd-361a-4268-8a29-1b4ba4c363ca.jpg)

As you can see, the bottom line shows 0.0U and some superfluous text, while top line correctly shows more than 50U. I did wait until next glucose/loop run after installing the update to see, but still 0.0U.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/f32709eaa6c30b64681c1e60a8e46db293db0f18
