### ISSUE TITLE
TempTarget-triggered loop run does not see TT itself

### ISSUE THREAD

**Issue by justmara** [nightscout/AndroidAPS#2304]
check the log
17:37:05.116 NSClient event for TT hypo set to 6.5: `"created_at":"2022-12-27T14:13:41.000Z","timestamp":1672150421000`
17:37:05.125 NSClient event for new TT of 6.0 received `"created_at":"2022-12-27T14:36:27.000Z","timestamp":1672151787000`
17:37:05.128 [ENPlugin.invoke():109]: invoke from EventTempTargetChange
17:37:05.139 D/DATABASE: [NSClientAddUpdateWorker.doWork():186]: Inserted TemporaryTarget  record
17:37:10.183 loop started but it has `"temptargetSet":false`

old TT was not canceled, only new one started.  but loop run got `false` for temptargetSet in profile data. so all the safety of disabled 'allow smb on high tt' failed.
potentially pretty dangerous behaviour.

[AndroidAPS_TT.log](https://github.com/nightscout/AndroidAPS/files/10309233/AndroidAPS_TT.log)

**Comment by MilosKozak** [comment]
what version is this?

**Comment by justmara** [comment]
Im running master for my kid.
You say this behaviour changed in current dev? Will wait for next release then, being careful. It was first time I'v met such behaviour and it is a really weird one.

**Comment by MilosKozak** [comment]
👍 sequetial procesing caused more issues not only this one. But they were random and not easy to catch

**Comment by justmara** [comment]
> Here is this problem that loop was triggered by 1st change before second was applied

Doesn't seem to be. Loop run has read for treatments and did not found both these TT records for some reason. Even though hypo TT was set long time ago. I've checked treatments log in AAPS and it shows original TT set time, not the real one applied by AAPS - that could be the problem too. While nsclient and NS see the TT, AAPS can be missing it, but when it receives - it adds it to log like it were there all that time.
