### ISSUE TITLE
xDrip BG not up to date in AAPS

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2317]
I think that this was signalled before but couldn't find the issue.

BGs coming from xDrip. The BGs are correctly shown in the xDrip tab in AAPS but the main UI shows older BG.

![Screenshot_20221231_005957_AAPS.jpg](https://user-images.githubusercontent.com/76626474/210131071-450724eb-8b50-4961-9863-649446f5bb01.jpg)

![Screenshot_20221231_010023_AAPS.jpg](https://user-images.githubusercontent.com/76626474/210131077-4ec20b60-70eb-49df-892b-a01b5202f197.jpg)

Might be important : BG was provided by BYODA a couple of days ago.

**Comment by jbr7rr** [comment]
Which build? Logs?
A similar issue was fixed a few days ago

**Comment by robertrub** [comment]
![Screenshot_20221226_161907_AAPS.jpg](https://user-images.githubusercontent.com/76626474/210133225-0c925e95-efa0-41ae-9729-831da2c72152.jpg)

**Comment by MilosKozak** [comment]
scroll down on BG tab, there is probably irregularity in last 2 days

**Comment by robertrub** [comment]
@MilosKozak I changed transmitters

**Comment by jbr7rr** [comment]
Yes after transmitter change, the data is not in 5 minute interval and gets recalculated, that causes the delay. However after your build, changes has been made to make this delay less frequent, so try to update to latest Dev and see if that fixes it

**Comment by robertrub** [comment]
I've just built the last dev now. But the problem happens ONLY if using xDrip. Using BYODA, everything is in sync.

I'll see in 10 days for the next sensor change (I'll switch to xDrip and 2nd transmitter)

**Comment by idalioreis** [comment]
what i detect is the trend at xdrip are not the same at AAPS, so i cant guide by AAPS trend, i have to go always  to xdrip.

**Comment by robertrub** [comment]
@idalioreis The different trends in xDrip and AAPS is "normal" as xDrip shows the arrow based on the last 2 BGs while AAPS uses a longer delta (or the one produced by Dexcom, can't recall exactly)

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/4b6eab6aa405b6906d7eb15fa1458759ab9dc3df
