### ISSUE TITLE
Bug: Danar R Bolus Pump History does not show records after new year

### ISSUE THREAD

**Issue by samihusseingit** [nightscout/AndroidAPS#2318]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
  
  My son gave a bolus but then the battery crashed in the middle.   We opened the pump history, and did a reload.  It did not show the bolus so I assumed he did not get it.
  
  We gave the insulin again, and we saw he was crashing, so I double checked the pump history directly on the pump itself.   The initial bolus was given, but not showing in the AAPS history.
  
  Upon further investigation, I know why:

 The pump history has weird dates *I believe due to new year*.

2023-01-01 New Bolus given (which I gave after checking AAPS Danar R History) 
00/00/00 Extended Bolus
00/00/00 Extended Bolus
2023-01-01 Bolus My Son Gave (Initial) which AAPS Danar R is is not showing.

This is due to an exception in:

    override fun handleMessage(bytes: ByteArray) {
        val recordCode = intFromBuff(bytes, 0, 1).toByte()
        val date = dateFromBuff(bytes, 1) // 3 bytes

  
  This is the method that fails with IllegalInstantException: 
  
    fun dateFromBuff(buff: ByteArray, offset: Int): Long {
            return DateTime(
                2000 + intFromBuff(buff, offset, 1),
                intFromBuff(buff, offset + 1, 1),
                intFromBuff(buff, offset + 2, 1),
                0,
                0
            ).millis

    }
  
and the below fails with IllegalFieldValueException:

    fun dateTimeFromBuff(buff: ByteArray, offset: Int): Long {
        return DateTime(
            2000 + intFromBuff(buff, offset, 1),
            intFromBuff(buff, offset + 1, 1),
            intFromBuff(buff, offset + 2, 1),
            intFromBuff(buff, offset + 3, 1),
            intFromBuff(buff, offset + 4, 1),
            0
        ).millis
    }
    
    both cause problems:
    
    
  For our code base, we are returning DateTime.now when faced with Exception, but I dont think that is a proper solution.  Probably ignoring such weird dates is best and allowing the Dana R Bolus history to be able to retrieve records that are in between/after/before such  00-00-00 dates rather than crash.

- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
  
  Latest master:  AndroidAPS 3.1.0.3   Build: b2b10e7654
  
  Console Log:  Attached.  It does not show both exceptions sorry about that.
  
[AndroidAPS Log.txt](https://github.com/nightscout/AndroidAPS/files/10328686/AndroidAPS.Log.txt)

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/c1fca211bffa79d19f3ed5c7dda605054f77b01f
