### ISSUE TITLE
[Latest DEV] Request: Backfill BG values with "grey" color?

### ISSUE THREAD

**Issue by parapenT1sta** [nightscout/AndroidAPS#2319]
Today replacing the sensor, I realized that after the two warm up hours a straight line was created from the last BG value before the sensor removed to the new value after two hours. Is it possible to put these values in grey or other color? Since they aren't real BG readings?

Using G5 with BYODA. The readings aren't sent to xDrip as screenshot below.

Screenshot of the straight line in AAPS:
![Screenshot_20230101-124920](https://user-images.githubusercontent.com/608650/210171218-32077691-2d1d-4438-a975-60b14c6c10f4.png)

in Xdrip:
![image](https://user-images.githubusercontent.com/608650/210171256-609246b3-ecff-410d-94e8-9f549db33b89.png)

**Comment by kristinsmotz** [comment]
Seen this for the first time today as well with our G6 sensor change. Love that values are filled via smoothing where there would otherwise be no data, but I agree especially when filling larger gaps they could be a different color to clarify that they're not "real data".

**Comment by parapenT1sta** [comment]
@MilosKozak This was already done. correct?

https://github.com/nightscout/AndroidAPS/commit/556c1a048fa591a28afebd7ad3752f98be4ac09f

**Comment by MilosKozak** [comment]
yes
