### ISSUE TITLE
Updated from 2.8 to 2.8.1.1 : imperfect profile import

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#232]
I was on 2.8.0. Saved the settings. Stopped the app and uninstalled.
Installed 2.8.1.1 on phone Samsung S9 Android 10.
Gave all the permissions.
Restarted the app.
Imported the last profile. 
Restarted the app, the phone but AAPS still says no profile.
I got the check mark saying the profile was imported. My settings and objectives are imported but I still get no profile message.

![Screenshot_20210113-174714_AndroidAPS](https://user-images.githubusercontent.com/76626474/104485709-1e4cbe00-55cb-11eb-8fb1-cc7c9325599f.jpg)
![Screenshot_20210113-175651_AndroidAPS](https://user-images.githubusercontent.com/76626474/104485745-2ad11680-55cb-11eb-9afa-35df252e610a.jpg)
![Screenshot_20210113-175712_AndroidAPS](https://user-images.githubusercontent.com/76626474/104485786-38869c00-55cb-11eb-89e9-18f06adaff26.jpg)
![Screenshot_20210113-180709_AndroidAPS](https://user-images.githubusercontent.com/76626474/104485806-40464080-55cb-11eb-8797-67af641e7bd7.jpg)

**Comment by robertrub** [comment]
Ok, solved it :) It is a translation error only. I needed to activate my profile.

"Pas de profile définie" means there are no defined profiles. The message should be 
"Pas de profile activé" which means no activated profiles.

**Comment by MilosKozak** [comment]
join cowdin and fix the translation if needed
