### ISSUE TITLE
A small, optical improvement suggestion.

### ISSUE THREAD

**Issue by elgrupo123** [nightscout/AndroidAPS#2328]
A small optical improvement suggestion.

The abbreviations for days and hours in German (or English) confuse me every time and our 8 year old son does not quite understand it either😉.
d - Day
s - hours or Stunden??

t. and std. or d. and h. would be, I think, more understandable.

Thanks for your great work!!!

![Screenshot_20230105-141756](https://user-images.githubusercontent.com/92778761/210793179-c6b76fe3-ea2e-4a73-8ab2-e2f70e252684.png)

**Comment by MilosKozak** [comment]
it must be done through translation
