### ISSUE TITLE
AAPS crashes when applying the setting

### ISSUE THREAD

**Issue by Viewquest** [nightscout/AndroidAPS#2329]
I have the following error since the last DEV F version: If I go to settings, AAPS is terminated immediately. All other functions are still applicable. In addition, since the penultimate version, the Eop2 has been beeping when I make a profile change. Attach to the last LOG.
[AndroidAPS_LOG_1673011924856.log.zip](https://github.com/nightscout/AndroidAPS/files/10360491/AndroidAPS_LOG_1673011924856.log.zip)

**Comment by MilosKozak** [comment]
what is last dev version?

**Comment by Viewquest** [comment]
![Screenshot_20230107-112358](https://user-images.githubusercontent.com/94917775/211145679-5cecbe53-6056-478b-9741-428dafcf58d4.png)

**Comment by Viewquest** [comment]
AAPS only crashes when I press the Settings button.
![Screenshot_20230107-113346](https://user-images.githubusercontent.com/94917775/211146192-ae7745e5-05e8-42c9-88e9-6c047581c5f3.jpeg)

**Comment by MilosKozak** [comment]
there is already newer commit
![image](https://user-images.githubusercontent.com/11146458/211172955-1a624979-3aad-49ac-a4a1-3377443e391d.png)

try latest dev

**Comment by Viewquest** [comment]
Thank you, I will do it immediately.

**Comment by Viewquest** [comment]
Installed the new version and still AAPS crashes when using the "Settings" button.

**Comment by Viewquest** [comment]
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/10368170/AndroidAPS.log)

**Comment by MilosKozak** [comment]
there is no app start in log

**Comment by Viewquest** [comment]
Ok, how can the error be fixed. The version from 01/02/2023 did not have this error.

**Comment by MilosKozak** [comment]
do not open all preferences but only plugin preference one by one .
It's probably in some I don't use

**Comment by Viewquest** [comment]
Thanks for the hint. I `ll do it. Go to Kodnfiguration and can also set everything for DYNISF. Just think that the error irritates many users.

**Comment by vanelsberg** [comment]
Can not repro this (dev-f #4b6eab6afrom, fullrelease, 08/01).
DASH/BYODA, not using DYNISF?

**Comment by Viewquest** [comment]
I use the ClucoMen Pump and Xdrip. I no longer use Byoda and Dash.

**Comment by MilosKozak** [comment]
open all availavable preferences from Config Builder directly

**Comment by sfriedriszik** [comment]
@MilosKozak I have exactly the same problem. From the main overview -> 3 dots menu -> settings AAPS crashes directly.
it only happens with configured EO patch pump. I suspect it's due to the recent changes made to the EO Patch Pump. This problem does not exist in a version from 01/04/2023.

**Comment by Viewquest** [comment]
The last two updates now also have the problem with NS. As soon as I want to go to the NS settings, the AAPS crashes. In addition, the data will no longer be transferred to fNS. The error message appears: Error i.o.socket.engineio.client.EngineIOExcception.xhr poll error

**Comment by Viewquest** [comment]
![Screenshot_20230111-063835](https://user-images.githubusercontent.com/94917775/211770395-9cccc44d-a621-48cb-ac74-a4c5359da524.png)

**Comment by MilosKozak** [comment]
@Viewquest regarding crash update. you are using old version

**Comment by Viewquest** [comment]
Hello Milos, I can't get into NS at all to be able to change something if necessary. Also when I go through the configuration, AAPS crashes.

**Comment by MilosKozak** [comment]
I see the crashed on Pixel 4a using old version

**Comment by Viewquest** [comment]
<img width="885" alt="Bildschirm­foto 2023-01-11 um 14 25 21" src="https://user-images.githubusercontent.com/94917775/211817695-a23e06b5-28da-4eed-aa21-d99efffc177d.png">
Do you mean the NS version?

**Comment by MilosKozak** [comment]
AAPS version

**Comment by sfriedriszik** [comment]
@MilosKozak Sorry, it's working again for me at the moment. I'll report back if the error crashes again.

**Comment by Viewquest** [comment]
I have the AAPS 3.1.0.3-def-f 11.01.2023

**Comment by MilosKozak** [comment]
I see crashes comming from 7ad13882ef 
The data is only date of build, not version

**Comment by Viewquest** [comment]
![Screenshot_20230111-151730](https://user-images.githubusercontent.com/94917775/211829178-40f77ecd-7437-40a6-bd8b-48f17912178c.png)
