### ISSUE TITLE
AAPS/NSClient watchface improvement - add temp target display option

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#2335]
Absolutely loving the watch faces in the wear app from NSclient and AAPS. The only thing missing is an option to display temp-target. I know I can see it if I go to settings, but that only applies to AAPS watchface.

Maybe a thin grey line like in Nightscout could illustrate that a temp-target is active?

That way it will be easier to remember to turn of temp-target if it's displayed on the watch faces when active.

**Comment by olorinmaia** [comment]
Don't need to be a visual thing either. Maybe if TT is active text "TT: target-value" could show on custom watch face when TT is active. @Philoul

**Comment by olorinmaia** [comment]
Or another option, like on Widget:
If normal target display value with default font-color.
If target is adjusted by autosens or DynIsfSens display value with green font-color.
If temp target display value + (duration in hour and minutes') with yellow font-color.

**Comment by olorinmaia** [comment]
@Philoul is this now easier to accomplish with latest changes in dev?

**Comment by Philoul** [comment]
It's neither easier nor more complicated...
I just have to take some time to develop it 😉.
=> I have to add 3 views within custom watchface layout (one to manage main user, and 2 additional views for external users now available for the followers), update code to manage these views with text and colors, and update communication to send data.
Maybe add a new parameter to manage if Target should be visible or hidden in watchface (😱 we are trying to reduce them to simplify settings... see topic opened yesterday in ux-design channel 😂)

Then users will have to create new CWF or update existing one to include this new information.

**Comment by Philoul** [comment]
See PR #3551 ;-)

**Comment by olorinmaia** [comment]
Ty @Philoul
