### ISSUE TITLE
AAPS Watch bolus calc improvement - add calc to treatments tab

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#2339]
AAPS watch bolus calculator is a great feature, especially that you can lock the choices so that caregivers at school wont hit the wrong buttons when bolusing. The only thing missing is the log from the calculation of the bolus when this is done from the watch.

Is this something that could be possible to improve so that bolusing from watch also add "Calc" in treatments tab in AAPS?

Treatment 18:14 is done from AAPS calculator on the phone and 17:15 from calculator on watch

Reason: To see the calculation and especially what percent is used to bolus when caretakers are allowed to change the percent of the bolus to be given from watch calculator.

![image](https://user-images.githubusercontent.com/114103483/211930621-fa87f9f8-fa2d-4d66-9f20-0c372ddd9c17.png)
![image](https://user-images.githubusercontent.com/114103483/211931266-b792b279-b2d1-4272-b64f-933a19204b39.png)

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/34ba03bef4ddcd3233edc619af2e812b93889c75

**Comment by olorinmaia** [comment]
@MilosKozak I'm pretty new to github and AAPS. Does this mean that the improvement will be implemented in the next master version of AAPS? :)

**Comment by MilosKozak** [comment]
yes. now is in dev
