### ISSUE TITLE
App shuts down when config tool button is selected for any displayed tab (Omnipod user)

### ISSUE THREAD

**Issue by Jane49** [nightscout/AndroidAPS#234]
Reporting bugs
9.14 a.m.
selected opens smb in config tab  page
a40df15e4-2021.01.12-14:14
[AndroidAPS._2021-01-15_02-42-31_.3.zip](https://github.com/nightscout/AndroidAPS/files/5819557/AndroidAPS._2021-01-15_02-42-31_.3.zip)
[AndroidAPS._2021-01-15_02-42-31_.4.zip](https://github.com/nightscout/AndroidAPS/files/5819558/AndroidAPS._2021-01-15_02-42-31_.4.zip)
[AndroidAPS._2021-01-15_09-15-26_.0.zip](https://github.com/nightscout/AndroidAPS/files/5819559/AndroidAPS._2021-01-15_09-15-26_.0.zip)

--------------

- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/EN/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
use 2.8.1.1
