### ISSUE TITLE
EOPatch and AAPS Erros

### ISSUE THREAD

**Issue by Viewquest** [nightscout/AndroidAPS#2347]
Hello Milos, I noticed yesterday that after changing the EOPatch pump I could no longer access the configuration of the DYNISF. AAPS kept crashing. Today I switched to the virtual pump. I wanted to test if I could work with that in the configuration. With this setting, everything could operate normally. I believe that an error has crept in with the EOPatch. Currently I have the DEV G 378002df33 installed. It would be great if the error can be detected and fixed.---------

![APK DEV Version](https://user-images.githubusercontent.com/94917775/212550171-8631719d-13f0-4099-954d-b9f004640f4b.png)

**Comment by MilosKozak** [comment]
i cannot replicate the issue. pm me crashing config and master pass

**Comment by Viewquest** [comment]
I will set a new pod tonight and then email you the settings and master password.

Many greetings
Lothar

**Comment by Viewquest** [comment]
Hello milos,

Here comes the data and my master password, as requested. I changed the EOPatch and went to the Settings button after the start. AAPS crashed again. Also, before that I built and installed the latest APK in Android Studio
.

Mein Masterkennwort: 31121957

**Comment by MilosKozak** [comment]
resolved by https://github.com/nightscout/AndroidAPS/commit/fa2b9bddcceee6c9dc071e6055d8ff365d5b6e0b
