### ISSUE TITLE
Dev loosing Accu_Chek Combo pump pairing after phone restart

### ISSUE THREAD

**Issue by tkvasnicka** [nightscout/AndroidAPS#2350]
on my new Pixel 6 (with android 13)
i was not able to pair my pump (Accu_Chek Combo) with Ruffy 
i moved to the DEV version and paired with V2 driver 
pairing is relatively smooth - but it always works only with a second try
however with every phone restart so far AAPS is loosing the pairing, showing the pump as unpaired.
the pump stay listed among the bluetooth known devices though. 
pairing again works only after removing the pump from the list.

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by swissalpine** [comment]
Can't confirm this problem on my phones:
Unihertz Jelly 2 and Samsung Flip 4.
Restarts doesn't change the pairing.

**Comment by parapenT1sta** [comment]
Using latest DEV, Combo on a Google Pixel 4a with no issues at all.

**Comment by MilosKozak** [comment]
Closing as not replicable
