### ISSUE TITLE
NSv3 : Strange NS web page behaviour if upload on charge set on phone

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2352]
Very strange missing points and data since I started using NSv3 on AAPS.

Setting: AAPS last Dev, NS tab, settings, do not upload if on battery, NS and Mongo db both running in containers on my QNAP NAS.

While NS is not uploading, the NS page is missing data. Normal behaviour. When phone is charging, the data is uploaded and it is no more "missing" in the Mongo db.

On NSv3, once the data is uploaded, actualising the web page does NOT fill the holes in the graph. I need to restart the containers to have the graph filled (which proves that the data is in the Mongo db). But, the last connection data is still missing on the upper part.

Till now, when using v1, I didn't have the "holes" in the graph. But, I had not tested as thoroughly.

![Screenshot_20230113_175703_AAPS.jpg](https://user-images.githubusercontent.com/76626474/212842135-8dca3390-ce95-417a-9785-47bbd43cc134.jpg)

![Screenshot_20230117_084425_DuckDuckGo.jpg](https://user-images.githubusercontent.com/76626474/212842273-f7769010-b2af-4310-8c70-0cd8e257087b.jpg)

![Screenshot_20230117_084842_DuckDuckGo.jpg](https://user-images.githubusercontent.com/76626474/212842948-cff09755-d524-40eb-9c74-c6b79f35a42d.jpg)

**Comment by MilosKozak** [comment]
this should be reported as NS bug
