### ISSUE TITLE
Minor bug : AAPS doesn't detect NS version (v15.0.0 beta)

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2356]
Not really important. I installed NS latest_dev version to test the _holes in the graphs_ problem. That problem has been solved.

In AAPS, _About_ , it says NS version unknown.

![Screenshot_20230118_174342_AAPS.jpg](https://user-images.githubusercontent.com/76626474/213242925-a6e49af0-56c7-4f60-b986-01ddfa4cb13b.jpg)

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/d67e13e105881e2c88889a6bd5f4b2baa2b813c2
