### ISSUE TITLE
BUG NSv3 does not do total synchronization 

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2358]
I had to try several times in order to do a total sych with NS using NSv3

Then it started the synch but stopped in the 12th (today is 18th)...

![Screenshot_20230118_221923_AAPS.jpg](https://user-images.githubusercontent.com/76626474/213297346-5bc5b018-012e-4183-acaf-e6c163e2757b.jpg)

![Screenshot_20230118_182857_AAPS.jpg](https://user-images.githubusercontent.com/76626474/213297417-e6243c37-3f76-4163-b610-78e5f2c4d419.jpg)

Look at the logs between 22:14 and 22:16. I'm not sure if the sync/upload had started when I exported the logs.

![AndroidAPS_LOG_1674076599701.log.zip](https://github.com/nightscout/AndroidAPS/files/10451245/AndroidAPS_LOG_1674076599701.log.zip)

**Comment by MilosKozak** [comment]
it this is repeatable after cleaning db and resetting to full sync, pm me your config

**Comment by robertrub** [comment]
Just tested. Cleared db for data over 3 months (minor bug : no message telling that it has been done) then tapped Total sync. Got the alert telling that it might take a long time. OKed. Nothing happened.

NS setup to not upload on battery but it is charging ATM.

Which config do you need ? The whole exported settings file or just the NS settings?

**Comment by MilosKozak** [comment]
send me your config and pass

**Comment by robertrub** [comment]
@MilosKozak  Done via DM in Discord.
