### ISSUE TITLE
ERROR WHEN ESTABLISHING THE PROFILE WITH ORANGELINK PRO

### ISSUE THREAD

**Issue by pagoblan** [nightscout/AndroidAPS#2362]
I am using Medtronic 754 with AAPS 3.1.0.3 dev F, and with Rileylink without problems, but I have bought a backup OrangeLink Pro c, updated with the latest available firmware and once linked with AAPS everything works except if I modify the profile and I try to activate NOT ESTABLISHED, constantly getting the error "Unable to establish the basal profile". I've tried creating new profiles, and it won't let me set them either, but if you change basal rates and send SMB,...

**Comment by MilosKozak** [comment]
that's out of scope of AAPS. Ask in OrangeLink groups

**Comment by pagoblan** [comment]
Ok, gracias.  Lo cierro.
