### ISSUE TITLE
AAPS Client CGM button missing

### ISSUE THREAD

**Issue by elgrupo123** [nightscout/AndroidAPS#2365]
CGM button missing ( 3.1..0.3 dev.-g.)

Best wishes.

**Comment by MilosKozak** [comment]
it does work only for xdrip and BOYDA and it must be enabled in preferences. is it your case?

**Comment by elgrupo123** [comment]
Yes, XDrip is correct. There is no option to select it. This only affects AAPS Client, not AAPS Full Release.

**Comment by MilosKozak** [comment]
![image](https://user-images.githubusercontent.com/11146458/213751533-14a8da90-d118-4bb7-af89-9b91f3faa3a6.png)

**Comment by MilosKozak** [comment]
nsclient has only NS as BG source thus these option is not there.
It's by design
