### ISSUE TITLE
[Latest DEV] NS Client is unselected after xDrip option

### ISSUE THREAD

**Issue by parapenT1sta** [nightscout/AndroidAPS#2367]
Latest DEV with NSClient V1 or V3 active if xDrip+ (Send data to xDrip) option is selected, then NSClient are unselected automatically.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/27e91182a160dc9bb9b997dd96c3665c6f2c3fc6
