### ISSUE TITLE
PasswordReset does not work for Accu-Check Spirit Combo

### ISSUE THREAD

**Issue by sdpeixoto** [nightscout/AndroidAPS#2369]
I tried to reset the master password on version 3.0.0.1 (Build: 479bfc410-2022.03.03-12:36) following the instructions given in the docs for v3.0 and above. I created the "PasswordReset" empty file and placed it in AAPS/extra folder from mobile phone and restarted the app. The file disappeared and the app showed a text message stating that the password had been set. But the password still isn't the Combo serial number.

I there something I'm doing wrong or overlooking? Or is there a different password for the Accu-Check Spirit Combo pump?
Help would be really appreciated.

**Comment by MilosKozak** [comment]
AAPS 3.0 is unsupported.
Upgrade to 3.1 first

**Comment by sdpeixoto** [comment]
Hi @MilosKozak,

Thanks for the feedback.

Following your suggestion, I have upgraded APPS to 3.1.0.3 version but master key reset functionality still doesn't work as described in the documentation.
I copied a "PasswordReset" empty file to AAPS/extra folder, restarted APPS application, file got droped, saw a popup message saying that password got changed, but then I when enter insulin pump serial number, it says that password is not correct.

Help would be really appreciated.

**Comment by sdpeixoto** [comment]
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/10528082/AndroidAPS.log)
[AndroidAPS._2023-01-28_13-30-08_.0.zip](https://github.com/nightscout/AndroidAPS/files/10528085/AndroidAPS._2023-01-28_13-30-08_.0.zip)

In attachment you can find AAPS log files.

**Comment by sdpeixoto** [comment]
Any news please?

**Comment by parapenT1sta** [comment]
@sdpeixoto Which Combo driver are you using? V1 or V2? With V1 and Ruffy the pump serial number was the Mac Address.
