### ISSUE TITLE
Bug ?? Connected to power but NS not uploading

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2370]
I'm not sure if it is a bug or an Android limitation...

NS set to upload _when charging_ only. The phone is connected to power but the battery is full => NS doesn't upload. 

Technically, the phone isn't charging (as the battery is full) but it is still connected to external power.

It would be logical to still upload in this case as the "limitation" is there to limit battery drain and with power connected, there is no drain on battery.

**Comment by MilosKozak** [comment]
![image](https://user-images.githubusercontent.com/11146458/213860502-ddc411b3-ba42-453c-a918-1f92f103f61c.png)
and uploading

**Comment by MilosKozak** [comment]
i did small update. connection status is updating faster now

**Comment by robertrub** [comment]
Will test your update this afternoon. 

My phone does not upload when battery is charged (I can see when it is not uploading with the holes in the NS chart)

![Screenshot_20230121_115604_DuckDuckGo.jpg](https://user-images.githubusercontent.com/76626474/213863776-f3b95bb1-2190-4416-b8bb-657fcb8c412b.jpg)

**Comment by MilosKozak** [comment]
isn't this issue the one with NS?
