### ISSUE TITLE
Feature Request: Allow automation integration with Fit Cycle Tracking

### ISSUE THREAD

**Issue by tim2000s** [nightscout/AndroidAPS#2375]
Given the variations to profiles during the menstrual cycle, allow integration with Fit's cycle tracking to allow automations to make changes to profiles accordingly. 

Potentially allows automation with, for example, Oura, Natural Cycles and Fit to learn about when cycles occur and then automatically adjust settings.

**Comment by ArthurusDent** [comment]
There is already this issue: #1586

**Comment by tim2000s** [comment]
Moved discussion to linked topic
