### ISSUE TITLE
Export parameters in 2.8 then import in 2.8.1.1 : The sensor age data was lost

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#238]
I export my parameters in 2.8. Uninstall 2.8 and install 2.8.1.1 and import my parameters. Everything came back EXCEPT the age of the BG sensor, it had no information on the age of the sensor.

**Comment by MilosKozak** [comment]
you have to upgrade AAPS to preserve all data (not remove and install new). import contains only settings
