### ISSUE TITLE
Omnipod "Pump" (Orange/EmaLink) battery age not shown (Not urgent)

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#239]
I have an Omnipod with an Orangelink. 

AAPS 2.8.1.1 shows the battery level of the Orangelink, which is working :)

But, if I note (on the Actions page) _Pump battery change_ with a **date** (today or before), the information is noted on the care portal but not shown in the actions page. 

Orangelink battery is NOT the pump battery but it is the only necessary battery information needed with Omnipod. 

As Orangelink is in beta testing, having the age of the battery shown will help giving them the necessary information too.

![Screenshot_20210117-140905_AndroidAPS](https://user-images.githubusercontent.com/76626474/104844028-09737180-58ce-11eb-8ec3-732f70c30a0f.jpg)
![Screenshot_20210117-140839_AndroidAPS](https://user-images.githubusercontent.com/76626474/104844030-0a0c0800-58ce-11eb-8f37-bb2327a11d67.jpg)

**Comment by vanelsberg** [comment]
Confirming.
Seeing this too.

**Comment by ToreBj** [comment]
+1

**Comment by andyrozman** [comment]
OrangeLink is the only RL/RL-clone that we can read battery from... 

And display you have shown, would show age of battery in pump (your case Pod). We can't read battery from Pod, so in this case age shouldn't be shown at all... 

Displaying Battery level of OL, wouldn't be really correct here... Especially since we don't know how long we have used the battery on OL.

**Comment by robertrub** [comment]
Sorry, I don't agree on battery age for OL having no meaning. My OL arrives at 50% in about 1 month. Even though it says "50%", when I measure the battery voltages, they are on the low side and more importantly, OL has more disconnect/reconnect problems. I use the battery age in NS to know when I'll need to change the batteries.  As we already have this information, it would be nice to show it ;)

As for DASH, no battery info is needed and, if possible, the "battery info" line should not be shown at all.

**Comment by vanelsberg** [comment]
@robertrub Agree that for OL battery age would make some sense. This could then be covered by the user option to enable the field?

(Just my personal view: Remembering battery **percentage** of OL on the EROS tab was quite accurate I mostly monitored this to determine battery health. Personally I had no interest in battery **age** - other then when testing OL to get and idea on how many days batteries would last - used pen-and-paper for that ;-)

**Comment by Andries-Smit** [comment]
For Omnipod EROS, the age should be working, when the "Change battery pump" action is performed. Change action button is only available for EROS when enabled through the preferences. For Dash battery section in action and overview status light will be hidden completely https://github.com/nightscout/AndroidAPS/pull/1328
