### ISSUE TITLE
*AndroidAPS** 3.1.0.3-dev showing logo on Omnipod EROS Pod management view (affects readability)

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#2390]
**AndroidAPS** 3.1.0.3-dev-g
**Build**: `ba58fb5ff7`
**Flavor**: fullrelease / Engineering mode

**Problem description**:
For EROS pump, the AndroidAPS logo is unexpectedly shown on the POD tab when on Pod Management (button press)?
Problem is the logo stays in overlay on "Pod Management" (making it unreadable) and while on Activate/Fill Pod.

**Additional Info**:

Similar problem was fixed for DASH through issue https://github.com/nightscout/AndroidAPS/issues/2250

**EROS POD tab:**

![Screenshot_20230204_140411_AAPS](https://user-images.githubusercontent.com/45144129/217220852-76f9d456-a270-4e07-b38e-e92e37ce4c9f.jpg)
![Screenshot_20230204_140426_AAPS](https://user-images.githubusercontent.com/45144129/217220845-46dcf38d-6603-44a4-b614-b836cc7cb644.jpg)
![Screenshot_20230204_140815_AAPS](https://user-images.githubusercontent.com/45144129/217220849-f3d6325d-38ff-4df1-b641-d51f2fc3ceb3.jpg)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/3326225d4f01b82d46a320ae4382e2e343c22252
