### ISSUE TITLE
Backup failed

### ISSUE THREAD

**Issue by Viewquest** [nightscout/AndroidAPS#2393]
Yesterday I got the new AAPS 3.1.0.3-dev-g
Installed Build: 1da267f05c-2023.02.08 and found that AAPS crashes and reboots on maintenance/export setup. Reinstalled the previous version and the error was gone.
I use the Eopatch, XDrip and Pixel 6a.
![Screenshot_20230209-084306](https://user-images.githubusercontent.com/94917775/217748797-0797214d-1d53-44d3-807e-84e05024f42c.png)

**Comment by mjhuisman** [comment]
Same here. I cant export settings into json. Aaps doesnt have the rights to write an export file, but it has.

**Comment by Viewquest** [comment]
The point is that I can no longer export settings. When I want to do that with this version, AAPS crashes and restarts.

**Comment by Viewquest** [comment]
Now I installed the latest version (09_02_2023_d7fd4d0_app-full-release.apk) and the same problem. AAPS restarts when backing up.

**Comment by MilosKozak** [comment]
reverted
