### ISSUE TITLE
[2.7] XDRIP tab does not show all entries

### ISSUE THREAD

**Issue by thomasmenges** [nightscout/AndroidAPS#24]
Since switching to AAPS 2.7 i have the problem that on the XDRIP tab not all BG entries are shown. More than the last 2 hours are not shown.
On the overview page everthing ist correct. The actual BG value is shown also on the graph.
The entries are also stored in NS correctly.

What can be done ? 

By the way. After closing AAPS and strating new, the values are shown.
![20201002_090409](https://user-images.githubusercontent.com/37514390/94915609-7c86e280-04ad-11eb-828b-8fc4c1b42d9b.jpg)
![20201002_090503](https://user-images.githubusercontent.com/37514390/94915610-7db80f80-04ad-11eb-82aa-506b1a789d78.jpg)

**Comment by MilosKozak** [comment]
resolved in https://github.com/nightscout/AndroidAPS/commit/79d24dfeca846dd250a43ecf667f9ffd17332a98
