### ISSUE TITLE
[Latest DEV] No Pump and OpenAPS info on NS15 with NSclientV3

### ISSUE THREAD

**Issue by parapenT1sta** [nightscout/AndroidAPS#2409]
First I have to tell I have xDrip sending BG values to NS since AAPS doesn't send it even if it is selected on NS options.

Is anything I can do yo fix it?

No Pump and OpenAPS is sent to NS with NSClient V3 and the predictive lines are not in the latest BG reading dot.
Compare the behavior on NSClient V3:
![Screenshot_20230215-081607](https://user-images.githubusercontent.com/608650/218972948-f8d4f5d3-b88a-40e6-9368-7a2043db7604.png)

On NSClient V1:
![Screenshot_20230215-082141](https://user-images.githubusercontent.com/608650/218973059-c53c9901-2b39-4a66-b946-241cac1ada4a.png)

**Comment by MilosKozak** [comment]
1) xdrip can send to NS itself thus this option is not available in AAPS
2) status is uploading well for me. more info needed
![image](https://user-images.githubusercontent.com/11146458/218983068-9c306e6a-136c-47c6-8437-ba75e27d8b60.png)

**Comment by parapenT1sta** [comment]
@MilosKozak 
1. I was talking about xDrip since on V3, there is the info that all uploaders should use V3 and I think xDrip is V1, that was my confusion.
![Screenshot_20230215-093802](https://user-images.githubusercontent.com/608650/218990638-acd34761-48ce-49b1-9e2c-9d46c7cdf5c4.png)

2. What more info do you need from me?

**Comment by MilosKozak** [comment]
1) sending to xdrip is no more related to comm with NS
2) logs, screenshots from nscv3 tab

**Comment by parapenT1sta** [comment]
Logs and screenshots: [AAPS_NS15.zip](https://github.com/nightscout/AndroidAPS/files/10741905/AAPS_NS15.zip)

**Comment by parapenT1sta** [comment]
One more screenshot with V3, for now I am going back to V1:
![image](https://user-images.githubusercontent.com/608650/219023095-b6ba3a8a-586c-4a9e-aa49-931cc19575cc.png)

**Comment by MilosKozak** [comment]
it's an issue with your NS, not AAPS. You may try new deploy

**Comment by MilosKozak** [comment]
or token is bad?

**Comment by parapenT1sta** [comment]
I rechecked the token but I'm going to create a new one. I had redeploy recently.

Will give a feedback

**Comment by parapenT1sta** [comment]
@MilosKozak Thank you for the tip about token, I just realized since I migrated to a new server I didn't set the token for admin role, issue now solved!! :-D
