### ISSUE TITLE
[2.8.0] Eating reminder does not work in NSClient and Pumpcontrol applications

### ISSUE THREAD

**Issue by reijoahola-nightscout** [nightscout/AndroidAPS#241]
Just noticed that "Eating reminder" (Bolus advisor new feature in 2.8.0 and 2.8.1.1) does not cause alarm/notification when used in NSClient and Pumpcontrol applications. It can be activated from Bolus advisor without any indication that there will be no alarm later.

 The reason probably is that those applications have disabled Automation function. In AAPS applications where esting reminder works this function seems to utilise Automation (automatically activated rule).

Should this feature (eating reminder) be disabled (greyed) in Bolus advisor in these applications.

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/8801c28176419ecda84a2278ce1701144ab6ac83
