### ISSUE TITLE
AndroidAPS 3.1.0.3-dev-h: "NSCLIENT Status not available"

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#2412]
**AndroidAPS** 3.1.0.3-dev-h
**Build**: `64f89528d3`
**Flavor**: fullrelease / Engineering mode

**Problem description**:
NCLIENT stopped working. It connects but the stays idle showing **Status not available**

- NSCLIENT ("v1") configured in AAPS
- Connecting to Nightscout  version 14.2.6
- This configuration was working for me until upgrading from 3.1.0.3-defg build#336225d4f to later builds

[AndroidAPS_LOG_1676464451464.log.zip](https://github.com/nightscout/AndroidAPS/files/10747512/AndroidAPS_LOG_1676464451464.log.zip)

**Comment by MilosKozak** [comment]
def-h works only with NS 15 (dev)
