### ISSUE TITLE
AAPS not syncing properly with AAPSClient

### ISSUE THREAD

**Issue by bchris21** [nightscout/AndroidAPS#2422]
Versions: 
AAPS Dev-h 0ae21b7a7d
NSClient Dev-h 21b3a70ad9

AAPS values are different than AAPSClient even though they seem to properly sync.

Carbs and Temp Targets sent via NS treatment menu do not pass to AAPS.

![Screenshot_20230218_165219_info.nightscout.aapsclient2.jpg](https://user-images.githubusercontent.com/4725280/219899588-d62f27d8-9a3f-4a5d-842a-b6054a111d11.jpg)

![Screenshot_20230218_165237.jpg](https://user-images.githubusercontent.com/4725280/219899590-048df86b-7c06-4e77-b4a5-a9e06a07a708.jpg)

![Screenshot_20230218_165411_com.google.android.apps.photos.jpg](https://user-images.githubusercontent.com/4725280/219899589-5eaf9ff7-088d-4009-8a4d-1d3d59213a80.jpg)

![Screenshot_20230218_165612.jpg](https://user-images.githubusercontent.com/4725280/219899591-108b66b6-1ee2-4444-84dd-2b071d0f1068.jpg)

![AndroidAPS_LOG_1676754291117.log.zip](https://github.com/nightscout/AndroidAPS/files/10775212/AndroidAPS_LOG_1676754291117.log.zip)

![AndroidAPS_LOG_1676754237579.log.zip](https://github.com/nightscout/AndroidAPS/files/10775214/AndroidAPS_LOG_1676754237579.log.zip)

NS hosted on 10be.de

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
read realease notes , especially the part regarding websockets

**Comment by bchris21** [comment]
> websockets

Is there a way to sacrifice battery life to faster sync or it's a fixed functionality with v3 to have less frequent communication?
I am monitoring my son at school and I would like to have values syncing as soon as possible.
Thank you

**Comment by bchris21** [comment]
> > websockets
> 
> Is there a way to sacrifice battery life to faster sync or it's a fixed functionality with v3 to have less frequent communication?
> I am monitoring my son at school and I would like to have values syncing as soon as possible.
> Thank you

Websockets are on, on both AAPS and NSClient but still there are delays.

**Comment by bchris21** [comment]
With websockets ON or OFF there is an inconsistency in IOB and Carbs between AAPS and NSClient.

![Screenshot_20230219_012707_com.teamviewer.teamviewer.market.mobile.jpg](https://user-images.githubusercontent.com/4725280/219962161-35b4ef94-6929-434f-ad8d-fe2b211d1e3c.jpg)

![Screenshot_20230219_174319_com.google.android.apps.photos.jpg](https://user-images.githubusercontent.com/4725280/219962159-61221040-252f-436f-bfc7-6133664beeac.jpg)



Is there something I can do to troubleshoot? Shall I delete the database on AAPSClient ?

Thank you

**Comment by MilosKozak** [comment]
I see different time on both screenshots

**Comment by bchris21** [comment]
Sorry Milos, wrong screenshots were chosen. Titles were truncated when chosen via mobile app and attached the wrong ones.

I still have an issue though with wrong carbs added via NSClient. They are added to AAPS (and NS) but they are not deleted when removed from NSClient Treatments.

That's a bit of an issue when kid is at school.

Test was made on 20:22 with 2gr test carbs entered from NSClient. They were deleted a few seconds away from treatments menu, but they are still in AAPS.

![Screenshot_20230303_210428_com.google.android.apps.photos.jpg](https://user-images.githubusercontent.com/4725280/222817289-72109b96-7752-4bec-85b4-a4d69126cecd.jpg)

![Screenshot_20230303_205537_info.nightscout.aapsclient2.jpg](https://user-images.githubusercontent.com/4725280/222817290-06a25e26-73d4-4bcd-aa2f-f1ea59acb370.jpg)



I don't know if logs help here. I attach from both.

AAPSClient2 3.1.0.3-dev-h
Build: da76506e01-2023.02.21

AAPS 3.1.0.3-dev-h
Build: da76506e01-2023.02.21

![AndroidAPS_LOG_1677873353708.log.zip](https://github.com/nightscout/AndroidAPS/files/10885757/AndroidAPS_LOG_1677873353708.log.zip)

![AndroidAPS_LOG_1677873380036.log.zip](https://github.com/nightscout/AndroidAPS/files/10885758/AndroidAPS_LOG_1677873380036.log.zip)

Final question:
When passing a Temp Target with NSClient, it syncs only when BG change arrives thus every 5th minute. Is this expected or should sync right away when NSClient sends a change ?

Thank you

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/d8235bab29db86a9abb8765c09009fc404a7756e
