### ISSUE TITLE
When syncing to xDrip, only BG and basals are uploaded.

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#2424]
**AndroidAPS** 3.1.0.3-dev-h
**Build**: `a608f55531`
**Flavor**: fullrelease / Engineering mode
**xDrip+**: version 344deb4-2022.11.16

**Problem description**:
When syncing to xDrip, treatments (Carbs & bolus) are missing. Only BG and basals are uploaded.

**Screenprints**
![aaps](https://user-images.githubusercontent.com/45144129/219956834-24763aa1-f022-48a5-a79f-32b10484c188.jpg)
![xdrip](https://user-images.githubusercontent.com/45144129/219956835-aa3ef5ac-579d-4d40-97a2-4e569471ea1f.jpg)

**Logfiles:**
[AndroidAPS_LOG_1676819528732.log.zip](https://github.com/nightscout/AndroidAPS/files/10777198/AndroidAPS_LOG_1676819528732.log.zip)

**Comment by overfrenk** [comment]
Same for me!

**Comment by parapenT1sta** [comment]
Also the same here. To get SMB on xDrip I need to setup it to download treatments from NS.

**Comment by MilosKozak** [comment]
https://github.com/NightscoutFoundation/xDrip/discussions/2636

**Comment by parapenT1sta** [comment]
I think some progress is beging made with the latest xDrip Nightly version: https://github.com/NightscoutFoundation/xDrip/commit/fcd8063a4149c59d01bc668e191eaa3c6cee5c3e

**Comment by vanelsberg** [comment]
@MilosKozak Really missing the option of syncing _all_ data to xDrip+
Any outlook/roadmap on a possible fix?

**Comment by MilosKozak** [comment]
it will start work when xdrip team implement it

**Comment by parapenT1sta** [comment]
Issue fixed with xDrip latest nightly version: https://github.com/NightscoutFoundation/xDrip/releases/tag/2023.06.17

At least it's working for me. I think this ticket can now be closed.

**Comment by vanelsberg** [comment]
> Issue fixed with xDrip latest nightly version: https://github.com/NightscoutFoundation/xDrip/releases/tag/2023.06.17
> At least it's working for me. I think this ticket can now be closed.

Nope. Nothing changed for me.

(Where was it fixed, what commit?)

**Comment by parapenT1sta** [comment]
https://github.com/NightscoutFoundation/xDrip/commit/ec2f90f7ecb12a8305e4ed9166342fafcd065918

I have AAPS syncing all the info to NS and broadcasting the info to xDrip. I enabled "Enable Broadcast to xDrip+" and "Send status line to xDrip+" in AAPS.

**Comment by parapenT1sta** [comment]
![Screenshot_20230625_221031_AAPS](https://github.com/nightscout/AndroidAPS/assets/608650/06f10e3c-ed18-4cfd-a280-e401748a328e)

![Screenshot_20230625_221048_AAPS](https://github.com/nightscout/AndroidAPS/assets/608650/68c08ea4-0caa-4373-b3a2-9ebaa86433eb)

![Screenshot_20230625_221100_AAPS](https://github.com/nightscout/AndroidAPS/assets/608650/2cdc7ab5-b085-4027-918f-0fd61465e4d6)

**Comment by parapenT1sta** [comment]
![Screenshot_20230625_225557_xDrip+](https://github.com/nightscout/AndroidAPS/assets/608650/268aa855-7f90-4479-858f-37b1c00bd52d)

**Comment by parapenT1sta** [comment]
![Screenshot_20230625_231834_xDrip+](https://github.com/nightscout/AndroidAPS/assets/608650/6e357df6-7101-4180-ac8a-c8a1f3d0ba3f)

**Comment by parapenT1sta** [comment]
> > Issue fixed with xDrip latest nightly version: https://github.com/NightscoutFoundation/xDrip/releases/tag/2023.06.17
> > At least it's working for me. I think this ticket can now be closed.
> 
> Partly. Now do see carbs and insulin treatments as data point being synced to NS. But no basal rates. NA is showing default basal rates from current profile on NS
> 
> Also COB and IOB reported on NS is wrong...?
> 
> > ....I think this ticket can now be closed.
> > So, nope, not yet...

The only issue I have is that BG values sent from AAPS aren't shown in Nighscout: https://github.com/nightscout/AndroidAPS/issues/2602 

Hopefully @MilosKozak can take a look.

**Comment by vanelsberg** [comment]
> The only issue I have is that BG values sent from AAPS aren't shown in Nighscout: #2602

With the update, xDrip is now showing showing correctly. So that problem is fixed improvement.

However, for me xDrip+ uploading to NS is ok, except for current basal rate:
NS only shows default basal values from current profile.
