### ISSUE TITLE
[3.1.0.3-dev-h] Cancel TempTarget realised in Nightscout isn't processed by NSClientV3

### ISSUE THREAD

**Issue by swissalpine** [nightscout/AndroidAPS#2428]
While TempTarget events entered in Nightscout have been accepted since this morning :-), this is not yet possible with CancelTempTarget.

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/e39c1e6dd6d80126763d17e880975848e8a56d68

**Comment by swissalpine** [comment]
I can confirm this and thank you once more!
