### ISSUE TITLE
Automations : Which line to delete

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2430]
Minor bug : In automations, I long press one line in order to delete it. The delete icon arrives but no idea which line will be deleted :( As it looks, all the active automations are checked, thus those will be deleted... 

![Screenshot_20230221_094912_AAPS.jpg](https://user-images.githubusercontent.com/76626474/220295440-d576f467-a403-4c6b-b863-bba8cded038d.jpg)

**Comment by vanelsberg** [comment]
Thins this is already fixed on latest dev?
For me it shows the "to delete" checkbox on the right of the automation(s)

**Comment by robertrub** [comment]
Hi Theo

I have the latest Dev (as usual ;) ). 

The delete icon is there but which line will be deleted ??? There is no information on that

**Comment by robertrub** [comment]
Ok, I get it. Long press shows the del icon. Hitting the del icon shows the check boxes. Hitting again the del icon (after having checked the lines) deleted the lines...
Not very clear. I don't like to hit delete (the first tap) with items I use already checked. 
Long press on a line should make appear the del icon AND the del boxes to be checked. Then, the use would be clear.

**Comment by vanelsberg** [comment]
> Long press shows the del icon

For me the bin/del icon is always showing.
To delete items:
1. I press the bin icon to show checkboxes (on the right of the screen)
2. Select one or more items to delete.
3. Press the bin icon again to confirm.

Actually this is consistent with other AAPS screens like the treatments tab?
I think the long press is a left-over from previous versions? Personally I'd like to see long-press removed as it is inconsistent and unintuitive for use?

**Comment by robertrub** [comment]
There is no Del icon in the automations

![Screenshot_20230222_134544_AAPS.jpg](https://user-images.githubusercontent.com/76626474/220626507-aea2b771-4f88-49d0-a8db-061cd40dc74b.jpg)

There is delete item in the 3 dots menu.

I agree, long press should be inactivated and either a Del icon should be added or only the 3 dots menu / delete should stay.

**Comment by vanelsberg** [comment]
Oops... for me there is....
S22 Ultra has a big screen?

![Screenshot_20230223_004729_AAPS](https://user-images.githubusercontent.com/45144129/220789556-faf45cbf-30b3-4389-8d09-34efbd792881.jpg)

**Comment by robertrub** [comment]
Do you have an Automations _TAB_ or do you open it from the hamburger menu ? Our captures do not look alike, I don't see any tabs on yours

**Comment by vanelsberg** [comment]
... opening from the hamburger menu.

**Comment by MilosKozak** [comment]
Remove/Sort option was duplicated and not working
https://github.com/nightscout/AndroidAPS/commit/3a950bcd7f35db2d74cb17c32fbe70db0192d7a2
