### ISSUE TITLE
[2.8.1.1]Home Tab 3dot preferences change name

### ISSUE THREAD

**Issue by chrisbev** [nightscout/AndroidAPS#244]
2.8.1.1 On first start Home Tab preferences are called 'Plugin preferences' 2nd entry in 3dots but after visiting the ACT Tab and back for me are called 'Actions preferences' and #242 reply says there are no preferences for ACT Tab. See pics attached. Samsung A1.
![Screenshot_20210120-051451_AndroidAPS](https://user-images.githubusercontent.com/43484095/105130326-b6bcd400-5ade-11eb-8692-6c7894390e9f.jpg)
![Screenshot_20210120-051246_AndroidAPS](https://user-images.githubusercontent.com/43484095/105130348-c3412c80-5ade-11eb-821a-511c339605ed.jpg)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/EN/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by AdrianLxM** [comment]
Thanks @chrisbev, I can reproduce that behaviour that the overview does not register it's name for the plugin specific settings.
