### ISSUE TITLE
NSCLient V3 Sync Problems

### ISSUE THREAD

**Issue by Yolotli88** [nightscout/AndroidAPS#2442]
AAPS Version: 3.1.0.3-dev-h
Build: 02a11ae902-2023.02.26
Nightscout Version 15.0,0
Engineering Mode Enabled

Issue:
NSCLient V3 shows that it is connected, but the screen shows errors and nightscout does not receive information

![Screenshot_20230228-000155_2](https://user-images.githubusercontent.com/94751487/222189667-5a18cffb-a03f-4ced-b522-407ee6a37e18.png)
![Screenshot_20230228-213145](https://user-images.githubusercontent.com/94751487/222189696-7018597d-db76-4b18-a010-969bf930a972.png)
[Log Export.txt](https://github.com/nightscout/AndroidAPS/files/10862754/Log.Export.txt)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
you token doesn't  have enough permissions.
I improved logging in this area in dev
