### ISSUE TITLE
Xdrip blood sugar

### ISSUE THREAD

**Issue by toniteh78** [nightscout/AndroidAPS#2447]
Hello, with the dev-h version I have no blood glucose data from either Nightscout or Xdrip in AAPS. Can someone explain the reason?
![Uploading Screenshot_20230303_
![Uploading 
![Screenshot_20230303_141637_AAPS](https://user-images.githubusercontent.com/61123634/222730492-bc4c0ea0-ed6a-4692-a227-7e0d191615d9.jpg)
Screenshot_20230303_141630_xDrip+.jpg…]()
140646_AAPS.jpg…]()
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by toniteh78** [comment]
![Screenshot_20230303_141637_AAPS](https://user-images.githubusercontent.com/61123634/222741882-dfc93d36-f760-4ba2-af7d-ef9148dfd37c.jpg)
![Screenshot_20230303_141630_xDrip+](https://user-images.githubusercontent.com/61123634/222741944-58e959c4-2c0b-48fa-bbc8-1b18c19299f9.jpg)
Screensho
![Screenshot_20230303_140646_AAPS](https://user-images.githubusercontent.com/61123634/222742059-81ca4e8e-a5df-4ba4-a826-f2f298bd98eb.jpg)

**Comment by parapenT1sta** [comment]
What info do you have in xDrip tab on AAPS? Was working before?

**Comment by toniteh78** [comment]
> Каква информация имате в раздела xDrip на AAPS? Работеше ли преди?

On dev-e everything was working fine now it looks like this
![Screenshot_20230303_182129_AAPS](https://user-images.githubusercontent.com/61123634/222786670-30d1372d-42a8-4a75-89bd-2bc6d8ffaf56.jpg)
![Screenshot_20230303_182107_AAPS](https://user-images.githubusercontent.com/61123634/222786673-8b0281ce-c822-4cea-aa1f-954d98334656.jpg)

**Comment by toniteh78** [comment]
what could this mean?
![Screenshot_20230303_190627_AndroidAPS](https://user-images.githubusercontent.com/61123634/222795319-6c6d6708-309a-4dc3-99c6-a625189f960f.jpg)

**Comment by toniteh78** [comment]
Is ok
