### ISSUE TITLE
AAPSClient missing entries from AAPS

### ISSUE THREAD

**Issue by bchris21** [nightscout/AndroidAPS#2449]
Both on Android 12
NS Dev15
AAPS DEV-h 
Logs attached.
Websockets ON on both.

Treatments entered by AAPS on 10:23 (25gr carbs), bolus 0.7 at 10:54 and bolus 1.1 at 12:19 not reflected on AAPSClient.

![Screenshot_20230305_134447_info.nightscout.aapsclient2.jpg](https://user-images.githubusercontent.com/4725280/222961389-507a619b-9146-4650-9d04-cc2b2c240c00.jpg)

![Screenshot_20230305_134910_com.google.android.apps.photos.jpg](https://user-images.githubusercontent.com/4725280/222961404-6f93125a-b51f-48d6-add0-867ebabafc91.jpg)

![Screenshot_20230305_135005_info.nightscout.aapsclient2.jpg](https://user-images.githubusercontent.com/4725280/222961553-92cf92f8-7093-49ae-b6ab-c2de95e214b3.jpg)

![Screenshot_20230305_135414_com.google.android.apps.photos.jpg](https://user-images.githubusercontent.com/4725280/222961599-c2c6bdaa-34a2-4b10-a8cf-26912d1fb9c7.jpg)

![Screenshot_20230305_134536_info.nightscout.aapsclient2.jpg](https://user-images.githubusercontent.com/4725280/222961320-5c65b96c-8d14-4d0e-985a-99071c8a3c69.jpg)

![Screenshot_20230305_134755_com.google.android.apps.photos.jpg](https://user-images.githubusercontent.com/4725280/222961345-cb2913f6-7030-47ca-ab77-63a613e61ce3.jpg)

![AndroidAPS_LOG_1678020298233.log.zip](https://github.com/nightscout/AndroidAPS/files/10891852/AndroidAPS_LOG_1678020298233.log.zip)

![AndroidAPS_LOG_1678020291169.log.zip](https://github.com/nightscout/AndroidAPS/files/10891853/AndroidAPS_LOG_1678020291169.log.zip)

**Comment by streethawk22** [comment]
I have the same experience. Not all comes to the AAPSclient. The comunication problem is also by the switching profile on AAPSclient App, not always get the command trough the NS to the Master App.

**Comment by MilosKozak** [comment]
could you check if there is WS reconnection around missing period?

**Comment by bchris21** [comment]
Manual NSClient restart and AAPS yes; while troubleshooting in order to see if a restart will finally push the missing treatments.
Now if there was an instant network disconnection I cannot confirm.

Let me know if I can assist troubleshooting in any way.

Without a fully working AAPSClient and NS being able to set temp targets, enter carbs etc it's very challenging to remotely control our kid while being at school. As a workaround TeamViewer/Airdroid is used to remotely control (also SMS Commands).

**Comment by gpgerrard** [comment]
Having the exact same problem with AAPSClient 3.2.0-beta1 and NS15 using v3 API.  Websockets on. Treatments appearing OK on one AAPSClient instance but not on another. Will keep an eye out for WS reconnections.

**Comment by CaroGo** [comment]
Same observation...entering carbs or tt in nightscout manually or via ifttt is not displayed and taken into account in AAPS. (Infos arrive in xdrip and nightscout).

**Comment by jumalakarhu** [comment]
I have a similar experience, but the opposite way. AAPS client is set to _not_ upload treatments and profile but to download treatments and profiles. Still when I enter 1 g carbs on AAPS client this is sent to Nightstcout side and further to AAPS. 
Also - Profiles from AAPS are not uploaded to NS and not sent to AAPS client. Tested on new install of AAPS client and another with total wipe (force stop, clear cache and storage and folders) before reinstall. If I set 
All boxes in AAPS nsv3 sync ticket except receive/backfill cgm data. Have done full sync on both AAPS an client to no avail. As it is now AAPS client does not have valid profile (
AAPS Android 12, and client android 11 dev-i, NS dev15 websockets ticked.

**Comment by MilosKozak** [comment]
> Same observation...entering carbs or tt in nightscout manually or via ifttt is not displayed and taken into account in AAPS. (Infos arrive in xdrip and nightscout).

you didn't read limitations in release notes

**Comment by MilosKozak** [comment]
> Having the exact same problem with AAPSClient 3.2.0-beta1 and NS15 using v3 API. Websockets on. Treatments appearing OK on one AAPSClient instance but not on another. Will keep an eye out for WS reconnections.

it has been improved in dev-i

**Comment by jumalakarhu** [comment]
> 

Update: Seems like a restart of dynos on Heroku and then a full sync from AAPS have fixed issues with profile sync. Still get carb entries entered in AAPSClient uploaded to NS and AAPS even though sync from AAPSClient is not enabled.

**Comment by MilosKozak** [comment]
this has been improved. open new issue if this re-appear
