### ISSUE TITLE
Unable to set english as language [3.2.0-beta1]

### ISSUE THREAD

**Issue by yhonatanb20** [nightscout/AndroidAPS#2451]
The beta has again the problem that appeared on earlier versions (3.0.0 and earlier) and was fixed with 3.1.0, which makes AAPS fixed on system language (setting english as system language makes it some wierd half-half hybrid). Please fix that, it was wonderful to be able to set english in 3.1.0.3, would greatly miss this feature...

**Comment by MilosKozak** [comment]
sorry I don't know how to improve this. Basically setting different language then Android is cheating and may not work in all situations. Paste here screenshot so I can at least test

**Comment by szantos** [comment]
Apart from the system language, using AAPS in English has the tremendous benefit, that you can easily find corresponding parts of the documentation, error messages, etc.

Currently the language chosen in AAPS (English) and system language (other) cause a mess of both languages. Units and 12/24h time also affected.

IMHO:
units should = language chosen in AAPS
time format should = system language

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/75d34955b7aba0782014631cd8656b7a67153186

**Comment by yhonatanb20** [comment]
Still experiencing this issue.
3.2.0 Dev-i 27.4.23: the issue has been fixed mostly, but on some particular screens (I found it on treatmets and on DASH screens) system language (here hebrew) is still used albeit english set in prefrences:
![Screenshot_20230430_223254_AAPS](https://user-images.githubusercontent.com/93551840/235372947-00f34017-63bc-4ba7-996b-36b60adfca68.jpg)
![Screenshot_20230430_223240_AAPS](https://user-images.githubusercontent.com/93551840/235372951-e0a56e00-87f7-4e70-b0ff-ee83a3e299e1.jpg)
![Screenshot_20230430_223259_AAPS](https://user-images.githubusercontent.com/93551840/235372960-45b46901-229e-4e88-97b8-ece5baeaca1e.jpg)

**Comment by yhonatanb20** [comment]
@MilosKozak could you fix that?

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/7faa34aa50d7deca20b344e23f6a136b30586501
