### ISSUE TITLE
Androidaps skips over latest xdrip measurement



### ISSUE THREAD

**Issue by gitthiy** [nightscout/AndroidAPS#2460]
AndroidAps is getting bg values from xdrip broadcast 
Xdrip provides value each 5 minutes 

On AndroidAps you can see latest value when xdrip gets latest value, this latest value is displayed for a short moment but will be ignored with previous value

Attached version Infos of androidaps / xdrip
Displayed bg and received xdrip values 

![Screenshot_2023-03-14-16-13-08-214_info.nightscout.androidaps-edit.jpg](https://user-images.githubusercontent.com/46824497/225049314-3a9ca8d8-3518-4110-a397-bb251b0d9625.jpg)

![Screenshot_2023-03-14-16-10-47-995_info.nightscout.androidaps~2.jpg](https://user-images.githubusercontent.com/46824497/225049312-2af13fd3-cab7-4b13-bbcc-e4ef3c78fb53.jpg)

![Screenshot_2023-03-14-16-11-00-197_info.nightscout.androidaps~2.jpg](https://user-images.githubusercontent.com/46824497/225049310-d37e416a-45c0-479c-b291-426ede4cd5cb.jpg)

![Screenshot_2023-03-14-16-13-46-914_com.eveningoutpost.dexdrip-edit.jpg](https://user-images.githubusercontent.com/46824497/225049311-c777f1ae-ca18-4d2b-bb93-c1b938f1b8a4.jpg)

Log Files of Screenshooting
![AndroidAPS_LOG_1678807366424.log.zip](https://github.com/nightscout/AndroidAPS/files/10970383/AndroidAPS_LOG_1678807366424.log.zip)

I have recorded behavior later shown in attachment
[AndroidapsBG_skip.zip](https://github.com/nightscout/AndroidAPS/files/10972358/AndroidapsBG_skip.zip)

Log Files during recording
[AndroidAPS_LOG_1678817812347.log.zip](https://github.com/nightscout/AndroidAPS/files/10972356/AndroidAPS_LOG_1678817812347.log.zip)

**Comment by MilosKozak** [comment]
most of the code is changed for 3.2
please re-test with 3.2

**Comment by MilosKozak** [comment]
closed for inactivity
