### ISSUE TITLE
3.2.0-dev-i TDD screen shows AndroidAPS logo in the background, making it difficult to read TDD stats

### ISSUE THREAD

**Issue by dv1** [nightscout/AndroidAPS#2473]
On a test KKM phone, I saw that the TDD screen shows the AndroidAPS logo in the background, which isn't good, because the white portions of the logo make the white TDD stats text hard to read.

Here is an example. ![Screenshot_20230323-124414_AAPS](https://user-images.githubusercontent.com/335064/227194445-e3687da7-1fe9-4f99-b093-afa8120b70b5.png)

Previous AndroidAPS versions kept the background fully black in this screen, and it would be good to do the same in this version.

**Comment by vanelsberg** [comment]
Not seeing this on latest dev builds (3.2.0-dev-i, 1920bc7ce5)
Moreover, I do not recognize the layout showed in the screenshots above so I think your are building from some alternate AAPS fork?

**Comment by dv1** [comment]
@vanelsberg  What does the screen look like for you? Post a screenshot please.

**Comment by vanelsberg** [comment]
![Screenshot_20230324_081427_AAPS](https://user-images.githubusercontent.com/45144129/227451334-0ef1a89a-9355-4e71-b84b-9cd9f9dd0ee8.jpg)

**Comment by parapenT1sta** [comment]
I don't have the same issue but was one like this one for EROS but already fixed.

https://github.com/nightscout/AndroidAPS/issues/2390

**Comment by dv1** [comment]
@vanelsberg That is a different screen. What you show is the Statistics screen. I am talking about the TDD screen available through the Actions tab.

**Comment by parapenT1sta** [comment]
@dv1 I can confirm! I also have the same issue going through Actions - TDD.

Maybe the fix is the same as the one used for EROS.

**Comment by vanelsberg** [comment]
> I am talking about the TDD screen available through the Actions tab.
For there is no such screen fro me. Are you building 3.2.0-dev-i from https://github.com/nightscout/AndroidAPS/tree/dev?

**Comment by parapenT1sta** [comment]
> > I am talking about the TDD screen available through the Actions tab.
> 
> Nope. For me there is no such screen fro me. Are you building 3.2.0-dev-i from https://github.com/nightscout/AndroidAPS/tree/dev?

![Screenshot_20230324-192849](https://user-images.githubusercontent.com/608650/227621937-75bdccfb-dc1a-4a0f-a9a6-978d11086025.png)

**Comment by parapenT1sta** [comment]
Using ComboV2 driver
