### ISSUE TITLE
AAPS 3.2.0 dev-i is not uploading to NS smoothed values from G7 patched app. 

### ISSUE THREAD

**Issue by emmatovar27** [nightscout/AndroidAPS#2475]
Reporting bug

I changed today from BYODA G6 to the patch app of G7. 

It looks like AAPS needs to upload the smoothed values. Instead is uploading the raw values to Nightscout. 

![Screenshot_20230326-004511](https://user-images.githubusercontent.com/39507448/227762682-dd3249d5-1fff-4567-867f-573e0fc07c7d.png)
![Screenshot_20230326-004522](https://user-images.githubusercontent.com/39507448/227762684-96e8f987-15c9-4ec9-b5a3-2b681bdf9434.png)
![Screenshot_20230326-004548](https://user-images.githubusercontent.com/39507448/227762685-3e2791f4-6f87-4fe0-b068-dd1122b64e6d.png)

I'm using version AAPS 3.2.0 - dev-i Build:003f323d4c-2023.03.25
I'm using the plugin that uses the API v3 and NS version 15.0.0

Here are the logs too. 
[AndroidAPS_LOG_1679817337271.log.zip](https://github.com/nightscout/AndroidAPS/files/11071036/AndroidAPS_LOG_1679817337271.log.zip)

**Comment by blaqone** [comment]
Maybe add a switch to allow uploading smoothed OR raw data to NS.

BUT then again it is the smoothed data you rely on if you enable that smoothing plugin - so I think the smoothed data must be written to NS.

**Comment by Pamalosebi** [comment]
yes, please. I guess it would also render services like [https://autotuneweb.azurewebsites.net](https://autotuneweb.azurewebsites.net) useless.

**Comment by blaqone** [comment]
> yes, please. I guess it would also render services like https://autotuneweb.azurewebsites.net useless.

Autotune has nothing to do with smoothing values.

**Comment by MilosKozak** [comment]
this is by design. AAPS doesn't modify BG values. But it can does smoothing for internal use and rendering

**Comment by blaqone** [comment]
This makes no sense - the smoothed values is what you "work" with and why should the NS values not represent what you daily calclulations are based on ?

**Comment by Pamalosebi** [comment]
> > yes, please. I guess it would also render services like https://autotuneweb.azurewebsites.net useless.
> 
> Autotune has nothing to do with smoothing values.

Are you sure about this?

As far as I know it uses CGM data from NS. How else would it find possible UAMs?

It may be that "Autotune has nothing to do with smoothing values", but I am talking about the calculations that are done with the raw data available in NS. And if these are not smoothed (as it should be) then I don't see how these services are supposed to work with the data. Also when generating reports and so on...

**Comment by blaqone** [comment]
> > > yes, please. I guess it would also render services like https://autotuneweb.azurewebsites.net useless.
> > 
> > 
> > Autotune has nothing to do with smoothing values.
> 
> Are you sure about this?
> 
> As far as I know it uses CGM data from NS. How else would it find possible UAMs?
> 
> It may be that "Autotune has nothing to do with smoothing values", but I am talking about the calculations that are done with the raw data available in NS. And if these are not smoothed (as it should be) then I don't see how these services are supposed to work with the data. Also when generating reports and so on...

Yes this is indeed correct!

**Comment by MilosKozak** [comment]
AAPS even keeps original values in DB. data is smoothed just before use and only in memory
