### ISSUE TITLE
Automation event WiFi SSID contains space

### ISSUE THREAD

**Issue by M1Sports20** [nightscout/AndroidAPS#2481]
I am currently using AndroidAPS 3.1.0.2

I have an automation that triggers a temp basel based on time and wifi ssid.  This automation works, however the SSID location I key off has recently renamed and has a space in it.  I believe having a space in the WiFi SSID causes the automation to not trigger.

**Comment by MilosKozak** [comment]
delimiter is set to ';'
it should work

**Comment by MilosKozak** [comment]
added to tests and it's working even with space https://github.com/nightscout/AndroidAPS/commit/06ece9747cf5ad2b836ca41eb1c9e79fca22737c

**Comment by M1Sports20** [comment]
Thanks, I will look back at my end.  Sorry for wasting your time.

**Comment by WesSec** [comment]
@M1Sports20 did you find a solution? I'm also trying to build an automation and my SSID contains spaces, it does not seem to 'detect' the condition.

**Comment by M1Sports20** [comment]
The space was not my problem.  I had another condition preventing the automation.

May 6, 2024 5:55:33 AM Wessel Hissink ***@***.***>:
