### ISSUE TITLE
[3.2.0-beta1] Profile helper 'Clone' reports Error in IC Values

### ISSUE THREAD

**Issue by Vigilo-Rob** [nightscout/AndroidAPS#2483]
When an existing working local profile is cloned, it generates a DefaultProfile <datetime> local profile.

When viewed in the LP tab - the profile is highlighted in Red, and has invalid entries (different to the original profile) in the Basal rate fields etc

Changing from a working profile to the newly cloned DefaultProfile shows an error at the bottom of the screen saying 'Error in IC Values'

build: b4e5b01ea3-23.03.03

![Screenshot_20230330-102215](https://user-images.githubusercontent.com/57946229/228798771-425d4c38-8d25-4a7a-972c-ee8a533fd502.png)

[AndroidAPS_LOG_1680169503885.log.zip](https://github.com/nightscout/AndroidAPS/files/11110157/AndroidAPS_LOG_1680169503885.log.zip)

**Comment by MilosKozak** [comment]
sorry explanation is not enough to be able replicate the issue.
put here step by step screenshots what you did and where are the differences

**Comment by Vigilo-Rob** [comment]
No problems - see attached Zip for screenshots.

Those entitled 'Working DAI' etc are the profile that is cloned and shows my current profile settings.

Those entitled 'Error DAI' etc are the cloned profile once its created.

The 'Profile Helper' screenshot is before I press the 'Clone' button.

[Profile Helper Error Details.zip](https://github.com/nightscout/AndroidAPS/files/11119914/Profile.Helper.Error.Details.zip)

**Comment by MilosKozak** [comment]
working profile has a name 40pct fiasp.
Failing profile is DefaultProfile
thus it's not a clone of "40pct fiasp"

**Comment by Vigilo-Rob** [comment]
DefaultProfile is the name it allocates to the profile when you press the 'Clone' button - not sure what you expect to happen? My guess is it can't clone a profile with the same name else there would be a duplicate profile hence uses DefaultProfile and Datetime to identify the new profile

The problem appears to be the values created in the profile itself - look at the IC ratio on the cloned profile - its shows an IC ratio of 23370203 with 7 different ICs

The IC ratio from the source cloned profile is 7.3 and a single time entry.

**Comment by MilosKozak** [comment]
but this is not your current profile. it kind of recommendation where to start if you have no profile
what values did you put in?

**Comment by Vigilo-Rob** [comment]
Current profile I used to clone is 40pct fiasp (thats what I'm actually using for the loop)

![Current Profile](https://user-images.githubusercontent.com/57946229/229782405-d17d110b-a7a6-4a25-a821-fa0079600fd0.png)

**Comment by Vigilo-Rob** [comment]
Right - light finally dawns - (thank you)

So it's not possible to clone the active profile, and the default profile has out-of-range entries to force the user to enter their own profile rather than accepting a default value.

Sort of makes sense - apologies for asking so many questions.
