### ISSUE TITLE
Make careportal_sensor_age configurable

### ISSUE THREAD

**Issue by Rubueno** [nightscout/AndroidAPS#2491]
Currently the `careportal_sensor_age` found in [app/src/main/java/info/nightscout/androidaps/plugins/general/overview/StatusLightHandler.kt#L42](https://github.com/nightscout/AndroidAPS/blob/master/app/src/main/java/info/nightscout/androidaps/plugins/general/overview/StatusLightHandler.kt#L42) has hardcoded values. I would like to see these values to be configurable. I use a Libre2 sensor which is only replaced every 14 days. Having the values be configurable would help remove the ugly red warning in the "overview" and "actions" windows.

**Comment by Philoul** [comment]
I think it's in overview preferences, status lights
You can tune all alerts values (for sensor age unit is number of hours)

**Comment by Rubueno** [comment]
Aha, you're right! I hadn't found that one yet. Thanks!
