### ISSUE TITLE
[dev-i] No backfilling of treatment data to Nightscout if server isn't available

### ISSUE THREAD

**Issue by swissalpine** [nightscout/AndroidAPS#2494]
I back up my FC and AAPS data to a Nightscout installation on my NAS. At night I turn it off to save power (from 1 to 6 o'clock).
At 6 o'clock xDrip+ syncs all blood glucose data, but AAPS not my treatment data.

<img width="447" alt="image" src="https://user-images.githubusercontent.com/12517693/230723702-053cd57a-c3d2-4f3e-955d-945a8eef8de2.png">

NSClientV3: websockets deactivated
Nightscout: 15.0.0

**Comment by MilosKozak** [comment]
full sync helps?

**Comment by swissalpine** [comment]
Thanks for coming back.
Yes. After a full sync the missing data (tbr changes) are there ...

**Comment by MilosKozak** [comment]
i'd need to know error received when server is off. could you provide logs?

**Comment by MilosKozak** [comment]
that's correct.
I'd need log from time when you turned on your NS but data was not uploaded

**Comment by swissalpine** [comment]
WLAN on at 06:01:45.377, NAS starts at 6:00 ...

06:05:17.011 [RxCachedThreadScheduler-42] D/NSCLIENT: [NSClientV3Plugin$onStart$7.accept():223]: ● RUN Starting next round MAIN_LOOP

[AndroidAPS._2023-04-18_02-00-13_.0.zip](https://github.com/nightscout/AndroidAPS/files/11277157/AndroidAPS._2023-04-18_02-00-13_.0.zip)

BTW After seeing this logs I disabled open human uploader because it seems to fail every time ... another issue? Login is correct ...

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/4c28de0b64fdf588702bd2636d7f4b4c123a872b
