### ISSUE TITLE
[dev] not sending data to nightscout v14.2.6

### ISSUE THREAD

**Issue by Not-AriStienfeld** [nightscout/AndroidAPS#2496]
the nightscout feature gets stuck requesting "do connect". I have tried a full delivery/synchronization, along with restarting the phone, but it will not connect. 
--------------
- unable to send any data to nightscout
- build: 04675332bf-2023.04.09 full release
- phone: google pixel 5a
- could not access logs as phone did not want to connect files to computer

**Comment by andyrozman** [comment]
AAPS Dev doesn't support old nightscout anymore... You need to have v15
(latest dev, I am not sure if it was released already)...

Andy

**Comment by Not-AriStienfeld** [comment]
thank you for the quick response. does the nightscout updater tool support the dev branches?
