### ISSUE TITLE
Dev - I Version 3.2.0 User Settings will not be written to the Pump

### ISSUE THREAD

**Issue by sfriedriszik** [nightscout/AndroidAPS#2498]
In the Dana I tab, User Settings, the values are not written to the pump. The button seems to be inactive.

**Comment by CaroGo** [comment]
Same here. No changes are send to pump. Changes made at the pump are not shown in the Dana tab...even after refresh of Bluetooth connection.

**Comment by Alamo04** [comment]
Confirmed

This bug has existed for a long time now, across multiple dev versions.

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/173cc754d5d7509dcd4ab3c033d854452bfbabfa
