### ISSUE TITLE
[2.7.0] Essensvorlagen aus Nightscout /  meal templates from Nightscout failed

### ISSUE THREAD

**Issue by mrschloemp** [nightscout/AndroidAPS#25]
Aaps 2.7.0

Wenn man aus Nightscout Essensvorlagen aktiviert, verschwindet im Startbildschirm von Aaps die komplette Steuerung (Insulin, Kohlenhydrate, Rechner, Kalibrierung und CGM Button) sowie unter dem Reiter Aktionen die oberen Buttons und es wird nur noch Temporäres Ziel angezeigt.

Google Translate:
If you activate meal templates from Nightscout, the complete controls (insulin, carbohydrates, calculator, calibration and CGM button) as well as the upper buttons under the Actions tab disappear from the Aaps start screen and only the temporary target is displayed.

Screenshots:
http://1lk.de/ns/uebersicht.jpeg
http://1lk.de/ns/aktionen.jpeg
http://1lk.de/ns/version.jpeg

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/EN/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
missing buttons means one of the folloving:
* no profile
* pump not initialized (yet)

it's not related to Food plugin at all
