### ISSUE TITLE
[AAPS 3.2.0-beta1] Daily AAPS crash at the same time

### ISSUE THREAD

**Issue by boris803** [nightscout/AndroidAPS#2508]
Hi together,

I‘m using the AAPS 3.2.0 beta 1 (39f7c1236b-2023.04.03) on a Samsung Galaxy A53 with the newest official Android version since  3 weeks.
We have the issue, that each day at nearly the same time AAPS is crashing between 5:40 pm and 5:50 pm (+/- a few minutes). (Timezone: GMT +2 / Hamburg, Germany) 
This means the apps is no longer running and therewith receiving or sending any BG information. The Android settings are fine and there isn’t any active energy saving mode configured.

I‘ve never had such an issue with the 3.1.0.3 release of AAPS, but I had to switch to the newest version due to the new Dexcom G7, which we would like to use the SMB / DynISF. 

[AndroidAPS._2023-04-19_17-46-33_.7.zip](https://github.com/nightscout/AndroidAPS/files/11276724/AndroidAPS._2023-04-19_17-46-33_.7.zip)
[AndroidAPS._2023-04-18_17-47-25_.5.zip](https://github.com/nightscout/AndroidAPS/files/11276725/AndroidAPS._2023-04-18_17-47-25_.5.zip)

I‘m very sorry, if it‘s just a problem at my end, but I don‘t hope so. ;)
Greetings from Germany
Boris

**Comment by CaptainBalou** [comment]
Hello @boris803 ,

I'm none of the developers here and so no pro in all that, just a user. But have you already checked/deactivated this?

https://androidaps.readthedocs.io/en/latest/Getting-Started/FAQ.html#aaps-stops-everyday-around-the-same-time

Kind regards
Marco
