### ISSUE TITLE
Commit for "Close gatt when BLE is disconnected" deteriorates connection reliability

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#2513]
**AndroidAPS 3.2.0-dev-i**
**Build**: 5e2614f9f6
**Flavor**: fullrelease / Engineering mode
Pump: DASH
Phone: Samsung S22 Ultra

**Problem description:**

As a result of this change APPS connects faster to the Pod but connection reliability has become a problem.
Getting timeouts on connecting a few time a day.

**Connection connection time has no relevance, connection reliability does!** On most supported phones there is no problem with connecting to the DASH Pod. Current BLE implementation was field-tested for a long time on many phones and with many DASH versions.

Note that this is not about connecting to some BLE bluetooth device but to Omnipod proprietary hardware that is not supported by the manufacturer and where DASH driver implementation was tweaked and tested by many to get this working reliably. 

_I do not see any reason for change. Please do not fix what is working for most phones!? 
So I suggest reconsidering necessity, implementation and on how this can be tested for a large range of Phone hardware._

![Screenshot_20230421_080338_AAPS](https://user-images.githubusercontent.com/45144129/233556948-d7dc2796-58d7-4b1e-b6c0-c9ef5f3d0676.jpg)
![Screenshot_20230421_080356_AAPS](https://user-images.githubusercontent.com/45144129/233556959-5095eb57-43c5-4c5a-b2fe-acc649043602.jpg)

[AndroidAPS_LOG_1682057146032.log.zip](https://github.com/nightscout/AndroidAPS/files/11292807/AndroidAPS_LOG_1682057146032.log.zip)

**Comment by jbr7rr** [comment]
This fixes the issue mentioned:
https://github.com/nightscout/AndroidAPS/pull/2514

And I would argue that the reliability was not always there, on most pixel phones and some samsungs, one had to enable the bluetooth watchdog, and always had a sub optimal success rate on connection attempt success (90-98%)

**Comment by vanelsberg** [comment]
@jbr7rr  Thanks. Quite busy atm, but will test this a.s.a.p.
Pixel has been problematic from the start and was concluded it was "problematic" when it comes to "DASH compatibility".

Let see if you can improve DASH's BLE implementation and discuss how to test your final code on as many hardware hardware as possible. I'll DM you!?

**Comment by vanelsberg** [comment]
Problem solved with https://github.com/nightscout/AndroidAPS/commit/9c902fb141b8c784e1ac245fc35d3577113827d7
