### ISSUE TITLE
Manual AAPS delivered bolus not picked up in treatments, may not be in IOB

### ISSUE THREAD

**Issue by tim2000s** [nightscout/AndroidAPS#253]
Reporting bugs
--------------
21.05 - manual bolus administered via AAPS and showing in pump history not showing in treatments or uploaded to Nightscout. Not clear that it's included in IOB. IOB may be undercounted. 

At the time AAPS issued a basal not updated followed by a bolus not delivered alert. 

Pump in use is Medtronic 722. Logs uploaded. 
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/EN/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by tim2000s** [comment]
Ran OpenAPS rig against the pump and confirmed that the bolus was missing from IOB.

**Comment by andyrozman** [comment]
That is weird... When you administer bolus from AAPS this information is added to treatments, unless something went wrong... Even if it wasn't added to treatment, if it was delivered with pump, it should have been picked up from history... 

Can you please provide logs @tim2000s

**Comment by MilosKozak** [comment]
we don't have logs

**Comment by tim2000s** [comment]
That's odd. They were sent through last night.

**Comment by tim2000s** [comment]
I've resent the logs through just now. To the usual logs@androidaps.org address.

**Comment by AdrianLxM** [comment]
@tim2000s androidaps.org email addresses do no longer work.

**Comment by tim2000s** [comment]
> @tim2000s androidaps.org email addresses do no longer work.

That's the address that AAPS used from within the system...

**Comment by StephenBrown2** [comment]
What email should be used? I have sent several logs via the Maintenance menu, now I think they must have gone nowhere, though I haven't gotten any bounce responses.
