### ISSUE TITLE
AAPS not responding after phone boot

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2534]
![Screenshot_20230509_140222_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/b2059381-a4df-4273-a83b-ed5d5892db06)

The app not responding after phone boot problem is still present.

![Screenshot_20230510_093523_One UI Home.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/5b7a50de-4a4b-41c0-b600-8e8fc37f7246)

If I'm not mistaken, reboot is fine but then off phone then start phone creates this messga. _Wait_ doesn't solve the problem. _Turn off app_ clears the problem. No more messages when AAPS restarts.

**Comment by MilosKozak** [comment]
sorry, this doesn't have solution. probably because phone is too busy after start
