### ISSUE TITLE
Set 120% for 20 min but see negative minutes

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2538]
Last build
![Screenshot_20230509_140222_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/6b93a4ca-750f-47d3-90b6-20a4e9d44c45)

There is a bug somewhere but can't get my hand on how to trigger it. I had set profile at 120% for 20 min. Some time later, I see -minutes and start another 120% for 20 min using the button _use 120%_ some time later, I see that I have more -minutes and set 120% for 20 minutes again but I have no indication that the command was accepted.

Last dash connection less than 1 min ago.

![Screenshot_20230512_191818_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/8c3a2eb1-82fb-4dc6-96a9-8aaee8b83cb4)

When I look in the treatments, the commands have been accepted.

![Screenshot_20230512_192250_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/6a3fcaf4-f4f2-42de-bb9a-0c1772d6ca34)

Here is the logs. You have the times on the capture above.

![AndroidAPS_LOG_1683912011490.log.zip](https://github.com/nightscout/AndroidAPS/files/11466529/AndroidAPS_LOG_1683912011490.log.zip)

**Comment by robertrub** [comment]
Might be related to reactivating a temp profile when the actual one is not over yet.

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/01bb554651f2dbfafdec7f069dd99f2ed16cc578
