### ISSUE TITLE
2.8.1.1 Reboot phone and a strange counting message

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#254]
I rebooted my Samsung S9 Android v10 phone. When the phone had started, I looked in AAPS 2.8.1.1 and there was a strange counting message. I'm not sure what it is connecting to (I suppose Orangelink but not sure) but the message was very strange and uncomprehensible.

![Screenshot_20210123-091810_AndroidAPS](https://user-images.githubusercontent.com/76626474/105573325-fbee3980-5d5c-11eb-9b12-18aaa3bf2cd5.jpg)

**Comment by MilosKozak** [comment]
it's connection to the pump/rileylink. just counter. if translation is wrong fix it in crowdin

**Comment by robertrub** [comment]
Hi Milos

After your first message asking me to correct things in Crowdin, I had asked to join but that was a week ago and I have not heard anything from them yet. I'm waiting at the door...

I'd like to thank you personally for all the work, time and brain cells you (and the team of course) put in AAPS, it is a magnificent piece of work. I'm a type 1 since '84 and been very keen on a strict control of the beast. This is the first time in 36 years that a big part of the burden has been lifted.

You can call on me for help, testing or finance. My coding days are decades away but testing and logics are still in my books :)

Thanks again and best regards.

Robert

----------------------------------------

23 janv. 2021 09:40:19 Milos Kozak <notifications@github.com>:
