### ISSUE TITLE
Same profile % correction has side effects

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2540]
Hi @MilosKozak 

Your correction to my last issue (repeat same profile % before it ends) has some side effects ;) Looks like the profile is set every 5 minutes...

![Screenshot_20230514_093712_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/5bb884cd-ce3e-4f04-9876-a530c4e04322)

![Screenshot_20230514_132717_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/48581cce-6733-4a41-aa0d-cbaae6d7a7ad)

![Screenshot_20230514_132732_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/fde81add-3b8b-4137-b54b-18385870268b)

![AndroidAPS_LOG_1684063661540.log.zip](https://github.com/nightscout/AndroidAPS/files/11471779/AndroidAPS_LOG_1684063661540.log.zip)

**Comment by MilosKozak** [comment]
already fixed in dev
