### ISSUE TITLE
Androidaps does not display latest value as read by xdrip

### ISSUE THREAD

**Issue by 01erster** [nightscout/AndroidAPS#2543]
On AndroidAPS Overview Tab the reading time of blood sugar value is behind xdrip+ latest reading. I have recorded this for 14.05.2023 11:06

Log files and screen recording in attached files:
[AndroidAPS_LOG_1684055313489.log.zip](https://github.com/nightscout/AndroidAPS/files/11489655/AndroidAPS_LOG_1684055313489.log.zip)
[VID_20230514_111241.zip](https://github.com/nightscout/AndroidAPS/files/11489658/VID_20230514_111241.zip)

**Comment by MilosKozak** [comment]
expecting this is not 3.2.0?

**Comment by 01erster** [comment]
It is this version:
![image](https://github.com/nightscout/AndroidAPS/assets/59749490/be878cba-ba5d-457f-9638-79b42f5b4881)

**Comment by MilosKozak** [comment]
this code is completely new in 3.2.0, test beta or dev or wait for next release
