### ISSUE TITLE
Pump not responding to Bolus requests

### ISSUE THREAD

**Issue by jcpeiro** [nightscout/AndroidAPS#2547]
I switched to a new phone yesterday and built a new APK for AndroidAPS v 3.1.0.3 and Ruffy.
The system seemed to work properly yesterday and loop was enabled changing temp basals and providing SMB.  This mornign also worked OK and delivered bolus w/o problem.

The problem started at noon to,e.  I can not send now boluses to my Accucheck Spirit combo.  I tried connecting only with Ruffy,  and the pump can be properly paired and controlled from Ruffy, even delivering bolus.  

Restarting the phone and starting AndroidAPS v 3.1.0.3, and the problem shows when trying to use the bolus calculator, or a insulin delivery.  AndroidAPS is conencting to the pump, but after a while trying to issue the bolus, the bolus is not provided and an error of bolus not delivered is reported, Automatic SMB are not working either.  They were working yesterday night and this morning. 

It seems like BT is reaching some sort of time out.  I checked all the BT settings in the pump and all seems correct. 

Automatic changes of temp basal rate and profile sets are working fine,  pump is responding to the request from androidAPS.  Problem is with SMB and with bolus.

Previously AndroidAPS was connecting and providing a message of "programing bolus of 5 units" while connecting to the pump. And some minutes later, the bolus was provided step by step.  Now, it does not give any message of programming bolus, not delives the bolus.  It just keeps trying,  with the pump beeping and exiting from BT with a beep beep, and after several cycles, AndroidAPS aborts with an error message that bolus was not delivered. 

Can you provide help to solve the problem and allow the closed loop system to properly manage SMB and allow me to manually use the bolus calculator or insulin delivery to send bolus from Androidaps  to the Combo pump?

Log file is attached.  

It is quite urgent, as I cant deliver anymore boluses.

Kind regards,

Joan Carles
Build  1de236a602-2023.05.19-00:10  v 3.1.0.3
[AndroidAPS_LOG_1684506576499.log.zip](https://github.com/nightscout/AndroidAPS/files/11517901/AndroidAPS_LOG_1684506576499.log.zip)

[AndroidAPS_LOG_1684506576499.log.zip](https://github.com/nightscout/AndroidAPS/files/11517881/AndroidAPS_LOG_1684506576499.log.zip)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
it's related to connectivity with pump. there is nothing we can do

**Comment by jcpeiro** [comment]
Yes;  you are right.  Confirmed.  I changed the pump by my spare pump, and
now is working fine.  I guess the BT circuit in my pump has comen to an
end.  Thanks anyway

El dv, 19 maig 2023 a les 23:23 Milos Kozak ***@***.***> va
escriure:
