### ISSUE TITLE
MINOR: Hearth rate chart starts at 0

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2566]
Not really a bug. The HR chart has the minimum set to 0... Not very useful :)

I think setting the min of the HR chart to 40 should cover 99,9% of cases and give a better definition of the variation of the HR. Even 50 BPM is very rare so it can be used as a min too.

![Screenshot_20230603_224654_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/80276f34-daa2-4cb9-b673-f934b2979f79)

![Screenshot_20230602_203522_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/aafd1261-c402-4862-ba90-594794a58d41)

**Comment by buessow** [comment]
My heart rate, or at least what the watch measures goes below 40. So how about 30?

**Comment by robertrub** [comment]
40 is real low (usually very long distance runners or long distance swimmers...). Ate you one of them ? Did you count your heart beat with a finger on the wrist and a timer and compare it to the SmartWatch ?

**Comment by buessow** [comment]
I think my resting heart rate is 45 and the lower values are artefacts off
the watch.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/ea8a58ed27834896361b1859a3f10758d510dfec
