### ISSUE TITLE
Carb, insulin button missing

### ISSUE THREAD

**Issue by m-l-s0** [nightscout/AndroidAPS#2568]
While they were there this morning, the Carb, Insulin and bolus calculator dissapered since then.
It did occur after I stopped insulin delivery completely on the Pump (Dana-i). The Buttons reappeared a while (10-20 min.) after starting insulin delivery.
The same thing happened when changing the reservoir jus now, so I suspect that might be the reason, althought I am not certain. 
The buttons are activated in the settings.
Build Nr. 1de236a602-2023.06.03-15:45
Version 3.1.0.3 fullrelease

![IMG_20230604_161855](https://github.com/nightscout/AndroidAPS/assets/121341642/670848ad-3843-4b3b-afd6-d92a1c79074e)
![IMG_20230604_161839](https://github.com/nightscout/AndroidAPS/assets/121341642/a356b372-0841-45e2-87cd-4e98d72febe6)

(the folders in emulated0/android/info.nightschout... are empty therefore I cannot provide log files)

**Comment by MilosKozak** [comment]
common in this situation is pump is not initialized
