### ISSUE TITLE
[EOPATCH2] Adding the texts of the notifications to translation

### ISSUE THREAD

**Issue by fjpezuela** [nightscout/AndroidAPS#2570]
Currently all notifications from the EOPATCH2/GlucoMen Day PUMP are in English. 

It would be a good idea to add them to the translations.

![image](https://github.com/nightscout/AndroidAPS/assets/67511778/f7cb57a4-e4fb-47e6-b8cf-fa67ccc7bdd8)

![image](https://github.com/nightscout/AndroidAPS/assets/67511778/55c4b79b-11f9-4b63-9890-7b4e8f91111a)

Thanks

**Comment by MilosKozak** [comment]
added
