### ISSUE TITLE
Double arrows DOWN when BGs are going UP !!

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2581]
Very strange. The BGs (coming from xDrip) are going up, the numbers are going up in AAPS too but AAPS shows double DOWN arrows ???

Logs are attached. The times are on the screen captures.

![Screenshot_20230602_203522_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/67489cd4-0c93-4637-b312-789d3ced6d6f)

![Screenshot_20230613_162949_xDrip+.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/f89a36ab-bf63-495f-aa95-e2f17aa519cd)

![Screenshot_20230613_162930_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/d1e765d6-85bd-4deb-8864-177fa9f77a7a)

![AndroidAPS_LOG_1686670359765.log.zip](https://github.com/nightscout/AndroidAPS/files/11736660/AndroidAPS_LOG_1686670359765.log.zip)

**Comment by MilosKozak** [comment]
log starts 16:29
but generaly aaps displays arrow received from BG source

**Comment by robertrub** [comment]
Hi @MilosKozak 

Got bitten by the double down arrows once more. It might be related to very jumpy BGs and the smoothing algorithm.

You have the times from the screenshots.

![Screenshot_20230705_102055_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/57aa3e8f-6f30-495d-aaa1-501203664dfe)

![Screenshot_20230705_102142_xDrip+.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/35e08da8-063a-4a76-acb8-f2953e1364af)

![Screenshot_20230705_102330_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/382d8b36-7481-477f-af4a-0203931c6e64)

![Screenshot_20230618_213209_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/4c2b1bbe-bad1-476f-a7ee-8427ecf7e117)

![AndroidAPS_LOG_1688545277936.log.zip](https://github.com/nightscout/AndroidAPS/files/11955666/AndroidAPS_LOG_1688545277936.log.zip)

**Comment by robertrub** [comment]
As before, very strangely, force stop AAPS, clear cache memory doesn't solve the problem.

Restarting phone does solve the problem.

I wonder what's the difference between _force stop and clear cache_ vs _restart phone_... Maybe a lock on a file that is reset at reboot. 🤔

**Comment by robertrub** [comment]
Once again, I have the double arrows for no reason.
I'm using at the moment xDrip and xDrip variant1 at the same time (end of one sensor and the new one "heating up" for 48h). xDrip variant1 doesn't send any data nowhere. I wonder if for some reason this could be the cause...

![Screenshot_20230718_081403_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/a8e43812-7be2-4ba8-8371-6e248fbfd92b)

**Comment by robertrub** [comment]
Once again, I have the double arrows for no reason.
I'm using at the moment xDrip and xDrip variant1 at the same time (end of one sensor and the new one "heating up" for 48h). xDrip variant1 doesn't send any data nowhere. I wonder if for some reason this could be the cause...

![Screenshot_20230718_081403_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/a8e43812-7be2-4ba8-8371-6e248fbfd92b)

 EDIT : It is NOT related to having 2 xDrip/G6 running at the same time. I have only 1 G6 at the moment and have the double arrows (only in AAPS with smoothing). Might help, this sensor is very sensitive to pressure and declaires lows when I sleep on it and goes to normal when I change positions.

![Screenshot_20230725_021812_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/4c852e55-b37a-42e9-8e3a-a704d871ad60)

**Comment by robertrub** [comment]
@MilosKozak I really think that the bug comes from the smoothing algorithm. The double arrows arrive after there has been a dive in the BGs for 1 reading.

![Screenshot_20230725_102923_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/32aa68f0-1993-40dd-b7c4-1fe6ca2d500b)

![Screenshot_20230725_102610_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/693b46af-bd12-4682-9b50-fe54aed1aee0)

![Screenshot_20230725_102627_xDrip+.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/a19dfdc3-0a8f-4731-b120-d492aa2317d7)

![AndroidAPS_LOG_1690273721008.log.zip](https://github.com/nightscout/AndroidAPS/files/12158886/AndroidAPS_LOG_1690273721008.log.zip)

**Comment by robertrub** [comment]
Ok, more testing and the problem seems unrelated to smoothing. I turned it off yesterday and I still have the double arrows problem. I'm still with the same bumpy G6 sensor.

![Screenshot_20230726_092842_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/b056aa52-5473-4b12-afa4-744f54cf81f0)

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/fa7b73bc8b8c114cafa88372af7ba497f8dbe5ce
