### ISSUE TITLE
After application startup loop fails with "Pump not initialized!" until manual connection to pump initiated

### ISSUE THREAD

**Issue by viq** [nightscout/AndroidAPS#2582]
AndroidAPS `f1118e238d-2023.06.11`

Whenever AAPS is (re)started, loop is not functional, failing with "Pump not initialized!" error, until I go into the pump tab and click on the bluetooth status to initiate a connection. Yes, it may be hours in this state before a manual connection will be made, after which everything works.

Pump is an old Dana R.

May or may not be related to https://github.com/nightscout/AndroidAPS/issues/2567

**Comment by viq** [comment]
[AndroidAPS._2023-06-13_19-37-53_.5313.txt](https://github.com/nightscout/AndroidAPS/files/11739836/AndroidAPS._2023-06-13_19-37-53_.5313.txt)
This one is from around the restart time. After restarting I went to loop, tried to run it, it failed, I went to pump, clicked on pump, then loop succeeded.
I'll have in a moment a log where there's more time between restart and connecting to pump.

**Comment by viq** [comment]
In this log AAPS was restarted around `23:54`, failed to run loop at `23:55` and `00:00`, and at `00:02` I connected manually to pump, after which loop succeeded.
[AndroidAPS._2023-06-13_23-54-24_.5321.txt](https://github.com/nightscout/AndroidAPS/files/11739862/AndroidAPS._2023-06-13_23-54-24_.5321.txt)
[AndroidAPS._2023-06-13_23-54-24_.5321.zip](https://github.com/nightscout/AndroidAPS/files/11739864/AndroidAPS._2023-06-13_23-54-24_.5321.zip)
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/11739865/AndroidAPS.log)

**Comment by MilosKozak** [comment]
It's a mess when you try to connect manualy.
Restart AAPS, keep it trying to connect for 15 min, then send log from this time

**Comment by viq** [comment]
New batch of logs. AAPS has been restarted at `13:48`, and manual connection to pump has *not* been establish until moment of log upload at `14:26`
[AndroidAPS._2023-06-14_13-48-19_.2245.zip](https://github.com/nightscout/AndroidAPS/files/11745653/AndroidAPS._2023-06-14_13-48-19_.2245.zip)
[AndroidAPS._2023-06-14_13-48-19_.2246.zip](https://github.com/nightscout/AndroidAPS/files/11745654/AndroidAPS._2023-06-14_13-48-19_.2246.zip)
[AndroidAPS._2023-06-14_13-48-19_.2247.zip](https://github.com/nightscout/AndroidAPS/files/11745655/AndroidAPS._2023-06-14_13-48-19_.2247.zip)
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/11745657/AndroidAPS.log)

**Comment by chrisdex** [comment]
I'm also having this issue (or similar) for a few weeks now. Running 3.1 Master and the loop just wont run for hours on end. I can't figure out when it stops working or why. 
When i open AAPS there is often a delay in showing the BG curve when this happens and the Basal is just on running on preprogrammed Profile levels. But not SMBs no Temp Basals.
This is obviously very aannoying and has repeatedly caused me unexpected hyperglycemias. 
What should i do ? Re-build the app ? 
AAPS has all the bakground permissions and Play Protect is off. S22+, OP_Dash, Libre 3

**Comment by ex-citer** [comment]
I can confirm heavy connection/BLE issues on Android 13 using AAPS 3.0.0.1 + ruffy+ combo and sometimes acceptable BLE issues on Android 13 using AAPS 3.2 dev + combo with integrated pump driver. The connection issues could be acceptable if it happens 2-3 times per week. But in addition I experience that the Pump Alarm sound/notification is not triggered at all. This leads to several hours of unexpected hypos due to the missing alarm. Should I raise another issue for this or use this issue? I can provide logfiles of 30 minutes of operation with a threshold set to 30 mins and no alarm is triggered. Sensor alarms are triggered, this is working well.

**Comment by MilosKozak** [comment]
try dev with https://github.com/nightscout/AndroidAPS/commit/1d6a48d01dcd16a5767940f9e04e3003af60e713

**Comment by viq** [comment]
[AndroidAPS._2023-08-03_20-30-26_.400.zip](https://github.com/nightscout/AndroidAPS/files/12254065/AndroidAPS._2023-08-03_20-30-26_.400.zip)
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/12254066/AndroidAPS.log)
Doesn't seem to have helped.

**Comment by viq** [comment]
....and just as I said that, after a few cycles of doing nothing, and seeing "pump not initialized" message in logs, it seems to have managed to connect and issue SMB without me clicking on the pump connection. I'll observe more and report.

**Comment by viq** [comment]
OK, it takes a few minutes, but it does connect to pump and succeeds with dosing changes after an application restart, without me having to manually click on pump connection. Should I close this issue, or is there anything more you want to look at here?

**Comment by MilosKozak** [comment]
primary reason is that pump disconnects unexpectly which is an error state. AAPS can recover from this state now better
