### ISSUE TITLE
MINOR : Heart rate graph / missing data

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2584]
A minor bug. When HR data is missing (watch not on arm), if it is for a short time, on the HR graph, there is a line between the last known rate and the new one.

![Screenshot_20230613_170607_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/ab963d83-dab1-485a-b091-5be8e18f984b)

If the missing data is for a longer period (at night), the last known HR goes off the screen and the new one is "not connected" to the old data.

![Screenshot_20230614_094144_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/c30e9b33-8b56-4e64-b58b-a6dbdec9708c)

It would be better to not have a line when there is no data.

![Screenshot_20230602_203522_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/db3e9b63-7e95-42a4-90d3-a992f918e6ae)

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/fd696a0c4bb675b96b7de86634711333e952407b
