### ISSUE TITLE
duration unit is mistaken for minute in function calculateFromTreatmentsAndTemps

### ISSUE THREAD

**Issue by DanielEColi** [nightscout/AndroidAPS#2588]
The relevant code is in the file [AndroidAPS] https://github.com/nightscout/AndroidAPS/tree/master/app/src/main/java/info/nightscout/androidaps/plugins/iob/iobCobCalculator)
/IobCobCalculatorPlugin.kt

the bug is in the function below:
```
override fun calculateFromTreatmentsAndTemps(toTime: Long, profile: Profile): IobTotal {
...
        val t = TemporaryBasal(
            timestamp = now + 60 * 1000L,
            **duration = 240,**
            rate = 0.0,
            isAbsolute = true,
            type = TemporaryBasal.Type.NORMAL
        )
...
```
`duration = 240` should be ` duration =240*60*1000 ` since the unit is milliseconds

**Comment by MilosKozak** [comment]
good catch 👍 
fixed by https://github.com/nightscout/AndroidAPS/commit/1500381e1477a1d53b2a0b123749fb401de4fa9b
