### ISSUE TITLE
Replace Skins with Configuration Qualifiers and Source-Sets

### ISSUE THREAD

**Issue by AdrianLxM** [nightscout/AndroidAPS#259]
### **Background:**
We use kotlin synthetics to access Views / layout elements in our Fragment.
They are deprecated now due to various reasons and the recommended way of replacing them is ViewBindings or DataBinding (special kind of ViewBinding) and access the elements via their ViewBinding properties/fields.

### **Problem to solve:**
ViewBinding classes generated form the layout xml files might have the same names for their fields - they do not inherit from each other and don't have a common interface.

### **Strategies:**

1. **_Use alternative resource loading via configuration qualifiers._**
https://developer.android.com/guide/topics/resources/providing-resources#AlternativeResources.
The qualifiers `small`, `port`, `land` can be used to distinguish the same layout for different configurations (running on a small device, in portrait, landscape, ...) similar to the language qualifiers to load resources in different languages.

2. **_Use separate source sets for Fragments in NSClient and other flavors_**
By moving functionality to an abstract superclass and then having two implementations of the fragment ad glue code we can use different `OverviewFragment`s and `ActionFragment`s for different flavors that behave the same. The individual fragments responsibility would only be the glue code to lookup the appropriate views.

3. **_Use Databinding & ViewModels _**
In places where a Skin affects a certain property element of a view, like `android:textSize` we can bind that to a ViewModel that asks the current Skin for the value. This is a good opportunity to introduce ViewModels as View-independent expression of view state - that we then later can amend and move functionality from our Fragments to the ViewModels.

**Comment by rICTx-T1D** [comment]
I think strategie 3 is a good way to go. Binding of datasets and model is a recommended solution in many development languages.
