### ISSUE TITLE
Carbs suggestions are impacting nightscout chart readability

### ISSUE THREAD

**Issue by zibra** [nightscout/AndroidAPS#2593]
Not sure what is the correct place to report this suggestion. Let me know if it should bi moved somewhere else.

Carbs suggestions (orange, big dots) from AndroidAPS SMB are impacting Nightscout chart readability. It will be good to display them differently. One of the solutions I see is to display them always below any other dots.

![obraz](https://github.com/nightscout/AndroidAPS/assets/4493100/5a015ee8-b9af-443f-9ff6-63c3615be52e)

**Comment by cascer1** [comment]
I think they are added as announcements in Nightscout. You could turn that off in nsclient settings > advanced > Create announcements from carbs required alerts.

For rendering in Nightscout, I think https://github.com/nightscout/cgm-remote-monitor/ is probably a better place for opening an issue.
