### ISSUE TITLE
Missing "pumpEnactResult.apply" in ComboV2 driver, leading to misleading feedback on SMS bolus

### ISSUE THREAD

**Issue by savek-cc** [nightscout/AndroidAPS#2594]
See https://github.com/nightscout/AndroidAPS/blob/a69fbf0635fa6cbfe9635d7949b761cefa282dbc/pump/combov2/src/main/kotlin/info/nightscout/pump/combov2/ComboV2Plugin.kt#L1071
it is missing
`
                pumpEnactResult.apply {
                    bolusDelivered = detailedBolusInfo.insulin
                }
`

without this, AAPS always reports back 0.0 units delivered when issuing a bolus command via SMS.

**Comment by savek-cc** [comment]
Should probably be added after line 1110 and report the actually delivered value.

**Comment by dv1** [comment]
True. Thanks for that. Will look at this.

**Comment by MilosKozak** [comment]
@dv1 ?
