### ISSUE TITLE
[Feature Request] Add option to launch treatmentdeliveryerror silently

### ISSUE THREAD

**Issue by m-l-s0** [nightscout/AndroidAPS#2600]
I am using android aps with the Dana-i and while most things work perfectly fine I have an issue with dropped connections during long boluses. That in and of itself is not an issue, as thus far the pump has always finished delivering the insulin.
But every time that happens the upcoming alarm has been played if my phones volume was on. As I don't always turn my volume down this has been particularly annoying in lectures, where I don't want to have my phone beeping in a high-pitched irritation (or any) tone during most times. 
That's why I would love to have an option to mute this particular alarm.
I have looked through the code and the alarm `treatmentdeliveryerror` is raised among others in line 245 of `app/src/main/java/info/nightscout/androidaps/dialog/InsulinDialog.kt` . It is passing the sound `R.raw.bouluserror` on in case that is relevant.
As I don't know the code-base (or Java/android Development in general tbh) very well I am sadly not able to fix this issue by myself, but I would appreciate it if somebody could do it, or maybe even help me do it :).

**Comment by MilosKozak** [comment]
the alarm is important when bolus is not applied correctly because it needs manual human intervention to check what happened. you problem is pump disconnections which can be caused by disturbance in room where you are or phone itself
