### ISSUE TITLE
[Master] Nightacout crash caused a permanent local db corruption?

### ISSUE THREAD

**Issue by ninelore** [nightscout/AndroidAPS#2603]
Both nightacout and aaps master versions

It started when i was noticing that NS didnt recieve anything anymore. For a weird reason i was getting socketexceptiona in ns client.
Restarting aaps wpuldnt help, ao i redeployed nightacout from newest master. Problem was solved for a time. 

A day later my aaps would not calculate anything anymore. A loop run was lasting minutes and no cob or iob would be calculated at all. Aaps restarts and reinstalls wouldnt solve the issue, only a DB reset did.

**Comment by ninelore** [comment]
Logs will follow

**Comment by MilosKozak** [comment]
where are the logs?

**Comment by ninelore** [comment]
Sorry forgot to hit send.

I was unable to get Logs of the time when it happend. Feel free to close as not reproducable or stale.
