### ISSUE TITLE
Strange data transfer logic with xDrip

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2616]
Probably not a bug but I can't understand how it is supposed to work.

BG source is xDrip
![Screenshot_20230708_064146_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/1e205588-b86a-4a9d-8dee-4ac7b5ab1960)

But if I select xDrip as receiving data from AAPS
![Screenshot_20230708_064226_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/f0ad4b10-b3e2-4254-8405-4d52394ea3a7)

The option that activates sending data from APPS to xDrip
![Screenshot_20230708_064257_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/3c7e67fb-65c7-49dd-bb15-9bec0cff6c37)

says that BGs will be sent **from** AAPS to xDrip... 

Doesn't that logic create a loop, BGs coming from xDrip to AAPS and then getting sent back to xDrip? 

Does only _xDrip follower_ gets all those data ?

**Comment by vanelsberg** [comment]
As far as I understand:
1. BG source is xDrip+
2. AAPS is synchronizing (write only) to the selected targets (NSv1, NSv3, Tidepool, and/or xDrip+)

By logic,
BG source is only for receiving BG values, never uploading data.
Synchronizing never uploads BG values to the BG source

I think AAPS's logic/implementation never uploads BG data to the selected BG-source.
Same goes when selecting NS as BG datasource: AAPS only receives BG values and only uploads treatments (when configured for synchronization). _I can however select a additional/separate NS site for synchronizing, including BG values_.
