### ISSUE TITLE
Change - Add Option for Bolus Wizard to Stop Forcing it to be 100% with No CGM

### ISSUE THREAD

**Issue by bobhome007** [nightscout/AndroidAPS#2643]
In version AAPS 3.2 when no CGM is available, add an option to disable forcing bolus wizard to be 100% as was added in Dev 3.2.

This means users should be able to either continue the existing option in 3.1 to vary bolus % change when no CGM is available instead of accepting the forced 100% which should not be assumed to fit all users.

This was discussed in chat on the msg app where it seems some users are ok to work with it and others are not when no CGM is available.

Instead of forcing user to accept this 100% basal option, maybe have it as a config option in settings.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/cb9935d88014b4b022f7bcddc0f216b18d5105d9
