### ISSUE TITLE
[dev] NSCv1: fix TBR upload -> v3 TBR upload broken

### ISSUE THREAD

**Issue by swissalpine** [nightscout/AndroidAPS#2646]
Since I merged https://github.com/nightscout/AndroidAPS/commit/18f01d7b5930252a01bdbda86d56a1af720a0aa0 no TBR is uploaded with NSCv3 ... so I assume it is related to this fix  (Pump: ComboV2).

<img width="631" alt="image" src="https://github.com/nightscout/AndroidAPS/assets/12517693/0c2343ea-74a2-42ad-8375-bd381a8724bf">

**Comment by MilosKozak** [comment]
right, fixed by https://github.com/nightscout/AndroidAPS/commit/4406b60ecff7195266cba80bfc5b97346e94fe1e
