### ISSUE TITLE
2.8.2  INFO: Pump unreachable

### ISSUE THREAD

**Issue by Harrypatz** [nightscout/AndroidAPS#267]
Copied from comment:
Is with me also so, was already at 2.7 and 2.8 and also at 2.8.1, that my phone starts to beep without what is displayed. Only by the sound I know that the pump can not be reached. Can I then only end in which I click in settings the app AAPS end force.
Now with 2.8.2 to
09:55

**Comment by Harrypatz** [comment]
Is with me also so, was already at 2.7 and 2.8 and also at 2.8.1, that my phone starts to beep without what is displayed. Only by the sound I know that the pump can not be reached. Can I then only end in which I click in settings the app AAPS end force.
Now with 2.8.2 to
09:55
@MilosKozak 

[AndroidAPS_LOG_1611651378771.log.zip](https://github.com/nightscout/AndroidAPS/files/5872317/AndroidAPS_LOG_1611651378771.log.zip)

**Comment by AdrianLxM** [comment]
Could you please describe your setup and your settings?
Could you please attach a screenshot of the Overview (Home) in AAPS when this happens?

**Comment by Harrypatz** [comment]
What do you want to know from the settings, the list is long, or do you want to have a backup file.
On the "Home" view is nothing more to see, is as always.
In this case it was after a bolus delivery with a wizzard.

**Comment by MilosKozak** [comment]
i see the alarm is comming from NS Announcement.
You can turn it off if you don't need it
Or try to scroll down overview page if the notification appears

**Comment by Harrypatz** [comment]
@MilosKozak 

NS alarms are switched off

**Comment by StephenBrown2** [comment]
Need to turn on "Use system notifications" under "Local alerts". Can filter the full preference list for "notification" and you'll find it right away.
![Screenshot_20210126-094734~2](https://user-images.githubusercontent.com/1148665/105876320-1a05a500-5fbc-11eb-8782-58984ac4a279.png)

**Comment by MilosKozak** [comment]
NS alarms and NS announcements ?

**Comment by Harrypatz** [comment]
Yes, unfortunately it occurs again and again and more frequently

**Comment by AdrianLxM** [comment]
Does it still happen if you fully disable NSClient in the ConfigBuilder?

**Comment by Harrypatz** [comment]
@AdrianLxM  Yes, unfortunately. It's annoying, especially when you're on the road. Another problem is that the smartphone gives an alarm after the bolus has been delivered that no insulin could be delivered, in this case with a proper error message and can also be turned off, but in the smartwatch the bolus runs correctly and is also ended there normally. (Sony SW3)
