### ISSUE TITLE
Issues "clean up"?

### ISSUE THREAD

**Issue by parapenT1sta** [nightscout/AndroidAPS#2673]
I wanted to recommend to get a clean up on the "issues" pages, there are more of 160 issues opened, some of them since 2021.

Is not easier to close them all with a note "If the issue persist with the latest DEV or RC version, please comment and it will be reopened. Don't forget to upload the new logs with the latest AAPS version." If there is no comment we assume the issue is now solved or not needed anymore.

**Comment by robertrub** [comment]
Ok, cleaned up some of my old ones.
