### ISSUE TITLE
Profile change when on pump disconnect activates basal

### ISSUE THREAD

**Issue by saFariW** [nightscout/AndroidAPS#2676]
Build: dev-k (personal branch) merged at [d68869c](https://github.com/nightscout/AndroidAPS/commit/9c229e72654758f30128427fc0684d49cd68869c)
Pump: Medtrum Nano
Time: 19:15
Logs: [AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/12372103/AndroidAPS.log)

I dont believe it is intended that basal is administered after a profile change while there is a pump disconnect active.

Reproduction:
![2023-08-17-19-14-54](https://github.com/nightscout/AndroidAPS/assets/13334532/f17a81ba-12ef-4d9a-b0d3-aabfcf4d5cd1)

**Comment by jbr7rr** [comment]
This is also reproducible with dash

**Comment by jbr7rr** [comment]
@MilosKozak  Also happens on other pumps (dash)
But I will pick this one up anyway
