### ISSUE TITLE
Nightscout Urgent Stale Data Alarm

### ISSUE THREAD

**Issue by asalimian** [nightscout/AndroidAPS#2680]
Reporting bugs
--------------
- Connection Settings = [Use Wifi Connection: True, During Charging: True, else: False]
- Build 1de236a602-2023.08.01-23:14

Reason:
Not 100% sure, I no longer have those NSclient logs, but it might have been due to my VM sleeping.

Effect: 
This happened everytime I plugged in my phone to charge, and every few minutes after that. Alarm is very loud, has do-not-disturb override, and had no apparent cause or way to silence.  There was no special notification raised in android for this issue, I think it just occurs under the Ongoing notification type. (I was almost thrown out of the bedroom as well)

Workaround:
I disabled NS upload for the night, and the next day changed my NS provider. 

Suggested Fix:
Add a notification type for Nightscout Sync alarms so that it is clear to the user.

**Comment by MilosKozak** [comment]
AAPS can display alarms generated by NS. they are not changed, just displayed.
Disable this in AAPS if you don't need it
