### ISSUE TITLE
MINOR : TDD reset button too big

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2686]
It is great to have the TDD visible all the time now :) Tnx

I find the reset button a bit too big for the page.

![Screenshot_20230822_071037_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/4580e6a7-6151-44fa-a885-519d4449e8f9)

**Comment by MilosKozak** [comment]
before it was too small

**Comment by MilosKozak** [comment]
like this is alligned with other buttons
