### ISSUE TITLE
update to 3.2-RC1 asks for engineering mode 

### ISSUE THREAD

**Issue by LuisPuertollano** [nightscout/AndroidAPS#2705]
After updating from AAPS v3.1.0.3 to v3.2-rc1, AAPS asks for engineering mode to loop in dev. As I understood from this message:
https://discord.com/channels/629952586895851530/866343285294104588/1144534633426456636
It is not the expected behavior. 

Also, configurations regading BG source were changed, having changed from xdrip to byoda (I manually changed it back to xdrip), I can't assure why was this.

Remarcable is, I updated to rc1 while having an active and without losing it.
I'm not sure if I can replicate the problem. 

Thank you 😇

**Comment by MilosKozak** [comment]
it works without
![image](https://github.com/nightscout/AndroidAPS/assets/11146458/b1ff81e5-192b-444f-a3cc-1cd3565e6673)
