### ISSUE TITLE
MINOR : dev-k HR lower limit is NOT 40

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2706]
@MilosKozak Your commit sets HR graph lower limit to 40 but it does not seem to work.

![Screenshot_20230825_142210_GitHub.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/2c651a9a-15d7-4529-9b83-72e8d327810d)

![Screenshot_20230825_132627_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/225a270a-703e-4350-94cc-1d56e52a84a6)

Version is last Dev + PR 2700 for testing DASH alert suppression 

![Screenshot_20230825_131555_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/247242db-a772-467a-966a-59c4b56b50ac)

**Comment by mtanjagithub** [comment]
Sorry why 40bpm? I have a resting heart rate of 34 bpm.

Op vr 25 aug. 2023 14:24 schreef Robrub ***@***.***>:

**Comment by robertrub** [comment]
_I am an avid cyclist_

That's probably the explanation ;) 

The min can be put to 30 it it seems ok to you (or even better, automatically detected, or user defined...)

**Comment by mtanjagithub** [comment]
30 that will work!

Op vr 25 aug. 2023 17:37 schreef Robrub ***@***.***>:

**Comment by MilosKozak** [comment]
> @MilosKozak Your commit sets HR graph lower limit to 40 but it does not seem to work.
> 
> ![Screenshot_20230825_142210_GitHub.jpg](https://user-images.githubusercontent.com/76626474/263267564-2c651a9a-15d7-4529-9b83-72e8d327810d.jpg)
> 
> ![Screenshot_20230825_132627_AAPS.jpg](https://user-images.githubusercontent.com/76626474/263267591-225a270a-703e-4350-94cc-1d56e52a84a6.jpg)
> 
> Version is last Dev + PR 2700 for testing DASH alert suppression
> 
> ![Screenshot_20230825_131555_AAPS.jpg](https://user-images.githubusercontent.com/76626474/263267602-247242db-a772-467a-966a-59c4b56b50ac.jpg)

you are not on latest dev

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/98fa5ef911b5d326330854abf0bbd3f27fbaa468
