### ISSUE TITLE
Synch AAPS and NS Client not working

### ISSUE THREAD

**Issue by Garweho** [nightscout/AndroidAPS#271]
I got error message: io.socket.engineio.client.EngineIOException: xhr poll error. AAPS doesn't upload data to my Nightscout site anymore. The app and site itself are working well. Xdrip sends glucose data to Nightscout and AAPS and if I input carbs or insulin via xdrip, it shows up on Nightscout site. But AAPS is not synching with Nightscout. So if I insert carbs or insulin in AAPS, it's going nowhere. I use AAPS version 2.8.2, but got this error message already in the previous version. But before that it worked. 

![Screenshot_20210128-154730](https://user-images.githubusercontent.com/39862850/106158421-01e08200-6184-11eb-9bec-83246af2b53f.png)
![error](https://user-images.githubusercontent.com/39862850/106158439-073dcc80-6184-11eb-9a74-db813afe8dad.jpg)
![version](https://user-images.githubusercontent.com/39862850/106158458-0a38bd00-6184-11eb-8869-ce63e180275a.jpg)

**Comment by MilosKozak** [comment]
where is you NS hosted? based on the message AAPS is loosing connection to the server until it's get paused
it's NS or internet issue

**Comment by Garweho** [comment]
it's hosted on my own pi server. strange it worked fine for several months, but started just now. don't remember I made any changed to server. do you know what this error message means or what problem the server could have?

**Comment by rapocalypse** [comment]
I'm seeing the same problem with a friend, that runs the NS on Heroku. Xdrip is sending BS readings to NS on Heroku, but AAPS isn't connecting to it, and pausing the client.

Even after restarting the smartphone or just the NSClient, for about 2 minutes the connection seams to be ok, but right after it goes on pause again.

**Comment by Garweho** [comment]
OK, tried old Version ( AAPS 2.7.0) which definately worked before. Having same problem now. So I guess it must really have something to do with internet or server/NS.
