### ISSUE TITLE
Is full NS sync being worked on?

### ISSUE THREAD

**Issue by JohnKitching** [nightscout/AndroidAPS#272]
Sorry to ask here but I can't find an answer elsewhere. 

Is the intention to go back to full NightScout sync without having to enable engineering mode with a future version. 
Or is the intention to leave it as it is?

**Comment by vagtil** [comment]
It is a crucial feature for all parents to have this ability. We need this feature back,

**Comment by MilosKozak** [comment]
it wil be reenabled once new NSClient is finished
