### ISSUE TITLE
Feature request: No yellow flag for G6

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2722]
Not really a paramount request.

When we change from one G6 transmitter to a new one, as their _BG lecture times_ differ by minutes, AAPS shows the yellow flag for 36 (?) hours. This information is false as there is only 1 recalculated reading.

Some thing happens every 10 days when you use 2 transmitters in order to suppress the _heating_ gap and the imprecision (for 24h - 36h) of a starting sensor.

Would it be possible (logical ?) to suppress the yellow flag if there were (per ex) 12 readings (= 1 hour) all with 5 min gaps ? 

I know that the yellow flag doesn't affect the loop but in this case, it signals a wrong "alert".

**Comment by MilosKozak** [comment]
the recalculation is done on whole 36h interval
