### ISSUE TITLE
BG upload from AAPS

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2723]
Seems like the BG data received from xDrip and **sent to NS by AAPS** differs from the one sent **directly from xDrip**

![Screenshot_20230831_085536_GitHub.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/85dacb75-e2e6-405b-b1ee-a5aa6e345136)

This is what I see for data sent directly from xDrip

![Screenshot_20230901_082651_DuckDuckGo.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/218be812-fce4-4035-8e89-e4991e9e1166)

And this is what the data sent from AAPS shows

![Screenshot_20230901_082720_DuckDuckGo.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/c0ddb01a-956e-4a89-9240-d29394f1e4c0)

Latest Dev + PR2700

![Screenshot_20230831_213308_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/15aa1a60-43e7-423d-a9cc-a80bd5beba89)

**Comment by MilosKozak** [comment]
yes, noise is not processed by AAPS because it's only xdrip thing
