### ISSUE TITLE
First BG reading not displayed on main screen

### ISSUE THREAD

**Issue by dar-kod** [nightscout/AndroidAPS#2727]
AAPS: 3.2.0-dev-l
xDrip+: c53c844-2023.08.27
Dexcom G6

Steps:
1. Uninstall the AAPS 3.2.0-dev-k application and install the new version.
2. Wait for the next BG value in xDrip+ to be sent to AAPS.
 
The first BG value arrives in xDrip+ and AAPS as seen in the **XDRIP+ BG** tab, but it is not displayed in the main screen. Not displaying the value is only an issue for the first value.

Here are attached screenshots and log file:

![1693584300434](https://github.com/nightscout/AndroidAPS/assets/24446806/1d174285-d4a9-4ea6-a247-c8db52b3bdfe)
![1693584300429](https://github.com/nightscout/AndroidAPS/assets/24446806/04dc2775-ea6b-479f-a514-233b374e8f40)
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/12499764/AndroidAPS.log)

**Comment by MilosKozak** [comment]
resolved by https://github.com/nightscout/AndroidAPS/commit/50818c2d4c01eca654631fa69e21f7148a5238ff
