### ISSUE TITLE
Basal+Bolus=TDD

### ISSUE THREAD

**Issue by JimZam** [nightscout/AndroidAPS#273]
Good morning. I don't know if it's an issue, just a question about Daily Dosis. In Actions/Daily Dose AAPS reports the Total Daily Dose for several days as the sum of Bolus + Basal. But if I add all the bolus reported in Treatments or uploaded to Nightscout it's not the same as the Bolus reported in Daily Dose. I've checked for several days and it's never the same. How does AAPS calculate the Daily Bolus? Which is the correct one?
Thank you and regards

**Comment by AdrianLxM** [comment]
This is the pump history. It counts whatever the pump counts into daily Basal/Bolus/TDD

**Comment by szantos** [comment]
@AdrianLxM 
This info should be displayed with a hint which calculation is the correct one.

Nightscout report shows a third value:

![image](https://user-images.githubusercontent.com/64865503/108760193-a4a2db00-754d-11eb-9da3-3bf629373695.png)

In AAPS it would be sufficient to display only the correct values, and Nightscout should match it. The current system causes a bit of confusion.

Please consider reopening.
