### ISSUE TITLE
Minor : About/ Show NS version

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2735]
Actually, in the _About_ window, NS version is only shown if AAPS is connected to NS at the same time. 

If NS connection is set to "connect when charging" in AAPS, even if the phone was charging 5 minutes ago (but is no more), the About screen forgets the NS version.

As NS version changes very rarely, it would be nice if the About window shoved the last NS version AAPS had detected.

![Screenshot_20230904_133803_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/ba5be77b-5a03-424e-8537-264abb42236c)

![Screenshot_20230903_181601_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/40cd32a0-6e6d-41f5-9dc9-9ade6c71de32)

**Comment by vanelsberg** [comment]
Confirming. Seeing the same on dev-m
Repro: switch off: connect settings -> On battery (while not charging)

**Comment by robertrub** [comment]
@MilosKozak Has there been work on this issue ? The problem has been solved.

I don't know if installing NS v15 _MASTER_ fixed it (was using NS v15 _dev_ till now) or if you fixed the code.

No upload to NS at the moment and NS version is still visible in _About_👍

Do I close this issue?

![Screenshot_20231020_153120_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/a9f0b460-258f-4ebf-9a3c-e694949a3552)

**Comment by vanelsberg** [comment]
> @MilosKozak Has there been work on this issue ? The problem has been solved.

Confirming!

**Comment by robertrub** [comment]
Hi @MilosKozak 
I don't know why you had reopened this issue. It has been solved. Now, once AAPS has connected to NS, the NS version info stays put in about and is visible even when not uploading.
I'm closing it.
