### ISSUE TITLE
NSClient: WIFI connection option ignored

### ISSUE THREAD

**Issue by RBarth-DE** [nightscout/AndroidAPS#2740]
Hi,

NSClient still tries to sync when WIFI is connected even option is disabled in settings.
Seems that WIFI option has no effect on sync. All other options (charging, battery, mobile network,...) are working OK.

Result: 
07:56:46.715 [RxCachedThreadScheduler-35] D/NSCLIENT: [NSClientPlugin.onStart$lambda-5():116]: ERROR io.socket.engineio.client.EngineIOException: xhr poll error

Background:
My NS server is not reachable via WIFI, only when connected via mobile network. If I am on wifi, NSClient alwa<s try to sync and I get an "ERROR io.socket.engineio.client.EngineIOException: xhr poll error" error. Not sure this is responsible for higher CPU load / battery usage.

AndroidAPS 3.1.0.3+autoISF2.2.8.1
NS-Version 14.2.6

![Screenshot_20230905-081214_AndroidAPS](https://github.com/nightscout/AndroidAPS/assets/92302964/3cf20a7c-4331-4065-be0b-519948b8aebc)

Logfile:
[all.log](https://github.com/nightscout/AndroidAPS/files/12519555/all.log)

**Comment by MilosKozak** [comment]
this has been rewritten in 3.2
test new release when it comes up
