### ISSUE TITLE
DynISF not adjusting ISF anymore [latest dev-l]

### ISSUE THREAD

**Issue by yhonatanb20** [nightscout/AndroidAPS#2741]
Updated to dev-l yesterday. Since then DynISF not actually working - ISF remains unchanged.
![Screenshot_20230905_143056_AAPS](https://github.com/nightscout/AndroidAPS/assets/93551840/b6133c3d-5c82-4ff9-9193-190f3a7d7496)
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/12522915/AndroidAPS.log)

**Comment by jbr7rr** [comment]
Start objective 11
