### ISSUE TITLE
[DEV] AAPSclient occasionally misses downloads

### ISSUE THREAD

**Issue by szantos** [nightscout/AndroidAPS#2748]
The data is there in NS, but not everything gets downloaded. Sometimes SGVs (entries) are missing. I'm not sure, if it's an AAPS or NS issue.

The particular case in the screenshots/log (TBR missing on the left side) has happened this morning after turning on the AAPSclient device, but in rare cases it can happen during the day, too when the device is on. Missing data won't get backfilled, even if I force close AAPSclient, delete cache and restart NSClient.

AAPS 3.2.0-dev-l 5c34184723-2023.08.30 with NSClientV3+websockets
NS dev v15: [d602de1](https://github.com/nightscout/cgm-remote-monitor/commit/d602de1c474c212ab8f27d17d18ce12d5679c990)
LOG: [Log Export.txt](https://github.com/nightscout/AndroidAPS/files/12545451/Log.Export.txt)

![Screenshot_20230907-061501_Chrome](https://github.com/nightscout/AndroidAPS/assets/64865503/c94061f4-ef34-430a-8a25-745e27304c7a)

![Screenshot_20230907-061108_AAPSClient~2](https://github.com/nightscout/AndroidAPS/assets/64865503/2b6c4f57-3b2c-48fb-8eb0-ee7e78840bd7)

**Comment by MilosKozak** [comment]
what is the timestamp of missing bg?

**Comment by MilosKozak** [comment]
do they backfill when you reset sync on aapsclient? provide logs from backfill if not

**Comment by MilosKozak** [comment]
and reset logging to default before

**Comment by szantos** [comment]
> do they backfill when you reset sync on aapsclient? provide logs from backfill if not

How do I perform "reset sync"?

**Comment by szantos** [comment]
This morning it happened again:
- on the left BG is missing
- that 25g was a bolus wizard entry: CH and bolus wizard details got synced, but no insulin

![Screenshot_20230911-081932_AAPSClient](https://github.com/nightscout/AndroidAPS/assets/64865503/e05158a1-36c5-49cd-aeb6-f3eb99647a69)

[Log Export 2023-09-11_1.txt](https://github.com/nightscout/AndroidAPS/files/12572819/Log.Export.2023-09-11_1.txt)
[Log Export 2023-09-11_2.txt](https://github.com/nightscout/AndroidAPS/files/12572817/Log.Export.2023-09-11_2.txt)

**Comment by MilosKozak** [comment]
resolved in https://github.com/nightscout/AndroidAPS/commit/d379b769d3739b75bb02d07d300f41871cb18c6d
