### ISSUE TITLE
[UI suggestion] Move bolus total line to top in calculator

### ISSUE THREAD

**Issue by Yobivas** [nightscout/AndroidAPS#2754]
When inputting carbs in calculator using the +/- buttons, the line with the total bolus is obstructed by my hand. I suggest moving it to the top of the dialog.

**Comment by MilosKozak** [comment]
could you attach screenshot and mark it?

**Comment by Yobivas** [comment]
![Screenshot_20230910_063841_AAPS](https://github.com/nightscout/AndroidAPS/assets/95351916/30769f49-b701-4eb3-bf7a-dd3febd93bef)

**Comment by olorinmaia** [comment]
I think most calculators got the result @ top of screen.  Mostly so you don't cover the result while typing. I'm positive to this change

**Comment by robertrub** [comment]
You can close this issue as it has been implemented in Dev.

![Screenshot_20231020_153017_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/f2bf5c51-c69c-4869-bca1-626a1c6a6cf4)
