### ISSUE TITLE
BUG ? : AAPS BG upload to NS / No Delta

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2757]
Don't know if this is a feature or a bug ;)

When, xDrip uploads BGs to NS, it has a _Delta_ value. When AAPS receives BGs from xDrip and uploads them to NS, there is no _Delta_ value.  If people used the xDrip upload for personal displays, things can get broken if the _Delta_ value was used.

![image](https://github.com/nightscout/AndroidAPS/assets/76626474/5249096e-a887-48f9-bafe-b2c83e2274a7)

**Comment by MilosKozak** [comment]
delta is calculated by NS. delta field is xdrip specific thing
