### ISSUE TITLE
[3.2.0-rc1] Bug: Calculator resulted from previous profile right after profile change.

### ISSUE THREAD

**Issue by T1DLiberation** [nightscout/AndroidAPS#2769]
I am running AAPS 3.2.0-rc1 build: dd6081efd2-2023.08.28 on Samsung Galaxy S9+, Android 10

I use calculator for a meal bolus. The bug occurred right after I changed my profile. I chose one of existing several profiles from profile section when I change my profile.
The issue is calculator getting result from previous profile, not the current running one until it gets new BG. Since new BG has arrived, calculator computes based on current running profile correctly.

**Comment by MilosKozak** [comment]
this is really strange. I didn't work for me too. I started  looking for the bug but at the end it works without any modification.
Maybe just reinstallation helped
