### ISSUE TITLE
Hidden sub-menu in settings (can only be found via search function) 

### ISSUE THREAD

**Issue by blochj** [nightscout/AndroidAPS#2774]
Hi all,
Not sure if this is the right place, but I found a sub-menu that only appears if I search for it (funnily enough only without the last 3 letters... See different screenshots) but not when I just scroll to the respective section. Sorry but my app is in German and unsure if same issue exists in other languages or maybe even is meant to be a feature rather than a bug 🙂
Now on RC1 but same behaviour already occured on 3.1.0.3.

![Screenshot_20230912_195102_AAPSClient.jpg](https://github.com/nightscout/AndroidAPS/assets/108429726/ee58306b-f54a-4ec6-9101-9bcb89570557)

![Screenshot_20230912_195109_AAPSClient.jpg](https://github.com/nightscout/AndroidAPS/assets/108429726/aa8c2f56-5e37-4f7b-9a20-fbef2d39d34b)

![Screenshot_20230912_195003_AAPSClient.jpg](https://github.com/nightscout/AndroidAPS/assets/108429726/07addbda-5c49-4083-8798-1139429cb66c)

![Screenshot_20230912_195036_AAPSClient.jpg](https://github.com/nightscout/AndroidAPS/assets/108429726/bd3e61ce-a00a-4772-b17d-54247bd73b0d)

**Comment by MilosKozak** [comment]
this is bug in android Preferences library. Some preferences are hidden but it's possible to get there by search, clicking forward and back etc
so far there is nothing we can do except write own library

**Comment by blochj** [comment]
All clear - thank you for the swift feedback.
If the bug affects the same sub-menus for everyone, would it make sense to list them in the wiki/documentation? I found it more by coincidence... Thank you
