### ISSUE TITLE
[DEV] Manual meal bolus not uploaded to NS

### ISSUE THREAD

**Issue by jbr7rr** [nightscout/AndroidAPS#2776]
Build: Personal build at f271c5a92d42bceea01659d57422c36e45b4898e
Pump: Medtrum Nano
Time:  18:34 - 18:44
Logs:  [AndroidAPS_2023-09-13.zip](https://github.com/nightscout/AndroidAPS/files/12600286/AndroidAPS_2023-09-13.zip)

During patch change I did a manual bolus, after patch activation I entered the treatment into AAPS. With a time-shift of 10 minutes into the past
It was not uploaded to NS.

Might be an unwanted side effect of 394883165d2f6603286d7bb56f6312d8b742c3b8 ?

![WhatsApp Image 2023-09-13 at 19 11 00](https://github.com/nightscout/AndroidAPS/assets/60566713/739e1dcd-5707-4a30-a6ff-68d6f2848da9)

**Comment by MilosKozak** [comment]
it is
please test with https://github.com/nightscout/AndroidAPS/commit/d302e6eb55f648144339260bd678b4e3195eb3bd

**Comment by jbr7rr** [comment]
Thx works as expected now
