### ISSUE TITLE
[DEV] AAPSClient does not upload bolus to NS

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#2777]
AAPSClient 3.2.0-dev-l
Build: d379b769d3-2023.09.13
Flavor: aapsclientrelease
Nightscout version: 15 (latest dev)

Step by step:
14:29 Add bolus 0,10 U from AAPSClient (e.g. manual bolus given by pen)
14:38 Still not uploaded to NS

Tested with V1, V3 + WS on/off. All fail.

Logs:
[AndroidAPS_LOG_1694695023504.log.zip](https://github.com/nightscout/AndroidAPS/files/12608820/AndroidAPS_LOG_1694695023504.log.zip)

![image](https://github.com/nightscout/AndroidAPS/assets/114103483/9209cac1-6d72-4784-aa12-b4dbe3144214)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/c0eb8b05-cd08-473a-b98c-24309c158b50)

**Comment by MilosKozak** [comment]
same as #2776 
update and test pls
