### ISSUE TITLE
[DEV] AAPS/AAPSClient suffer slow sync in V3+WS=on compared to V1 API

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#2778]
AAPSClient / AAPS 3.2.0-dev-l
Build: d379b769d3-2023.09.13
Nightscout: 15 (latest dev)
Pump AAPS/AAPSClient: Virtual pump (Dash)

I have done some testing (attached picture of spreadsheet)  with dev-l d379b769d3-2023.09.13. Both with v1 API and v3 API + websockets on to see how sync performs.

From a parents perspective we are using NSClient/AAPSClient alot, and key for us is fast and reliable sync. It seems to me that v3 API with websockets ON are way slower on some operations than v1 API. 

My expectation is that v3 API WS=on is as fast as V1 API. As you can see of spreadsheet V1 API works well similar to what of master version now.

I'll list the different actions that after my view has slow sync.

**AAPS:**
* Enact Temp profile
* Edit/create/delete profile

Log from slow temp profile change, time 14:44:
[AndroidAPS_LOG_1694696140096.log.zip](https://github.com/nightscout/AndroidAPS/files/12608992/AndroidAPS_LOG_1694696140096.log.zip)

**AAPSClient:**
* Set TT
* Cancel TT
* Enact Temp profile
* Edit/create/delete profile 

Log from slow "Set TT", time 14:56:
[AndroidAPS_LOG_1694696426834.log.zip](https://github.com/nightscout/AndroidAPS/files/12609015/AndroidAPS_LOG_1694696426834.log.zip)

**Results of testing V3 API with Websockets = ON**
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/46569c60-9f8a-4f76-86e4-573bb88c94f0)

**Results of testing V1 API:**
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/7ea26afd-bbc0-4b7c-ad92-27eca49b48ee)

![image](https://github.com/nightscout/AndroidAPS/assets/114103483/04001f18-43e5-4dbd-b2cc-5979f48d9e28)

**Comment by MilosKozak** [comment]
improved by https://github.com/nightscout/AndroidAPS/commit/d2247dc9bcf37b6ddf65a6018e10f63346e764e4

**Comment by MilosKozak** [comment]
and https://github.com/nightscout/AndroidAPS/commit/471ed28a04ccd93afb6d2f33d1c7fad3c11ef640
