### ISSUE TITLE
[DEV] "PH" gets added in Treatments history when manual bolus (not delivered by pump)

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#2782]
AAPSClient 3.2.0-dev-l
Build: 471ed28a04-2023.09.14
Flavor: aapsclientrelease
Nightscout version: NS15 dev

Step by step
1) Bolus from AAPSClient or AAPS, toggle "do not bolus, record only". 
or
1) Bolus from AAPSClient Calculator (Possibly also Wear AAPSClient Calc and manual bolus / treat?)
2) Successful sync, but "PH" gets added to treatment history

Expected result would be only "NS".

[AndroidAPS_LOG_1694728318735.log.zip](https://github.com/nightscout/AndroidAPS/files/12613848/AndroidAPS_LOG_1694728318735.log.zip)

![image](https://github.com/nightscout/AndroidAPS/assets/114103483/ff034f4a-e7f9-488f-8997-242664313e7a)

![image](https://github.com/nightscout/AndroidAPS/assets/114103483/81304031-125a-432a-b45e-dee6a170f08f)

**Comment by jbr7rr** [comment]
Yes I see the same with hardware pump

@MilosKozak 

Is it an idea to make the original fix https://github.com/nightscout/AndroidAPS/commit/394883165d2f6603286d7bb56f6312d8b742c3b8 include a check if there is a temporaryId and pumpId is null to then exclude it ?

**Comment by MilosKozak** [comment]
resolved in https://github.com/nightscout/AndroidAPS/commit/275e52a546791ff044121bce6984a778b724a2c6

**Comment by olorinmaia** [comment]
@MilosKozak Could you apply the same fix to the Calculator in AAPSClient. If I do a bolus via the Calculator in AAPSClient "PH" gets added in treatment history as well. Maybe check Wear AAPSClient calculator also.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/ccabee0399d33427ffa8837e53d6756d569e99b5
