### ISSUE TITLE
Wear calculator percentage increment and range differ from AAPS calculator

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#2783]
In wear app today increment is 1% while in AAPS increment is 5% for each click. Also you can't go lower than 50% in wear app, while in AAPS you can go down to 10%. Some time you may want to dose lower than 50%, and then are forced to use AAPS calculator :)

To sum it up:
Range in AAPS: 10-200%
Range in Wear: 50-150%
Increment in AAPS: 5%
Increment in Wear: 1%

It would make sense that wear app calculator got same range and increment as AAPS calculator.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/dec3b1ca2fbd21797f17031282de52b3d186772e
