### ISSUE TITLE
Wear tiles, menus and settings aren't translated for Norwegian language

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#2790]
In wear app for AAPS / AAPSClient (master and also dev) there are missing translations for almost all icons in the tiles, text in menu and settings although I think everything is translated in e.g. Norwegian. 

I notice that for example "Cancel" is translated to "Avbryt" in Norwegian but nothing else. in the temp-target tile. All other tiles / settings are in English. If I activate an item in any tile, the following screen up to confirmation isnt translated, after confirmation some translation is done.

My main AAPS has Norwegian language, and clock and phone is Norwegian language (if it matters)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/986095db-ff06-4caa-aacb-a28f6a75decb)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/bdff08ed-337c-4478-8d80-64c6eb4420ad)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/28cbd5ca-2702-4a28-a95a-af7ffda9e414)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/1cd0460e-01a3-4757-a6f1-b0e069f66514)

**Comment by olorinmaia** [comment]
@MilosKozak 

Updated to  AAPS 3.2.0-dev-l c52c0e1125-2023.09.20 and updated also wear APK and did a fresh install on watch.

I can't see any change in issue described above originally. If I change language in AAPS to English "Avbryt" turns to "Cancel" in the tiles, but all tiles except of that one stay in english no matter what language in AAPS. 

![image](https://github.com/nightscout/AndroidAPS/assets/114103483/367dea8e-b768-47be-b5bf-37faa84aeaab)

**Comment by MilosKozak** [comment]
I agree it doesn't work but it works for other languages tested. Probably android bug

**Comment by olorinmaia** [comment]
Cant see any difference if I change language in AAPS go Swedish for example. Or do I need to change system language on phone?

I thought language setting in AAPS decided what getting translated in app and wear. If that is true this also happen for Swedish, German I tested just now.

**Comment by olorinmaia** [comment]
I notice if I change language in android to Swedish and use system default language in AAPS all translations in AAPS and wear turns Swedish. So that means system language in android does matter.

If I use Norwegian as system language in android only small parts gets translated in AAPS and wear if I use language = system default in AAPS. 
Is there some reason AAPS don't support Norwegian as system language vs Swedish or is it just a android bug?

**Comment by olorinmaia** [comment]
![Screenshot_20230923_001217_Settings](https://github.com/nightscout/AndroidAPS/assets/114103483/a401776e-be1f-4940-9cb8-058e0db22d67)
Norwegian got three choices in android. It's Norwegian bokmål that is 100% right in most cases. In comparison Sweden only got one option.

**Comment by MilosKozak** [comment]
translation is done for language marked 2 on your screenshot. Internation code "no"

**Comment by MilosKozak** [comment]
![image](https://github.com/nightscout/AndroidAPS/assets/11146458/c268f58d-951b-4083-9df3-bb937bbc68d4)

**Comment by olorinmaia** [comment]
This is wrong since 99,9% use number 1 in my list and also standard setting when setting up a phone in Norwegian.

Norwegian bokmål should be chosen. If possible all those Norwegian choices should recieve til translation in Norwegian.

**Comment by MilosKozak** [comment]
well I can enable Norwegian Bokmal in Crowdin but it will mean new translation

**Comment by olorinmaia** [comment]
They can't be merged or copyied over? So we basically have translated for a language that doesnt get recognized via the default system language in android for Norway. Workaround is now to select "Norwegian" as language in AAPS. but that doesnt translate all correctly in wear as this issue describes.

Is it possible to edit the current translation to Norwegian bokmål instead and see if that fixes this issue so we dont have to translate everything again? And also not continue translating for a Norwegian language noone uses? ;)

**Comment by olorinmaia** [comment]
I noticed something in the code, not sure if it matters. 

Where translation doesn't work it looks like this: 
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/045660e9-f3ba-4ee7-82c5-8a1a1a8f1687)

Where it works it looks like this: (nb)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/eeee514f-0492-4e3b-8c46-201a2102ad68)

**Comment by Philoul** [comment]
@MilosKozak I asked @olorinmaia to create within wear resources a new subfolder `values-nb-rNO` and copy paste in it the string file included into `values-no-rNO`
=> It fixed the tiles translation issue for him...
So I think enabling Norwegian Bokmal in Crowdin will fix this issue...

**Comment by olorinmaia** [comment]
Thanks @Philoul  :) I solved the issue locally, so I'm happy. But for other Norwegian users it would be nice to find a permanent solution. 

We know now that "values-nb-rNO" translates correctly (Norwegian Bokmål). Is there any way to copy all translated strings already done in Norwegian over to Norwegian bokmål? 
If not, I suggest we add it, and I start translating all wear strings, and leave the rest for when I got time. (Since you can force norwegian within AAPS by selecting Norwegian language)

**Comment by olorinmaia** [comment]
Norwegian bokmål added to crowdin and uploaded the "old" Norwegian translations. Going to build and check that this fixes this issue tomorrow.

![image](https://github.com/nightscout/AndroidAPS/assets/114103483/806105a0-91f7-4d7e-a7de-02c2904d72b3)

**Comment by olorinmaia** [comment]
Fixed in dev with fdc9ac1b
