### ISSUE TITLE
[DEV] AAPS/AAPSClient NSV3-tab getting alot of spam and stops sync (V3+WS API)

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#2792]
AAPS/AAPSClient 3.2.0-dev-l
Build: f717d7a0b2-2023.09.16

Not sure what triggered it, but last operation I made was enacting TT from AAPSClient around 15:55. Then checked logs and there is alot of spam in both AAPS/AAPSClient NSV3-tab. As a consequence sync isnt working. at 16:05 spam is still there in both tabs.

Workaround:
Disable v3 API, enable v1 API. Then after sync is fixed, v3 API can be used again.

Screens: 
AAPSClient:
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/3b7fb00a-495e-4677-aca0-ca2c3110a123)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/9b505eeb-3bd3-4a38-935e-c212804b456c)

AAPS:
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/512b39e3-e56d-4c4e-b9a2-aea8ed15eb4a)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/eb1935a8-acd6-4088-8e22-9c0e1758a2a5)

Logs AAPS:
[AndroidAPS_LOG_1694959105301.log.zip](https://github.com/nightscout/AndroidAPS/files/12642979/AndroidAPS_LOG_1694959105301.log.zip)
Logs AAPSClient:
[AndroidAPS_LOG_1694959080007.log.zip](https://github.com/nightscout/AndroidAPS/files/12642981/AndroidAPS_LOG_1694959080007.log.zip)
From 16:05
[AndroidAPS_LOG_1694959585235.log.zip](https://github.com/nightscout/AndroidAPS/files/12642997/AndroidAPS_LOG_1694959585235.log.zip)

**Comment by Alamo04** [comment]
Confirmed.

Old issue comes up again = Profile Spamming

[AndroidAPS_LOG_1695038502416.log.zip](https://github.com/nightscout/AndroidAPS/files/12647544/AndroidAPS_LOG_1695038502416.log.zip)

**Comment by NighthawkEvP** [comment]
also confirmed

**Comment by MilosKozak** [comment]
https://github.com/nightscout/cgm-remote-monitor/issues/8096

**Comment by MilosKozak** [comment]
https://github.com/nightscout/cgm-remote-monitor/pull/8100

**Comment by parapenT1sta** [comment]
> [nightscout/cgm-remote-monitor#8100](https://github.com/nightscout/cgm-remote-monitor/pull/8100) this resolve the issue

When will be merged? Do you have an idea?
CGM Monitor is slower than AAPS repo :-)

**Comment by MilosKozak** [comment]
@bewest is maintaining NS repo now
