### ISSUE TITLE
[DEV] AAPS IOB differ from AAPSClient (tested with v1 API)

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#2796]
AAPSClient 3.2.0-dev-l
Build: f717d7a0b2-2023.09.16
Remote: https://github.com/nightscout/AndroidAPS
Flavor: aapsclientrelease
Nightscout versjon: 15.0.0

See attached screenshots. Seems like a temp basal at 17:04 is the culprit.

**Logs:**
[AndroidAPS_LOG_1695056440606.log.zip](https://github.com/nightscout/AndroidAPS/files/12651529/AndroidAPS_LOG_1695056440606.log.zip)

**Screenshot AAPSClient:**
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/5823fe4f-2a62-4e96-9384-add5bc9909f7)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/798b6fef-0425-4987-9e9b-60490dbfc080)

**Screenshot AAPS:**
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/adf77f85-1584-4631-93cd-5f915f7c9cb9)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/ff928727-8f0c-4a70-945f-e618759d671f)

**Comment by olorinmaia** [comment]
Happend again.
Logs AAPS:
[AndroidAPS_LOG_1695239877826.log.zip](https://github.com/nightscout/AndroidAPS/files/12677159/AndroidAPS_LOG_1695239877826.log.zip)
Logs AAPSClient:
[AndroidAPS_LOG_1695236772114.log.zip](https://github.com/nightscout/AndroidAPS/files/12677161/AndroidAPS_LOG_1695236772114.log.zip)

Time: 20:30
AAPSClient:
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/07b341ec-d7c0-482e-af59-fdacf55c38df)
AAPS:
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/702b76c3-08bc-4924-8599-142df75a36b6)

**Comment by olorinmaia** [comment]
I know I changed from v3 APi to v1 API before I noticed it, if that's whats causes it then it will probably not be normal behaviour as most people will stick with one type of api until forced onto the other.

**Comment by MilosKozak** [comment]
the record has wrong duration. what is in NS?

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/8c6157b8f6219bd826543393a9cc570bab7b23bb
