### ISSUE TITLE
[DEV] AAPSClient profile switch update is delayed and causes BG to not update from NS (V3+WS API)

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#2809]
AAPSClient 3.2.0-dev-l
Build: c52c0e1125-2023.09.20
Only applies to V3+WS API

21:29: Enact profile change 120% +30min from AAPSClient. AAPS update profile fast. Visually change pretty fast.
21:30 new BG arrives in AAPS, sync NS. But does not sync to AAPSClient. AAPSClient gets profile change updated.

21:33 enact profile change from AAPSClient. AAPS updates 21:34.
21:35 AAPSClient update profile but misses also next bg. No BG for 10 minutes.

Usually on next BG new and previous missed BG updates in AAPSClient.

[AndroidAPS_LOG_1695238602956.log.zip](https://github.com/nightscout/AndroidAPS/files/12676931/AndroidAPS_LOG_1695238602956.log.zip)

![image](https://github.com/nightscout/AndroidAPS/assets/114103483/5ac0d6e9-dbdb-45ad-a611-ccd5172d1cf7)

**Comment by MilosKozak** [comment]
resolved here https://github.com/nightscout/AndroidAPS/commit/7cb27fced0a6260bc9486f005b7ab779dade38c8
