### ISSUE TITLE
[DEV] Autosens is shown on Overview even if disabled

### ISSUE THREAD

**Issue by justmara** [nightscout/AndroidAPS#2815]
[This](https://github.com/nightscout/AndroidAPS/blob/dev/plugins/main/src/main/java/info/nightscout/plugins/general/overview/OverviewFragment.kt#L1091) line of code makes aaps always draw Autosens data on overview screen as 'active', even if isAutosensModeEnabled() returns false.

<img width="117" alt="image" src="https://github.com/nightscout/AndroidAPS/assets/4157587/b0c00a54-0b5c-4c6b-affd-4f9a8a981a26">
<img width="474" alt="image" src="https://github.com/nightscout/AndroidAPS/assets/4157587/bd44ab87-aa12-433f-b002-d60b9992856a">

**Comment by NighthawkEvP** [comment]
And if you select dynISF the related figures are missing since a few days. 
Could that be related to the Autosens thing?

**Comment by MilosKozak** [comment]
this is by design because it's calculated anyway. it's there to notify user some change can be usefull

**Comment by justmara** [comment]
@MilosKozak  There is special icon with `x`-mark that were used to show `disabled` autosens. Why it is not used anymore? The design has changed?

**Comment by MilosKozak** [comment]
right! resolved in https://github.com/nightscout/AndroidAPS/commit/0ef3d9b3757cc3b983132cae832d04cb51180395
