### ISSUE TITLE
[DEV] BG in AAPSClient differ from AAPS/NS by decimal (v1 API)

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#2832]
AAPSClient 3.2.0-dev-l
Build: bdfa4a98fc-2023.09.24
Flavor: aapsclientrelease
Nightscout versjon: 15.0.0

Only applies to V1 API. in V3 BG is same in AAPS/AAPSClient and NS.

Logs AAPSClient:
[AndroidAPS_LOG_1695560769859.log.zip](https://github.com/nightscout/AndroidAPS/files/12708560/AndroidAPS_LOG_1695560769859.log.zip)

Screenshots: top images are AAPS, bottom AAPSClient.
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/0198b5a1-4e25-4700-a330-bed3aca18bcf)
NS:
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/0d5c442e-6246-4506-b115-abaf72c690d0)

**Comment by MilosKozak** [comment]
I need log from boh sides

**Comment by olorinmaia** [comment]
Is this what you need? from today:
AAPSClient:
[Uploading AndroidAPS_LOG_1695677050900.log.zip…]()

serverlog from ns.10be.de:
[ns.10be.de_serverlog.txt](https://github.com/nightscout/AndroidAPS/files/12719526/ns.10be.de_serverlog.txt)

Screens:
AAPS BG: (Same as NS)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/d9a9bc70-8734-4075-bd38-5d22c9c0ff9c)

AAPSClient BG:
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/6ec191da-e751-4cbe-8920-57e7929e31ec)

**Comment by olorinmaia** [comment]
I don't feel it's right to use time on this, since v1
