### ISSUE TITLE
[DEV] Crash on trying to enter minutes in TT window

### ISSUE THREAD

**Issue by jbr7rr** [nightscout/AndroidAPS#2839]
Build: 92558e9d65-2023.09.25
Time: 08:21
Log: [AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/12723522/AndroidAPS.log)

App crash when trying to enter duration in temp target dialog

How to reproduce:

- Open TT dialog
- Press the minutes field, so keyboard will pop op
- App will crash

**Comment by NighthawkEvP** [comment]
same here, app crashes by entering the first digit

**Comment by hemmann** [comment]
here are the screenshots

![Screenshot_2023-09-26-09-22-04-77_3eaa31bb2c2a38a1c605d9dc918cf694](https://github.com/nightscout/AndroidAPS/assets/72262044/d4e46134-6b33-4a6e-a077-6b77ff183d49)
![Screenshot_2023-09-26-10-13-45-55_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/nightscout/AndroidAPS/assets/72262044/16a1f5d1-153e-4999-92c3-babf9003b3c3)
![Screenshot_2023-09-26-09-22-17-28_3eaa31bb2c2a38a1c605d9dc918cf694](https://github.com/nightscout/AndroidAPS/assets/72262044/34ca1e06-e624-4ec6-9060-79b85e2f8ac9)

**Comment by parapenT1sta** [comment]
> mine don't crash android version?

Mine is also OK.

**Comment by MilosKozak** [comment]
tested on 
Androd12 (digital clock appear - keyboard popup)
Android 13 (analog clock appear - no keyboard)
no crash :(

**Comment by jbr7rr** [comment]
Pixel 6Pro android 13 > Crash
Redmi Note with custom rom android 11 also crash.

Will see if I can create stacktrace later today

**Comment by NighthawkEvP** [comment]
in my case it is on a Pixel 5 with Android 13 and it seems to be in every case where a numeric keyboard is used. I tried TT and bolus assistent and both did crash. I went back to the version from 15.09.2023.

**Comment by jbr7rr** [comment]
Stacktrace:
```

**Comment by MilosKozak** [comment]
try to update
Androd java lib was not properly marked @Nullable

**Comment by jbr7rr** [comment]
Jup, works for me! Thx!

**Comment by NighthawkEvP** [comment]
works like a charm!
Thx Milos!
