### ISSUE TITLE
2.8.2  Error on the basal graphics

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#284]
At first, I thought that is was a bug and that the graph was showing basals when the rate was zero. But, ss it has been pointed our, between basals at zero, AAPS reverted to the basic basal rates for several minutes.

What I can't understand is, why reactivate basals when BGs are going down steadily.

I can understand that around 2:30 AM, there is a small BG raise and thus the basal.
 But at around 3:10 AM, BGs are getting near the low limit, there is no raise but there is a basal injection anyway.

AAPS 2.8.2 with OL fw2.1 and Omnipod.

![Screenshot_20210205-042643_AndroidAPS](https://user-images.githubusercontent.com/76626474/107103716-e67a1480-681e-11eb-8fcc-e5f721f61099.jpg)

![20210205_130623](https://user-images.githubusercontent.com/76626474/107103734-f42f9a00-681e-11eb-83a5-095a26c147a7.jpg)

**Comment by MilosKozak** [comment]
this is correct. like you may see previous was set to 30 min. after  30 min basal was returned to common rate and immedietely on next APS run again set to zero. the amount of insulin for these few minutes between  is "nothing"
