### ISSUE TITLE
SMB bolus applied despite setting Glycaemic value to stop insulin

### ISSUE THREAD

**Issue by Korostensky** [nightscout/AndroidAPS#2842]
The pump TouchCare Nano A8
DYNSENZ
--------------
Build: dev-l (personal branch) 
Pump: Medtrum TouchCare Nano A8
Time: SMB 12:58
Log: 
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/12726853/AndroidAPS.log)
The IOB was positive and a SMB was applied despite a lower than set glycaemic value.

![Screenshot_20230926_133130_AAPS](https://github.com/nightscout/AndroidAPS/assets/54218454/a8427657-57b0-4e26-a6c4-abbc189d2df3)

![Screenshot_20230926_130727_AAPS](https://github.com/nightscout/AndroidAPS/assets/54218454/4b70a7ee-9cae-44a4-b0ee-c786bfa98477)

![Screenshot_20230926_130921_AAPS](https://github.com/nightscout/AndroidAPS/assets/54218454/2ee3c682-73af-45ee-8581-61c0f60f71e3)

**Comment by MilosKozak** [comment]
DynISF was not active because of missing TDD (defaulted to SMB)
