### ISSUE TITLE
 3.2.0-dev-k Application expired

### ISSUE THREAD

**Issue by elgrupo123** [nightscout/AndroidAPS#2844]
3.2.0-dev-k Application expired

![signal-2023-09-27-155117_002](https://github.com/nightscout/AndroidAPS/assets/92778761/223c157f-73b8-4b08-8b0a-88ed4780f304)

**Comment by vanelsberg** [comment]
FYI: Confirming: Current "dev-k" commit expires on startup, dropping into "Open Loop"

Expected version: "dev-m"

**Comment by elgrupo123** [comment]
Dev-K has just been uploaded. this confuses me a little...

**Comment by vanelsberg** [comment]
> Dev-K has just been uploaded. this confuses me a little...

Version tag "dev-k" was already used and has expiry date 2023-09-05.
Needs fixing.

**Comment by robertrub** [comment]
The version should be dev-m and not dev-l ;)

**Comment by elgrupo123** [comment]
![Screenshot_20230927-183536](https://github.com/nightscout/AndroidAPS/assets/92778761/84b025e9-089c-4472-a96b-17344395ff46)

**Comment by elgrupo123** [comment]
This isn't about typos. I already wrote above. The current, uploaded Dev version has already expired.

**Comment by robertrub** [comment]
The last commit sets the Dev version. Then, the when it starts, the apk checks this Dev version with a file on the Net to see if it has expired.
If you don't name correctly the Dev version, then your AAPS will think that it has expired.
Change the commit and replace K with M and you'll have a working AAPS version dev-M

**Comment by jbr7rr** [comment]
@elgrupo123 Please don't close, this has not been solved in dev branch yet..

**Comment by elgrupo123** [comment]
---

**Comment by MilosKozak** [comment]
mistake. updated in dev

**Comment by vanelsberg** [comment]
Confirming, problem fixed.
Tnx Milos!
