### ISSUE TITLE
[DEV] AAPSClient occasionally misses to download SGV

### ISSUE THREAD

**Issue by szantos** [nightscout/AndroidAPS#2846]
AAPSClient 3.2.0-dev-l d379b769d3-2023.09.14 with NSClientV3 + websockets
NS dev v15: d602de1
[Log Export.txt](https://github.com/nightscout/AndroidAPS/files/12746351/Log.Export.txt)

AAPSClient misses to download or backfill some SGV - which is present in NS.

![Screenshot_20230924-075612_AAPSClient](https://github.com/nightscout/AndroidAPS/assets/64865503/23767361-5679-4a13-bffd-7e07bcf3c46c)

**Comment by olorinmaia** [comment]
I recommend updating to latest dev and use v1 api until this issue is sorted
https://github.com/nightscout/AndroidAPS/issues/2792

**Comment by szantos** [comment]
Thank you! Does switching between v1 and v3 make any issues?

**Comment by olorinmaia** [comment]
Its no problem to switch between! But update dev first since there was a few bugs regarding that + more that has been fixed recently. When NS15 v3 api has been updated with fix Im going to test more as i believe there still are issues with new api and sync between AAPS, AAPSClient and NS. 😀

**Comment by olorinmaia** [comment]
@szantos v3 API should be OK now, update to latest NS dev and see if you can reproduce this with v3

**Comment by szantos** [comment]
Thank you! I'll test and tell if there are any issues.

**Comment by MilosKozak** [comment]
create new issue if needed

**Comment by olorinmaia** [comment]
Make sure NS is updated to latest dev, if that is true and this still happens create a new issue with logs!

**Comment by ohjay73** [comment]
> Make sure NS is updated to latest dev, if that is true and this still happens create a new issue with logs!


I updated using todays commits and still same issue. New issue created #2890
