### ISSUE TITLE
[DEV] AAPS missed to upload a bolus to NS

### ISSUE THREAD

**Issue by szantos** [nightscout/AndroidAPS#2847]
AAPS 3.2.0-dev-l d379b769d3-2023.09.14 with NSClientV3 + websockets
NS dev v15: d602de1
[AndroidAPS_LOG_1695846554288.log.zip](https://github.com/nightscout/AndroidAPS/files/12746474/AndroidAPS_LOG_1695846554288.log.zip)
Time: 2023.09.27 around 15:45

There was a "do not bolus record only" bolus of 1,0U (given with a pen) at around 15:45 - as seen in AAPS. Everything got uploaded to NS, except the bolus.

![Screenshot_20230927_180655_info nightscout androidaps](https://github.com/nightscout/AndroidAPS/assets/64865503/6f299d7e-acb3-49a3-a39d-b7a966ca86ed) ![NS Screenshot 2023-09-28 084615](https://github.com/nightscout/AndroidAPS/assets/64865503/fc6e29b9-a9f2-400c-9a6d-5ec3b863892c)

**Comment by jbr7rr** [comment]
Update, this has been resolved around a week ago
