### ISSUE TITLE
[DEV-M] Widget is broken 

### ISSUE THREAD

**Issue by swissalpine** [nightscout/AndroidAPS#2848]
The widget is frozen after the update, re-adding (after deleting) is not possible.

**Comment by robertrub** [comment]
I confirm. Widget is available but will not install. Android 13 S21FE
![Screenshot_20230928_122813_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/c75c6d24-d8b8-4840-8f39-06901d1cf743)

**Comment by MilosKozak** [comment]
it works in emulator. what android version?

**Comment by robertrub** [comment]
![Screenshot_20230929_051258_Settings.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/e779d3b9-28ad-489e-ae7e-976c4ebc2ab8)

**Comment by robertrub** [comment]
The video, if it helps...

https://github.com/nightscout/AndroidAPS/assets/76626474/51e511bc-1c33-401d-af9d-7eb9c444f925

**Comment by swissalpine** [comment]
Samsung Z Flip 4, Android 13, One UI 5.1.1 (September 2023)
Same here: Fine with dev-l, buggy with dev-m
Logcat after installing (widget freezes):
```
08:39:24.024  I  addProviderLocked Provider is added Provider{ProviderId{user:0, app:10423, cmp:ComponentInfo{info.nightscout.androidaps/app.aaps.ui.widget.Widget}}} at 107
08:39:51.765  D  Provider info from ComponentInfo{info.nightscout.androidaps/app.aaps.ui.widget.Widget} won't be persisted.
```
Logcat after re-adding (only one line):
```
08:45:23.693  D  bindAppWidgetIdIfAllowed() appWidgetIds = 121, provider = ComponentInfo{info.nightscout.androidaps/app.aaps.ui.widget.Widget}
```
More info needed?
Thanks!

**Comment by CaroGo** [comment]
same here with Samsung Fold 4 , Android 13

**Comment by MilosKozak** [comment]
hmmm it does work in emulator :(

**Comment by robertrub** [comment]
According to a book I read recently, we might all be the products of a huge emulator... ;)

The widget is working with this version.

![Screenshot_20230926_181601_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/de7f843a-e88c-4149-aa52-7c13a95a78e8)

Something changed between that and last Dev.

**Comment by Josch24** [comment]
I installed the last Dev-M. On my Pixel 4a the Widget is working. I am also on Android 13.

**Comment by robertrub** [comment]
Maybe it is Samsung's ONE UI 5.x related... Both of us with problems are on Samsung phones.

**Comment by MilosKozak** [comment]
you may try to uninstall aaps

**Comment by robertrub** [comment]
Uninstalling will loose too much data.

Tested again with dev-l and the widget installed

![Screenshot_20230930_104240_One UI Home.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/560504f1-7d86-43e2-87c3-fa34db910048)

**Comment by HuismanErik** [comment]
I did a reinstall with this change https://github.com/nightscout/AndroidAPS/pull/2850 and it fixed the Widget

**Comment by ninelore** [comment]
For the record: This doesnt happen on my Pixel 6 Pro on commit 81548b7

**Comment by swissalpine** [comment]
Fix for the issue: https://github.com/nightscout/AndroidAPS/pull/2850
Thanks a lot!
@HuismanErik

**Comment by robertrub** [comment]
I confirm too. Including Eric's PR 2850 on Dev solved the widget problem. When updating from dev-L to dev-M + PR2850, the widget disappears but can be put back in place.

**Comment by vanelsberg** [comment]
FYI: Running dev-m (commit 81548b7d).
On Samsung S22 Ultra (Android 13, One UI 5.1): No problems with Widget.
