### ISSUE TITLE
[2.8.2] DanaR connection timeout, reconnect failed

### ISSUE THREAD

**Issue by Rol71** [nightscout/AndroidAPS#285]
Setup:

AAPS 2.8.2
DanaR
Samsung A3 2017 (Android 8.0)
Dexcom G6
xDrip+

Time: 02:18 a.m.

Issue:

AAPS reports connection timeout. Reconnect is only possible after restart.
This problem exists since AAPS 2.7. It did not occur in any version before that. 

![grafik](https://user-images.githubusercontent.com/28503031/107108680-0ec33c80-683a-11eb-9035-dc76a0577d09.png)
![grafik](https://user-images.githubusercontent.com/28503031/107108625-a2483d80-6839-11eb-93b3-792d1468ebff.png)

Log file: 
[AndroidAPS_LOG_1612574672728.log.zip](https://github.com/nightscout/AndroidAPS/files/5936223/AndroidAPS_LOG_1612574672728.log.zip)

**Comment by MilosKozak** [comment]
the problem seems to be related to phone and some app crashes on background
there is nothing i can do here.
you can try to do factory reset or try another phone
