### ISSUE TITLE
BUG / DEV-M / DASH History button restarts AAPS

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2853]
When I look at the DASH history, AAPS restarts (I see the AAPS icon and then the main page with the progress bar etc). First found by @ohjay

![Screenshot_20231001_100512_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/a6c748a6-afa6-4cda-9a78-36b44363cc61)

![AndroidAPS_LOG_1696214180512.log.zip](https://github.com/nightscout/AndroidAPS/files/12779212/AndroidAPS_LOG_1696214180512.log.zip)

**Comment by TheNeskik** [comment]
Same issue here
[AndroidAPS_LOG_1696248292700.log.zip](https://github.com/nightscout/AndroidAPS/files/12782465/AndroidAPS_LOG_1696248292700.log.zip)

**Comment by TheNeskik** [comment]
Same here : log below
[AndroidAPS_LOG_1696250330973.log.zip](https://github.com/nightscout/AndroidAPS/files/12782791/AndroidAPS_LOG_1696250330973.log.zip)

**Comment by robertrub** [comment]
To all that have commented and added logs.

Please try to use pod history again. It started working for me but I did nothing new... I didn't start a new pod. I just rebooted the phone but no idea if this is related. Now, pod history works.

The bug got solved all by itself... Not normal.

**Comment by parapenT1sta** [comment]
> To all that have commented and added logs.
> 
> Please try to use pod history again. It started working for me but I did nothing new... I didn't start a new pod. I just rebooted the phone but no idea if this is related. Now, pod history works.
> 
> The bug got solved all by itself... Not normal.

A fix is waiting to be merged: https://github.com/nightscout/AndroidAPS/pull/2858

**Comment by TheNeskik** [comment]
> To all that have commented and added logs.
> 
> Please try to use pod history again. It started working for me but I did nothing new... I didn't start a new pod. I just rebooted the phone but no idea if this is related. Now, pod history works.
> 
> The bug got solved all by itself... Not normal.

Not on my phone :)

Tried the fix and everything seems to be back in place.

**Comment by ohjay73** [comment]
powercycled and still have the same crash experience.

**Comment by jbr7rr** [comment]
> A fix is waiting to be merged: #2858
Fix needs testing. Have not tested it on a active pod. So if any of you can test the PR and see if everything is there in the pod history that would be really helpful

**Comment by robertrub** [comment]
Ok, tested the PR of @jbr7rr and everything is working ok for me. Pod history is accessible (but that had started working for me before the fix) and recent events are recorded to history.

For me, the OR is a _go for merge_
