### ISSUE TITLE
Upload to tidepool crashes new upgrade AAPS 3.2-rc1

### ISSUE THREAD

**Issue by PedanticAvenger** [nightscout/AndroidAPS#2860]
I've been waiting for tidepool support for a while. ;)

Just upgraded to rc1 and got everything else setup.  Plugin itemizes what needs to be uploaded, assembles it then right after upload begins the app crashes.  This has happened 4 times consecutively before I disabled tidepool.

Log attached, at least a couple crashes should be in there. 
Build: dd6081efd2-2023.10.03
Flavor: fullrelease
Nightscout version: 15.0.0

[AndroidAPS._2023-10-03_15-54-04_.34.zip](https://github.com/nightscout/AndroidAPS/files/12797268/AndroidAPS._2023-10-03_15-54-04_.34.zip)

**Comment by MilosKozak** [comment]
log doesn't contain any crash
replicate the issue, update with new logs and time of occurence
make sure the time is in logs

**Comment by PedanticAvenger** [comment]
Will do.
I have previous logs as well, is a crash obvious in them if I go looking to verify?

**Comment by PedanticAvenger** [comment]
Active and previous included as well as screen shot of the tidepool tab taken about a second and a half before crashing.

[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/12807525/AndroidAPS.log)
[AndroidAPS._2023-10-03_22-20-35_.43.zip](https://github.com/nightscout/AndroidAPS/files/12807526/AndroidAPS._2023-10-03_22-20-35_.43.zip)
![Screenshot_2023-10-04-13-38-21-25_3eaa31bb2c2a38a1c605d9dc918cf694](https://github.com/nightscout/AndroidAPS/assets/15637097/cb29b9f7-0341-432f-8234-d089dc6434e9)

**Comment by MilosKozak** [comment]
i cannot replicate the issue

**Comment by PedanticAvenger** [comment]
AFter full release it appears to be behaving correctly so will close this.
