### ISSUE TITLE
SMS Authenticator setup screen crashing

### ISSUE THREAD

**Issue by rvilchez1** [nightscout/AndroidAPS#2866]
Trying to Set up the SMS authentication in AndroidAPS 3.2.0 Dev-m build 81548b7d65-2023.09.30
When clicking Authenticator Setup the application crashes.

Attaching the Androidaps logs

(https://github.com/nightscout/AndroidAPS/files/12807528/AndroidAPS_LOG_1696444711596.log.zip)

**Comment by MilosKozak** [comment]
already fixed in dev. update
