### ISSUE TITLE
Cannot start Objective 11 - buttons are missing

### ISSUE THREAD

**Issue by ledrexter** [nightscout/AndroidAPS#2873]
I'm using dev compiled 6 days ago. My phone is Xiaomi 11T Pro. 
The buttons to start and verify the Objective are missing. Should I add log files as well?

![Screenshot_2023-10-05-19-55-14-235_info nightscout androidaps](https://github.com/nightscout/AndroidAPS/assets/51510015/a7de188b-1db0-4b09-a4e0-a975d83b9737)

![Screenshot_2023-10-05-19-55-21-171_info nightscout androidaps](https://github.com/nightscout/AndroidAPS/assets/51510015/7af7e36c-1e11-4464-9684-0bf05133056f)

![IMG_20231005_200150](https://github.com/nightscout/AndroidAPS/assets/51510015/5920154c-f31b-4ee3-b1a6-7845032baf15)

**Comment by jbr7rr** [comment]
Check if all.other objectives are passed. There are probably some open. Objective 3 got some new questions

**Comment by ledrexter** [comment]
Thanks a lot!
All in Objective 3 were finished but there was a button Verify that I have missed when checking.
Closing this one!
