### ISSUE TITLE
Kotlin Android Extensions is deprecated

### ISSUE THREAD

**Issue by JustinSouthcombe** [nightscout/AndroidAPS#288]
Getting this error on MDT build "Kotlin Android Extensions is deprecated" and being prompted to modify to Jetpack. I am not used to changing APS code directly - do I need to do anything? Thanks.

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/EN/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
it's a warning only. ignore
