### ISSUE TITLE
Dev M and RC2 AAPS Client missing BG's and regular updates

### ISSUE THREAD

**Issue by ohjay73** [nightscout/AndroidAPS#2890]
Tested with Dev M and RC2 and both aaps clients will miss BG updates. All power savings are turned off.. nothing is killing the app. 
Can get updates if i pause websockets for a moment then restart and the data will refresh. 
Regular updates are occurring in NSClient though

[AndroidAPS_LOG_1696874984171.log.zip](https://github.com/nightscout/AndroidAPS/files/12849197/AndroidAPS_LOG_1696874984171.log.zip)
[AndroidAPS_LOG_1696874984171.log.zip](https://github.com/nightscout/AndroidAPS/files/12849201/AndroidAPS_LOG_1696874984171.log.zip)

**Comment by ohjay73** [comment]
![Screenshot_20231009_120909_AAPSClient](https://github.com/nightscout/AndroidAPS/assets/51689492/11ffa2e1-dc85-4bfb-98cb-6c9f3941df4b)
![Screenshot_20231009_120902_AAPSClient](https://github.com/nightscout/AndroidAPS/assets/51689492/87f78306-a442-44c2-a384-93e127b799fe)
![Screenshot_20231009_120930_AAPSClient](https://github.com/nightscout/AndroidAPS/assets/51689492/02ca919b-1995-45e1-8380-f8efbb97e0ed)
![Screenshot_20231009_120918_AAPSClient](https://github.com/nightscout/AndroidAPS/assets/51689492/8303737c-63c1-4a4d-b435-6366c63e6b60)

**Comment by szantos** [comment]
Similar issue here, but I have a slightly older build:
SGV are present in NS, AAPSClient misses to download and/or backfill some of them

AAPSClient 3.2.0-dev-m 81548b7d65-2023.09.29 with NSClientV3 + websockets
NS dev v15: 5f8c734
[Log Export.txt](https://github.com/nightscout/AndroidAPS/files/12853392/Log.Export.txt)

![Screenshot_20231010-061912_Chrome~2](https://github.com/nightscout/AndroidAPS/assets/64865503/bdd99698-b940-4e60-b431-d7edacdcf646)

![Screenshot_20231010-061918_AAPSClient~2](https://github.com/nightscout/AndroidAPS/assets/64865503/b4606db5-2dea-4570-aad0-fe736579e49c)

**Comment by MilosKozak** [comment]
improved in https://github.com/nightscout/AndroidAPS/commit/b870de1e078696a842b934287edf09c7754b313d

**Comment by ohjay73** [comment]
@MilosKozak improvements yes.. I can see everything except for BG update now

**Comment by ohjay73** [comment]
![Screenshot_20231011_193626_AAPSClient](https://github.com/nightscout/AndroidAPS/assets/51689492/7fe56518-ce09-4197-b17b-bb7e2cf822c5)

**Comment by olorinmaia** [comment]
Is NS updated to latest dev? AAPSClient and AAPS? Im feeding AAPS with bg from xdrip and i dont have issues after update yet in AAPS, AAPSClient or NS with sync.

**Comment by ohjay73** [comment]
Yes both with latest dev.. I'm using BYOD for BG.. aaps syncs perfectly.. aapsclient will sync then lose bg but gets basal and carbs and smb etc. It'll also send from aapsclient for carbs temp targets etc. Just the BG won't show up unless you pause and restart the connection

**Comment by ohjay73** [comment]
![Screenshot_20231012_074924_AAPSClient](https://github.com/nightscout/AndroidAPS/assets/51689492/93aa9155-30fb-46bb-8058-51d42d0e64ad)

![Screenshot_20231012-074741_AAPS](https://github.com/nightscout/AndroidAPS/assets/51689492/7eb895bb-7ff4-46c5-b689-7676032be302)

**Comment by olorinmaia** [comment]
Strange. I know what Milos would say;  Create new issue and attach logs :) Just make sure that Nightscout is latest dev also and make sure AAPSclient and AAPS use same API version (stating the obvious) ;)

**Comment by ohjay73** [comment]
yup.. added https://github.com/nightscout/AndroidAPS/issues/2905

**Comment by ohjay73** [comment]
@olorinmaia how do you send bg to ns? Is it direct from aaps or do you use bridge or the new connect option in NS? I was using bridge during the issue above but am seeing improvements when I switch to aaps direct to ns. Wondering if it's placebo

**Comment by olorinmaia** [comment]
I'm using a testrig so setup is like this:
xdrip receive BG from dexcom share.
xdrip local broadcast BG to AAPS.
AAPS upload to NS.

In my live setup with my kid it's like this.
BYODA recieve BG from G6
BYODA local broadcast to AAPS and xdrip
AAPS upload to NS.

I would not recommend using bridge in NS, as it not recommended in live setup either. The way I setup my testrig is as close I can get it to a live setup.

**Comment by ohjay73** [comment]
It's looking more and more that bridge and connect are not reliable based on what your setup and what I'm observing with this latest change.

**Comment by olorinmaia** [comment]
I would mention your BG setup in the issue. As it probably matters. However, it's a question for @MilosKozak to answer if this is an AAPS bug or NS bug. I don't understand why anyone would want to feed AAPS with BG from NS in a live setup.
