### ISSUE TITLE
Dev-M / Delete old data / List have double entries

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2894]
I just cleaned the AAPS database. Once finished, I have the list of the deleted data. Up to that point, all is ok.

The list has some lines doubled. Everything up to _UserEntry_ starts again at the end of the list. Strange part is that the numbers are not the same when shown a second time...

![Screenshot_20231010_142051_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/d55f326c-1700-40ed-a46f-79db2f686030)

![Screenshot_20231009_181539_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/e040053a-1683-49d1-b6aa-16d4fd612639)

**Comment by MilosKozak** [comment]
this is correct. I added more info in https://github.com/nightscout/AndroidAPS/commit/7df80eebe0d7c14c803a8375c39f00c2c49c61f5
