### ISSUE TITLE
[Wear] Sync Calc settings from quick wizard

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#2895]
See https://github.com/nightscout/AndroidAPS/issues/2339

Can same fix be implemented for quick wizard when used in wear?

![Screenshot_20231010_180807_nsclient](https://github.com/nightscout/AndroidAPS/assets/114103483/57239ec4-36ca-4298-b5b9-e8fd2ae11caf)
![Screenshot_20231010_180756_sysui](https://github.com/nightscout/AndroidAPS/assets/114103483/0ccde347-1685-4d11-893f-29930549f8ef)
![Screenshot_20231010_180704_AAPSClient](https://github.com/nightscout/AndroidAPS/assets/114103483/be60a491-08f9-4966-ad2d-8f1a7374baa8)

**Comment by MilosKozak** [comment]
test with https://github.com/nightscout/AndroidAPS/commit/ae3b66d5c0cc8c454669134e358f95ef1665cbcc

**Comment by olorinmaia** [comment]
testet OK in https://github.com/nightscout/AndroidAPS/commit/ae3b66d5c0cc8c454669134e358f95ef1665cbcc
