### ISSUE TITLE
Heart rate graph inversed

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2918]
If there is no HR input, the graph is upside down ( 0 is on top)

![Screenshot_20231014_190656_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/0530a39a-82d3-43b0-8da3-2d8262b0fe28)

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/20e4590eea78d76fb628f88bcda2693a04b53b4d
