### ISSUE TITLE
Transparency when entering time in carbs

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2919]
The Time overlay is not opaque when filling in the time.

![Screenshot_20231014_185640_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/48a22aab-1979-44d2-84dd-8aca289ed8ee)

**Comment by MilosKozak** [comment]
@osodebailar could you find the reason?

**Comment by kenzo44** [comment]
Note: all time picker dialogs are transparent.

**Comment by parapenT1sta** [comment]
> @osodebailar could you find the reason?

Example: Carbs > Click on the hour of "Event Time"

**Comment by osodebailar** [comment]
@parapenT1sta @MilosKozak  the reason is a problem in the theme configuration of the night style. i will solve it in the next days.
