### ISSUE TITLE
feature request 2.8.2: amend alarm of prebolus to carb menue

### ISSUE THREAD

**Issue by cheers2** [nightscout/AndroidAPS#292]
Carb Alarm for prebolus is only available in the calculator.
Please amend it also to the carb input screen.

Many thanks

**Comment by AdrianLxM** [comment]
@cheers2 this PR includes it: https://github.com/nightscout/AndroidAPS/pull/333

**Comment by cheers2** [comment]
@AdrianLxM thx for informing and fixing
