### ISSUE TITLE
Minor : time setting window / edited box not the correct color

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2936]
The time setting's window's transparency with dark theme bug have been solved but there is a minor colour "error".

The box I'm modifying (hours below) is the same colour as the background when the box I'm NOT modifying is more "visible".

![Screenshot_20231017_183448_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/9bcb9bff-eb9d-42cc-8bc2-ef889190055f)

It would be better if the box that is being edited has a different colour than the background (black when the background and the other box are dark gray)

**Comment by osodebailar** [comment]
The color here is the correct material theme background color.
If you see the light theme, and here there are no special customization done, the background color of the selected edit field is the ticker background. 
So i see here nothing further to do.

**Comment by robertrub** [comment]
Ok, if this appearance is the standard, then let's leave it as it is. To me, it seems illogical to _not_ outline where the user is editing but no need to loose sleep over it.
