### ISSUE TITLE
Minor : New UI buttons : takes time to change color

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2937]
Since the new round cornered buttons, when setting a new % for the profile, the button takes time to change it's colour.

I set a profile change for 10 minutes, it changed color when 8 minutes were left.

![Screenshot_20231017_230120_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/ccc1d320-7992-492e-9662-91ca16b8e1fa)

![Screenshot_20231017_230140_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/35a5e9d9-2d32-4a34-bf30-3ff7deb4510c)

White icon on yellow background is not very visible either

**Comment by olorinmaia** [comment]
I think it's always been like this tho :) it's abit sporadic, some times it gets lit yellow asap, and some times it takes a few seconds.
