### ISSUE TITLE
Suggestion : use NTP server for time check in objectives 

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2940]
Actually, AAPS uses date and time of the 4G connection to verify the "real" time while the objectives are done.

Some phones don't have 4G accounts. Why not use a NTP server as a reliable date/time source ? It can be accessed via WiFi and internet.

**Comment by MilosKozak** [comment]
aaps uses NTP server

**Comment by MilosKozak** [comment]
time.google.com

**Comment by robertrub** [comment]
Tnx, good to know. Does that mean that only a WiFi connection (no 4G data) will be sufficient? 

Some users had problems with the objectives if 4G was turned _off_.

**Comment by MilosKozak** [comment]
it's only about good connectivity to the server. wifi of 3G/4G/5G doesn't matter
