### ISSUE TITLE
AndroidAPS 3.2 dev hangs after pressing NSClientV3 "switch on" button

### ISSUE THREAD

**Issue by basgeurds** [nightscout/AndroidAPS#2947]
Version 3.2.0-dev-m
Build 90e23b4f78-2023. 10.18
Wanted to activate sending data to Nightscout. The option in the Configurator for NSClient can be switched on like normal, but the new NSClientV3 option makes AndroidAPS hang. 
Button turns gray, showing it is selected, but after that nothing happens anymore and the app hangs.
See screenshot.

[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/13044045/AndroidAPS.log)
![Screenshot_20231019_163209_info nightscout androidaps](https://github.com/nightscout/AndroidAPS/assets/76550379/a159f07b-0a65-4d5d-bfdd-9a1a69df5b04)

**Comment by olorinmaia** [comment]
I experienced the same some other day. Not sure how exactly but i made it work again. I think installing rc2 and update to dev again may have helped. Not that it makes any sense 😅 

https://github.com/nightscout/AndroidAPS/issues/2929

**Comment by MilosKozak** [comment]
just restart the app helps
it's android issue

**Comment by basgeurds** [comment]
Tried restarting the app, but didn't help.
Tried stopping the app and deleting cache data did not help.
Restarting phone didn't help either.

**Comment by osodebailar** [comment]
Same problem here on a google pixel 5 with Android 14.

**Comment by MilosKozak** [comment]
is after restart NSCv3 activated?

**Comment by vanelsberg** [comment]
FYI: Running current dev-m, commit b18f3c9e
Can not repro this problem.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/2b89a78102afa47cf7d4a3b0a771facd74293ec1

**Comment by basgeurds** [comment]
Thank you Milos,
With this update the problem is solved.
Thank you very much for all your work on AndroidAPS!
You help is all a lot, to have a beter life, with better control and less risk of diabetic complications.

Best regards, 
Bas Geurds
