### ISSUE TITLE
MINOR: New UI buttons change size

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#2948]
Not sure if this is a bug or a feature. Since the new rounded UI buttons, when the profile name + percentage is long, the profile button gets bigger, the target button gets smaller.

![Screenshot_20231019_052641_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/0626c399-0253-47d3-8de2-f4b5fb1b06df)

I don't think that the buttons changed sizes before. Unless a very long profile name is used, the new presentation is just a bit strange to look at but nothing more than that.

**Comment by robertrub** [comment]
In some cases, the target button gets "thicker" which really looks weird

![Screenshot_20231019_171932_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/2b33d842-0709-4c1d-8abb-b15c4d135d03)

**Comment by kenzo44** [comment]
Will fix this shortly. I did not test with a timed profile change.
