### ISSUE TITLE
[3.0.2-rc2] Extended boluses mising on AAPSClient side

### ISSUE THREAD

**Issue by vmichalec** [nightscout/AndroidAPS#2950]
[3.0.2-rc2] AAPS, AAPSClient, on both sides NSClientV3 on websockets
[dev, 15.0.0] Nightscout

- I'm using dana-r pump with extended boluses enabled
- In main graph there is a visual difference in rendered basal between AASP and AAPSClient
- On NSClient side in treatments - there is missing extended boluses icon / tab

![Screenshot_20231019_194129_AAPS](https://github.com/nightscout/AndroidAPS/assets/24793786/892b96cb-b5d9-4ed7-b8c5-d46cbe0b20c7)
![Screenshot_20231019-194148_AAPSClient](https://github.com/nightscout/AndroidAPS/assets/24793786/54f74e4d-98e6-47b4-9773-56a2d4988266)

![Screenshot_20231019_195351_AAPS](https://github.com/nightscout/AndroidAPS/assets/24793786/0cec4e4c-f98f-4d58-ac5e-695e29573c4c)
![Screenshot_20231019-194229_AAPSClient](https://github.com/nightscout/AndroidAPS/assets/24793786/447d249d-3665-47d3-b8dc-51352c8b911e)

And screenshot from nightscout - are they also missing there?
![nightscout](https://github.com/nightscout/AndroidAPS/assets/24793786/c5d9436c-432b-44f7-a757-286602bfe837)

**Comment by MilosKozak** [comment]
this is already fixed in dev
test it and if not mention me here

**Comment by vmichalec** [comment]
@MilosKozak
I took 3ffc75bd from this morning, updated Nightscout do 15.0.1 but looks like same. No `NS` sign on such entries  at all. If you need logs, where can I send them?

![Screenshot_20231020_210524_AAPS](https://github.com/nightscout/AndroidAPS/assets/24793786/34f93c39-dc96-483a-bbb7-d605cfb535f1)


![Screenshot_20231020_192721_AAPS](https://github.com/nightscout/AndroidAPS/assets/24793786/805e5b9c-0bb9-4168-9d6e-fa6f3ae4bc17) ![Screenshot_20231020_192711_AAPS](https://github.com/nightscout/AndroidAPS/assets/24793786/f6b0bd72-7021-4a90-ba4e-9354f8591919)

**Comment by MilosKozak** [comment]
yes

**Comment by vmichalec** [comment]
I have send logs to logs @ aaps.app

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/17c3ef6274f77dac36002ec335a3c8bd201911fc
