### ISSUE TITLE
[RC2] NSClientV3 FullSync only gets 2 days of TDD.

### ISSUE THREAD

**Issue by justmara** [nightscout/AndroidAPS#2966]
Fresh install of AAPS 3.2, NSClientV3, all checkboxes to 'download data from NS', made Full sync. Loaded BG data, treatments, etc, but statistics shows only 2 days of TDD. So DynISF does not work correctly right from start and needs another 5 days to fill the required tdd7 data. While it exists in NS and simply must be downloaded on full sync.
History browser shows BG values, TT changes, notes and sensor change/cannula replacement events for these days, but not bolus/carbs treatments.

![telegram-cloud-photo-size-2-5307618162767942449-y](https://github.com/nightscout/AndroidAPS/assets/4157587/88d29bc5-7bb3-4109-befe-9b290dd39df4)

**Comment by MilosKozak** [comment]
I cannot replicate this issue. I did v3 setup - clear database - restart app and after v3 finished sync, TDD data was available

**Comment by justmara** [comment]
hmm, where did all the screenshots go?
![Screenshot_20231023_160545_AAPSClient](https://github.com/nightscout/AndroidAPS/assets/4157587/c18ed3e1-c81d-41b8-9f11-66d12171f437)
![Screenshot_20231023_160514_AAPSClient](https://github.com/nightscout/AndroidAPS/assets/4157587/94118eae-1364-448e-b8a0-7ae650523023)
![Screenshot_20231023_160430_AAPSClient](https://github.com/nightscout/AndroidAPS/assets/4157587/b874ba66-fd85-442f-9b10-6631c22882ad)
![Screenshot_20231023_160425_AAPSClient](https://github.com/nightscout/AndroidAPS/assets/4157587/3b77e1be-3215-4933-a70a-ee36990f69d0)
![Screenshot_20231023_160417_AAPSClient](https://github.com/nightscout/AndroidAPS/assets/4157587/a144db21-e429-40ab-9c39-a7976a95a224)

**Comment by justmara** [comment]
But this time it has loaded 3 days of boluses. And only last portion of boluses from 19.10
<img width="1208" alt="image" src="https://github.com/nightscout/AndroidAPS/assets/4157587/e9b0bb2a-a391-4cf0-9497-0182c765664e">

**Comment by justmara** [comment]
> what happen when you reset statistics?

exactly same values recalculated

**Comment by justmara** [comment]
I see only this fail in log, dunno if it is related
```
16:02:49.404 [RxCachedThreadScheduler-245] D/NSCLIENT: [NSClientV3Plugin$onStart$7.accept():229]: ◄ INSERT TherapyEvent 145
16:02:49.559 [pool-12-thread-1] D/WORKER: [CalculationWorkflowImpl.stopCalculation():111]: Stopping calculation thread: onEventNewHistoryData
16:02:49.576 [DefaultDispatcher-worker-3] D/WORKER: [LoggingWorker$doWork$2.invokeSuspend():27]: Worker result FAILURE for class app.aaps.workflow.iob.IobCobOref1Worker
16:02:49.580 [pool-12-thread-1] D/WORKER: [CalculationWorkflowImpl.stopCalculation():116]: Calculation thread stopped: onEventNewHistoryData
```

**Comment by justmara** [comment]
these are last events from that evening. only last two `0.5` boluses were synced.
<img width="1195" alt="image" src="https://github.com/nightscout/AndroidAPS/assets/4157587/3493816e-a3d3-41ab-a663-2633727c2baf">

**Comment by justmara** [comment]
just made absolutely clean build from RC2 branch in emulator, ran full sync. two days of statistics again.
subsequent syncs does not add anything to this.
still dont understand how did it load 3 days on my phone, but refuses to do the same in emulator (from same NS).
<img width="509" alt="image" src="https://github.com/nightscout/AndroidAPS/assets/4157587/a8ad946b-2737-4f86-8880-5981e6038d36">

**Comment by hartlijn** [comment]
I have the same. Insulin data seems to get stuck during sync. sometimes (after reset database) it gets a little more data than the other time, but more than 2 days completely doesnt work.

**Comment by justmara** [comment]
@MilosKozak this issue can be related https://github.com/nightscout/cgm-remote-monitor/issues/8149
I see many HTTP500 errors during Full sync because NSClientv3 calls treatments/history without `limit` argument

**Comment by justmara** [comment]
Seems that I've found the reason.
This request returns ONLY TempBasals and TempTargets
api/v3/treatments?sort=date&**created_at**$gt=2023-10-21T04:28:26.411Z&limit=500

This requests returns Boluses
api/v3/treatments?sort=date&**date**$gt=2023-10-21T04:28:26.411Z&limit=500

Seems to be related to how treatments are sent to NS.
