### ISSUE TITLE
Disabling basal on no BG readings

### ISSUE THREAD

**Issue by zibra** [nightscout/AndroidAPS#2969]
Is there any setting to tell loop to disable basal after X minutes of missing BG readings? 

I had recently such case where BG was high because of night pressure, then sensor died for few minutes but basal was still kept high. This led to hypo later.

![Screenshot_20231023_043746_Chrome](https://github.com/nightscout/AndroidAPS/assets/4493100/80e3c8fe-c015-47d1-b783-2a99a42f7e3f)

**Comment by MilosKozak** [comment]
expecting you are not using SMB?

**Comment by zibra** [comment]
Yes, I am using SMB

**Comment by zibra** [comment]
I know what was wrong. This failure was because of connection issue (device out of range), so AAPS was not able to disable basal because Omnipod was also not in range. I see no issue here. Probably it will be disabled otherwise if it will be just sensor error, right?

**Comment by MilosKozak** [comment]
SMB create TBR as long as it expects to be correct. so even when there are not new BGs after issuing TBR, it should result in "good" state
