### ISSUE TITLE
[Master] Different actions doesn't sync through and receive error sporadic (v3+WS)

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#2974]
AAPS / AAPSClient 3.2.0.1
Build: aeed6e2083-2023.10.24
Nightscout version: Master: 15.0.1
GIT-Commit: f46f869c63b3e09f9895c4b99bf596942f5a013c

Bolus from AAPS calc / QW or AAPS wear calc / QW. This instance at 00:47 from wear bolus calc. Sync to NS OK. but not to AAPSClient. Error message in NSCV3-tab I have not seen before. Now time is 01:04 and it still not synced to AAPSClient. Thus wrong carb + IOB in AAPSClient.

Edit: Seem to be any action. tried to delete treatments in AAPS. Then same error message occurred in AASPClient with no sync of deletion.

Happend a few times although bit sporadic, attaching logs and screenshots from both AAPS and AAPSClient.

**Logs:**
**AAPSClient:** 
[AndroidAPS_LOG_1698101580952.log.zip](https://github.com/nightscout/AndroidAPS/files/13079793/AndroidAPS_LOG_1698101580952.log.zip)
AAPS: 
[AndroidAPS_LOG_1698101501125.log.zip](https://github.com/nightscout/AndroidAPS/files/13079798/AndroidAPS_LOG_1698101501125.log.zip)

**### Screenshots:**
**AAPS:**
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/33d0dd4a-0eeb-4d6e-addd-a2ab07042763)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/0038fc9b-f129-4752-a06a-7e46518e71b3)

**AAPSClient:**
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/be3693ad-3e4e-4ec2-979f-bcfe787bf43f)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/5ba1adf3-1d25-482f-9db1-460b58dd7337)

**Comment by olorinmaia** [comment]
Tried updating to RC2 or a later dev version I have tested alot with with no errors earlier. And same ERROR (status 400 message parameter limit out of tolerance) is appearing there also.

**Comment by olorinmaia** [comment]
I'm using ns.10be.de, and when selecting NS Dev (15.0.2) im not able to reproduce it. But if I redeploy Master (15.0.1) error reappear pretty fast.

**Comment by MilosKozak** [comment]
this was a bug in setting in 10be.de
some parameter must adjust

**Comment by zehnBE** [comment]
@olorinmaia please try it again with master.
I have patched the lib/api3/generic/collection.js and lib/api3/index.js because it doesnt use the API3_MAX_LIMIT from the my.env on our side (it is in), so i rewrite it to env.API3_MAX_LIMIT.

**Comment by olorinmaia** [comment]
@MilosKozak & @zehnBE . Thanks for looking into this. I redployed NS15-master on 10be.de and no errors in nscv3 log. Closing issue.

**Comment by nl-ruud** [comment]
Had a similar issue - in my case it was fixed by the provider by updating to Nightscout >= 15.0.7
