### ISSUE TITLE
Dana RS Stats reload data not working

### ISSUE THREAD

**Issue by hartlijn** [nightscout/AndroidAPS#2988]
in 3.2, the option to reload data from pump DANA RS to get TDD data to display, does not work. Hitting the reload connects with pump but no data is shown in the Stats screen

**Comment by MilosKozak** [comment]
isn't it after fresh install or pump change?

**Comment by hartlijn** [comment]
Fresh install, with same pump. Only had to repair since it was a fresh install

**Comment by MilosKozak** [comment]
then older records from pump are ignored .... wait a few days

**Comment by MilosKozak** [comment]
and?

**Comment by hartlijn** [comment]
Stats are generated for the last two days.
Fixed I'd say
