### ISSUE TITLE
Carb time alarm in BW not working

### ISSUE THREAD

**Issue by Ashley112885** [nightscout/AndroidAPS#299]
This feature does not appear to be working for several users according to Facebook comments. Does not appear to be a permissions issue. I've tried it on both a Jelly 2 (Android 10) and Pixel 3a (Android 11)

**Comment by reijoahola-nightscout** [comment]
Works in Samsung Galaxy S9 / Android 10.

**Comment by happygirlnyc70** [comment]
Does not work for Pixel 4a 5g or Pixel 3XL

**Comment by susannaca** [comment]
It does not work in Mi A3, Android 11

**Comment by AdrianLxM** [comment]
This PR adds a second way to get the alarm - via the system alarm app (countdown/kitchen timer): https://github.com/nightscout/AndroidAPS/pull/333
