### ISSUE TITLE
3.1.0.3 + 3.2.0.1 No Pump (Dana RS) Pairing possible

### ISSUE THREAD

**Issue by sfriedriszik** [nightscout/AndroidAPS#2990]
The problem here is that in the pairing process the pump goes into communication according to the pairing codes,
the arrows appear but then the process stops. 

The whole thing happens reliably 12 times in a row. It is a DANA RS V3 from 03/2023. 
Another older RS in working well.

Log attached.
[AndroidAPS_LOG_1698424097983.log.zip](https://github.com/nightscout/AndroidAPS/files/13191320/AndroidAPS_LOG_1698424097983.log.zip)

**Comment by MilosKozak** [comment]
unpair pump in android
reset pairing on Dana tab by holding BT icon
then try again

**Comment by MilosKozak** [comment]
or .... try to pair the pump to another phone first and then back

**Comment by sfriedriszik** [comment]
@MilosKozak 
tried both approaches. still without success.
Is there another approach?

(log attached)
[AndroidAPS_LOG_1698510482597.log.zip](https://github.com/nightscout/AndroidAPS/files/13196327/AndroidAPS_LOG_1698510482597.log.zip)

**Comment by MilosKozak** [comment]
try original anydana app

**Comment by sfriedriszik** [comment]
@MilosKozak Anydana App works.

**Comment by MilosKozak** [comment]
hmmm sorry,  no more ideas
is any other pump with the same firmware working?

**Comment by MilosKozak** [comment]
does the dialog for entering keys appear on screen?

**Comment by sfriedriszik** [comment]
@MilosKozak 

Yes, the dialog appears and the values can also be entered and confirmed.
then the arrow graphic appears and then the process stops.

**Comment by MilosKozak** [comment]
then  i don't know

**Comment by sfriedriszik** [comment]
@MilosKozak 

Anyway, thank you very much for your efforts

**Comment by mSternEU** [comment]
Issue detected/solved, it was a display resolution problem.

The pairing dialogue doesn't get scrollable when showing more content than the current device resolution allows, so the user isn't able to reach the "cancel / ok" buttons (or can't even guess they are there).
Implementing scrollable diaglogue, fix-binding exit/confirmation-buttons to the visible bottom part or allocate the Enter-Key / bottom right key of the virtual keyboard to a 'send' command could be helpful enhancements.

This is a "small device/screen"-issue, like Jelly/oldphone users.

Workaround was "connecting pump via big-screen phone and import saved settings to Jelly" 

(Screen was taken from a working phone though, just as a reference)
![image](https://github.com/nightscout/AndroidAPS/assets/38337079/ba249ef0-6917-4630-bbaa-97678c0a7a8b)

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/bfacfd925590d458d08fd29ddbf09dcc3fd91996

**Comment by mSternEU** [comment]
Beautiful, much appreciated, thank you :clap:
