### ISSUE TITLE
bg target not aligned on client

### ISSUE THREAD

**Issue by painbrain81** [nightscout/AndroidAPS#2992]
in the 3.2.0.x and 3.1.0.x client app the target always remains that of the active profile. on androidaps master it is varied with autosens but on the client it always remains the same. Is it a mistake or is it intentional?
on client app it changes only if temp-target enable (from master or from client, it's the same)

**Comment by MilosKozak** [comment]
can you provide screenshot?

**Comment by painbrain81** [comment]
Sure! As soon as there is an opportunity for a target modified by autosens I will immediately take screenshots. Thank you.

**Comment by justmara** [comment]
There were options `sensitivity rises target` and `resistance lowers target` - only those could affect target by sensitivity. Do you have those enabled?

**Comment by painbrain81** [comment]
Yes. They are enabled and in fact on master it's ok (raise and decrease for autosens). In NSclient i see always only target from current profile.

**Comment by painbrain81** [comment]
> can you provide screenshot?

here is 3 screenshots. Master, NSclient and OPAS detail popup in NSclient.
![photo1698557809](https://github.com/nightscout/AndroidAPS/assets/24631990/73556f1e-0bc7-49d0-900a-fe8fdf68fa5f)
![photo1698557756 (1)](https://github.com/nightscout/AndroidAPS/assets/24631990/a25e298c-c698-4720-bd3f-d2d741578a05)
![photo1698557756](https://github.com/nightscout/AndroidAPS/assets/24631990/e53155d2-1a22-4de9-862b-86cb895bf362)

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/aa2ae1b99fe9dc6c02338bb86495ce0cc93093f9
