### ISSUE TITLE
It is unclear where the entry Carbs came from

### ISSUE THREAD

**Issue by KochiaX** [nightscout/AndroidAPS#2994]
Last night at 2.15 it is unclear from where there was a record of 96 grams of carbs. 96 is the max allowed carbs according to the settings. Around this time, I made a bolus for correction of 1.5 units through the button Insulin, but carbs were not introduced. As a result, AAPS started injecting SMB, which led to hypoglycemia.
I use AAPS 3.1.0.3, Nighscout 14.2.5.
![Preferences](https://github.com/nightscout/AndroidAPS/assets/118016784/a27f2d38-a1f4-4e47-abe9-1a8f3eb7433c)
![Treatments 1](https://github.com/nightscout/AndroidAPS/assets/118016784/010a5e2c-91fd-4e20-bec3-c58f3ef70346)
![Treatments 2](https://github.com/nightscout/AndroidAPS/assets/118016784/dd2a3c7b-5f08-476a-a596-cb73c76624e2)

**Comment by MilosKozak** [comment]
i can tell you if you have logs

**Comment by KochiaX** [comment]
> i can tell you if you have logs

Are these logs?

[AndroidAPS._2023-10-27_00-00-01_.0.zip](https://github.com/nightscout/AndroidAPS/files/13195815/AndroidAPS._2023-10-27_00-00-01_.0.zip)
[AndroidAPS._2023-10-27_00-00-01_.1.zip](https://github.com/nightscout/AndroidAPS/files/13195816/AndroidAPS._2023-10-27_00-00-01_.1.zip)

**Comment by vanelsberg** [comment]
Maybe wrong button pressed?
Your logs show user pressing button for Carbs entry:

```
02:16:15.959 [main] D/APS: [DialogFragmentWithDate.onViewCreated$lambda-7():130]: Submit pressed for Dialog: info.nightscout.androidaps.dialogs.CarbsDialog
....
02:16:18.377 [RxCachedThreadScheduler-52] D/CORE: [UserEntryLogger$log$2.invoke():45]: USER ENTRY: CARBS CarbDialog  [Gram(value=96)]
```

**Comment by MilosKozak** [comment]
exactly, someone entered them through Carbs dialog
