### ISSUE TITLE
[EOPATCH2] AAPS deactivates the time change loop

### ISSUE THREAD

**Issue by fjpezuela** [nightscout/AndroidAPS#3002]
Hello,

In Spain, the time has changed this morning (from 3:00 to 2:00).

Users of the EOPATCH2 pump have received a notification stating: "Daylight saving time change less than 3 hours ago - Closed loop disabled".

For 2 hours, we have been with the loop disabled, only receiving the programmed temporary basals.

This has happened to users with master version 3.2.0.1 as well as dev users.
[AndroidAPS._2023-10-29_02-00-00_.0.zip](https://github.com/nightscout/AndroidAPS/files/13197623/AndroidAPS._2023-10-29_02-00-00_.0.zip)

Later, everything started to work normally.

Here is an extract from the log, where you can see when the message appears:

03:02:42.273 [DefaultDispatcher-worker-5] D/APS: [LoopPlugin.invoke():229]: invoke from Calculation for app.aaps.core.interfaces.iob.InMemoryGlucoseValue@396971f
03:02:42.280 [RxCachedThreadScheduler-26] D/NOTIFICATION: [NotificationStore.add():61]: Notification received: Cambio al horario de verano hace menos de 3 horas - Lazo cerrado deshabilitado
03:02:42.280 [DefaultDispatcher-worker-5] D/CONSTRAINTS: [ConstraintObject.set():28]: Setting value true -> false (DST in last 3 hours.)[DstHelper]
03:02:42.282 [DefaultDispatcher-worker-5] D/CONSTRAINTS: [ConstraintObject.getReasons():89]: Limiting original value: true to false. Reason: DstHelper: DST in last 3 hours.
03:02:42.283 [DefaultDispatcher-worker-5] D/APS: [LoopPlugin.invoke():236]: LAZO DESACTIVADO POR RESTRICCIONES
DstHelper: DST in last 3 hours.
03:02:42.284 [RxCachedThreadScheduler-94] D/XDRIP: [XdripPlugin$onStart$3.accept():122]: UPL Start
03:02:42.284 [DefaultDispatcher-worker-5] D/APS: [LoopPlugin.invoke():456]: invoke end

03:17:02.808 [DefaultDispatcher-worker-7] D/WORKER: [LoggingWorker$doWork$2.invokeSuspend():27]: Worker result SUCCESS for class app.aaps.workflow.PrepareIobAutosensGraphDataWorker
03:17:02.852 [DefaultDispatcher-worker-7] D/WORKER: [LoggingWorker$doWork$2.invokeSuspend():27]: Worker result SUCCESS for class app.aaps.workflow.UpdateGraphWorker
03:17:02.893 [DefaultDispatcher-worker-7] D/APS: [LoopPlugin.invoke():229]: invoke from Calculation for app.aaps.core.interfaces.iob.InMemoryGlucoseValue@aeb738b
03:17:02.898 [DefaultDispatcher-worker-7] D/CONSTRAINTS: [ConstraintObject.set():28]: Setting value true -> false (DST in last 3 hours.)[DstHelper]
03:17:02.898 [RxCachedThreadScheduler-26] D/NOTIFICATION: [NotificationStore.add():61]: Notification received: Cambio al horario de verano hace menos de 3 horas - Lazo cerrado deshabilitado
03:17:02.900 [DefaultDispatcher-worker-7] D/CONSTRAINTS: [ConstraintObject.getReasons():89]: Limiting original value: true to false. Reason: DstHelper: DST in last 3 hours.
03:17:02.901 [DefaultDispatcher-worker-7] D/APS: [LoopPlugin.invoke():236]: LAZO DESACTIVADO POR RESTRICCIONES
DstHelper: DST in last 3 hours.
03:17:02.902 [DefaultDispatcher-worker-7] D/APS: [LoopPlugin.invoke():456]: invoke end
03:17:02.902 [DefaultDispatcher-worker-7] D/WORKER: [LoggingWorker$doWork$2.invokeSuspend():27]: Worker result SUCCESS for class app.aaps.workflow.InvokeLoopWorker
03:17:02.940 [DefaultDispatcher-worker-7] D/WORKER: [LoggingWorker$doWork$2.invokeSuspend():27]: Worker result SUCCESS for class app.aaps.workflow.UpdateWidgetWorker

Image of the period where the loop was disabled (I muted the notification).

![image](https://github.com/nightscout/AndroidAPS/assets/67511778/0084b5d8-8c35-4e30-8155-31d592a67162)

![image](https://github.com/nightscout/AndroidAPS/assets/67511778/fbe74052-8195-4454-84c2-c3f24b10e39a)

Thanks!

**Comment by Dorayaki-84** [comment]
Hi,
I attach screenshots of 2 more users.
Where we can see that due to the time change the closed loop stopped working for 2 hours.
![photo_2023-10-29_10-36-20](https://github.com/nightscout/AndroidAPS/assets/64844117/b92cfa35-ca33-4777-ae22-59cbbfeff505)
![photo_2023-10-29_08-13-11](https://github.com/nightscout/AndroidAPS/assets/64844117/53336e7a-d48e-4391-9c32-22bcd7e6325e)

**Comment by parapenT1sta** [comment]
Check in Other Pumps. Is working as expected. No bug.

https://androidaps.readthedocs.io/en/latest/Usage/Timezone-traveling.html#time-adjustment-daylight-savings-time-dst

**Comment by fjpezuela** [comment]
> Check in Other Pumps. Is working as expected. No bug.
> 
> https://androidaps.readthedocs.io/en/latest/Usage/Timezone-traveling.html#time-adjustment-daylight-savings-time-dst

Thank you. I had read that, but I thought it was referring to older pumps, as the other pumps do set the time correctly. So, does the Omnipod Dash do the same thing? There is no specific mention of these pumps.

Regards, Fran.

**Comment by parapenT1sta** [comment]
Other is different from older. :) Dash has also the same behavior.

https://github.com/nightscout/AndroidAPS/issues/3001

**Comment by vanelsberg** [comment]
Confirming: By design, no bug.

**Comment by robertrub** [comment]
Well, the design is not good then :)

I can understand 1 hour without loop (especially when time goes back with double entries for BGs etc) but not 3 hours.

Even the 1h should be treated internally and stay on closed loop (as with some other pumps) when DST changes.

**Comment by MilosKozak** [comment]
write better code ;)

**Comment by robertrub** [comment]
Before starting to write code (which I don't know how to), I need to think over the logic of how to threat the double entries or the 1h "blank" in the data. Will think about it.

We have 6 months to find a nice solution ;)

Can't understand why some pumps don't need open loop for 3h...

**Comment by MilosKozak** [comment]
the only pump with history which handles DST properly is Dana-i
For pumps without history it's only SW thing
