### ISSUE TITLE
[DEV] AAPSclient blocked connectivity without reason

### ISSUE THREAD

**Issue by szantos** [nightscout/AndroidAPS#3007]
AAPS 3.2.0.1-dev a909f8653a-2023.10.25 NSClientV3 + websockets
NS dev v15.0.2 44f70db
Time 2023-10-29 06:22:25
[Log Export 10-29.txt](https://github.com/nightscout/AndroidAPS/files/13204326/Log.Export.10-29.txt)

NSClient gave Blocked by connectivity options error without any reason, as every option is on, and there is no WIFI SSID restiction. Toggling all of them off and on, force closing the app and clearing cache has solves the problem.

![Screenshot_20231029-062656_AAPSClient~2](https://github.com/nightscout/AndroidAPS/assets/64865503/5ad9c2a5-122c-4a9c-824c-f794224e4d39)

![Screenshot_20231029-062708_AAPSClient~2](https://github.com/nightscout/AndroidAPS/assets/64865503/6772b064-c1e3-479d-8d06-5048d132c1b3)

**Comment by MilosKozak** [comment]
you simply lost connection to internet

**Comment by MilosKozak** [comment]
improved anyway here https://github.com/nightscout/AndroidAPS/commit/51e4a984974702b1652bfcabc4fe315234b66fda
