### ISSUE TITLE
[DynISF] Between 23:00 - 00:00 TDD stats only 6 days

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#3009]
I noticed that DynISF stop working between 23:00 and 00:00. Culprit seem to be that for some reason only 6 days of TDD are shown in AAPS Statistics and thus DynISF stop working.

Reproduced in latest dev and master. Can easily be reproduced by manually altering time in android.
Logs from AAPS 3.2 where DynISF was working then stopped working: 
[AndroidAPS_LOG_1698704407889.log.zip](https://github.com/nightscout/AndroidAPS/files/13210385/AndroidAPS_LOG_1698704407889.log.zip)

Before 23:00
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/96cfde43-7236-4e47-aa5a-20371a0b1b4b)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/659d3fdf-dca6-473b-854b-b0a5a620c4da)

After 23:00
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/e9526462-a098-4919-b6cf-e65c48b85591)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/a7d10892-b6f9-4e0b-90d8-ee9d8700c038)

**Comment by MilosKozak** [comment]
wasn't it at DST change day?

**Comment by olorinmaia** [comment]
In Norway we adjusted time back 1 hour 29. October 03:00.

**Comment by olorinmaia** [comment]
If it matters, same issue happens today. Both dev + master

**Comment by jakobheyman** [comment]
I can confirm this issue in dev.
![Screenshot_20231101-230621~2](https://github.com/nightscout/AndroidAPS/assets/9973815/c4cbfd97-4384-4f6f-82e0-d71277102313)

**Comment by TheNeskik** [comment]
I confirm this bug in master too.
[AndroidAPS_LOG_1698965455785.log.zip](https://github.com/nightscout/AndroidAPS/files/13245500/AndroidAPS_LOG_1698965455785.log.zip)

**Comment by szantos** [comment]
Same here with dev

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/47758b6b27c6e8562d598e5c63ba0ffde6593cb3

**Comment by marjolijnvanekkendonk** [comment]
I can confirm in master 3.2.01. No daylight savings since I’ve started using 3.2 on October 30th and daylight savings happened on the 29th. 
![Uploading 29B42385-8ECB-4455-AA4D-7FAF67A42A96.jpeg…]()
