### ISSUE TITLE
(enhancement) active insulin and absolute insulin in summary

### ISSUE THREAD

**Issue by painbrain81** [nightscout/AndroidAPS#3012]
If possible I would like to ask if it is possible to indicate in brackets after the active insulin also the absolute insulin, so as to have a complete picture and not have to obtain it empirically from the graph.
![Screenshot_20231031_102520_edit_1148366377337191](https://github.com/nightscout/AndroidAPS/assets/24631990/9bab7f00-cf14-4464-b917-3cb6bdc05cbd)

**Comment by MilosKozak** [comment]
this is very specific value not commonly used in treatment. it would be confusing for most people. so no
