### ISSUE TITLE
[DEV] Target in AAPSClient not aligned with AAPS using DynISF sensitivity target adjustment

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#3015]
AAPS / AAPSClient 3.2.0.1-dev
Build: ddc643b83a-2023.10.31

Nightscout-versjon: 15.0.2

Tested https://github.com/nightscout/AndroidAPS/issues/2992 with DynISF and options for adjusting target if sensitivity or resistance is detected enabled.

If I understood the change right, target in AAPSClient should change to show same value as AAPS when target is adjusted by autosens or dynISF-"autosens".

AAPS:
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/f232a2ab-9790-411a-8181-6e8cebf55019)

AAPSClient:
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/20f154d2-375f-4a9d-bb79-ba90d30ef6e2)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/6ad595d0-1bc0-42c0-8e6a-21d34c1de4b9)

Logs 
AAPS:
[AndroidAPS_LOG_1698788562612.log.zip](https://github.com/nightscout/AndroidAPS/files/13221670/AndroidAPS_LOG_1698788562612.log.zip)
AAPSClient:
[AndroidAPS_LOG_1698788545712.log.zip](https://github.com/nightscout/AndroidAPS/files/13221673/AndroidAPS_LOG_1698788545712.log.zip)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/2e8dd257c6152dbc8ddcade19fea77b1ebf05ce3
