### ISSUE TITLE
AAPS Overview contains stale CGM data

### ISSUE THREAD

**Issue by KM217** [nightscout/AndroidAPS#3022]
![Screenshot_20231101-160857](https://github.com/nightscout/AndroidAPS/assets/4782000/0b3bf63d-f463-4c30-ba24-7089b190f82e)
![Screenshot_20231101-160826](https://github.com/nightscout/AndroidAPS/assets/4782000/6e949721-4b23-4ca7-969c-1ccf5cd67a4d)
![Screenshot_20231101-161044](https://github.com/nightscout/AndroidAPS/assets/4782000/9c3ee35e-3308-4076-9459-f060ac728f3f)
Reporting bugs
--------------
- **Note the precise time the problem occurred**
1607-1610 UTC-7
 I noticed afyer having seen it many times before that the datat in the Overview tab was expired. I checked the xDrip+ app and found that it was getting updated glucose levels without issue. I then went back to AAPS, found the Overview tab had still not updated, and switched to the xDrip+ status tab within AAPS to find that it was updating without issue. I did finally see the Overview tab update, but I also noticed that it was running off of old values.

Since the AAPS app clearly shows different values depending on the screen you are in, this clearly appears to be an issue within the app itself and not a delay in updates from xDrip+.
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/13232648/AndroidAPS.log)

- Note the Build version
AndroidAPS 3.1.0.3

Build: 1de236a602-2023.09.26-16:39

Flavor: fullrelease

Nightscout version: UNKNOWN

Crash logs upload disabled!

**Comment by MilosKozak** [comment]
3.1 version is not supported anymore
upgrade to 3.2
