### ISSUE TITLE
[DEV] AAPS wear show unsmoothed BG value

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#3027]
AAPS 3.2.0.1-dev
Build: 168bc9cbdc-2023.11.03
NS: 15.0.2 master

Logs:
[AndroidAPS_LOG_1699020207115.log.zip](https://github.com/nightscout/AndroidAPS/files/13251640/AndroidAPS_LOG_1699020207115.log.zip)

AAPS show smoothed value:
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/d519ae54-28ed-4b87-82de-b968b13e1981)

Wear BG point on graph looks right, but show unsmoothed BG value:
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/1d184f2c-e114-4acb-90c1-fbebe184de3d)

**Comment by MilosKozak** [comment]
fixed in https://github.com/nightscout/AndroidAPS/commit/29356e0b2cb84b67ae4a4982ee170ccc85b8b819
