### ISSUE TITLE
[Master/Dev] BG Check in AAPS doesn't show BG value AAPSClient > Treatments > User entry

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#3028]
AAPS & Client 3.2.0.1-dev
Build: f08f32c581-2023.11.03
Nightscout version: 15.0.2

In 3.1 adding a BG check in AAPS careportal it appeared in AAPSClient in overview graph, treatments > careportal and treatments > "user entry" where value was showed.

In 3.2 BG value in Treatments > "User entry" seem to have disappeared. Does not matter if NSClientV1 or V3. It could possibly be improved while at it that BG value also show in Treatments > Careportal 

Logs & Screenshots:

AAPS: 
[AndroidAPS_LOG_1699049346841.log.zip](https://github.com/nightscout/AndroidAPS/files/13255075/AndroidAPS_LOG_1699049346841.log.zip)

![image](https://github.com/nightscout/AndroidAPS/assets/114103483/aa51bb33-f139-4a68-b710-e703c2356d76)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/b91f5216-c1f8-4e60-bac4-102d661f1161)

AAPSClient:
[AndroidAPS_LOG_1699049331268.log.zip](https://github.com/nightscout/AndroidAPS/files/13255076/AndroidAPS_LOG_1699049331268.log.zip)

![image](https://github.com/nightscout/AndroidAPS/assets/114103483/b33f6250-8ac2-49af-a071-bc238bc2b74d)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/fb4f6eb3-6bad-459b-a7a4-275aade2b10b)

**Comment by MilosKozak** [comment]
UserEntries are local log of user actions. They are not transferred anywhere

**Comment by olorinmaia** [comment]
I see. It was visible in 3.1 im pretty sure. Its just that we cant see bg value in AAPSClient anymore when entered in AAPS. Workaround for us is to type in value in notes field.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/617d722edda0b09e54795648082449c66df37aa3
