### ISSUE TITLE
AAPS 3.2.0.1 does not load NEW profiles to pump medtronic 712

### ISSUE THREAD

**Issue by Volberger** [nightscout/AndroidAPS#3029]
Since update to 3.2.0.1 NEW profiles are not loaded to pump medtronic 712. Profiles made with 3.1.xx can still be loaded to the pump. After cloning, editing, storering and starting the new made profil you will not get the "pump history" answer in the treatment section.
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://wiki.aaps.app/en/latest/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
no logs = no answer
