### ISSUE TITLE
CI error in bolus calculations 

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#3030]
I've never had this bug before. I started dinner, used the wizard to bolus and validated (not really checking the numbers). Then, when it started injecting, I saw over 7U to be given... My dinner is often less than 5U. I stopped immediately the injection. 

My Dev version

![Screenshot_20231104_164457_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/c1007c9b-9bc2-420b-8ace-dea7b6f36881)

I had my COVID injection and BG numbers were stuck a bit high. I set several times profile at 160% for 15-20 minutes to lower the BGs before dinner.

![Screenshot_20231104_200311_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/668b809b-d0b7-4502-aedc-e8fc51e5d1fd)

But the last one was long before dinner.

![Screenshot_20231104_195803_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/f9dff99e-66fc-4e42-9982-5db5c8385f07)

This is my profile

![Screenshot_20231104_195415_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/03833362-316b-4d32-afe9-1bdb1d04cd28)

And this is the calc results... The CI doesn't correspond to anything (not even 160% of my profile CI).

![Screenshot_20231104_195338_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/87a99ee6-2748-4b8c-ae27-e4697c7272fd)

When I used the wizard a second time, all worked ok as usual.

And the logs. Look around 19:52

![AndroidAPS_LOG_1699124288583.log.zip](https://github.com/nightscout/AndroidAPS/files/13257554/AndroidAPS_LOG_1699124288583.log.zip)

**Comment by MilosKozak** [comment]
I didn't see any bug in logs. Always was calculated with correct IC, except result of Wizard.
The only possible reason I see is you selected another profile for calculation in dialog. Don't you have one with IC 4,3?

**Comment by MilosKozak** [comment]
BolusWizard dialog is not covered by detailed logging to be able say what did you select

**Comment by robertrub** [comment]
I just checked and none of my profiles use a CI of 4.3 🤔

If there is no info in the logs, nothing we can do. Those repetitive actions we do without really putting in our full attention, I can't see how but maybe I did something strange... 

I'll close this issue and keep an eye open when using the wizard.
