### ISSUE TITLE
3.2.0.1 Increased connection Problems with Omnipod Dash

### ISSUE THREAD

**Issue by bionictom** [nightscout/AndroidAPS#3031]
Ever since updating to 3.2 I'm having many more problems with connection to my Omnipod Dash.
Multiple times of days, i'll get errors, where AAPS isnt' sure if SMB were delivered or profile changes didn't work.
On top of that , I just had an error Pod-Fault: 095 ALARM_WIRE_TEST_OPEN_GROUND which I didnt have before.

I have been usind Dev-Version with DynISF before with no connection problems.

[AndroidAPS_LOG_1699178398619.log.zip](https://github.com/nightscout/AndroidAPS/files/13259240/AndroidAPS_LOG_1699178398619.log.zip)
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/13259241/AndroidAPS.log)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://wiki.aaps.app/en/latest/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by jbr7rr** [comment]
Do you know which dev version you were using before?

**Comment by bionictom** [comment]
The one before 3.2.1 I've used was Dev "D" if that makes sense.

**Comment by robertrub** [comment]
```
 I just had an error Pod-Fault: 095 ALARM_WIRE_TEST_OPEN_GROUND which I didnt have before.
```

That alert has nothing to do with AAPS. It is pod breakdown.

With the last master and Dev, DASH connections are working really fast and good. Can you check your pod's validity dates ? Can you use another lot of pods to test ?

**Comment by bionictom** [comment]
Thanks for the feedback on that error.

Unfortunately, all the pods I have are the same lot-number. And i won't get any other ones for the next months

**Comment by robertrub** [comment]
And the expiry date is ???

**Comment by bionictom** [comment]
> And the expiry date is ???

2024-12-07

**Comment by robertrub** [comment]
Sorry, with the expiry out of the solution, no more threads to pull in order to guess what goes wrong with your system 🤔

**Comment by robertrub** [comment]
Do you have other BT connected to phone (ear/headphones?) any new powerful 5G WiFi router/extender ?

For all those who have tested the modified 3.2 version DASH, it was always rock solid, always better than with the "old" version.

**Comment by bionictom** [comment]
The other device connected via bluetooth is a smartband, but that's been like it before the update too. And no Wifi changes in my apartment either.

Thanks for looking into it. Maybe a weird combination of phone/os (lineageOS)? Maybe a software update will change anything? Gonna try that.

**Comment by robertrub** [comment]
We didn't have any other OS to test the modified code. So that can be an explanation but I'm not really convinced.

Try disconnecting smartband first (easier than flashing the phone ;) )

**Comment by robertrub** [comment]
Hi

Did you update to 3.2.0.3 and see if you still have the connection problems? If you have no more the connection problems, please close this issue.

**Comment by bionictom** [comment]
I did update, but the problems persisted. I have now upgraded my phone (from Poco F3 on Lineage OS to Poxo X6 Pro on  stock OS, and the problems went away. So I guess it was a phone/lineage problem?
