### ISSUE TITLE
DynamicISF gives no warning when not running

### ISSUE THREAD

**Issue by RBJervey** [nightscout/AndroidAPS#3038]
I updated to v3.2.1 on Tuesday with my pod change and decided not to change anything else at that point. On Thursday I changed from the G6 sensor to the G7. Sunday morning I decided to try out the new DynamicISF algorithm. So I went into my config and enabled it there. I then went back into config (which had closed upon enabling it) and set up all the settings. The x appeared over the autosens value and the DynamicIPS tab replaced the SMB tab. Great, I thought it was running. The next day i noticed that the change in ISF that I'd seen in others pictures wasn't showing on mine and I studied the DynamicISF tab in more detail to find a tiny line at the bottom of the constraints that said it wasn't running because I hadn't yet started Objective 11. 

 I'm proposing an enhancement to either start objective 11 when dynamicISF is selected  OR at very least display a message if it's selected without starting the objective that reminds the user to go start the objective so others aren't running for 24+ hours like I did without realizing it isn't active.

**Comment by MilosKozak** [comment]
improved in dev
