### ISSUE TITLE
[Dev/Master] Automation icon missing and small bug with rule temp target "is equal to" X mmol/l

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#3049]
- [x] **1)** If you add a automation rule with temp target "is equal to" example 8,0 it doesn't trigger. If you choose "equal or greater than" it triggers.

- [x] **2)** If you add a rule marked for "User action" the green gear icon doesn't appear in overview screen anymore, it was visible in 3.1.

**Rule TT is equal to not working:**
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/87107a41-84b8-4d29-a37f-96b0eea91990)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/5946c46c-fd04-49ee-8467-2244f28e99b7)

**Missing gear icon:**
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/cbcef4b5-17b6-4d12-8293-871fc87575c4)

**Comment by MilosKozak** [comment]
@osodebailar i didn't find the reason why icon is not appearing. can you help?

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/27355c18a2acc217401b7d70624df95d0eadd918

**Comment by ga-zelle** [comment]
With User Action the logo was always the gear icon. Therefore it does not add any information. Either reduce the button height or show the logo of the first action.
