### ISSUE TITLE
BG not rounded with dynISF

### ISSUE THREAD

**Issue by painbrain81** [nightscout/AndroidAPS#3050]
After few days with dynisf i discover that in nightscout BG is "float" and not rounded. 
With dynisf off situation is normal with rounded values. 
I attach a pic (just shared in discord) with incorrect value. 
![Screenshot_20231107_224311](https://github.com/nightscout/AndroidAPS/assets/24631990/0e23967a-8511-4f3c-81e8-36857d1d0b9b)

**Comment by MilosKozak** [comment]
what is your BG source?

**Comment by painbrain81** [comment]
It's always the same. Xdrip with freestyle 2 and smooth (by xdrip) with mean of last 5 values.
When dynisf is on, nightscout show float, when off is ok.
Ps: bg is uploaded by aaps, not xdrip

**Comment by MilosKozak** [comment]
put here log from AAPS to be able see data coming from xDrip

**Comment by painbrain81** [comment]
I'm sorry but I haven't been able to recreate the defect yet. I'll post the logs as soon as it happens

**Comment by MilosKozak** [comment]
it's xdrip issue
i added rounding of inccoming values anyway https://github.com/nightscout/AndroidAPS/commit/3e681ef219ceb11b6a185548ef735c8e43bd97ea
