### ISSUE TITLE
Omnipod Dash - Frequent "Pump Unreachable" errors

### ISSUE THREAD

**Issue by jchester47** [nightscout/AndroidAPS#3052]
ADD TIME OF EVENT HERE: 11:25 AM
ADD ISSUE DESCRIPTION OR GITHUB ISSUE REFERENCE NUMBER: I have been struggling with multiple "pump unreachable" events a day with escalating frequency. Upgrading AAPS has not helped. This occurs at random and not in a single place or around a single possible source of bluetooth interference. I'm using Omnipod Dash. 

This started about 2 months ago at random, prior to that never had a single issue. Using a Motorola Razr Plus 2023. All battery optimizations disabled, even on Bluetooth.

The only thing that seems to resolve this is force closing AAPS, clearing the cache, and then cycling BT on and off before rebooting the app. 

This occurs 4-5 times per day and is more frequent since upgrading to v3.2.0.0. 

I've tried everything - wiping BT cache multiple times per day, set up a macrodroid to kill and restart Bluetooth background processes, tried wearing the pod on a seperate arm from the dexcom, tried a different lot of pods ...nothing works. AAPS is just randomly killing the connection to the pod which then needs to be restored with a force close and reboot. 

Would appreciate any insight a more savvy user could provide, this has been driving me nuts!
-------------------------------------------------------
(Please remember this will send only very recent logs.
If you want to provide logs for event older than a few hours,
you have to do it manually)
-------------------------------------------------------
AAPS 3.2.0.0
Build: 0d969ac8ca-2023.10.23
Remote: https://github.com/nightscout/AndroidAPS
Flavor: fullrelease
Nightscout version: UNKNOWN
![AndroidAPS_LOG_1699637200507.log.zip](https://github.com/nightscout/AndroidAPS/files/13321840/AndroidAPS_LOG_1699637200507.log.zip)

**Comment by MilosKozak** [comment]
It's related purely to android and your phone as AAPS is asking android to connect to BT device and pump don't respond.
You may try following:
* Is multiple connection/disconnections of BT device "TWI BOARD". Unpair it, it may cause issues.
* Try if it's not related to place with high jamming of 2.4GHz frequency
* Remove all other BT paired devices
* Reset phohe to factory state
* Try another phone
