### ISSUE TITLE
Ability to manually set IOB

### ISSUE THREAD

**Issue by zibra** [nightscout/AndroidAPS#3058]
Is there any other way to manually adjust IOB other than providing fake boluses? The use case is negative IOB that I would like to change to zero when seslnsivity is high and I need to struggle with loop (or disable) to not pull into the hypo because of negaive IOB it tries to reduce.

**Comment by MilosKozak** [comment]
IOB is calculated value not user entry. so no

**Comment by szantos** [comment]
@zibra 
There is an automation trigger for IOB. As action, you could choose a higher TT or a lower profile %, etc.
