### ISSUE TITLE
I am modifying the source code to make it suitable for my app.

### ISSUE THREAD

**Issue by 100cm** [nightscout/AndroidAPS#3062]
First ,I almost finish this work, thanks everybody.

but i finnaly find some problems about oref0  algorithm . i understand the code how to calculate the AutosensResult, But I don't know why the result is calculated in this way. 

Do you have a more detailed documentation or algorithm document for the calculation process?

thanks a lot !

**Comment by MilosKozak** [comment]
GitHub with code is here: https://github.com/openaps/oref0
And here is the documentation: https://openaps.readthedocs.io/en/latest/
