### ISSUE TITLE
Unwanted loop run when switching targets.

### ISSUE THREAD

**Issue by justmara** [nightscout/AndroidAPS#3070]
The temptarget switch does not happen atomicly. There is an additional loop run triggered - between target changes.

Why this is a problem?
Here is exact scenario that happened to me:

I have set up 'disable smb with high temptarget' for my daughter's aaps and we're successfully using it to prevent overreaction on sneaks, when countering hypos. Eat/drink, then set 'hypo' target of 6.5 for 50 minutes and usually that is enough.

But this day after 35 minutes I decided to switch target to 6.0, so aaps could set a bit stronger TBS for the last 15 minutes. So without cancelling target I've set up NEW target of 6.0 for 15 minutes.
But AAPS did it in two steps: cancel TT, start new TT. Both events triggered loop run. So after cancelling TT AAPS placed a bolus for 'fast rise' that I wanted to prevent with high TT.

Lucky for us this time it was relatively small SMB, so we've managed it without a problem. But happens that predictions for the moment of change are highs so the unwanted SMB can be quite huge and lead to rollercoaster effect.

![Screenshot_20231118_112555_AAPSClient](https://github.com/nightscout/AndroidAPS/assets/4157587/66993bf7-959e-4393-ad00-48dc94132011)

![Screenshot_20231118_114528_AAPSClient](https://github.com/nightscout/AndroidAPS/assets/4157587/8c033970-24d6-4c7b-afed-47a60f9e9a64)

Target switch must be an atomic operation, without intermediate events and loop runs.

**Comment by painbrain81** [comment]
It's true. Same for me. Between target switch aps launch for one moment loop and do smb if set.

**Comment by swissalpine** [comment]
I can confirm this problematic behaviour.

**Comment by MilosKozak** [comment]
well is not atomic. loop is triggered by database change and there are 2 changes: end current TT and start new TT.
I'll check the code if this an be improved

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/2feaa419a715000eff001e5d58ca12e073cca8f1

**Comment by justmara** [comment]
got similar issue but with loop suspend event:
![Screenshot_20231202_150220_AAPSClient](https://github.com/nightscout/AndroidAPS/assets/4157587/ba6c162b-fe37-4044-9f36-2c766d9fbd4b)

High TT were set, then loop were suspended, and enabled again later. On start in were triggered ignoring TempTarget so it placed SMB.
