### ISSUE TITLE
Add Tidepool to objective question 

### ISSUE THREAD

**Issue by jbfeutz** [nightscout/AndroidAPS#3075]
As Tidepool can now be used as an alternative to Nightscout this question should be updated to avoid confusion ![FB_IMG_1700593924276.jpg](https://github.com/nightscout/AndroidAPS/assets/13263947/770f3b39-517c-4309-b403-31fae8fd1072)

**Comment by andyrozman** [comment]
Tidepool can't be used as alternative. Just as a backup.

**Comment by MilosKozak** [comment]
tidepool is not prerequisity

**Comment by jbfeutz** [comment]
I understand the comments above but this question is causing some confusion: https://www.facebook.com/groups/AndroidAPSUsers/permalink/3698473660374024/

If it is still the stance that Nightscout is a required prerequisite we should update the read the docs to reflect this as the new objective 1 makes it seem that it is no longer required.

**Comment by sbjornda** [comment]
The documentation at https://androidaps.readthedocs.io/en/latest/SettingUpAaps/SettingUpTheReportingServer.html clearly states "We recommend using Nightscout." - a recommendation, not a requirement. I just wasted an hour by being correct!
