### ISSUE TITLE
Minimum SMB Interval cannot go below 3 minutes

### ISSUE THREAD

**Issue by ga-zelle** [nightscout/AndroidAPS#3077]
The user can select a time between 1 and 10 minutes as minimum SMB interval. Nevertheless  in LoopPlugin.kt for instance this minimum is hard coded as 3 minutes.

**Comment by blaqone** [comment]
Interval set to 1 minute. This happens:

![Uploading BE513D84-8FD5-440B-A19A-D3110DCF452F.jpeg…]()

**Comment by MilosKozak** [comment]
thanks. will be fixed in 3.3
https://github.com/nightscout/AndroidAPS/commit/37e9931255662c1abd4d8f4d51f5c9fdd0002eb4

**Comment by blaqone** [comment]
Still does not work with your fix above included!

![915B414F-A6BC-479E-9810-555935BDBEA2](https://github.com/nightscout/AndroidAPS/assets/37814299/eed216c8-b220-4240-8a3e-cd93ebbb2a64)

**Comment by blaqone** [comment]
https://github.com/nightscout/AndroidAPS/commit/37e9931255662c1abd4d8f4d51f5c9fdd0002eb4#commitcomment-133429183

**Comment by MilosKozak** [comment]
right. thanks!
https://github.com/nightscout/AndroidAPS/commit/dcf74d23e8b2fe8de51e416e307e33adcb8d1073

**Comment by parapenT1sta** [comment]
@MilosKozak I left a comment on the commits. What is the reason of not being apply to "dev" branch? As I can see was applied on dev33, simplemode and equil branches.

**Comment by parapenT1sta** [comment]
@MilosKozak What is the reason for this bug fix only be applied on the next 3.3 version?

**Comment by MilosKozak** [comment]
3.3 diverged a lot
this fix is conflicting with changes in 3.3
