### ISSUE TITLE
Generic error 

### ISSUE THREAD

**Issue by benischatz** [nightscout/AndroidAPS#3080]
Hello
After upgrading to 3.2 unable to start a new pod, see attached screenshot. Old pod properly diactivated, thrown far away from new one. Tried cleaning database, rebuild apk, nothing.. xiamo F21pro phone. 
Once downgrading back to 3.1 all works just fine.
Any leads?
Thanks!!
![IMG_20231115_233146](https://github.com/nightscout/AndroidAPS/assets/97632459/d0ebafb5-f2f1-4d03-a993-e8318293b23f)

**Comment by painbrain81** [comment]
usually we solve with reboot phone. i think is a bluetooth (or smartphone) issue, not androidaps

**Comment by MilosKozak** [comment]
exactly. sorry there is nothing we can do
