### ISSUE TITLE
AAPS 3.2.0.2 crashes on basal temp attempt -> No connection to ruffy...

### ISSUE THREAD

**Issue by b-aeby** [nightscout/AndroidAPS#3083]
AAPS 3.2.0.2 (master) crashes every time a new basal temp is accepted.

Build version :  c31617fd2c-2023.11.21
Flavor: full release
Nightscout version 15.0.2

Pixel 6a, Android 14
Omnipod Dash

Here is the log file and a screen copy. It occurred at 16:16:28
16:16:28.996 [main] I/PUMP: [RuffyScripter.<init>():178]: No connection to ruffy. Pump control unavailable.

[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/13467324/AndroidAPS.log)
![IMG-20231126-WA0001](https://github.com/nightscout/AndroidAPS/assets/58775333/9bac9de2-1b2c-41d4-8b40-4dd111d76cd3)

**Comment by vanelsberg** [comment]
Have not seen any of this. Assuming this might be phone specific?

**Comment by b-aeby** [comment]
Objective 4, number of days > 7 but manual activation still at 0/20 as the app crashes on every attempts to accept a basal temp.

**Comment by vanelsberg** [comment]
I'd say there is something in your profile or settings that AAPS can not handle...

1. Immediately after the crash, not date and time and then get recent logfiles and attach them to this issue so dev can have a look?
2. Unselect your current pump (set it to Virtual pump), close/restart AAPS (... menu, exit), reselect your pump.
3. To make sure this is not some invalid setting in your profile, try removing all profiles (make a note of current profile settings) and then recreate a new one.

**Comment by jotomo** [comment]
@vanelsberg The log entry about RuffyScripter is benign. Will go away when ComboV2 has taken over.

**Comment by b-aeby** [comment]
Hello, restarting setup from scratch, including all objectives solved this issue.
I didn't try to reproduce but the issue happened while objective 1 was passed with Tidepool only, no Nightscout.
Thank you
