### ISSUE TITLE
Calibrations in Dexcom are causing duplicate value alerts and suspending closed loop 

### ISSUE THREAD

**Issue by jchester47** [nightscout/AndroidAPS#3089]
ADD TIME OF EVENT HERE:  11:22 AM 11/29/23
ADD ISSUE DESCRIPTION OR GITHUB ISSUE REFERENCE NUMBER:  Any time a calibration is entered in Dexcom, APS shows a red exclamation next to the blood sugar and a glucose value is marked as an out of normal sequence duplicate. However, this error occurs even when Dexcom does not accept the calibration and the Deccom app shows no duplicate or extra readings to match what APS shows in the history. Also, the supposed duplicate reading flagged in APS has a different time stamp from any other readings, confirming that it is not a duplicate.

This is very problematic as a calibration should not break the loop. I have to remember each time to go back into APS, delete the supposed duplicate value, and restart the loop. 
-------------------------------------------------------
(Please remember this will send only very recent logs.
If you want to provide logs for event older than a few hours,
you have to do it manually)
-------------------------------------------------------
AAPS 3.2.0.2
Build: c31617fd2c-2023.11.13
Remote: https://github.com/nightscout/AndroidAPS
Flavor: fullrelease
Nightscout version: UNKNOWN
![AndroidAPS_LOG_1701280115707.log.zip](https://github.com/nightscout/AndroidAPS/files/13503908/AndroidAPS_LOG_1701280115707.log.zip)

**Comment by jchester47** [comment]
I am using the G7 app, however this issue occurred with the G6 as well.

**Comment by MilosKozak** [comment]
* log doesn't have 11:22
* keep logging at default level until asked to change it

**Comment by blaqone** [comment]
diaKem sending doube values to AAPS is a known problem.

**Comment by MilosKozak** [comment]
Closed for inactivity
