### ISSUE TITLE
[Minor formatting bug] Bonus calculator show wrong precision, when glucose is in unit mg/dl

### ISSUE THREAD

**Issue by rICTx-T1D** [nightscout/AndroidAPS#31]
Bonus calculator show wrong precision, when glucose is in unit mg/dl.
Stable-Version 2.7.0

![screen](https://user-images.githubusercontent.com/57756367/89124548-38d92200-d4d8-11ea-972a-f95a8006285e.png)

**Comment by Philoul** [comment]
I made a PR to remove the decimal for BG value if unit is mg/dl

**Comment by rICTx-T1D** [comment]
> I made a PR to remove the decimal for BG value if unit is mg/dl

Thank you for fixing
