### ISSUE TITLE
AAPS BG/SG sync delay with BYODA 

### ISSUE THREAD

**Issue by galloglass** [nightscout/AndroidAPS#3105]
AAPS sync delay between BYODA BG/SG reading and AAPS displayed reading. 
AAPS picks up at 4 mins and doesn't update until 8/9mins, picks up old BYODA reading, just after AAPS update BYODA moves to latest SG reading. 
Setup: 3.2.02, BYODA latest updated version, combov2, pix6pro. 
BYODA tab shows 5min intervals but at 4mins in arrears. At 9mins SG is struck through and 3 delta marks go blank, then it picks up the old reading and shows the 4min interval reading. 
Yellow triangle disappeared after 36hrs, bug persists. 
Interestingly, xdrip shows the correct SG running alongside AAPS and recieving the SG from AAPS. 
Resolution attempted: cleared cache to AAPS and BYODA, updated AAPS and BYODA. Ran in airplane mode Bluetooth on.  xdrip source switched from 640g to sync follower. 
Date bug noticed 24th October, pre v3.2 update. Unknown cause for bug. 
Post noticing bug, I've changed transmitter and every 10days my sensor.

I've saved log files today and can share if I should? Images attached more available. 

Tia 

![Screenshot_20231210-211132](https://github.com/nightscout/AndroidAPS/assets/51086540/6a934b46-ab17-481d-9478-af40c2377570)
![Screenshot_20231208-200149](https://github.com/nightscout/AndroidAPS/assets/51086540/015d3b04-c4bc-47e2-a7d0-388cecc24633)

**Comment by MilosKozak** [comment]
add logs

**Comment by galloglass** [comment]
ADD TIME OF EVENT HERE:
ADD ISSUE DESCRIPTION OR GITHUB ISSUE REFERENCE NUMBER:
-------------------------------------------------------
(Please remember this will send only very recent logs.
If you want to provide logs for event older than a few hours,
you have to do it manually)
-------------------------------------------------------
AAPS 3.2.0.2
Build: c31617fd2c-2023.12.03
Remote: https://github.com/nightscout/AndroidAPS
Flavor: fullrelease
Nightscout version: UNKNOWN

**Comment by galloglass** [comment]
Log Export
<https://drive.google.com/file/d/113sfpwMUP0zT8z1ICmlx4htYA67Y9qe6/view?usp=drivesdk>

Please see attached.

Many thanks

Cormac

**Comment by MilosKozak** [comment]
Dexcom app sends data with wrong timestamp or late ie data received at 12:26:36 has a timestamp of 13:22:29
I don't have a solution for this as it's out of AAPS scope but you can try to reinstall BOYDA or use xdrip
