### ISSUE TITLE
[dev] ComboV2 - Pump site change as SMB (IOB)

### ISSUE THREAD

**Issue by parapenT1sta** [nightscout/AndroidAPS#3111]
*** Update: is also happening with the latest DEV:  https://github.com/nightscout/AndroidAPS/commit/b589b4fd90feb999a89e2da4db9fb0fb8c7dcd01***

I am using latest dev33 and my pump site change are being recognized as SMB (bolus)! I made a test to give 9.5U on a pump site change. Please check the screenshots and logs. Check around 8:00AM

[AndroidAPS_LOG_1702541012663.log.zip](https://github.com/nightscout/AndroidAPS/files/13670461/AndroidAPS_LOG_1702541012663.log.zip)

![Screenshot_20231214_080028_AAPS](https://github.com/nightscout/AndroidAPS/assets/608650/95baad13-119c-4605-9310-a7d4c65c2f5b)
![Screenshot_20231214_080147_AAPS](https://github.com/nightscout/AndroidAPS/assets/608650/f4249d39-e60f-405a-9bc6-4b71028f7951)
![Screenshot_20231214_080159_AAPS](https://github.com/nightscout/AndroidAPS/assets/608650/0d6ed0be-7c77-41f7-98d4-4e2e745cefd9)
![Screenshot_20231214_080210_AAPS](https://github.com/nightscout/AndroidAPS/assets/608650/0d549135-64c2-43b1-a3e7-03477af035fb)
![Screenshot_20231214_080230_AAPS](https://github.com/nightscout/AndroidAPS/assets/608650/466deff4-789a-4ecb-8207-c2d0bd54036b)
![Screenshot_20231214_080235_AAPS](https://github.com/nightscout/AndroidAPS/assets/608650/e2b88b08-c09b-4a48-ad59-07da2c9a0b9a)
![Screenshot_20231214_080316_AAPS](https://github.com/nightscout/AndroidAPS/assets/608650/e883ff1c-2fde-4958-861c-85182ad7630f)

**Comment by idalioreis** [comment]
Hi,

Same on me, Pump change insulin add to IOB.

**Comment by parapenT1sta** [comment]
@dv1 Can you check it?

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/405d013d25b462fd903b6472847af38860de1903
