### ISSUE TITLE
If the OK button is missing. Quite stupid for the kids ;)

### ISSUE THREAD

**Issue by elgrupo123** [nightscout/AndroidAPS#3119]
If the OK button is missing. Quite stupid for the kids ;) 3.2.0.3 

Thank you for your hateful work!

![Screenshot_20231216-175827](https://github.com/nightscout/AndroidAPS/assets/92778761/280f268d-fc16-400c-80c0-99a0cbf3f7b1)

**Comment by MilosKozak** [comment]
just scroll down

**Comment by elgrupo123** [comment]
well, for us as parents it's self-evident. Unfortunately for an 8 year old it's not. After all, the system is very innovative and should also be usable by small children.

**Comment by fezulin** [comment]
I took a closer look at the GUI. Although I was initially unhappy with the change, I have come to the conclusion that the design decision was a good one. 
If you have a small display (like me - Pixel 4), deactivate the checkbox next to the eye at the height of the "Cancel" and "OK" buttons. The display is clearer and the buttons are immediately accessible.
I hope that there are not too many people whose display is too small to show the buttons. 
@MilosKozak: Well done - thank you!

**Comment by MilosKozak** [comment]
> well, for us as parents it's self-evident. Unfortunately for an 8 year old it's not. After all, the system is very innovative and should also be usable by small children.

If the patient is 8yo why do you have all details enabled?

**Comment by elgrupo123** [comment]
So that he can click away IOB/COB if he has to deliver insulin more often in a row.

**Comment by MilosKozak** [comment]
??
