### ISSUE TITLE
Eros alerts option label typo wrong

### ISSUE THREAD

**Issue by lostboy86** [nightscout/AndroidAPS#3126]
There is only a possibility to set alerts relative to 80h for Eros. 

The text in the configuration page is wrong. 

It shuld say 80h not 72h. for alert configurations.

Tested with other users with Eros, it's an error typo on Eros preferences screen

**Comment by MilosKozak** [comment]
"Reminder at hours before expiry (72 Hours)" this should be 80?

**Comment by fredrik-ljung** [comment]
Yes. It shold be relative 80 Hours. I tested it a couple of days ago.
There is a similar string for dash. With dash you have the possibility to set one alert relative to 80h and one relative to 72h.
Perhaps the description string with 80h for dash can be reused for eros.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/2c992dfd6824d52a3554df5794cccc7b70c4a037
