### ISSUE TITLE
No insulin recorded when administering insulin with option "Do not bolus, record only"

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#3130]
**AndroidAPS 3.3.0-dev**
**Build:** c1b9dbe8
**Flavor:** Fullrelease

**Problem description:**
Administering insulin with option "Do not bolus, record only" does not record any insulin

**Additional information**
Using the Insulin button at the bottom of the AAPS overview/Home screen

**Repro:**
1. Press "Insulin" button
2. Select checkbox "Do not bolus,..."
3. Enter units of insulin.
4. Optionally enter offset in minutes.
5. Press OK (Pop-up confirms and shows warning about insulin amount and "recorded only...")

Validation:
1. No additional insulin listed as IOB
2. Treatments->Crabs & Bolus does not show insulin recorded

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/adf2df745145a07d0ebe3e3a6bb22babcfa1cadf
