### ISSUE TITLE
[AndroidAPS 3.2.0.3] Suggestion: GUI change bolus wizard

### ISSUE THREAD

**Issue by fezulin** [nightscout/AndroidAPS#3132]
I would like to suggest a GUI change for bolus wizard.
The line "carb time" can be included in the table with the other input fields. 
If the details are hidden, the line could still be visible. 
See attached pictures.
I changed the file "dialog_wizard.xml" locally and I like to provide this file. 
(But I also like to avoid the effort to learn the processes about pull requests.) ;o)
Please give me a hint how I can share the changed file, if you are interested.

![Bolus_Wizard_long](https://github.com/nightscout/AndroidAPS/assets/16593716/57567e68-4b75-41f9-806b-29a3cb3a0b37)
![Bolus_Wizard_Short](https://github.com/nightscout/AndroidAPS/assets/16593716/4bde589a-e515-41e1-8302-fcc06db77de5)

**Comment by MilosKozak** [comment]
paste it here if you don't know how to create a PR

**Comment by fezulin** [comment]
<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    style="@style/StyleDialog"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:focusableInTouchMode="true"
    tools:context=".dialogs.InsulinDialog">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <RelativeLayout
            style="@style/StyleDialogHeader"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center">

            <ImageView
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:importantForAccessibility="no"
                app:srcCompat="@drawable/ic_calculator" />

            <TextView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_centerInParent="true"
                android:layout_gravity="center"
                android:layout_marginStart="10dp"
                android:layout_marginEnd="10dp"
                android:text="@string/boluswizard"
                android:textAlignment="center"
                android:textAppearance="?android:attr/textAppearanceLarge" />

        </RelativeLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:layout_marginStart="10dp"
            android:layout_marginTop="5dp"
            android:layout_marginEnd="10dp"
            android:background="?attr/dialogTitleBackground"
            android:gravity="center_horizontal"
            android:orientation="horizontal"
            android:paddingTop="5dp"
            android:paddingBottom="5dp">

            <TextView
                android:id="@+id/total"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:paddingStart="10dp"
                android:paddingEnd="10dp"
                android:text="2.35U 28g"
                android:textAppearance="?android:attr/textAppearanceLarge"
                tools:ignore="HardcodedText" />

            <TextView
                android:id="@+id/percent_used"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="10dp"
                android:paddingStart="10dp"
                android:paddingEnd="10dp"
                android:text="50%"
                android:textAppearance="?android:attr/textAppearanceLarge"
                android:textColor="?attr/bolusColor"
                tools:ignore="HardcodedText" />

        </LinearLayout>

        <LinearLayout
            android:id="@+id/spacer"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:padding="5dp" />

        <TableLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:paddingStart="0dp"
            android:paddingEnd="5dp">

            <TableRow
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <TextView
                    android:id="@+id/bg_input_label"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:padding="10dp"
                    android:text="@string/bg_label"
                    android:textAppearance="@style/TextAppearance.AppCompat.Small"
                    android:textStyle="bold" />

                <app.aaps.core.ui.elements.NumberPicker
                    android:id="@+id/bg_input"
                    android:layout_width="130dp"
                    android:layout_height="40dp"
                    android:layout_marginBottom="2dp"
                    app:customContentDescription="@string/a11y_current_bg" />

                <TextView
                    android:id="@+id/bg_units"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_vertical"
                    android:gravity="start"
                    android:padding="5dp"
                    android:text="@string/mgdl"
                    android:textAppearance="?android:attr/textAppearanceSmall" />

            </TableRow>

            <TableRow
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <TextView
                    android:id="@+id/carbs_input_label"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:labelFor="@id/carbs_input"
                    android:padding="10dp"
                    android:text="@string/carbs"
                    android:textAppearance="@style/TextAppearance.AppCompat.Small"
                    android:textStyle="bold" />

                <app.aaps.core.ui.elements.NumberPicker
                    android:id="@+id/carbs_input"
                    android:layout_width="130dp"
                    android:layout_height="40dp"
                    android:layout_gravity="center_horizontal"
                    android:layout_marginBottom="2dp"
                    app:customContentDescription="@string/carbs" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_vertical"
                    android:gravity="start"
                    android:padding="5dp"
                    android:text="@string/shortgramm"
                    android:textAppearance="?android:attr/textAppearanceSmall" />

            </TableRow>

            <TableRow
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <LinearLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:gravity="center_vertical"
                    android:orientation="horizontal">

                    <TextView
                        android:id="@+id/correction_input_label"
                        android:layout_width="0dp"
                        android:layout_height="wrap_content"
                        android:layout_weight="1"
                        android:padding="10dp"
                        android:text="@string/treatments_wizard_correction_label"
                        android:textAppearance="@style/TextAppearance.AppCompat.Small"
                        android:textStyle="bold" />

                    <CheckBox
                        android:id="@+id/correction_percent"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="center_vertical"
                        android:checked="false"
                        android:layoutDirection="rtl"
                        android:padding="2dp"
                        android:text="%"
                        android:textAppearance="@style/TextAppearance.AppCompat.Medium"
                        android:textStyle="bold"
                        tools:ignore="HardcodedText" />

                </LinearLayout>

                <app.aaps.core.ui.elements.NumberPicker
                    android:id="@+id/correction_input"
                    android:layout_width="130dp"
                    android:layout_height="40dp"
                    android:layout_gravity="center_horizontal"
                    app:customContentDescription="@string/a11_correction_units" />

                <TextView
                    android:id="@+id/correction_unit"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_vertical"
                    android:gravity="start"
                    android:padding="5dp"
                    android:text="@string/insulin_unit_shortname"
                    android:textAppearance="?android:attr/textAppearanceSmall" />

            </TableRow>

            <TableRow
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <LinearLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:gravity="center_vertical"
                    android:orientation="horizontal">

                    <TextView
                        android:id="@+id/carb_time_input_label"
                        android:layout_width="0dp"
                        android:layout_height="wrap_content"
                        android:layout_weight="1"
                        android:padding="10dp"
                        android:text="@string/carb_time_label"
                        android:textAppearance="@style/TextAppearance.AppCompat.Small"
                        android:textStyle="bold" />

                    <CheckBox
                        android:id="@+id/alarm"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="center_vertical"
                        android:checked="false"
                        android:contentDescription="@string/a11y_set_carb_timer"
                        android:drawableEnd="@drawable/ic_access_alarm_24dp"
                        android:layoutDirection="rtl"
                        android:padding="2dp" />

                </LinearLayout>

                <app.aaps.core.ui.elements.NumberPicker
                    android:id="@+id/carb_time_input"
                    android:layout_width="130dp"
                    android:layout_height="40dp"
                    android:layout_gravity="center_horizontal"
                    app:contentDescription="carb time" />


                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_vertical"
                    android:gravity="start"
                    android:padding="5dp"
                    android:text="@string/unit_minute_short"
                    android:textAppearance="?android:attr/textAppearanceSmall" />

            </TableRow>

        </TableLayout>

        <include
            android:id="@+id/notes_layout"
            layout="@layout/notes" />

        <LinearLayout
            android:id="@+id/checkbox_row"
            android:layout_width="match_parent"
            android:layout_height="45dp"
            android:paddingHorizontal="10dp">

            <ToggleButton
                android:id="@+id/bg_checkbox_icon"
                style="?android:attr/borderlessButtonStyle"
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:checked="true"
                android:contentDescription="@string/bg_label"
                android:drawableTop="@drawable/checkbox_bg_icon"
                android:scaleX="1.4"
                android:scaleY="1.4" />

            <ToggleButton
                android:id="@+id/tt_checkbox_icon"
                style="?android:attr/borderlessButtonStyle"
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:checked="true"
                android:contentDescription="@string/tt_label"
                android:drawableTop="@drawable/checkbox_tt_icon"
                android:scaleX="1.6"
                android:scaleY="1.6" />

            <ToggleButton
                android:id="@+id/trend_checkbox_icon"
                style="?android:attr/borderlessButtonStyle"
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:checked="true"
                android:contentDescription="@string/bg_trend_label"
                android:drawableTop="@drawable/checkbox_trend_icon"
                android:scaleX="1.4"
                android:scaleY="1.4" />

            <ToggleButton
                android:id="@+id/iob_checkbox_icon"
                style="?android:attr/borderlessButtonStyle"
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:checked="true"
                android:contentDescription="@string/iob"
                android:drawableTop="@drawable/checkbox_iob_icon"
                android:scaleX="1.4"
                android:scaleY="1.4" />

            <ToggleButton
                android:id="@+id/cob_checkbox_icon"
                style="?android:attr/borderlessButtonStyle"
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:checked="true"
                android:contentDescription="@string/treatments_wizard_cob_label"
                android:drawableTop="@drawable/checkbox_cob_icon"
                android:scaleX="1.6"
                android:scaleY="1.6" />

        </LinearLayout>

        <View
            android:id="@+id/delimiter"
            android:layout_width="fill_parent"
            android:layout_height="2dip"
            android:layout_marginStart="20dp"
            android:layout_marginTop="0dp"
            android:layout_marginBottom="5dp"
            android:background="?android:attr/dividerHorizontal" />

        <LinearLayout
            android:id="@+id/result"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal"
                android:orientation="horizontal">

                <com.google.android.material.textfield.TextInputLayout
                    style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.ExposedDropdownMenu"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_marginStart="5dp"
                    android:layout_marginEnd="5dp"
                    android:layout_weight="0.5"
                    android:hint="@string/profile"
                    android:paddingStart="7dp"
                    android:paddingEnd="0dp">

                    <com.google.android.material.textfield.MaterialAutoCompleteTextView
                        android:id="@+id/profileList"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:inputType="none" />

                </com.google.android.material.textfield.TextInputLayout>

                <CheckBox
                    android:id="@+id/sb_checkbox"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_vertical"
                    android:layout_marginStart="10dp"
                    android:checked="false"
                    android:padding="5dp"
                    android:text="@string/superbolus" />

            </LinearLayout>

            <TableLayout
                android:id="@+id/result_table"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:padding="5dp">

                <View
                    android:layout_width="fill_parent"
                    android:layout_height="2dip"
                    android:layout_marginStart="20dp"
                    android:layout_marginTop="0dp"
                    android:layout_marginBottom="5dp"
                    android:background="?android:attr/dividerHorizontal" />

                <TableRow
                    android:layout_width="match_parent"
                    android:layout_height="match_parent">

                    <LinearLayout
                        android:layout_width="wrap_content"
                        android:layout_height="match_parent"
                        android:orientation="horizontal">

                        <CheckBox
                            android:id="@+id/bg_checkbox"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:checked="true"
                            android:text="@string/bg_label" />

                        <CheckBox
                            android:id="@+id/tt_checkbox"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:checked="false"
                            android:text="@string/tt_label" />

                    </LinearLayout>

                    <TextView
                        android:id="@+id/bg"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_weight="1"
                        android:width="94dp"
                        android:textAppearance="?android:attr/textAppearanceSmall" />

                    <TextView
                        android:id="@+id/bg_insulin"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:width="50dp"
                        android:gravity="end"
                        android:textAppearance="?android:attr/textAppearanceSmall" />

                </TableRow>

                <TableRow
                    android:layout_width="match_parent"
                    android:layout_height="match_parent">

                    <CheckBox
                        android:id="@+id/bg_trend_checkbox"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:checked="false"
                        android:text="@string/bg_trend_label" />

                    <TextView
                        android:id="@+id/bg_trend"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_weight="1"
                        android:width="94dp"
                        android:textAppearance="?android:attr/textAppearanceSmall" />

                    <TextView
                        android:id="@+id/bg_trend_insulin"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:width="50dp"
                        android:gravity="end"
                        android:textAppearance="?android:attr/textAppearanceSmall" />

                </TableRow>

                <TableRow
                    android:layout_width="match_parent"
                    android:layout_height="match_parent">

                    <CheckBox
                        android:id="@+id/iob_checkbox"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:checked="true"
                        android:text="@string/iob" />

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_weight="1"
                        android:width="50dp"
                        android:textAppearance="?android:attr/textAppearanceSmall" />

                    <TextView
                        android:id="@+id/iob_insulin"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:width="50dp"
                        android:gravity="end"
                        android:textAppearance="?android:attr/textAppearanceSmall" />

                </TableRow>

                <TableRow
                    android:layout_width="match_parent"
                    android:layout_height="match_parent">

                    <CheckBox
                        android:id="@+id/cob_checkbox"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:width="32dp"
                        android:checked="false"
                        android:text="@string/treatments_wizard_cob_label" />

                    <TextView
                        android:id="@+id/cob"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_weight="1"
                        android:width="94dp"
                        android:textAppearance="?android:attr/textAppearanceSmall" />

                    <TextView
                        android:id="@+id/cob_insulin"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:width="50dp"
                        android:gravity="end"
                        android:textAppearance="?android:attr/textAppearanceSmall" />

                </TableRow>

                <TableRow
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:focusable="true">

                    <LinearLayout
                        android:layout_width="wrap_content"
                        android:layout_height="match_parent"
                        android:orientation="horizontal">

                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:width="32dp" />

                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:width="86dp"
                            android:text="@string/carbs"
                            android:textAppearance="?android:attr/textAppearanceSmall" />

                    </LinearLayout>

                    <TextView
                        android:id="@+id/carbs"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_weight="1"
                        android:width="94dp"
                        android:textAppearance="?android:attr/textAppearanceSmall" />

                    <TextView
                        android:id="@+id/carbs_insulin"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:width="50dp"
                        android:gravity="end"
                        android:textAppearance="?android:attr/textAppearanceSmall"
                        tools:ignore="TooManyViews" />

                </TableRow>

                <TableRow
                    android:id="@+id/super_bolus_row"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:focusable="true">

                    <LinearLayout
                        android:layout_width="wrap_content"
                        android:layout_height="match_parent"
                        android:orientation="horizontal">

                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:width="32dp" />

                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:width="86dp"
                            android:text="@string/superbolus"
                            android:textAppearance="?android:attr/textAppearanceSmall" />

                    </LinearLayout>

                    <TextView
                        android:id="@+id/sb"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_weight="1"
                        android:width="94dp"
                        android:textAppearance="?android:attr/textAppearanceSmall" />

                    <TextView
                        android:id="@+id/sb_insulin"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:width="50dp"
                        android:gravity="end"
                        android:textAppearance="?android:attr/textAppearanceSmall" />

                </TableRow>

                <TableRow
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:focusable="true">

                    <LinearLayout
                        android:layout_width="wrap_content"
                        android:layout_height="match_parent"
                        android:orientation="horizontal">

                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:width="32dp" />

                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:width="86dp"
                            android:text="@string/treatments_wizard_correction_label"
                            android:textAppearance="?android:attr/textAppearanceSmall" />

                    </LinearLayout>

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_weight="1"
                        android:width="94dp"
                        android:textAppearance="?android:attr/textAppearanceSmall" />

                    <TextView
                        android:id="@+id/correction_insulin"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:width="50dp"
                        android:gravity="end"
                        android:textAppearance="?android:attr/textAppearanceSmall" />

                </TableRow>

            </TableLayout>

        </LinearLayout>

        <LinearLayout
            android:id="@+id/done_background"
            android:layout_width="match_parent"
            android:layout_height="50dp"
            android:layout_gravity="center_vertical"
            android:background="@android:color/transparent"
            android:orientation="horizontal"
            android:paddingStart="5dp"
            android:paddingEnd="5dp">

            <CheckBox
                android:id="@+id/calculation_checkbox"
                android:layout_width="wrap_content"
                android:layout_height="fill_parent"
                android:layout_gravity="center_vertical"
                android:checked="false"
                android:contentDescription="@string/show_calculation"
                android:drawableEnd="@drawable/ic_visibility" />

            <include
                android:id="@+id/okcancel"
                layout="@layout/okcancel" />

        </LinearLayout>

    </LinearLayout>

</ScrollView>

**Comment by fezulin** [comment]
Hm - in my last comment the xml-header is not displayed.
I did not change it. Here the header again:

<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    style="@style/StyleDialog"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:focusableInTouchMode="true"
    tools:context=".dialogs.InsulinDialog">

**Comment by fezulin** [comment]
WTF? The header cannot be displayed here? 
However - it is unchanged anyway.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/8ab0b697d9bcb68815c2de72b5571ea7a0c524ea
