### ISSUE TITLE
Automatically enabled Hypo Temp-Target with input from Carbs 

### ISSUE THREAD

**Issue by Korostensky** [nightscout/AndroidAPS#3134]
3.3.0-dev-app-full-release
--------------
Option is not checked and yet the temporary hypoglycemic target is triggered.
I've tried the master version and it's ok.

![Screenshot_20231220_141106_AAPS](https://github.com/nightscout/AndroidAPS/assets/54218454/719edc89-f04d-4c49-b75f-df0325666e1a)

![Screenshot_20231220_141114_AAPS](https://github.com/nightscout/AndroidAPS/assets/54218454/72a1903b-bcbc-4fd4-b10f-86689d3ce50f)

![Screenshot_20231220_141118_AAPS](https://github.com/nightscout/AndroidAPS/assets/54218454/212394ae-aaf9-4171-af95-ff3207699adb)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/775eff004efc100728b4afa9e3c949a14323fee4
