### ISSUE TITLE
AAPS Wear, latest dev commit#041d0f0: Ongoing bolus notification that can not be cleared.

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#3137]
**AndroidAPS 3.3.0-dev Wear application**
Build: https://github.com/nightscout/AndroidAPS/commit/041d0f0b7bd43042dbf201f442c1a48433eb22cd
Flavor: Fullrelease

**Problem description:**

Latest dev commit https://github.com/nightscout/AndroidAPS/commit/041d0f0b7bd43042dbf201f442c1a48433eb22cd (Wear: create notification channel) introduces a problem for my Samsung Watch 4 running the AAPS watchface (both stock or custom):

The watch now continuesly shows an "ongoing notification" that can not be cleared.
Forcefully clearing the notification is not possible (it immediately reopens after clearing)

![ogn](https://github.com/nightscout/AndroidAPS/assets/45144129/9cebe95c-054e-4fdf-99df-610351bc241f)

**Comment by vanelsberg** [comment]
Additional note:
Looks like this problem is only for bolus notifications. They stay open at 100% - Success (see screenschot)
(Notification not properly closed when bolus finisces?)

Carbs notification for instance are not affected.

**Comment by vanelsberg** [comment]
**Additional note:**
@MilosKozak Tested with previous commit f3be1bbfe1fe78aee30d791ae5f5e6dadab579b1
Problem is not in this commit.

**Comment by MilosKozak** [comment]
ongoing notification channel is necessary to keep app running on background
you have to hide it https://www.reddit.com/r/tasker/comments/rf7369/protip_disable_specific_notification_channels_on/

**Comment by vanelsberg** [comment]
> ongoing notification channel is necessary to keep app running on background you have to hide it https://www.reddit.com/r/tasker/comments/rf7369/protip_disable_specific_notification_channels_on/

Nope, does not solve the problem... :-(
From developer mode on the watch I can disable some of the notification types, but as soon as there is a (bolus) notification it  is a "ongoing notification" which can not be cleared. I can disable "all", but then I do not get any notifications at all :-|

**My conclusion:**
1) User being unable to clear (any) notification on the watch UI is unwanted behavior.
2) Hiding only works when disabling _all AAPS notifications_ on the watch, which would disable important functionality.
3) It is rather odd to expect AAPS users to go into developer mode to hide/prevent such unexpected and unwanted behavior?

**Proposed solution:**
Make activating the ongoing channel a user configurable option:
The ongoing notification channel is unexpected and unwanted behavior and only necessary (as a work around?) for users running non-AAPS watchfaces.

@MilosKozak Let me know if you'd like this prosed solution moved to a separate issue?

**Comment by vanelsberg** [comment]
@MilosKozak Did some local testing enabling the [Wear: create notification channel](https://github.com/nightscout/AndroidAPS/commit/041d0f0b7bd43042dbf201f442c1a48433eb22cd) as a user option through the wear app settings. 

Code is still QAD, but could to a PR for dev's to test?

**Comment by vanelsberg** [comment]
Confirming #3141solved this problem!
Tnx.
