### ISSUE TITLE
Red numbers when sensor has life left

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#3140]
Dev 3.3.0. I reset sensor life to 14 days but I still have a red 8 days on the UI.

![Screenshot_20231225_183747_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/b3b66e1b-f282-4983-89a5-027c5e72465e)

![Screenshot_20231225_185120_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/7b96fc46-0d4c-44b2-970d-d5e104d60c5e)

![Screenshot_20231225_185135_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/acfe5196-6cbf-4939-8054-ff75a7c5cb88)

![AndroidAPS_LOG_1703528340908.log.zip](https://github.com/nightscout/AndroidAPS/files/13766999/AndroidAPS_LOG_1703528340908.log.zip)

**Comment by robertrub** [comment]
Deleting the CGM insertion in the treatments and entering it again didn't solve the problem. 8 days sensor life is still red.

**Comment by mick711** [comment]
With last dev 3 days réd.

**Comment by mordechi-david** [comment]
Same to me too

**Comment by vanelsberg** [comment]
For me the problem was fixed through (https://github.com/nightscout/AndroidAPS/commit/45d93f0a7c95fe8a3d91f03d4b0a9748ea77c97c)
