### ISSUE TITLE
Wear : Data layer foreground notification 

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#3143]
Latest Dev on phone and wear.

![Screenshot_20231225_183747_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/5e2940eb-4767-41ab-be40-fb431ba9eb30)

I keep getting the Data layer foreground notification over and over.
![Screenshot_20231227_180411_sysui.png](https://github.com/nightscout/AndroidAPS/assets/76626474/60a8c35e-abd7-46bc-9e99-4efa26ec6621)

 Can't erase it.

![Screenshot_20231227_180447_sysui.png](https://github.com/nightscout/AndroidAPS/assets/76626474/0112ff75-3196-4cd0-9f5c-9a340cbd4f51)

The only option is open the notification settings and stop the notifications but it then asks me if I want to stop all notifications from AAPS... 

![Screenshot_20231227_180419_sysui.png](https://github.com/nightscout/AndroidAPS/assets/76626474/978b2615-64d0-40aa-90e1-ee6954fd64e9)

Was working great before. I don't know why this commit was added but it made things worst.

Logs. 

![AndroidAPS_LOG_1703697301388.log.zip](https://github.com/nightscout/AndroidAPS/files/13780165/AndroidAPS_LOG_1703697301388.log.zip)

**Comment by robertrub** [comment]
Turning OFF the notification turned OFF ALL notifications on watch from AAPS.

https://github.com/nightscout/AndroidAPS/commit/d75c4651f6e41b44486c8b13500d6b5972ae406a  Is not working as it should.

**Comment by robertrub** [comment]
Updated to the latest Dev on phone and watch tonight and the problem is still there.

![Screenshot_20231227_203227_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/e974912b-0356-47d5-b9fb-4358618dc4e8)

**Comment by vanelsberg** [comment]
Confirming:
See also https://github.com/nightscout/AndroidAPS/issues/3137 (AAPS Wear: Ongoing bolus notification that can not be cleared)

**Comment by MilosKozak** [comment]
on android 10+ ongoing notification must be in place if you want to have service running on background

**Comment by robertrub** [comment]
Till now, the notifications were working great . Now we're stuck with a notification that we can't erase. 

The fix made things worst (at least for some (or many ?) users).

**Comment by MilosKozak** [comment]
in 3.2.0.3 service was suspended without active watchface (on background). if you add notification android allows have it running on backgroung

**Comment by vanelsberg** [comment]
> in 3.2.0.3 service was suspended without active watchface (on background) and complications were not working. if you add notification android allows service running on background. the price for it is permanent notification

@MilosKozak @robertrub How about making this notification feature optional (read: configurable on/off)?
I could do a PR for this...

**Comment by robertrub** [comment]
Totally vote for it being an option.

**Comment by MilosKozak** [comment]
totally against more options :)

**Comment by robertrub** [comment]
You're the boss ;)

How many people use the AAPS watchface and how many use others ?

I still believe that more will be bothered with the change than happy to gave it.

Of course, you can ignore the _stuck notification_ on the watch but I'll be the one to tell them to ignore it when they'll complain about it on Discord... :(

**Comment by TebbeUbben** [comment]
@MilosKozak As far as I know, using an ongoing notification is not required, although the system might enforce that depending on the Android version. It might also be worth an attempt to use PRIORITY_MIN. These notifications did not appear on my watch at all and I got a notification by the system instead that AndroidAPS was running in the background (which can be dismissed).

Anyways, on my Pixel Watch 2 I'm able to disable the notification channel in the system settings. Perhaps that setting is hidden on watches from other manufacturers. Manually launching the intent might work (see https://stackoverflow.com/questions/32366649/any-way-to-link-to-the-android-notification-settings-for-my-app). There's probably also a way to manage notifications via ADB.

**Comment by vanelsberg** [comment]
> ...] Perhaps that setting is hidden on watches from other manufacturers [...

With current dev-builds, on the Samsung Galaxy Watch 4, I can hide the ongoing notification through developer settings:
`App Notifications -> All watch apps -> AAPS -> Data layer Foreground Service Channel: OFF`

**Comment by robertrub** [comment]
No, I don't have that option. Samsung Android 14. Both phone and watch are set to developer mode.

Am I searching in the wrong place ?

![Screenshot_20240114_090427_Settings.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/a2b08dfd-3b00-4b2b-9900-bbae46427c68)

**Comment by vanelsberg** [comment]
> No, I don't have that option...

Wrong place. Check developer options menu _on Watch_:
1. Scroll all to way down to App Notifications
2. Select: All watch apps -> AAPS -> Data layer Foreground Service Channel
3. Switch ir OFF

**Comment by robertrub** [comment]
OK, thanks. Found it and deactivated it with succes. 

Not the best option/solution for an "average" user though.

Robby

**Comment by olorinmaia** [comment]
@MilosKozak Here are my thoughts on the matter. I don't think we want to solve a problem for a few users, and create a new problem that will concern all. As it stands now the data layer foreground notification is an annoyance that most users will have issues with. It vibrates often without any reason, and if you enact anything from the tiles it also comes up first, before what you usually see.

I've been trying to alter the code to make it less annoying, it seems that the following helps, keeping it from blocking wanted notifications when enacting from tiles and vibrating alot less. It still isn't possible to remove tho, and I find that troubling, as it very often adds a dot to the watch screen making it look like you have a missed notification. Which is usually the datalayer foreground notification :/
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/52cf61ad-e72e-421f-a481-947833e54525)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/0787a4be-db5d-4558-b26d-51dc119ea255)

I have tested a few days without commit 041d0f0b to pursue @TebbeUbben claim that a notification channel is not necessary, and so far, using stock samsung galaxy watch watchface I'm still able to enact from all commands from every tile. So maybe a persistent channel isn't necessary? Would be nice if more could test this, so we don't add stuff that isn't really necessary and just is in the way of notifications you really want to see.

**Comment by vanelsberg** [comment]
> I have tested a few days without commit https://github.com/nightscout/AndroidAPS/commit/041d0f0b7bd43042dbf201f442c1a48433eb22cd

Originally had the idea disable the change based on a watch config option setting.

However, when I disable the this commit in current dev by commenting out the changes (code from the first screenshot) somehow leaves the wear app unstable in that what looks like the watchface restarting about every minute or so?
Did not get to load this into the debugger (need to figure out how to do that ... ) to see what it is doing...

**Comment by olorinmaia** [comment]
> > I have tested a few days without commit [041d0f0](https://github.com/nightscout/AndroidAPS/commit/041d0f0b7bd43042dbf201f442c1a48433eb22cd)
> 
> Originally had the idea disable the change based on a watch config option setting.
> 
> However, when I disable this commit in current dev by commenting out the changes (see code from the first screenshot) somehow this leaves the wear app unstable in that what looks like the watchface restarting about every minute or so? Did not get to load this into the debugger (need to figure out how to do that ... ) to see what it is doing...

I just deleted the lines in that commit, shouldn't matter if delete or comment out I guess, but I'm not experiencing unstable wear app. Neither with our without AAPS watchface.

**Comment by MilosKozak** [comment]
the reason why I added notification channel is that in logs were a message that communication service was killed because it didn't call startforeground. That disappeared after mentioned change. My thoughts is that complications cannot work properly without this service.
The change what started this is targeting API 29 on watch in last master version

**Comment by vanelsberg** [comment]
> the reason why I added notification channel ...

Thanks for clarifying, which would explain.
Seems solving this is not as straightforward as I anticipated.

**Comment by olorinmaia** [comment]
Please test [8cfa312](https://github.com/nightscout/AndroidAPS/commit/8cfa312c087360334d426b2ee92a2682dcf79ebb) and see if it's better now. At least for me it works great. (Samsung Galaxy watch 4)
