### ISSUE TITLE
Insulin suspended notification 

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#3149]
Last Dev

![Screenshot_20231228_182353_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/0ccbb571-2784-48ab-960f-3922e029d3d7)

A bolus is being given but a notification says insulin suspended...

![Screenshot_20231230_092006_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/4d33da6b-285a-4f60-9a65-aaefbf04b128)

![Screenshot_20231230_092003_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/355b3197-37c1-4c81-be53-cdbbd64bef8a)

Maybe related, there was a temporary 50% profile had ended (-2 min) but new profile not yet sent to the pump.

Logs. Look around 9h19

![AndroidAPS_LOG_1703924453894.log.zip](https://github.com/nightscout/AndroidAPS/files/13797540/AndroidAPS_LOG_1703924453894.log.zip)

**Comment by MilosKozak** [comment]
notification was genereated 23:47

**Comment by robertrub** [comment]
Shouldn't the notification be deleted by itself when the insulin started being given again ? It was probably a temporary message during a profile change by automation as at that time, I was surely sleeping.

**Comment by MilosKozak** [comment]
this message is not confirmed automatically

**Comment by robertrub** [comment]
Ok. Looks like something changed in the DASH driver. This message was almost never stuck (or maybe shown ??) till very recently. I only got it when pump was far from phone. 

Now, it seems to happen once a day. When I see the notification and check the DASH tab, I need to reactivate insulin distribution (but not sure if I need to do it systematically...)

Will go on observing to give more precise details.

I'm not sure if this didn't start since @Philoul corrected an untranslated message to translatable (message was _uncertain_ ). Can't see why/if it changed anything... Wild guess only ;)
