### ISSUE TITLE
No more logs

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#3151]
My last logs are dated Dec 25th. Something in the code stopped working when you installed unfinished mode.

**Comment by robertrub** [comment]
I found the screenshot of the version I had installed on the 25th in the waste basket...

![Screenshot_20231225_183747_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/78d08b26-227c-46f4-b1de-6cd94a946df0)

**Comment by MilosKozak** [comment]
with new libs version it's not possible to keep logs in `/AAPS/logs` directory and they are back in default location `/Android/data/info.nightscout.androidaps/files`
