### ISSUE TITLE
NOT working: Master Password reset (AndroidAPS 3.1.0.3, Samsung Galaxy XCover 5)

### ISSUE THREAD

**Issue by cstromblad** [nightscout/AndroidAPS#3152]
Date: 2024-01-01 11:02
Phone: Samsung Galaxy XCover 5
AAPS: 3.1.0.3, Flavor: FullRelease, buildVersion: 1de236a602 2022.08.07 12:47
Pump: Omnipod Dash

The file PasswordReset placed in /AAPS/extra, AAPS terminated (nothing), Phone restarted (nothing). Password remains set and unavailable for reset.

This can be CLOSED. Having made the jump (without exported settings) to version 3.2.0.2, password reset now worked!

**Comment by bendaaCgm** [comment]
Hi,
what type of file is it?
