### ISSUE TITLE
Steps Graph should be simplified

### ISSUE THREAD

**Issue by Philoul** [nightscout/AndroidAPS#3154]
I can't understand steps graph, with lots of overlapping on some periods

![Screenshot_20231231-151038_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/52934600/fdf7a16c-246a-4aa8-a45c-6855be3d82b0)

In above graph, I have bars close to 40 and at the same time a green bar close to 180 ?

To be able to understand graph, I think we should show for example something like "number of steps during the last minute" to avoid overlapping...

**Comment by Philoul** [comment]
additional screenshot during sport training
![Screenshot_20240108-223152_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/52934600/54ff8b39-e040-41b9-b269-116224772c8e)

HR should be smoothed but we see the increase duting training and decrease after.
Concerning steps, it's a mess...

**Comment by DM-LTR** [comment]
It would be nice to have steps in form of bar graph, the same as deviations
