### ISSUE TITLE
Dana RS: Loop gets automatically disabled/enabled

### ISSUE THREAD

**Issue by Truman1234** [nightscout/AndroidAPS#3159]
I am running the 3.2.0.2-dev version of AndroidAPS and since about a month I am facing a problem, that the loop gets automatically disabled and then reenabled from time to time.

![Screenshot_20240107-113059_AAPS](https://github.com/nightscout/AndroidAPS/assets/7819558/6cb578dd-bbae-4ed2-adfd-81b2f44059e4)

When I press the loop icon, it shows this:

![Screenshot_20240107-113111_AAPS](https://github.com/nightscout/AndroidAPS/assets/7819558/75200fd3-ab47-43cb-b89a-ee2aa982c248)

I seems, like there is a bluetooth connection problem, but when I go on the Dana RS tab in AndroidAPS, to read the stats from the pump, it connects to the pump and reads the values.

I am using a Samsung M51 for AndroidAPS, but also tested another android phone with the same result. 

Additionally, I also tried an older version of AndroidAPS, where I never had that problem, but it also shows now the same behavior.

So it seems to be a pump connection issue, but I don´t understand, why it the can easily connect to the pump, when I am reading the stats from my Dana RS via AndroidAPS

**Comment by Truman1234** [comment]
And what I forgot: The loop still seems to work, when it is in disabled mode, but on the action tab and at the bottom of the main screen all the pump related buttons are gone.

**Comment by MilosKozak** [comment]
When the pump is not initialized Loop status is set to disabled (and you don't see Calc an Insulin button as well)

**Comment by Truman1234** [comment]
So you are saying, the pump is faulty ? Or is it a software problem ?

**Comment by MilosKozak** [comment]
impossible to say from this one screenshot

**Comment by Truman1234** [comment]
What is necessary ? The log file ?

**Comment by MilosKozak** [comment]
I see what you tested so I'd expect faulty pump as first option

**Comment by Truman1234** [comment]
Ok, I will check back with the Dana representative. Thank you.
