### ISSUE TITLE
Error in dynamicISF algorithm

### ISSUE THREAD

**Issue by mordechi-david** [nightscout/AndroidAPS#3173]
In version dev3.3.0 build on 14.01.24 the dynamicISF gives an abnormal result Attached is a picture I don't find the log something strange in this version I don't have recent logs
![Screenshot_20240116-033118](https://github.com/nightscout/AndroidAPS/assets/73236490/e4c87fb0-6568-4328-bbc1-ba1b8f377a58)

**Comment by MilosKozak** [comment]
what is your dynisf factor? what it one time?

**Comment by parapenT1sta** [comment]
@mordechi-david About the logs: https://github.com/nightscout/AndroidAPS/issues/3151#issuecomment-1873488139

**Comment by parapenT1sta** [comment]
Same issue?
 https://github.com/nightscout/AndroidAPS/issues/3153

**Comment by MilosKozak** [comment]
you had to set it back to previous value manually?

**Comment by mordechi-david** [comment]
Yes, I restored it manually and it worked

**Comment by MilosKozak** [comment]
I checked the code. The code itself only reads the value. So, to modify you have to:
* either enter preferences and change it
* or import another settings
If this is not your case you phone must be malfunctioning and I'd reset it to factory setting or replace at all

**Comment by olorinmaia** [comment]
@MilosKozak It happend on my test-rig now after updating to latest dev. I haven't touched the setting ofc. attaching screenshots and logs. Can you check if there is something in the logs that can be helpful if this can be improved?

Probably around 14:00 - 14:10

[AndroidAPS_LOG_1705497291262.log.zip](https://github.com/nightscout/AndroidAPS/files/13963697/AndroidAPS_LOG_1705497291262.log.zip)

![image](https://github.com/nightscout/AndroidAPS/assets/114103483/4fdfe349-87ef-4a49-81ce-3ddb3291d33b)
![image](https://github.com/nightscout/AndroidAPS/assets/114103483/3a65e343-543d-4e49-864d-3b5a35e9c70b)

**Comment by mordechi-david** [comment]
@MilosKozak I did change the preferences and it works fine
The only question is how it changed to 0 without me touching it

**Comment by MilosKozak** [comment]
app was started at 14:08 and then restarted 
first run was already wrong
last run during night was ok
somthing happened between

**Comment by idalioreis** [comment]
i think the dynamicISF factor is by default 0%, so cause this error, if update to value that i define it works.

**Comment by olorinmaia** [comment]
> i think the dynamicISF factor is by default 0%, so cause this error, if update to value that i define it works.

default value is 100

`ApsDynIsfAdjustmentFactor(R.string.key_dynamic_isf_adjustment_factor, 100, 1, 300),`

**Comment by idalioreis** [comment]
> > i think the dynamicISF factor is by default 0%, so cause this error, if update to value that i define it works.
> 
> default value is 100
> 
> `ApsDynIsfAdjustmentFactor(R.string.key_dynamic_isf_adjustment_factor, 100, 1, 300),`

i understand, but i never change this value, only choose dynamicISF and was 0%.  

i put 100% after, and work fine.

**Comment by szantos** [comment]
I've entered preferences to check the value (did not edit it), and it was zero. I've set it back to the normal value, but 1 loop run was affected, and I had a similar high ISF. Unable to provide logs.

**Comment by MilosKozak** [comment]
what was the value before?

**Comment by szantos** [comment]
80

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/bc0eac0eb4900c401753cd514f3d2ea683e6de69
