### ISSUE TITLE
Advanced parameters everywhere in settings 

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#3191]
![Screenshot_20240126_104919_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/365ce6f2-803e-43c3-becd-6fa0f09df02c)

![Screenshot_20240126_104950_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/fd0c0926-db7d-426e-a828-3d8e22446690)

Is it normal to have "advanced parameters" everywhere? If I recall correctly, this was not the case before dev-a

**Comment by MilosKozak** [comment]
android handles this. 
but it's not so off in this case (even it's not what we want) because you get more options when you expand it
