### ISSUE TITLE
Dev 3.30 latest DynISF error with activation

### ISSUE THREAD

**Issue by lostboy86** [nightscout/AndroidAPS#3192]
[AndroidAPS_LOG_1706264093742.log.zip](https://github.com/nightscout/AndroidAPS/files/14064334/AndroidAPS_LOG_1706264093742.log.zip)
![immagine](https://github.com/nightscout/AndroidAPS/assets/39415490/3c767511-3e0f-4795-948d-2089d1940863)

**Comment by MilosKozak** [comment]
give me screenshots of your profile's isf

**Comment by lostboy86** [comment]
Attach here the screenshots

Il ven 26 gen 2024, 13:27 Milos Kozak ***@***.***> ha scritto:

**Comment by MilosKozak** [comment]
nothing is visible. add it on web

**Comment by lostboy86** [comment]
![d2ca1bb9-177b-496d-8631-d8a74813b7c5](https://github.com/nightscout/AndroidAPS/assets/39415490/54b82604-4aa6-4e65-aa98-40133ce5fe74)
![698ddd26-4ac8-40f0-b9bf-5e24a36ea2b7](https://github.com/nightscout/AndroidAPS/assets/39415490/8bcad678-b45f-4937-aa67-d9497eda694f)

**Comment by MilosKozak** [comment]
at what action this message appeared? is it replicable?

**Comment by lostboy86** [comment]
I'm only turn on the DynISF on latest dev.

The banner appears a few moments after, then repeat itself

Il dom 28 gen 2024, 09:53 Milos Kozak ***@***.***> ha scritto:

**Comment by MilosKozak** [comment]
hmmm no data in logs. set logging levels to default and post new logs with timestamp

**Comment by lostboy86** [comment]
How i can set logging levels to default?

Il lun 29 gen 2024, 17:11 Milos Kozak ***@***.***> ha scritto:

**Comment by MilosKozak** [comment]
there is a button on page where you set it

**Comment by lostboy86** [comment]
On settings log, i have all checked.

Il lun 29 gen 2024, 17:43 Milos Kozak ***@***.***> ha scritto:

**Comment by lostboy86** [comment]
[AndroidAPS_LOG_1706547426289.log.zip](https://github.com/nightscout/AndroidAPS/files/14088184/AndroidAPS_LOG_1706547426289.log.zip)

**Comment by MilosKozak** [comment]
can be resolved by removing APS resuts

**Comment by lostboy86** [comment]
Sorry, how i can resolve?
The issues it's in the graph scale of IC, ISF, Basal.
DIA scale graph it's resolved.

Il giorno ven 2 feb 2024 alle ore 10:32 Milos Kozak <
***@***.***> ha scritto:
