### ISSUE TITLE
Error bolus Calculator on latest dev 3.30 take IC /ISF on inexistent profiles Active

### ISSUE THREAD

**Issue by lostboy86** [nightscout/AndroidAPS#3193]
I have only one profile named "FIASP" on nightscout and aaps latest dev.
When i launch the Bolus Calc, if i not select manually FIASP, takes value from not existent profile named Active, with IC and ISF different from mine.

No Autotune profiles, no DynamicISF active.

Pay attention, with this bug many people can rise BG or experiment dangerous low BG.

![photo_5881917511434354581_y](https://github.com/nightscout/AndroidAPS/assets/39415490/a329be57-548d-4d84-8e1e-bd00a032b0aa)
![photo_5881917511434354583_y](https://github.com/nightscout/AndroidAPS/assets/39415490/86eedee2-65bb-4c52-a90f-040e46a84812)
![photo_5881917511434354582_y](https://github.com/nightscout/AndroidAPS/assets/39415490/e6abee0c-de70-4ad9-8d0f-9197825b6950)

**Comment by robertrub** [comment]
Strange. I don't have your problem. <Active> and my active profile give the same numbers. Using latest dev-A.

![Screenshot_20240126_104919_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/26cad149-9940-43aa-8233-a1d746a89e59)

Can you stop all downloads from NS and reactivate your profile in APPS. Then check again if you have the same problem.

**Comment by lostboy86** [comment]
Yes i try now, also NS not had previous the Active Profiles, i have only
FIASP on ns and aps.

How i can delete the Active Profiles wrong?

Il giorno sab 27 gen 2024 alle ore 07:00 Robrub ***@***.***>
ha scritto:

**Comment by lostboy86** [comment]
Now another user report to the FB group AAPS USERS same situation : 

[https://www.facebook.com/photo?fbid=3647468725537482&set=gm.3706718732882850&idorvanity=1900195340201874](url)

**Comment by robertrub** [comment]
There is no profile named _Active_ . I'm almost sur that the profile download from NS creates the bug.

In AAPS settings, stop all downloads **from** NS. Keep only the uploads **to** NS.

Create a new profile with a new name in AAPS. Manually, copy the settings from your _FIASP_ profile to the new one. Activate the new profile.

Delete the _FIASP_ profile.

Check if you stil have the bug (difference between _Actual_ and _New_ profile when you use the bolus calculator.

**Comment by lostboy86** [comment]
I also try this option.
Same bug.

BUT i found a strange solution.
If i deactivated autotune circadian on-off, automation profile change
on-off, now Active show same Value on calc from Fiasp.

Pay attention : above, in the post of fb user on aaps users, she had same
issue but with the latest master.
The master don't have obv autotune inside the app, like the dev.

In the previous version,i have no difference from active to my profiles, in
bolus calc.

Il giorno sab 27 gen 2024 alle ore 15:14 Robrub ***@***.***>
ha scritto:

**Comment by MilosKozak** [comment]
I see on the backgroud screen  yellow background on profile name => you are running % change on profile. thus different values

**Comment by lostboy86** [comment]
Thank you very much for help question!

Il dom 11 feb 2024, 15:48 Milos Kozak ***@***.***> ha scritto:
