### ISSUE TITLE
DASH : No more 50+U

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#3194]
Dev A (or maybe since Dev 3.3). We lost the + sign after 50 when the DASH pod has over 50U left

![Screenshot_20240127_064302_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/c7b3b19d-5087-42d0-9409-ee50ce79cebf)

![Screenshot_20240127_064520_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/b31b773e-59be-4dfa-a319-8f076740bf5c)

This capture is from v3.1

![Screenshot_20240127_064701_Discord.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/54b1831a-7a65-4098-81c1-5f3e061cafca)

**Comment by m4nnihuber** [comment]
This is also seen on master 3.2.0.3 with Omnipod Dash
