### ISSUE TITLE
3.3 Dev-A : Widget shows ISF ??

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#3196]
Last Dev. I have a "normal" AutoSens information on the AAPS UI but a strange information on the AAPS widget. It is as if it was showing an ISF change but I don't use _Variable sensitivity_ or DynISF.

![Screenshot_20240126_104919_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/2af40730-38fa-4e1e-a78e-6fcf24ec2c86)

![Screenshot_20240127_151804_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/62c69ef0-ef2d-433f-884c-c61e8cbb4ef3)

![Screenshot_20240127_151842_One UI Home.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/b42e2c14-3a4f-47dd-8456-dc7a0c6d7be7)

**Comment by vanelsberg** [comment]
Confirming!

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/aa13cff67ea9c4ece56f3a4051711ee561b03daf
