### ISSUE TITLE
No profile set

### ISSUE THREAD

**Issue by xLimzy** [nightscout/AndroidAPS#3200]
Hello! Just built the new version of Andriod Aps and imported my settings- but nothing is coming through- please help I've been without the closed loop for hours

**Comment by lostboy86** [comment]
After import prefs and settings, have you stopped and reopen the app?

**Comment by xLimzy** [comment]
Yes, I actually just noticed that on nightscout I am getting  "status: not loaded". No data there...?

Sincerely,

Lisa Coladonato 
 
  On Sun, Jan 28, 2024 at 2:35 AM, ***@***.***> wrote:   


After import prefs and settings, have you stopped and reopen the app?

**Comment by xLimzy** [comment]
Sorry, my nightscout is back up and running but my settings still haven't come through. Does exports from a different version transfer to updated versions?

Sincerely,

Lisa Coladonato 
 
  On Sun, Jan 28, 2024 at 2:37 AM, ***@***.******@***.***> wrote:   Yes, I actually just noticed that on nightscout I am getting  "status: not loaded". No data there...?

Sincerely,

Lisa Coladonato 
 
  On Sun, Jan 28, 2024 at 2:35 AM, ***@***.***> wrote:   


After import prefs and settings, have you stopped and reopen the app?

**Comment by xLimzy** [comment]
Yes, nothing is coming through. Can exports from previous versions import to updated versions?

**Comment by MilosKozak** [comment]
what do you see on nsclient tab?

**Comment by lostboy86** [comment]
Nsclient From APS?

Il lun 29 gen 2024, 13:06 Milos Kozak ***@***.***> ha scritto:

**Comment by MilosKozak** [comment]
closed for inactivity
