### ISSUE TITLE
Graphs of ISF, BASAL, IC, and DIA minor bug

### ISSUE THREAD

**Issue by lostboy86** [nightscout/AndroidAPS#3201]
All graphs present a bug on the label for Hours, especially the DIA for 9 hours.

![photo_1_2024-01-28_11-44-02](https://github.com/nightscout/AndroidAPS/assets/39415490/fc09526d-c789-4ee0-8a9c-bb347ff485a4)
![photo_2_2024-01-28_11-44-02](https://github.com/nightscout/AndroidAPS/assets/39415490/0650d7ff-3e52-4cf5-8d01-e04ef2de99b0)

**Comment by MilosKozak** [comment]
improved here https://github.com/nightscout/AndroidAPS/commit/7e7f04b57e799abaa8d2166deddf8d72e995cf2c

**Comment by lostboy86** [comment]
Not fixed for IC, BASAL, ISF in the lastest dev.
DIA fixed in the latest dev.
