### ISSUE TITLE
Graph not updated after removing invalid BG value

### ISSUE THREAD

**Issue by TimVroom** [nightscout/AndroidAPS#3211]
After receiving an invalid BG value from xdrip (was during sensor switch) I removed it from the xdrip+ BG list.
It resulted in the displayed graph being too high:
![Screenshot_20240203-083912.png](https://github.com/nightscout/AndroidAPS/assets/800147/aac976f3-d2d3-4069-9c4d-e7dce9222c47)

The invalid value compared to the screenshot was at 15.15.35 the previous day. I have this value still in xdrip. But doesn't show up in nightscout.

This was still the case after 12 hours when graph scale was set to 6 hours.
It seems that when removing the invalid BG value from AAPS the height is not properly recalculated.

I rebooted my phone after about 18 hours and then it's calculated properly. Even when looking at the 24 hour graph.

Current version: 3.2.0.3

![AndroidAPS_LOG_1706957137579.log.zip](https://github.com/nightscout/AndroidAPS/files/14151122/AndroidAPS_LOG_1706957137579.log.zip)

Edit: extra image from xdrip:
![Screenshot_20240204-115723.png](https://github.com/nightscout/AndroidAPS/assets/800147/3b46c8ac-f1b8-4544-8225-764cb44b1447)

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/90c297639f38cf9823c7ea99c237a97ba95bc680
