### ISSUE TITLE
Medtrum preferences close

### ISSUE THREAD

**Issue by TT83TT** [nightscout/AndroidAPS#3213]
With the Medtrum Nano pump, latest version Dev 3.3.0, preferences close the Aaps application

https://github.com/nightscout/AndroidAPS/assets/28483752/5c153583-624e-48fd-9c11-69e6e2fd1c83

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://wiki.aaps.app/en/latest/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

https://github.com/nightscout/AndroidAPS/assets/28483752/20d83a24-9473-4674-a23b-882f1f7a6d37

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/b7a6fbf099967272fc64736bc4cdf5151cdf3a31
