### ISSUE TITLE
Red Color of Values

### ISSUE THREAD

**Issue by Duester64** [nightscout/AndroidAPS#3214]
Ver. 3.3.0-dev-a

On Home screen and AKT the values of Sensor, Insulin, Canula and Battery are shown in red color even they are in range. In the former versions of AAPS they have been shown in white as long as there were in the given range. Only on case of limit violations they turned red. 

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://wiki.aaps.app/en/latest/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
provide screenshot of setting and real state. for me it does work

**Comment by Duester64** [comment]
Hi Milos,

 

please see the pics attached.

 

Before it was very good. You could catch very convenient if something was wrong when the color turned red. If everything was white means all values are fine.

 

I’m not sure if the color changed to yellow before to give a warning.

 

Why this good system was changed?

 

Thanks a lot for your attention.

 

Regards

Frank

 

Von: Milos Kozak ***@***.***> 
Gesendet: Dienstag, 6. Februar 2024 18:50
An: nightscout/AndroidAPS ***@***.***>
Cc: Duester64 ***@***.***>; Author ***@***.***>
Betreff: Re: [nightscout/AndroidAPS] Red Color of Values (Issue #3214)

 

provide screenshot of setting and real state. for me it does work

**Comment by MilosKozak** [comment]
pictures are not visible. attach them on web site

**Comment by Duester64** [comment]
![Screenshot 2024-02-06 212510](https://github.com/nightscout/AndroidAPS/assets/61905746/385c1b88-2b41-49ea-8278-0ca9aea2980d)
![Screenshot 2024-02-06 212434](https://github.com/nightscout/AndroidAPS/assets/61905746/e6a0018d-f52d-4a6c-8525-d6f395515f0b)

**Comment by MilosKozak** [comment]
and your setting from preferences?

**Comment by Duester64** [comment]
What preferences do you mean. Is there an option to change colors?

**Comment by parapenT1sta** [comment]
Preferences > Overview > Status Light

![Screenshot_20240209_202019_AAPS](https://github.com/nightscout/AndroidAPS/assets/608650/c7ff109c-50bc-4af7-914d-a5693e911f45)

**Comment by Duester64** [comment]
That was it. Thanks a lot.

**Comment by parapenT1sta** [comment]
Close this issue if it is fixed.
