### ISSUE TITLE
Error Historical graph scale view

### ISSUE THREAD

**Issue by lostboy86** [nightscout/AndroidAPS#3217]
![Immagine WhatsApp 2024-02-08 ore 08 50 39_5443ea6a](https://github.com/nightscout/AndroidAPS/assets/39415490/bc2af6ca-7574-45ad-9060-3df22dd2cea0)

This happens for every part of the days, for every view type, randomly.

**Comment by MilosKozak** [comment]
it's a bug in library

**Comment by MilosKozak** [comment]
duplicate to https://github.com/nightscout/AndroidAPS/issues/2854
