### ISSUE TITLE
Can't connect to the internet from DiaKEM G7 Decom patches apps

### ISSUE THREAD

**Issue by jedih123** [nightscout/AndroidAPS#3220]
I don't know if it's the new Samsung OS version but with my S22 OS version 14. Or because I'm from Canada or if I doing soemthing wrong.

When installing the DiaKEM Decom G7 patches apps, after enter my accoutn nfo, I can't connect to the internet using this version or even the BYODDecom G7 version, I can't pass the autenticated as a result not able to connect to the internet

I tried to connect using mobile phone data and WIFI and still can't connect to internet from this apps when log in,other apps such as TikTok, Internet browser, email YouTube videos facebook and other apps can access the internet but not this DiaKEM Dexcom G7 apps patches.

Original Dexcom G7 apps work perfectly but not this one

The G7s are available since October in Canada and the close loop too but it doesn't work due to this problem with this patches apps to we have to used for AAPS close loop.

The only way I can make it work wth AAPS is by using Xdrip, but I would like to use DiaKEM Dexcom G7 patches version with AAPS instead.
Can someone align me with what I shoudl do next or have a look at it?

Thanks

**Comment by MilosKozak** [comment]
This is not AAPS bug. Go to Diakem support or ask in AAPS FB group
