### ISSUE TITLE
Erased treatments are not erased from nightscout

### ISSUE THREAD

**Issue by yhonatanb20** [nightscout/AndroidAPS#3221]
Perhaps this is a known issue, reporting anyway:
I often prebolus (i.e. set carb time >0), and if for some reason (e.g., bg rising) I have to delay my meal, I simply erase the old carb entry (via treatments) and assign a new one at the relevant time. The old entry indeed gets erased from AAPS but persists in nightscout, which results in wrong total carb reporting (i.e., double entry). I can speculate that this is the case with any other deleted treatments as well.

**Comment by MilosKozak** [comment]
NS doesn't reflect `isValid` property. At least for now. It should be properly displayed in AAPS client
