### ISSUE TITLE
invalid pump history data detected. Open new issue and email log

### ISSUE THREAD

**Issue by alnassermahrouqi** [nightscout/AndroidAPS#3223]
![426392756_7639811069375841_4553554406002180877_n](https://github.com/nightscout/AndroidAPS/assets/160229502/a526f24e-1850-4810-b35e-86b9619305c0)

Had this error yesterday. I'm not sure what it means. My logs will be sent by email

**Comment by MilosKozak** [comment]
you sent the logs too late (it contains only vere recent data).
Are you able to locate logs from mentioned time?

**Comment by alnassermahrouqi** [comment]
I don't know if I can. I'll be on the look out if it happens again and submit a ticket and logs immediately. 

Al Nasser Al Mahrouqi 
 
  On Fri, Feb 16, 2024 at 15:21, Milos ***@***.***> wrote:   


you sent the logs too late (it contains only vere recent data).
Are you able to locate logs from mentioned time?

**Comment by alnassermahrouqi** [comment]
I have resent the logs as quickly as I could, ill update the email with the request number

**Comment by MilosKozak** [comment]
I didn't found the message in any of logs you sent

**Comment by alnassermahrouqi** [comment]
Even in today's log? I mistakenly mentioned in my last log submission it happened at 3pm but it was 1pm

Al Nasser Al Mahrouqi 
 
  On Wed, Feb 21, 2024 at 0:47, Milos ***@***.***> wrote:   


I didn't found the message in any of logs you sent

**Comment by alnassermahrouqi** [comment]
1 31pm specifically. 

Al Nasser Al Mahrouqi 
 
  On Wed, Feb 21, 2024 at 1:06, Alnasser ***@***.***> wrote:   Even in today's log? I mistakenly mentioned in my last log submission it happened at 3pm but it was 1pm

Al Nasser Al Mahrouqi 
 
  On Wed, Feb 21, 2024 at 0:47, Milos ***@***.***> wrote:   


I didn't found the message in any of logs you sent
