### ISSUE TITLE
Duplicate IOB, COB and in treatments

### ISSUE THREAD

**Issue by gh4tf** [nightscout/AndroidAPS#3224]
At 07:28 this morning, I gave 1u and announced 10g using the calculator. It definitely only gave 1u, but the treatments show 1u and 10g have been given twice and 2u and 20g were added to the IOB and COB respectively, although only 1u and 10g are showing on the graph.

Using v 3.2.0.2.

It is the first time we've noticed it.  It appears to have been fine since.  We're just concerned because we use SMS commands for our daughter when she's at school and if this happens again, AAPS may think she has double COB and give lots of SMBs, but also think she has more IOB than she does and hold off giving insulin.

I've located the log files under Maintenance, but is it too late to send them now?  If not, how do I send them please? There's a button to send them by email, but I didn't know if it sends them automatically when hitting that button, or if I need an email address.

Thanks in advance!
![calc](https://github.com/nightscout/AndroidAPS/assets/68807070/9f5e0f97-d68a-42d7-b2d9-0683695ff9ab)
![graph](https://github.com/nightscout/AndroidAPS/assets/68807070/a2d0b324-9d95-4c59-aff3-743f9188e65d)
![treatments](https://github.com/nightscout/AndroidAPS/assets/68807070/b8748e28-e880-4bc2-9c65-f30eb44676d3)

**Comment by MilosKozak** [comment]
Send email works only when you use just after the issue appeared
Use this https://androidaps.readthedocs.io/en/latest/Usage/Accessing-logfiles.html to locate proper log from time of issue and add it here

**Comment by gh4tf** [comment]
Thanks for replying Milos.

The duplicates occurred at 07:28.

The link you posted says to upload the file dated before the error occurred.  There is one zip file modified at 04:36 and the next one is at 7:38.  Should I unzip the one modified at 04:36 because this is before the error occurred, or the one from 07:38 please?

**Comment by MilosKozak** [comment]
You can drop the zip here directly. Just verify wanted data is there
I need logs from some time before and after

**Comment by gh4tf** [comment]
Thanks Milos.

Unfortunately, the earliest date showing in the logs now is the 17th February and it happened on the 16th :-(

**Comment by MilosKozak** [comment]
create new issue with logs if you notice it again
