### ISSUE TITLE
AutoSens tuned ON even with settings bring OFF

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#3235]
I turned OFF AutoSens in the settings but it keeps going above 100%. Is there something I did wrong or is there a bug ?

![Screenshot_20240223_201145_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/bb13622d-ed0f-421d-9712-dce1b226d420)

![Screenshot_20240223_221403_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/5fb90f45-723b-49c8-a85e-f6af6293660a)

![Screenshot_20240201_174706_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/c01d6801-aecf-483d-b9d4-a40a6b8c09da)

**Comment by olorinmaia** [comment]
There was a bug earlier, with Autosens not showing in options. If you update to latest dev you will be able to see both Autosens and DynISF-"Sens" (if Dynamic sensitivity is enabled).

**Comment by MilosKozak** [comment]
check it on latest dev
