### ISSUE TITLE
Glucose graph sometimes shows pale green dots, couple hours later those entries are normal dots

### ISSUE THREAD

**Issue by ConstantinMatheis** [nightscout/AndroidAPS#3245]
Screenshot with some pale green dots, e.g. at 04:38 also an SMB was given at such a time:
![Screenshot_20240228-075145](https://github.com/nightscout/AndroidAPS/assets/26505965/5da0bd6a-51a9-43a2-86da-f282caa97362)

A couple hours later all the pale green dots switched to normal dots:
![Screenshot_20240228-123543](https://github.com/nightscout/AndroidAPS/assets/26505965/4ba9eae7-ff0f-461d-9494-d7c1e5928fe2)

Everything seems to work normally, but it doesn't seem right that the dots switch color.

Setup when the issue occurred:
* AAPS Version 3.2.0.3
* G7 connected directly to xDrip (nightly xDrip-plus-20240220-d52fc70.apk)

I noticed the issue after I changed my setup, not sure which of those things triggered the issue:
* switched phone
* updated AAPS from 3.2.0.2 to 3.2.0.3
* switched from DiaKEM G7 App to xDrip

At first I thought it's some battery saving stuff from the new phone, but I'm not sure anymore, since sometimes SMBs are given at the time of the pale green dots (which I think wouldn't happen if one of the apps was suppressed by battery savings?).

I already updated to AAPS 3.2.0.4, so far I didn't notice it again.

**Comment by MilosKozak** [comment]
It indicates there are gaps in glucose reception which are back filled sometimes later
