### ISSUE TITLE
Xdrip sync plugin starts repeatly (every few hours) fullsync between pumpcontrol and xdrip

### ISSUE THREAD

**Issue by maskac** [nightscout/AndroidAPS#3247]
Xdrip last nightbuild
virtualpump
BYODA G6 as source BG
Xdrip hw source: xdrip follower

Pumpcontrol 3.2.0.3
Build: bb1a276078-2023.12.17
Verze Nightscoutu: 15.0.2

[AndroidAPS_LOG_1709322758182.log.zip](https://github.com/nightscout/AndroidAPS/files/14466983/AndroidAPS_LOG_1709322758182.log.zip)
[AndroidAPS_LOG_1709323258734.log.zip](https://github.com/nightscout/AndroidAPS/files/14466985/AndroidAPS_LOG_1709323258734.log.zip)

**Comment by MilosKozak** [comment]
It's probably db issue. I don't see any reason for such behavior and unable to replicate it. I'd recommend database reset

**Comment by maskac** [comment]
Same issue few hours after DB reset :( 

[AndroidAPS_LOG_1709751815122.log.zip](https://github.com/nightscout/AndroidAPS/files/14514599/AndroidAPS_LOG_1709751815122.log.zip)
