### ISSUE TITLE
TDD not correct

### ISSUE THREAD

**Issue by bertroode** [nightscout/AndroidAPS#3260]
Hi,
On march 9 I tried to invoke Dynamic ISF but then AAPS was switched back to OpenAPsAMA. To correct the problem I imported the reference settings to get back to the last known good. Subsequently I finished the objectives needed.
Today I noticed however that the TDD report is wrong sing march 9. See enclosed
![Screenshot_20240311_091201_AAPS](https://github.com/nightscout/AndroidAPS/assets/3540901/bbc74d61-bac0-4bf9-96fd-29f8ab5ceed2)\

AAPS 3.2.0.3
build bb1a276078-2023.12.19

When you need any further information, please give me a message.

Best regards and thank for all the effort in impriving AAPS

Bert roode

**Comment by MilosKozak** [comment]
This is not enough info to provide any opinion
BTW: you can reset precalculated TDD on Stats page

**Comment by bertroode** [comment]
The information on the Stats page is the same as the data in my pump.

**Comment by MilosKozak** [comment]
what pump is it?

**Comment by MilosKozak** [comment]
closed for inactivity
