### ISSUE TITLE
AAPS 3.2.0.4 ComboV2 status tab unreadable in daytime display mode

### ISSUE THREAD

**Issue by NicoAAPS** [nightscout/AndroidAPS#3263]
### AAPS version
3.2.0.4 
build  5d3e33ce8a
flavor fullrelease

### hardware and software
Samsung Galaxy A13 5G  - Android 14 - oneUI  6.0

### problem description

In daytime screen mode the status tab of the combo v2 has white text on white background, which makes it rather unreadable
Changing to night mode changes the screen into white text on black background which is quite readable.

### See attached screen shots
![Screenshot_20240312_091016_AAPS](https://github.com/nightscout/AndroidAPS/assets/126802516/48fa417e-9f6a-4809-93e7-52347ed0e648)
![Screenshot_20240312_090955_AAPS](https://github.com/nightscout/AndroidAPS/assets/126802516/124b9f0c-67fb-4edc-80ee-7984b83d2daa)

**Comment by MilosKozak** [comment]
this is already fixed in dev
https://github.com/nightscout/AndroidAPS/pull/3258

**Comment by MilosKozak** [comment]
just notice there will be only combo v2 driver in AAPS 3.3
