### ISSUE TITLE
Enable SMB always while using xdrip in companion app mode and dexcom g7 original app

### ISSUE THREAD

**Issue by Pentagit** [nightscout/AndroidAPS#3266]
When using xdrip (latest nightly) in companion app mode fetching bg values from dexcom g7 app, aaps (3.2.0.3) still won't allow SMB to be enabled always. Please fix so that g7 users can use latest dexcom g7 app including clarity and still have hcl/fcl possibility in aaps.

**Comment by jbr7rr** [comment]
Problem is that xDrip doesn't send which sensor the data comes from in companion app mode., so AAPS can't determine if it is data from G7 or e.g. a medtronic sensor
So we need this information from xDrip when we want to enable it for ONE/G7 companion mode, I suggest you open a discussion/issue over at xDrip as well.

**Comment by Pentagit** [comment]
Thank you. I understand and will do that.
Though, why isn't AAPS enabling SMB always no matter which BG source xdrip is using?
AFAIK, xDrip companion mode is available for the following vendor apps:
G6 (master only)
One (only if the app shows BG notifications)
G7 (master only)
CamAPS
Guardian
MiniMed
Omnipod 5 app

Is any one of these apps a problem for always SMB in AAPS or why can't AAPS just enable it for the xdrip companion mode? But perhaps I'm misunderstanding something :)

**Comment by jbr7rr** [comment]
> Though, why isn't AAPS enabling SMB always no matter which BG source xdrip is using? AFAIK, xDrip companion mode is available for the following vendor apps: G6 (master only) One (only if the app shows BG notifications) G7 (master only) CamAPS Guardian MiniMed Omnipod 5 app

For Dexcom we know that they have good filtering, meaning that when there are erroneous values the sensor/transmitter doesn't send them

**Comment by Pentagit** [comment]
Why no mandatory smoothing (average/exponential) then when using xdrip companion data?

**Comment by jbr7rr** [comment]
> Why no mandatory smoothing (average/exponential) then when using xdrip companion data?

Dexcom does error detection, meaning it will not send data when there are erroneous values., with smoothing only there will still be a datapoint on the erroneous value, which can lead to wrong dosing. But this is already being discussed in other issues as well:
https://github.com/nightscout/AndroidAPS/issues/3181
https://github.com/nightscout/AndroidAPS/issues/2121

**Comment by MilosKozak** [comment]
Can anyone provide current state?

**Comment by Pentagit** [comment]
Xdrip in companion mode still leads to

**Comment by Pentagit** [comment]
I updated my AAPS app with androidstudio (fetch/pull/generate signed etc.) but somehow its the same build number just with a newer date:
Build: 3df83535f9-2024.11.16

Anyway it still does not work. 
Still: "Safety: SMB always and after carbs disabled because active BG source doesn't support advanced filtering." When chosing xdrip as bg source while xdrip getting values from dexcom app via companion mode .
