### ISSUE TITLE
[Medtrum Nano]: BT -> Connection timed out

### ISSUE THREAD

**Issue by dar-kod** [nightscout/AndroidAPS#3268]
I started trying Medtrum Nano on 14 March at 18:52. I activated my first test patch and tried to give a bolus, but there was no connection for a long time. If I remember correctly, there was a "pump unreachable" notification. I restarted AAPS with Exit. That didn't help either. After about 10 minutes of waiting, a connection was made. But after about half an hour, the Medtrum took a few minutes to connect. I have used Dash before without any problems. I have a small problem with the Anubis transmitter, which often doesn't connect for 10-20 minutes, even when the phone is near me. It appears that disabling power optimization specifically for the Bluetooth system service on OnePlus devices is not directly possible through the standard user interface.

After that, the connection is usually established within 2 seconds. But sometimes, after receiving the BG reading, I see that it has been trying to connect for 120 seconds and still hasn't connected. With Dash, if I remember correctly, it always connected within 2 seconds or sometimes a little longer.

On 17 March at 1:56 and 2:05, I got "Connection timed out". I tried to give a small bolus 2 times with the message pump unreachable. It reconnected after I clicked on the three dots to exit. After a disconnection at 2:05, it didn't reconnect after the first exit but after the second. This is getting annoying.

AAPS version: AAPS 3.3.0-dev
Build: f2166ec366-2024.03.15
Phone: OnePlus 12
OS: OxygenOS 14.0
Bluetooth: 5.4, A2DP, LE, aptX HD, LHDC
Nano battery: 2.82 V

Whole log folder is zipped and attached.

[AAPS log files.zip](https://github.com/nightscout/AndroidAPS/files/14627504/AAPS.log.files.zip)

**Comment by jbr7rr** [comment]
Thx for reporting, unfortunately the logs don't contain the time period of the connection issues, and no errors in the logs provided.

@MilosKozak Can we increase the log size? compared to master, dev logs are tiny

Can you setup the logs in the following manner, and upload logs when it happens again?
![WhatsApp Image 2024-03-17 at 19 49 21](https://github.com/nightscout/AndroidAPS/assets/60566713/7a57a4fc-f2e3-4984-ae7c-d416950d4db6)

**Comment by MilosKozak** [comment]
I didn't touch the size of logs

**Comment by jbr7rr** [comment]
@dar-kod Can you test with https://github.com/nightscout/AndroidAPS/pull/3270 ?

Can you let it run for a couple of days and see if it fixes it? After that pls report back and send logs

**Comment by dar-kod** [comment]
Thank you @jbr7rr. I started testing with #3270 at 23:47 the day before. No disconnects so far.

**Comment by dar-kod** [comment]
@jbr7rr There have been no BT problems so far. I have yet to test if there will be when I apply a new patch. 

I have something strange and I am not sure if it is related to BT. When the bolus is visible in the progress bar, when I click stop it says "failed": "Bolus reported an error. Manually check real delivered amount". I have tried stopping 2 times today (15:42 and 17:35) and both times it was like this.

[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/14704626/AndroidAPS.log)

**Comment by jbr7rr** [comment]
> @jbr7rr There have been no BT problems so far. I have yet to test if there will be when I apply a new patch.
> 
> I have something strange and I am not sure if it is related to BT. When the bolus is visible in the progress bar, when I click stop it says "failed": "Bolus reported an error. Manually check real delivered amount". I have tried stopping 2 times today (15:42 and 17:35) and both times it was like this.
> 
> [AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/14704626/AndroidAPS.log)

This is expected behaviour when you cancel bolus

**Comment by jbr7rr** [comment]
Merged in dev, can be closed imo. If you thing cancel bolus should not give a error please open new issue

**Comment by fjpezuela** [comment]
Hello,

I have a OnePlus 10 Pro with Android 15 and I've had the same problem discussed in this thread with version 3.3.3.0-dev-d.

I tried two Medtrum patches, and the connection was successful, allowing me to place a bolus immediately afterward. Subsequently, the phone stopped connecting to the pump. I tried restarting the phone, restarting AAPS, turning Bluetooth on and off, etc., without success.

I thought it was a problem with the base station, but I tried connecting it to another phone with version 3.2.0.4 and Android 10, and it connects and works without problems.

In three days, I can test the Medtrum again with a different patch and upload the logs, in case it can be resolved.

The strangest thing is that even though AAPS wouldn't connect to the pump, if I went to the option to discard the patch or activate a new one, I could do so without problems, with the same failure occurring after the initial pairing.

**Comment by dar-kod** [comment]
@fjpezuela In the Medtrum settings, you will see "Advanced Settings" at the bottom. Turn ON "Scan on connection error."

**Comment by fjpezuela** [comment]
> [@fjpezuela](https://github.com/fjpezuela) In the Medtrum settings, you will see "Advanced Settings" at the bottom. Turn ON "Scan on connection error."

Yes, I tried that option too, without success. I tried several times with both patches and it still wouldn't connect.

**Comment by fjpezuela** [comment]
> [@fjpezuela](https://github.com/fjpezuela) In the Medtrum settings, you will see "Advanced Settings" at the bottom. Turn ON "Scan on connection error."

AAPS 3.3.3.0-dev-d
Build: 5276a23d84-2025.12.04
Remote: https://github.com/nightscout/AndroidAPS
Flavor: fullrelease
Versión de Nightscout: UNKNOWN
Modo de ingeniería activado

I started the change around 12:25 PM.
Patch activated at 12:28 PM.
First 0.05U bolus successful.
No more BT connections between phone and patch.

![Image](https://github.com/user-attachments/assets/1cbeac4b-05f0-4746-a50b-003e32ad76d9)
![Image](https://github.com/user-attachments/assets/d844c3ba-e4dc-4bad-978f-b25e360f6b9d)
![Image](https://github.com/user-attachments/assets/e8b07a99-275a-4acf-9fc6-3bd5e611f6f5)

[AndroidAPS_LOG_1764934481029.log.zip](https://github.com/user-attachments/files/23960438/AndroidAPS_LOG_1764934481029.log.zip)

**Comment by fjpezuela** [comment]
@jbr7rr I'm adding new logs, from the first 30 minutes since the connection and the first unreachable pump error.

[AndroidAPS_LOG_1764935962652.log.zip](https://github.com/user-attachments/files/23960749/AndroidAPS_LOG_1764935962652.log.zip)

![Image](https://github.com/user-attachments/assets/a3333db0-e234-4daa-b911-cf108a7a3ad4)
![Image](https://github.com/user-attachments/assets/bf0e31e6-3910-4f9a-8ed8-abd0b0cb9665)
