### ISSUE TITLE
AAPS 3.3.0-dev-b crashes when trying to use quick wizzard

### ISSUE THREAD

**Issue by cr582** [nightscout/AndroidAPS#3278]
AAPS 3.3.0-dev-b crashes immediately as soon as you try to open the quick wizard.

**Comment by cr582** [comment]
[AndroidAPS_LOG_1711366700050.log.zip](https://github.com/nightscout/AndroidAPS/files/14742840/AndroidAPS_LOG_1711366700050.log.zip)

**Comment by Philoul** [comment]
I used quickwizard on my side to test it on latest dev without any crashes (within my dev configuration with android v11, Insight pump)

**Comment by cr582** [comment]
I just double checked and deleted the old project, cloned it once again and made a clean build. AAPS immediately crashes as soon as I choose quick wizard. Samsung Galaxy S20 FE 5G Android 13

**Comment by olorinmaia** [comment]
Can you try to go to settings > quick wizard > delete old QW ?

Add new QW and see if that helps? As a workaround.

**Comment by cr582** [comment]
deleting the old QW entries and create new QW buttons did help indeed. thx

**Comment by MilosKozak** [comment]
I don't see any crash around 12:32:30

**Comment by MilosKozak** [comment]
I see crashes before but there is no stacktrace anyway.
