### ISSUE TITLE
3.3 dev-b User entries duplicated for Carbs

### ISSUE THREAD

**Issue by Philoul** [nightscout/AndroidAPS#3279]
As you can see in screenshot below, user entries are duplicated, first entry recorded within dialog (with correct icon) second entry recorded within PersistentLayerImpl (In think after analysis) with wrong icon (always Treatments icon) as source:
Note that duplicated information is only for Carbs and is not for boluses...

![image](https://github.com/nightscout/AndroidAPS/assets/52934600/0a97ed38-48ae-4e98-8bf8-127df63d43ca)

I don't know the reason of this second entries within PersistentLayerImpl (but I think both could be removed in PersistentLayerImpl class because eather for a new entry or an update of an existing one, it should already be recorded with the correct icon where the action comes from (wear watch command, Carbs, Treatments, Calculator or QuickWizard dialogs, NS or SMS...)
![image](https://github.com/nightscout/AndroidAPS/assets/52934600/fcf8e1f1-c816-424d-a672-77181c7e832c)

**Comment by MilosKozak** [comment]
I'd keep logging in PersistentLayerImpl only to make the logging independent to UI and other code

**Comment by Philoul** [comment]
Ok, so I propose to use a dedicated icon / source for persistant layer (I suggest database icon), different than treatments icon used for Treatments Dialog in overview...
