### ISSUE TITLE
Minimum insulin action time can't be set less then 5.0

### ISSUE THREAD

**Issue by FilArt555** [nightscout/AndroidAPS#3293]
Hi. I use Apidra insulin. Its effect lasts 3 hours. But in the AAPS application the minimum insulin action time can be set 5.0. How can this be fixed?

**Comment by ArthurusDent** [comment]
The AndroidAPS docs are really good and there is an answer for almost anything in there. 

Please take a look at the reasoning behind using a DIA of at least 5 h: https://androidaps.readthedocs.io/de/latest/Usage/Profiles.html#dia-3hr-too-short
