### ISSUE TITLE
my app not found closed loop

### ISSUE THREAD

**Issue by s2228554** [nightscout/AndroidAPS#3294]
This project I downloaded today，Not found closed loop，my english is poor，please help。
[app-pumpcontrol-release_3.2.0.4.apk， this one
![微信图片_20240404234441](https://github.com/nightscout/AndroidAPS/assets/115908808/b35e59dc-d830-4c31-83f0-fdde28270e5c)

**Comment by MilosKozak** [comment]
Pumpcontrol app is not intended for closed loop. You must build the app yourself. Follow https://wiki.aaps.app
