### ISSUE TITLE
Autosens value on AAPS Client never goes above 120% with 1.5 upper sensitivity ratio on AAPS Master

### ISSUE THREAD

**Issue by janvitos** [nightscout/AndroidAPS#3295]
AAPSClient 3.2.0.4

When using an upper sensitivity ratio of 1.5 instead of the default 1.2 ratio with Autosens, the sensitivity shown on AAPS Client never goes above 120% even if it is 150% on AAPS Master (see photo below). It's as if AAPS Client is using the default upper sensitivity ratio of 1.2 instead of the custom chosen one in AAPS Master.

![PXL_20240405_150918879](https://github.com/nightscout/AndroidAPS/assets/10037804/92c8bedc-858c-4397-9bdd-1b03c5f33f89)

I wasn't able to test the custom lower sensitivity ratio, but the same issue might be present for that value as well. So if I set the lower sensitivity ratio to 0.5 instead of 0.7, then AAPS Client might never show anything below 70%.

**Comment by MilosKozak** [comment]
It's can take up to 30 min to get min/max value sychronized to cleint

**Comment by bjarnege** [comment]
Same problem here. Please let me know if there is anything else i need to check.
