### ISSUE TITLE
Unable to clear allowed WiFi SSID on NSClient connection settings ("The field must not be empty")

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#3310]
**AndroidAPS 3.3.0-dev-b**
Build: https://github.com/nightscout/AndroidAPS/commit/3bb0705a03e10aae2cef5d642d86ae0852c43aa5
**Flavor**: Fullrelease

**Problem description:**
On NSClient connection settings, once a WiFi SSID is set, it can not be clear.
Emptying the allowed SSID is blocked with the error message "_The field must not be empty_"

![x](https://github.com/nightscout/AndroidAPS/assets/45144129/d5fc771b-da8e-4cda-845f-44eb777d2a71)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/3f8d4c00466735419305d4ead741eb8668e1897a
