### ISSUE TITLE
Unable to connect to Nightscout -No error in log

### ISSUE THREAD

**Issue by FamouZzE** [nightscout/AndroidAPS#3326]
I am unable to connect my APS to my self-hosted Nighscout Server. It worked on a previous phone with a previous version of APS. I can access Nighscout site from phone directly via Browser and my xdrip+ Installation is also able to upload to Nighscout. 
The Log only shows the following two lines:
14:05:13.122 [RxCachedThreadScheduler-37] D/NSCLIENT: [NSClientPlugin$onStart$5.accept():112]: ● NSCLIENT destroy
14:05:13.124 [RxCachedThreadScheduler-37] D/NSCLIENT: [NSClientPlugin$onStart$5.accept():112]: ● NSCLIENT do connect 

In the UI APS shows also only the two lines and state never changes from connecting.
![Screenshot_20240506_153201_edit_11871962071876](https://github.com/nightscout/AndroidAPS/assets/55629931/640fab3a-8aba-4246-85c8-82e3dcab5878)

I am running APS Version 3.2.0.4 (Build: 5d3e33ce8a-2024.05.06) what seems odd to me is the Nighscout version "unknown" but maybe this is only reported if I could connect correctly.
![Screenshot_20240506_153155](https://github.com/nightscout/AndroidAPS/assets/55629931/9c97168f-6267-4768-96f6-fceb1839c8cf)

What I Already tried without success:
- Clearing Data and Cache APS
- Clean new Installation of APS
- Change Nighscout default role to admin
- Clear storage of Nighscout DB
- Restart Nighscout
- Change Port from 5423 to standard 443

**Comment by MilosKozak** [comment]
what is your NS version?

**Comment by MilosKozak** [comment]
then read release notes

**Comment by FamouZzE** [comment]
Sorry my bad, after update to version 15.0.2 I do still get a 401 error in the log, but URL is correct and I checked token also multiple times. Am I missing anything?
