### ISSUE TITLE
MEDTRUM / Empty reservoir when pod is deactivated 

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#3328]
Minor Medtrum bug. No active pod but the tab says that there is still insulin available. 
I think that, once the pod has been deactivated,  the insulin in it is "lost" and could be set to 0.

![Screenshot_20240507_215200_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/50fee573-3042-4bac-8e81-69390a28ff0c)

**Comment by jbr7rr** [comment]
Should we reset the others too? Last bolus, pump battery and Expiration date

**Comment by robertrub** [comment]
Keep last bolus, that's not pump related only.
 
Yes, reset pump battery and exp date

**Comment by robertrub** [comment]
I remind you about the _connection to the export settings button_ too ;)
