### ISSUE TITLE
DASH/EROS : Feature / add export settings button

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#3340]
It would help people to be "more serious" with backups if there was an _export settings_ button shown at the end of the pod activation sequence.

**Comment by kenzo44** [comment]
We can also update the text..."x days since last aaps back up. Please back up aaps to not lose settings"

**Comment by robertrub** [comment]
You need to export after each pod activation. If you have a phone problem, do a new installation and then import old settings, not only you'd lose your active pod but also stress trying to deactivate a pod that AAPS can't reach...

It should not be let to believe that doing backups "whenever you have time" is an option ;)

**Comment by MilosKozak** [comment]
Automated exports added in 3.3
