### ISSUE TITLE
Medtrum : End of pod AAPS alert error/feature request ?

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#3344]
Medtrum Nano. I can't hear the pod alerts. I need AAPS alerts too.

The pod end alert is set to 72 hours. I don't know if the pod beeped. 

![Screenshot_20240520_065643_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/ed6426ac-4fe5-417a-bdce-08eb55d77962)

No (AAPS) alert 3 days after the pod's end (maybe the pod beeped...). The AAPS alert arrived at 3 days + 8 hours...

![Screenshot_20240520_065558_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/7ed35617-e9bd-472f-906d-e779699cbad3)

It would be good to have the 72 hours and 72+8 hours alerts in AAPS too

The logs (to see if the pod beeped)

![AndroidAPS_LOG_1716182640634.log.zip](https://github.com/nightscout/AndroidAPS/files/15373059/AndroidAPS_LOG_1716182640634.log.zip)

**Comment by jbr7rr** [comment]
Have you considered automations to setup additional alerts?

**Comment by robertrub** [comment]
Very good idea, thanks. Didn't know that option existed. I'll try.
