### ISSUE TITLE
MEDTRUM : Bogus insulin counter

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#3348]
It did it again. This time, I put the base on the patch but nothing more. The insulin counter says 10U

![Screenshot_20240525_191427_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/9b1b8b99-0ec1-4cdf-8b99-bb9e593bd68b)

Then, I pull the air and put in around 120U in the pump. Once again, around 20U are "lost" as I end up with 101U only.

The logs. Look around 19h15

![AndroidAPS_LOG_1716657643141.log.zip](https://github.com/nightscout/AndroidAPS/files/15444349/AndroidAPS_LOG_1716657643141.log.zip)

And my dev version

![Screenshot_20240519_173817_AAPS.jpg](https://github.com/nightscout/AndroidAPS/assets/76626474/4bd8e825-5335-4e35-86d7-9447c63487a3)

**Comment by jbr7rr** [comment]
Thx, for reporting

I think from AAPS side we can only manage to filter out the initial reporting of the 10U, but not the discrepancy between the reservoir level and what you actually put into the pump as that is determined by the pump and we have no influence what so ever, only reading it out
