### ISSUE TITLE
Equil: TBR consistent fail, possible connection issue.

### ISSUE THREAD

**Issue by TheDevilsKnock** [nightscout/AndroidAPS#3361]
```
Equil FW 5.3
AAPS 3.3.0-dev-b
```

As the clip below shows, Temp Basal Rate fails to be set, with the pump falling back to default basal rates. 
The issue can persist even by retrying form the Loop plugin. 
Same bug presents itself even on earlier objectives when having to confirm the suggested temp basal rates manually. 

https://github.com/nightscout/AndroidAPS/assets/98546700/055139e7-0f8e-4359-b352-cb49b3fdfda5

Frequency of this happening is often more than 50% of the times. Even cancelling TBR might fail. 

![WhatsApp Image 2024-05-29 at 13 42 06_01a92ae4](https://github.com/nightscout/AndroidAPS/assets/98546700/813d3d78-70c2-48d1-8380-4bbcf5485f23)

Not sure if this could be a driver / BT connection error, even bolusing gave me twice this error in the last 2 days 

![WhatsApp Image 2024-06-03 at 19 45 26_5cf06eb8](https://github.com/nightscout/AndroidAPS/assets/98546700/38c71098-22bf-4326-913b-ce7930df6116)

Logs show 
```
12:43:22.041 [binder:6277_B] D/PUMPCOMM: [EquilBLE.writeData():302]: indexData error 
```

[AndroidAPS.log](https://github.com/user-attachments/files/15537710/AndroidAPS.log)

Issue was confirmed by other people from my same hospital using Equil.

**Comment by EquilHack** [comment]
Your log is not complete. I need all the logs for May 27th

**Comment by nuke3** [comment]
Hi @EquilHack Does Equil already work with AAPS?
Or maybe for now the status is "maybe it works a little"?

**Comment by EquilHack** [comment]
I have submitted a fix, you can try it
https://github.com/nightscout/AndroidAPS/pull/3376

**Comment by nuke3** [comment]
@EquilHack I'm going to borrow Equil for 10 days. The consultant said there are two versions of the pump software and the version he can borrow is without open BT. Will this work?

**Comment by EquilHack** [comment]
> @EquilHack I'm going to borrow Equil for 10 days. The consultant said there are two versions of the pump software and the version he can borrow is without open BT. Will this work?

Pls keep in mind , only FW 5.3 can work with this code
