### ISSUE TITLE
SMBs not disabled but aren't executed

### ISSUE THREAD

**Issue by alnassermahrouqi** [nightscout/AndroidAPS#3373]
SMBs have been disabled for two weeks now, loop wants top give SMBs but doesn't execute them
logs will be sent now

![448547768_8198324293524513_8665250844269180444_n](https://github.com/nightscout/AndroidAPS/assets/160229502/7be3c83c-8664-43ae-8172-f6dfdbbe2b56)
![448530679_8198325303524412_5900070656182562440_n](https://github.com/nightscout/AndroidAPS/assets/160229502/5546ed7f-ff1d-4882-b6b3-a93580cd598d)

**Comment by MilosKozak** [comment]
unreadable resolution
reset logging to defaults, and provide new logs

**Comment by alnassermahrouqi** [comment]
Duplicate treatments probably caused by incorrect xdrip settings when swapping sensors. Once treatments were deleted, SMBs were back
