### ISSUE TITLE
Feature request: Direct watch control for Medtrum nano or Omnipod and broadcast on watch

### ISSUE THREAD

**Issue by SLi95c** [nightscout/AndroidAPS#3386]
Hi Everyone,

I would like to request the ability to directly control the Medtrum nano insulin pump using a smartwatch, without the need for a connected smartphone. Specifically, I'd like to be able to:

1. Initiate insulin delivery: Start or stop bolus doses directly from the watch.

2. Adjust basal rates: Modify the basal rate profile on the go.

3. Broadcast glucose data on watch: receive on wearos aaps live glucose readings from Juglucco (watch is collector) directly on the watch.

Currently, the inability to operate patch pumps independently of a smartphone significantly limits user freedom and flexibility. Being able to run without a phone would be particularly beneficial for activities like jogging or other workouts where carrying a phone is inconvenient or undesirable.

Benefits of this feature:

- Increased independence: Users can manage their diabetes without being tethered to their phones.

- Improved convenience: Easier to monitor and adjust insulin delivery during physical activity.

- Enhanced user experience: A more streamlined and user-friendly experience.

**Comment by MilosKozak** [comment]
This is not possible. AAPS is an Android (not WearOS) app. Thus it always needs a phone. And generaly it's not possible to connect  and control pumps from more than 1 device and bypass phone when controling from watch
