### ISSUE TITLE
Bug: Bolus insulin not being counted towards total IOB

### ISSUE THREAD

**Issue by missmagoo** [nightscout/AndroidAPS#3393]
- Starting Tuesday, July 30 at around 5pm CT, I started having issues where I was repeatedly going low despite not changing any of my settings or changing how I use loop. The problem has persisted through today, while I've tried to institute temporary fixes like running a 50% profile and adjusting profile settings. Today at 1pm CT I noticed in the treatments log that the bolus delivered through AAPS at 10:03AM was not counted towards total IOB. This caused AAPS to then deliver a series of SMBs to make up for the perceived lack of insulin, which then caused my blood sugar to drop rapidly.
- Build version is 3.2.0.3
- Logs have been sent

**Comment by Philoul** [comment]
Strange, could you please share screenshots of AAPS main screen (including main graph and a first subgraph with COB + IOB), this can help analysis...
And scrrenshot of treatments activity for the period with missing boluses.
It's also better if you could attached log file in the issue (more dev will be able to analyze your issue, on my side I can only see what is shared here...).
Additional question, which pump?
