### ISSUE TITLE
[Feature request] add predefined profiles modifications 

### ISSUE THREAD

**Issue by gregorybel** [nightscout/AndroidAPS#3394]
I do profiles modifications several times a day, especially before lunch I increase the percentage for 30 or 60min.

As I do it really often with always the same parameters, I thought we could add predefined profiles modifications like we did it for the temporary target, we could add 2 or 3 default profiles modifications into the profile UI.

The default values can be set using configuration menu and are stored permanently.

We could maybe set custom icons but this would optional.

**Comment by mick711** [comment]
Why you don't use automation ? You çan add buttons..

**Comment by gregorybel** [comment]
Good point, because I set profiles above 130%

**Comment by mick711** [comment]
Oh yes sorry i don't see this hard limit .
You can change hard limite set to 130.0 to your max limit ;

**Comment by gregorybel** [comment]
Yes that's might be the easiest solution, how do I do that? I don't see a
parameter for this, shoo I modify directly into the code?

**Comment by mick711** [comment]
You can find with find in files : const val MAX = 130.0
File InputPercent.kt
