### ISSUE TITLE
Feature request: Support for Manual Entry of External Insulin Injection via Pen for AndroidAPS on Android and Wear OS

### ISSUE THREAD

**Issue by SLi95c** [nightscout/AndroidAPS#3397]
I would like to request the addition of a feature to AndroidAPS that allows users to manually log insulin administered via an external pen. This feature should be available on both Android and Wear OS platforms.

**Benefits:**

1. **Extended Patch Pump Usage:** By manually logging insulin injections from a pen, users can extend the wear time of their patch pumps, especially during high-carb meals.
2. **Activity Flexibility:** Users can continue to inject insulin with a pen and still track active insulin, even when they don't have their smartphone with them. This is particularly useful during activities like jogging or other exercises, making users less dependent on their smartphones.

**Use Case:**

- During high-carb meals, users can inject additional insulin using a pen and manually log it in the AndroidAPS app.
- While engaging in physical activities without their smartphone, users can still track their insulin levels using their Wear OS device.

Thank you for considering this feature request. It would greatly enhance the flexibility and usability of AndroidAPS for many users.

**Comment by gerison77** [comment]
That is already possible. Checkbox, record bolus only.

**Comment by SLi95c** [comment]
Where do I find this option? I can't find it.

**Comment by gerison77** [comment]
https://androidaps.readthedocs.io/en/latest/Getting-Started/Screenshots.html#insulin
