### ISSUE TITLE
Feature Request: Ability to backup AAPS settings via WearOS AAPS

### ISSUE THREAD

**Issue by staticx** [nightscout/AndroidAPS#3400]
Hello,

I would like to request an option to perform a backup of the application via a command from the app installed on the watch.

Reason: Often phones fall and the screen gets damaged, and we almost always don't have the most up-to-date backup. The phone continues to work, but we have no way to operate the application.

Therefore, if a case occurs where the screen is not functioning, we can choose a backup option directly from the watch, and the file is sent to an email or a Google Drive folder that we have predefined, so when we switch to a new phone, we can use the newest backup. 

Alternatively it would be great to have an Auto-Backup function on AAPS app for daily backups. 

Thank you in advance.

**Comment by MilosKozak** [comment]
there will be automated solution in place
