### ISSUE TITLE
BUG temp basal increases and SMB in Low Glucoe Suspend

### ISSUE THREAD

**Issue by cygrahampearson** [nightscout/AndroidAPS#3401]
[AndroidAPS._2024-08-05_20-00-14_.0.zip](https://github.com/user-attachments/files/16534231/AndroidAPS._2024-08-05_20-00-14_.0.zip)

- occured on Wednesday, August 7th. LGS was enabled via SMS commands. Confirmed enabled by SMS and by the LGS symbol on the device. SMBs were given at 2:47 and 2:57. Temp basal increases also occured
- AAPS [3.2.0.4](http://3.2.0.4/)
Build: 3df83535f9-2024.07.07
- 
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new
-

**Comment by Philoul** [comment]
Can you please share a screenshot of main overview (including main graph and a subgraph with IOB / COB curves) please ?

**Comment by cygrahampearson** [comment]
Here is a nightscout report with COB, IOB and prediction curves. I also attached some screenshots of SMS.

There was a pump unreachable SMS an hour before the SMBs. I wonder if it reverted to SMB rather than open loop somehow?

![Screenshot_20240808_170959_Chrome](https://github.com/user-attachments/assets/a7332b99-0f03-4ca3-bcbb-388f2c4c612b)
![Screenshot_20240808_092925_Messages](https://github.com/user-attachments/assets/2b13acde-5e9a-4347-af6f-6b10b1e43bdb)
![Screenshot_20240808_092858_Messages](https://github.com/user-attachments/assets/3aa182c5-7101-49a1-a2fb-5675676ca2e9)

**Comment by Philoul** [comment]
Read the doc concerning ĹGS mode here:
https://androidaps.readthedocs.io/en/latest/Configuration/Config-Builder.html#low-glucose-suspend-lgs

IOB was negative during all the night so LGS worked as designed and didn't provided more insulin that what was defined in profile.
SMBs and High TBRs kept IOB negative.

**Comment by cygrahampearson** [comment]
Thank you for clearing that up @Philoul 

I feel like a fool for not knowing that.
