### ISSUE TITLE
Feature request (for discussion) add negative Carbs input

### ISSUE THREAD

**Issue by Philoul** [nightscout/AndroidAPS#3406]
Use case: sometimes (due to exercise, type of carbs during meal...) Carbs absorption can be much faster than calculated COB with deviation.
So we can have for a long duration zero deviation, a lot of remaining COB and slow carbs absorption calculated by min_5m_carbimpact.
This can lead to over correction on BG variation due to an overestimation of remaining COB.
In parallel lots of users don't enter carbs during exercise (again to not take the risk of over correction with loop).
The idea is to allow negative carbs entry (max allowed value is remaing COB), to reduce remaining COB.
=> for discussion...

**Comment by swissalpine** [comment]
I very much support this idea! I discussed this with Adrian years ago. However, my ideas were more far-reaching: enter the impact of movement as a negative COB and enable negative COB ... He saw a big problem with the latter because COBs are seen as 0 or positive values in all calculations. This would not happen with your proposal. 
However, a negative eCarb entry, limited to 0 COB, would also be good.

**Comment by jbfeutz** [comment]
Also very helpful for children who may not finish an entire meal. The process to delete a carb entry is very complicated, especially if you are only removing a portion of an announced carb entry.

**Comment by gerison77** [comment]
With respect to sports, I would encurage to implent a "fake carb" option as well like the equivalent for "record a bolus only".

Especially during sports carbs are consumed and not entered. However it would be nice to track the intake of the carbs during sports just be able to analyse the amount of carbs actually needed in that particular situation. I have two active TD1 kids. And sometimes I loose track whom i gave which amount when...

**Comment by MilosKozak** [comment]
add it as a note

**Comment by olorinmaia** [comment]
9fe441bc I guess this can be closed, nice feature :)
