### ISSUE TITLE
Dev-b AutoISF / Can't calculate acceleration 

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#3413]
I switched G6 transmitters which resulted in a desynchronisation of the 5 minutes interval which started the recalculated values.

![Screenshot_20240824_212910_AAPS.jpg](https://github.com/user-attachments/assets/2ee95278-b07c-4e0d-8e06-974422b0dace)

I think (just a guess) that AutoISF plugin does not like recalculated values and can't get a "reliable" acceleration; all acceleration numbers are at 0. 

As it didn't see the deceleration, it selected an agressive ISF for those 3 last BGs (were over target).

![Screenshot_20240824_221303_AAPS.jpg](https://github.com/user-attachments/assets/cb3577d6-d27a-46ab-91f9-b1f13f28718d)

As you can see, just before the drop, there was a dark dot.

Here are the logs (around 22h13 and before)
![AndroidAPS_LOG_1724530521674.log.zip](https://github.com/user-attachments/files/16737927/AndroidAPS_LOG_1724530521674.log.zip)

**Comment by ga-zelle** [comment]
There are only 4 loop events in a single log file. It would help if under Maintenance you disable WEAR (because it just jams the file and makes reading very hard) but enable GLUCOSE which I think is the important one here.

**Comment by robertrub** [comment]
Ok, did the changes to wear and glucose last night. Here are the new logs. There are still dark green dots but I don't know if acceleration was at 0 or not.

![Screenshot_20240825_080246_AAPS.jpg](https://github.com/user-attachments/assets/fa544ae7-f0b3-4a2f-9408-e19820db7721)

![AndroidAPS_LOG_1724565734883.log.zip](https://github.com/user-attachments/files/16739166/AndroidAPS_LOG_1724565734883.log.zip)

**Comment by robertrub** [comment]
Calculated BGs (transmitter change 24h ago)

![Screenshot_20240825_082453_AAPS.jpg](https://github.com/user-attachments/assets/446a8b94-908b-4658-a56e-fad501f7bc28)

Acceleration at 0

![Screenshot_20240825_082426_AAPS.jpg](https://github.com/user-attachments/assets/d1cd431d-9b84-4f19-b6cf-485499fd4321)

**Comment by robertrub** [comment]
OK, I found 2 cases in the logs where Parabola settings change to 0 after a BG time recalculation and the BGs go into a "loop" with 3 minAGO  coming over and over. In the first ZIP, it is 30, 40 and 45 min ago. Look before 9:16:34:840
[AndroidAPS._2024-08-25_00-00-28_.93[1].zip](https://github.com/user-attachments/files/16740609/AndroidAPS._2024-08-25_00-00-28_.93.1.zip)

**Comment by robertrub** [comment]
Recalculated data period is over. There are no more dark green dots on the graph and AutoISF is working normally once again.

There is a problem with the recalculated data and AutoISF.

**Comment by ga-zelle** [comment]
The problem is with gaps in data, not recalculated ones. AutoISF deals with them as expected.
Without G6 I have recalculated all year round and no such problems..

**Comment by robertrub** [comment]
Sorry but I disagree. As soon as the yellow triangle disappeared (and the dark green dots too), the problem of parabola at 0 stopped. Field test says that I'm right ;)

The recalculated data of Libre and G6 seems to be different. No idea what difference. Maybe the difference is that Libre has just _seconds_ of difference when a transmitter change makes _minutes_ of difference...

Another possibility : Are you using the AutoISF plugin in _AAPS dev_ or are you using your "own" AutoISF build ?

**Comment by robertrub** [comment]
@MilosKozak Same as the _color changing dots_ issue, please reopen this one too. Both are related and both are not solved.

**Comment by vanelsberg** [comment]
https://github.com/nightscout/AndroidAPS/issues/3415
