### ISSUE TITLE
Suggestion: Adding SMB recommendations in an open loop

### ISSUE THREAD

**Issue by Inkalika** [nightscout/AndroidAPS#3424]
The proposal is to add to the open loop the ability to see suggestions not only about TBR adjustments, but also SMB. And then the open loop suggests increasing TBR, and when the loop is closed, SMB colitis, which immediately becomes scary, since SMB cannot be canceled in comparison with TBR

**Comment by MilosKozak** [comment]
SMB means borrowing insulin from the future. This can be dangerous in open loop mode as the user may not reflect to suggestions in the future (to stop TBR)
This will not be implemented
