### ISSUE TITLE
BG Source "xDrip+ BG": settings in the wrong place / duplicated

### ISSUE THREAD

**Issue by Gohtraw** [nightscout/AndroidAPS#3434]
This is a minor thing I believe:
In the config builder, section "BG Source" **xDrip+ BG** is the plugin that gets BG data from xDrip+. 
![Screenshot 2024-09-09 121223](https://github.com/user-attachments/assets/cd616dab-5131-47c4-a934-92bcc0e27081)
The only preferences this plugin has are:
"BG upload settings"
- Upload BG data to NS
- Log sensor change to NS

There is another config builder section "Synchronization" **NSClientV3** for data that's being sent from AAPS to NS.
![Screenshot 2024-09-09 121301](https://github.com/user-attachments/assets/2f744228-4198-447b-942c-d2cdfcface66)
- Log sensor change to NS could be moved to the section  .
- Upload BG data to NS can already be found there (toggling it in Synchronization" also toggles it in "BG Source" and vice-versa).

**Comment by XXilay** [comment]
I can confirm right now that this is not **a purely cosmetic issue.** The discussion of what exactly happened can be found on the discord, (https://discord.com/channels/629952586895851530/629954570394533889/1296464093993111602 ) but ill reiterate again here:

If you (apparently) use the search function to set these values, it ends up activating the same options twice and is not automatically turned off in 1 of the plugins like it would when edited directly under "plugin preferences"

This in turn causes aaps to send a sensor change entry and all data with it to nighthawk on every blood glucose update sent by the CGM. (from what i read off the logs, the data sent with that sensor change just has all fields set to null)
