### ISSUE TITLE
AAPS client Sync button does not work 3.3.0-dev-c

### ISSUE THREAD

**Issue by ohjay73** [nightscout/AndroidAPS#3435]
Unable to access the syncronization settings for appsclient to adjust or view current sync settings. 

You can find the option via a search of preferences, but unable to "click" and edit

build 922640eb63

**Comment by ohjay73** [comment]
AAPS full app works just fine

**Comment by olorinmaia** [comment]
This has never been possible in AAPSClient if you are talking about the NSclient > Sync option available in AAPS.

**Comment by olorinmaia** [comment]
@MilosKozak this is actually a bug, in current master 3.1.0..4 you can search for "sync" in settings and open NSClient Synchronization options that shouldn't be possible. These settings shouldn't be altered and will cause issues if changed on AAPSClient side. In dev, you can search for it and it appears, but you can't click on it. It shouldn't appear in search either.

See screens from AAPSClient:
Option is hidden if you navigate to settings:
![image](https://github.com/user-attachments/assets/db860888-d4d2-4c41-a45e-4be1f4ec6278)

If you search for it, it appears and you can click on it and adjust settings.
![image](https://github.com/user-attachments/assets/e8aa5b6b-748e-473b-b397-dcba36be7a7e)
![image](https://github.com/user-attachments/assets/17d6ceeb-8130-417c-a716-79be2573abc7)

**Comment by MilosKozak** [comment]
in current dev you can search for it but you cannot select "Synchronization"
Can you confirm?

**Comment by olorinmaia** [comment]
Yes, it appears briefly, you can click on it, but nothing happens. After a few seconds it disappears.
