### ISSUE TITLE
Automatic care portal entries in the treatments in the “User input” tab are incorrectly entered/sorted in a timely manner

### ISSUE THREAD

**Issue by TeufelHH** [nightscout/AndroidAPS#3452]
Hi, when AAPS creates automatic care portal notes in the treatments (e.g. pump paused, pump started, etc.) these are entered or sorted/displayed incorrectly.

Unfortunately my English isn't the best but I hope you understand what I mean.

AAPS 3.2.0.4
Handy: Samsung Galaxy S23 ultra (Android 14 - OneUI 6.1)

Here you can see that the oldest entries are at the bottom and become more current as they go up.
But the 3 Careportal entries are sorted the exact opposite time.
![Screenshot_20241004_204008_AAPS](https://github.com/user-attachments/assets/13efccae-56d4-4bea-8d2d-bd634cd12adb)

It's the same here, the old entries at the bottom and the new ones at the top, only with the Careportal entries it's exactly the opposite.
![Screenshot_20241004_204054_AAPS](https://github.com/user-attachments/assets/ce5b7b89-0e47-4f8e-a5f5-6cbb39f12e1e)

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/bb7df50a68308acc8e6a223272fda44e4881283b
