### ISSUE TITLE
Tidepool 400 (bad request) error

### ISSUE THREAD

**Issue by sebastiaanvanderzee** [nightscout/AndroidAPS#3462]
Hi, I found out that my data hasn't been uploaded to Tidepool via AAPS from Aug 31 until now. I made a few screenshot. In one you can see a 'wrong' BG value of about 60 mmol/l, could this be the reason Tidepool gives the 400 (bad request) error? I contacted Tidepool support, but they say they can't help me. I created another Tidepool account to see if I could upload there, but it didn't work. Uploading the BG values only with xdrip does work but it messes up my view in Tidepool. I think this is a bug, in this thread https://github.com/NightscoutFoundation/xDrip/issues/842 they are talking about the fix implemented for xdrip. Is there a way to look at the data my phone is trying to upload, so I can manually remove some records? Clearing the AAPS database also seems to work for me, but now I am missing bolus and basal values for the last 1,5 months.

--------------
- Build version AAPS 3.2.0.4.
![AAPS high](https://github.com/user-attachments/assets/50d9b453-dcbf-4b02-aa57-0b83a6f49f79)
![Tidepool](https://github.com/user-attachments/assets/07398d29-2dcb-4936-90e0-4f6fe9890d2a)
![tidepool2](https://github.com/user-attachments/assets/2ce258b8-f9e8-43ea-aa37-0f20d0c761d6)

**Comment by vanelsberg** [comment]
Confirming: seeing this. 
AAPS 3.3.0-dev, from September 18th, 2024, Tidepool has no data. Same failure.

**Comment by vanelsberg** [comment]
Response 400 shows invalid values for treatments/carbs.
It does not like AAPS's negative carbs. Will look into a fix.
