### ISSUE TITLE
Problems with AGP

### ISSUE THREAD

**Issue by Duester64** [nightscout/AndroidAPS#3489]
Can't compile due to AGP Problems as follows:

The project is using an incompatible version (AGP 8.7.1) of the Android Gradle plugin. Latest supported version is AGP 8.7.0-alpha08

Greets

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://wiki.aaps.app/en/latest/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
update your studio
make sure you are using latest SDK
![image](https://github.com/user-attachments/assets/0a2213d0-405a-4b76-a3e7-318ea5e7b2f2)
