### ISSUE TITLE
Negative carbs ?

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#3492]
Yesterday afternoon, I set a negative carbs entry as the big carbs entered in the morning were still not finished around 14:00

![Screenshot_20241024_025421_AAPS.jpg](https://github.com/user-attachments/assets/f8e70f23-f527-413b-a7b8-ebc9879c7fcc)

After the negative carbs entered,  I could bolus normally (COB was set to 0).

This morning, I see negative carbs on the main screen.... 

![Screenshot_20241024_025208_AAPS.jpg](https://github.com/user-attachments/assets/c2d9af61-8b0f-4a76-adfb-80cc0c7d47e0)

The negative carbs entered should "erase" carbs of COB but should not generate negative carbs.

**Comment by MilosKozak** [comment]
I cannot reproduce this issue

**Comment by robertrub** [comment]
I don't use neg carbs so can't tell if it happens regularly.

Will try to trigger it again.

Ii has set neg IOB to clear the 15gr to 0 then add the meal carbs and bolus. Some hours later, I saw the neg carbs.

**Comment by vanelsberg** [comment]
_Confirming_: notices the same. No details on repro.
Will try to trigger again..

**Comment by robertrub** [comment]
@MilosKozak It happened again. I have the screenshot the treatments tab (if it can help reproduce).

I saw the negative COB at 19h10 but it probably appeared earlier.

![Screenshot_20241102_191025_AAPS.jpg](https://github.com/user-attachments/assets/914ed39d-6840-487b-bf07-8eb8c4631f34)

![Screenshot_20241102_191043_AAPS.jpg](https://github.com/user-attachments/assets/91395353-2b89-4ddb-b5da-03f1c011b47c)

![AndroidAPS_LOG_1730571053438.log.zip](https://github.com/user-attachments/files/17607915/AndroidAPS_LOG_1730571053438.log.zip)

**Comment by olorinmaia** [comment]
It would make more sense to "edit" a carb entry that is overestimated than actually adding a negative carb entry at a given time. It needs to be supported in NS v1/v3 api to sync correctly.

It is possible to edit directly in NS > Reports > Treatments, but it doesn't sync back to AAPS/AAPSClient. What I do today is to delete the carb entry that is wrong, and add a new entry with about same timestamp with correct number of carbs.

**Comment by robertrub** [comment]
Normally I don't use neg carbs. I'm just testing the function. It seems that some people had a need for neg carbs though. It is faster to enter neg carbs than delete the carbs, enter new carbs with the old time stamp.

**Comment by olorinmaia** [comment]
Yes, I am testing it as well. But I wonder if it is possible to add a function to edit instead within AAPS / AAPSClient.

**Comment by vanelsberg** [comment]
> It would make more sense to "edit" a carb entry that is overestimated.

yes & no?
When I overestimated carbs I remove and then add the actual amount of carbs. So similar to "editing" as you propose.

But I think the original intention of negative carbs was not so much "editing" for "over/underestimated" carbs, but a way to handle situations where _carbs absorption is to slow_, without changing original amount of carbs registered.
That is a feature that I find extremely useful in certain situations.

**Comment by robertrub** [comment]
Yes, "eliminating" slow COB reduction is where I use/test the option too.

**Comment by MilosKozak** [comment]
try with https://github.com/nightscout/AndroidAPS/commit/9f3cbe21505da570054f06f86dc8f2b0c6841d9a

**Comment by robertrub** [comment]
Will build this afternoon and test 👍🏻

**Comment by MilosKozak** [comment]
result?

**Comment by olorinmaia** [comment]
I haven't been able to reproduce at least
