### ISSUE TITLE
(2.8.2) Pre-bolus alarm could not be turned off.

### ISSUE THREAD

**Issue by Pipsko** [nightscout/AndroidAPS#350]
I was having a little annoying problem, while having dinner (pizza). 

I used the calculator to determine units and pre-bolus (15 min) for my meal (100g KH). 
While the bolus was given by my pump, I got a "reservoir empty" message through AAPS. I took my time with changing my reservoir, because 80% of the bolus was already done. 

So 15 minutes later the "time to eat" alarm kicks in, while I am changeing the reservoir. Unfortunately no message popped up for that. I finished changeing the reservoir and reconnected the pump via the pump menu in AAPS.

I was hoping that would stop the alarm, but to no avail. Then I shut down AAPS via the upper left 3-dot-menu.

Then another alarm continued instead. This one could be muted by lowering the volume to 0.
https://user-images.githubusercontent.com/45955102/108558856-d53f0680-72fa-11eb-85ef-b650f2f762cc.mp4

**Only a restart of the phone did the trick.** 

**Setup:** 
Galaxy Note 10 lite (Android 10), Dexcom G6@xdrip(056b822-2020.12.18, Accu Chek Insight V3.00.17, AAPS 2.8.2 (194549adc-2021.01.23-15:55)

**Logfile:**
[AndroidAPS_LOG_1613767274483.log.zip](https://github.com/nightscout/AndroidAPS/files/6012826/AndroidAPS_LOG_1613767274483.log.zip)

**Time of occurence:**
Pre-bolus: 19:57 Alarm: 20:12

**Comment by MilosKozak** [comment]
there are issues with this feature on some phones. it's already changed in dev
