### ISSUE TITLE
Medtrum Nano 300u base with 200u patch

### ISSUE THREAD

**Issue by I1985** [nightscout/AndroidAPS#3511]
Not necessarily an Issue, but interesting and wanted to share in case the developers are interested. 

I'm using the Medtrum Nano 300u. Had some fails so requested new patches and got them delivered. But didn't open the box till I used all other patches. Turned out they delivered 200u patches by mistake.

As it was late at night, and I was without a pump I thought I'd ive it a try. The 200u patch connected fine with the 300u base, went through the fill process and it activated as normal. 
In the morning I got a rather concerned tech support from Medtrum on the phone, they're not supposed to be compatible, and they don't recommend doing this. 

But since it seemed to work ok I ended up using this combination for 51 hours without any problems before the reservoir was too low to risk another night. 

Could it be that the Medtrum app/pdm does a check on patch/base match that aaps doesn't? 
And/or do we know where the difference between the bases is?

**Comment by jbr7rr** [comment]
No, in app we can't check what patch you pair to the base. No information regarding that is shared afaik.

I think the bolus step is slightly different on the 300, but that might also be a firmware thing. I had less success when pairing a 200 patch with a 300 base. it gave errors after couple hours
