### ISSUE TITLE
profile not coming back 100%

### ISSUE THREAD

**Issue by kacperpetla** [nightscout/AndroidAPS#3514]
I upgraded from dev-c to dev-d and noticed a problem

Automation sets the profile to the desired value and time, after this time the profile does not set itself to 100%
![Screenshot_20241104_103344_AAPSClient](https://github.com/user-attachments/assets/8cdc7818-52e2-4954-901b-e303ea7950d2)
![Screenshot_20241104_111457_TeamViewer](https://github.com/user-attachments/assets/e974457a-a6be-485a-912a-fcf67c8cdd2f)

**Comment by vanelsberg** [comment]
Have seen this once (after -45 mins, temp profile stil running) , unable to reproduce. 🧐

**Comment by MilosKozak** [comment]
the only reason I see is when pump is not reachable. Otherwise profile is switched within 5 min

**Comment by kacperpetla** [comment]
I ran tests, set the profile to 90% for 5 minutes and after 15 minutes it was -10 and nothing happened, I went back to the older version of Dev-c and the profiles change as they should, when I was building the application the servers were probably overloaded because it was laborious, today I made a new apk, installed it on my phone and set up a virtual pump, for now everything is fine, I will test for 2 days and update the master and write if everything is fine

**Comment by kacperpetla** [comment]
the connection to the pump was definitely there, since it was serving smb, as you can see in the screenshots, the profile was set to 130% at 8:40. after that time it was serving smb, I turned off the profile manually at 10:36
![Screenshot_20241104_201931_TeamViewer](https://github.com/user-attachments/assets/910344fc-8f1b-447a-9096-81bda00ec508)
![Screenshot_20241104_202033_TeamViewer](https://github.com/user-attachments/assets/6666a0ac-286b-440e-a784-947ab0176433)

**Comment by kacperpetla** [comment]
I changed the version to dev - c, I don't know if the logs were saved, and I didn't download them then.

**Comment by MilosKozak** [comment]
create new issue with logs if it happen again
