### ISSUE TITLE
Dev version closed loop not avaiable 

### ISSUE THREAD

**Issue by Duester64** [nightscout/AndroidAPS#3532]
With the newest dev I get an error that with this dev version closed loop not avaiable, This error occurs only with the latest two versions. The ones before runing well.

Any ideas? Has something changed?

Thx for help.

**Comment by parapenT1sta** [comment]
Copy the engineering file to Documents\AAPS\extra.

And also check the selected AAPS folder in maintenance menu.

**Comment by Duester64** [comment]
Changed folder from AAPS\extra to Documents\AAPS\extra on your request and put the file there.
changed directory in the maintenance menu to documents\AAPS\extra
However AAPS gives the same error
AAPS generates another extra folder within the existing extra folder ???

**Comment by Duester64** [comment]
Found the problem. The directory has to be set to documents\AAPS only. The app adds the \extra folder by itself.
solved, thanks a lot for your help.

**Comment by parapenT1sta** [comment]
> Found the problem. The directory has to be set to documents\AAPS only. The app adds the \extra folder by itself. solved, thanks a lot for your help.

That is what I mentioned "selected APPS Folder" :-)
Glad it worked for you.
