### ISSUE TITLE
Remove Invalid BG entries UI in bulk is not possible

### ISSUE THREAD

**Issue by muthijammy** [nightscout/AndroidAPS#355]
Remove Invalid BG entries UI in bulk is not possible

Note: in 2.7.x  was autoscrolling to latest BG after every BG removal and annoyingly we had to scroll down again. In 2.8.2 which I did today, I notice this seems is fixed

I use xdrip with G5. As most CGM users extend, there are some BG values wrong. Inherently as well due to calibration and other issues, Even though high noise is suppressed within xdrip, there are cases of incorrect values in androidaps. Ex: historic wrong values during sleep. Androidaps allows delete of BG but UI is cumbersome. U need to click "remove" of invalid BG to one by one, no checkboxes in select in bulk or filter to show certain BG entries. In addition, 2.7 x was auto scrolling to latest BG after every remove and we need to scroll down to historic BG.

Also,would be good for tab to show entries for more than 12 hrs that it currently displays.

**Comment by MilosKozak** [comment]
sorry, editing BGs is not a task for a loop app. if you cannot rely on CGM data you should not use it
