### ISSUE TITLE
[Dev] Preferences for Pump and Local alerts appear in places they don't belong

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#3550]
Navigate to Home Screen -> Preferences ->  Overview -> Default Temp-Targets or Fill/Prime or many other preferences via Home Screen -> Preferences.

"Pump" and "Local alert" appear at the bottom for some reason. I've been trying to fix this myself but no luck so far.

![image](https://github.com/user-attachments/assets/922103cc-d58b-45fa-9015-08b8b7817776)

**Comment by Philoul** [comment]
I confirm this issue, very strange...

It's for all preferences that have 2 level of "standard" sub menu.
Within second level of submenu (opened in a dedicated page), it's like pump/advanced and alert/advanced are not removed or hidden and remained visible...

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/97860cf0cf1b35e151f12174ba0bba29e077f750
