### ISSUE TITLE
Max Usage Limit for Master Password Reset in v3.2.0.4?

### ISSUE THREAD

**Issue by Maccha-Azuki** [nightscout/AndroidAPS#3556]
Build version 3.2.0.4,, 

I reset the master password once **without having an active Omnipod Dash**. After reopening AAPS, I received a message indicating success. However, when I tried using this feature again later (with an active Omnipod Dash), there was no success message, and the `PasswordReset` file in the `extra` folder no longer disappears. After deleting the `extra` folder and reopening AAPS, the folder is automatically recreated. 

Therefore, I would like to know if this feature has a minimum time interval for reuse or if it can only be used once. If anyone can help me, I would be very grateful. Thank You！

**Comment by Philoul** [comment]
Usage is only once.
Then a new password should be set using the temporary one.

**Comment by MilosKozak** [comment]
and the file is removed on successful reset

**Comment by Maccha-Azuki** [comment]
Thank you for your reply! So is the password for the Omnipod Dash pump still 4241 when it's not active? I tried entering the master password 4241 in the export configuration section, but it still showed a password error. I previously used the Dash, and the one currently active is also the Dash. I also tried using the serial number of a Medtronic pump I used a long time ago (which didn't help either).

________________________________
发件人: Milos Kozak ***@***.***>
发送时间: 2024年11月27日 9:27
收件人: nightscout/AndroidAPS ***@***.***>
抄送: Maccha-Azuki ***@***.***>; Author ***@***.***>
主题: Re: [nightscout/AndroidAPS] Max Usage Limit for Master Password Reset in v3.2.0.4? (Issue #3556)


and the file is removed on successful reset

―

**Comment by MilosKozak** [comment]
yes when dash is selected as a pump it's always 4241

**Comment by MilosKozak** [comment]
I'll change the code. Thanks for finding this issue

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/c37395ae96d7fe3fd2e959d03262cd9fe0429e55
