### ISSUE TITLE
[Dev-E] NSV3 is getting a queue and TBR aren't updated

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#3570]
AAPS / AAPSClient 3.3.0-dev-e
Build: cab69e7cae-2024.11.30
Nightscout version: 15.0.2
Engineering mode enabled 

TBR on AAPS seem to be unable to upload to NS thus making a queue. Carbs/boluses/notes/etc seem to be working fine. If I change to NSV1 all get uploaded and synced. Then problem starts again after switching to NSV3.

See logs.
AAPS: [AndroidAPS_LOG_1733055705924.log.zip](https://github.com/user-attachments/files/17968912/AndroidAPS_LOG_1733055705924.log.zip)

AAPSClient: [AndroidAPS_LOG_1733055480781.log.zip](https://github.com/user-attachments/files/17968915/AndroidAPS_LOG_1733055480781.log.zip)

Screenshots:
| AAPS | AAPS |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/3c4bf82f-9727-4d7a-9f5e-3f715d9f5f4f) | ![image](https://github.com/user-attachments/assets/e5359f04-8feb-429f-acdb-0b6184197599)| 

| AAPSClient | Nightscout |
|--------|--------|
|![image](https://github.com/user-attachments/assets/86a3cdea-dbb3-485b-a5da-e715c5f39a29)| ![image](https://github.com/user-attachments/assets/3f5687ab-872b-4588-a226-6b8f2d016eb6)|

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/0f89dfd159f235377dfc71b92acdc28fe9e8b3e8
