### ISSUE TITLE
 [Dev 3.3.0-dev-e] Language setting hidden when simple mode = on

### ISSUE THREAD

**Issue by emilisev** [nightscout/AndroidAPS#3579]
When simple mode is on, the language setting is not visible, is this intended ?

![Screenshot_20241203-222650](https://github.com/user-attachments/assets/e00557f7-9559-42f7-b4be-8ee0532b8e2d)

![Screenshot_20241203-222656](https://github.com/user-attachments/assets/4d65f6d0-fb67-4531-86bc-018785b45361)

**Comment by MilosKozak** [comment]
yes, android language is used
