### ISSUE TITLE
AAPS 2.8.2 change language will not change it

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#358]
I was testing for an English text in the French interface and fell on a bug. I changed the language from "System default" to German but everything stayed in French. 3 dot menu and quit AAPS. Restart AAPS and still, everything stayed in French.
![Screenshot_20210222-084104_AndroidAPS](https://user-images.githubusercontent.com/76626474/108677711-59a3ac00-74ea-11eb-842c-1c7ac0fa3775.jpg)
![Screenshot_20210222-084122_AndroidAPS](https://user-images.githubusercontent.com/76626474/108677751-6922f500-74ea-11eb-8a28-8d119f95699c.jpg)

**Comment by Philoul** [comment]
Select System default in AAPS settings and change language in your android setting, then it works perfectly.
@MilosKozak I propose to remove this setting in AAPS (always set "system default") and show a reminder of the selected language in the android settings.

**Comment by robertrub** [comment]
This was something that was working in 2.7 as, while replying to the questions for the objectives, I had changed the language in AAPS in order to see the questions in English for some of them.

**Comment by Philoul** [comment]
It's a recurring bug that exists for long time (sometimes it works on some fields)
See 
- https://github.com/MilosKozak/AndroidAPS/issues/2759, 
- https://github.com/MilosKozak/AndroidAPS/issues/2746, 
- https://github.com/MilosKozak/AndroidAPS/issues/2152, 
- https://github.com/MilosKozak/AndroidAPS/issues/1060

**Comment by robertrub** [comment]
Ok. As I said, not important. I wonder if anybody (except a very few) ever tried using it.

**Comment by Philoul** [comment]
Mainly developers and translators I guess use it.
We all use now Android language switching with "Default System" in AAPS...
