### ISSUE TITLE
[beta1] TBR not showing in AAPSClient with NSv1

### ISSUE THREAD

**Issue by emilisev** [nightscout/AndroidAPS#3585]
AAPS and AAPSClient both on beta1, both using NS v1. Settings imported from 3.2 on both sides. I don't see the TBR on AAPSClient. I see them all right on NS web UI, so they get uploaded.

[AAPSClient log](https://github.com/user-attachments/files/18042466/AndroidAPS_LOG_1733511287304.log.zip)
![Screenshot_20241206-194914](https://github.com/user-attachments/assets/8a7cb6b6-cb7f-49a0-9f82-d40f16a36093)

![image](https://github.com/user-attachments/assets/4a80ff77-3ecd-44dc-a6dc-0802540c6336)

**Comment by MilosKozak** [comment]
was the data uploaded to NS by 3.3?
pm me access to you NS to be able see the data

**Comment by emilisev** [comment]
No, the data is uploaded with v1 as well. Credentials sent in discord, thanks.

**Comment by MilosKozak** [comment]
resolved in https://github.com/nightscout/AndroidAPS/commit/0247d3b198fc572889122e0eb3c75acceb26028e
