### ISSUE TITLE
3.3.0 Beta 1 AAPS Sync/Websockets

### ISSUE THREAD

**Issue by elgrupo123** [nightscout/AndroidAPS#3587]
1.Wenn Websockets aktiviert sind, bekommt AAPS Client keine Daten. Sind die Websockets auf allen Geräten ausgeschaltet, funktioniert der Sync. Ist es so gewollt??
2.Das Menü "Synchronisierung" in AAPS Client lässt sich nicht öffnen. 

Update: Lösung zu 1. 
Master - Websockets AN,  AAPS Client - Websockets AUS

**Comment by MilosKozak** [comment]
must be related to your connectivity as the communication module is the same on master and client

**Comment by elgrupo123** [comment]
Also ich muss auf beiden Follower Geräten die Websockets ausschalten, um die Daten zu bekommen, Master Websockets sind aktiviert. Wenn ich AAPS Clients ältere Versionen nehme, können die Websockets aktiviert bleiben und die Daten kommen an.

**Comment by MilosKozak** [comment]
provide screenshots and logs if you need more help

**Comment by elgrupo123** [comment]
Das Problem besteht selbst mit der DEV Version. Nach einiger Zeit werden NUR die BZ Werte nicht synchronisiert, alle anderen Daten kommen an.  Heute Morgen ca. 6Uhr tratt der Fehler wieder auf. 
Mit der Master Version (3.2.0.4) gibt es das Problem nicht
[AndroidAPS._2024-12-17_00-00-19_.0.txt](https://github.com/user-attachments/files/18167163/AndroidAPS._2024-12-17_00-00-19_.0.txt)

**Comment by elgrupo123** [comment]
> Stellen Sie Screenshots und Protokolle zur Verfügung, wenn Sie weitere Hilfe benötigen

Das Problem besteht selbst mit der DEV-Version. Nach einiger Zeit werden NUR die BZ-Werte nicht synchronisiert, alle anderen Daten kommen an. Heute Morgen ca. 6Uhr tritt der Fehler wieder auf.
Mit der Master Version (3.2.0.4) gibt es das Problem nicht.

[AndroidAPS._2024-12-17_00-00-19_.0.txt](https://github.com/user-attachments/files/18167252/AndroidAPS._2024-12-17_00-00-19_.0.txt)
