### ISSUE TITLE
AAPS 3.3Beta1 SMB always not working with libre3 sensor

### ISSUE THREAD

**Issue by DonSnacks** [nightscout/AndroidAPS#3589]
So after installing AAPS3.3Beta1 in hopes to let my Libre3 sensor can use SMB always

but after testing out different data smoothing, both in xdrip+ and AAPS i have still not been able to get SMB always to be enabled.
testing with only xdrip -> AAPS. then juggluco -> Xdrip -> AAPS 
attatching logfile and screenshots of aaps and xdrip+.

[AndroidAPS.log](https://github.com/user-attachments/files/18050822/AndroidAPS.log)
![Screenshot_20241207_210440_xDrip+](https://github.com/user-attachments/assets/83f33d7a-744e-4d8a-a9ca-ef1e95c7ad48)
![Screenshot_20241208_055121_AAPS](https://github.com/user-attachments/assets/8fc78e06-b6d5-4571-a9be-c6dc2f762acd)
![Screenshot_20241208_055128_AAPS](https://github.com/user-attachments/assets/8412ff82-137c-4b72-9922-42bb54e91352)
![Screenshot_20241208_055146_AAPS](https://github.com/user-attachments/assets/2b6ee990-5ecb-42c6-a000-b0f2bd64fa9c)
![Screenshot_20241208_055233_xDrip+](https://github.com/user-attachments/assets/0fd13e13-4e78-48f3-8ab5-3a9ecc444274)

**Comment by MilosKozak** [comment]
xdrip is sending sensor type LIBRE_1_OTHER. Report to xdrip groups
it must be updated
