### ISSUE TITLE
English text in French interface but not in the translation files

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#359]
When I suspend Omnipod and then reactivate it, I have an English text. I thought that there was a missing translation but the translation files are OK and "Resume delivery" was translated 2 months ago. It is possible that AAPS 2.8.2 is not using the translated text there.

![20210221_215538](https://user-images.githubusercontent.com/76626474/108678270-29a8d880-74eb-11eb-9713-1c10a79f6d25.jpg)

**Comment by robertrub** [comment]
I just tested other communocations with the pod and ALL are shown in English.

**Comment by MilosKozak** [comment]
these statuses are not translatable at the moment
