### ISSUE TITLE
[3.3 beta1] Feedback on unattended exports

### ISSUE THREAD

**Issue by emilisev** [nightscout/AndroidAPS#3590]
Feature working well so far, just some feedback on strings.
Here's what I did on this screenshot : 
* 16:52 : unattended export attempt through automation
* 16:53 : manual export
* 16:55 : unattended export through automation

My feedback : 
* 16:52 : the text seems so long that the checkbox to delete the entry does not show
* 16:52+16:55 : strings improvements : empty parenthesis, nothing before colon
* 16:55 : the source string seems to be different than the manual export one. Maybe it's the same wording in english, but the resulting possible discrepancies in translations makes it confusing.

![WhatsApp Image 2024-12-07 à 18 00 31_c4fd55ca](https://github.com/user-attachments/assets/5e3f31cd-523f-4146-a6a1-fff4ffa82f29)

**Comment by emilisev** [comment]
> the password for automatic export expire once a month and you have to re-enter it within 1 week to continue doing exports. the reason is for this is that if you don't remeber the password, the export is useless. 

Yes, no problem with that, my feedback was only about UI. Here is the screenshot in english showing the same issues : 

![WhatsApp Image 2024-12-08 à 21 09 39_27b8605a](https://github.com/user-attachments/assets/165b3704-ebc3-4a75-b271-e5fb9da1c0dc)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/9c041ef1480a0693434e46de868b626616e98d74
