### ISSUE TITLE
[DEV] Minor issue with numbers appearing in temp target default values dialog box (mg/dl vs mmol/l)

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#3593]
Fresh install of AAPSClient make default values of preset TT in mmol/l show as divided by 18. 

If I enter 8.0 and save it's fine for a while, but then overwritten by what AAPS is sending probably after a while.

![image](https://github.com/user-attachments/assets/c50767ee-d9fb-4647-8cda-e8ab618406cf)

**Comment by MilosKozak** [comment]
do you mean value are transferred wrong from AAPS?

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/446d5cf9db214ad3035de9ac88b8a7f6826eb3d2
