### ISSUE TITLE
[Dev] [NSv3] After short period of offline TBR sync wrong on AAPSClient causing wrong IOB

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#3597]
After a short period of no connectivity there seem to be a small issue with TBR syncing correctly causing wrong IOB in AAPSClient vs AAPS.

Logs:
AAPS: Not able to find logs from that time period.. Shouldn't they be located in \Android\data\info.nightscout.androidaps\files ? 

Logs don't seem to write in the folder \AAPS\ set by setting in Maintenance.

AAPSClient: 
[AndroidAPS_LOG_1733776611326.log.zip](https://github.com/user-attachments/files/18067808/AndroidAPS_LOG_1733776611326.log.zip)

| AAPS | AAPSClient |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/73624f8a-b1cb-4e51-bc08-47ba78e89710)| ![image](https://github.com/user-attachments/assets/846437ea-5ddf-4a1a-befd-4ec8dc57458c)|

**Comment by MilosKozak** [comment]
is there a step by step guide how to replicate it?

**Comment by olorinmaia** [comment]
I tried yesterday but couldn't.. I'll make another attempt later today. It could be a rare case.

**Comment by olorinmaia** [comment]
Can't reproduce. Will open again if I manage.
