### ISSUE TITLE
[dev-e]  Medtrum - Hide pump expiry warning when patch expiration is disabled

### ISSUE THREAD

**Issue by WesSec** [nightscout/AndroidAPS#3600]
With the medtrum pump, when Patch Expiration is turned off in the medtrum settings, the setting/line for "Pump expiry warning [hours]" is still marked as active, but nonresponsive. It would be a slight improvement to gray out/hide this setting when pump expiry is disabled

![image](https://github.com/user-attachments/assets/2af7a416-bb0a-4793-a14c-39245fe9c9ea)

**Comment by olorinmaia** [comment]
https://github.com/nightscout/AndroidAPS/pull/3604

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/5618586913cb183263d3c6b53112e427ce1ca7b3
