### ISSUE TITLE
Layout degradation Portal overview: unexpected empty space

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#3607]
**AndroidAPS 3.3.0-dev-e**
**Build:** https://github.com/nightscout/AndroidAPS/commit/859764d2ce4fc3359c4fe4e243a89466fc5aa996
**Flavor:** Fullrelease

**Problem description:**

Layout degradation at AAPS portal overview: unexpected empty space for _BG Check_ events.

**Logfiles**
[AndroidAPS_LOG_1733905150983.log.zip](https://github.com/user-attachments/files/18092689/AndroidAPS_LOG_1733905150983.log.zip)

**Comment by MilosKozak** [comment]
screenshot?

**Comment by olorinmaia** [comment]
AAPSClient look fine.
![Screenshot_20241211_115751_AAPSClient2](https://github.com/user-attachments/assets/bf93eacf-318c-4c96-a4c2-2fc2b0907988)


AAPS
![20241211_115822](https://github.com/user-attachments/assets/436fbb98-8f9d-45dc-8cf7-e99b685ef232)

**Comment by vanelsberg** [comment]
> screenshot?


![CarePortal](https://github.com/user-attachments/assets/bd599912-45bb-43ea-89b2-160f05d40501)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/6f3e9372ef73045ec88c1fc389823d8fcc2ef17b
