### ISSUE TITLE
Minor issue with checkbox not appearing in treatments when text is long

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#3609]
Enter a note with long text and go to treatments and try to delete it. Checkbox is not visible. 

![Screenshot_20241212_014611_AAPSClient2](https://github.com/user-attachments/assets/71fa7e7a-3141-430f-88d8-83d60c834cb7)

**Comment by MilosKozak** [comment]
Damn ....

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/e73d2925c4771b0932fc02ba35568dede7a564ce
thanks!
