### ISSUE TITLE
[3.3.0 Beta1] CGM Button can't be made visible on main screen.

### ISSUE THREAD

**Issue by gerison77** [nightscout/AndroidAPS#3610]
On the Main screen of the above mentioned beta Version the CGM button is not shown on main screen despite activation in menu.

Rig: N6000 + Diakem G7 App + G7

**Comment by MilosKozak** [comment]
On android 11 it's not possible to detect installed applications.
Thus this feature had to been removed for Dexcom.
It's still available for xdrip
