### ISSUE TITLE
Dev F Progression barre stuck

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#3613]
@MilosKozak As we talked on Discord, with the last dev f, the progression barre gets stuck till next BG reading and stops data being sent to watch.

![Screenshot_20241212_173245_AAPS.jpg](https://github.com/user-attachments/assets/7ecc7c5e-2b66-48fa-90ad-d13f371aa36a)

![IMG-20241212-WA0001.jpg](https://github.com/user-attachments/assets/c429f3a8-62f1-466b-82e7-ac7f717e1d22)

Pulling on the Loop tab gives a black screen on loop and AutoISF

![Screenshot_20241212_190905_AAPS.jpg](https://github.com/user-attachments/assets/f4d12a9b-b916-41aa-87f8-d4f0428c2092)

![Screenshot_20241212_190910_AAPS.jpg](https://github.com/user-attachments/assets/cf22eaa6-091e-4402-bcd0-5dbb218b4d56)

The problem seems only with AutoISF (but that needs to be tested) and since the arrival of Dev F. Last dev E was working OK.

Here are the logs. See around 19:11

![AndroidAPS_LOG_1734027130885.log.zip](https://github.com/user-attachments/files/18117453/AndroidAPS_LOG_1734027130885.log.zip)

**Comment by vanelsberg** [comment]
FYI: Dev-e, commit#6f3e937, "fix careportal layout" is ok.

**Comment by Josch24** [comment]
Dev-e was ok till 09.12.2024. Dev-e from 10.12.2024, has the Problem. Picture is from last dev-e, that was working ok. 
![Screenshot_20241212-211924](https://github.com/user-attachments/assets/d015553f-cfe6-4ce9-b7e6-b9c4bef1ff08)

**Comment by MilosKozak** [comment]
does it creash without AutoISF?

**Comment by robertrub** [comment]
Nope. I switched to OpenSMB to test and it seems to work ok. Didn't check with the watch really but no more progression barre stuck on the main UI.

**Comment by Josch24** [comment]
Without autoISF, on Standard SMB, everything is ok. Also Watch is getting BG immediately.

**Comment by vanelsberg** [comment]
Confirming: Have been running OpenSMB/DASH for one hour now. No issue...

**Comment by robertrub** [comment]
@MilosKozak Just had the _black screen then the UI "refilling"_  when BG came in and the loop kicked in **but** I was using OpenSMB !!!

So, not only an AutoISF problem...

**Comment by MilosKozak** [comment]
i don't see the issue. Please go commit by commit to find out which broke it for you
