### ISSUE TITLE
[Dev] "Send logs by email" not working without selecting AAPS Directory

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#3618]
Works fine in AAPS. But in AAPSClient nothing happens when I click the button.

![Screenshot_20241214_124910_AAPSClient2](https://github.com/user-attachments/assets/3ce13f2f-ce2c-4e6a-a18c-95b5a1672dd7)

**Comment by olorinmaia** [comment]
I had to select folder for AAPS storage for it to work. But that shouldn't be necessary as logs are stored else where?

**Comment by MilosKozak** [comment]
it needs temporary storage to be able send attachment
