### ISSUE TITLE
[Dev] Can't click to delete carb entries without clicking inside checkbox

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#3619]
Minor "bug". Also present in Master.

https://github.com/user-attachments/assets/b095e150-c0ff-4561-a6c5-c6eaf9697439

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/b8f4cf8606a687bf65cbdce45f5842025fcaf7c1

**Comment by olorinmaia** [comment]
Thanks for looking into this @MilosKozak 

I can select it now, but entry isn't deleted. See video below.


https://github.com/user-attachments/assets/6f3bf424-3267-4b9b-a1dd-92fee91a0fd1

**Comment by MilosKozak** [comment]
and https://github.com/nightscout/AndroidAPS/commit/72e44ebe620d3a7324b8b6e5f9260716a64f9787
