### ISSUE TITLE
[Dev] NSv3 full sync isn't getting boluses except for Smb and sync stops

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#3622]
AAPSClient2 3.3.0-dev-f
NSCLIENT
Build: b9686af643-2024.12.14
Remote: https://github.com/nightscout/AndroidAPS
Flavor: aapsclient2release
Nightscout version: 15.0.2
Engineering mode enabled 

Logs
[AndroidAPS_LOG_1734183665898.log.zip](https://github.com/user-attachments/files/18136095/AndroidAPS_LOG_1734183665898.log.zip)

First did a fresh install or clear database of AAPSClient. Then doing a full sync on AAPSClient with NSv3. Expect to get same iob as AAPS. Seem to be missing boluses except for smb. 

![Screenshot_20241214_144100_AAPSClient2](https://github.com/user-attachments/assets/1818936f-4c6a-41e6-97ee-b4856577ba57)

AAPS

![20241214_144041](https://github.com/user-attachments/assets/efe59656-6f8f-4484-9698-098a7494f608)

**Comment by olorinmaia** [comment]
AAPS is running and getting bg but AAPSClient is spamming in the logs and not updating. Attaching more logs.
[AndroidAPS_LOG_1734184080437.log.zip](https://github.com/user-attachments/files/18136119/AndroidAPS_LOG_1734184080437.log.zip)


Video
https://photos.app.goo.gl/7yNNiW2TZxfUnSXq6

**Comment by MilosKozak** [comment]
nothing interresting in logs
if it's replicable pm me NS credentials

**Comment by olorinmaia** [comment]
Pm'd you credentials, but no. NSV3 log say insert bolus, but not recorded to NS treatments or displayed on graph.

**Comment by MilosKozak** [comment]
this is probably NS or mongo issue

**Comment by MilosKozak** [comment]
for me it works

**Comment by olorinmaia** [comment]
Related to https://github.com/nightscout/AndroidAPS/issues/3623 I think

**Comment by MilosKozak** [comment]
i did a few tries (bolus wizard) using virtual pump a everything is synced correctly to Client
