### ISSUE TITLE
[3.3.x. Beta] Client 1 + 2, COB displayd negaitve after neg. Carb Correction, Broadcasting to Client 1 for Dual Wear display won't work after that

### ISSUE THREAD

**Issue by gerison77** [nightscout/AndroidAPS#3624]
AAPSClient2 3.3.0-beta1
NSCLIENT
Build: 9209de1dd0-2024.12.11
Remote: https://github.com/nightscout/AndroidAPS
Flavor: aapsclient2release
Nightscout-Version: 15.3. dev

Rig Master: N6000 - Diakem G7 - G7, Android 12, Ticwatch Pro 3, Wear 3.5

Some Time after entering neg. carbs. COB was displayed negative on the graph. Some time later Client 2 stopped broadcasting to Client 1, no data of Client 2 in dual watch face. 

I did a full database reset, which didn't work. After a reinstall of Client 2, broadcasting was working again.

![Screenshot_20241215-020849](https://github.com/user-attachments/assets/42523d4f-30c5-4935-8e23-c9cc3c96c61c)

Logs are sent via email

**Comment by Philoul** [comment]
Log should be sent to your own mail, then files attached here.
You can also connect phone on computer and copy log files.
When you have this kind of issue o. AAPSClient, having the equivalent screenshot on main app of your child can help analysis...

**Comment by gerison77** [comment]
Logs added. Would be a screenshot from history of mein app suffice?

**Comment by MilosKozak** [comment]
this is fixed in dev and will be part of next beta
