### ISSUE TITLE
3.3.0-beta1 Combo pump pair screen fails to load Android 15

### ISSUE THREAD

**Issue by twinning92** [nightscout/AndroidAPS#3633]
Started losing connection to the pump after updating Android today to v15. Attempted to unpair/re-pair but upon opening pair window, nothing loads.

I will note that Android complains that the app has been "built for an older version of Android" when I attempt to toggle the permission. 

Logs attached, combo logging seems to start around 22:59:49

build version: 9209de1dd0-2024.12.18
[AndroidAPS[2].log](https://github.com/user-attachments/files/18184870/AndroidAPS.2.log)

**Comment by MilosKozak** [comment]
resolved in https://github.com/nightscout/AndroidAPS/commit/a8cee9f06ab6d15ad4a536eb3cf62fef9c3ee40a
