### ISSUE TITLE
[3.3.0-rc1] Blue bar on whole graph on entering note on specific pont of time

### ISSUE THREAD

**Issue by gerison77** [nightscout/AndroidAPS#3643]
on entering a note on a particular point of time 
![grafik](https://github.com/user-attachments/assets/4753600b-aba0-49e8-8098-432136363e18)
the whole screen is cover with a blue bar, way back  into the past 3.3.0-rc1
![grafik](https://github.com/user-attachments/assets/e0d8a15e-abe8-46d4-821c-225aa83b8ec4)

**Comment by vanelsberg** [comment]
AFAIKSL Solved in current 3.3.0-dev-g
