### ISSUE TITLE
Large time difference DanaRS + Unihertz Jelly Star

### ISSUE THREAD

**Issue by chrissie7** [nightscout/AndroidAPS#3645]
Hi,
I keep getting the message that there is a large time difference between pump and smartphone, but every time I check the time, pump and smartphone have the same time, not even one minute difference.
What I tried so far:
• automatic timezone --> off
• automatic time -->off
• Pump clear history
• unpair and pair pump
• Phone power off and on a few times a day
• Reset smartphone and installed new build AAPS
• Change language settings in English

I had this alarm with two different Dana RS pumps (6yrs old and 2 yrs old) and two different smartphones (Unihertz Jelly Star + Unihertz Jelly 2)

Phone is always in airplane mode, only online 1-2x per week for data upload.
I‘ve attached pictures and the last log, alarm occured at : 10:31:09.536

Thanks.
Christina

![1734602728890](https://github.com/user-attachments/assets/64e11229-bdf3-420c-95db-794100819dbd)
![1734602728901](https://github.com/user-attachments/assets/2efbb921-8ef1-418e-82b8-3c5f728ccf9c)
![1734602728911](https://github.com/user-attachments/assets/4d747337-2caa-4d71-8810-d67ce8c058a2)
![1734602978355](https://github.com/user-attachments/assets/515cb999-adc8-4301-848a-382f07f08574)
![1734602978368](https://github.com/user-attachments/assets/0d30fcf2-8407-46a3-beb4-1d6e25751829)
![1734804659962 - Kopie - Kopie](https://github.com/user-attachments/assets/9d46649b-a1d9-4249-a28c-0ab91dde12d4)
[AndroidAPS._2024-12-19_10-36-13_.16.txt](https://github.com/user-attachments/files/18219534/AndroidAPS._2024-12-19_10-36-13_.16.txt)

**Comment by MilosKozak** [comment]
the message should be fixed by https://github.com/nightscout/AndroidAPS/commit/393f3fe0cf819a06c2612c2c94970bb1e26127b7
.... but the primary reason is unstable comm with pump. try different phone, pump ....
