### ISSUE TITLE
[DEV] Medtrum settings does not show current setting

### ISSUE THREAD

**Issue by jbr7rr** [nightscout/AndroidAPS#3655]
dev 0a29d84c4f96e04e39391077239af9d3c52c1a7

In the settings screen the current setting is not shown anymore:
![afbeelding](https://github.com/user-attachments/assets/58e2f1e6-1852-442e-92a2-81b4375ae4a1)

Compare this to the screenshot in the wiki (which is master 3.2):
![afbeelding](https://github.com/user-attachments/assets/4913eeb3-9a5a-4815-98ca-b91224de4637)

I have looked into the code, but could not find any obvious reasons why this is happening

**Comment by MilosKozak** [comment]
migration from xml to `BooleanKey`... style will resolve it

**Comment by jbr7rr** [comment]
This is not fixed, PR was for a different issue

**Comment by robertrub** [comment]
I confirm, on last dev, the information is only visible when I tab on the lines and nothing gappens when I tap the serial number line

![Screenshot_20241229_123312_AAPS](https://github.com/user-attachments/assets/6e4568c6-feac-4109-a21f-0f6632653fd3)
