### ISSUE TITLE
Automation profile% can be set at 135% - but cannot be executed

### ISSUE THREAD

**Issue by Sneepie** [nightscout/AndroidAPS#3656]
A profile switch Automation can be set at 135% (type the numbers).

However, the automation won't start when profile% is set at 135.
(dev version 26 dec 2024). 

![share_3808440895573697182](https://github.com/user-attachments/assets/8cf18c1f-cb1f-44fd-bd21-8b66584644cc)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/3dd68a5a4f07d840dd3d3ddf4bd9cb41a9080bb3
