### ISSUE TITLE
[3.3.0-rc1] Actions tab buttons reordered

### ISSUE THREAD

**Issue by vmichalec** [nightscout/AndroidAPS#3661]
I just wonder if those two buttons are swapped intentionally or by mistake (compared with previous version).

![AAPS_Actions](https://github.com/user-attachments/assets/effbc46f-64d3-479e-9780-35c2c9565198)

**Comment by olorinmaia** [comment]
They are swapped to not make UI so stretched for pump that doesn't have prime/fill. E.g. Dash. See https://github.com/nightscout/AndroidAPS/pull/3337

**Comment by vmichalec** [comment]
Okay, I'll get used to it.
