### ISSUE TITLE
Why Equil pump ver 5.2 not supported ?

### ISSUE THREAD

**Issue by henrycoding** [nightscout/AndroidAPS#3664]
Is there any problems when adapting this pump for AAPS?

**Comment by MilosKozak** [comment]
It doesn't support BT connectivity as we need

**Comment by henrycoding** [comment]
but, I have captured the communications between my pump and PDA,  which seems like BT-LE packes
![Uploading WX20250102-104529@2x.png…]()

**Comment by MilosKozak** [comment]
yes, it's BLE but AAPS driver "understands" only 5.3
