### ISSUE TITLE
AAPS 3.3.0: Main Menu Button CGM no longer visible/nor activates DiaKEM DEX G7 App (BYODA) 

### ISSUE THREAD

**Issue by Arne1346** [nightscout/AndroidAPS#3665]
Hi,

on my phone I run just the DiaKEM Dexcom G7 for gathering CGM readings. AAPS is getting those directly from there via the BYODA config.
Till 3.2.0.4 I could activate and display the CGM button on the AAPS main screen. When pressing it brought me straight away to the DiaKEM Dexcom G7 App.

With AAPS 3.3.0 activating the button in AAAPS' config is still possible, but it does not show up on the main screen.

This is really unhandy as I now need to switch to the Dexcom app manually everytime I need to confirm or temporarily disable alarms.
Please make sure that this gets fixed and the CGM button works as previoulsly.

thank you

**Comment by olorinmaia** [comment]
Strings where adjusted based on @MilosKozak statement in Discord.
See  https://github.com/nightscout/AndroidAPS/pull/3627

**Comment by MilosKozak** [comment]
Impossible for Android 11

**Comment by Arne1346** [comment]
Thanks for having realized this "Impossible for Android 11" and already closed issue with AAPS 3.3.1.1. -- works perfectly with Android 15
