### ISSUE TITLE
Properly validate duration and inform user when sending TBR via SMS

### ISSUE THREAD

**Issue by samspycher** [nightscout/AndroidAPS#38]
When sending a TBR via SMS, any duration > 0 may be defined from the perspective of the core application.

However, `Pumptype` defines the property `tbrSetting` as a `DoseSetting`, which contains a `durationStep`. This property prescribes increments of duration in which TBRs should be passed. E.g. a `durationStep` of 30 should only allow for sending durations of 30, 60, etc. 

Since the core only responds with "Wrong format" when Pumps invalidate an incorrect duration, users will be confused about what exactly they did wrong, e.g. if they send "BASAL 1 20".

Sending a PR shortly to submit a fix for this issue.

**Comment by bartsopers** [comment]
@MilosKozak this has been fixed in #39 and can be closed.
