### ISSUE TITLE
Delta show and go back to 0

### ISSUE THREAD

**Issue by mick711** [nightscout/AndroidAPS#392]
I use dev 2.8.2.1.dev c built 41c4aa
I dont know if it's thé patch #389 but now Delta show correctly few second and go to 0 .

![IMG_20210303_201510](https://user-images.githubusercontent.com/441734/109860461-79f80700-7c5e-11eb-8a60-785d92b21b9e.jpg)
![IMG_20210303_201519](https://user-images.githubusercontent.com/441734/109860498-89775000-7c5e-11eb-9db4-ecdff8d76029.jpg)

**Comment by swissalpine** [comment]
This is usually the result of a wrong configuration: AAPS receives the same blood glucose value twice in quick succession, so the delta then inevitably becomes 0.
Check your settings, e.g. deactivate "Autobackfill BG".

**Comment by Alamo04** [comment]
Confirmed.
Works until I update yesterday to the Dev, with your XDrip fixes, now Delta was also permanent 0.
Backfill missing values was enabled, disable them now and it works now - Delta is shown.

**Comment by mick711** [comment]
Thanks swissalpine i disable autobackfile BG and work again .
