### ISSUE TITLE
Feature request: Units left to inject while bolusing

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#396]
When a bolus injection has started, the same info is given twice on the same window: the total of units to be injected.

It would be nice if the upper part gave the total of U **to be** injected and the lower part indicated the units **left** to inject.

![20210305_201603](https://user-images.githubusercontent.com/76626474/110163501-6086c480-7df0-11eb-92b2-deeb0772c858.jpg)

**Comment by Philoul** [comment]
Good Idea, I agree the proposal...

**Comment by Philoul** [comment]
See screenshot of my dev phone (dev branch), it will be close to your proposal (Total in the upper part, not the unit left in the lower part but the injected Units)
![Screenshot_20210308-084607](https://user-images.githubusercontent.com/52934600/110290363-02720100-7feb-11eb-8106-2375bdd46ea7.png)

I think you can close this issue.

**Comment by robertrub** [comment]
Y§es, the translation is not good but we'll take care of that together ;)  x U ont étés injectées

**Comment by Philoul** [comment]
I corrected translation
