### ISSUE TITLE
[2.7.0] NSClient version - missing the "Virtual Pump" module

### ISSUE THREAD

**Issue by peterholubek** [nightscout/AndroidAPS#40]
Hi, I noticed a missing module in the NSClient version 2.7.0. It is the "Virtual pump" module in Configuration.

Thx for the Solution 😉

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/b4ff0889748bf3171ccbe2a3756da1e2e196d6e4
