### ISSUE TITLE
Sensor changes not being processed by AAPS from Dexcom patched app

### ISSUE THREAD

**Issue by guydavies** [nightscout/AndroidAPS#410]
Using 2.8.2.1-dev-d build 2ef91e681 this morning, I changed my Dexcom G6 sensor.  The sensor change was not recognised or recorded automatically in AAPS although the subsequent cathether change and refill of the pump were both automatically recorded.  I am sure that some time ago that this has worked, however, I also think that I have noticed at least one previous change to this latest one and probably two or even three (so maybe as much as a month of changes) have not been automatically recognised, I just haven't sat down and thought about it to report it.

I changed my set around 07:45-07:50 this morning.  I had to replace both the sensor and transmitter (for the first time) this morning, around that time.  The first time at which the reservoir is recognised as being full is around 07:54:45.957.

I notice that there is a dump (E/CORE) for OpenHumansUploader at 07:48:26.030 (probably unrelated but interesting)

I still had Automation logging turned on so there's rather a lot of noise but I've attached the logs from that time.  I think the sensor change would have been finalised around 07:35 - 07:45.  Sorry I cannot be more precise.  I also didn't have any logging of glucose or BGSOURCE active, so it's possible that there's no useful info there :-(

[AndroidAPS._2021-03-10_00-00-00_.1.log](https://github.com/nightscout/AndroidAPS/files/6116694/AndroidAPS._2021-03-10_00-00-00_.1.log)

**Comment by MilosKozak** [comment]
yes, the code is missing in the app. There is nothing what AAPS developers can do with this issue
