### ISSUE TITLE
Loop failed to calculate

### ISSUE THREAD

**Issue by JohnKitching** [nightscout/AndroidAPS#412]
I suspect I'm not going to be able to provide enough information to enable anything to be done but I'll try. 

When I woke up this morning BG was high (unusual) so I looked at what had happened. I thought Android might have killed AAPS or something but it hadn't. AAPS had been running all night but not doing anything. Just basal was being applied. I tried to manually run the loop calculation and it failed. Something about no APS selected. Sorry, didn't note the exact text. I restarted phone and that seems to have fixed it. 

I'll email logs now. 

NS screenshot showing what happened (the initial rise was entirely my fault, not AAPS)

![image](https://user-images.githubusercontent.com/48366213/110906773-55f29080-8304-11eb-9905-c92986182b63.png)

**Comment by Tornado-Tim** [comment]
If you scroll back to the time no basal changes took place, you will find out why you were not getting any Loop cycles.
