### ISSUE TITLE
Feature Request: additional information for Insight-Tab

### ISSUE THREAD

**Issue by zwackelfuss** [nightscout/AndroidAPS#413]
Migrating from Akku-check Combo to Insight, I am missing two simple but useful informations in the pump-tab:

a) show elapsed time between last connection and now
b) show time and amount of last bolus

![rect4535](https://user-images.githubusercontent.com/46249367/111036901-f68aa280-8421-11eb-9107-d100954f9e7c.png)

Both should not be a big deal, but helpful if dealing with connection issues.

Thanks for your great work!

**Comment by Philoul** [comment]
I think this issue can be closed (see screenshot of latest dev)

![Screenshot_20211009-093143_AndroidAPS](https://user-images.githubusercontent.com/52934600/136648935-a9a32e3e-baae-4c16-a33b-005e676f5cb5.jpg)
