### ISSUE TITLE
AndroidAPS restarts on bad blob of historical data from Medtronic pump

### ISSUE THREAD

**Issue by Amunhateb** [nightscout/AndroidAPS#418]
I am having an issue with AAPS restarting every 7-9 minutes. Judging by logs it is related to historical data incorrect date value. I've attached the log file. Issue could be found by looking up Exception.

[AndroidAPS._2021-03-04_15-24-25.log.zip](https://github.com/nightscout/AndroidAPS/files/6140163/AndroidAPS._2021-03-04_15-24-25.log.zip)

**Comment by Amunhateb** [comment]
@andyrozman here you go, thx for finding out the cause

**Comment by MilosKozak** [comment]
https://console.firebase.google.com/project/androidaps-c34f8/crashlytics/app/android:info.nightscout.androidaps/issues/297f1f2deabd18e680a04b3f5cf33672?versions=2.8.2%20(1500)&time=last-twenty-four-hours&sessionEventKey=60517F110369000151DE4ED6E5E43AEB_1518914798545604254

**Comment by andyrozman** [comment]
@Amunhateb Fix is now done in this branch, please install and test if this fixes everything... I have run it through my history decoded and all entries seem to be correct now. Please write here so that I can then do PR so that it can get released in next version. 
https://github.com/andyrozman/AndroidAPS/tree/bug418_historyFix_BolusWizardRecordProblem

**Comment by Amunhateb** [comment]
@andyrozman I've tested it. Everything is good, thx.

**Comment by duzy78** [comment]
I am experiencing similar problem but it looks that different field is problematic (dayOfMonth)

[AndroidAPS_2.8.2.1-dev-build.log](https://github.com/nightscout/AndroidAPS/files/6163704/AndroidAPS_2.8.2.1-dev-build.log)

Should I log in as a separate problem or should it be fixed along with this one?
The log is from the branch with potential fix for problems with parsing historical data.
If you need more data please let me know.

**Comment by andyrozman** [comment]
@duzy78 Create separate ticket please... While the end result seems to be the same (that date can't be parsed), this doesn't mean that there is a same base problem...

**Comment by andyrozman** [comment]
PR was opened: https://github.com/nightscout/AndroidAPS/pull/430 and merged into dev. Closing this issue.

**Comment by Amunhateb** [comment]
> PR was opened: #430 and merged into dev. Closing this issue.

https://github.com/nightscout/AndroidAPS/pull/422 is the correct PR. Thanks for fixing it!

**Comment by andyrozman** [comment]
@Amunhateb I have created special hotix branch that is based on master and contains all 3 medtronic fixes: https://github.com/andyrozman/AndroidAPS/tree/hotfix_mdt_2_8_2
