### ISSUE TITLE
NSClient: allowed state is not restored when re-entering allowed wifi

### ISSUE THREAD

**Issue by tanja3981** [nightscout/AndroidAPS#419]
I have the nsclient connection settings set to "wifi only".
Since a couple of minor versions I noticed that nsclient does notice when I leave wifi and sets the status correctly to "not allowed". However, it doesn't detect when I'm back and connected to wifi, status stays "not allowed".
Restart of AAPS helps, so I guess there is some event lost that would trigger the network evaluation.

See screenshot: I left the house around 7.45h but was back home at ~ 8.15h.
![Screenshot_20210315-121033](https://user-images.githubusercontent.com/7403966/111145547-a9751080-8588-11eb-80b4-be99b1213564.png)

**Comment by MilosKozak** [comment]
what version?

**Comment by tanja3981** [comment]
@MilosKozak Sorry, I forgot to mention it.
It's version 2.8.2!

**Comment by MilosKozak** [comment]
it works properly in current dev
