### ISSUE TITLE
AndroidAPS is stopped when processing Medtronic pump history

### ISSUE THREAD

**Issue by duzy78** [nightscout/AndroidAPS#423]
It has happened on AndroidAPS 2.8.2. It is 100% reproducible since it started, so AAPS is being restarted every time pump sends history. 
Phone: Samsung Galaxy S7 (Android 8.0)
Pump: Medtronic 715 (firmware 2.3A)
RileyLink

After changing battery in insulin pump, application started to stop during retrieving historical data from insulin pump.
From log it looks that parsing of history is causing the problems:
org.joda.time.IllegalFieldValueException: Value 0 for dayOfMonth must be in the range [1,31]

[AndroidAPS_2.8.2_history_parsing_problem.log.zip](https://github.com/nightscout/AndroidAPS/files/6163923/AndroidAPS_2.8.2_history_parsing_problem.log.zip)

**Comment by andyrozman** [comment]
PR was merged, so this is fixed... Problem was BGReceived512 entry... It should work correctly now...

**Comment by andyrozman** [comment]
https://github.com/nightscout/AndroidAPS/pull/448

**Comment by andyrozman** [comment]
Since this was merged into dev we can close it...

**Comment by andyrozman** [comment]
@duzy78 I have created special hotix branch that is based on master and contains all 3 medtronic fixes: https://github.com/andyrozman/AndroidAPS/tree/hotfix_mdt_2_8_2
