### ISSUE TITLE
Merge Buttons Insulin + Bolus (wish / suggestion) 

### ISSUE THREAD

**Issue by doraberta** [nightscout/AndroidAPS#44]
(I hope I'm right here with my wish) 
I think it would be good if the two buttons "Insulin" and the additional "Bolus" could be combined in one. There are not many differences, only "Eating Soon-TT", "carbohydrates" and the "insulin amounts to be pre-assigned".
Background:
I miss the insulin defaults in the bolus button and the carbohydrates in the insulin button.

Rgds
Dirk

**Comment by MilosKozak** [comment]
what is additional Bolus ?

**Comment by doraberta** [comment]
Hi Milos,
sorry for the bad explanation. I mean these both buttons:
![Bolus](https://user-images.githubusercontent.com/46416185/97147781-57af2380-176a-11eb-8fcc-6b48804dbd8f.jpg)
![Insulin](https://user-images.githubusercontent.com/46416185/97147789-5a117d80-176a-11eb-97db-5cf073260d3d.jpg)

**Comment by MilosKozak** [comment]
integrating everything into one button would lead to dialog with too many option. and this is something I don't want for most used dialogs.
combined button was requested by people who are not using calculator to be able enter both at once

so I don't plan to change it
