### ISSUE TITLE
combination of (AND + OR) is not possible in automation

### ISSUE THREAD

**Issue by TranceCake** [nightscout/AndroidAPS#450]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem:
  I am trying to set this event in automation: IF ((bg >= 7 AND delta >= 0.3) OR bg >= 10)

Setup
![setup](https://cdn.discordapp.com/attachments/629954570394533889/826420168178663484/Screenshot_20210330-133706.jpg)

First result
![result](https://cdn.discordapp.com/attachments/629954570394533889/826420219420475402/Screenshot_20210330-133715.jpg)

Trying the other way around
![flipped AND and OR](https://cdn.discordapp.com/attachments/629954570394533889/826420282507788318/Screenshot_20210330-133735.jpg)

Second result
![second result](https://cdn.discordapp.com/attachments/629954570394533889/826420333238026260/Screenshot_20210330-133741.jpg)

I expected the inner clause and outer clause to have different operators (AND/OR) but they are the same.
So only the outer AND/OR selector seems to work and it sets all operators and not just the one on the outer clause

- Build Version: 
  AAPS 2.8.2
  14559a01f-2021.03.25-12:57

- Logs:
  Will add shortly when I have access to a computer

**Comment by robertrub** [comment]
I confirm. I couldn't create a mix of *and* + *or* conditions.

**Comment by TranceCake** [comment]
it was brought to my attention that you can achieve this if you first select all condition and then fill in the values. This is not intuitive, it took me 3 tries to understand it. This could maybe use a UX pass, to which I'm happy to contribute!
