### ISSUE TITLE
Pump command send 

### ISSUE THREAD

**Issue by mick711** [nightscout/AndroidAPS#467]
Pump command send to pod at the same time BG reading by xdrip and fail 
Can its possible to aaps to wait that BG reading end before send the command ?
On aaps de can see time when last BG reading so i hop its possible.

**Comment by MilosKozak** [comment]
it's not possible to synchronize anything with xdrip.
this seems to be a BT issue in your phone.
Try another phone

**Comment by mick711** [comment]
It's not for syncronise with xdrip, just aaps know when BG is reading by xdrip so when BG is at 4,50 second for exemple just aaps can wait to send command to Omnipod
