### ISSUE TITLE
Automation Screen Cut off

### ISSUE THREAD

**Issue by Thomas-Wolff** [nightscout/AndroidAPS#471]
I have noticed a small problem in the automation. The right screen is cut off (see screenshot). Latest version AAPS 2.8.2, occurred on a Samsung Galaxy A40 after an update to Android 11 UI version 3.1. Maybe you can take a look at this and optimise it. Otherwise, I am very satisfied with AAPS, respect to all those who have contributed here.
Best regards Thomas
![Bild1](https://user-images.githubusercontent.com/59526802/114373887-58eed400-9b83-11eb-8068-7df9778e7d8a.png)

**Comment by MilosKozak** [comment]
there is no solution. layout is rendered by Android
