### ISSUE TITLE
Dexcom-G6-App will stop operation after May 12, 2021

### ISSUE THREAD

**Issue by rICTx-T1D** [nightscout/AndroidAPS#473]
Hi folks, 
Iam using patched dexcom g6 app in version 1.5.1.5 dxcm3. After every start a notification will be shown that the program will cancel after May 12, 2021. 
( Creation of screenshot was denied)

How can I get a newer version they works with AAPS? The last version from [github](https://github.com/dexcomapp/dexcomapp/tree/master/2.4) is older than 2 years.

**Comment by Alamo04** [comment]
Hier kannst du dir die neue erstellen.
https://docs.google.com/forms/d/e/1FAIpQLScD76G0Y-BlL4tZljaFkjlwuqhT83QlFM5v6ZEfO7gCU98iJQ/viewform

In this version you can also activate broadcast to XDrip, or AAPS, or both.

**Comment by MilosKozak** [comment]
as above

**Comment by rICTx-T1D** [comment]
Thanks, @Alamo04
