### ISSUE TITLE
Starting Objective 7

### ISSUE THREAD

**Issue by mathewmarko** [nightscout/AndroidAPS#481]
Upon starting Objective 7, when you change your preferences to raise the max IOB above zero and go back to check progress, it does not credit you with completing the "Maximal IOB Set Properly" task.  After trying every possible setting, I finally figured out the only way to get the Objective calculator to accept it was to turn off looping and then turn it back on.  

Perhaps there could be a note about that in the objective instructions so more people don't pull their hair out?  :-)

**Comment by Andries-Smit** [comment]
@MilosKozak Issue is probably fixed by https://github.com/nightscout/AndroidAPS/commit/c211c2e4c3abf1b71557751e58b02088cbe062e1 ?
