### ISSUE TITLE
Enter carbs  externally via nightscout

### ISSUE THREAD

**Issue by Simonsaccount** [nightscout/AndroidAPS#492]
Hi,

I wanted to ask, weather I did a mistake in my configuration or if the feature is missing:
I would like to be able entering carbs externally via nighscout - this would make it more easily for me to use the nighscout REST-API to add entries for example with my gramin smartwatch (no google wear).
However once I manually enter carbs in NS they do not appear in AAPS and thus are not considered in the loop.

Is there an option I missed to activate or is it intended that carbs can only be entered through the AAPS-Interface?

Best regards,
Simon

**Comment by Tornado-Tim** [comment]
Nightscout Syncing via Pull is disabled in the latest version of AAPS as its a security risk. You can enable it still, but needs to explicit and involves several steps.
The Wiki has details.

**Comment by Simonsaccount** [comment]
Hi Tim,
thanks for clarifying that it can work. I guess You are hinting towards this article, right?
[https://androidaps.readthedocs.io/en/latest/Installing-AndroidAPS/Nightscout.html?highlight=sync#androidaps-settings](https://androidaps.readthedocs.io/en/latest/Installing-AndroidAPS/Nightscout.html?highlight=sync#androidaps-settings)

I made sure that download from NS should be enabled. Under the Nightscout-Client Panel I confirm that the treatments seem to be received correctly in AAPS. They are however still not shown or considered in the algorithm.

Am I still missing a step?

**Comment by MilosKozak** [comment]
do you have NS UPLOAD ONLY set to off?

**Comment by Simonsaccount** [comment]
yes for sure.
Upload is working fine. And datalog shows that treatments are received correctly. I currently use V2.8.2.

![Screenshot_20210502-192959~2](https://user-images.githubusercontent.com/29257323/116822217-e5d2ef00-ab7d-11eb-9de6-be9273998689.png)

**Comment by MilosKozak** [comment]
you don't have enabled engineering mode and proper NSClient settings

**Comment by Simonsaccount** [comment]
No I am currently on master-branch. So do I need to switch into Dev? Please elaborate.

**Comment by MilosKozak** [comment]
https://androidaps.readthedocs.io/en/latest/Installing-AndroidAPS/Releasenotes.html?highlight=release%20notes#version-2-8-1-1

**Comment by Simonsaccount** [comment]
Thank You. Works like a charm now :)
