### ISSUE TITLE
Predefined Temporary Target for Activity is allowed be set in preferences up to 220. This is ok but is not recognized when the button ist pressed. Then 180 is the maximum which is set. Please allow the correct maximum which is set in preferences.

### ISSUE THREAD

**Issue by Duester64** [nightscout/AndroidAPS#506]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/EN/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/469054135a5c8cee23f238eb80a0806ab30e6707
