### ISSUE TITLE
Autosense calculation with empty sensor data

### ISSUE THREAD

**Issue by aendes** [nightscout/AndroidAPS#540]
Hello,

I am using Version 2.8.2 with xdrip and G6 Sensor.
I had a sensor which i was not able to start for about 6h (waiting 2h each time).
After that autosense was on max. Value (140%).

For me it looks like autosense includes the empty values.
My expectation would be, that autosense stops calculation after long time without sensor data?

Thanks for your help

Andreas

**Comment by MilosKozak** [comment]
autosens is based on 8h and 24h data
