### ISSUE TITLE
[dev-e5] NS some careportal events are updated in NS and removed or lost a few hours later

### ISSUE THREAD

**Issue by Philoul** [nightscout/AndroidAPS#552]
Issue with Insulin Age, Sensor Age and Site Change (I don't know if it's the same for other CP events...)
When I update this information in AAPS, it's updated in NS, but a few hours later (I didn't understand exactly what is the trigger, but I think the day after), these informations are "lost in NS (but remains Ok in AAPS)

1rst screenshot the 4th of june in the evening (14 hours after insuline and Site change) information Ok in NS (note it's the same for sensor change but last change was 3 days earlier so KO in this screenshot)
2nd screenshot the 5th of june in the morning, information is removed
![NSlost](https://user-images.githubusercontent.com/52934600/120918722-26aab000-c6b6-11eb-91af-4636671c8edb.jpg)

**Comment by Philoul** [comment]
Yesterday same issue (I changed Insulin and site in the morning and sensor in the afternoon)
=> 10 hours after Insulin and site change (and immediatly after sensor change), everything was correctly updated in NS, but about 2 hours later, information lost in NS...

![Screenshot_20210610-191442_Chrome](https://user-images.githubusercontent.com/52934600/121731128-d0dc6a80-caf0-11eb-81d1-86b6792ad52a.jpg)

Unfortunatly no log available (bug in latest dev)...

**Comment by swissalpine** [comment]
Seems related to https://github.com/nightscout/AndroidAPS/issues/456

**Comment by Philoul** [comment]
@swissalpine 👍 it's the same issue...
