### ISSUE TITLE
TDD and basals in statistics change when profile switch is made

### ISSUE THREAD

**Issue by Vlin-der** [nightscout/AndroidAPS#56]
I was running a 120% profile for a few days and took a screenshot of my Statistics:
![Screenshot_20201029-133909](https://user-images.githubusercontent.com/46421525/97607299-168c6d00-1a11-11eb-9416-130508dfde4d.jpeg)

Then I did a 100% profile switch and took a new screenshot of my Statistics:
![Screenshot_20201029-133953](https://user-images.githubusercontent.com/46421525/97607401-34f26880-1a11-11eb-98b7-c47c873dee27.jpeg)

The values for TDD and Basals had changed, which shouldn't happen after a profile switch.

Logs (date, time of occurence: October 29th, 13:39):
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/5460095/AndroidAPS.log)

Using AAPS v 2.7.0 on an Android 7.0 phone

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/edd5dd7980cbeeb349179494121375ed22e148d3
