### ISSUE TITLE
Android 11 problems

### ISSUE THREAD

**Issue by mcm2007** [nightscout/AndroidAPS#574]
Hello, so i recently updated my samsung a20e to android 11 and he has some problems now than he didnt had in android 10 just like: Bomb disconnects and dont reconnect (i have to rebbot the phone to connect and it just works for a minuts) and when im in other app he just swipes up to AndroidAPS for it own!
Hoep you figure it out fast. Regrades.

**Comment by MilosKozak** [comment]
this is not enough information to help you. Android 11 is supported and widely used
