### ISSUE TITLE
[2.8.2.2-Dev] Temporary basal does not reset to 0% when pump is disconnected

### ISSUE THREAD

**Issue by fjpezuela** [nightscout/AndroidAPS#581]
Reporting bugs
--------------

When disconnecting the pump, the temporary basal does not reset to 0% in the main AAPS screen.  The baseline value for that hour is displayed.  However, if you change the screen, you can see that the temporary basal is at 0%.
![Screenshot_20210625-080007](https://user-images.githubusercontent.com/67511778/123381938-a3cc9500-d591-11eb-9057-108702e00d9f.jpg)
![Screenshot_20210625-080026](https://user-images.githubusercontent.com/67511778/123381942-a4fdc200-d591-11eb-8465-9f27320ea5aa.jpg)

Version: 2.8.2.2-Dev Build 33047e478

**Comment by fjpezuela** [comment]
Add that I have disconnected the pump more times these days and it has not happened again. This may occur in certain circumstances that I am not aware of.

**Comment by MilosKozak** [comment]
ok, download logs if you see this issue again and open new issue
