### ISSUE TITLE
[2.8.2.2-Dev] The main screen sometimes does not show all glucose values

### ISSUE THREAD

**Issue by fjpezuela** [nightscout/AndroidAPS#583]
Reporting bugs
--------------
The main screen sometimes does not show all glucose values.  When changing the view to show the history of glucose values, many times only the last 4 hours are shown, and not the total of the hours set on the screen.

![Screenshot_20210625-075517](https://user-images.githubusercontent.com/67511778/123383745-d2e40600-d593-11eb-8eee-8676d27544df.jpg)

Version: 2.8.2.2-Dev build 33047e478

**Comment by Alamo04** [comment]
Confirmed
That happened if you change the view to a longer Timeline.
After the next value they are shown again
