### ISSUE TITLE
[2.8.2.2-Dev] Some texts and images are shown in English with language in Spanish

### ISSUE THREAD

**Issue by fjpezuela** [nightscout/AndroidAPS#585]
Reporting bugs
--------------
Using the Spanish language, some application options display texts and images in English.  For example, the buttons for time goals are displayed in English.  Many texts of the treatment part are shown in English.  A choice of the graphics is displayed in English.

![Screenshot_20210625-091316](https://user-images.githubusercontent.com/67511778/123385496-e42e1200-d595-11eb-9fe1-2716891519b2.jpg)
![Screenshot_20210625-091337](https://user-images.githubusercontent.com/67511778/123385499-e55f3f00-d595-11eb-8381-a7d9d41004b8.jpg)
![Screenshot_20210625-091405](https://user-images.githubusercontent.com/67511778/123385503-e55f3f00-d595-11eb-9529-b45af70b60b8.jpg)
![Screenshot_20210625-091443](https://user-images.githubusercontent.com/67511778/123385504-e5f7d580-d595-11eb-9dec-3820b21c32bf.jpg)

Version: 2.8.2.2-Dev Build 33047e478

**Comment by Alamo04** [comment]
This is not a master version.
Dev versions are still "under construction" and most of your reported issues are known by the developers.
So, if you don't find a realy bad issue, don't post it here.

After the dev, it comes a Release Candidate.
There you can look, search and test the version for issues and report everything you find.

**Comment by fjpezuela** [comment]
Hello @Alamo04 ! Yes, I agree with everything you say. I only created it by the post on Facebook that we created the tickets with all the problems we detected. It's not really a problem as such, but I decided to comment on it more than anything because I guess the developers will test the English versions more, and they may not be aware of this.

For me there is no problem in closing this ticket.

**Comment by MilosKozak** [comment]
Spanish translation is not finished. Let's do it on Crowdin ;)
