### ISSUE TITLE
[2.8.2.2 - dev] History browser navigation buttons do not work as expected

### ISSUE THREAD

**Issue by hartlijn** [nightscout/AndroidAPS#591]
1. with time-window set to 24h (=default) you can slide into the past with the < and >, but with time-window smaller than 24h you are not able to see more than 1 window per day.
Expected behavior is: the > and < buttons scroll to the next/previous time-window. 
example: choosing 6; you only see the first window of 6 hours for that day and you can't (or I don't know how) browse to the other 3 windows in that day.

2. the >| navigation buttons does not seem to do anything

**Comment by MilosKozak** [comment]
resolved in dev
