### ISSUE TITLE
[2.8.2.2 - dev] disconnect pump Dana RS gives error

### ISSUE THREAD

**Issue by hartlijn** [nightscout/AndroidAPS#594]
choosing Disconnect (for 30 mins), AAPS presents an error screen after the command to set a temp basal op 0%.
see log file timestamp 11:39..
![Screenshot_20210701-113914](https://user-images.githubusercontent.com/28272471/124103612-bf3c1200-da61-11eb-8a2c-3bd6eb422b17.jpg)
[AndroidAPS._tempbasal_errorlog.txt](https://github.com/nightscout/AndroidAPS/files/6747168/AndroidAPS._tempbasal_errorlog.txt)

**Comment by MilosKozak** [comment]
same as https://github.com/nightscout/AndroidAPS/issues/597

**Comment by hartlijn** [comment]
confirmed solved
