### ISSUE TITLE
[2.8.2.2-dev] unable to save local profile: error profile name contains dots upon save

### ISSUE THREAD

**Issue by hartlijn** [nightscout/AndroidAPS#596]
![Screenshot_20210702-230135](https://user-images.githubusercontent.com/28272471/124328403-d0803e00-db89-11eb-916c-bd46e8b958af.jpg)

When saving a profile *without* dots in its name an error occurs as stated.

**Comment by MilosKozak** [comment]
then name of any of your profiles contains dot

**Comment by hartlijn** [comment]
solved indeed.
NS does support it. A minor thing, but maybe change the error message to make clear that _one or more_ of the profiles contains a dot. From a user perspective you are working on one specific profile. Saving that profile results in an error, but the error is a general one (since AAPS saves/uploads all profiles at once).
