### ISSUE TITLE
[2.7] Engineering mode enabled per default

### ISSUE THREAD

**Issue by ArthurusDent** [nightscout/AndroidAPS#6]
Engineering mode is enabled per default. Right now I can't disable it. I removed the file and rebooted but engineering mode is still enabled as shown in About.

Phone: Oneplus 3T (Android 9)
Pump: Medtronic 554
xDrip+ G6

Logs:
[AndroidAPS.zip](https://github.com/nightscout/AndroidAPS/files/5283082/AndroidAPS.zip)

**Comment by goomStar** [comment]
Can confirm same behaviour.

**Comment by veterlch** [comment]
In my case, not using git check-out but using project from version control, I could build 2.7 master version.
(2.7.0-dev was made when I used git checkout).

I hope it will work for you.
