### ISSUE TITLE
[Feature Request] Show ABS Insulin Activity on Graph

### ISSUE THREAD

**Issue by joshbohmer** [nightscout/AndroidAPS#60]
Would be useful to have an option to visualise ABS Insulin Activity.

Currently we have IOB, IOB Activity & ABS as seen in the attached Screenshot.

![Screenshot_20201101-231512_NSClient](https://user-images.githubusercontent.com/3621222/97803156-1eaa0e00-1c98-11eb-9db6-15ee402c5734.jpg)

**Comment by MilosKozak** [comment]
this value doesn't help to anything
