### ISSUE TITLE
[2.8.2.2 - dev]  Target value not shown correctly on Home screen

### ISSUE THREAD

**Issue by MichaelJohnSmith** [nightscout/AndroidAPS#611]
I modified my local profile, changing both the high and low targets from 6.0 to 7.5, then saved and activated the profile at about 17:21.
I discovered the Home screen still showed a target of 6.0, both on the Profile button and on the graph.
![image](https://user-images.githubusercontent.com/55034864/126365958-f850c8b3-f0aa-4ec0-9ebd-3bc176de8f91.png)
I checked that the profile had be correctly saved.
The loop screen shows that the correct target, 7.5, is being used in calculations.
![image](https://user-images.githubusercontent.com/55034864/126366425-2922c252-88bb-4ae0-aeba-65c08bf83dcb.png)

![image](https://user-images.githubusercontent.com/55034864/126365008-825f1862-cf6b-4f59-8c5c-60f567ab82ae.png)
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/6850037/AndroidAPS.log)

Libre2 - OOP2 - Xdrip+
Dana-i pump
Samsung Galaxy A20e running Android 11
Just started Objective 6

**Comment by MichaelJohnSmith** [comment]
On setting a temporary target, the screen is updated as expected.  On ending the TT, the screen shows to the same, wrong, target value.

After a phone restart (and the consequent restart of AAPS), the correct target value is displayed.

So it seems that an App restart provides a work-around for this issue.

**Comment by MilosKozak** [comment]
resolved in dev
