### ISSUE TITLE
[2.8.2.2-dev] no refreshing of cob after entering carbs

### ISSUE THREAD

**Issue by dalilith** [nightscout/AndroidAPS#613]
After entering 30g carbs (18:09) via carbs button on the home screen cob where not updated. Even after getting new bg reading and loop calculation cobs are not up to date. Restarting aaps at 18:16 solved this problem.

 
![IMG_1417](https://user-images.githubusercontent.com/35224007/126824297-5751364a-b90f-4c8a-a22a-9ba90cca69f3.jpg)
![IMG_1419](https://user-images.githubusercontent.com/35224007/126824303-98e91194-5823-43e1-9d7f-f7a075ca648c.jpg)
[AndroidAPS._2021-07-23_18-16-14_.0.zip](https://github.com/nightscout/AndroidAPS/files/6870535/AndroidAPS._2021-07-23_18-16-14_.0.zip)

**Comment by MilosKozak** [comment]
should be resolved now
