### ISSUE TITLE
2.8.2.2 Dev : Insulin delivered message

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#639]
DASH driver (but same bug is also present in 2.8.2 main and EROS driver). 
The upper part says x U **will be** delivered. That message is ok. 
The lower part says x U _has been delivered_ when the x U has not been delivered yet.
Either show the real amount delivered (best solution) or a percentage for the sent amount (not very useful) or delete the lower message (easiest solution).
![IMG-20210820-WA0012](https://user-images.githubusercontent.com/76626474/130280150-b5c8a5ec-b945-4827-9639-a86578067099.jpg)

**Comment by Philoul** [comment]
The message included in Insight driver is the best I think (on each update of horizontal bar graph we have an update of text
"0.8 U/ 5.95 U has been delivered"
What do you think of moving some of the common pump strings in core to standardize User Interface and translation, and only keep in pump module specific strings?

**Comment by MilosKozak** [comment]
@Philoul does omni have this information?

**Comment by robertrub** [comment]
No, the same "error" is in Omni too. It says the same _xU (the full amount) have been injected_ when it is still in the process of injecting.

**Comment by MilosKozak** [comment]
resolved in https://github.com/nightscout/AndroidAPS/commit/77e3c736085a99c36c73eee0c3d915caa13eba47
