### ISSUE TITLE
[2.8.2.2 - dev] ISF lower than 2 mmol/l results in invalid profile

### ISSUE THREAD

**Issue by smokkelaar** [nightscout/AndroidAPS#640]
When setting the ISF lower than 2. it will not validate the profile.

![image](https://user-images.githubusercontent.com/35005706/130351535-43903f64-4ab1-447b-a977-ba9931d655e1.png)
![image](https://user-images.githubusercontent.com/35005706/130351620-3b47560f-0b7a-4ffb-93bd-939239089a66.png)

It was still working correctly in 2.8.2 main.

Couldn't find the exact build where it goes wrong.
Multiple people on discord could validate this issue.

**Comment by DM-LTR** [comment]
Same issue here with 2.8.2.2 dev - when ISF is set below 2.0, profile cannot be saved.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/a448efe09cfeb7c54e28c5d4c67783d30fc6d918
