### ISSUE TITLE
Always error message by delivering bolus, when the bolus amount 1.15U is. (Dana R, AAPS 2.8.2)

### ISSUE THREAD

**Issue by streethawk22** [nightscout/AndroidAPS#649]
This error is coming always when the bolus amount 1.15U is. I noticed it allready in sooner versions of AAPS (I thought it was sporadic), in version 2.x. And it is stil there, on the newest final version 2.8.2 too. 
For order, the bolus was always delivered correctly, only the message comes always, when the bolus amount exactly 1.15U is.

THX for fixing. We have the Dana R Insulin Pump.

Peter from Slovakia

**Comment by MilosKozak** [comment]
i tested current dev version for both (R and Rv2) and no error appeared.
Create new issue when you see this error in next version (or test dev)
