### ISSUE TITLE
[2.8.2.2-dev] Pump Site Change prime displayed as a normal bolus on graph

### ISSUE THREAD

**Issue by MichaelJohnSmith** [nightscout/AndroidAPS#650]
![image](https://user-images.githubusercontent.com/55034864/130977027-b6170b14-984f-439e-a5ff-43e4def13295.png)
Libre2 - Patched App - Xdrip+
Dana-i pump
Samsung Galaxy A20e running Android 11

Prime is handled correctly and not added to IOB, it is just displayed misleadingly as a bolus.

![Screenshot_20210826-090423_AndroidAPS](https://user-images.githubusercontent.com/55034864/130977320-e3812786-fedb-49ef-ad09-360f536f28cc.jpg)
![Screenshot_20210826-090449_AndroidAPS](https://user-images.githubusercontent.com/55034864/130977330-f152de9c-53d6-483e-8a22-76f2426f0e76.jpg)
![Screenshot_20210826-090503_AndroidAPS](https://user-images.githubusercontent.com/55034864/130977334-14167f28-63d6-4538-ba1e-2cdc1368f2f9.jpg)
![Screenshot_20210826-090819_AndroidAPS](https://user-images.githubusercontent.com/55034864/130977335-8d32ac97-71f6-411b-a03f-038b74c7e01b.jpg)

**Comment by MilosKozak** [comment]
resolved by https://github.com/nightscout/AndroidAPS/commit/c611674b3b1e240a7f5e587725815c2e74426817

**Comment by MichaelJohnSmith** [comment]
No longer displays bolus, but grey dot displayed without "Pump Site Change" message

![Screenshot_20210919-093112_AndroidAPS](https://user-images.githubusercontent.com/55034864/133945355-deb2f55c-cfa6-4172-abbe-be1ab8a4a8cc.jpg)

![Screenshot_20210919-093042_AndroidAPS](https://user-images.githubusercontent.com/55034864/133945357-de65f488-a740-46aa-bcef-3ef941d75ef2.jpg)

**Comment by MilosKozak** [comment]
resolved by https://github.com/nightscout/AndroidAPS/commit/a1a5fbaa4f5cb3a53b9890d3a9a9fb2946862c70
