### ISSUE TITLE
2.8.2.2 dev BUG : COB is zero if bolus canceled 

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#651]
I use the wizard, enter 40g carbs, it proposes the bolus and I "ok" it.

After 0.40 units, I cancel the bolus. Injection stops.

![IMG-20210826-WA0000](https://user-images.githubusercontent.com/76626474/131013803-57ff7940-fd6a-47d2-bdb4-089503f7d1cb.jpg)

I start again the wizard in order to recalculate the missing units. The wizards thinks that there are zero COB.

![IMG-20210826-WA0001](https://user-images.githubusercontent.com/76626474/131013863-49501957-433a-4e89-83a9-1b44ce20903f.jpg)

**Comment by MilosKozak** [comment]
hopeffuly resolved in https://github.com/nightscout/AndroidAPS/commit/b80e2a764894217c18b80c3b010760dcfabee2e0
