### ISSUE TITLE
Dev bug: NS profiles are overwritten with local profile

### ISSUE THREAD

**Issue by dexdan** [nightscout/AndroidAPS#652]
This is with DASH-AIMI code (build 0e4a6579e) on S20 but is thought to apply more broadly to aaps main dev.

Before this aaps version, I had previously used NS profiles, and had several profiles in NS. This aaps version only allows for local profile (fine for dev purposes). So I set up a local profile to use it. BUT now that seems to have deleted all the profiles I had in NS - all that is visible in NS is a new 'LocalProfile'.

Aaps shouldn’t be deleting previous profiles stored in ns.

**Comment by MilosKozak** [comment]
i updated AAPS to sync profiles with NS in setup wizard 
https://github.com/nightscout/AndroidAPS/commit/5411f4fb3c02ba6a85d142fcb31b0d7d0c824d52

**Comment by dexdan** [comment]
Great thanks
