### ISSUE TITLE
Move 'connecting for' message underneath profile / tt bar

### ISSUE THREAD

**Issue by dexdan** [nightscout/AndroidAPS#653]
Feature request. The 'connecting for' message covers the ability to change profile or temp target. It would be nice if it appeared underneath so you could change tt rather than waiting for the connection first.
![Screenshot_20210827-133945_AndroidAPS](https://user-images.githubusercontent.com/8146651/131138936-22da9420-b41d-4156-a277-5880a3861d0a.jpg)

**Comment by MilosKozak** [comment]
you can always use action tab
i tested this layout too but it's even worse because of jumping screen

**Comment by dexdan** [comment]
Fair enough.... Still do think this may be a bit of an issue though with dash where you may be waiting 40-70s for the pump
