### ISSUE TITLE
Objectives: question is not valid for Omnipod - user can not answer correctly

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#654]
AndroidAPS 2.8.2

**Problem:** Objectives for Omnipod users.

Asking user on _what to do when received less insuline than the pump history suggests..._
(see screenshot attached)

Omnipod users can never answer the question correctly.
Question apparently was compiled with standard "_external_" insulin pumps in mind.
With Omnipod there is no "**pump history**" to check.

As for Omnipod users there is no way to check if AAPS and pump agree on the amount of insulin received answer #4 ("Compare values in AndroidAPS and pump history") is wrong. But AAPS expects user to select it as true.

![Screenshot 2021-08-27 163657](https://user-images.githubusercontent.com/45144129/131144498-80bdfd88-7f2c-4a41-8640-d54e309da143.png)

**Comment by MilosKozak** [comment]
updated text https://github.com/nightscout/AndroidAPS/commit/3064fea60d46415408b9c10a44f540d1076f8a0f
