### ISSUE TITLE
error alerts alarms

### ISSUE THREAD

**Issue by notprogrammer** [nightscout/AndroidAPS#655]
Screenshots with the problem and time with the accompanying screenshot recording the date and time I send as attachments attached to this message.

The problem is alarms, see screenshot. I also noticed that the app at the top often reports that a basal profile has been updated. But I don't change the basal profile in any way. I use a local profile.

Circumstances when this happens are often when I have the phone in my hand, or. shortly after its postponement. But if I don't notice the phone, I rarely notice the problem.

I supply a screenshot of the assembly and logs as well.

Thanks very much for support.

[AndroidAPS._2021-08-27_02-10-34_.2.zip](https://github.com/nightscout/AndroidAPS/files/7069347/AndroidAPS._2021-08-27_02-10-34_.2.zip)
[AndroidAPS._2021-08-27_02-10-34_.1.zip](https://github.com/nightscout/AndroidAPS/files/7069348/AndroidAPS._2021-08-27_02-10-34_.1.zip)
[AndroidAPS._2021-08-27_02-10-34_.0.zip](https://github.com/nightscout/AndroidAPS/files/7069349/AndroidAPS._2021-08-27_02-10-34_.0.zip)
[AndroidAPS._2021-08-26_15-43-29_.2.zip](https://github.com/nightscout/AndroidAPS/files/7069350/AndroidAPS._2021-08-26_15-43-29_.2.zip)
[AndroidAPS._2021-08-27_02-10-34_.3.zip](https://github.com/nightscout/AndroidAPS/files/7069352/AndroidAPS._2021-08-27_02-10-34_.3.zip)
![Screenshot_20210827_203849_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187351-0ec06824-986f-4622-9334-6c163a49b6cc.jpg)
![Screenshot_20210827_203311_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187355-02f390fd-a71a-4f82-9f7a-3494e6109ce5.jpg)
![Screenshot_20210827_082017_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187358-b1ad0ff8-7584-490b-a9aa-aad1023d7741.jpg)
![Screenshot_20210827_194806_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187360-832b3444-2b29-4c61-b12a-2d4207b66a30.jpg)
![Screenshot_20210827_203326_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187362-7acf9eba-d91e-4784-892d-e9c2a7a4fbbf.jpg)
![Screenshot_20210827_164834_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187365-ec8f3b79-4917-4044-80b5-330a77a5531a.jpg)
![Screenshot_20210827_190326_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187367-8969fb34-6266-4029-9723-b5131b3b94d1.jpg)
![Screenshot_20210826_194622_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187370-26cc5fd0-ecc3-4f5f-b9c1-cfc2aea35d08.jpg)
![Screenshot_20210827_194809_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187373-48c413c7-f50b-411f-ba7c-99e3007bab0c.jpg)
![Screenshot_20210827_103820_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187377-329c4df0-986c-4dc7-bfef-b381b6134e55.jpg)
![Screenshot_20210827_190324_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187380-369ebd15-d88f-402c-b624-bc5e1e401520.jpg)
![Screenshot_20210827_202804_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187384-86013c4c-bb47-473b-93da-664b2f945006.jpg)
![Screenshot_20210827_195448_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187387-14626409-117b-4d39-9d9f-1cb98277c872.jpg)
![Screenshot_20210827_000603_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187389-8baae1e3-cdba-4c10-b7f9-81ed589b8d7a.jpg)
![Screenshot_20210827_094306_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187390-cf631f31-0b6a-49ff-8da6-c206f00c86fb.jpg)
![Screenshot_20210827_000559_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187391-f450c5e1-62a2-49b4-b0e4-036dd11d0f1e.jpg)
![Screenshot_20210827_154808_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187392-0b58b4d6-4d72-4c48-9c49-c0b4a002c895.jpg)
![Screenshot_20210825_200558_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187394-1a746599-6dea-46ed-87fd-6c23d8bbb30b.jpg)
![Screenshot_20210826_194645_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187399-c2050b3d-ea55-4910-bab9-52ccf40c6072.jpg)
![Screenshot_20210827_103827_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187401-cef38e8b-dd69-40c8-8e63-fc85e6cad26b.jpg)
![Screenshot_20210826_174137_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187402-9f2f2d79-2835-4d69-bf81-70419a046c57.jpg)
![Screenshot_20210827_094303_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187404-82f56efa-fa1a-4850-b817-701a60d52c57.jpg)
![Screenshot_20210827_154811_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187406-a6fb70fc-4e3e-4d20-8574-2249979dad88.jpg)
![Screenshot_20210827_202810_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187408-16cb24ee-7521-479c-b879-fce7fd5cc1b2.jpg)
![Screenshot_20210826_174142_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187410-29c6bbff-25e3-4f5e-b248-4592bdb4f998.jpg)
![Screenshot_20210827_195452_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187411-5e7dee11-79d8-4fb1-99ca-47b3667634d7.jpg)
![Screenshot_20210827_164832_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187413-f1c28720-7c1a-4672-85c3-16115b78403b.jpg)
![Screenshot_20210827_082009_info nightscout androidaps](https://user-images.githubusercontent.com/21248300/131187416-1f793748-fe1b-42de-9966-e2856354f064.jpg)

**Comment by MilosKozak** [comment]
this is old AAPS version which is not supported anymore.
and btw the problem is in NS profile sync which is disabled by default in latest AAPS (because of this issue)
