### ISSUE TITLE
Allows for a max basal out of hard limits to be set on dash pod on >100% profile switch

### ISSUE THREAD

**Issue by dexdan** [nightscout/AndroidAPS#657]
** Issue moved from dash branch - please refer to https://github.com/0pen-dash/AndroidAPS/issues/94 for attachments ***

Local profile was set with a basal rate of 10u/hr. I did a profile switch to 200%. Message quickly appeared to say 'profile set ok', v soon followed by message ' is out of hard limits. 20 limited to 10'.
HOWEVER the pod was not updated with a 10u/hr rate and counting clicks confirmed that 20u/h wax being delivered (66 clicks over 10min). ALSO display indicated 10u/h despite 20u/h being delivered.
I also monitored identical behaviour with 150% profile
Build 51709c2-2021.08.16-01:42
Samsung s7.
Screenshots (inc profile) attached and logs attached from the 200% and 150% examples.

**Comment by MilosKozak** [comment]
dev is update with more profile checking 
https://github.com/nightscout/AndroidAPS/commit/ba71e0db9b68af67c31dcbde560c73886294fb2d
