### ISSUE TITLE
Last dev update pb activate profile

### ISSUE THREAD

**Issue by MTR93600** [nightscout/AndroidAPS#671]
when you activate the local profile, I get the message min target profile is out of hard limits
I try withy 90, 100, 110, 120
same message for all the value

**Comment by MilosKozak** [comment]
paste screenshot of profile

**Comment by MTR93600** [comment]
we are several. tester with the same bug
here the screenshots
![photo_2021-09-14_21-44-05](https://user-images.githubusercontent.com/44895345/133323647-b0d1241e-9615-4e7a-9863-ca4ab31e65e9.jpg)
![photo_2021-09-14_21-44-19](https://user-images.githubusercontent.com/44895345/133323649-27e2f67b-935d-47a3-9376-212dd489f54d.jpg)
![photo_2021-09-14_21-44-14](https://user-images.githubusercontent.com/44895345/133323650-4f2da9a9-fc9d-46df-aec6-845b0b10c63d.jpg)
