### ISSUE TITLE
loop icon don't show after disconnect the pump

### ISSUE THREAD

**Issue by MTR93600** [nightscout/AndroidAPS#674]
if I disconnect the pump for 15 minutes, when I come back to close loop, the icon don't change, the time is still running like in overview the action didn't happen.
![photo_2021-09-15_15-35-55](https://user-images.githubusercontent.com/44895345/133443540-7f084c70-09b2-479c-872e-b7bc6ebc3b1d.jpg)

**Comment by MTR93600** [comment]
At the end of the three minutes left, the icon change to loop

**Comment by MTR93600** [comment]
it's in the last commit dev version

**Comment by Philoul** [comment]
There are currently several bugs in "Loop Dialog" (I made a PR to fix them) :
"Reconnect pump" button missing when pump state is disconnected, "Enable Loop" button missing if loop is disabled...
=> In your Screenshot, I think you tried to reconnect your pump before the end of duration (and without Reconnect button in dialog it's difficult!)

@MilosKozak can you please take a look on #634 and tell me if it's ok for you or if you want some modification ? (This PR fix the bugs of current dev, improve the user interface compared to current master, and the code is simplified to be easier to maintain)
