### ISSUE TITLE
[OMNIPOD & RILEYLINK/ORANGE] Communication failed : Nonce resync failed 

### ISSUE THREAD

**Issue by Okanami** [nightscout/AndroidAPS#676]
Hello,

After 2 days of my omnipod ( two in a row ), AAPS starting to show an error code "Communication failed : nonce resync failed"
Omnipod play the beep song if i press on it on page management but not bolus/basal/suspend, any order work, they always end by "Communication failed : nonce resync failed"

Restarting BT, phone, RL/OrangeLink etc.. don't work.
I can't either desactivate the pod.
I'm on AAPS 2.8.2

[https://imgur.com/a/l5N02Ov](url)

**Comment by Alamo04** [comment]
Hi @Okanami 

Perhaps it helps, but I'm a Medtronic user and everything is working fine on my side.
Did you updated your OL with the newest Firmware 2.6 ?

> 

OrangeLink and OrangeLinkPro Firmware v2.6

    Fix Hardware version number, for OrangeLink = HW is v1.0, OrangeLinkPro = HW v1.1
    Enhanced RF connectivity stability
    Fix low battery bug, disabled Vibrator and Buzzer when battery low triggered.

> https://getrileylink.org/orangelink-firmware
