### ISSUE TITLE
Minor bug / 2.8.2. Master and 2.8.2.2. dev / Duration of canula and insulin after déactivation

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#677]
A minor bug, I'm not sure if it is necessary to resolve... Using Onmipod EROS (on 2.8.2 main) and DASH (2.8.2.2 Dev)
The time counter for canula and insulin age is reset to 0 when the pod is **activated**. This works well. 
If you **deactivate** the pod BUT **do not restart another one** rapidly, the insulin age and canula age continue counting. There is no more canula or insulin but AAPS says that the age is overdue.

DASH deactivated at 79h
![image](https://user-images.githubusercontent.com/76626474/133881555-cecf6a87-1b74-43fb-9833-fae5d09422b8.png)

And here is the screen capture a couple of hours later...
![image](https://user-images.githubusercontent.com/76626474/133881566-7af34f9f-4fe2-4a61-b50a-d8860bee4ae0.png)

It would be better to reset the canula / insulin age to 0 when pod is deactivated and stop counting till pod activation. 

As we usually put in a new pod just after deactivation of the old, I'm not sure if this bug needs to be solved.

**Comment by MilosKozak** [comment]
this time is time elapsed since last reset. there is no way to keep it zero
