### ISSUE TITLE
COB Issue - Time was shown under COB

### ISSUE THREAD

**Issue by Alamo04** [nightscout/AndroidAPS#679]
@MilosKozak 

I think a mistake happened with last merge.

The actual time was shown under the active COB, see screenshot:
![Screenshot_20210919-131352](https://user-images.githubusercontent.com/36486505/133925580-62e4d4ad-2508-4949-9001-a36eb01a9924.png)

You can close this Issue, if you are aware of it.

**Comment by Philoul** [comment]
@Alamo04 It's temporary for debugging...

**Comment by Alamo04** [comment]
Then it can be closed. 👍
