### ISSUE TITLE
2.8.2.3 Dev / DASH : No pod activated but UI shows a basal distribution

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#684]
I have built the latest version via the DASH branch. No pod is activated but AAPS is showing a basal blue line on the graph. 

Built this morning

![image](https://user-images.githubusercontent.com/76626474/134378609-dbae7776-7d87-460a-82dd-2be1023e8f78.png)

The graph

![image](https://user-images.githubusercontent.com/76626474/134378868-550015cb-d390-4db3-a8e9-f59b70055ceb.png)

**Comment by MilosKozak** [comment]
for DASH contact DASH devs
