### ISSUE TITLE
[Dev] [Bug]Intermittent Issue with Delta values not being passed from glucose_status to _determine_basal

### ISSUE THREAD

**Issue by tim2000s** [nightscout/AndroidAPS#689]
In the current Dev code, the values for Delta, Short Average Delta and Long Average Delta are not always passed to determine_basal. 

Screenshots attached showing example where none is showing up on either the GUI main screen or in openAPS SMB in spite of a change in glucose value of 32 mg/dl. Dev build listed in image. 

Logfile also attached. 

![Screenshot_20210924-164031_AndroidAPS](https://user-images.githubusercontent.com/14833174/134703074-9fc5a28b-c1ca-4b94-a1fa-40cd0af767ce.jpg)
![Screenshot_20210924-164039_AndroidAPS](https://user-images.githubusercontent.com/14833174/134703081-3fd851fd-5358-4d9f-87a7-848a846758ba.jpg)
![Screenshot_20210924-164047_xDrip+](https://user-images.githubusercontent.com/14833174/134703085-f9114f94-2043-4a8a-9690-4708009ebad2.jpg)
![Screenshot_20210924-153559_AndroidAPS](https://user-images.githubusercontent.com/14833174/134703087-5a6f3696-11b8-49f7-a452-dd5fb7961848.jpg)
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/7226925/AndroidAPS.log)

**Comment by dexdan** [comment]
Likely linked to https://github.com/0pen-dash/AndroidAPS/issues/104

**Comment by MilosKozak** [comment]
it's caused by your wrong setup: doubled BG values with identical timestamp.
G6 is smoothing old values and you are probably synchnonizing them elsewhere which breaks it

**Comment by tim2000s** [comment]
If there are dual glucose entries for each point, then the backfill from NS must be picking up additional data from Dexcom bridge in Nightscout which has the same value and a slight time delay. I'm surprised that the backfill from NS would pick this up and use it, but I think that explains the problem. 

I wonder how many others use dual feeds to NS for redundancy purposes?

**Comment by MilosKozak** [comment]
I don't know your setup but for Dexcom patched app + aaps is recommended for NS upload

**Comment by tim2000s** [comment]
> I don't know your setup but for Dexcom patched app + aaps is recommended for NS upload

Yes. Nightscout upload is configured via AAPS. There is also an upload via Share, which had the Bridge component enabled in Nightscout providing an alternative route. 

The key difference between master behaviour and Dev behaviour is that in the Dev version, the dual values are being recognised and generating incorrect delta data. In master, this wasn't happening. 

It looks like the Dev handles duplicate timestamps differently.

**Comment by MilosKozak** [comment]
Double upload can cause only troubles. Keep only AAPS which handles backward smoothing properly

**Comment by MilosKozak** [comment]
Previous versions didn't upload smoothed values to NS

**Comment by vanelsberg** [comment]
@MilosKozak I do not agree on the way it seems to works now:

When in AAPS user **explicitly defines a BG source** (xDrip, or any other BG source then NS) it should ignore BG information from NS. This includes complaining about double values....

Imho AAPS version 2.8.2.9 is introducing a dependency to NS that is not needed or even unwanted:
User should be able to configure AAPS to not download *any* data from NS ("upload-only" as was available for 2.8.2)

Please see also https://github.com/nightscout/AndroidAPS/issues/857

**Comment by vanelsberg** [comment]
@MilosKozak 
> I don't know your setup but for Dexcom patched app + aaps is recommended for NS upload
I do not see what this has to do with the Dexcom. Same goes for any other "BG source"

What you are saying is the AAPS does not accept *any* BG source writing values to NS even if it does not need or use these values? I can not see the point in this...
