### ISSUE TITLE
2.8.2.3 dev Automation does not color profile %

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#693]
More of an infirmation mini bug.
When an automation kicks in a _profile %_ and _TT_ change, in 2.8.2 master, both informations are in yellow 

![20210926_100534](https://user-images.githubusercontent.com/76626474/134800669-c12cd5ec-32c3-4f66-beeb-7a70f036463a.jpg)

In 2.8.2.3 dev (build a55eb0623) the profile % stays black.

![20210926_100615](https://user-images.githubusercontent.com/76626474/134800695-1af983ae-c3be-4709-8af7-a593e1c499cf.jpg)

It would also be nice to add a space between the name and the percentage...

**Comment by Philoul** [comment]
I can take a look into the code for the missing yellow background 😉

**Comment by MilosKozak** [comment]
resolved by https://github.com/nightscout/AndroidAPS/commit/214078b47740ce1b7e37be11c30ef9c470103e26
