### ISSUE TITLE
 Objective 1:Failed retrieve time

### ISSUE THREAD

**Issue by xialff** [nightscout/AndroidAPS#696]
Objective 1 Error.
Prompt:Failed retrieve time
AAPS 2.8.2

**Comment by MilosKozak** [comment]
this is cause by your internet connection, try anoter one

**Comment by xialff** [comment]
I will try.
Thank you very much,.

**Comment by evansyuyu-droid** [comment]
I have the same issue but not working under several different networks. How did you solve this? Thank you.
