### ISSUE TITLE
[2.7] connection to pump get lost

### ISSUE THREAD

**Issue by thomasmenges** [nightscout/AndroidAPS#72]
During the day and also night it could happen, after receiving a new BG value from rhe patched dexcom app that the pump connection get lost.

AAPS is stil waiting for a result from  the pump. New BG values are coming in but AAPS isn't activating a new connection to the pump and still waits for a not coming result of the pump.

Exit AAPS and starting AAPS again helps to solve the problem diretly.

Why can't AAPS recognize that the pump does'n't delivers results for SMB or temp basals after a defined time and restarts tAAPS ?

By the way the closed issue whichvdescribes my problem couldn't solve my problem.

I have already reinstalled AAPS for severeal times and all accu optimizations on my phone are switched off.

![20201114_090035](https://user-images.githubusercontent.com/37514390/99157872-2375b580-26cd-11eb-8ca2-a9ad5ab6892b.jpg)

**Comment by MilosKozak** [comment]
turn on pump debugging , and provide logs with time of occurence.  this not enough to be able to help you

**Comment by thomasmenges** [comment]
Attached you can find the log.zip file.
Time is difficult to say because I recognize the problem only after some time when  temp basals or SMBs aren't done anymore.

Try to use 09.00  and some minutes before.

[AndroidAPS_LOG_1605308881804.log.zip](https://github.com/nightscout/AndroidAPS/files/5545208/AndroidAPS_LOG_1605308881804.log.zip)

**Comment by MilosKozak** [comment]
logs doesn't conataing that time. do what said and provide logs on next occurence

**Comment by thomasmenges** [comment]
Here is a new log file. Please use time 17:32

And 2 new screen shots

[AndroidAPS_LOG_1605544633665.log.zip](https://github.com/nightscout/AndroidAPS/files/5548400/AndroidAPS_LOG_1605544633665.log.zip)
![20201116_174441](https://user-images.githubusercontent.com/37514390/99282234-b9c3eb80-2833-11eb-8251-72cd873ef5ee.jpg)
![20201116_174513](https://user-images.githubusercontent.com/37514390/99282253-be889f80-2833-11eb-89cb-befafab9eab1.jpg)

**Comment by MilosKozak** [comment]
Pump failed to set TBR and this state was not properly reported to loop tab
fixed by https://github.com/nightscout/AndroidAPS/commit/6f7cfdd06dba07907a8dd4781182d12e9d4424b5
