### ISSUE TITLE
eCarbs over time are wrong commited to NS

### ISSUE THREAD

**Issue by Alamo04** [nightscout/AndroidAPS#721]
[DEV 2.8.2.5] from 08.10.2021 20:33]

This and the all the last Dev versions entered eCarbs over time as a single entry (undefined) in NS.

If I say AAPS to do a treatment about 60gr eCarbs, starting at 7:00pm and lasts 2 hours, then everything is fine in AAPS.

But in NS the entry was shown as 60gr carbs at 7:00pm (undefined) without any hint, that they are eCarbs over time.

Because I use NS for my 3 month reports, they will be wrong if that will stay this way

Logs attached

![Screenshot_20211009-112938](https://user-images.githubusercontent.com/36486505/136653018-e33fea55-29eb-49bd-b8e7-615f03790ae0.png)
[AndroidAPS_LOG_1633771518559.log.zip](https://github.com/nightscout/AndroidAPS/files/7315343/AndroidAPS_LOG_1633771518559.log.zip)
m.

**Comment by MilosKozak** [comment]
NS must be upgraded to support carbs with duration
