### ISSUE TITLE
SMS command LOOP RESUME does not work

### ISSUE THREAD

**Issue by maskac** [nightscout/AndroidAPS#73]
AAPS version 2.7.0

After loop paused SMS command LOOP RESUME resposne loop resumed, but nothing will happen.

In SMS look everting OK.

![image](https://user-images.githubusercontent.com/16052233/99197464-f55aa900-2792-11eb-8211-f801406153f4.png)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/0cdcc8f1c2a9d45e9e19b48c6dd66e83698b9506
