### ISSUE TITLE
[3.0-dev] delta values reset to 0 when updating historic BG values from Nightscout

### ISSUE THREAD

**Issue by savek-cc** [nightscout/AndroidAPS#760]
For BG values I have xDrip+ performing a local broadcast and upload to Nightscout.
AndroidAPS accepts BG values from xDrip+.
If NSClient is set to "Receive/backfill CGM data", AAPS will first receive the new BG value from xDrip+ - and then receive the same value again from NS - only that receiving the value from NS causes all delta calculations to be reset to 0 and thus the closed loop is effectively and permanently disabled.

**Comment by MilosKozak** [comment]
xdrip doesn't handle timestamps with NS correctly thus records get doubled with slightly different timestamps and delta become zero. it's xdrip issue
