### ISSUE TITLE
[3.0-beta1] Incorrect COB

### ISSUE THREAD

**Issue by AndyS117** [nightscout/AndroidAPS#788]
## Condition / Lead up
AAPS Version: v3.0-beta1 build 24a277bf1
Nightscout: 14.2.2
Pump: DanaRS (v3, Model: 05, Protocol: 11, Code: F0)
CGM: DexcomG6 (Patched App)

10/27/2021 08:35 - Food (35g) & Bolus 3.37U
10/27/2021 09:15 - Checked Overview & noticed 60g COB

Cross checked COB in Treatments & Loop. All showing as 60g.
Suspect that original 35g was somehow doubled, NS issue?

## Observations

No issues with CGM or Pump comms

## Attachments

- Treatments
- Overview
- Loop
- Preferences/NSClient
- Logs

![Screenshot_20211027_091518_info nightscout androidaps](https://user-images.githubusercontent.com/38948885/139029823-743f47b4-1059-46c8-ba07-1c1f57361782.jpg)
![Screenshot_20211027_091524_info nightscout androidaps](https://user-images.githubusercontent.com/38948885/139029828-c2e8ff23-5523-4b2d-9793-a40d66add1a5.jpg)
![Screenshot_20211027_091540_info nightscout androidaps](https://user-images.githubusercontent.com/38948885/139029832-ed5742d2-e5b9-45fd-abf2-3b38cb35e3f1.jpg)
![Screenshot_20211027_092602_info nightscout androidaps](https://user-images.githubusercontent.com/38948885/139029804-247d5d64-4d89-4bac-b685-007105d53449.jpg)
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/7424511/AndroidAPS.log)

**Comment by Philoul** [comment]
I got same issue today...
![image](https://user-images.githubusercontent.com/52934600/139531536-c639de3e-41cb-47f7-971c-ec20ebcc6c05.png)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/345a57da09453c4528a470f669e192d048fddc18
thanks to all
