### ISSUE TITLE
[3.0-beta1] Medtronic SMBs show as Meal Boluses as well as Incorrect IOB calculation from temp basals

### ISSUE THREAD

**Issue by siggy226** [nightscout/AndroidAPS#798]
1. Using Medtronic, SMBs initially show correctly, but after 10-15 minutes get changed to appear as meal boluses.  I read issue  #739, was unclear what that setup was (I've never heard of a Dexcom app uploading to NS).  In my setup, only AAPS is uploading to NS, and switching to Dash driver with all other settings identical shows SMBs correctly.
![image](https://user-images.githubusercontent.com/65743481/139304184-ade157aa-dfbf-4c64-be8a-7cf879abef80.png)

2. When AAPS has set a 0 temp basal for 30 or 90 minutes it is applying the full negative IOB, even though a new rate is set after the next loop.  In this case, a 90 minute 0.00 basal was set at 2:14, the full 90 minutes of IOB was deducted.  At 2:19, 0.00 was set again for 90 minutes, and the full 90 minutes of IOB was deducted, even though those rates only actually ran for 5 minutes each.  Same occurred at 2:39AM with 30 minutes of IOB deducted even though it only ran for 5 minutes.
![image](https://user-images.githubusercontent.com/65743481/139303108-36559621-d0cf-4c2a-beb0-18f2125b5f3b.png)

**Comment by jroth-haj** [comment]
@andyrozman do you need more logs?

**Comment by andyrozman** [comment]
I think I know where the problem lies, so I am trying to fix it (TBR one), problem with boluses is little more global, and will require more investigation.
@siggy226 will you be able to test this, as soon as I am done with fix? Should be done by end of day on sunday.

@jroth-haj If you can help test this, this would be great... Are you experiencing the same problem?

**Comment by andyrozman** [comment]
So both fixes are ready in my branch, if you guys could test it. I don't have SMB on my test device, so I couldn't test it myself... 
@siggy226  @jroth-haj 

https://github.com/andyrozman/AndroidAPS/tree/bug798_meal_tbr

**Comment by siggy226** [comment]
@andyrozman I can build later today and test

**Comment by siggy226** [comment]
@andyrozman SMBs look good.  Thank you!

Temp basals/IOB are still an issue (see 3:05 and 3:40 entries).  I tested by enacting some high temp targets to get a 0.00 u/hr rate, then cancelling the temp target to trigger loop to restart an actual rate.  Profile basal at this time is 1.3 u/hr.  Manually refreshing pump history a few times didn't make any changes.
![image](https://user-images.githubusercontent.com/65743481/139599393-5826c202-2890-45a3-ba17-14fbac98fd7f.png)

I also noticed that AAPS is a bit all over the place with display though as well:
Pump shows 4.95 (which matched what loop requested), 29 minutes remaining:
![image](https://user-images.githubusercontent.com/65743481/139599560-86050be4-669a-458c-81b2-d45b498082a7.png)
Treatments shows the rate of 4.95 started:
![image](https://user-images.githubusercontent.com/65743481/139599527-34e275dc-a1b3-4d9b-b2a7-50fcf7fb125d.png)
MDT tab shows 5.0 (rounded from 4.95), but 13 minutes remaining:
![image](https://user-images.githubusercontent.com/65743481/139599484-625ea17a-a78f-446d-9fe4-a123f0fe80b1.png)
Action tab says I can cancel a rate of 2.80:
![image](https://user-images.githubusercontent.com/65743481/139599495-a26731c1-fa6a-4ef0-9f1c-ff0d666f1605.png)
Home shows scheduled basal of 1.75, but graph shows an increased rate:
![image](https://user-images.githubusercontent.com/65743481/139599513-9572da87-b892-4e3f-9d43-d13e89c0ea0a.png)

Logs:
[AndroidAPS._2021-10-31_12-48-43_.log](https://github.com/nightscout/AndroidAPS/files/7449714/AndroidAPS._2021-10-31_12-48-43_.log)

**Comment by andyrozman** [comment]
Ok, so I found the problem, and its real whooper... It seems that Zero TBR are not time limited (when normal TBR is cancelled we get cancel command in history (rate=0, duration=0), this doesn't happen if we have standard Zero TBR, so duration shown (and taken by us is always full one)... The problem was there since the beginning and nobody noticed this before...

I know what I need to fix, and I will do it in next few days... I will send notification here when its ready to be tested...

**Comment by siggy226** [comment]
Thanks for the effort.  I'll be on the lookout and ready to test.

**Comment by andyrozman** [comment]
I checked in the fix, so both issues should be fixed. Can you please check it if it works for you... @siggy226

**Comment by siggy226** [comment]
@andyrozman Installed today and testing.  Initial test, the fix looks good.  I will let it run for a while and report back.

**Comment by siggy226** [comment]
@andyrozman It handled 9:15 and 9:35 correctly, but at 10:00 continued to accumulate the negative IOB for the full 60 minutes:
![image](https://user-images.githubusercontent.com/65743481/140661359-cb15f6bf-c928-4d4e-b108-3902fa1ef7a6.png)
[AndroidAPS._2021-11-07_09-05-29_.log](https://github.com/nightscout/AndroidAPS/files/7493065/AndroidAPS._2021-11-07_09-05-29_.log)

**Comment by siggy226** [comment]
@andyrozman I tried 2 installs, the first over the top of the last build.  On initial connection to the pump while reading history AAPS would crash and restart.  I then cleared data, uninstalled and did a fresh install.  This ran for a short time, but then again entered a loop of read history > crash > restart.
I attached the recent log, but can grab further back if you need them.
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/7501031/AndroidAPS.log)

**Comment by andyrozman** [comment]
@siggy226 
So I looked at both logs... The first one is done with older version of App... The second actually had a problem. I refactored code a little so it should work now... Please let me know...

**Comment by andyrozman** [comment]
@siggy226 Any news about this? Does it work now?
