### ISSUE TITLE
[2.7.0] SMBInterval uses always the default 3 minute value

### ISSUE THREAD

**Issue by the-swish** [nightscout/AndroidAPS#8]
The setting could be set from 3 min to 10 min but determine-basal uses always the default value of 3 min.

In DetermineBasalAdapterSMBJS.java
` mProfile.put("SMBInterval", sp.getInt("key_smbinterval", SMBDefaults.SMBInterval));`
should be
`mProfile.put("SMBInterval", sp.getInt(R.string.key_smbinterval, SMBDefaults.SMBInterval));`

The dialog limits the value to 3 to 10 but the SMBDefaults.java mention the value could be 1 to 10 and determine-basal.js limits it also only to 1 to 10.

**Comment by MilosKozak** [comment]
good catch !
fixed by https://github.com/nightscout/AndroidAPS/commit/c2c1fc15e63d69fdd2da35eb3e915b3c4cfcc721
thanks
