### ISSUE TITLE
cant import prefs on new phone

### ISSUE THREAD

**Issue by bryce2071** [nightscout/AndroidAPS#803]
hi
i have a new phone and exported prefs on old phone aaps 2.8.2
if reimporting on new phone, aaps 2.8.2 i get error:
row 6: yellow !: huawei vog-29 (HWVOG) ... this is my old phone
row 7: red x: konfig file manipulated

**Comment by MilosKozak** [comment]
then the file was not transferred to new phone properly (file is changed)
