### ISSUE TITLE
[AAPS3.0_beta2] Incorrect insulin amt shown after new pod activated.

### ISSUE THREAD

**Issue by tjbain** [nightscout/AndroidAPS#805]
Slow, but gradual beeping sounds after I deactivated a  DASH pod. Started a new pod, but beeping continued. Several screens showed 50u, despite the pod being full (pics attached). Force closing the app didn't solve the problem. Beeping stopped once I deactivated the new pod, but screen shows "unknown pod failure". Everything happened starting around 2:45am.

New Pod works like normal, but screens still show 50u in yellow, despite having a full pod.

AAPS3.0 Beta2
G6 CGM
Dash pod
Samsung Galaxy Note 20 5G

[AndroidAPS_LOG_1635501672753.log.zip](https://github.com/nightscout/AndroidAPS/files/7445504/AndroidAPS_LOG_1635501672753.log.zip)
![Screenshot_20211029-025707_AndroidAPS](https://user-images.githubusercontent.com/43968079/139514574-6c485560-f46e-49d6-b7fb-7f78aa9ea24d.jpg)
![Screenshot_20211029-025713_AndroidAPS](https://user-images.githubusercontent.com/43968079/139514570-048cf94b-f6e2-4b91-8bc2-7a3256a825a5.jpg)
![Screenshot_20211029-025718_AndroidAPS](https://user-images.githubusercontent.com/43968079/139514567-184f9447-45b7-4c96-ad87-1aacb3902784.jpg)

**Comment by vanelsberg** [comment]
The amount showed is correct.
It is the amount of insulin needed (as reported by the Pod) to activate. Includes the 0.3U to prime the canula on canula insertion.

**Comment by MilosKozak** [comment]
Ominipod cannot report reservoir value above 50U
