### ISSUE TITLE
[AAPS3.0_beta2] NSClient - Cant select NS Profile

### ISSUE THREAD

**Issue by old-square-eyes** [nightscout/AndroidAPS#808]
NSClient but probably also AAPS... I can't select my profile. Error below...

<img width="362" alt="image" src="https://user-images.githubusercontent.com/25760491/139517697-eac06956-4639-4334-b9b9-2a1aca509d7b.png">

And not sure what the "reuse..." string/button is in the below...

<img width="406" alt="image" src="https://user-images.githubusercontent.com/25760491/139517742-7f10b014-5ae3-4cc2-a30c-225d2a178014.png">

**Comment by old-square-eyes** [comment]
I changed the DIA to 7 and now I can select it. But it doesn't apply. I tried creating a new manual profile in NS, and NSClient can see it, and select it but I get the same. It doesn't apply.

**Comment by old-square-eyes** [comment]
<img width="385" alt="image" src="https://user-images.githubusercontent.com/25760491/139519091-010ed59b-2911-44e7-8c5d-01ae517d9c7d.png">

And...

<img width="667" alt="image" src="https://user-images.githubusercontent.com/25760491/139519099-7fb67ea5-36c0-44c0-853b-a3ac4fd1cc84.png">

**Comment by Alamo04** [comment]
In v3.0 only local profiles are allowed. 

You can download NS profiles into your local profiles and sync them, but using is only allowed for local profiles.

Perhaps that's the problem ?

**Comment by old-square-eyes** [comment]
@Alamo04 - OK I'll try again. Hopefully that improves #807 and no plot too :)

**Comment by MilosKozak** [comment]
MAX DIA if limited to 7hours

**Comment by MilosKozak** [comment]
buton text is fixed by https://github.com/nightscout/AndroidAPS/commit/3a33529307da30810ae273123cda12cb0f1743f6

**Comment by MilosKozak** [comment]
there is profile functional change. see release notes

**Comment by old-square-eyes** [comment]
@Alamo04 I made @MilosKozak change https://github.com/nightscout/AndroidAPS/commit/3a33529307da30810ae273123cda12cb0f1743f6 and now I don't seem to have the ability to access my NS profile at all. Not even to make a local copy like you suggested. Though I'm still battling sync issues :(

**Comment by old-square-eyes** [comment]
@MilosKozak can we please reopen this. I will rename it.

1. My NS sync finally complete
2. I couldn't download my NS OpenAPS profile so I created a manual, local one.
3. I saved, and activated the profile but NSClient still says "NO PROFILE SET"

I still have no data on my plot (but it's in the history browser)

**Comment by old-square-eyes** [comment]
Here is a video...

https://user-images.githubusercontent.com/25760491/139558488-da2a9849-dbb5-45d9-bb88-0e0f403ed91a.mov

**Comment by Alamo04** [comment]
Don't know what you have done, but it seems to be a user problem.

You can try to do a fresh installation:
- save your preferences
- deinstallation of AAPS 
- restart phone
- New installation of AAPS
- restart phone
- load your preferences
- control all settings that they are correct

Didn't have more ideas.

**Comment by Alamo04** [comment]
Check all NightScout client settings, what you want to use.

![Screenshot_20211031-105504](https://user-images.githubusercontent.com/36486505/139577672-8cd47a4d-fdb5-4526-bd36-d3daaa2bd674.png)

**Comment by Alamo04** [comment]
Profile creation and set in AAPS.
![Screenshot_20211031-112034](https://user-images.githubusercontent.com/36486505/139578168-bb913513-26b3-41f3-bf71-b53a66b6d755.png)

![Screenshot_20211031-112515](https://user-images.githubusercontent.com/36486505/139578213-da16a278-7f42-4b54-9272-b00f5762bda1.png)

**Comment by bchris21** [comment]
> I changed the DIA to 7 and now I can select it. But it doesn't apply. I tried creating a new manual profile in NS, and NSClient can see it, and select it but I get the same. It doesn't apply.

I had the same issue when installed the Beta2. You have to change at least one basal in order for the profile to be applied. Once applied then change it back to the normal one.

Hope it helps.

**Comment by Alamo04** [comment]
You can also read this tread, with that problem:
https://github.com/nightscout/AndroidAPS/issues/771#issuecomment-955699907

**Comment by old-square-eyes** [comment]
@Alamo04 and @Philoul Changing % as suggested in #771 still does not set a profile. I am on beta 3 now.

All I see on the main page is "PROFILE NOT SET". I have set a manual local profile. And I even deleted at basal segment so it's not the same as before.

**Comment by old-square-eyes** [comment]
@MilosKozak can we please reopen. I'll update the tile to be beta 3.

**Comment by old-square-eyes** [comment]
@MilosKozak I'm getting a reproducible crash using the "copy profile" button.

**Comment by MilosKozak** [comment]
the create new issue for that
