### ISSUE TITLE
[AAPS3.0_beta2] NSClient - Cant silence alarm while sync in progress

### ISSUE THREAD

**Issue by old-square-eyes** [nightscout/AndroidAPS#809]
While setting up fresh and (still, presumably) syncing NS data, the main graph doesn't display, not do any of the info pills/widgets or profile. Basically most features don't seem to work.

I got a loud "last loop" 30 minutes ago alarm in NSClient, because I walked away from my OpenAPS rig.

While NSClient is in this state there is no way to snooze or dismiss this alarm. I had to turn my phone off until I had returned to my rig and another loop completed.

**Comment by MilosKozak** [comment]
what phone do you have? full NS sync is pretty CPU consuming

**Comment by old-square-eyes** [comment]
Galaxy S20.

**Comment by MilosKozak** [comment]
probably because of busy bus
hopefully this helps https://github.com/nightscout/AndroidAPS/commit/ff1a9b24dbd3a36361171aa85ff8eed54f8cb003
