### ISSUE TITLE
TDD/Statistic not calculated

### ISSUE THREAD

**Issue by dalilith** [nightscout/AndroidAPS#810]
In both versions 3.0beta1 and 3.0beta2 no TDD or statistic is calculated using DanaI.
![82A2A6BD-5411-49C7-B632-4DDAA502ADCE](https://user-images.githubusercontent.com/35224007/139530894-c496d5a6-403f-4bc1-b983-84d058b39065.jpeg)
![85D8B21F-9CAB-4FFA-87DA-06672F2A6CEB](https://user-images.githubusercontent.com/35224007/139530902-e3a0f80c-9e4f-4d36-9fdd-6a2a41988ea3.jpeg)
`
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/7446397/AndroidAPS.log)
`

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/2582240556b75f887e820f4f319bed2c99a847b2
