### ISSUE TITLE
Data from another pump 

### ISSUE THREAD

**Issue by dalilith** [nightscout/AndroidAPS#811]
3.0 beta1 and beta2 show the same issue. If i go to Dana/History and reload the TDD i get  „data from another pump“ error. Other history data like glucose, alarm, bolus etc works without showing an error. 
![666C4C6C-7DFC-4531-8C03-32D33ABBD7C3](https://user-images.githubusercontent.com/35224007/139532152-038ddbd2-b3c0-4345-97c4-a8104fdd19c6.jpeg)

[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/7446451/AndroidAPS.log)

**Comment by pbloom209** [comment]
Yes I am having the same issue

**Comment by MilosKozak** [comment]
resolved by https://github.com/nightscout/AndroidAPS/commit/bc14496cbd8dc3ea0478820c40c3498bcaa80a62
