### ISSUE TITLE
Engineering mode option to disable encryption for exporting settings is missing?

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#812]
**AndroidAPS 2.8.2.8-dev**
Build: 8fe7e7ce2
Flavor: fulldebug

**Problem description:**
Engineering mode option to disable encryption for exporting settings file seems to be missing?
Settings only shows "Email recipient" and "No of logs to send".

Is this a bug or intentional or did the option maybe move?

**Comment by MilosKozak** [comment]
unencrypted backups are not supported anymore
