### ISSUE TITLE
v3 beta 2 / Minor NotANumber bug

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#813]
Milos, you had solved the NaN bug (division by zero I suppose) but here it is in beta 2.

I installed v3b2 over 2.8.2.1 main this morning at 4AM. When I look at the stats 13 hours later, I see the NaN bug for the used insulin.

![Screenshot_20211030-172047_AndroidAPS](https://user-images.githubusercontent.com/76626474/139539397-edf0429a-0def-44ce-b2bf-73ac9cab9ec2.jpg)

Not sure if it is related : I tested something for @avereha before checking the stats. I had an active EROS and I changed pumps and selected and activated a DASH then changed pump again back to EROS.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/bb2fced905bb6a64cb0c26ae000aa96a0032a64d
