### ISSUE TITLE
Profile configuration: [Save] button appears when it shouldn't

### ISSUE THREAD

**Issue by rustymonkey** [nightscout/AndroidAPS#820]
The [SAVE] button sometimes appears when profile configuration is partly completed, and other times only when it is fully completed.

1 Delete all profiles and create a new one
2 Set DIA to 5.5
--> [SAVE] button appears even though all other profile attributes are unconfigured!
3 Set IC to 6.0
--> no [SAVE] button appears
This isn't that severe an issue, but it's confusing since the initial appearance of the SAVE button on the DIA screen implies that the profile can be partially saved (when the profile isn't conpletely configured), but on subsequent screens, the fact that a [SAVE] button doesn't appear implies that a profile cannot be saved unless it's completely configured.

Even stranger is that after step 3, if the user goes back to the DIA screen, the [SAVE] button no longer appears.

-------------------------------
Tested 3.0 Beta 2.

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/d53071297ee276caf897268e20451efe1a08a5af
