### ISSUE TITLE
3.0 beta2 Statistics screen stopped updating insulin amount

### ISSUE THREAD

**Issue by RalfCGM** [nightscout/AndroidAPS#823]
3.0 beta 2

Happened since 30 okt, don't know exact time. 

Statisticus screen does notr "updating" when selecting, nut doesn't show the right insulin amounts. Status for TIR do seem to be right. 

Somehow, since updating the log files aren't updated anymore, so can't provide logs. 

![Screenshot_20211101-083525](https://user-images.githubusercontent.com/15680598/139637577-46c09f8c-8c7e-4e9f-aefc-f3cff4ec0027.png)

Reporting bugs

**Comment by RalfCGM** [comment]
Now, after a reboot of the phone, or after some time (dont know what caused it) it looks like giving the right values. 
![Screenshot_20211101-115729](https://user-images.githubusercontent.com/15680598/139661706-cc5f2584-22de-467a-b05f-e7a23a339c63.png)

**Comment by MilosKozak** [comment]
If it works today it's cased by DST change

**Comment by RalfCGM** [comment]
Ive changed the time on my phone om the 30st, not the 31st. But  it's working today, so you might be right. Ill close this issue.
