### ISSUE TITLE
NSClient 3.0-beta2 profile sync problem

### ISSUE THREAD

**Issue by shafiro** [nightscout/AndroidAPS#828]
NSClient 3.0-beta2
Build: f49c93f22-2021.10.30-14:48
Remote: https://github.com/nightscout/AndroidAPS
Flavor: nsclientrelease
Nightscout version: 14.2.4
Engineering mode enabled
Device: Xiaomi MI 9, Android 11, MIUI 12.5.1

1. Profile is synced correctly from AAPS to NS.
2. Profile is not synced correctly from NS to NSClient.
3. Wrong profile name is shown on NSClient main screen (top left), but correct profile name shows on profile switch box.
3. BG is displayed in mmol/l, despite profile details shows units defined as mg/dl.
4. 3-line menu->Profile: shows profile in RED with "Error in ISF Values" despite all profile values including ISF are shown correctly.
5. Preferences->General->Units: None is checked.
6. After checking mg/dl, main screen becomes distorted for a short period, than shows values as they should appear. Also 3-line menu->Profile, shows profile correctly with no error. After a few minutes, all is back to as described on section 3-5 above.

Had same problem with 3.0-beta1
Tried Force stopping NSClient, Clear all data via android settings, delete app folders, reinstall.
Tried disabling/enabling sync from both AAPS and NSClient.
Could not find the cause.

[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/7452171/AndroidAPS.log)

![Profile is synced correctly to NS](https://user-images.githubusercontent.com/36660177/139653050-69774189-17ca-45d9-934b-e1177010d5d4.jpg)
![wrong profile name on main screen](https://user-images.githubusercontent.com/36660177/139653083-bc860d24-1795-476f-a041-21a6c1cc9473.jpg)
![correct profile name on profile switch box](https://user-images.githubusercontent.com/36660177/139653137-11504b31-501b-4b99-a63a-43b2b5c0231a.jpg)
![red profile page with ISF error](https://user-images.githubusercontent.com/36660177/139653286-c0dc387b-34e1-47a6-b91c-6be739e6968c.jpg)

![preferences units type none is marked](https://user-images.githubusercontent.com/36660177/139653394-32cac646-9011-41d8-a34a-23cf6c04a8e5.jpg)
![main screen distorded after selecting mgdl in preferences](https://user-images.githubusercontent.com/36660177/139653506-45fa55d0-9a64-4b07-b272-c6c16be339a6.jpg)
![profile ok after selecting mgdl in preferences](https://user-images.githubusercontent.com/36660177/139654382-b84f3393-1fc9-4c05-8cd2-2431ed9d7053.jpg)

**Comment by MilosKozak** [comment]
Unit settings is taken from AAPS preferences ... not from NS profile anymore

**Comment by MilosKozak** [comment]
pm me your NS address

**Comment by MilosKozak** [comment]
resolved in dev hopefully
you are running profile name Eitan which is not in profiles anymore
do a profile switch on aaps phone with existing profile
