### ISSUE TITLE
V3B2 and last dev : Missing BG dots on the graph

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#831]
It happened with V3B2 and in the last dev.
![Screenshot_20211101-192842_AndroidAPS](https://user-images.githubusercontent.com/76626474/139722172-e7c9fcb3-e6a6-4ad3-b1c7-3eb5e13b293c.jpg)

Sometimes, the left side of the graph has no BG points and then they appear next time I look at them... No idea what is the cause...

![Screenshot_20211030-175617_AndroidAPS](https://user-images.githubusercontent.com/76626474/139722386-2f73328f-254c-499a-abcb-b14556a48f5f.jpg)
![Screenshot_20211101-192558_AndroidAPS](https://user-images.githubusercontent.com/76626474/139722429-4f89cbe5-7d08-4bf9-9aad-2939aaf24bae.jpg)

**Comment by Philoul** [comment]
Do you see that after a long press on graph to change time range or at any moment (without doing anything else) ?

**Comment by Alamo04** [comment]
Confirmed.

For me, it was fixed after a few long press to the graph until comming back to the wanted time range.

**Comment by Alamo04** [comment]
This issue still happens. 

Most of the rime it works fine, but rarely it happens.

It was self fixed in active overview after 10 - 20 seconds. I think AAPS is loading data in that time.
