### ISSUE TITLE
[3.0 beta2] Omnipod Eros. Sms delivery issue - Polish

### ISSUE THREAD

**Issue by betees82** [nightscout/AndroidAPS#834]
AndroidAPS 3.0-beta2
Remote: https://github.com/nightscout/AndroidAPS
Build: f49c93f22-2021.10.30-12:09
Flavor: fullrelease
Nightscout version: 14.0.7
Engineering mode enabled

I'm not receiving bolus delivery reports if polish language is set. Problem disappears when language is switched to ENG.
I faced it also in 2.8 version.
![image](https://user-images.githubusercontent.com/60583387/139845450-f3abed5c-7407-4458-a02b-123605841019.png)
[AndroidAPS.zip](https://github.com/nightscout/AndroidAPS/files/7460558/AndroidAPS.zip)

**Comment by MilosKozak** [comment]
it's a bug in libraries but i made a workaround in AAPS https://github.com/nightscout/AndroidAPS/commit/e715167254a63c00f6577e8af3a83409e7778b4b

**Comment by betees82** [comment]
Thank you! I can confirm, 3b3 no issue with Polish

**Comment by betees82** [comment]
Now after switching to Dash, some minor SMS Issue. 
![IMG_20211107_155324](https://user-images.githubusercontent.com/60583387/140650128-aeeaeace-0cac-4498-8616-5e94081cb127.jpg)
