### ISSUE TITLE
[DEV 2.8.2.9] eCarbs shown in AAPS, but wasn't entered by myself

### ISSUE THREAD

**Issue by Alamo04** [nightscout/AndroidAPS#835]
Only a small issue.
After I forgot my phone at home and comming back after a hour, there are eCarbs (1gr per tick) in my AAPS overview.
I never forgot my phone before, so I never saw that.
Also the Alarm was running on the phone.

That seems to be ghost carbs, because they are only visible in overview, not in treatments, not in NS.
[AndroidAPS_LOG_1635943240758.log.zip](https://github.com/nightscout/AndroidAPS/files/7469233/AndroidAPS_LOG_1635943240758.log.zip)

**Comment by Alamo04** [comment]
![Screenshot_20211103-133913](https://user-images.githubusercontent.com/36486505/140103478-e89c058d-ecdb-4062-8441-4570eb0e0176.png)

**Comment by MilosKozak** [comment]
go to treatments - user actions
you will see all entered data

**Comment by Alamo04** [comment]
Oh.. so I did a mistake at 3::23AM in the night 10g over 10h.
But if that was the reason, the shown data are also incorrect.

Thanks Milos, that was my day of mistakes.  😀
