### ISSUE TITLE
Automations actions exceeding 'normal' limits can be enabled, but don't fire

### ISSUE THREAD

**Issue by rustymonkey** [nightscout/AndroidAPS#837]
When the user configures a rule that sets a Profile % out of range or beyond normal limits, the rule turns red.

The bug is that:
- If 'red' means that the rule is valid but beyond normal limits: the rule isn't firing
- If 'red' means that the rule is out of limits: it should not be possible to enable it

Repro steps:
- Import settings from 2.8.2. It contains an automation rule to increase profile % to 150% for 10m when BG > 15mmol
--> On the automation screen, the rule displays as red, but it's enabled. Since it's enabled, my interpretation is that this means that the rule is valid, but exceeds 'normal' values.
-  When BG > 15 mmol
--> The rule doesn't fire!

Tested on 3.0 beta 3.

**Comment by MilosKozak** [comment]
red means invalid rule and this is not executed until you fix it
added code to disable it https://github.com/nightscout/AndroidAPS/commit/0a798d1ea494be9f9e7136ccad177ff1a36ff309
