### ISSUE TITLE
[3.0-beta3] error importing NS profiles (worked in beta2)

### ISSUE THREAD

**Issue by hartlijn** [nightscout/AndroidAPS#839]
error importing NS profiles. 
right after installing beta3 (I came from beta2) below error popped up.

It is referring to the BG target that has a value of 5.6 in nightscout.
As a result profiles are not imported.

attached logfile. Error is at line:
10:55:09.896 [RxCachedThreadScheduler-2] D/NOTIFICATION: [NotificationStore.add():61]: Notification received: Invalid profile dana_mix_95RES not accepted from NS
![Screenshot_20211104-105518](https://user-images.githubusercontent.com/28272471/140295927-6aa25823-8d73-432a-aff3-0f608957e505.jpg)
![Screenshot_20211104-105526](https://user-images.githubusercontent.com/28272471/140295934-914da0dc-55ff-4a8b-9571-835dc97442ad.jpg)
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/7473964/AndroidAPS.log)

**Comment by MilosKozak** [comment]
pm me your ns address

**Comment by hartlijn** [comment]
> pm me your ns address

I sent it via FB Messenger. regards, Joost

**Comment by MilosKozak** [comment]
well it's a bug in NS profile (units are not explictly declared) but I made a workaround https://github.com/nightscout/AndroidAPS/commit/35c6ee38e5c8d55afd01be20e1999de939da4194
