### ISSUE TITLE
Notification received: Unsupported action in pump. Use AndroidAPS UI only!

### ISSUE THREAD

**Issue by stefanchavdarov** [nightscout/AndroidAPS#845]
That message appear in red as a notification.
18:44:51.690 [RxCachedThreadScheduler-3] D/NOTIFICATION: [NotificationStore.add():61]: Notification received: Unsupported action in pump. Use AndroidAPS UI only!

[AndroidAPS._2021-11-04_00-00-17_.2.zip](https://github.com/nightscout/AndroidAPS/files/7477007/AndroidAPS._2021-11-04_00-00-17_.2.zip)

AAPS - 3.0-beta3 
pumpType=DANA_R
Android 11, Samsung A72.

**Comment by MilosKozak** [comment]
good catch! this bug was there for years
fixed by https://github.com/nightscout/AndroidAPS/commit/0321d4cd07a098effe0470543714b53dcd44d90f
