### ISSUE TITLE
[3.0-beta3] Small fixes on the Treatments page

### ISSUE THREAD

**Issue by fjpezuela** [nightscout/AndroidAPS#846]
When entering the treatment page, some links are not displayed correctly in vertical view, as the text is too long (Spanish language). The only way to see it correctly is to change the position of the screen to horizontal. The date is not shown in all the events of the first option, only the time

Version: APPS 3.0-beta3

![image](https://user-images.githubusercontent.com/67511778/140406168-8ae041ca-e89b-4300-840c-47a327504ab4.png)

Sample of the problem

![image](https://user-images.githubusercontent.com/67511778/140405308-f1f69f28-5cdd-4adf-9c31-3f36eb0ca152.png)

When you are in any of the options marked in the red square and you turn the mobile horizontally, it automatically goes to the first option marked with an arrow. The option in which we are positioned is not maintained.

![image](https://user-images.githubusercontent.com/67511778/140405496-5491cca9-0d8a-41ea-9f1f-17d2e611bec9.png)

Thanks a lot for your support

**Comment by MilosKozak** [comment]
the problem is too long translation of IOB

**Comment by fjpezuela** [comment]
If that is. Is it possible that it shows in two lines like you do in the other options? Another option is to try to shorten the translation.

**Comment by MilosKozak** [comment]
what language is it?

**Comment by fjpezuela** [comment]
Spanish (Spain)

**Comment by MilosKozak** [comment]
i updated the translation
