### ISSUE TITLE
Profile and Dana-i pump IC settings have inconsistent precision

### ISSUE THREAD

**Issue by MichaelJohnSmith** [nightscout/AndroidAPS#848]
The profile editor allows setting of IC values in steps of 0.1 mmol/l
The Dana-i pump restricts IC to integer values

The values are rounded as expected.  A profile value of 5.4 sets 5 in the pump while a value of 5.5 sets 6 in the pump.

It would be preferable for the profile editor to be restricted to the precision available in the currently connected pump. 

Version 3.0-beta3 (but I suspect same in all versions).
Dana-i pump
Libre2 sensor via patched app and Xdrip+
Samsung A20e with Android 11

**Comment by MilosKozak** [comment]
saving IC, ISF supports only Dana-i and it's only fallback when you cannot use AAPS for calculation. In this case precision in pump is fine
This behavior is not gonna be changed, sorry
