### ISSUE TITLE
3.0 beta3 - homescreen doesn't update right

### ISSUE THREAD

**Issue by RalfCGM** [nightscout/AndroidAPS#853]
Weird issue with the homescreen. 

BG data is coming in. Calculations are being made, as is visible on the message / announcements screen, but on the aaps homescreen the data isn't updating, and time looks like running back. (amount of minutes of last bg reading is going up faster than the actual time). 

See screenshot and the timestamp of the screenshots.

Restarting aaps and clearing cache doesn't help. 

After 10 more minutes the issue disappeared. (last screenshot). 
![Screenshot_20211106-032304](https://user-images.githubusercontent.com/15680598/140594683-04360219-7484-48e5-a450-95d94beed25b.png)

![Screenshot_20211106-031353](https://user-images.githubusercontent.com/15680598/140594642-5c7e9cad-d0b8-4ee7-9f2a-c6edbd7f541e.png)
![Screenshot_20211106-031402](https://user-images.githubusercontent.com/15680598/140594644-7bfbd091-1cba-466a-a385-6dae05ba7884.png)
![Screenshot_20211106-031707](https://user-images.githubusercontent.com/15680598/140594645-e778a2b2-b16b-4b68-9d16-bfbcfaa014c0.png)

**Comment by RalfCGM** [comment]
[AndroidAPS._2021-11-06_03-12-13_.1.zip](https://github.com/nightscout/AndroidAPS/files/7489636/AndroidAPS._2021-11-06_03-12-13_.1.zip)
[AndroidAPS._2021-11-06_03-12-13_.0.zip](https://github.com/nightscout/AndroidAPS/files/7489637/AndroidAPS._2021-11-06_03-12-13_.0.zip)

**Comment by mick711** [comment]
Not à New issue i sera two ôther issue like this and i have this issue yesterday with thé last dev. Il seem that nobody would like to explain or solve this problem. If needed i have thé log files

**Comment by AdrianLxM** [comment]
@mick711 would you have a link to your GitHub issue please?

**Comment by MilosKozak** [comment]
turn on event logging and update to 3.0-b4 (or latest dev)
then provide logs again if the issue reappear

**Comment by RalfCGM** [comment]
I'll add that this issue seems to appear after missed readings.

Ill update to latest dev and see.

**Comment by RalfCGM** [comment]
Happening again on beta5. 
![Screenshot_20211109-192442](https://user-images.githubusercontent.com/15680598/140982783-877da618-fc1c-4285-babf-9e7b79e50503.png)
![Screenshot_20211109-192436](https://user-images.githubusercontent.com/15680598/140982785-bdf108c9-1113-448b-b881-ece37c93703f.png)
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/7507164/AndroidAPS.log)

**Comment by MilosKozak** [comment]
i revorked UI updating un dev 
will be in beta6 or current dev

**Comment by MilosKozak** [comment]
@RalfCGM how about beta6?

**Comment by RalfCGM** [comment]
Beta 6 doesn't work ok for me. See issue https://github.com/nightscout/AndroidAPS/issues/952

used beta 6 a short time (2 days) but reverted back tot master.

The time i used it the issue didn't appear.
