### ISSUE TITLE
AAPS 2.8.2.9-dev, Yellow Warning Triangle in Main Screen

### ISSUE THREAD

**Issue by Thomas-Wolff** [nightscout/AndroidAPS#855]
Since the update to AAPS 2.8.2.9-dev build 2b021ffaf I have a yellow warning triangle in the top left corner of the main screen and I have absolutely no information what this is supposed to signal.  AAPS runs without any problem.
I am not sure how far this is an issue, but I would appreciate any information about this.

![Bild2](https://user-images.githubusercontent.com/59526802/140603975-655cf594-9fcf-42fe-995d-26cc0c597d83.jpg)

![Bild1](https://user-images.githubusercontent.com/59526802/140603979-67d9b87a-d8e0-4a9c-8c30-51d30aca5959.jpg)

Best regards Thomas

**Comment by robertrub** [comment]
I didn't have it in the last build

![Screenshot_20211106-122233_AndroidAPS](https://user-images.githubusercontent.com/76626474/140607903-68bb1f53-88d4-4491-929d-125f1f1cb810.jpg)

Then I turned _ON_ backfill BGs from NS (I had only half the screen of the BG curve) and then I got the red triangle. I'm not sure if they are related. Un checking the _NS BG backfill_ did not make the triangle disappear.

![Screenshot_20211106-122345_AndroidAPS](https://user-images.githubusercontent.com/76626474/140607973-2f032f8c-82d8-43b7-a064-a4f081b438ef.jpg)

**Comment by MilosKozak** [comment]
https://www.facebook.com/groups/AndroidAPSUsers/posts/3115136028707793/?comment_id=3130352127186183&__cft__[0]=AZVxHcA30glk-Zd30GDgB95Ot_fZFVzhxb501quwrlOCHvdpDpA0PPEomprW8fbyrTOK7i1evSkbQM7NeYYLwiJSriiJOIKSNbuRbSM50b7G6cxynvt65fDEKtw2FO15VWjjwDCeoRZPdXjYdLmdj2IKWFcfNMvOXjXw4ToeGc6wbXGhipIIyN5TpMiRILzcwY0&__tn__=R]-R

**Comment by robertrub** [comment]
No FB for me (it is not possible to select _Do not use tracking cookies_ thus I refuse to use FB). What does the link says ?

**Comment by Alamo04** [comment]
That the triangle is intend.
It shows the quality of your bg data, if it goes to red closed loop will stopped.

Milos Syd there:
> there is new icon in 3.0-beta to report BG data quality. it looks like this. Yellow means data must be recalculated to 5 min interval, red means there are BG duplicates preventing AAPS from running in closed loop mode. If you are getting red one, see: https://github.com/nightscout/AndroidAPS/issues/689
https://github.com/nightscout/AndroidAPS/issues/772
