### ISSUE TITLE
Loop Disabled due to constraints

### ISSUE THREAD

**Issue by vanelsberg** [nightscout/AndroidAPS#857]
**AndroidAPS 2.8.2.9-dev**
Build: 2b021ffa
Flavor: Fullrelease

**Problem description:**
Getting RED warning icon in overview
Loop displays on the "Last run" field: LOOP DISABLED BY CONSTRAIMTS BgQualityCheck: Doubled values in BGSource

Per configuration, AAPS should ignore BG values from NS. _Only BG sources is xDrip as per configuration_

**Additional information**

- AAPS/NSClient is set to "Upload data to NS" (all other options switched "off")
- AAPS BG Source is set to xDrip+ (release version 2021.03.30, G6-client).
- xDrip+ is synchronizing with Nightscout, also sending BG values.
- No other sources are uploading to Nightscout

This configuration has been working for a long time.
_As BG sources for AAPS is set to "xDrip" I expect it to ignore BG values from NS (nor should it download anything else)_

But with the latest QulityCheckPlugin update (commit#2b021ffafc0c4f01df65b7dfe28c3d0e51cc088f) something changed making AAPS to decide disablling loop due to _BG values from NS_?

**Logfile:**
[AndroidAPS_LOG_1636205974971.log.zip](https://github.com/nightscout/AndroidAPS/files/7490608/AndroidAPS_LOG_1636205974971.log.zip)

**Screen-prints:**
![loop disabled](https://user-images.githubusercontent.com/45144129/140612793-968de1d9-9556-490e-874e-f6fd2ed139aa.png)

![urgent](https://user-images.githubusercontent.com/45144129/140612983-611d25db-3d29-4bee-97e2-17081e13cacc.png)

**Comment by vanelsberg** [comment]
Please also see my comments on
https://github.com/nightscout/AndroidAPS/issues/689?

**Comment by robertrub** [comment]
And the red triangle stays there even when _Backfill BGs from NS_ has been turned off. Closing AAPS, clearing cache memory doesn't get rid of the red triangle.

**Comment by Alamo04** [comment]
If that is an issue with latest dev, then the new BG Quality Check is possible the reason ?
https://github.com/nightscout/AndroidAPS/commit/2b021ffafc0c4f01df65b7dfe28c3d0e51cc088f

**Comment by RalfCGM** [comment]
Ive got the same issue. Loops isn't able to run. Data coming from xdrip. Bg Data table in xdrip and, bg data table in aaps doesn't show doubles.

**Comment by MilosKozak** [comment]
i made the triangel clickable in dev branch

**Comment by MilosKozak** [comment]
you may try update to latest dev and clear db

**Comment by vanelsberg** [comment]
@MilosKozak @RalfCGM I think the problem is cause by executing receive/backfill CGM data.
Both on AAPS and/or xDrip.
