### ISSUE TITLE
Dev DASH/ Pod inactivated by itself

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#858]
[AndroidAPS_LOG_1636205584466.log.zip](https://github.com/nightscout/AndroidAPS/files/7490643/AndroidAPS_LOG_1636205584466.log.zip)
Last dev version, using DASH pod

![Screenshot_20211106-122233_AndroidAPS](https://user-images.githubusercontent.com/76626474/140613469-1652533e-0cce-4adb-80cf-70e0c1ada21c.jpg)

I get a sound alert from AAPS, _pod is unreachable_ (phone was charging at 5m from DASH) at around 14:31. I mute the alert and wait for the pod to connect but nothing happens. I check and DASH has been suspended all by itself...

![Screenshot_20211106-143206_AndroidAPS](https://user-images.githubusercontent.com/76626474/140613558-c69b59de-c1b8-4b0d-ac6e-ae08b6b853fb.jpg)

Here is the copy of the alert

![Screenshot_20211106-153451_xDrip+](https://user-images.githubusercontent.com/76626474/140613587-ac38cd24-3053-45b4-b940-df50b492b22c.jpg)

The logs are above.

**Comment by avereha** [comment]
Do you have automation that updated the basal rates?

Updating the basal rates for Dash involves: suspend delivery, set a new basal rate.
In this case, the communication failed after the first step.

**Comment by robertrub** [comment]
Hi Andrei 

Yes, I have automation that change profile % if high delta or high bg.

The strange part is that, when phone and pod were near again, the connection didn't kick in and refreshing pod status did nothing either (if my memory is good...)

I had to "unsuspend" pod and then be zble to refresh.

**Comment by robertrub** [comment]
Sorry for the delay. I'm very late on everything at the moment...

I got the alert ringing on AAPS (Mute, wait 5 min etc). I muted it and tried to actualize the pump directly after that. 

The 15 minutes wait is not logical as the alarm that "pulls" the user to AAPS and s/he needs to silence it. I don't know why it didn't actualize. Is actualizing not possible if the pump is suspended ?

**Comment by avereha** [comment]
I think this can be closed after https://github.com/nightscout/AndroidAPS/pull/984
