### ISSUE TITLE
[3.0-beta3-4] Calculation error in Statistics

### ISSUE THREAD

**Issue by fjpezuela** [nightscout/AndroidAPS#859]
Insulin data count error in statistics section. In the TDD section it appears correctly.

The bug started in version 3.0-beta3. After I have updated to version 3.0-beta4 and the same error continues to appear.

![image](https://user-images.githubusercontent.com/67511778/140614889-4c30f8b5-5397-403e-92e3-dd1695d0f49d.png)

TDD:
![image](https://user-images.githubusercontent.com/67511778/140614917-0bb65956-df77-499d-9da6-0be05d5e70b3.png)

Regards, Fran.

**Comment by MilosKozak** [comment]
unable to replicate the issue
it seems to error in data
reset db
