### ISSUE TITLE
NSClient shows TBR in percents only. 

### ISSUE THREAD

**Issue by shafiro** [nightscout/AndroidAPS#860]
NSClient 2.8.2.9 dev
Build: f49c93f-2021.11.4-12:37
Remote: https://github.com/nightscout/AndroidAPS
Flavor: nsclientdebug
Nightscout version: 14.2.4
Engineering mode enabled
Device: Xiaomi MI 9, Android 11, MIUI 12.5.1

NSClient shows TBR in percent.
BR is shown in U/H.
AAPS shows both TBR & BR in U/H. 
![IMG_20211106_193453](https://user-images.githubusercontent.com/36660177/140618674-a6978e1e-d009-4c35-af72-e0f23564bf97.jpg)

**Comment by shafiro** [comment]
Similar behavior described in docs under
"AAPSv2 watchface - Legend", but not for NSClient. 

"G - basal rate (shown in U/h during standard rate and in % during TBR)"
https://androidaps.readthedocs.io/ko/stable/CROWDIN/ko/Configuration/Watchfaces.html#aapsv2-watchface-legend

**Comment by shafiro** [comment]
I have tested this with NSClient 2.8.2, which always showed TBR with U/H, and it also moved to "%".
So change is coming from AAPS or NS but not a problem with NSClient.

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/e14fc44957e2339d2c63726d548f144b0dd766e2
