### ISSUE TITLE
[3.0 beta4] can't change TBR -Dash

### ISSUE THREAD

**Issue by betees82** [nightscout/AndroidAPS#861]
NSclient 3.0-beta4
Remote: https://github.com/nightscout/AndroidAPS
Build: 9202b91c5-2021.10.30-12:09
Flavor: Nsclient
Nightscout version: 14.0.7
Omnipod Dash

[LOG7.txt](https://github.com/nightscout/AndroidAPS/files/7491478/LOG7.txt)
Can't change TBR via NSclient
Massage: Data from another pump. Change pump driver, to reset pump state.

Works with NSClient 2.8.2

![image](https://user-images.githubusercontent.com/60583387/140625750-d5e50fc6-6780-4373-ae83-c1afacad5300.png)

**Comment by MilosKozak** [comment]
you cannot set TBR from NSClient. with any version

**Comment by betees82** [comment]
No it looks like I'm not able to change TBR directly in AAPS. 
![Screenshot_2021-11-07-00-19-56-180_info nightscout androidaps](https://user-images.githubusercontent.com/60583387/140626896-85516d66-0555-4eb1-b1fc-2cc01cbd7d90.jpg)

**Comment by betees82** [comment]
[https://photos.app.goo.gl/hRDHGwdF3yCby6dj8](url)

**Comment by betees82** [comment]
TBR is not synchronizing to NSClient

![image](https://user-images.githubusercontent.com/60583387/140627489-f908c133-afb6-4861-a6ef-5e385609e1f3.png)

**Comment by betees82** [comment]
Looks like issue is with T:0,00 U/h
![image](https://user-images.githubusercontent.com/60583387/140636810-643365e5-6753-4439-81b2-84c622f3e28c.png)

**Comment by MilosKozak** [comment]
i improved TBR sync in https://github.com/nightscout/AndroidAPS/commit/e14fc44957e2339d2c63726d548f144b0dd766e2
