### ISSUE TITLE
[3.0 beta4] Sms delivery repport -Dash

### ISSUE THREAD

**Issue by betees82** [nightscout/AndroidAPS#865]
NSclient 3.0-beta4
Remote: https://github.com/nightscout/AndroidAPS
Build: 9202b91-2021.10.30-12:09
Flavor: AAPS
Nightscout version: 14.0.7
Omnipod Dash
[AndroidAPS._2021-11-07_00-30-53_.4.zip](https://github.com/nightscout/AndroidAPS/files/7492553/AndroidAPS._2021-11-07_00-30-53_.4.zip)

In Sms with Bolus report first value is 0.00 

Strange TBR time value

![image](https://user-images.githubusercontent.com/60583387/140651262-2cb9572c-d816-411d-87c3-8a91717cfe95.png)

**Comment by avereha** [comment]
The strange TBR is related to https://github.com/nightscout/AndroidAPS/issues/861
I'm still trying to understand how it end up in this state.
