### ISSUE TITLE
[3.0 beta3/4] QuickWizard editor end-time not displayed correctly

### ISSUE THREAD

**Issue by MichaelJohnSmith** [nightscout/AndroidAPS#866]
On editing an existing QuickWizard setting, the Start time is displayed in both start and end time fields.
If end time is edited, the new value is displayed in the start time field.  However, if editor closed with OK, the correct start and end times are shown in the QuickWizard List.

![Screenshot_20211105-175111_AndroidAPS 1](https://user-images.githubusercontent.com/55034864/140655949-7ba75151-8d2e-4396-b28a-452566d56e1d.jpg)

![Screenshot_20211105-175127_AndroidAPS 1](https://user-images.githubusercontent.com/55034864/140655939-5208341a-daa1-4cf6-a243-3812cc21cbe6.jpg)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/2b20aa3e38ca180d32c004130cb1a7e878d07beb
thanks
