### ISSUE TITLE
[3.0-Beta4] Duplicate entries/rows in Statistics page.

### ISSUE THREAD

**Issue by bchris21** [nightscout/AndroidAPS#870]
On Statistics Page, under Average (70-180) and Average (70-140) duplicate entries exist.

![Screenshot_20211108_003140.jpg](https://user-images.githubusercontent.com/4725280/140667931-5b3bd564-c021-4c91-a90b-ec18227154e4.jpg)

Steps to reproduce:
Enter Statistics page from 3ple dots menu on top right of AAPS.

Device: Xiaomi Mi6 (Android 9)

**Comment by MilosKozak** [comment]
it's ok. it's calculated for 7 and 30 days but with lack of data both are the same
