### ISSUE TITLE
[last dev] Crash during Carbs entries Calculator or Carbs button

### ISSUE THREAD

**Issue by Philoul** [nightscout/AndroidAPS#874]
I don't know if it's a side effect of https://github.com/nightscout/AndroidAPS/commit/dcf3c9cc57b0a2b63af9ee418dafee82fefef95b but this morning my carbs entered in CALCULATOR was not recorded in database (see screenshot and log) (First time I see missing carbs in database)
[AndroidAPS._2021-11-08_08-41-23_.0.zip](https://github.com/nightscout/AndroidAPS/files/7495715/AndroidAPS._2021-11-08_08-41-23_.0.zip)

![image](https://user-images.githubusercontent.com/52934600/140717535-7d4bacdc-6d46-4993-bbc3-0d83af81fcaa.png)

**Comment by MilosKozak** [comment]
there was a crash at 08:41:25.913

**Comment by Philoul** [comment]
Very strange in log file the line before crash is:
```
08:41:25.862 [main] D/PUMP: [OmnipodDashPodStateManagerImpl.load():665]: Creating new Pod state
```
Could it be the reason of the crash ? (How can I have this line (`Creating new Pod state` from Dash driver with an Insight driver selected...)

**Comment by Philoul** [comment]
Got a crash when I tried to manually enter Carbs from Carbs button with the same strange OmnipodDash line before

**Comment by Alamo04** [comment]
Confirmed, with dev from 00:12 AM
If I try to enter carbs, AAPS crashed, restarted and Carbs are not entered. Tryed again with same result.

**Comment by robertrub** [comment]
I confirm the missing carbs too @MilosKozak.
Latest dev built this morning

![Screenshot_20211108-093312_AndroidAPS](https://user-images.githubusercontent.com/76626474/140736283-1a3f6ddc-cbb2-416d-b731-5cee0f7c25d1.jpg)
 
At noon I use the wizard to calculate and inject my bolus. The insulin and the calc line are in treatments but not the carbs. I saw that something was wrong when my 2nd graph showed onlt IOB and no COB. I didn't have a crash.

![Screenshot_20211108-124006_AndroidAPS](https://user-images.githubusercontent.com/76626474/140736593-1f04d8a2-d12a-4523-a437-0d7f59b4a0f4.jpg)

![Screenshot_20211108-124036_AndroidAPS](https://user-images.githubusercontent.com/76626474/140736659-20fa61b0-b32a-4e31-a69b-21103abd9860.jpg)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/2a2bb4edc63df8fdb3cd05a17b1967c56babd604

**Comment by naromero77** [comment]
I had something like this happen today except it was with DASH pod and the 3.2.0-beta1. I will try to get logs and screen snapshots next time. I have been testing AAPS on and off for over a month for my son. First time such a thing happened.
