### ISSUE TITLE
[Insight] Wrong Extended TBR

### ISSUE THREAD

**Issue by Philoul** [nightscout/AndroidAPS#875]
I started to analyse log file, Real amount injected in pump was 0.08U and not 2.2U
It's seems that I recieved from pump a wrong "updated amount" (Very rare but probably an old bug I already noticed sometimes very high TBR in the past) (Amount sent 0.38U 30 min, Amount updated after 5 min 2.2U ????)

![image](https://user-images.githubusercontent.com/52934600/140718658-e4507da0-4b21-452a-9799-9cccfe641dc4.png)

```
06:13:39.146 [NSClientServiceHandler] I/DATABASE: [DataSyncSelectorImplementation.processChangedExtendedBolusesCompat():714]: Loading ExtendedBolus data Start: 2782 ID: 2783 HistoryID: ExtendedBolus(id=2783, version=0, dateCreated=1636348413139, isValid=true, referenceId=null, interfaceIDs_backing=InterfaceIDs(nightscoutSystemId=null, nightscoutId=null, pumpType=ACCU_CHEK_INSIGHT_BLUETOOTH, pumpSerial=33013206, temporaryId=null, pumpId=11901, startId=null, endId=null), timestamp=1636348411770, utcOffset=3600000, duration=1800000, amount=0.38, isEmulatingTempBasal=true) 

06:18:43.702 [Thread-8908] D/DATABASE: [PumpSyncImplementation.syncExtendedBolusWithPumpId():381]: Updated ExtendedBolus ExtendedBolus(id=2783, version=2, dateCreated=1636348723678, isValid=true, referenceId=null, interfaceIDs_backing=InterfaceIDs(nightscoutSystemId=null, nightscoutId=6188b203272eef00047368a5, pumpType=ACCU_CHEK_INSIGHT_BLUETOOTH, pumpSerial=33013206, temporaryId=null, pumpId=11901, startId=null, endId=11903), timestamp=1636348411770, utcOffset=3600000, duration=310654, amount=2.2018065114242855, isEmulatingTempBasal=true)
```
[AndroidAPS._2021-11-08_00-00-00_.40.zip](https://github.com/nightscout/AndroidAPS/files/7495867/AndroidAPS._2021-11-08_00-00-00_.40.zip)
[AndroidAPS._2021-11-08_00-00-00_.39.zip](https://github.com/nightscout/AndroidAPS/files/7495868/AndroidAPS._2021-11-08_00-00-00_.39.zip)

**Comment by MilosKozak** [comment]
it's a bug already  fixed in dev. but db record is broken.
use latest dev for aaps and nsclient
