### ISSUE TITLE
[AAPS3.0_beta5] NSClient - No Plot on Main Screen

### ISSUE THREAD

**Issue by old-square-eyes** [nightscout/AndroidAPS#881]
No plot after full sync with NS, no other metrics.

Creating new issue since quite a few things have been fixed/changed from the initial issue.

<img width="358" alt="image" src="https://user-images.githubusercontent.com/25760491/140845689-af5e451e-e1d8-4a7d-a5d2-6218d4afc198.png">

Data exists in history

<img width="352" alt="image" src="https://user-images.githubusercontent.com/25760491/140845638-114314c3-cd8c-4482-8bfc-efcdeb65837a.png">

**Comment by old-square-eyes** [comment]
Old issue: https://github.com/nightscout/AndroidAPS/issues/808

**Comment by MilosKozak** [comment]
NO active profile is the issue

**Comment by old-square-eyes** [comment]
@MilosKozak - I cannot set a profile. Please see #808, and your comment on https://github.com/nightscout/AndroidAPS/issues/807#issuecomment-962518009 - I believe you told me I cannot have an active profile. I have tried everything possible to set a local profile. It is not possible.

**Comment by old-square-eyes** [comment]
I think I must be missing something #808 even has a video posted of me trying to set a profile.

**Comment by MilosKozak** [comment]
we were already talking about it, didn't we? you must use full AAPS or PUMPCONTROL to create effective profile switch

**Comment by old-square-eyes** [comment]
@MilosKozak - so are you saying I cannot have a plot in NSclient, by itself?

**Comment by old-square-eyes** [comment]
I understood NSclient to be a standalone client... to visualise NS data and use care portal. Why do I need Pump control or AAPS to see the plot.

**Comment by MilosKozak** [comment]
bucause no other tool supports new features at the moment

**Comment by old-square-eyes** [comment]
@MilosKozak there seems to be a categorical misunderstanding here. Are you saying NSclient is no longer functional standalone?

**Comment by old-square-eyes** [comment]
If so, why am I spending hours testing it?
