### ISSUE TITLE
[3.0 beta5] Nightscout backfills CGM data with Feature set to OFF >> Red triangle

### ISSUE THREAD

**Issue by hartlijn** [nightscout/AndroidAPS#883]
option Receive/backfill CGM data is set to OFF.
I moved from Xdrip to DYODA dexcom app
I resetted my database >> zero CGM entries.
all goes fine with AAPS setting of Dexcom app 'Upload BG data to NS' to NO
with AAPS setting of Dexcom app 'Upload BG data to NS' to YES, the DXCM tab is getting filled with CGm entries from NS. I am sure they come from NS, since I just started de Dexcom app a few hours a go, while the backfilled data is older.

As a result I get a red triangle and the Loop cant be closed.

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/b9a3a72e863c05d8181746affcc69c2f456ce832
