### ISSUE TITLE
Loop status indicator fails to update on lost RileyLink connection

### ISSUE THREAD

**Issue by rustymonkey** [nightscout/AndroidAPS#884]
If the RL connection has been lost
--> Medtronic tab indicates that there's no connection to the Rileylink
--> Loop icon still displays as Green!

Tested as follows:
1 Removed phone away from RL and Pump
--> RileyLink unreachable message appears after 5m on Medtronic tab but loop remains green
--> This situation persisted even after 20 minutes -- it seems that as long as BG data was received, the loop was considered operational

What would be expected is that once the connection between AAPS and either the pump/RL or CGM is lost, the loop's status icon should be updated--preferably with a Red icon communicating that the loop is broken, and an indicator within showing for how long.

Tested with: AAPS 3 Beta 5, Medtronic 554, RileyLink, Android 11 (Pixel Experience) on a Galaxy S7

**Comment by MilosKozak** [comment]
there is no permanent connection between devices mostly. AAPS connects as needed.
and there can be only temporary connection outage
thus the only available alert is (and will be) pump unreachable after XX mnutes

**Comment by rustymonkey** [comment]
Is the situation for Medtronic/Rileylink different than for other devices? With Medtronic/Rileylink, outages do occur periodically, and they're communicated on the Medtronic tab e.g.:
Rileylink Status: Problem connecting to pump
Last connection: 57m ago
OR
Rileylink Status: RileyLink unreachable
Last connection: 1 hour ago

And while this is occurring, the loop status indicator is Green (unexpected)! In contrast, when I rewind the pump to refill the reservoir for a couple of minutes, the loop status changes to 'Paused' (expected). So doesn't it make sense for the Loop indicator to similarly update to reflect the status if the last connection was > X minutes ago?

Aside:
There are currently multiple different types of status/notifications that appear re. the status of the loop:
a) The Loop status icon
b) Red notifications that appear at the top of the screen
c) Failed to update basal notification dialogs
Using a red loop to convey connection problems could also yield the benefit of helping to standardize on a single method of communicating failed loop issues (i.e. always using a) as described in #885 rather than b) and c) ). e.g. upon a failed basal update, the Loop turns red and an alarm is generated. The user can then click the icon and observe the status/problem OR ignore the issue for 5 minutes and and if AAPS reconnects the status changes to green and there's no more problem of error messages persisting after the connectivity issues have resolved by themselves (as mentioned in #889 ).

**Comment by rustymonkey** [comment]
I wanted to summarize the benefits of fixing this, since in the course of testing #373 I came up against this issue again: 
a) As already described, it would give users an accurate sense of whether the loop has failed (since as described at #889 warning dialogs are a reflection of the fact that a disconnection occurred at some point in time--regardless of whether the loop failure has subsequently been resolved).
b) In addition, it lets the user know once the loop has resumed operating (e.g. if the user resets the RileyLink to solve the disconnection problem described at #373 ). 
It's true that in both cases, the user can visit the Pump tab to see the actual status, but that's a step that the UI shouldn't force the user to take.
