### ISSUE TITLE
[3.0-beta5] Broadcasting Treatments into xDrip+

### ISSUE THREAD

**Issue by reijoahola-nightscout** [nightscout/AndroidAPS#895]
I tried to test how Broadcasting treatments work in 3.0-beta.
Earlier issue for 2.8.2 https://github.com/nightscout/AndroidAPS/issues/504 seems to say that it works if NS connection is configured and working.

I have 2.8.2 system and know how to configure it and it works if NS connection works.
However, I could not see the treatments in xDrip+ in my test system. The problem has been in all 3.0-beta versions. 

Is it so that this feature is removed totally ?

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/88a8d08f5657805c7c68f36505387fc9f13c77a6
