### ISSUE TITLE
Medtronic tab initially renders the careportal [refresh problem]

### ISSUE THREAD

**Issue by rustymonkey** [nightscout/AndroidAPS#900]
When importing settings into AAPS 3.0, the pump tab initially renders the old careportal (or some variant thereof). The workaround to this is to either:
a) reconfigure the pump
b) in the Profile builder, disable visibility for the Medtronic tab, and then re-enable it
![Screenshot_20211110-123704_AndroidAPS](https://user-images.githubusercontent.com/34991028/141166693-1b7afc2e-a8c0-4312-8846-a5b950b4645e.png)

Tested AAPS 3.0 B5

**Comment by MilosKozak** [comment]
is the app restarted aftr you import?

**Comment by MilosKozak** [comment]
it happened to me too but currently i don't have solution. restart helps

**Comment by MilosKozak** [comment]
Closed for inactivity. Create new issue is if you still see the problem on latest branch
