### ISSUE TITLE
Maximum total IOB hard limit 

### ISSUE THREAD

**Issue by Bispham1983-bit** [nightscout/AndroidAPS#908]
AndroidAPS 3.0-Beta5
Build: 917de7261-2021.11.08-20:59

Maximum total IOB OpenAPS can't go over [U]" has a hard limit of 25 regardless of selected selected patient type.

![Screenshot_20211111-220002](https://user-images.githubusercontent.com/77126795/141375603-16455493-4c81-4413-84fc-f409bd992464.png)
![Screenshot_20211111-220047](https://user-images.githubusercontent.com/77126795/141375606-bb6e3483-f2b4-4aed-b65c-60742ea94606.png)

**Comment by MilosKozak** [comment]
max iob update accordinf to max bolus values
thanks
https://github.com/nightscout/AndroidAPS/commit/f067ff11099582f63f2b6e2bb9a4476cb94d70c8
