### ISSUE TITLE
AAPS shutting down and disconnecting from pump everyday at 3AM after 2.8.2.1 update.

### ISSUE THREAD

**Issue by GrapesGithub** [nightscout/AndroidAPS#910]
**Problem:** 
I have 2 kids on AndroidAPS and updated both from 2.6.1.2 to 2.8.2.1 a few weeks ago. After the update, only in 1 of the kids (the other one is fine… weird), I notice that almost every night, at around 3AM the AAPS disconnects from the pump and so it stays in open loop. I only figure it out either when I normally wake up or when her glucose gets out of the limits I set on Dexcom.

**My system**: 
Xiaomi 4x with android 8, accuchek combo and a Dexcom, and I get the glucose readings into the app through nightscout (not the Dexcom patched app)

**What I already checked/tried:** 
1) both AAPS and Ruffy are NOT on battery optimization. 
2) I left the phone charging all night and I still got the issue.

**Attached files:**
I attach hee logs of before the issue and recent ones. 
I also attach photos of how AAPS looks like as soon as I realize the issue, what I then do is refresh accuchek and restart the Nsclient and all goes back to normal.

Can someone help? Is there any detail you need from me to find the issue? I am out of ideas and I have no clue how to interpret the logs…

![AAPS1](https://user-images.githubusercontent.com/39673180/141442278-f731f8f8-9717-494d-9a83-de9129e386f9.jpg)
![AAPS2](https://user-images.githubusercontent.com/39673180/141442282-97835825-8f6a-446f-b369-317d776bbbd4.jpg)
![AAPS3](https://user-images.githubusercontent.com/39673180/141442286-05da0d8c-2e46-43d4-a688-15f07f4ee409.jpg)
[logsaaps.zip](https://github.com/nightscout/AndroidAPS/files/7526304/logsaaps.zip)

**Comment by MilosKozak** [comment]
disable play protect on your phone

**Comment by GrapesGithub** [comment]
Aha! Thank you. 
The play protect scanning time actualy matches the time of shutting down. I have disconnected and will revert back if it solved the issue. Thank you again

**Comment by GrapesGithub** [comment]
It's been 2 nights without the issue, so i guess it really was the play protect thing. Thank you so much for the help.
