### ISSUE TITLE
[3.0-beta5] Treatment tab IOB not green

### ISSUE THREAD

**Issue by chrisbev** [nightscout/AndroidAPS#913]
For me on the orange grain treatment tab with carbs and bolus has IOB but these are not green like IOB on other tabs. Samsung A41 Android 11.  See attached.
![Screenshot_20211112-170008_AndroidAPS](https://user-images.githubusercontent.com/43484095/141506601-2ce6bd3a-ac55-4f36-aa5d-be1aa16ded5a.jpg)
![Screenshot_20211112-144449_AndroidAPS](https://user-images.githubusercontent.com/43484095/141506635-60c90cb8-6724-4111-ad61-8042dad92024.jpg)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/EN/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/17630394c7331a2a20f85d79b475bcb148ca060a
