### ISSUE TITLE
Dana wrong password

### ISSUE THREAD

**Issue by ulastojak** [nightscout/AndroidAPS#919]
Hi 
I made update to version 2.8.2.1 and imported all previous settings from 2.6.2. but i'm getting info that password to pump is not correct and i can't make bolus. I have dana r pump and phone with android 11. My phone is connected to pump so password is correct and when i returned to 2.6.2 everything is working. Any ideas how to connect pump?
![Screenshot_20211113-100734](https://user-images.githubusercontent.com/56483408/141644815-dbe92843-16fd-4569-b10b-9d64b3ca5b23.png)
![Screenshot_20211113-100700](https://user-images.githubusercontent.com/56483408/141644819-758fbcf1-ec46-4bd9-b895-f9ea3a342221.png)
![Screenshot_20211113-100611](https://user-images.githubusercontent.com/56483408/141644820-da301ffc-32db-41ed-8c4b-3a2e382657dc.png)

**Comment by MilosKozak** [comment]
in 2.6.2 password was not verified for RS v1 pump. In 2.8.2 it is
did you read this? https://androidaps.readthedocs.io/en/latest/Configuration/DanaRS-Insulin-Pump.html

**Comment by ulastojak** [comment]
I have old Dana Diabecare pump. Not rs version
![Uploading IMG_20211115_150317710.jpg…]()

**Comment by MilosKozak** [comment]
then you  can use code (menu) 3463 to change user pass

**Comment by ulastojak** [comment]
There is no option of changing password on my pump. I found old chat with Paul Janiak from 2020 so i guess i have the same issue. Dana r from 2013 and can't change password with code 3463. New version of aps won't work without new firmware?


Paul Janiak @Pallesauka May 13 2020 09:32
My pump was Soo old that I could not change pump default password with the 3463 code. Had to change to a different DanaR with the v2 firmware to be able to change pump password. Now AAPS connects again
https://gitter.im/MilosKozak/AndroidAPS?at=5eb957e13f5b01031940146d

**Comment by MilosKozak** [comment]
i don't have so old pump to be able test it but generaly AAPS will work if you find the password
you may ask on FB group if someone knows or upgrade pump to v2

**Comment by Pallesauka** [comment]
I can confirm that after a certain AAPS version upgrade we could no longer connect using the default pump pairing password. I guess this was a safety feature that was introduced. It was also not possible to change password with the 3436 code in this old firmware. After firmware upgrade everything worked well again, i.e. It was possible to change pump password using 3436 code and AAPS connect without issues.
I suggest that you update the firmware version on your Dana R.

**Comment by MilosKozak** [comment]
one more option is search for password in log files

**Comment by ulastojak** [comment]
Hi Paul do you know how to update firmware?

**Comment by Pallesauka** [comment]
Ask around in the Facebook group. Some people have access to firmware update tools. Or, if you have a local Dana representative in your country they might assist you.

**Comment by ulastojak** [comment]
Hi. I contacted pump producer and they confirmed that it's not possible to change password on my pump. Is this pairing change really necessary in new version of aaps? Local distributor is still selling old pumps so buying new one is not an option, Dana RS is not available.

**Comment by qq254344379** [comment]
> I can confirm that after a certain AAPS version upgrade we could no longer connect using the default pump pairing password. I guess this was a safety feature that was introduced. It was also not possible to change password with the 3436 code in this old firmware. After firmware upgrade everything worked well again, i.e. It was possible to change pump password using 3436 code and AAPS connect without issues. I suggest that you update the firmware version on your Dana R.

Hello, how can I update Dana R firmware
