### ISSUE TITLE
[3.0-beta5] DIA increase for FIASP

### ISSUE THREAD

**Issue by chrisbev** [nightscout/AndroidAPS#922]
Request please to increase DIA limit from 7 to say 8/9/10? I feel the need to try 7.5 or 8 for FIASP and there are various other Facebook posts with people making code changes/edits of 9.

**Comment by chrisbev** [comment]
Workaround:  Anyone searching for a workaround it has been brought to my attention that a pregnancy increases the max DIA to 10! Not suggesting getting pregnant or any advice but I am trying a Fake pregnancy in my preferences!

**Comment by AdrianLxM** [comment]
I don't see any issues to set it to 10. The important part is that the peak is not off - and we restrict it in the settings to reasonable values.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/f800b85f62fcfcca955a83d972f20d853fc8afe0
