### ISSUE TITLE
[dev] Manual profile switches sent twice to pump

### ISSUE THREAD

**Issue by Philoul** [nightscout/AndroidAPS#939]
It seems to be a recent bug...

At 3:00:48 I installed a previous built done after https://github.com/nightscout/AndroidAPS/commit/081e8bd684632cfa795b68dd623f9663fe962d2d (10/11 9h24) and PS is sent twice to pump

Then I installed at 3:05:42 an older built done after https://github.com/nightscout/AndroidAPS/commit/22fced61fe72870f9891d2a9cada081a8d5244eb (08/11 13:37) and PS was sent only once to pump

Just one trial it can be luck...

![image](https://user-images.githubusercontent.com/52934600/141861010-aae813b9-fda0-4e94-bd24-ac281f4f7384.png)

**Comment by MilosKozak** [comment]
this is the reason. profile name checking 
 https://github.com/nightscout/AndroidAPS/commit/b4dec7195c028a987974eaf3a8e3ca0acc37929b#diff-7bb20fd96aa8b14c4f8761da416e727b07c4ab8cad22e8d4b9bea6aaf398b0cc

**Comment by robertrub** [comment]
Isn't this the same thing as https://github.com/nightscout/AndroidAPS/issues/827#issue-1040934646  ?

**Comment by MilosKozak** [comment]
i prepared a solution but i have to test it first

**Comment by MilosKozak** [comment]
it's a duplicate. this seems to independed to pump driver

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/f48dcc77e23d499ab0c1af8499ce9ce8ed574ba1
