### ISSUE TITLE
[dev] temp profile switch resets Autosense

### ISSUE THREAD

**Issue by hartlijn** [nightscout/AndroidAPS#941]
Dev version 2021.11.15

When setting a temp profile switch with end-time, Autosense gets a reset. I do see that after the temp profile the previous profile is set to active (without user action. the only user action was setting the 15 minute temp profile). Maybe that is handled differently than in Master; does the 'reactivation of the previous profile trigger the Autosense reset, while in Master that was not the case.

Expected behavior: a temp profile switch will not reset Autosense.
![Screenshot_20211116-101824](https://user-images.githubusercontent.com/28272471/141958648-72a7c91a-70f8-4169-a864-15a16d69f347.jpg)
![Screenshot_20211116-101903](https://user-images.githubusercontent.com/28272471/141958663-b49d3110-96a0-4229-862d-af2bb26f6660.jpg)
[AndroidAPS_LOG_1637054358950.log.zip](https://github.com/nightscout/AndroidAPS/files/7545040/AndroidAPS_LOG_1637054358950.log.zip)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/102f73fbc932b34100a956677853491accc9d5eb
