### ISSUE TITLE
[3.0-beta6] NSClient Crash on startup

### ISSUE THREAD

**Issue by shafiro** [nightscout/AndroidAPS#943]
NSClient 3.0-beta6
BuildVersion: ae52998d2-2021.11.16-21:20
Flavor: nsclient-debug/release
Nightscout version: 14.2.4
Engineering mode enabled
Device: Xiaomi MI 9, Android 11, MIUI 12.5.1

NSClient crashes on startup, a few seconds after logo shows up.

PlayProtect is Off.
Tried Uninstall, reinstall, force stop, clear data (android settings), delete AAPS folder, delete project folder, build from different pc.

Same crash with NSClient dev built 15.11, on Galaxy A10s SM-A107F, Android 11

NSClient 3.0-beta5 works on both phones.

[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/7549784/AndroidAPS.log)

[AndroidAPS1.log](https://github.com/nightscout/AndroidAPS/files/7549907/AndroidAPS1.log)

**Comment by streethawk22** [comment]
I have exactly the same experience...NSClient crash on startup...I have Galaxy Note10+. All others 3.0 Beta versions without Problems.

**Comment by shafiro** [comment]
@streethawk22
Please upload log

**Comment by streethawk22** [comment]
I can't now upload log, then when the App not starts,  she have's not the logs directory and I can't go to the App and Send Logs per Email.

**Comment by shafiro** [comment]
If you give storage permission via android settings, you will have the log.

**Comment by streethawk22** [comment]
Yes, this have I not tried...THX

Here is the LOG file.

[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/7554068/AndroidAPS.log)

**Comment by MilosKozak** [comment]
could you try dev?

**Comment by shafiro** [comment]
No more crash with current dev. thanks a ton!
