### ISSUE TITLE
Duplicate Glucose

### ISSUE THREAD

**Issue by pbloom209** [nightscout/AndroidAPS#944]
Dana I
Using Beta3 ver 6
Xdrip. but prefer Dexcom.
Everything was working properly.
Sensor fellout so I needed to insert a new one.
Immediately using Xdrip got duplicate glucose symbol.
Uninstalled Xdrip and installed Dexcom.
Still have duplicate readings.
Previously I fixed by resetting database.
Starting fresh without pulling in data from Nightscout.

![Screenshot_20211117-192300_AndroidAPS](https://user-images.githubusercontent.com/37948551/142164194-cd48f444-3b30-4e2c-8d1d-e971defda5ff.jpg)
![Screenshot_20211117-192318_AndroidAPS](https://user-images.githubusercontent.com/37948551/142164267-34d2a6c8-92f8-4f93-bf0e-ed0f30a80b53.jpg)
![Screenshot_20211117-192326_AndroidAPS](https://user-images.githubusercontent.com/37948551/142164283-fe2fc668-ff2d-42bb-8fa5-4e40644498f8.jpg)

**Comment by streethawk22** [comment]
Try to manual delete the duplicate BGs on AAPS, It can Help.

**Comment by swissalpine** [comment]
I've seen the same behaviour some days agos: After a Sensor Stop (Dexcom G6, xDrip+) all BG readings are duplicated. This workaround is a solution for the moment - but something strange happens ...

**Comment by MilosKozak** [comment]
it's a bug on xDrip side we cannot resolve. xDrip sends data from previous session with different timestamps
in release notes is already mentioned you have to switch to dexcom app and do not use xDrip+ as a dexcom collector for AAPS

**Comment by pbloom209** [comment]
I did also observe using Dexcom, the calibration entry flowed into AAPS and casued another duplicate BG, it was easy to fix as it was just one entry,

**Comment by MilosKozak** [comment]
@pbloom209 if this happen again please provide logs and timestamp of removed entry
