### ISSUE TITLE
 [3.0-beta6] No Messages but Alarm by empty Battery and empty Reservoir

### ISSUE THREAD

**Issue by 69nobody** [nightscout/AndroidAPS#948]
Please excuse my bad english.
Version Beta6
the reservoir is empty - but there are no messages only i hear a signal ton
the battery is empty - but there are no messages only i hear a signal ton
aaps show a red triangle on the left side on the top. when i push the triangle the following information was displayed.
Blood values are to near?!

**Comment by 69nobody** [comment]
addional the signal ton can only turn off when you restart your smartphone.

**Comment by MilosKozak** [comment]
what pump?

**Comment by 69nobody** [comment]
Dana i
should i send teh log files?

**Comment by MilosKozak** [comment]
when low battery or low reservoir accures aaps displays notification
pump will beep

**Comment by 69nobody** [comment]
I have seen no notification

**Comment by MilosKozak** [comment]
i tested dana-i and can confirm that pump is not sending notification to phone
but it beeps regulary
on AAPS side you'll see red status light for reservoir on overview

red triangel is related to bad CGM data
