### ISSUE TITLE
Lost carb entry by 2.8.2 after using calculator

### ISSUE THREAD

**Issue by mk886714** [nightscout/AndroidAPS#950]
I entered a meal of 24g carbohydrates using the bolus calculator.  As my blood sugar continued to rise over the next few hours, I noticed that the insulin release had been entered, but an entry for the carbohydrates was missing.  this set TBR0 and therefore the BZ rise.  maybe this should be tested somehow
![Screenshot_20211116-171707_AndroidAPS](https://user-images.githubusercontent.com/48983274/142479926-2c42d898-b01c-4436-94db-5c808bc262bf.jpg)
![Screenshot_20211116-171719_AndroidAPS](https://user-images.githubusercontent.com/48983274/142479939-4c159bd4-0b6a-4bfd-91a0-10a13d1775bd.jpg)
![20211117_091932](https://user-images.githubusercontent.com/48983274/142481851-c19a99c8-294c-444a-850a-a9f7877fff9a.jpg)

--------------

**Comment by mk886714** [comment]
![Uploading 20211117_091932.jpg…]()

**Comment by MilosKozak** [comment]
2.8.2 is at the end of it's life. there will no fixes added because code of 3.0 is by 50% new
test with 3.0 and open issue if it appears again

**Comment by MilosKozak** [comment]
thanks for reporting anyway
