### ISSUE TITLE
[3.0-beta6] SMB are converted to meal bolus on app restart

### ISSUE THREAD

**Issue by savek-cc** [nightscout/AndroidAPS#951]
When restarting AAPS (it's enough to end the app and start it again), all past SMB are converted to meal bolus in the graph.
AAPS 2.8.2.11-dev @ https://github.com/nightscout/AndroidAPS/commit/b2c12d233cb06313797a4e948552787eeb71740f etc. - pump is Combo, BG via xDrip+/G6 local broadcast.

Before app restart:
![Screenshot_20211118-213729_AndroidAPS](https://user-images.githubusercontent.com/13501427/142493333-8b93a029-9df1-4ab0-9a9a-8539b8a34a06.png)
After restart while still reading pump history
![Screenshot_20211118-213747_AndroidAPS](https://user-images.githubusercontent.com/13501427/142493330-1397855d-4ed9-4cb0-83be-a49d05174252.png)
After completing initialization
![Screenshot_20211118-213809_AndroidAPS](https://user-images.githubusercontent.com/13501427/142493335-1685954e-1db3-4512-ad0e-ca391548416d.png)

**Comment by MilosKozak** [comment]
guessing you have xDrip synchronized with NS

**Comment by savek-cc** [comment]
REST-API enabled, Send Display Glucose enabled, Download treatments enabled.
Wrong/incompatible settings?

**Comment by savek-cc** [comment]
AAPS NS client: upload enabled, download profiles enabled; all other options are disabled.

**Comment by MilosKozak** [comment]
my experinece is that xDrip modify data and send back to NS.
or better accepts data from NSClient (which is NS data aready) modify and upload to NS
this data is synced back to AAPS from NS and this leads to behavoir you observe now

**Comment by savek-cc** [comment]
But why does AAPS take anything other than the configured items from NS? I only enabled:
- upload
- download profiles
Why does that affect the type of bolus? Apart from profiles (which I could disable now as it's converted to a local one) AAPS should not be downloading/syncing anything from NS?

**Comment by MilosKozak** [comment]
hard to say and probably not a worth to spend time with digging in logs because in 3.0 this parts of code are completely new

**Comment by savek-cc** [comment]
? This is current dev - i.e. 3.0.

**Comment by MilosKozak** [comment]
ahhhh ok. then when this happen again upload logs pls

**Comment by swissalpine** [comment]
I see this too and don't upload treatments to xDrip+, only from AAPS to Nightscout and vice versa. Next time I restart the app will share a log.

**Comment by swissalpine** [comment]
Perhaps these are reimported from the pump. Because at first the triangles are visible, then, during the pump initialization, they disappear and numbers appear:
![Screenshot_20211119-161613](https://user-images.githubusercontent.com/12517693/142647003-8982c6da-b3ca-4843-af56-8e6d370e648b.png)
![Screenshot_20211119-161641](https://user-images.githubusercontent.com/12517693/142647089-8a32d33c-11d5-494a-82cf-14d8eddd9d51.png)

Log of the restart
[Log.txt](https://github.com/nightscout/AndroidAPS/files/7571214/Log.txt)

**Comment by swissalpine** [comment]
By the way: The message "Pump driver changed" isn't correct. Problem seems for me that the Omnipod driver is initialized (?) befor my real pump Spirit Combo.

**Comment by savek-cc** [comment]
It really happens on reading the pump history on app start. See two screenshots. First is before stopping AAPS - SMB all the way back to last night. Pump history (checked on pump) has entry 30/30 (oldest one) at 6:02.
After AAPS start, the SMB are first still visible as SMB - until the history is read from the Combo - at which point they are converted to regular boli. **But only the ones that are present in the combo's internal history**.
Screenshots and log attached.

![Screenshot_20211119-163141_AndroidAPS](https://user-images.githubusercontent.com/13501427/142649429-f45b2026-b9cf-4757-8d3d-5b60f1375999.png)
![Screenshot_20211119-163402_AndroidAPS](https://user-images.githubusercontent.com/13501427/142649434-dbbb7c43-f1fd-4d95-a02d-3bf41135d180.png)
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/7571290/AndroidAPS.log)

**Comment by MilosKozak** [comment]
it was combo specific issue. fixed by https://github.com/nightscout/AndroidAPS/commit/f5faa3492288b97b49284e116c29720f50194560
thanks!
