### ISSUE TITLE
Dev / BYODA v1.9 : Calibration in BYODA give double readings in AAPS

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#953]
![Screenshot_20211116-213207_AndroidAPS](https://user-images.githubusercontent.com/76626474/142583593-10c6d5bf-ceae-4562-8bfa-bf4c1c93d86d.jpg)

I have installed the new version 1.9 of BYODA. All was working OK till I got the red triangle when I calibrated this morning. I saw that in the Dexcom tab, there were 2 same readings at the time of the calibration

![Screenshot_20211119-074210_AndroidAPS](https://user-images.githubusercontent.com/76626474/142583813-4580eb04-49ec-4d39-98ef-48d26e1dbe6b.jpg)

![20211119_075028](https://user-images.githubusercontent.com/76626474/142583841-f35469f2-9555-4fce-b6b0-2455ddd2e75e.jpg)
 
Deleting of the readings cancelled the red triangle

[AndroidAPS_LOG_1637304353677.log.zip](https://github.com/nightscout/AndroidAPS/files/7568517/AndroidAPS_LOG_1637304353677.log.zip)
.

**Comment by MilosKozak** [comment]
2nd timestamp is not visible . do you still have it?

**Comment by swissalpine** [comment]
Could AAPS delete double entries when they come in (condition for example: (same bg, same delta, timestamp < 60 sec)?

**Comment by MilosKozak** [comment]
there is a wide range of CGM producing different data. so far i'm trying to find setup which doesn't produce duplicates instead of cheating/filtering on AAPS side (which may work for one CGM but not for others)

**Comment by robertrub** [comment]
> 2nd timestamp is not visible . do you still have it?

Sorry, nope. I hadn't realized that the text was longer than the windows. 

It could be better f the text was shorter and more explicit.... ;)

**Comment by vanelsberg** [comment]
I can see why upgrading BYODA could result in duplicates:
The new version does not have any history of it predecessor: it just read the memory of the transmitter containing several hours of BG data and dump all to APPS?

**Comment by robertrub** [comment]
@vanelsberg The duplicate issue I opened was for _calibration_, not for general use.

To answer your question: i changed from 1.7 to 1.9 towards the end of the 2h wait period (no BGs for 2h) of a sensor restart and I didn't have any duplicates.

**Comment by robertrub** [comment]
@MilosKozak  More testing on BYODA calibration (v1.9) : I did the same things at +3 min after last BG reading at at +4 min after last reading and the first did NOT give a double BG value and the 2nd did give a double value. Several messages on Discord gives the same impression of this bug being time related to the last BG reading.

Open BYODA by its own icon, calibrate in BYODA and see what happens in AAPS. The attached log with double BGs in AAPS. Look around 8:48

![Screenshot_20211204-084837_AndroidAPS](https://user-images.githubusercontent.com/76626474/144703079-8ab0de6a-cfe2-4863-9ba2-0f5b9f2f5326.jpg)


[AndroidAPS_LOG_1638604271854.log.zip](https://github.com/nightscout/AndroidAPS/files/7653603/AndroidAPS_LOG_1638604271854.log.zip)

**Comment by vanelsberg** [comment]
> ... trying to find setup which doesn't produce duplicates instead of cheating/filtering on AAPS side ...
How about implementing some threshold allowing "N" duplicates within a set time window (e.g 1h)?

This way it would allow casual duplicates caused by calibration or manually entering, but alert on multiple duplicates generated consistently (indicating some sort of automation or alternate BG source)
