### ISSUE TITLE
DEV/ BYODA v1.7 : CGM start date error in _treatments_ tabs

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#954]
I have restarted a sensor in BYODA v1.7. All went ok but I see here is a date error in one of the _Treatments_ tab (date 2106...) while on the other, the date is correct.

![Screenshot_20211116-213207_AndroidAPS](https://user-images.githubusercontent.com/76626474/142584446-33f2f713-8a2e-46e8-8891-d84f5af483b1.jpg)

![Screenshot_20211119-014129_AndroidAPS](https://user-images.githubusercontent.com/76626474/142584465-59c369d7-b1be-4394-9df5-1f1e6b23a0f1.jpg)
 
![Screenshot_20211119-014228_AndroidAPS](https://user-images.githubusercontent.com/76626474/142584488-142a05ad-d6e8-451f-9b1d-ad91b8e0f5be.jpg)

**Comment by MilosKozak** [comment]
session was started in BOYDA 1.9 and the downgraded to 1.7?

**Comment by robertrub** [comment]
No, sensor endod with v1.7, waited 15+ minutes then restarted with v1.7. Uninstalled v1.7 15-20min before the end of the 2 hour waiting time and installed v1.9 (didn't wan to clean too many duplicates if I was bitten with the problem).  First BGs arrived via v1.9 after the wait time finished.

**Comment by MilosKozak** [comment]
hmmm nobody knows what dexcom app does. aaps only accepts sent data. if they come with wrong timestamps ....
open new issue when this happen after you do whole procedure with 1.9
