### ISSUE TITLE
[3.0-beta5] Samsung M21 interchangeably doesn't see or cannot connect to Dash pod for activation

### ISSUE THREAD

**Issue by checkatillo** [nightscout/AndroidAPS#955]
I have a Samsung Galaxy M21 running Android 11 (March 2021 security patch level)
I've tried dash alpha before with no luck (though S9+ activated the same pod right away) and the same happens now on beta5
While pressing Retry the phone constantly gives me "No pods found to be activated" that is sometimes changed to it (supposedly) seeing the pod, trying to connect to it and then giving me "Failed to connect to the pod"
I was advised to see if the pod is visible from the phone by nRF and it was indeed visible and even showed the "Insulet corporation" as a manufacturer of the device.

I have a whole pack of dash pods and am able to provide more details if needed

[AndroidAPS_LOG_1637100842952.log.zip](https://github.com/nightscout/AndroidAPS/files/7571401/AndroidAPS_LOG_1637100842952.log.zip)

**Comment by avereha** [comment]
This not much we can do about this.
Please join the dash testing channel in discord and report this phone model as "not working with Dash".
