### ISSUE TITLE
Problems with NS Sync.

### ISSUE THREAD

**Issue by elgrupo123** [nightscout/AndroidAPS#964]
Removed treatment in AAPS is not deleted in NS and causes incorrect COB / IOB on the followers.

**Comment by MilosKozak** [comment]
version?

**Comment by elgrupo123** [comment]
3.0Beta6 + NS Client 2.8.2

**Comment by MilosKozak** [comment]
AAPS is ahead of NS in functionality. invalidated records are still accounted and displayed in NS.
for nsclient just update to the same version as AAPS and you'll see everything properly

**Comment by elgrupo123** [comment]
That was the mistake. It's going great again. Thank you for your great work!
