### ISSUE TITLE
Config UI: Pump unreachable threshold displays in the wrong location

### ISSUE THREAD

**Issue by rustymonkey** [nightscout/AndroidAPS#966]
In Preferences > Local Alerts > Advanced , there is an 'Alert if pump is unreachable' toggle. It has a corresponding setting 'Pump unreachable threshold [min]' but that's displayed below another setting instead of adjacent to the corresponding toggle setting
![Local-alerts-misplaced-config-entry](https://user-images.githubusercontent.com/34991028/142776318-a0512ea0-eaf3-4090-8025-cc2d63c4f063.png)
.

**Comment by MilosKozak** [comment]
agree https://github.com/nightscout/AndroidAPS/commit/8c1b4f7534096dcc36175310b394ce2232ada251
