### ISSUE TITLE
[3.0-beta6] Temporary profile % change - Autosens reset at end

### ISSUE THREAD

**Issue by kristinsmotz** [nightscout/AndroidAPS#971]
I noticed that when a temporary profile change ends, Autosens is reset to 100%. Previously in 2.8.2 this has not been the case. Is this an intended change in behaviour or an error? I had noticed that in 3.0 betas we get the "profile change" visible tagging of correct profile after the duration ends, but I was unaware it also reset autosens when that happens. 

If this is intended I will reconsider using %/duration profile changes as much as I had intended, especially with automation. 
I don't have the AAPS phone with me right now for logs, but here is a screenshot from NSClient. 
![Screenshot_20211122-104251_NSClient](https://user-images.githubusercontent.com/71758682/142839763-323b9c47-0bbb-4c90-8e34-ae542008593b.jpg)

As you can see, Autosens is quite high (158%) before the profile switch, and drops rapidly down to 100% when we went back to ordinary profile after using a 105% change for 10 minutes to test this theory.

**Comment by MilosKozak** [comment]
duplicate to https://github.com/nightscout/AndroidAPS/issues/941
