### ISSUE TITLE
[3.0beta6] AAPS stopped

### ISSUE THREAD

**Issue by chrisbev** [nightscout/AndroidAPS#972]
While waking at about 4:00hrs on looking at phone AAPS Started (may have been stopped) popped up and no BG were in the graph for about the last 40mins.
Previous interaction with AAPS: At about 2:30hrs I woke and noticed my BGs were running flat but above target with positive IOB.  Earlier the previous evening I was recovering from a period of high BG, faulty canular and FIASP water!  I did a temporary reduced target and a correction (using prime as IOB and running flat but high BG).
At and since 4:00hrs AAPS seems 'normal.
First 24hrs of beta6 so too early to see if a pattern but this has not previously happened with beta5 or 2.8.2.
Logs sent by email.
FSL2 patched Librelink xDrip Samsung A41 Android 11.
Just noticed xDrip did not have any BG for the 40mins prior to 4:00hrs which to me leads me to think it could be a phone problem or did say AAPS cause a 'phone problem?
![Screenshot_20211122-040442_AndroidAPS](https://user-images.githubusercontent.com/43484095/142842765-798071ba-910f-4b14-a455-5f583e4c8fc7.jpg)
![Screenshot_20211122-100831_xDrip+](https://user-images.githubusercontent.com/43484095/142842838-d1c85454-c02b-4cd0-9eee-0bfd8195a875.jpg)
![Screenshot_20211122-100848_AndroidAPS](https://user-images.githubusercontent.com/43484095/142842858-a32dc7bd-37a6-4bf5-9811-9b3d7bd135cc.jpg)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/EN/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
03:23:12.942 AAPS stopped
04:02:58.644 woke up

but no crash or reason visible in logs, sorry

**Comment by MilosKozak** [comment]
but seems to phone issue rather than AAPS because new BG would wake up AAPS
