### ISSUE TITLE
[3.0-beta6] Add Basal Daily Total to Profile

### ISSUE THREAD

**Issue by chrisbev** [nightscout/AndroidAPS#975]
Request that the total of the daily basal is added to the profile summary found by pressing the profile in the top bar of the home screen.
Reason: Other profile screens show the daily basal total and I find when checking that any basal changes I have made are correct the basal total is a good confidence, the other parameters are reasonably easy to remember but each of the 24 hourly values I find difficult.  When making changes I like to check back at that screen that the changes were implemented as I intended.
[3.0-beta6] Samsung A41 Android 11.

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/EN/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by Philoul** [comment]
See proposal in PR #978 (I added a screenshot)

**Comment by chrisbev** [comment]
Thanks @Philoul the screenshot looks great.  I expect it is very low risk but will try to build the PR soon...

**Comment by Philoul** [comment]
Oups, crash detected in CommandTempBasalPercent (strange because it's only when I disconnect pump)
