### ISSUE TITLE
[Enhancement] Add option of correction by % in Bolus Wizard

### ISSUE THREAD

**Issue by yossibivas11** [nightscout/AndroidAPS#977]
I suggest adding a correction by % in addition to the correction by U in the Bolus Wizard/ Calculator.

**Comment by Philoul** [comment]
Included in #300 
See also this issue and associated comments in previous repo MilosKozak/AndroidAPS#2462

**Comment by yossibivas11** [comment]
Looks like this won't happen anytime soon then
