### ISSUE TITLE
[3.0-beta7] Treatments screen issue

### ISSUE THREAD

**Issue by vmichalec** [nightscout/AndroidAPS#993]
Version 3.0-beta7

Hi, I noticed on treatments screen:
* on last tab there is an automation entry - temporary target to `5,0 mmol/L` but it is displayed as `90,0mmol/L`

And I suggest some enhancements:
* could we have there left/right swapping to switch the tabs as the main screen does?
* it would be nice on manual blood glucose entries to see also the value entered

![Screenshot_20211127-122608_AndroidAPS](https://user-images.githubusercontent.com/24793786/143679708-14f5aed1-377c-48ef-bc5f-1e15db6f8e9e.jpg)

After a time I can add screenshot where is (from the bottom) wrong automation target followed by manual target (this is ok). I have also NS Client (3.0-beta7) where I did set next target of 6.0 which is displayed wrongly with mg/dL.

After that I did some profile switches from NS client (seems ok) but after that there are many many entries in same minute (48 times), values seems in mmol/L but labeled with mg/dL.

![Screenshot_20211127-190215_AndroidAPS](https://user-images.githubusercontent.com/24793786/143716158-3c21be37-5db8-4233-a7a9-d9225545be06.jpg)

![Screenshot_20211127-190239_AndroidAPS](https://user-images.githubusercontent.com/24793786/143708081-6b71dc25-ba90-4156-9186-480327626a5e.jpg)

**Comment by Philoul** [comment]
@vmichalec can you please switch your phone in english and make the same screenshots (It will be easier for me to analyse).
(And while your phone is in english, can you send me the csv export too, I suspect some wrong convertion in it too, you can PM on discord if you prefer for csv file)
Thanks
