### ISSUE TITLE
[3.0-beta7] NS Client doesn't sync extended boluses

### ISSUE THREAD

**Issue by vmichalec** [nightscout/AndroidAPS#996]
Version `3.0-beta7` - booth aaps and nsclient, nightscout: `14.2.4`, Dana R pump

I noticed that at least the extended boluses tab of the treatments is empty on nsclient side. Check images bellow - left side is AAPS, right side is nsclient. The difference can be seen also on main graph of nsclient. And probably also `IOB` shown on nsclient is affected by this. Last screenshot is from nightscout where those extended boluses are also shown.

And another minor issue on nsclient side - I'm unable to hide the fiasp-oref insulin tab. It's not part of configuration as was in previous version.

![aaps_main](https://user-images.githubusercontent.com/24793786/143764975-5d178cae-ffe8-4f91-a823-e4c773aa2ac3.jpg) ![nsclient_main](https://user-images.githubusercontent.com/24793786/143764984-23bdd30b-ef3a-432b-9bfd-6c4386b3c524.jpg)

![aaps_treatments_extended](https://user-images.githubusercontent.com/24793786/143765052-a1dbf217-336d-4c42-a0be-9564208bd490.jpg) ![nsclient_treatments_extended](https://user-images.githubusercontent.com/24793786/143765059-a032174a-a016-4167-9937-d7a16c8f0c07.jpg)

![aaps_temp_basal](https://user-images.githubusercontent.com/24793786/143765068-a8dc3d5d-214f-4025-9928-ed081801edd0.jpg) ![nsclient_temp_basal](https://user-images.githubusercontent.com/24793786/143765074-dabfd240-cd11-4647-97fd-c34e1a9dc49c.jpg)

![nightscout_screen](https://user-images.githubusercontent.com/24793786/143765926-62e81bed-d7be-42bb-ad8c-024065ff0351.jpg)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/3739db489f47377021639474f79e7b06bbc57ce2

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/3ee1a3a9d806df84e0e559af40df1512586a085b
