### ISSUE TITLE
[2.8.2.13-dev] Pod failed with "Unknown Announcement" in treatments, and "set bolus" "command not sent" in pod history.

### ISSUE THREAD

**Issue by shafiro** [nightscout/AndroidAPS#999]
Galaxy S20 Plus.
Pod screamed 28.11@08:49 and had to be deactivated and replaced.
Treatments: "Unknown Announcement"
Pod history: "set bolus" "command not sen
![11del](https://user-images.githubusercontent.com/36660177/143857491-41144e96-03a9-4216-a360-47306b868906.jpg)
![12del](https://user-images.githubusercontent.com/36660177/143857538-e8ec03bc-6d5e-468c-a4d2-735658902d23.jpg)

[logs.zip](https://github.com/nightscout/AndroidAPS/files/7617718/logs.zip)

**Comment by avereha** [comment]
The logs are from 29.11.
Can you please add logs from 28.11?

**Comment by shafiro** [comment]
Happened again today. Logs attache
[info.nightscout.androidaps.zip](https://github.com/nightscout/AndroidAPS/files/7663323/info.nightscout.androidaps.zip)

**Comment by avereha** [comment]
I can't find it in the logs. At what time did it happen?

**Comment by avereha** [comment]
Suggesting to close this unless we find logs that contain the error.
